### ISSUE TITLE
3P Media: Add support for Openverse

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10002]
## Feature Description

[Openverse](https://wordpress.org/openverse/) is a collection of openly licensed content (under Creative Commons) [from various sources](https://wordpress.org/openverse/sources) (e.g. NASA, Wikimedia Commons, SpaceX, etc.). Currently the website only offers photos search, but the API also supports searching for video and audio (see also #8585)

We could consider supporting this service through the Google-hosted media3p API ([go/media-proxy-api](http://go/media-proxy-api))

## Additional Context

Openverse is part of the WordPress project as of recently and there are plans to have a direct integration with Openverse in WordPress core itself. When that happens, creators would likely want to have the same integration in the WordPress Web Stories editor.

Openverse API docs: https://api.openverse.engineering/v1/

**Comment by swissspidy** [comment]
cc @gajasinski @choumx for thoughts

**Comment by gajasinski** [comment]
Took a look at the website search ( i realize this only supports searching images for now) and the content quality is inconsistent, at times looking like someone's personal Flickr account.

Interested to learn more about the video and audio content and quality.

**Comment by swissspidy** [comment]
Good thing is that the list of image sources can be customized, so if we don't like the image quality from let's say NASA we can always exclude those.

Audio search is supposed to go live in January, will keep an eye on it.

**Comment by spacedmonkey** [comment]
There is an [API](https://api.openverse.engineering/v1/).

**Comment by swissspidy** [comment]
Yep, I linked to the API docs above already. The idea was to proxy access to the existing media3p API though since it requires an API key.

**Comment by gajasinski** [comment]
Keeping an eye on this to see the quality of audio/video that could be provided.

**Comment by swissspidy** [comment]
The beta launch of audio search UI is imminent, but it's already available via the API it seems

For audio, the following sources are used: Wikimedia Audio (random stuff, usually related to Wikipedia articles), [Jamendo](https://www.jamendo.com/) (music), and [freesound.org](https://freesound.org/) (random stuff)

Only Jamendo has some useful audio IMO (on freesound you can find stuff like the sound of a flushing toilet...), so here are some examples from there:

https://www.jamendo.com/track/15655/invisible-walls
https://www.jamendo.com/track/8561/distance
https://www.jamendo.com/track/26736/struttin
https://www.jamendo.com/track/35574/heavy-hopes

License seems to be either [CC BY-SA 2.5](https://creativecommons.org/licenses/by-nc-sa/2.5/) or [CC BY-SA 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/)

Some additional details:

Two of the [goals for the WordPress project in 2022](https://make.wordpress.org/project/2022/01/21/big-picture-goals-2022/) are to:

* Integrate Openverse into wp-admin.
* Integrate Photo Directory submissions into wp-admin.
