### ISSUE TITLE
Context Menu: Add functionality to clear text styles

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#10018]
## Feature Description

Text styles cannot be cleared because the menu item doesn't exist! The code has already been written to reset text styles to default but it's just not being applied to text elements.

1. Add the menu item `Clear text styles` for text styles and make sure that text styles can be cleared
2. Make sure text styles can be cleared when multiple elements are selected

## Additional Context

This came up in #9885 QA: https://github.com/google/web-stories-wp/issues/9885#issuecomment-995321400

**Comment by BrittanyIRL** [comment]
Hi @amovar18  - just noticed you picked this up, it's actually blocked at the moment.

**Comment by amovar18** [comment]
Hi @BrittanyIRL is this blocked because of the PR #9900 or is it for any other reason. If it’s any other reason should I close my PR?

**Comment by BrittanyIRL** [comment]
> Hi @BrittanyIRL is this blocked because of the PR #9900 or is it for any other reason. If it’s any other reason should I close my PR?

Great question, yes because of 9900 but also because it shouldn't need all of this and we'd rather have our internal team work through it to keep it aligned. Really appreciate you reaching out though.

**Comment by samwhale** [comment]
After a discussion with @agingoldseco and @BrittanyIRL it was decided that the 'clearing styles' actions are not necessary. This ticket will be closed, and another one will be added to remove that action from the right click menu.

Edit: #10293 is the new ticket.
