### ISSUE TITLE
Keyboard Shortcuts: Add "Shift + Arrows" to the shortcuts table

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10015]
## Feature Description
When using Shift with Arrow keys while focused on an element, the element moves by 1 step. This is not documented anywhere but is useful for positioning elements exactly next to each other.

We should add the following to the shortcuts table:
Keys: Shift + Arrows 
Description: Incremental nudge

Also add a test.

**Comment by miina** [comment]
@amovar18 Just saw you have already created a PR for this, would be great if you could confirm working on any issue before starting.

**Comment by amovar18** [comment]
@miina sure would ask before picking any future issues
