### ISSUE TITLE
Background Audio: Support non-looping audio

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10010]
## Feature Description

Some creators are using background audio to narrate the story.

They would like the page level background audio to be non-looping and to be considered for the "auto" page advancement calculation.

For this to work we'd need to:

* Store the audio length together with the URL when saving the audio
* Add background audio as an `<amp-video` element instead of with a `background-audio` attribute
* Update the advancement calculation to take into account the page background audio

## Additional Context

**Note:** narration also means there's a need for captions, hence the idea of using `<amp-video>` for audio. See #8821

**Comment by DanielCryptoK** [comment]
It has been over one month since this was requested and I see zero progress, even though you have just released the latest update. Please see how ridiculous it is to not have the ability to turn off loop by viewing my web story. https://bitcoin-casino-no-deposit-bonus.com/web-stories/decentral-games-review/

It has been a complete disaster for me adding these web stories, they are getting no traffic. I can not improve them until that feature is live so if you can please let me know as I may as well exit this over 1 year experiment with web stories that I am starting to regret doing. Do you think it is going to be beneficial for me to carry one creating web stories as getting no rewards back for them?

**Comment by swissspidy** [comment]
@DanielCryptoK This feature is actively being worked on and is slated for our next release as can be seen on our [public roadmap](https://docs.google.com/spreadsheets/d/10DZZrWJdkjcJXD1vL0VG0PqRhsIqaHkacF_ujOdEwJc/view)

**Comment by spacedmonkey** [comment]
> Update the advancement calculation to take into account the page background audio

Can you expand on this? 

Do we need a new attribute to background audio, loop and default to true?

What about legacy data? Could we make an api call to backfill audio track length?

**Comment by swissspidy** [comment]
> > Update the advancement calculation to take into account the page background audio
> 
> Can you expand on this?

We determine page advancement in this section here:

https://github.com/GoogleForCreators/web-stories-wp/blob/bb7e9775bd80e9663ffb5f29d305724470721517/packages/story-editor/src/output/page.js#L56-L70

When there is non-looping background audio that is longer than any other videos on the page, we need to change `autoAdvanceAfter` to that bg audio's video element ID accordingly.

This way the page will only advance once the background audio has finished.
 
> Do we need a new attribute to background audio, loop and default to true?

Yes.

> 
> What about legacy data? Could we make an api call to backfill audio track length?

Maybe. But best reserved for a separate ticket and PR. We can discuss this once we have the initial implementation done.

**Comment by spacedmonkey** [comment]
Maybe we should only show the looping checkbox if the audio length is present? Meaning on an existing story with audio already set, the loop option you would see it. But if you create a new story or remove & re-add the audio, the loop option would appear. What do you think?

**Comment by swissspidy** [comment]
Yeah that could be a good first step 👍

**Comment by spacedmonkey** [comment]
Should this be behind a feature flag?

**Comment by swissspidy** [comment]
We can use the same feature flag from #10288

**Comment by spacedmonkey** [comment]
Now that we have an option make background audio none looping, it means that the number of seconds a page of a story is displayed to a user, is the same length as the audio. So 30 second background audio, would mean the next page on auto progresses, is after the sound is complete. This means how long the audio clip is now pretty important. But this is not displayed to the user in the UI. Thoughts on adding it. 

<img width="301" alt="Screenshot 2022-01-25 at 17 49 58" src="https://user-images.githubusercontent.com/237508/151031483-6db056e8-d52a-402b-85e4-6ec339706c2e.png">


cc: @agingoldseco @aaskedall @swissspidy

**Comment by swissspidy** [comment]
Thanks for raising that; as mentioned in our chat today this is an opportunity to revamp the audio "player" experience a little bit.

Ideally we:

* Use the file's actual title if available (instead of the file name)
* Display the video length
* Link to the audio file so you could download it / listen to it outside the editor

**Comment by agingoldseco** [comment]
Questions: 

1. Does length of background audio only make the screen display longer or can it also cause it to be shorter than standard? 
2. Is there a time limit for uploaded audio clips? If so, do we cut them off or does the user have to before upload? 

Asking cause maybe there are a few other things we can smooth out. Otherwise, think the changes Pascal proposed are pretty simple to add to the UI.

**Comment by swissspidy** [comment]
1. Only longer. The page advancement works so that it advances after the longest media element has finished playing or after all animations have finished, whatever is longer. If there's no audio/video on a page, it advances after a fixed amount of seconds.
2. No. We don't.

**Comment by andrew-askedall** [comment]
This is great, I also think this is an opportunity to place the page duration in a more sensible place then under document settings.

**Comment by swissspidy** [comment]
Yeah maybe but that definitely warrants its own separate ticket / discussion.
The page advancement setting under the Document panel affects the whole story though, so it makes sense there.
