### ISSUE TITLE
Code Quality: Refactor `setOrCreateImage` function

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10025]
## Feature Description

Currently the `setOrCreateImage` is a little messy and the code is unclear. It has the following issues. 

- It creates a hidden dom element when it doesn't need to. 
- It is not async code. 
- It passing functions again. 
- Needs better jsdocs.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10100.

1. Created a new story
2. Added a solid color to the background
3. Added a text
4. Changed text color to the same as the background
5. Check accessibility message

![accessibility](https://user-images.githubusercontent.com/96055551/148999611-51d801c1-8792-4dd1-9387-1a5a8e1cf9a4.png)
