### ISSUE TITLE
Custom Fonts: allow linking from any public URL

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10021]
## Feature Description
Currently, many URL's don't work with the Custom Fonts implementation due to CORS issues (related to the Video Optimization feature).

For handling hotlinking Media, a server-side proxy was created, we should figure out an approach for the fonts as well.

**Comment by miina** [comment]
@swissspidy Here as well -- not sure if this will be for Infra / Prometheus, assigned both until we get clarity.

**Comment by swissspidy** [comment]
I'm not sure how feasible this is...

The proxy is intended for use in the editor. If there are also CORS issues for fonts on the frontend when viewing the story, that CORS proxy would not help there.

Publishers should really just set CORS headers for their fonts. IMO we should make that mandatory.

cc @choumx

**Comment by dreamofabear** [comment]
+1, we should respect CORS e.g. for publishers/hosts that don't want to proliferate their fonts. 

Is the intent here to handle font URLs with CORS issues? If so, we should detect if that are CORS issues when a new font URL is added (like we do for hyperlinked images) and display an error message to the user.

**Comment by miina** [comment]
> The proxy is intended for use in the editor.

Hm, okay, perhaps I misunderstood but I thought we currently had the issue of not being able to fetch URLs in the editor (or Dashboard, thus not being able to get the font metrics) due to the Video Optimization feature, as it was in case of media, but still would be able to display those in the front-end -- is that not the case?

If that's not the case then we can probably close this issue, or convert it to an issue for providing more details about setting the CORS headers, currently the message we display is just this, probably could be improved post-MVP:
`"Please ensure correct CORS settings for allowing font usage on this site."`

**Comment by dreamofabear** [comment]
Yea, I'd expect fonts to have appropriate CORS headers set. IIUC, images don't require CORS because they were grandfathered in before CORS itself proliferated.

https://stackoverflow.com/questions/33208474/why-do-font-files-have-to-abide-by-cors-rules-but-images-dont

**Comment by miina** [comment]
Thanks for the link, closing the issue.
