### ISSUE TITLE
Social media embed function in the editor 

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#10046]
## Feature Description

One user on the support forum has asked about the possibility of having a social media embed function in the Web Stories editor for Instagram, TikTok, YouTube etc. 

This could work in a similar way to the embedding of third party images/videos.

## Additional Context

Support topic: https://wordpress.org/support/topic/instagram-twitter-embeds/

**Comment by swissspidy** [comment]
AFAIK the web stories format currently only supports embedding tweets.

cc @gajasinski for consideration.

**Comment by gajasinski** [comment]
Going to bring this up to the format team for consideration

**Comment by gajasinski** [comment]
Can keep this at the current priority.
