### ISSUE TITLE
Performance: pageHash memoization

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10054]
It seems that `pageHash`, which is memoized and stringify-ing `currentPage` is getting called about 40 times per each actual update to `currentPage` resulting in an excess of components receiving updates. Let's fix it!

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10044.

Retested all main functionalities (upload, drag and drop, publish, preview, text, images, videos, gifs, etc...). No impact.
