### ISSUE TITLE
Deduplicate Popup 

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10089]
Noticed in review of #9944 that we still have 2 `Popup` components (one in the design system and one in the story-editor), these are nearly identical and combining them would be a nice clean up. 

## Acceptance 
- no regressions in used popups
- Popup component lives in Design System

**Comment by amovar18** [comment]
@BrittanyIRL Can I take this?

**Comment by swissspidy** [comment]
I think so yeah! Let us know if you need any help

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL Can I take this?

If you are working on it, please do update the status of the ticket so that nobody else starts on it.

**Comment by BrittanyIRL** [comment]
## Testing 
Unfortunately, the Popup in the design system touches a bunch of stuff. Verifying that combining the popup into one central location means regression testing the following - that these all behave the same in #10460 as on staging in both LTR and RTL. 🥵 

Tooltip behavior (be mindful of tooltips that change location when a button is interacted with while they are open - like locked vs unlocked), scroll, when expected space isn't available)
Drop downs
Editor: style presets, color input, play pause button, links in canvas
Dashboard: stories view tooltip toggle

**Comment by felipebochehin87** [comment]
Tested locally against my local instance, after downloading and installing https://github.com/GoogleForCreators/web-stories-wp/files/8025263/web-stories-1.18.0-alpha.0.zip

Tested scenarios below (both RTL and LTR):
1. Added images
2. Added text
3. Added videos
4. Added gifs
5. Added shapes
6. Used color picker
7. Added links
8. Right clicked on elements
9. Play/pause videos
10. Tooltips on hover over buttons/items
11. Dropdowns (date and time to publish)
