### ISSUE TITLE
Media: Drag and drop video in safari not working

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10098]
## Bug Description

Dragging and dropping a video onto canvas in Safari does not upload the video. However dragging image into canvas does work. 

## Expected Behaviour

On dragging video into canvas, it should upload. 

## Screenshots

https://user-images.githubusercontent.com/237508/148226381-9693c062-a934-4bb1-97e7-30a6271df492.mov

## Additional Context

- Plugin Version: 1.15.1
- WordPress Version: 5.9-RC1
- Operating System: Mac OS 11.6
- Browser: 15.1

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10125.

1. Dragged and dropped videos, images and gifs into Canvas in Safari ✔️ 
2. Dragged and dropped videos, images and gifs into Canvas in Chrome ✔️
3. Dragged and dropped videos, images and gifs into Canvas in Firefox ✔️
