### ISSUE TITLE
Media: Base color generation incorrect

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10099]
## Bug Description

Sometimes, when generating base color, a previously generated color from another image is used. This is because, the existing implementation reuses a existing image tag to generate base color. This issue was explored in https://github.com/google/web-stories-wp/pull/10022, there the issue was found to be that image tag was being reused. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Isn't there now some overlap with #10025? We might want to combine them.

**Comment by spacedmonkey** [comment]
Forgot about that ticket. Closing in favour #10025
