### ISSUE TITLE
Bump PHP version requirement to 7.2+

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10094]
## Feature Description

Last summer we changed the minimum version requirements for the WordPress plugin from PHP 5.6 and WP 5.3 to PHP 7.0 and WP 5.5, respectively. See #7551 for background.

The current telemetry numbers are promising enough that we should look into bumping the PHP version requirement even further.

Excerpt of telemetry data for the Web Stories plugin from our own analytics:

<table>
<tr>
	<td>PHP Version
	<td>Percentage (rounded)
<tr>
	<td>7.0
	<td>0.4%
<tr>
	<td>7.1
	<td>0.3%
<tr>
	<td>7.2
	<td>4%
<tr>
	<td>7.3
	<td>16%
<tr>
	<td>7.4
	<td>69%
<tr>
	<td>8.0
	<td>7%
<tr>
	<td>8.1
	<td>0.1%
</table>

The highlights:

* Less than **0.4%** of users are on PHP 7.0
* Less than **0.3%** of users are on PHP 7.1

PHP 7.2 usage is still reasonably high, so my takeaway is to **bump the minimum version requirement to PHP 7.2**.

This would allow us to use more modern techniques in PHP development and drop some old baggage.

It would also make our build tooling a bit easier to maintain, since we currently install PHP-Scoper, PHPStan and others via `civicrm/composer-downloads-plugin` since they require newer versions of PHP, accumulating quite a few workarounds to make things work on PHP <7.2.

Composer 2.3 will also increase the required PHP version to >=7.2.5, see https://blog.packagist.com/composer-2-2/

As for PHP-Scoper, it means we could even switch to the current `dev-master` version of it which makes our config a little simpler. See https://github.com/humbug/php-scoper/issues/303

**Comment by spacedmonkey** [comment]
+1 to this. 

Recommended version of PHP is 7.4. See https://wordpress.org/about/requirements/. There has also been talk, for some time about upping in the min version to PHP 7.2. But with the pandemic, this conversion seems to gone a little quite.

**Comment by spacedmonkey** [comment]
I wonder if we should look at https://github.com/GoogleForCreators/web-stories-wp/issues/7754 again?
