### ISSUE TITLE
UI Simplification: Add rotate handle

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10105]
## Feature Description
Add an icon for the rotate handler instead of just a filled circle.

See [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11122%3A445797)

## Additional Context
<img width="373" alt="Screenshot 2022-01-06 at 11 36 59" src="https://user-images.githubusercontent.com/3294597/148362031-a78cf800-7290-4cb8-b423-b8d4dd9231eb.png">

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10159.

1. Added an image, a gif and a video to the canvas and clicked on them - rotation icon is displayed
2. Rotated image, gif, video - working as expected
 
![rotate](https://user-images.githubusercontent.com/96055551/149395044-bfd824bf-8f2c-456a-8178-5e3e5707c842.png)

![rotate 2](https://user-images.githubusercontent.com/96055551/149395228-a26e5f27-d5c8-4f86-aab9-3f88d956741e.png)
