### ISSUE TITLE
UI Simplification: Unlock corners of rectangles and images when resizing

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10106]
## Feature Description
Currently, the ratio of rectangle shapes and images are locked when resizing from the corners. 

Note: this is for single selection only.
- [ ] For single selection: use the aspect ratio lock based on what's set in the design panel. E.g. if the ratio is locked there, also lock it when resizing the element (no matter from where)
- [ ] Unlock the ratio by default for images and rectangles
- [ ] For text element, continue to only allow resizing from the corners and use the "Auto" height for unlocked state.
- [ ] When "Shift" is held, the ratio is locked, no matter the setting in the design panel

**Comment by andrew-askedall** [comment]
The user can either press shift or press the lock in selection to lock the ratio.

**Comment by miina** [comment]
@aaskedall Currently, the lock in the design panel and the way how the selection box work are not related.

The lock in the Selection panel is for the inputs only and does not influence anything else, it only influences how the user can interact with these specific inputs it's tied to. The selection box works so that resizing from the corners has ratio locked, resizing from any sides is not ratio locked (independent of the lock of the design panel inputs). It's like this for all the elements except for text which can always be resized from the corners only (since we adjust the size automatically to make the font fit well).

Is the suggestion that we should change this? I thought we're only changing the Selection box resizing behaviour. If we're relating the design panel and the selection box resizing, it would be good to review and change this for all the elements, not just media and rectangles, to make it consistent.

**Comment by andrew-askedall** [comment]
Ah, I did not test this out because I assumed it's how it worked based on using other applications. I think they should be related for all selectable objects. If we do that and turn off ratio lock by default I think that will make the experience a little ore intuitive.

**Comment by miina** [comment]
@andrew-askedall Alright, confirming just in case:
If the aspect ratio is locked in the Design panel, it will now mean that resizing from any side of the Selection box (including the edges, not only the corners) will still keep the ratio, is that correct? (Previously corners always kept the ratio but edges not). And if the ratio is unlocked in the design panel, ratio is not kept, no matter where it's resized, corners or edges.

**Comment by andrew-askedall** [comment]
yes, that is correct. I believe this pattern is quite common in other editors. If it's unlocked by default this should not be too difficult. Holding shift while resizing should maintain the ratio of a shape or media element.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10370.

- Resize works for images, shapes, stickers, videos and text box;
- Tested locked ratio;
- Tested unlocked ratio;
- Tested ratio for stickers (always locked, never unlocked);
- Tested on Safari, Chrome and Firefox.
