### ISSUE TITLE
UI Simplification: Allow changing background media from the panel

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10108]
## Feature Description
See [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11122%3A447721)

We will be using the design with button "Replace".

Currently, the background media can be replaced by dragging a new image onto the Page, or by clicking "Set as background" while having another media element selected.

We should allow doing it directly from the Page Background panel as well.

- [ ] Add a new "Replace" button.
- [ ] This button will open Media library to replace the background media

**Comment by andrew-askedall** [comment]
![image](https://user-images.githubusercontent.com/6991691/148608886-8b19cfe5-5b78-4fd1-b1a8-90585ed629cb.png)

Let's use this button! thanks @miina

**Comment by miina** [comment]
@andrew-askedall One note about the Removal button's style. Currently, only the `X` is really a button -- in Figma, the existing Removal button looks fully like a button though. It happened once before with UI Simplification vol 1 that the button was changed in Figma like this, however, it was confirmed with Amy that it was by mistake and it should stay as it is now.

Keeping it as it is currently, let me know if we should change it.

**Comment by agingoldseco** [comment]
Just saw the comments in Figma—"Replace" seemed more obvious but given the points you brought up it would be okay to use this button instead!

<img width="552" alt="Screen Shot 2022-01-10 at 10 19 55 AM" src="https://user-images.githubusercontent.com/90645922/148790660-157e211c-236a-46e3-b6d0-4ba6413e2112.png">

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10134.

1. Visited URL above
2. Selected PR above
3. Started a new story
4. Added an image as background
5. Clicked on the background - upload button is displayed under Page Background section
6. Button works as expected
7. Existing button to replace background (beside the canvas) working as expected too

![image](https://user-images.githubusercontent.com/96055551/149131126-a0959031-1ce9-4f6d-bc0e-7b177ba40348.png)
