### ISSUE TITLE
UI Simplification: Move the right sidebar functionality to the left sidebar as tabs

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10111]
## Feature Description
See [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11122%3A447794)

- [x] Add additional tab row to the left sidebar to the top with the functionality of the right sidebar. The new tabs are: Insert (previously the whole left sidebar), Style (previously the Design tab), Document (previously the right sidebar Document tab).
- [x] Adjust the whole grid of the editor to match Figma and use the space of the right sidebar for the workspace. Move the Page and the top buttons accordingly.
- [x] Ensure the highlighting system and the quick-action menu still work as expected.

For now, don't change anything else in the content of the panels, even if it is so in Figma -- these will be followed up in separate issues.

## Additional Context
<img width="613" alt="Screenshot 2022-01-06 at 13 14 57" src="https://user-images.githubusercontent.com/3294597/148374634-14dca286-a051-47a1-8f2a-3073e1169df1.png">

**Comment by agingoldseco** [comment]
The bottom bar is correct—I'll go through and fix those in the doc. However, there is more to think through to get combining the right and left panels just right and I'll be working on that for a lot of this week. I would start on the more ready tickets first and I'll keep you posted on progress.

**Comment by miina** [comment]
@agingoldseco Alright, thanks for the update, I understood from Slack conversation that not much should change anymore. Please let me know once the final version is ready.

**Comment by bmattb** [comment]
@merapi Infra pod has flagged that E2E tests will require updating in support of this UI change.

**Comment by miina** [comment]
Closing as this part got fixed (there's an epic now combining all the Sidebar issues: #10817)

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10931.

Regressed all functionalities, side bar works fine RTL, LTR, Safari, Chrome, Firefox. Text, videos, images, animations, subtitles, audio, shapes, editing, publishing, preview, etc...

**Comment by BrittanyIRL** [comment]
Thanks @felipebochehin87  I know that was _alot_
