### ISSUE TITLE
UI Simplification: Base structure/architecture for Floating element menu bar

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10112]
## Feature Description
See [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11394%3A457049)

Full Todo list:

- [x] Add this behind a Feature flag to release together with #10111 
- [x] Add a floating menu bar that is opened by default.
- [x] When closing the menu bar, it can be opened again by re-selecting the element, it will always be open for the element that gets selected.
- [ ] Add items to the menu bar based on Figma -- these will not be links as in quick-action menu but can be directly edited from the bar.
- [ ] Note: Border and Corner inputs are only displayed when locked. If unlocked, don't display these in the menu.
- [ ] When clicking on "More" button, it will open and highlight the Design Panel
- [ ] Use flyouts as in Figma
- [ ] Replace button for media edit bar -- replaces the media, keeping other props the same as possible.
- [ ] Remove duplicates from the quick-action menu.

Duplicated to remove:
- From text element, remove: Change Color; Edit Text
- From shape element, remove: Change Color
- From video, remove: Trim

The remaining work has now been moved to a number of child issues:

- #10624
- #10625
- #10626
- #10627
- #10628
- #10629
- #10630
- #10631
- #10632
- #10633
- #10634
- #10635
- #10636
- #10638
- #10639

**Comment by agingoldseco** [comment]
I've been thinking about the issue of needing to access something just under the bar—would it be possible to make it moveable?

**Comment by miina** [comment]
@agingoldseco Yes, it should be possible to allow the user to drag it, or alternatively (perhaps easier option) could be being able to toggle the bar either to appear below or above the element. WDYT?

**Comment by agingoldseco** [comment]
I was actually thinking recently that it should always be on top of the element, but I like that idea! One issue is whether the rotate handle would then have to keep shifting too? I think I would most ideally like it to drag, but might also have to add a signifier that it's draggable—probably in the form of some dots on the left side. 

Otherwise, I think this is where we've landed with the floating edit bars. We want to add "add link", but I'm afraid of making it too long before we get rid of the right panel (after testing it on a 13" laptop editor mockup), and that option is available in quick actions too. @aaskedall would you be okay with this for now?

With "change color" being an option on the floating bars, we can get rid of it in the Quick Actions menu for both Shape and Text. When Text is selected, we can also take "Edit Text" out of Quick Actions.

<img width="1565" alt="Screen Shot 2022-01-21 at 12 54 39 AM" src="https://user-images.githubusercontent.com/90645922/150474381-1d598b86-d29f-47af-bb06-63d77d269724.png">

**Comment by miina** [comment]
Thanks, @agingoldseco, for the details.

When possible, could you also add link to the updated bars in Figma, also with the bar for Image, Video, Sticker.
Would be great if it would be in context in Figma, with both options -- above / on top of the element.

If there are flyouts that open when clicking on a menu item (e.g. the color / font), would be good to see those in opened state as well in context.

To confirm: "More" button would open and highlight the Design panel, is that correct?
And the `X` button would still close the floating menu without the option to open (until re-selecting the element), is that correct?

> One issue is whether the rotate handle would then have to keep shifting too?

It seems to me that even on my 13'' screen there's enough room to place the floating bar above the rotation handle in this case, thoughts?

**Comment by andrew-askedall** [comment]
To confirm: "More" button would open and highlight the Design panel, is that correct?
And the X button would still close the floating menu without the option to open (until re-selecting the element), is that correct? that's correct.

**Comment by agingoldseco** [comment]
Updates: Here's where we landed with the floating edit bars! I'll fill in a few more in-context examples, but don't think we're going to try putting the bar on top of the rotate handle yet.

<img width="1604" alt="Screen Shot 2022-01-24 at 6 30 34 PM" src="https://user-images.githubusercontent.com/90645922/150915710-aa6a5139-6028-4911-8f06-42c94f41144f.png">

And here's a link to them in Figma: 
https://www.figma.com/file/ZrO763yvMWJjYeAPsRnNfW/_Editor---Sprint-Feature-Level-Designs_2022?node-id=109%3A14698

**Comment by miina** [comment]
Thank you, @agingoldseco!

I'm not able to access the Figma link for some reason, could these be moved to the general UX Simplification file?

When you add some in-context examples, would be good to have the flyouts there, too -- to see the positioning.

Q1: Currently the border assumes locked border only, however, it's also possible to have unlocked border and set separate border width to each side -- can you add a flyout / mockup for that, too?

Q2: What does the upload button do in editing media element menu? Does it replace that media? 🤔

**Comment by agingoldseco** [comment]
> Q1: Currently the border assumes locked border only, however, it's also possible to have unlocked border and set separate border width to each side -- can you add a flyout / mockup for that, too?

We actually decided to not have those unlocked border and corner options in these bars just to save the space, so users can click on "More" to access those features. Also, please notice small bars connecting some elements to show that, for example, some color dropdowns are only for the border. 

<img width="278" alt="Screen Shot 2022-01-25 at 1 33 08 PM" src="https://user-images.githubusercontent.com/90645922/151037823-f20c1dca-4f34-4a46-b448-690fdb930925.png">
<img width="355" alt="Screen Shot 2022-01-25 at 1 33 02 PM" src="https://user-images.githubusercontent.com/90645922/151037833-a318e4d7-a8d2-4b91-99cc-2a4ecf3d0453.png">


> Q2: What does the upload button do in editing media element menu? Does it replace that media? 🤔

Yes—I'll actually replace those with Replace Media icons.

**Comment by bmattb** [comment]
@agingoldseco can you transfer the Figma files for this to the XWP managed instance so that the developers can access?

**Comment by agingoldseco** [comment]
Sorry! Did that yesterday, they're all in there—not sure why the link is still not working when I've replaced it a few times. Trying again now.

**Comment by miina** [comment]
Closing as the base structure is ready.
Added an epic for this and the following issues: #10640
