### ISSUE TITLE
UI Simplification: Empty Story state helper text / menu

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10110]
## Feature Description
See [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11122%3A445997)

- [ ] Display helper text / icon on the empty page when there is just one empty page.
- [ ] Add a separate right-click menu with options to interact
- [ ] The same menu also opens when clicking on the icon

Menu actions:
- Choose Image or Video: Opens and highlights the Media Library
- Upload Image or Video: Opens Media upload modal (the default WP modal as elsewhere)
- Browse Page Templates: Opens and highlights the Page Templates tab
- Browse Stock Images and Videos: Opens and highlights the 3rd party Media Library tab

## Additional Context
<img width="183" alt="Screenshot 2022-01-06 at 12 49 39" src="https://user-images.githubusercontent.com/3294597/148371529-838e4dd4-533d-4ed7-97c1-73a217a54575.png">

**Comment by miina** [comment]
To confirm:
- In Figma, is it a right-click menu, or does this menu open when clicking on the icon displayed?
- If it's right-click menu, then this means that the other Page right-click menu will not work there, correct?
- Do we display this helper for only fully new unsaved Story? E.g. if the user adds an image and removes it again, we should not display this helper text anymore (essentially getting into empty state again), is that correct?
- Are these menu actions correct:
1. Choose Image or Video -- opens and maybe highlights(?) the Media Library
2. Upload Image or Video -- opens Media Library (or maybe just highlights the existing button?)
3. Browse Templates -- redirects the user to the Dashboard's templates library
4. Browse Stock Images and Videos -- opens and maybe highlights(?) the 3rd party Media Library

**Comment by barklund** [comment]
> 3\. Browse Templates -- redirects the user to the Dashboard's templates library

I assumed that this would refer to the page templates tab actually and do "switch tab + highlight".

**Comment by agingoldseco** [comment]
Confirming all this:

> In Figma, is it a right-click menu, or does this menu open when clicking on the icon displayed?

It opens when you click on the icon, but it can be the right click menu too cause you won't need anything else in that starting state.

> If it's right-click menu, then this means that the other Page right-click menu will not work there, correct?

Yes

> Do we display this helper for only fully new unsaved Story? E.g. if the user adds an image and removes it again, we should not display this helper text anymore (essentially getting into empty state again), is that correct?

I think it can come back to empty state as long as the color of the background hasn't been changed, etc—don't see any reason why not? 

> Are these menu actions correct:
> Choose Image or Video -- opens and maybe highlights(?) the Media Library

Yes

> Upload Image or Video -- opens Media Library (or maybe just highlights the existing button?)

No, this should open the new upload modal that Pea Pod recently implemented—you can see it by click on the Upload button in the Upload Media tab.

> Browse Templates -- redirects the user to the Dashboard's templates library

No, this should just go to the Templates tab in the editor. What Morten said. 

> Browse Stock Images and Videos -- opens and maybe highlights(?) the 3rd party Media Library

Yes

**Comment by miina** [comment]
@agingoldseco 

> No, this should open the new upload modal that Pea Pod recently implemented—you can see it by click on the Upload button in the Upload Media tab.

By Upload Media tab, do you mean just the local Media tab?
<img width="366" alt="Screenshot 2022-01-10 at 11 17 43" src="https://user-images.githubusercontent.com/3294597/148742413-f0302814-d17d-4580-81a8-17a6efcc5b8b.png">

When I click the "Upload" button, I just see this as usually:
<img width="1311" alt="Screenshot 2022-01-10 at 11 18 03" src="https://user-images.githubusercontent.com/3294597/148742430-2adb4c6f-6c09-4643-b5f6-66b08192e2e1.png">

Could you send me a link to Figma for the design? Anyway -- if the modal is already implemented separately, then this part is out of scope for this issue. We just open the same thing that opens when clicking the "Upload" button in the Media tab.

> No, this should just go to the Templates tab in the editor. What Morten said.

Okay, in this case it might be good to change the name to Browse Page Templates since we don't have Templates available inside the editor, we only have Page Templates available. Thoughts?

**Comment by agingoldseco** [comment]
Sorry, yes I meant that upload button in the Upload Media tab! So yes, that "Upload to Story" modal in your screenshot should open immediately when someone clicks "Upload image or Video" and work the same as the flow of clicking to that modal from anywhere else. It is a little different than the other empty state buttons, but taking people to the tab to click on the button themselves is an unnecessary extra step. Would this be a problem for scope?

I'd be okay with this name change, yes—Andrew and I talked about potentially changing that template layout in the future, but for now we don't think it makes sense for any of these empty state options to take you out of the editor entirely.

**Comment by miina** [comment]
> Sorry, yes I meant that upload button in the Upload Media tab! So yes, that "Upload to Story" modal in your screenshot should open immediately when someone clicks "Upload image or Video" and work the same as the flow of clicking to that modal from anywhere else. It is a little different than the other empty state buttons, but taking people to the tab to click on the button themselves is an unnecessary extra step. Would this be a problem for scope?

Not a problem at all, just for information that this upload Modal is the default WordPress media library modal, we can use it anywhere without a problem.

> I'd be okay with this name change, yes

Sounds good!

**Comment by barklund** [comment]
> > Upload Image or Video -- opens Media Library (or maybe just highlights the existing button?)
> 
> No, this should open the new upload modal that Pea Pod recently implemented—you can see it by click on the Upload button in the Upload Media tab.

I assume pressing "upload image or video" will also insert the newly uploaded item into the page and not "just" add it to the media library? And if added, should it be added as background media or not?

**Comment by miina** [comment]
> I assume pressing "upload image or video" will also insert the newly uploaded item into the page and not "just" add it to the media library?

Yep, it should essentially do the same as the Upload button in the Media Library -- insert to Page + upload to Media Library (if applicable). We could use the `MediaUploadButton` component.


EDIT:
> And if added, should it be added as background media or not?

Amy said that it should "work the same as the flow of clicking to that modal from anywhere else", elsewhere it just inserts into page, not as background.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10261.

1. Created a new story - message is displayed as expected
2. Added an item to the canvas (added images, videos, shapes, stickers, text, uploaded from my local machine, dragged and dropped items) - message is hidden
3. Deleted item from the canvas - message is displayed again
4. Tested on Safari, Chrome and Firefox


https://user-images.githubusercontent.com/96055551/152016599-710fac82-35ee-4b31-a19c-2c2888e75a12.mp4
