### ISSUE TITLE
Double scrollbars in zoomed state

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#10126]
## Expected Behaviour

No double scrollbars expected

## Steps to Reproduce

1. Zoom page to 200%
2. Observe double scrollbars on canvas

## Screenshots
![Screen Shot 2022-01-07 at 15 45 17](https://user-images.githubusercontent.com/637548/148608595-95af14d7-d597-4383-bb95-c9d299126381.png)

**Comment by felipebochehin87** [comment]
@miina @swissspidy @kkalarickal 

I tested this fix against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10127, and you can find the evidences on the doc below:

1. Opened Stories editor
2. Zoomed in to 200%
3. Zoomed in to 300%
4. Only one scroll bar is displayed vertically and one horizontally 

https://docs.google.com/document/d/1XusJsRdx8rn0hAkwciwJPJZAOzf-JnL57oJbl_ZaY-E/edit#
