### ISSUE TITLE
Media: Use a single worker for BlurHash generation

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10133]
## Feature Description

Right now, for every image for which we need to generate the blurhash, a new worker thread is created. So potentially mean dozens of threads, which just slows things down.

It would be more performant to have only 1 worker for all the blurhash generation/backfilling and pass messages back and forth, instead of creating 1 per image

At the same time it might be beneficial to use a solution like @koale/useworker, https://www.npmjs.com/package/react-hooks-worker or  https://www.npmjs.com/package/@shopify/react-web-worker (seems tricky to set up as it requires webpack changes) to make working with workers more intuitive and to make this goal easier to achieve.

**Comment by spacedmonkey** [comment]
In earlier versions of the blurhash, I simple generated one blurhash at a time. This can be done by limiting one blurhash at time in the backfill queue. Should I push that change, it is only a couple lines of code.

**Comment by swissspidy** [comment]
That's not the goal.

Generation should still happen in parallel, just in 1 worker instead of many workers.

**Comment by spacedmonkey** [comment]
This was what I was discussing for the record - https://github.com/google/web-stories-wp/commit/e386b4f6fc8e197bf1742f4209f63fd1ee1ac845

**Comment by swissspidy** [comment]
Right, this is not what is meant here.

This will still generate multiple ones in parallel. Just in 1 worker thread.
