### ISSUE TITLE
Fix Drop Target Handle Image Dragged from Library Karma Test

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10145]
## Bug Description

Test was disabled to help find solution to karma fixture issue, currently it's failing. 

components/dropTargets/karma/dropTarget line 112

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
Since this issue is for image only then not sure if related somehow but currently drop-targeting videos from the library seems to be broken for some reason:
https://github.com/google/web-stories-wp/issues/10166
