### ISSUE TITLE
Performance Report: Jan 2022 baseline perf report

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10158]
## Task Description

As we move to focus on performance as a feature we should have a proper baseline to compare and seek improvements from.

**Comment by maxyinger** [comment]
Testing three base interactions on `main` prior to any of the recent performance improvements to establish a baseline (commit hash: `1d5c7228e`):
- Select an element
- Drag a selected element to update it's position
- Change the layer order of a selected element

These tests are being performed on a fully specced out 2018 macbook pro on this sample story:
https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=20239&action=edit#page=%2522593109cf-a227-4f95-af6b-f413e823064a%2522

The story should look like this and have 1 page that contains 50 shape elements (51 elements total including the background):
<img width="725" alt="Screen Shot 2022-01-13 at 12 17 15 PM" src="https://user-images.githubusercontent.com/35983235/149386851-7314f2e2-78f4-4a3e-b4d9-950a2a8bb497.png">

All tests are being performed with the layers panel expanded, the design panel open, and the library pane set to the media tab

**Comment by maxyinger** [comment]
**Select an Element**
| React Specific | Total JS |
| ------------ | ----------|
| Largest Commit: ~150ms | Rough total interaction time: ~350ms |
| <img width="825" alt="Screen Shot 2022-01-13 at 12 27 17 PM" src="https://user-images.githubusercontent.com/35983235/149388080-be576bd9-3eb3-464e-b901-2511457768ad.png"> |  <img width="854" alt="Screen Shot 2022-01-13 at 12 30 50 PM" src="https://user-images.githubusercontent.com/35983235/149388553-b17cc72c-6b1b-47d7-9701-d34a085bc6b5.png"> |

**Comment by maxyinger** [comment]
**Drag a selected element to update it's position** 

**Initiating the drag**
| React Specific | Total JS |
| ------ | ------ |
| Relevant Commit: ~115ms | Rough total interaction time:  ~225ms |
| <img width="614" alt="Screen Shot 2022-01-13 at 12 47 28 PM" src="https://user-images.githubusercontent.com/35983235/149390828-1b297baa-2d45-48e3-9ace-b891a7b0eef2.png"> | <img width="613" alt="Screen Shot 2022-01-13 at 12 50 17 PM" src="https://user-images.githubusercontent.com/35983235/149391241-46f89e4a-48e9-424b-9e6f-fb528b2ed161.png"> |


**Ending the drag**
| React Specific | Total JS |
| ------ | ------ |
| Relevant Commit: ~250ms | Rough total interaction time: ~690ms |
| <img width="613" alt="Screen Shot 2022-01-13 at 12 47 42 PM" src="https://user-images.githubusercontent.com/35983235/149390880-ef6bda63-c92f-4852-a478-667abd6cf7ef.png"> | <img width="614" alt="Screen Shot 2022-01-13 at 12 51 30 PM" src="https://user-images.githubusercontent.com/35983235/149391376-8c984002-164d-40c7-b4e9-668a11873483.png"> |

**Comment by maxyinger** [comment]
**Change the layer order of a selected element**

| React Specific | Total JS |
| ---- | ---- |
| Largest Commit: ~205ms | Rough total interaction time: ~455ms |
| <img width="602" alt="Screen Shot 2022-01-13 at 1 05 32 PM" src="https://user-images.githubusercontent.com/35983235/149393411-b2e3bb5d-214c-41d8-b8b5-de1e9fa09497.png"> | <img width="555" alt="Screen Shot 2022-01-13 at 1 07 21 PM" src="https://user-images.githubusercontent.com/35983235/149393600-473666a7-a49e-4e8f-9b21-a8a539097f7e.png"> |

**Comment by maxyinger** [comment]
We can add more baseline tests here as we establish them by checking out main at the hash `1d5c7228e` and performing them on the test story mentioned above.
