### ISSUE TITLE
Code Quality Updates after bumping PHP version requirement

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10151]
## Task Description

* Remove some compat code we have for PHP 7.0 or even PHP 5.6
* Use newer language features / simplify some code where applicable (the IDE will easily help with this)

Examples:

* `void` return type

**Comment by spacedmonkey** [comment]
More examples 

- [Class Constant Visibility](https://wiki.php.net/rfc/class_const_visibility)
- [Square bracket syntax for array destructuring assignment](https://wiki.php.net/rfc/short_list_syntax)

**Comment by spacedmonkey** [comment]
I think we should add a lint rules for all the new php 7.2 we wish to implement. That way, some of the features can be implemented by using php code fixer.

**Comment by spacedmonkey** [comment]
Wonder if we should run [Rector](https://github.com/RectorPHP/Rector) again, so what can be automatically upgraded.

**Comment by swissspidy** [comment]
Use whatever tool you deem best suited for the task.

Regarding lints, if we can achieve some changes with the current config, that's great. If something would require additional PHPCS plugins or the like, that needs to be discussed separately.

For class constant visibility we can just uncomment this line in the PHPCS:

https://github.com/GoogleForCreators/web-stories-wp/blob/7274e02b0fe5c2d10c03c64d68c1e0db5329f3a8/phpcs.xml.dist#L172-L173

For `void` return types we can try enabling `SlevomatCodingStandard.TypeHints.ReturnTypeHint`:

```xml
<rule ref="SlevomatCodingStandard.TypeHints.ReturnTypeHint ">
  <properties>
    <property name="enableStaticTypeHint" value="false" />
    <property name="enableMixedTypeHint" value="false" />
    <property name="enableUnionTypeHint" value="false" />
  </properties>
</rule>
```

I am not aware of a lint rule for array destructuring.

There's also stuff that probably needs to be changed manually, for example:

https://github.com/GoogleForCreators/web-stories-wp/blob/7274e02b0fe5c2d10c03c64d68c1e0db5329f3a8/includes/Infrastructure/Injector/SimpleInjector.php#L390-L405

https://github.com/GoogleForCreators/web-stories-wp/blob/7274e02b0fe5c2d10c03c64d68c1e0db5329f3a8/includes/AMP/Output_Buffer.php#L195-L201

https://github.com/GoogleForCreators/web-stories-wp/blob/7274e02b0fe5c2d10c03c64d68c1e0db5329f3a8/includes/Infrastructure/ServiceContainer/LazilyInstantiatedService.php#L59-L60

**Comment by timarney** [comment]
@spacedmonkey let me know if there's something I can help out on for this one --- do we have some next steps?

**Comment by spacedmonkey** [comment]
I think I have an idea what I what to do here.
