### ISSUE TITLE
Block: Styling of text input off

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10165]
## Bug Description
The styling of the archive link text input, is indented, when it should not be, to keep inline with other text inputs. 

## Screenshots

<img width="299" alt="Screenshot 2022-01-12 at 11 08 52" src="https://user-images.githubusercontent.com/237508/149129234-72deba89-0c0e-4e6d-8b31-35542e83ee6f.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
I think this is intentional 🤔 

To indicate that it belongs to the toggle.

**Comment by spacedmonkey** [comment]
@aaskedall @agingoldseco Can someone from design chime in here. I really feel like this UX looks off / strange.

**Comment by agingoldseco** [comment]
I think it could go either way. Does look a little strange, perhaps it could just be a bit less indented than it is? Like halfway across the toggle.
