### ISSUE TITLE
Media: Deleting media element crashes the editor

### ISSUE THREAD

**Issue by amovar18** [swissspidy/web-stories-wp#10161]
## Bug Description
While deleting a video element the story-editor breaks with a `console.log` printing that error was in the `mediaElement.js`. Further exploration revealed that the `mediaElement` ref changes from `video` element to `image` element thus leading to `pause()` throwing an error.

## Expected Behaviour

The video should delete properly without breaking the editor.

## Steps to Reproduce

1. Go to any local media hover on it.
2. Click on dropdown 
3. Then click on delete from dropdown menu
4. Notice the editor breaking.

## Screenshots

https://user-images.githubusercontent.com/59614577/149081887-33a987f8-1491-4b10-8ccd-ba5ec85ea108.mov

## Additional Context

- Plugin Version: 1.16.0-alpha-0
- WordPress Version: 5.8.3
- Operating System: MacOS monterrey
- Browser: Chrome

**Comment by amovar18** [comment]
I guess it can be fixed by removing the condition:
https://github.com/google/web-stories-wp/blob/da4cc377d079af87216978ad461c45fb5e77ab14/packages/story-editor/src/components/library/panes/media/common/mediaElement.js#L137-L142
Since when the video becomes inactive it automatically converts to image

**Comment by swissspidy** [comment]
Nice find!

Would you be open to submit a PR?
