### ISSUE TITLE
Block: Remove button styling off

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10164]
## Bug Description

The styling of the remove thumbnail button seems to be off. Being too close to the select button see screenshot. 

## Screenshots

<img width="301" alt="Screenshot 2022-01-12 at 10 54 08" src="https://user-images.githubusercontent.com/237508/149127659-b396b33a-28a6-4d23-addb-cacfa7737503.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Seems like some 10px margin or so should be enough

**Comment by timarney** [comment]
@spacedmonkey 

I found the code for this feature but how do I access that screen in the editor?  
I found the poster image setting but I don't see the Embed Settings panel.


<img width="301" alt="149127659-b396b33a-28a6-4d23-addb-cacfa7737503" src="https://user-images.githubusercontent.com/62242/152787033-138f5fe2-a7f2-4926-acde-6b5cf151b8a2.png">

**Comment by spacedmonkey** [comment]
@timarney Here is a video of how to replicate. 

https://user-images.githubusercontent.com/237508/152789763-b6f0208c-2fa6-470d-bc79-7c347655a094.mov

Here is the url I used 
```
https://preview.amp.dev/documentation/examples/introduction/stories_in_amp
```
