### ISSUE TITLE
Template Details: RTL arrows inverted 

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10177]
## Bug Description

Found by @spacedmonkey during bug bash. 

Arrows are inverted in RTL. 

## Expected Behaviour

The next button should be be in with use template button. 
Tab order should go to 'next' and then 'prev'.

## Screenshots

<img width="1352" alt="Screen Shot 2022-01-12 at 11 28 58 AM" src="https://user-images.githubusercontent.com/10720454/149200415-7b16059a-555e-4681-918c-0600b45677bd.png">

## Additional Context

Make sure paging order is proper too

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10181.

1. Clicked on Switch to RTL
2. Clicked on Stories > Explore Templates
3. Clicked on See details on any template
4. Used the < and > arrows to switch templates
    a. First template displays the "< previous" arrow disabled
    b. Last template displays the "next >" arrow disabled



https://user-images.githubusercontent.com/96055551/149503478-e71838a8-e779-48f9-a763-228c6ff8ff14.mp4
