### ISSUE TITLE
Template Details: Clean up A11Y

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10176]
## Feature Description

@spacedmonkey brought up a good question about screen readers announcing the proper info on the templates detail page. We should make sure everything's working properly. 

Right now, screen readers announce the template title and the description. The chips holding the keywords and the color tags are not, these elements can't be interacted with. Should they be turned into lists instead so that they could be given proper structures by screen readers?

Additionally, announcing the template title when the modal opens might be a nice improvement. 

Update should include some tests to make sure functionality doesn't regress. 

## Additional Context

Template Details has never actually been finished! It was a prototype that never got priority, so let's use this as an opportunity to scale what we need to.

**Comment by BrittanyIRL** [comment]
(let's discuss any UX updates via #10175 before working through this)

**Comment by BrittanyIRL** [comment]
Testing (copied from PR description) 

Shouldn't be any visual changes.

If you use a screen reader (chrome vox or voiceover on mac will suffice) you should get the following:

Helpful messages on all focusable content
Announcing new template title when you use the arrows (works on chrome vox, I think I've got user error on my voice over set up)
Announcing when the dialog opens or closes
If you select text, it'll get read.


If you tab, you'll hit: 1) close button 2) use template button 3) (if available) prev template button 4) group of buttons to change preview image 5) next template button.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10313.

1. Opened screen reader
2. Moved mouse over screen elements - screen reader reads buttons, elements, labels, content, etc...
3. Clicked on screen elements - screen reader reads buttons, elements, labels, content, etc... and elements are selected
