### ISSUE TITLE
Right Click Actions: Duplicate Selection

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10179]
## Feature Description

Pointed out by @barklund and @agingoldseco during bug bash.

> When duplicating an element (or multiple elements), I would expect the new element(s) to be selected rather than the old one(s). That’s what happens if you do it by keyboard (cmd+d), so the two ways should at least be identical.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10241.

1. Opened https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/
2. Added formats
3. Right clicked on the format
4. Clicked on Duplicate Element - duplicate format is selected, existing one (old) is not
5. Repeated steps above using images, gifs, text, videos, etc...
