### ISSUE TITLE
Template Details: Reset images on navigation

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10178]
## Bug Description

@merapi had a great idea to reset the state of the template images when navigating to prevent the lag on the grid. 

## Expected Behaviour

No more lag on template images in detail modal 

## Screenshots

https://drive.google.com/file/d/1hW4zUkfNIX0X6f-4Y5zIn3Q8gzeQcJ66/view?usp=sharing 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10193.

1. Opened https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/
2. Clicked on Stories > Explore Templates
3. Clicked on See details on any template
4. Used arrows <- and -> to switch templates - images loading as expected, no images from previous template are displayed when a new template is open


https://user-images.githubusercontent.com/96055551/150090753-0d319ea7-0467-4e53-ae41-a4adcf3c3f5d.mp4
