### ISSUE TITLE
Story player replay button does not revert to next button 

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#10171]
## Bug Description
After completing a story, the replay button restarts the story but does not change back to the forward/next button. This issue does not occur when the user is a logged-in user, but you will notice the behavior in an incognito window or when in a logged-out state.

Note the functionality is there even though the button does not display correctly.
## Expected Behaviour

It should be a forward button after replaying the story.

## Steps to Reproduce

1. View story to completion in a logged-out state, or incognito window.
2. Click on replay button
3. Note the button remains that way after landing on the first page onward

## Screenshots

<img width="916" alt="Screen Shot 2022-01-12 at 9 03 50 AM" src="https://user-images.githubusercontent.com/66372350/149156258-83e17f0c-3912-4034-b9f3-90e5f5839cdb.png">

-->

## Additional Context
original report: https://wordpress.org/support/topic/the-replay-icon-at-the-end-of-the-story-doesnt-disappear/
example story: https://testsite.cmsdevrel.com/web-stories/replay-story-test/

- Plugin Version: 1.15.1
- WordPress Version:
- Operating System: macOS
- Browser:

**Comment by swissspidy** [comment]
Could you please report this on the amphtml repo? It's not something we control.

**Comment by LuckynaSan** [comment]
Sure thing. The ticket has been filed on AMP: https://github.com/ampproject/amphtml/issues/37350.
