### ISSUE TITLE
Library: Remove old feature for searching in the text and shapes tab

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#10174]
## Feature Description

Discovered during bug bash 1.16: a very old feature that isn't being used still exists in the text and shapes tabs. Remove the `showTextAndShapesSearchInput` from the experiments list and all associated code.

**Comment by amovar18** [comment]
@samwhale can I raise a PR for it or is it already in the works?

**Comment by swissspidy** [comment]
I don't think this is in the works already, so feel free to submit a PR 👍
