### ISSUE TITLE
Classic Editor: Add integration to allow embedding selected stories

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#10185]
## Bug Description

When using the HTML embed code in the classic WordPress editor, the '**selected_stories**' variable is not pulling through the requested stories given. For example if we have Stories 1,2 and 3 created in that order and embed the code below the latest story number 3 will be pulled through and not story 1 which is what has been put for the '**selected_stories**' variable:

`[web_stories title="true" excerpt="false" author="false" date="false" archive_link="false" circle_size="150" sharp_corners="false" image_alignment="right" number_of_columns="1" number_of_stories="1"  view="carousel" selected_stories="1"/]`

It appears to be selecting and ordering by descending order. If you add in the `order=”DESC” ` or `order=”ASC” ` then it will display these in the correct order but again if you have the '**selected_stories**' variable with the value 1 and are ordering by descending order then selected_stories are ignored and the last story 3 is selected.

## Expected Behaviour

When using the selected_stories variable I would expect that those stories are pulled through and override the order and when order is not set then I would definitely expect the selected stories to show.

## Steps to Reproduce

1. Install the classic editor plugin.
2. Go to Web Stories and edit one of your current stories or create a new story. Get the story ID from the url. 
3. Create a new post.
4. Place the Web Stories HTML code snippet above in your post content making sure to change the selected_stories value to the ID you gathered from your story url.
5. View the post.

## Video Recording

https://user-images.githubusercontent.com/91896826/149329056-962ebbb6-066d-4bbb-8f52-2488e1e9ddc8.mp4

## Additional Context

**Related support forum topic:** https://wordpress.org/support/topic/display-selected-web-story-using-html-code-2/

**Comment by swissspidy** [comment]
`selected_stories` is not a supported argument, I don't know why they think it works. We do not currently support displaying selected stories with this shortcode. It only supports displaying the latest stories.

So this is a feature request :-)

**Comment by swissspidy** [comment]
Since it's a feature request: supporting the classic editor doesn't have a high priority, I'd encourage them to use the block editor instead.

**Comment by swissspidy** [comment]
Related: #7898

**Comment by swissspidy** [comment]
Closing since we should focus on Gutenberg
