### ISSUE TITLE
Stories Archives Setting Does Not Reset 

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#10191]
## Bug Description

Once you set the custom page, you can't see the other page options until you leave the Stories Settings dash and come back. The settings start to show wonky behavior until you refresh or leave the Settings dashboard. See recording below.

Perhaps, you can show the list of page options with a checkmark beside it for "custom" setting.
## Expected Behaviour
For settings to reset after toggling between default, custom, or disabled. 
For settings to show up once.

## Steps to Reproduce

1. Navigate to Stories Settings > Stories Archive
2. Change setting from Default to Custom
3. Select a custom page
4. View it
5. Change the setting from Custom to Default, default to custom, and so on. View the page options and note the selections acting finnicky.

## Screenshots

https://user-images.githubusercontent.com/66372350/149377767-4c75bbe0-103e-40b8-89b5-27d96dbaa87e.mov

## Additional Context

- Plugin Version: 1.15.1
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10446.

1. Visited Dashboard > Settings
2. Toggled between Default/Disabled/Create your own - every time I selected "Create your own" after selecting any of the other two options, the search field was displayed empty as expected

https://user-images.githubusercontent.com/96055551/152589979-a9d6c9ba-c055-4969-a812-c7466e1133d3.mp4
