### ISSUE TITLE
User should be prevented from loading the same custom font twice

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10196]
## Bug Description
Originally reported by @BrittanyIRL 
The user should not be able to provide the dashboard settings with the same custom font as one already loaded. Currently it's possible, and then the same font is shown twice
![image3.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/c60d96d0-2b88-4bd0-931f-6497acb75c08)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
This was actually also a known "bug" (just not implemented yet), forgot to add it. We should probably place post-MVP Custom Fonts to the Roadmap somewhere.

**Comment by swissspidy** [comment]
Hmm we have some PHP logic in place to prevent this on the server level already, sounds like it's not working correctly 🤔 

Of course proper error handling on the client is also needed for it.

**Comment by swissspidy** [comment]
Error handling is done in #10941
