### ISSUE TITLE
Media Library: BlurHash never goes away on video in Chrome

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10204]
## Bug Description

Originally reported by @BrookeGraham 

If hovered on a video when first loaded the blur never goes away until you are no longer hovered on that video

  Chrome only, issue not present in Safari

![image4.gif](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/1806b965-7768-4db5-b21a-f4171fe943b7)
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10218.

1. Opened story editor
2. Changed filter to video
3. Moved cursor over the first video

Blurhash is displayed and hidden as expected.
