### ISSUE TITLE
Karma: Investigate and fix file pattern config log 

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10207]
## Bug Description

Hot fix added fonts.googleapis.com to list of external files that are OK for Karma to load in karma-story-editor.config.cjs. This decreases the amount of times we get this error but doesn’t fix it completely. While this doesn’t block any tests from running it is adding noise to the logs that should be avoided both for legibility of the logs and to make sure all tests are getting the same treatment (allowing external link retrieval vs not). 
Regex added to config is helpful but only after initial set up - at first it gives a console warning (`Pattern "/home/runner/work/web-stories-wp/web-stories-wp/^https:/fonts.googleapis.com/css*" does not match any file.`). Let's fix this.

## Expected Behaviour

No  fonts.googleapis.com related error logs in karma 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrittanyIRL** [comment]
Pretty sure I've _finally_ pinpointed where the inline css errors are stemming from!  

It's associated with the [fontEmbedCss set up in our htmlToImage flow](https://github.com/bubkoo/html-to-image/issues/179). Our flow is intentional though - looks like it's here: `web-stories-wp/packages/story-editor/src/utils/usePageAsCanvas.js`.
```
 const promise = htmlToImage.toCanvas(fullbleedContainer, {
                fontEmbedCss: '',
                pixelRatio: 1,
                filter: filterSelectedElement && filter,
              });
```

Where the fontEmbedCss is an empty string - that's on purpose I think to make sure the canvas stays current.

Apparently others have recently fixed this by adding crossorigin anon to their set up which we're doing when we're loading stylesheets (`web-stories-wp/packages/story-editor/src/utils/loadStylesheet.js`) but I think it's just not syncing up timing wise for Karma. 

@merapi I'm curious if this rings a bell at all for you since you've contributed to the html-to-image package.

**Comment by BrittanyIRL** [comment]
hey @merapi  - just a nudge - when you get a sec, i'm curious your take on the above given your experience with html to image.

**Comment by merapi** [comment]
I did some testing (only on `fdescribe('Eyedropper'`).
It looks like those `cssRules` errors are only present in headless Karma tests, I don't see them in non-headless mode and in headless e2e Puppeteer tests (that's weird).




| Karma headless | Karma non-headless / Puppeteer headless(!? different output but without errors) |
|----------------|--------------------|
| ![Screenshot 2022-02-10 at 13 23 27](https://user-images.githubusercontent.com/21036224/153409528-61b83239-7aa6-4491-b379-2dc266da03fe.png) | ![Screenshot 2022-02-10 at 13 23 23](https://user-images.githubusercontent.com/21036224/153409618-0292c388-b840-4093-9c76-7af8d494e97f.png) |

> Regex added to config is helpful but only after initial set up - at first it gives a console warning (Pattern "/home/runner/work/web-stories-wp/web-stories-wp/^https:/fonts.googleapis.com/css*" does not match any file.). Let's fix this.

What this regex really does? I can't see any difference. For me, it looks like if we remove the regex - pattern errors (`Error while reading CSS rules from https://fonts.googleapis.com/css`) will disappear, CSS rules error (`Error while reading CSS rules from https://fonts.googleapis.com/css`) will not - but they are unrelated to me.

After regex removal:
| Karma headless | Karma non-headless |
|----------------|--------------------|
| ![Screenshot 2022-02-10 at 13 28 25](https://user-images.githubusercontent.com/21036224/153411536-d5f66180-8871-41d1-8b10-e473e4905588.png) | ![Screenshot 2022-02-10 at 13 26 34](https://user-images.githubusercontent.com/21036224/153411567-3cb84b88-6b7e-4b21-b73d-fb9c631cf3af.png) |
