### ISSUE TITLE
UX improvements for Archive setting

### ISSUE THREAD

**Issue by mxbclang** [swissspidy/web-stories-wp#10203]
## Feature Description

We regularly receive requests on the support forum for the ability to adjust the default Web Stories archive page (`web-stories`). In #4862, this was discussed and the alternative of allowing users to build out their own custom archive page using Gutenberg blocks was determined to be the best next step.

However, we find in the forums that users don't understand that the Custom option in Web Stories > Settings > Stories Archives will allow them to do this and have the control that they're looking for. I think there might be some confusion on the user side, as our approach is pretty uncommon in my experience with WP plugins. I've seen settings like this before, but they typically generate an automated archive on the selected page that is *not* modifiable; see https://wordpress.org/support/topic/custom-archive-page-is-empty/. Our approach is different.

To make this option clearer to users, I think there are some adjustments that we can make here. The suggestions below should definitely be vetted by our UX team.

## Disabled option
- Change helper text from "**This disables the default archive page.**" to "**Turn off the default archive page at [site URL]/web-stories/". Users will receive your 404 page when they go to the default archive page.**"

## Custom option
- Change "**Custom**" label to "**Create your own**"
- Change helper text from "**Choose a custom page as your stories archive.**" to "**Choose a page to serve as your Web Stories archive. Use the Web Stories block to add stories to this page.**"
- Change helper text that appears under page select from "**Visit archive page at [custom page URL]**" to "**Visit archive page at [custom page URL]. [site URL]/web-stories/ will automatically redirect to this page.**"

## Additional Context

Previous archive customization requests:
- https://wordpress.org/support/topic/editing-gws-archives-page/
- https://wordpress.org/support/topic/web-stories-page-edit/
- https://wordpress.org/support/topic/how-to-customize-web-stories/
- https://wordpress.org/support/topic/archives-stories/
- https://wordpress.org/support/topic/how-do-i-add-h1-heading-to-the-web-stories-archive-page/

**Comment by swissspidy** [comment]
cc @agingoldseco @gajasinski for thoughts

**Comment by swissspidy** [comment]
Related: #7558

**Comment by gajasinski** [comment]
I'm good with the wordsmithing if we think this will help. @agingoldseco thoughts on the phrasing?

**Comment by agingoldseco** [comment]
Agreed! These helper text alternatives look good, in this case I believe more descriptive is better and even just "Create your own" will go a long way.
