### ISSUE TITLE
Code quality: refactor the right-click menu provider into smaller files

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10212]
## Feature Description
Currently, the [right-click menu provider file is 1200+ lines](https://github.com/google/web-stories-wp/blob/e7cb5fe4dee961dbfc318dbc7b3c75b3373b6a02/packages/story-editor/src/app/rightClickMenu/provider.js). It would be good to refactor it into smaller files for readability and for simpler management of the file, e.g. by menu items per element + common items, or some other way.

**Comment by samwhale** [comment]
To test:

1. Verify that the right click menu opens and closes as expected still.
    - Right clicking the canvas, an element in the canvas, and a layer in the layer panel should open the right click menu.
    - Selecting multiple elements or layers and right clicking should open a context menu
    - Pressing `Esc` should close it. 
    - Clicking away from the context menu should close it.
2. Verify that the actions in each menu work as expected.
    - Each element type has its own context menu. Verify that all actions don't break the app. 
    - Selecting multiple elements at the same time should only show one action. Verify that this duplicates all elements.
    - Clicking the `Undo` button in snackbars that appear should revert the action performed from the context menu.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10361.

1. Added images to the canvas
2. Added videos to the canvas
3. Added gifs to the canvas
4. Added shapes to the canvas
5. Added text to the canvas
6. Added stickers to the canvas
7. Right clicked on each of these elements - menu is displayed
8. From the menu, clicked on bring to front, send to back, duplicate element, copy and all other actions - working as expected
9. Right clicked on the background - menu is displayed
10. From the menu, clicked on add new page before/after, delete page, duplicate page - working as expected
