### ISSUE TITLE
Code Quality: remove `customVideoCaptionsInEditor` feature flag code

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10236]
## Task Description

This feature was enabled by default in 1.16.0

Let's remove the `customVideoCaptionsInEditor` code completely for the next release.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10447.

1. Uploaded a video
2. Added video to the canvas
3. Uploaded subtitles
4. Added subtitles to the video - working as expected


https://user-images.githubusercontent.com/96055551/152587607-1b034663-ed7f-4dd8-a118-57df940f5a59.mp4
