### ISSUE TITLE
Transfer repository to new org

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10248]
## Task Description

- [x] Transfer repository to the `GoogleForCreators` org
- [x] Update any URL references in the code
- [ ] Update Percy

**Comment by c0b41** [comment]
@swissspidy looks like all links broken `github.com/googleforcreators/web-stories-wp-wp` https://github.com/GoogleForCreators/web-stories-wp/commit/242188869094f41bffdd15b169e860d2760cccf4

**Comment by swissspidy** [comment]
Ugh, strange. Now idea how that happened. Thanks for letting me know!
