### ISSUE TITLE
Video Trimmer constantly re-renders due to changing `currentTime`

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10243]
## Bug Description

The `useVideoNode` hook in the video trimmer tracks the video's `currentTime` in state, which is then passed on by `VideoTrimProvider` and consumed by `VideoTrimmer`.

There, it is only used to update the slider as the video is playing:

https://github.com/google/web-stories-wp/blob/083ade640608cab6e532b24716a51a88f34ece9a/packages/story-editor/src/components/videoTrim/videoTrimmer.js#L172-L178

This means the whole `VideoTrimmer` component is constantly re-rendering as long as the video is playing.

## Expected Behaviour

I feel like this could be improved by getting the `currentTime` from the actual video node instead, or at least do a simple

```js
const { currentTime } = useVideoTrim(({ state: { currentTime } }) => ({
    currentTime,
  }));
```

call within the `CurrentTime` component itself so that the re-render is scoped to that component.

## Steps to Reproduce

1. Enter trim mode
2. Observe re-renders in React dev tools or with the `useWhyDidYouUpdate` hook

## Additional Context

- Plugin Version: 1.16.0
- WordPress Version: 5.9
- Operating System: maCOS
- Browser: Chrome

**Comment by maxyinger** [comment]
This should be fine if `currentTime` is a primitive:
```
const currentTime = useVideoTrim(({ state: { currentTime } }) => currentTime);
```

Happy to help with any brainstorming here around escaping react renders with something updating this frequently too

**Comment by swissspidy** [comment]
Thanks Max!

In that case it should be as simple as moving that selector to `CurrentTime` and removing it from `VideoTrimmer`, so that only the `CurrentTime` component re-renders, not the whole trimmer UI.

Right now `CurrentTime` is just a styled component though.
