### ISSUE TITLE
Consider allowing transparency for background media

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10298]
## Feature Description
At some point, it was a UX decision to explicitly forbid having transparency of the background media. Can't recall the reasons exactly but I think it was meant for restricting the possibility of creating stories with backgrounds that don't look good. E.g. it's hard to create a radial/linear background that looks great under a semi-transparent background. So it was decided that better just not to allow doing it.

We do allow adding any type of color layer on top of background media currently.

Recently, it was brought up by UX that the users might want to have semi-transparent background media as well, meaning allowing setting both background color and media on each page.

We should decide if it makes sense to allow doing that, perhaps with some examples to see cases where it's useful?

**Comment by miina** [comment]
@agingoldseco / @aaskedall / @gajasinski  FYI I added this issue to follow up on the topic of allowing transparency for background media vs not.

Added the original reason for disallowing it to the description as I remember it.

**Comment by spacedmonkey** [comment]
Related: https://github.com/GoogleForCreators/web-stories-wp/issues/1194
