### ISSUE TITLE
Performance: LibraryMoveable Discovery

### ISSUE THREAD

**Issue by maxyinger** [swissspidy/web-stories-wp#10292]
We get a lot of re-renders from LibraryMoveable whenever we drag to move an object. This may not be avoidable, but goal of this ticket is to look into this and document possible solutions or why the current approach is necessary:
![Screen Shot 2022-01-20 at 1.29.15 PM.png](https://images.zenhubusercontent.com/5ea0a3e2f739259b2b0b092a/a81f1db7-b9c9-467f-a4b0-6ae64a353d37)

**Comment by swissspidy** [comment]
Related / Previously: #9580 #9882

**Comment by maxyinger** [comment]
@swissspidy Oh dope. Thanks for linking the previous work here!

**Comment by maxyinger** [comment]
Started looking into why some of the library panels, like text & shapes, have empty re-renders when selecting new elements. LibraryMoveable ended up being the root culprit.

Looks like a lot of things are set up well in here thanks to previous perf work in the area. 

Seems the empty re-renders are now being caused by the addition of the adaptive colors for text sets feature. Through `LibraryMoveable -> useInsertTextSet -> usePageAsCanvas`, theres a dependency on `selectedElementIds` to generate an image from the story to test color accessibility against.

I've currently come up with two options for this, but trying to think of others that I like more:
1) add a `TextSetLibraryMoveable` wrapper around `LibraryMoveable` that calls the `useInsertTextSet` hook and passes the necessary callback into `LibraryMoveable`. Only use `TextSetLibraryMoveable` for text sets.
  - [pro] Just uses composition adjustments which are pretty straight forward
  - [pro] Fixes empty re-renders in shape panel
  - [con] Still will deal with the same empty re-renders in the text panel where `useInsertTextSet` will still be called in the scope of the `TextSetLibraryMoveable` component

2) Getting latest context values through a ref without imposing any forced renders
```
const selectedElementIdsRef([]);
useStorySelector(({ state }) => {
  selectedElementIdsRef.current = state.selectedElementIds;
  return true;
})
```
  - [pro] This will fix all empty re-renders from element selection in LibraryMoveable components used through out the library panels
  - [pro] Doesn't break any behavior since the `selectedElementIds` are just used for callbacks
  - [con] We're already dealing with the issue of putting side effects in our selectors with new versions of `use-context-selector` coming (#10528) . This could potentially compound tech debt here. It also may be fine with the proposed use case since the selector never triggers an update :shrug:

Going to timebox trying to think of a new different solution today cus I'm not in love with any of the above approaches, but if worse comes to worst, we'll still see benefits from any of the above approaches

**Comment by maxyinger** [comment]
Hmph wondering if there's a way to leverage and augment the `PageDataUrlProvider` & something like `storyPageToDataUrl`. to limit a some of the dependencies in `usePageAsCanvas`.

I also think we could limit the amount of times `currentPageHash` gets generated in the `storyProvider` by splitting up the memo it's computed in a bit. I know `JSON.stringify` called frequently on large objects can cause a lot of memory build up and could contribute to garbage collection time and/or memory leaks

**Comment by maxyinger** [comment]
Alright closing this discovery ticket. Think I figured out a good approach and documented it here. Could possibly tie into some extra wins around memory management too.

https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/googleforcreators/web-stories-wp/10730
