### ISSUE TITLE
Context Menu: Remove 'clear styles' action

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#10293]
## Feature Description

After a discussion with @agingoldseco and @BrittanyIRL it was decided that the 'clearing styles' actions are not necessary. 

Remove the `Clear Styles` actions from the right click menu.

Old ticket: #10018

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10294.

1. Clear styles not displayed for individual elements
2. Clear styles not displayed for multiple elements at the same time
3. Copy & paste works as expected - clear styles is not displayed

![10294](https://user-images.githubusercontent.com/96055551/150837062-dd83823c-439c-433c-a7de-625b7906e7ad.png)
