### ISSUE TITLE
Initial thumbnails disappear in storybook local media library pane

### ISSUE THREAD

**Issue by mohdsayed** [swissspidy/web-stories-wp#10300]
## Bug Description

All initial thumbnails on the local media library pane disappeared on [storybook](http://localhost:50045/?path=/story/playground-stories-editor--default) recently however when you scroll down all media at the bottom do show up.

## Screenshots

![image](https://user-images.githubusercontent.com/6297436/150564297-6c40ac9c-37ee-4bbd-99a0-3a6fbbbbe57c.png)

![image](https://user-images.githubusercontent.com/6297436/150564331-3e06acdc-106b-442f-925d-4b27a3b91e48.png)

## Additional Context

- Plugin Version: 1.17.0-alpha.0
- WordPress Version: 5.8.3
- Operating System: Mac OS
- Browser: Chrome, Safari

**Comment by spacedmonkey** [comment]
The dummy data found [here](https://github.com/GoogleForCreators/web-stories-wp/blob/main/.storybook/stories/playground/story-editor/getDummyMedia.js) should be updated with all media fields. Including

- Poster image
- Blur hash
- Base color
- isMuted
- isExternal 
 
Maybe even 

- isOptimized
- needsProxy
