### ISSUE TITLE
Background Audio: Ensure empty `poster=""` attribute for `amp-video`

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10338]
## Feature Description

Right now it looks like our hidden `amp-video` for page background audio might need a poster image.

Filed an upstream issue to get clarification: https://github.com/ampproject/amphtml/issues/37462

**Comment by spacedmonkey** [comment]
Could we maybe reuse the story's poster image?

**Comment by swissspidy** [comment]
Good idea, but that wouldn't really be an accurate representation of the audio/video IMO.

Let's wait for feedback here from the format team.

**Comment by spacedmonkey** [comment]
Maybe we could take a screenshot / image of a the current page of the web story and use that as a poster image.

**Comment by swissspidy** [comment]
We can just use an empty `poster=""` attribute to solve this then.

Might need custom PHP AMP sanitization logic to enforce this; needs testing.
