### ISSUE TITLE
E2E Tests: Move percy uploads to separate job

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10333]
## Task Description

Now that our e2e tests are running in a parallel job, it means that we're uploading Percy snapshots 2 times instead of once
![Screenshot 2022-01-22 at 17 15 20](https://user-images.githubusercontent.com/841956/150646722-30e78f62-b333-4bad-8a2a-54ca3499abf6.png)

To fix this, we need to somehow move the snapshot upload step to its own job that runs after the matrix job, passing around the snapshot files using `actions/upload-artifact`

That means moving away from using `@percy/cli-exec` as-is and probably starting the snapshot server before the test run and stopping it & uploading the snapshots afterwards

```
percy.start()

// run tests in matrix, ensuring that snapshots are not uploaded directly

percy.stop()
```

**Comment by spacedmonkey** [comment]
A while back, I had a quick play with multi-step github actions. Here is what I [made](https://github.com/GoogleForCreators/web-stories-wp/actions/runs/1697999576). To speed up e2e, build once and just run the test in different actions. We could do something similar here maybe...
