### ISSUE TITLE
Karma Improvements

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10345]
## Description

A set of issues based on discovery and discussion done in Dec 2021/Jan 2022 when [karma broke](https://github.com/google/web-stories-wp/pull/10095) with the intention of clearing up some outstanding issues to fortify our integration testing structure. 

### Expected outcome

- Easier/more helpful logs 
- No more fragile tests that sometimes pass and sometimes fail

Link to notes that created this epic: https://docs.google.com/document/d/1W7QorbJoHoQsFdleRhY-1S6CJpTVorPTA_6oh_OQK74/edit#

**Comment by BrittanyIRL** [comment]
@bmattb this should be an epic, i keep updating it and it won't stick? Can you try?

**Comment by swissspidy** [comment]
converted.

edit: actually it really doesn't seem to stick 🤔

**Comment by BrittanyIRL** [comment]
yup. weird, right?
<img width="559" alt="Screen Shot 2022-01-24 at 11 53 06 AM" src="https://user-images.githubusercontent.com/10720454/150845756-9f723957-740b-4679-8ec7-0512e6962f20.png">

**Comment by swissspidy** [comment]
@BrittanyIRL now it worked! :) had to reconnect the repo with ZenHub

**Comment by BrittanyIRL** [comment]
@swissspidy  thank you!!!
