### ISSUE TITLE
Media: Only prevent saving if actually uploading to story

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10341]
## Feature Description

Right now we disable saving a story if _any_ upload is in progress, even if just uploading to the library and not the canvas

Instead, we only want to disable saving a story if any media item within the story itself is currently uploading, as only those are concerning due to blob URLs.

**Comment by felipebochehin87** [comment]
Hi @swissspidy! I found one thing here:

1. When I drag and drop a video to canvas, I see the same issue as we fixed on PR #10373;

Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10343.

https://user-images.githubusercontent.com/96055551/151233764-c6c0a152-1985-41eb-a1b2-808f007df6e7.mp4

**Comment by swissspidy** [comment]
@felipebochehin87 expected, because this PR was opened before that issue got fixed :-) I'll update it real quick, but make sure to test by dragging & dropping a video from your desktop to the canvas (so it uploads), not by dragging from the library to the canvas. We wanna test the uploading part.

**Comment by felipebochehin87** [comment]
Thanks @swissspidy :) will do!

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10343.

1. Dragged and dropped a video - "Save" and "Publish" buttons disabled until upload is complete


https://user-images.githubusercontent.com/96055551/151259743-4b5854b8-3aba-4b9c-954e-6a0e65bd22a0.mp4
