### ISSUE TITLE
Decoupling: Consistent code location of story locking feature

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10340]
## Task Description

In the editor we moved all story locking (`postLock`) functionality to `wp-story-editor`. But there are still some references to `postLock` in `story-editor`.

In the dashboard, all story locking functionality is still in `dashboard`, not in `wp-dashboard` as one would expect.

Should we move that to `wp-dashboard`?

Or should we move everything to the "core" packages?

**Comment by swissspidy** [comment]
cc @sayedtaqui perhaps you have some ideas here

**Comment by mohdsayed** [comment]
Oh, I wasn't aware that the `dashboard` has story locking functionality too. Thanks for creating an issue for it. I will work on moving it to `wp-dashboard` and `story-editor` locking references.

**Comment by swissspidy** [comment]
Here's what it looks like on the dashboard, for reference:

![Screenshot 2022-01-24 at 16 25 02](https://user-images.githubusercontent.com/841956/150811849-fb3d1d6b-bb17-4c6b-b8e9-0848d1ff3aa9.png)

**Comment by mohdsayed** [comment]
> In the editor we moved all story locking (postLock) functionality to wp-story-editor. But there are still some references to postLock in story-editor.

@swissspidy Just to confirm, I see `postLock` in test/fixtures, and `lockUser` refrerences in story. Is there anything else that I am missing in `story-editor` ?

**Comment by swissspidy** [comment]
That's all, I think.

**Comment by mohdsayed** [comment]
Noting down the traces of story locking feature in `dashboard`.

1. Would need to move all related UI from the following files.

-  `packages/dashboard/src/app/views/myStories/content/storyGridItem/storyDisplayContent.js`
-  `packages/dashboard/src/app/views/myStories/content/storyGridItem/components.js`
-  `packages/dashboard/src/app/views/myStories/content/storyGridItem/index.js`
-  `packages/dashboard/src/app/views/myStories/content/storyListItem/index.js`
-  `packages/dashboard/src/app/views/myStories/content/storyListItem/components.js`

If we move the UI, will have to do a lot of prop drilling via these components
```js
InterfaceSkeleton > MyStories > Content > StoriesView > StoryGridView > StoryGridItem
                                                      > StoryListView > StoryListItem
```

2. Move all references of `lockUser` and `locked`.

**Comment by mohdsayed** [comment]
@swissspidy Unlike `story-editor`, the story locking feature is so tightly coupled with `dashboard`, that it doesn't look feasible to me to move it to `wp-dashboard` without some dirty refactoring. Any suggestion?

**Comment by swissspidy** [comment]
Agreed, that would make things super complex. That prop drilling chain looks 😵

I'm inclined to perhaps just keep it like that.

We could even move the current implementation in `wp-story-editor` back to `story-editor` if we want to, for consistency.

But yeah maybe we keep this as a wontfix/maybelater for now? It's not great, but also not a huge deal.

**Comment by swissspidy** [comment]
Thinking about it again, I can see how the general "Someone else is already editing this story" functionality makes sense to live in `story-editor` / `dashboard`. That's a pretty reasonable feature.

I just now wonder whether the `Take over editing` part could be seen as a more platform-specific feature that is better extracted to `wp-story-editor`.

Hmm 🤔

**Comment by mohdsayed** [comment]
@swissspidy What's your thought behind considering "Someone else is already editing this story" a core functionality and "Take over editing" as integration package functionality?

**Comment by swissspidy** [comment]
"Someone else is already editing this story": maybe not a core functionality for the editor, but perhaps for the dashboard.
In the dashboard, displaying avatars of the person(s) currently editing a story is pretty simple and seems like something many integrations could want/need. Just like Google Docs shows who's currently editing a document.

On the editor side, there could be stark differences between integrations.

Some integrations might not want to do anything in the editor, some might want only "Someone else is already editing this story" (which is simple enough, just block editing).

And some might want to offer "Take over editing" functionality, which involves also autosaves and revisions to restore previous versions when someone took over from you.

I guess what I am saying is that an argument could be made for the status quo being OK.

Just thinking out loud here though.

**Comment by mohdsayed** [comment]
Initially, moving the "Someone else is already editing this story" to the core editor looked like a good idea, but when I actually started moving, it didn't feel worthwhile. 

1. If I move `PostLock` to `story-editor` and use it in `wp-story-editor` and pass the props to enable "Take Over" functionality, I end up moving almost everything to achieve that.
2. If I move only `PostLockDialog` to `story-editor` for the sake of keeping the UI in the core editor, we anyways have to pass `dialogContent` and "Take Over" button from `wp-story-editor` and it doesn't feel worthy to only keep such a small component in the core.

May its a wontfix.
