### ISSUE TITLE
Clean up memory leaks

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10347]
Consider adding a `cleanup` from react to fixture.restore and making sure that container, screen, editor are all reset to null. (draft PR #10143)

**Comment by samwhale** [comment]
After some investigation I've found that `cleanup` is [run automatically in our karma tests](https://testing-library.com/docs/react-testing-library/api/#cleanup). I verified this by adding a log in the cleanup function in the node modules.

This change isn't necessary, so I'll close this ticket.
