### ISSUE TITLE
Dragging video into canvas crashes editor

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#10373]
## Bug Description

Clicking and dragging a video into the canvas crashes the editor. This happens with videos in the media panel and the 3p media panel.

## Expected Behaviour

Clicking and dragging videos into the canvas should not crash the editor

## Steps to Reproduce

1. Open the media or 3p media tab in the library
2. Click and drag a video into the canvas
3. Editor crashes

## Screenshots

![image](https://user-images.githubusercontent.com/22185279/151026518-63199c46-aebe-4c26-b652-88ef77a0891d.png)

https://user-images.githubusercontent.com/22185279/151026704-2fc231a6-c9e6-426a-a30a-b43b37ba2ca3.mp4

## Additional Context

Stack trace seems to point to the popover component:
![image](https://user-images.githubusercontent.com/22185279/151027160-253f59fe-3cd6-4f40-9536-615bf5c6a182.png)

- Plugin Version: 1.17.0-alpha.0+e1a8832
- WordPress Version: 5.8.3
- Operating System: MacOSX Big Sur 11.6.2
- Browser: Chrome

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10383.

1. Dragged videos from 3p media library to canvas - no error displayed
2. Dragged videos from media library to canvas - no error displayed
3. Reproduced the same steps against the main branch - errors displayed (which means that this PR fixes the bug)

https://user-images.githubusercontent.com/96055551/151158363-c804854a-1793-475e-b4e5-eb93b6f19c56.mp4
