### ISSUE TITLE
Karma: Add snapshot testing to dashboard

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10392]
## Task Description

Somehow we've never added snapshot testing to the dashboard, but there's no reason why we couldn't do it

## Acceptance Criteria 
- Snapshots for default views 
- Snapshots after scroll + opening a dropdown on settings (response to regression that occurred that's solved here: #10539)

**Comment by timarney** [comment]
> Snapshots after scroll + opening a dropdown on settings (response to regression that occurred that's solved here: https://github.com/GoogleForCreators/web-stories-wp/pull/10539)

☝️ 

@BrittanyIRL do you know if there's a Karma test that covers the regression you fixed in  #10539 looking to add a Snapshot as part of the issue.
