### ISSUE TITLE
Provide a "Fade Out" animation

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10402]
## Feature Description

In speaking with the reps from some well known enterprise publishers, one request that was flagged was for the ability to apply a fade out animation on elements within the canvas. It was noted that this ability would permit for a much more complex presentation on a story page, as every element introduced onto the page would no longer need to persist throughout the page presentation.

I've noted the challenges with this request below, but I still think that it's a valid ask
## Additional Context

As @swissspidy rightly points out, this would potentially open a can of worms around the pre-publish checklist, as now we would likely need to validate that items like text aren't fading out before they can be read.

Additionally, as @littlemilkstudio has flagged, there are issues with the current model where elements are presented on canvas in their final state, meaning they would be invisible (and therefore challenging to select, manipulate, etc)

**Comment by swissspidy** [comment]
> this would potentially open a can of worms around the pre-publish checklist, as now we would likely need to validate that items like text aren't fading out before they can be read.

That's not what I said 🤔  And for the record I don't think we would need to do (or should do) any such validation.

I was merely questioning the usefulness of such a feature, especially without having an animation timeline to handle more complex animations. In other words, how useful is Fade Out without the possibility to also Fade In elements at different times?

Related: #9635, #3414

/cc @gajasinski @aaskedall @agingoldseco

**Comment by bmattb** [comment]
Apologies for both misunderstanding and misquoting you on that @swissspidy.

**Comment by agingoldseco** [comment]
I believe creators do have the ability to fade in elements at different times now, but an issue Fade Out might present is someone wanting to apply more than one animation to the same element, like having it fade in and then out. We can come up with a solution for that in the UI, but it becomes a bigger project than just adding an animation. 

If we don't address that immediately and just add it, curious if it it would make sense to have people choose delay/duration relative to the end of the story segment so it, in most cases, would still persist through most of the page presentation.
