### ISSUE TITLE
Media: Video Trimming affects all instances of video

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10409]
## Bug Description

This is a follow-up to https://github.com/GoogleForCreators/web-stories-wp/pull/9945#issuecomment-1007467673

When trimming a video within a story, currently all instances of that video within the story are being trimmed.

The `useProcessMedia` hook uses `updateElementsByResourceId` to update all instances of a video item within the story.

This makes sense for optimization and probably also muting. But for video trimming this is confusing, as it's not really expected behavior as a user.

## Expected Behaviour

When trimming one instance of a video, it should only trim the current instance, not all instances of it.

We should not use `updateElementsByResourceId` for trimming.

## Steps to Reproduce

1. Drag video from media library to a page
2. Drag the same video from media library to a page (same page or new one)
3. Trim first video
4. Observe that both are now trimmed once completed

## Additional Context

- Plugin Version: 1.16.0
- WordPress Version: 5.9
- Operating System: macOS
- Browser: Chrome

**Comment by timarney** [comment]
> Observe that both are now trimmed once completed

Adding a note while I track this down.

Looks like given  2 videos on the screen the trim data gets applied to both as soon as TRIMMING starts

<img width="1348" alt="Screen Shot 2022-02-10 at 8 09 05 PM" src="https://user-images.githubusercontent.com/62242/153523092-da552df3-d1aa-4613-b950-48b3cd9d11b9.png">

**Comment by swissspidy** [comment]
Yeah the `useProcessMedia` hook which is responsible for this does update videos on start, on error, and on success.

The relevant code is here:

https://github.com/GoogleForCreators/web-stories-wp/blob/1aeacb30f5234b87947065919d801b5fb4bc3a91/packages/story-editor/src/app/media/utils/useProcessMedia.js#L173-L263

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10554.

1. Dragged a video from my local and dropped into the canvas
2. Repeated step 1 (same video)
3. Trimmed the 1st video - only 1st video is trimmed, the 2nd one remains the same
