### ISSUE TITLE
Canvas: Links no longer show Tooltip on hover. 

### ISSUE THREAD

**Issue by BrookeGraham** [swissspidy/web-stories-wp#10428]
## Bug Description

While cleaning up karma test in #10194, found the design link karma test was disabled citing it being flakey. However I found that the test wasn't grabbing the correct "tooltip" element. Either while this test was disabled or due to it testing the wrong thing a regression occurred causing links to no longer show a `tooltip` when hovering on the link element on the canvas. 

## Expected Behaviour

Tooltip should appear when hovering an element with a link. Karma test `CUJ: Creator Can Add A Link: Apply a link to any element should display the link tooltip correctly'` should be updated to grab the tooltip, and it should pass. 

## Steps to Reproduce

Add text element. 
Click `Link` in design panel
Add url
Deselect the text element on the canvas
Hover the text element
`Tooltip` should appear but does not. 

## Additional Context

- Plugin Version: 1.16.0
- WordPress Version: 7.4
- Operating System: OSX
- Browser: Chrome Version 97.0.4692.99 (Official Build) (x86_64)

**Comment by merapi** [comment]
I can't even select the element with link (and it disappears when you group move it):

https://user-images.githubusercontent.com/21036224/151963307-680a0299-fe82-4ca7-a158-e7895f4a6591.mov
