### ISSUE TITLE
Background Audio: Display captions in editor on play

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10439]
## Feature Description

When playing background audio in the editor and the audio has captions, it would be nice to display them in the editor for a better WYSIWYG experience.

The `VideoCaptionsLayer` component needs to be updated to check for captions existence and to find the audio player on the page.

The audio player needs to be updated to include the `track` (with `kind="metadata"`) so it's not otherwise visible)

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10514.

1. Added an image to the canvas
2. Added an audio to the background
3. Added subtitles to the audio file
4. Played audio file


https://user-images.githubusercontent.com/96055551/153645730-f69ef170-cc7e-46d0-a196-17fd61dffc84.mp4
