### ISSUE TITLE
Side menu is covering some controls making them unselectable

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#10441]
## Bug Description

As in the title - please check the attached video.

## Screenshots

https://user-images.githubusercontent.com/21036224/152161556-2d6eee06-fbba-4910-9d7d-46d8b790d4aa.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11138.

1. Added elements to the canvas
2. Expanded them until they reach side menu - right edge handle still works
3. Expanded more - right edge handle still works
4. Side menu buttons still work
