### ISSUE TITLE
Replace `react-photo-gallery`

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10444]
## Feature Description

The `react-photo-gallery` package we're using for the media library hasn't been updated in over 3 years.

We already had to patch it once in #4438 because of the outstanding bugfix in https://github.com/neptunian/react-photo-gallery/pull/184 that hasn't been merged to this day.

Another issue is that the library doesn't officially declare support for React 17, causing some issues with duplicated React dependencies (https://github.com/neptunian/react-photo-gallery/issues/205).

I think it's time we look for alternatives.

One often named alternative is https://github.com/igordanchenko/react-photo-album which has a very similar API. Docs: https://react-photo-album.com/

My hope is that it's gonna be almost a drop-in replacement.

**Comment by swissspidy** [comment]
Another reason for a replacement:

https://github.com/GoogleForCreators/web-stories-wp/issues/10597#issuecomment-1046823837

**Comment by swissspidy** [comment]
Assigning to Prometheus pod as per discussion with @miina 

#10737 solves this, but needs figuring out why drop targets don't seem to work reliably anymore.

See thread at https://xwp.slack.com/archives/CCCAUAH6F/p1645802324147119 for some context

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR 10737.

1. Regressed adding images from library to canvas
2. Regressed adding videos from library to canvas
3. Regressed drag and drop from local to canvas
4. Regressed upload images from local to insert to canvas
5. Regressed upload videos from local to insert to canvas
