### ISSUE TITLE
Custom Fonts: support `woff2`

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10440]
## Feature Description
See the [discovery issue](https://github.com/GoogleForCreators/web-stories-wp/issues/10020) and comments for options to support `woff2`.

Summary:the libraries that support `woff2` and claim to have browser support don't actually really have browser support, thus we'd need a custom implementation / modifications to support it.

**Comment by swissspidy** [comment]
Closing for now to keep the backlog clean. We can reopen when there's demand & library support.
