### ISSUE TITLE
Documentation: Auto-generate code reference

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10455]
## Feature Description

Similar to other open source projects, like WordPress, the web stories plugin, should have some level of automated documentation about for code. This documentation should provide a search interface for finding functions/classes and methods in the plugin. This documentation, would list params and return types for functions. 

This documentation would make it easier for third parties to integrate with this plugin and extend it. 

## Alternatives Considered

- https://phpdox.net/index.html
- https://phpdoc.org/

**Comment by swissspidy** [comment]
There's also https://github.com/johnbillion/wp-hooks-generator just for hooks
