### ISSUE TITLE
Establish good practices around transient props ($ prefixed)

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#10468]
## Summary

Follow-up ticket from Slack discussion: https://xwp.slack.com/archives/CCCAUAH6F/p1643891495809269

Maybe a cheat sheet on when to use them will be enough 
or we might want to create an ESLint rule(s) to flag unnecessary `$` usages or advice this usage.

**Comment by swissspidy** [comment]
Regarding ESLint I already created a ticket for that: #6669
