### ISSUE TITLE
Rework how resizing Text element works

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10466]
## Feature Description
In https://github.com/GoogleForCreators/web-stories-wp/issues/10106 the design panel ratio lock was related to resizing the elements, however, since it's not clear right away that these are related, there was some feedback about issues with resizing text.

Since the Text element works differently than the other elements (e.g. height is auto-set with unlocked ratio), we should unrelate the design panel lock and resizing on the Page for Text element, and revert the changes to what it was before (for Text only!)

The rest of the elements will still be dependent on the lock in the Design panel and "locked" by default except for Image and Rectangle.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10490.

1. Added a text element
2. Resized from corners
3. Resized from edges
4. Tested with both locked and unlocked aspect ratio


https://user-images.githubusercontent.com/96055551/153023094-b8a9030e-cf6e-4b3b-b740-971a6d2b32d9.mp4
