### ISSUE TITLE
Code Quality: Clean up Checkpoint Provider Access

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10470]
## Feature Description

When #10115 is wrapped up and no longer behind a feature flag we'll be able to gut a chunk of the checklist context. The new story details modal that is part of 10115 is reusing the reviewChecklist action in the checkpoint hook, that can get cleaned up too. Other areas that can get cleaned up now: Publish button - doesn't need to know status of any checks anymore.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11197.

Regressed publish flow.
