### ISSUE TITLE
E2E Tests: broken Percy snapshots

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10486]
## Task Description

For some reason the Percy snapshot for the `Story Background Audio` e2e test is always broken, see screenshots below.

It would be nice to find out why & fix it.

**Note:** testing locally is preferred so that we don't wastefully upload tons of snapshots to Percy.

![Screenshot 2022-02-07 at 00 14 28](https://user-images.githubusercontent.com/841956/152705651-ea007f84-4bcf-43b5-9374-3e90292102ee.png)

![73eef55ce8d431f35a87748e8fd83479fae959803fc32dbcef3915cce42493ab](https://user-images.githubusercontent.com/841956/152705644-0326bf71-bbcd-4e1f-836b-185369d8b552.png)

**Comment by miina** [comment]
Another seemingly broken snapshot, for "Get Started Story":
<img width="402" alt="Screenshot 2022-02-09 at 12 54 28" src="https://user-images.githubusercontent.com/3294597/153184693-d4ec63f5-0cec-4e0c-bf31-18212995de4f.png">

**Comment by timarney** [comment]
I can replicate the "broken snapshot" screen running Percy locally (not via CI) --- so I can dig deeper on that part to start.

https://github.com/GoogleForCreators/web-stories-wp/issues/10486#issuecomment-1033631848

For "Story Background Audio" I get this for an output

![4ebe5dfed03a3d482e98cdff3193ed92c96ace96ea3fa3d6ebaeb69a7ad9801d](https://user-images.githubusercontent.com/62242/154378039-f8a60088-3b52-4d78-849e-847c294cd374.png)


---
Same test screens outside of the editor render properly.

![46482f530f7d5f70480c2e150ae752eccc827d02f58022dbd50aa0ac4b7fa705](https://user-images.githubusercontent.com/62242/154383166-b23728a5-62f8-40da-8a95-dd31f6bcb863.png)

---


---

As for the "unstyled" Admin --- unclear as to why that's happening.  I contacted Percy support to see if that turns up anything.

I did find some screens online that seems to be similar.  This appears to be related to load-styles.php possibly around `CONCATENATE_SCRIPTS` issues or Cross origin related (http vs https)

https://wordpress.org/support/topic/admin-pages-unstyled-and-unformatted/


<img width="500" alt="Screen Shot 2022-02-16 at 7 08 30 PM" src="https://user-images.githubusercontent.com/62242/154378730-1c0885f2-f641-44da-867a-53ac3b621ab9.png">

<img width="500" alt="Screen Shot 2022-02-16 at 7 03 18 PM" src="https://user-images.githubusercontent.com/62242/154378285-411d48f1-5fd0-4a90-9722-e49d660ac62b.png">


<img width="682" alt="Screen Shot 2022-02-16 at 12 36 45 PM" src="https://user-images.githubusercontent.com/62242/154378228-b03bad13-80e0-45fc-9b9a-3f5dc34c9839.png">

**Comment by timarney** [comment]
Testing with 5.8.3 locally 🤔 

<img width="500" src="https://user-images.githubusercontent.com/62242/154544219-08d3cda6-a470-4446-b647-4cf981cefb8f.png"  />

**Comment by spacedmonkey** [comment]
I think the key issue here, is the missing images. That means that images can not be served, meaning the docker container is not reachable or has a ssl error.

**Comment by timarney** [comment]
Okay 

**builds/15757883**

So the "unstyled Admin" is from Safari

https://percy.io/google/web-stories-wp-e2e/builds/15757883/unchanged/889282071?browser=safari&browser_ids=18%2C20&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600

The same run from Chrome looks like
https://percy.io/google/web-stories-wp-e2e/builds/15757883/unchanged/889282071?browser=chrome&browser_ids=18%2C20&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600

**Comment by timarney** [comment]
Safari snapshots are now disabled.

**Comment by timarney** [comment]
Passed along a debug log to Percy support 

Added these for a local run to get logs to print to the console

```
LOG_LEVEL=debug PERCY_DEBUG=* 
```

**Comment by swissspidy** [comment]
Closing as this seems to be fixed
