### ISSUE TITLE
Element alignment keyboard shortcuts conflict with browser control

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10489]
## Bug Description

In #625 (2 years ago!) we added functionality to the design panel to more easily align and distribute elements on the canvas (see screenshot below)

Some of these buttons were also made accessible as keyboard shortcuts:

<table>
<tr>
	<td><b>Shortcut
	<td><b>macOS
	<td><b>Windows
<tr>
	<td>Align left
	<td><kbd><kbd>⌘</kbd>+<kbd>{</kbd></kbd>
	<td><kbd><kbd>Ctrl</kbd>+<kbd>{</kbd></kbd>
<tr>
	<td>Align center
	<td><kbd><kbd>⌘</kbd>+<kbd>H</kbd></kbd>
	<td><kbd><kbd>Ctrl</kbd>+<kbd>H</kbd></kbd>
<tr>
	<td>Align right
	<td><kbd><kbd>⌘</kbd>+<kbd>H</kbd></kbd>
	<td><kbd><kbd>Ctrl</kbd>+<kbd>}</kbd></kbd>
</table>

Unfortunately these shortcuts clash with keyboard shortcuts provided by the browser itself.

For example, <kbd><kbd>⌘</kbd>+<kbd>H</kbd></kbd> hides the current browser window.

And when I try to press  <kbd><kbd>⌘</kbd>+<kbd>{</kbd></kbd> on my US keyboard (for which I need to press <kbd>⌘</kbd> <kbd>⇧</kbd> and <kbd>[</kbd>), that actually triggers the "Select previous tab" shortcut in Chrome.

**That means these shortcuts might have never actually worked!**

**NB:** the keyboard shortcuts are not displayed in the keyboard shortcuts modal either.

## Expected Behaviour

Conclusion: For now, we will remove the shortcuts, see comments thread below.

Element alignment shortcut should not clash with browser.

Alternatively, we should consider just removing the shortcuts.

For context, here are the keyboard shortcuts Figma uses for similar actions:

Action | Shortcut
-- | --
Align left | <kbd><kbd>⌥ </kbd><kbd>A</kbd></kbd>
Align right | <kbd><kbd>⌥</kbd> <kbd>D</kbd></kbd>
Align top | <kbd><kbd>⌥ </kbd><kbd>W</kbd></kbd>
Align bottom | <kbd><kbd>⌥ </kbd><kbd>S</kbd></kbd>
Align centers | <kbd><kbd>⌥</kbd><kbd>H</kbd></kbd> and <kbd><kbd>⌥</kbd><kbd>V</kbd></kbd>
Distribute spacing | <kbd><kbd>⌃</kbd><kbd>⌥</kbd><kbd>H</kbd></kbd> and <kbd><kbd>⌃</kbd><kbd>⌥</kbd><kbd> V</kbd></kbd>

## Steps to Reproduce

Try using the keyboard shortcuts in the editor

## Screenshots

![Screenshot 2022-02-07 at 10 57 10](https://user-images.githubusercontent.com/841956/152765856-8825e80a-e826-4938-95d5-ee1d6c20684c.png)

## Additional Context

- Plugin Version: 1.17.0
- WordPress Version: 5.9
- Operating System: macOS or Windows
- Browser: all?

**Comment by swissspidy** [comment]
@aaskedall @agingoldseco @gajasinski @miina curious to hear your thoughts on this one

**Comment by miina** [comment]
Related: https://github.com/GoogleForCreators/web-stories-wp/issues/6595 -- probably can be closed as the new issue has more details.

**Comment by miina** [comment]
> curious to hear your thoughts on this one

If no one (except for Morten) has mentioned the shortcuts not working during these 2 years, perhaps these are not missed by any of the users really and could be removed for now.

Not sure if there are any common shortcuts for these that could feel familiar for the editors -- I suppose WordPress doesn't use shortcuts for aligning?

**Comment by swissspidy** [comment]
> I suppose WordPress doesn't use shortcuts for aligning?

There are shortcuts for _text alignments_ but there is no canvas to align elements, so it doesn't really apply to WP.

I shared Figma shortcuts above, but I am sure other tools have those as well. We could also check out how other story creation tools do it.

**Comment by agingoldseco** [comment]
I think we make the buttons readily available enough that we can remove the useless "shortcuts" now rather than waiting until we have new ones—I just tried a few of them and they were indeed just browser shortcuts. We can see if anyone says anything once they are removed, but this seems unlikely if no one's complained yet.

**Comment by swissspidy** [comment]
Sounds reasonable 👍 

Removing for now and then thinking of new ones if really needed.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10902.

1. Created a story
2. Added elements
3. Tried using shortcuts - removed as expected
4. Used side menu and floating menu buttons - working as expected

https://images.zenhubusercontent.com/235435637/a832cdaa-f632-4834-9987-743614c805a4/10902.mp4
