### ISSUE TITLE
Layer selection incorrectly detects rotated elements under the cursor

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#10519]
## Bug Description

~Layer selection in the right-click menu seems to detect elements under the cursor incorrectly. Please check the video.
Extracted from https://github.com/GoogleForCreators/web-stories-wp/pull/10458#discussion_r801805256~ Fixed in #11163

Note that this also happens for auto-setting background. Rotated media is sometimes set as background even if it doesn't fully cover the page.

## Expected Behaviour
- ~When using the "Select Layer" option in the right-click menu, it should only display the elements directly under the cursor and not include nearby rotated elements~ Fixed in #11163
- When rotated media is resized to be covering the Page mostly but not fully (e.g leaving the corners out), it should not be auto-set as background.

## Steps to Reproduce
1. Add a media element to a page
2. Rotate it
3. Try to cover the entire canvas to make it background image and see that it does not always trigger correctly (triggers before actually covering the full canvas)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11163.

1. Added multiple rectangles (one over the other)
2. Right clicked on different parts of the canvas - where we have intersection of elements, we have displayed rectangles (the number of rectangles that are at the position that has been right clicked) on Select Layer & where we have only one rectangle, we only see one rectangle on Select Layer


https://user-images.githubusercontent.com/96055551/162016340-1eb766db-1f12-4b76-96ec-1a9841adda69.mp4
