### ISSUE TITLE
MockMoveable function doesn't exist

### ISSUE THREAD

**Issue by c0b41** [swissspidy/web-stories-wp#10536]
`@googleforcreators/moveable` package exporting nonexistent function..

https://github.com/GoogleForCreators/web-stories-wp/blob/296cf2e6abc39b8afb5d0420a3a0f734be2b336d/packages/moveable/src/index.js#L20

![image](https://user-images.githubusercontent.com/2834954/153420057-8cc0609e-c6d5-4ebc-b00d-e75f2c073218.png)

**Comment by swissspidy** [comment]
Thanks for reporting! We'll get this sorted

**Comment by mohdsayed** [comment]
This was recently moved in https://github.com/GoogleForCreators/web-stories-wp/pull/10399 here
https://github.com/GoogleForCreators/web-stories-wp/pull/10399/files#diff-7fcc7f7e4bced1ad0bf5c4e48977105eb52a27383a5b0eb1b8493e652570797cL22 and is only being used fo unit test in `story-editor` package, but yes it doesn't exist and is mocked here https://github.com/GoogleForCreators/web-stories-wp/blob/main/__mocks__/react-moveable.js
