### ISSUE TITLE
Settings: DropDown opening in wrong position

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10538]
## Bug Description

A regression snuck through recent efforts to deduplicate popup usage (#10089 ) 

![Screenshot 2022-02-10 at 15.51.29.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/9d5f9c66-bea5-4343-ba2c-88428f6d96d7)

## Expected Behaviour

Open dropdown menu should show either directly below or above (depending on space) its affiliated input. 

## Steps to Reproduce

Go to Settings and open dropdowns after you have scrolled. 

## Additional Context

An important part of this update: https://github.com/GoogleForCreators/web-stories-wp/pull/6533/files was overwritten

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10539.

1. Visited Settings page
2. Clicked on the dropdown - dropdowns opened in the expect location (below by default, if no space below, opened above)
3. Tried both RTL and LTR


https://user-images.githubusercontent.com/96055551/153465879-41648c37-d641-48fd-9278-bd63604a68bf.mp4
