### ISSUE TITLE
Incompatibility with WPGraphQL plugin

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10533]
## Bug Description

As per [this support topic](https://wordpress.org/support/topic/issue-breaking-wpgraphql-plugin/), there is a known bug in [WPGraphQL](https://github.com/wp-graphql/wp-graphql/issues/2065) that causes errors when registering settings with type `array` or `object`.

We can work around this by hiding these settings from the GraphQL schema.

## Expected Behaviour

No conflicts

## Steps to Reproduce

1. Install both the Web Stories plugin and the WPGraphQL plugin
2. Visit the GraphiQL IDE and see that there's no schema loaded

## Additional Context

- Plugin Version: 1.17.0
- WordPress Version: 5.9
- Operating System: macOS
- Browser: Chrome

**Comment by spacedmonkey** [comment]
Looping in @jasonbahl for his advice on the matter.

**Comment by swissspidy** [comment]
As mentioned above this known bug is explained in detail at https://github.com/wp-graphql/wp-graphql/issues/2065

**Comment by jasonbahl** [comment]
I've got a PR up that fixes this conflict: https://github.com/wp-graphql/wp-graphql/pull/2262
