### ISSUE TITLE
Fonts package doesn't have font list

### ISSUE THREAD

**Issue by c0b41** [swissspidy/web-stories-wp#10537]
fonts package currently only releasing javascript files, and don't have `packages/fonts/src/fonts.json` file and this is feature request not bug.

**Comment by mohdsayed** [comment]
@swissspidy  If we just export `fonts.json` from `packages/fonts/src/index.js`, it will bundle `fonts.json.js` file, will that work or do we specifically need `.json` file ( in which case we will have to copy the json file in the dist directory using some rollup plugin like `rollup-plugin-copy` and can be used as `import fonts from "@googleforcreators/fonts/fonts.json"`  )? 

```js
export { default as fonts } from './fonts.json';
```

**Comment by swissspidy** [comment]
I'd prefer an actual JSON file 👍
