### ISSUE TITLE
Web Stories Live Story

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#10530]
## Feature Description

A user has requested a way to make stories live, similar to the [AMP concept here](https://amp.dev/documentation/components/amp-story/#live-story) of adding new pages to a story for users to see in real-time using the live-story attribute.

## Additional Context

Related topic: https://wordpress.org/support/topic/for-breaking-news-how-add-live-story-meta-tag/

**Comment by swissspidy** [comment]
Closing this for now to keep our backlog tidy, since it's not on the immediate roadmap
