### ISSUE TITLE
Justify Text Alignment Off in FireFox Browser

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#10542]
## Bug Description
Justify text behavior seems off/different in Firefox browser versus Chrome browser. View [this example story](https://testsite.cmsdevrel.com/web-stories/justified-text-test/) in Chrome then compare it in Firefox.

## Expected Behaviour

For the justify text alignment to apply accordingly. 

## Steps to Reproduce

1. Open Chrome browser 
2. Add Text > Justify text
2. View it in Chrome. Then view it in Firefox.
3. Open Firefox browser
4. Add Text > Justify text
5. Note behavior

## Screenshots
Firefox:
<img width="1032" alt="Screen Shot 2022-02-10 at 4 19 20 PM" src="https://user-images.githubusercontent.com/66372350/153498517-8281babe-dbc9-4491-b2a8-27ddc9cc2ff1.png">
Chrome:
<img width="1016" alt="Screen Shot 2022-02-10 at 4 19 53 PM" src="https://user-images.githubusercontent.com/66372350/153498544-e332a2a8-e031-49fd-bc65-83650a131345.png">

## Additional Context
related topic: https://wordpress.org/support/topic/justified-button-not-working-in-editor/

- Plugin Version: 1.17.0
- WordPress Version:
- Operating System: macOS
- Browser: Firefox

**Comment by swissspidy** [comment]
What does it look like in the frontend preview in both browsers? What does it look like in Safari?

**Comment by LuckynaSan** [comment]
Chrome
<img width="487" alt="Screen Shot 2022-02-11 at 9 17 14 AM" src="https://user-images.githubusercontent.com/66372350/153607605-4c2a4486-e138-4c4d-bf45-d376131b0e96.png">

Safari
<img width="596" alt="Screen Shot 2022-02-11 at 9 16 59 AM" src="https://user-images.githubusercontent.com/66372350/153607643-3643f112-3e7d-4bd1-9297-bc6de05bde93.png">

Firefox
<img width="849" alt="Screen Shot 2022-02-11 at 9 16 47 AM" src="https://user-images.githubusercontent.com/66372350/153607675-63679595-bf65-423f-8eab-b2b2431482fa.png">

**Comment by barklund** [comment]
We can't both have `white-space: pre-wrap` and `text-align: justify` on an element in Firefox and Safari. The former makes the latter ineffective, but only in non-Chrome browsers. And we need `white-space: pre-wrap` to make newlines render.

However, [`white-space: pre-line`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#:~:text=fill%20line%20boxes.-,pre%2Dline,characters%2C%20at%20%3Cbr%3E%2C%20and%20as%20necessary%20to%20fill%20line%20boxes.,-break%2Dspaces) **does work correctly** with justified text across all browsers! Only real difference is, that this would not allow authors to create space between words by adding multiple spaces - this would be collapsed to a single space with `pre-line`.

Is that a potential problem? Do we use multiple spaces to add longer gaps between words in any text sets or templates?

CC @agingoldseco, @aaskedall

**Comment by felipebochehin87** [comment]
@barklund @mariana-k @merapi 

On Firefox, the text is not displayed Justified when we are on Preview Story mode.

https://images.zenhubusercontent.com/235435637/bcfbb8d5-879b-4a4a-aa29-49792388f30a/2022_05_04_11_46_12.mp4

**Comment by barklund** [comment]
> On Firefox, the text is not displayed Justified when we are on Preview Story mode.

Fixed, please check again!

**Comment by felipebochehin87** [comment]
Retested in Firefox. Looks good now.
