### ISSUE TITLE
`Insert text` tooltip placement incorrect in RTL

### ISSUE THREAD

**Issue by BrookeGraham** [swissspidy/web-stories-wp#10547]
## Bug Description

Tooltip placement issue for `Insert Text` quick action, it isn't getting moved when in RTL.

## Expected Behaviour
Should appear on the left of the quick actions when in `RTL` along with all the other quick action tooltips

## Steps to Reproduce
in RTL, hover over quick action `insert text` notice it is place to the right, whereas all other quick action tooltips appear on the left. 

## Screenshots
|:(|:)|
|--|--|
|<img width="250" alt="Screen Shot 2022-02-10 at 10 00 27 AM" src="https://user-images.githubusercontent.com/1820266/153461209-695de590-ff66-4555-9432-ac24cabe6986.png">|<img width="282" alt="Screen Shot 2022-02-10 at 4 26 08 PM" src="https://user-images.githubusercontent.com/1820266/153514007-696c6a1b-6fc3-438a-92f7-ca63a94c50a6.png">|

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by amovar18** [comment]
@BrookeGraham looked into this it could be solved by adding `...actionMenuProps` just after line 471 in `packages/story-editor/src/app/highlights/quickActions/useQuickActions.js`

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10650.

1, Clicked on the background
2. Hovered over buttons - tips are displayed as expected
