### ISSUE TITLE
Tooltip maximum depth error on hover

### ISSUE THREAD

**Issue by BrookeGraham** [swissspidy/web-stories-wp#10546]
## Bug Description
 When in `RTL` if a `TOOLTIP` is cutoff the left edge of the screen AND cutoff by the bottom of the screen we run into an infinite loop. Likely due to `bottom` and `end` placement overrides fighting one another? 

## Expected Behaviour

App shouldn't crash when hovering over a tooltip. 

## Steps to Reproduce

In `RTL` mode, Open Layers panel and scroll until the `duplicate` and `trash can` icons are just in view. 
Hover the `duplicate` icon and leave mouse positioned over icon. 
Wait a few seconds and you'll get the exceeded max depth error. 

## Screenshots
![Kapture 2022-02-10 at 10 23 48](https://user-images.githubusercontent.com/1820266/153462358-55c2c2e5-7739-4c7e-bff5-df6ee8db7350.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by amovar18** [comment]
@BrookeGraham looked into this i think it could be solved by adding `ignoreMaxOffsetY` just in `Tooltip` component inside the story-editor.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10668.

1. Opened the app on RTL mode
2. Hovered over the Duplicate Layer icon
3. Waited for a few seconds - max depth error was not displayed
