### ISSUE TITLE
Use composer to install WordPress for unit tests

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10541]
## Feature Description

Currently, there is a bash script to install WordPress for unit tests. However with packages like [wp-phpunit](https://github.com/wp-phpunit/wp-phpunit) this is not required. Installing via composer, means that install will be quicker and cached. 

Related https://github.com/google/site-kit-wp/pull/2581

**Comment by swissspidy** [comment]
Would have to see how well it works with PHPUnit-Polyfills.

Also worth noting that switching to wp-env (if that's ever easily possible) would make this obsolete because then everything is running within a Docker container.

Putting this in the backlog for now.

**Comment by spacedmonkey** [comment]
A good example for CI is the [performance](https://github.com/wordpress/performance) project.

**Comment by swissspidy** [comment]
Current blocker for wp-phpunit: https://github.com/wp-phpunit/issues/issues/10
