### ISSUE TITLE
Pause icon has the wrong icon (globally)

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#10561]
## Bug Description

When the user hits "Play" to preview an audio file, the button icon changes to the Stop icon, but when hovering over the button, the hint reads "Pause". I kindly suggest changing the icon to the universal "Pause" icon ![image.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/e8cc050c-2690-44af-84f5-25978528eafc)

Also here (check the whole editor for this icon):
The icon on the background audio playback controls shows "Stop" icon however the button is a pause button
<img width="354" alt="image1" src="https://user-images.githubusercontent.com/58738530/179244966-029a2674-9996-4230-97ca-379729ef7e7c.png">

## Expected Behaviour

The icon should be "Pause" [ | | ] ![image.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/3141f89e-5356-4fdf-82ce-387a2639a947)

## Steps to Reproduce

1. Create a new story
2. Add an audio file
3. Click on Play to preview audio file
4. Hover over the Stop button

## Screenshots

![stop button or pause button.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/4205d563-ebb8-4a5f-b9ce-4e58f2e257dd)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by merapi** [comment]
We also use this ⏹️  icon in other places, should we fix it everywhere?

![image](https://user-images.githubusercontent.com/21036224/153884911-fd53dc28-92bd-4cf3-b25a-fedb50454d3a.png)

Back in the days, it was ⏸️ :
![image](https://user-images.githubusercontent.com/21036224/153884980-2dcc26dd-9c9d-45fd-89ee-61997b246268.png)
