### ISSUE TITLE
Semantic Headings: Enable new feature by default

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10563]
## Task Description

We want to enable the semantic headings feature by default for 1.18, as per the [documented approach](https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/feature-flags.md#enabling-feature-flags-by-default).

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10612.

1. Added texts
2. Added cover text sets
3. Added paragraphs
4. Changed font sizes - text elements wrapped in the expected size (h1, h2, h3, ...)
