### ISSUE TITLE
Visibility Panel: Redesign

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10579]
In the latest editor redesign, the visibility panel is getting updated from the legacy 3 radio buttons into a dropdown. This ticket is to handle that update in this panel. **Functionality on select will remain the same as this is required by WordPress.** 

Figma lives here: 
- [story details modal](https://www.figma.com/file/ZrO763yvMWJjYeAPsRnNfW/_Editor---Sprint-Feature-Level-Designs_2022?node-id=57%3A14792)

## Acceptance Criteria 
- Update e2e tests accordingly 
- Regression testing on panel visibility as used in both editor and story details publish modal 
- keyboard accessibility

**Comment by felipebochehin87** [comment]
@BrookeGraham @BrittanyIRL 

Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10582.

There's an issue when switching from "Private" to "Password Protected":
1. Click on the visibility dropdown and select "Private"
2. After that, click on the visibility dropdown again and select "Password Protected" - the app displays "Public" selected.


https://user-images.githubusercontent.com/96055551/154648538-decf4a39-30a3-44d1-93f1-81659c3ce123.mp4

**Comment by BrookeGraham** [comment]
Hi @felipebochehin87 Sorry about that. Should be good to test again.

**Comment by felipebochehin87** [comment]
@BrookeGraham no prob :) retested!

Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10582.

1. Clicked on the background
2. Opened Document panel
3. Clicked on the dropdown under Visibility 
4. Switched from Public to Private, from Private to Public, from Password Protected to Public, etc... - values are displayed as expected within the field


https://user-images.githubusercontent.com/96055551/154734942-7911f04f-791e-4731-88fc-a0904fddfb41.mp4
