### ISSUE TITLE
Support specifying the ranking/order of the items presented in the Story Carousel

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10576]
## Feature Description

As a publisher using the story carousel we would like the ability to specify the order of the story presentation as this will provide us additional editorial control.

**Comment by swissspidy** [comment]
To clarify, you are talking about the Web Stories Gutenberg block which offers a carousel layout?

That block supports displaying the latest stories ordered by date or by title, as well as displaying selected list of stories in whatever order desired.

And for latest stories there's also a ticket to support grouping/filtering by taxonomies, see #8897

So I am not sure what other types of ordering are missing here and definitely need some clarification.
