### ISSUE TITLE
SEO: Support adding a separate `<title>` in the editor

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10575]
## Feature Description

Story creators would like the ability to be able to specify the SEO Headline title in the editor in order to specify SERPs with a title of their choosing. This SEO Headline title may be different than the title of the story in the editor and may not always be manually supplied, but will permit an extra level of control over how this web story is surfaced in search engine result pages.

**Comment by swissspidy** [comment]
Our recommendation is to use existing SEO plugins like Yoast SEO, Rank Math, or others, which all work great with the editor through their custom meta boxes. They provide the ability to add custom titles, meta descriptions, structured data and much more. It doesn't make much sense for us to duplicate all of this functionality in the story editor when there is a great ecosystem of WP plugins that offer this.
