### ISSUE TITLE
Story Locking: Enable baseline implementation by default

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10587]
## Task Description

Since we split up the story locking feature and the takeover functionality into two separate feature flags, we want to first enable the baseline story locking feature by default in the next release.

This means enabling the `enablePostLocking` feature by default ([as per the docs](https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/feature-flags.md#enabling-feature-flags-by-default)) and getting another round of QA on it.

**Comment by swissspidy** [comment]
Just noting that we should not be picking this up before the 1.18.0 release, since enabling this feature is slated for 1.19.0.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10795.

Avatar:

![10795_06](https://user-images.githubusercontent.com/96055551/156925965-a7328e6b-71d7-4b86-bdd0-92e78326a874.png)
![10795_05](https://user-images.githubusercontent.com/96055551/156925966-c43d4707-9dda-4a6b-bf78-b96fae2f282d.png)


No avatar:

![10795_07](https://user-images.githubusercontent.com/96055551/156925986-b11ba74f-f4bf-428e-acf1-f6b957f0c465.png)
![10795_04](https://user-images.githubusercontent.com/96055551/156925988-506221dc-f3b3-4dcb-837e-0d9ee20ce923.png)


Message:

![10795_01](https://user-images.githubusercontent.com/96055551/156925991-e9f9ee87-930c-42ec-8e60-3e45de4828b6.png)


Hint:

![10795_08](https://user-images.githubusercontent.com/96055551/156925993-17f4a2f6-8fa5-4817-9bdc-b18c060badb2.png)
