### ISSUE TITLE
New Story Details Modal: Upload/Edit Featured Media From Cover Preview

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10584]
Pulled this out of #10115 which was the entire story details modal in an effort to get a v1 of the modal done on time. Talked to @aaskedall and he was ok with this per comment here: https://github.com/GoogleForCreators/web-stories-wp/issues/10115#issuecomment-1032754948 

I know there's a shared component for updating the featured media, this is different because of the way it's styled, so maybe a variant there to avoid having to duplicate the process? 

![Screen Shot 2022-02-15 at 5.11.58 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/16e89ad8-1c4c-4d6b-b058-48861b356e60)

## Acceptance criteria 
- Enabling the edit button on the cover preview of story details modal
- Corresponding unit, karma, e2e tests

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10731.

1. Enabled new pre-publish confirmation modal
2. Opened editor
3. Added images and videos to the story
4. Clicked on Publish
5. Hovered over the cover image - "edit" pencil was displayed
6. Clicked on the pencil - upload image pop-up was displayed
7. Selected an image - if size fits the canvas, no crop option is displayed; if image is too big, crop image option is displayed
8. Cropped image - working as expected
9. Cancelled publishing
10. Repeated steps 4, 5, 6, 7, 8 - image was updated
