### ISSUE TITLE
Media: Move list of transcodable mime types to JS

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10591]
## Task Description

We currently have this hardcoded list of video mime types supported by FFmpeg in PHP here that we simply pass to the editor via the inline config:

https://github.com/GoogleForCreators/web-stories-wp/blob/19aa34528cadcb2b0554d76ccb19ff3537c7cf39/includes/Media/Types.php#L175-L202

It does not make sense for this to live there because this list is hardcoded and is coupled to the FFmpeg binary. Passing this via config just makes any custom editor implementation (in a decoupled context) unnecessarily cumbersome.

**To-do**

* Remove this hardcoded list from PHP
* Define a new `TRANSCODABLE_MIME_TYPES` array in `packages/story-editor/src/app/media/constants.js`
* `export * from './constant.js` in `packages/story-editor/src/app/media/index.js`
* Change all usage of `transcodableMimeTypes` from config to use this const again

**Comment by spacedmonkey** [comment]
What about it's usage in jetpack class? 

https://github.com/GoogleForCreators/web-stories-wp/blob/d8cf5a932dc1d8cf183448f2d0d15a6afb91fdc5/includes/Integrations/Jetpack.php#L188-L192

**Comment by swissspidy** [comment]
See discussion at https://github.com/GoogleForCreators/web-stories-wp/pull/10604#discussion_r809869376 for that. I already pinged you there this morning.
We need to find a different solution there.
