### ISSUE TITLE
Remove Updated Publish Story Modal Experiment

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10594]
After 1.18 release we should remove experiment for new publish story modal and remove old flow. 

See #10115 for work related to new publish story modal

**Comment by BrittanyIRL** [comment]
@felipebochehin87 QA for this is just a bit of regression testing - make sure that story details publish modal is still showing and publish/review flow for admin and contributors is intact the same here as in staging.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11123.

Regressed publish/review as an admin, as an editor, as an author and as a contributor.
