### ISSUE TITLE
Unbounded Editor

### ISSUE THREAD

**Issue by ayushnirwal** [swissspidy/web-stories-wp#10599]
## Bug Description

If Story Editor is not bound by a div with a well-defined height then it keeps on stretching while loading more media.

https://user-images.githubusercontent.com/53055971/154408072-1e7a314e-ef82-4312-912b-cee77b5abbf6.mp4

## Steps to Reproduce

Use story editor as below
```jsx
const App = () => {
  const config = {
    apiCallbacks: { saveStoryById: () => Promise.resolve({}) },
  };

  return (
    <StoryEditor config={config} initialEdits={{ story: {} }}>
      <InterfaceSkeleton />
    </StoryEditor>
  );
};
```

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by mohdsayed** [comment]
@swissspidy  We had to add `100vh` height to the parent container to avoid this however it should work without it.

https://github.com/GoogleForCreators/web-stories-wp/blob/2010a9b3f6a43596b8eff792f6ac3dbca9add3b8/.storybook/stories/playground/story-editor/index.js#L37-L39

**Comment by swissspidy** [comment]
Fascinating bug 😄 

@sayedtaqui Agreed. Can we do something like `max-height: 100vh` somewhere in the `story-editor` package? Or did you have something else in mind?

**Comment by mohdsayed** [comment]
> @sayedtaqui Agreed. Can we do something like `max-height: 100vh` somewhere in the `story-editor` package? Or did you have something else in mind?

Yes, I have thought of setting the max-height somewhere in `story-editor`.
