### ISSUE TITLE
UI Simplification: Text element insertion panel - Allow applying Presets

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10609]
## Feature Description
In addition to adding an element by clicking on a text Preset, it should also be possible to apply it, if a text element is selected.

Note: this feature should be released together with #10113 and not separately!

- [x] Clicking on a Preset when no element is selected or non-text element is selected: Insert a new text element
- [x] Clicking on a Preset when text element selected: Apply the preset to the selected text(s)
- [x] Note: Do not display the Insertion `+` icon on the Preset if clicking on it results in applying style. The insertion icon should be displayed only if we'll add a new element when clicking.
- [ ] Performance: make sure only the Presets re-render when selecting/de-selecting a text element, and make sure it re-renders only if it actually needs to.
- [x] Update tests (quite a few will break due to not being able to insert two elements in a row anymore)
- [x] Remove feature flag for Saved Styles added in #10113 

Note: for consecutively adding text elements, the user now has to de-select text first and then click to add text again.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10719.

1. Hovered over Text elements and clicked on +
2. Left text selected and hovered over other texts - button + not displayed
3. Clicked out of the text and hovered over other texts - button + displayed
4. Added a text and clicked on a preset - text formatted as the preset
5. Added a text set and hovered over other texts - button + not displayed
6. Added a text set and clicked on a preset - text formatted as the preset

https://user-images.githubusercontent.com/96055551/157820349-6d269db5-afcf-4080-8a55-7c3b775805f8.mp4
