### ISSUE TITLE
Editor: `TypeError: entryTypes contained only unsupported types`

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#10616]
## Bug Description

A user has reported (https://wordpress.org/support/topic/editor-crashes-now/) the below error when trying to access the story editor. 

Hosting provider: Siteground

<details>
<summary>Error Stack</summary>

TypeError: entryTypes contained only unsupported types

UnreffedTab@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:133:5509
ul
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:1:34097
TabView@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:133:5834
nav
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:1:34097
section
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:1:34097
LibraryLayout@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:199:5858
div
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:1:34097
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
div
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:1:34097
UploadDropTarget@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:87:6953
LibraryUploadDropTarget@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:199:6649
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
LibraryProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:199:2056
Library
div
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:1:34097
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
RightClickMenuProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:201:174
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
UnitsProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:272:63978
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
CanvasProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3020558
section
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:1:34097
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
WithOverlay@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:143:5412
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
HighlightsProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:185:19804
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
ChecklistCheckpointProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:69:1458
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
LayoutProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:246:90296
DR@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:201:13183
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
MetaBoxesProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:264:3176
Layout
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
PageDataUrlProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:5:37394
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
HelpCenterProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3074408
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
DropTargetsProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3003056
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
TransformProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:226:35592
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
MediaProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:226:26914
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
FontProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3029563
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
CurrentUserProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3026264
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
TaxonomyProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:5:28247
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
StoryTriggersProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:201:100042
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
StoryProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:201:100871
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
SnackbarProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:262:30536
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
HistoryProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3001259
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
Media3pApiProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:246:11946
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
APIProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:201:124171
https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:236:3034432
ConfigProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:201:117758
M@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:5:26886
Fe@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:1:32705
ce@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:1:29723
FlagsProvider@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:226:1154
StoryEditor@https://wadirumescape.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=e44bad9a3979cf7f76684a5cfa1812c2:5:56008
</details>

- Plugin Version: 1.17.0
- WordPress Version:
- Operating System: macOS 
- Browser: Chrome 98.0.4758.102, Safari 13.1.3 (15609.4.1)

**Comment by swissspidy** [comment]
@miina This might be one for you

This error occurs in `usePerformanceTracking` when trying to instantiate the `PerformanceObserver`

I think we need to check whether [`PerformanceObserver.supportedEntryTypes`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver/supportedEntryTypes) contains the `event` entryType and if not, bail early and not do any tracking at all.
