### ISSUE TITLE
UI Simplification: Floating menu: Element alignment

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#10627]
## Feature Description

Make the element alignment options in the floating design menu functional.

Design: [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11394%3A457271)
Menus: Multiple elements
Optional rendering: Distribution icons could be displayed for 3+ element selection. Please coordinate with UX whether this is desired.
Notes: Refactor the existing logic from the existing element alignment panel.

## Additional information

<img width="679" alt="Screen Shot 2022-02-18 at 18 41 37" src="https://user-images.githubusercontent.com/637548/154775242-bb03a02e-c5ae-47e9-8a28-df52c098b4ec.png">

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10902.

1. Created a story
2. Added elements
3. Tried using shortcuts - removed as expected
4. Used side menu and floating menu buttons (with 1, 2 and more items) - working as expected

https://images.zenhubusercontent.com/235435637/5989b8f2-12bb-4262-ae60-b8fbb4acd3a0/10902.mp4
