### ISSUE TITLE
Story Details Modal x Prepublish Checklist Parity

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10623]
## Feature Description

Separating this out from #10115 to untangle the different UI states the checklist button and publish button have based on the checkpoint of the checklist. 😅  

With the introduction of the story details modal we're sunsetting the "do you want to review the checklist" modal that shows up when you click publish and have either a) under 4 pages or b) other outstanding priority checklist issues to solve. 

(PB = editor publish button, CB = checklist button, MPB = modal publish button, MCB = modal checklist button)

| Issue | Location | Visual |
| --- | --- | --- |
| Less than 4 pages | PB | <img width="82" alt="Screen Shot 2022-02-18 at 3 49 05 PM" src="https://user-images.githubusercontent.com/10720454/154771522-65a54113-644a-4b83-9aea-0075f12fcf16.png"> |
| Less than 4 pages | CB | <img width="52" alt="Screen Shot 2022-02-18 at 3 49 36 PM" src="https://user-images.githubusercontent.com/10720454/154771559-20c7eb38-338d-453a-9c82-e321fd423c90.png"> |
| Less than 4 pages | MPB | <img width="113" alt="Screen Shot 2022-02-18 at 3 50 15 PM" src="https://user-images.githubusercontent.com/10720454/154771630-98b3ce6b-ee47-40aa-8e7d-51a39519ebbe.png">
| Less than 4 pages | MCB | <img width="101" alt="Screen Shot 2022-02-18 at 3 50 42 PM" src="https://user-images.githubusercontent.com/10720454/154771677-5ccfe105-027a-4d2b-9fb4-6fd1d5b95eb5.png"> | 
| 4 or greater pages  | PB | <img width="254" alt="Screen Shot 2022-02-18 at 3 45 20 PM" src="https://user-images.githubusercontent.com/10720454/154771281-9afc5973-ce8a-45b4-9d84-92650521eb48.png"> |
| 4 or greater pages | CB | <img width="63" alt="Screen Shot 2022-02-18 at 3 47 13 PM" src="https://user-images.githubusercontent.com/10720454/154771378-06541c3a-f9b1-4431-a705-780018739118.png"> |

My thinking is that _regardless_ of story having 4 or more pages, the publish button on MPB should have the little exclamation mark and tooltip if there are priority issues present (which there will be if story has less than 4 pages).

If my thinking is correct, then should the editor's publish button have parity with the modal publish button? Does this mean if the story has under 4 pages and I click the editor's publish button and get to the modal - the modal publish button has the icon/tooltip - does the editor's button update to match it? Does the editor checklist button update to show the priority issues as well? 

## Updated after talking through with @agingoldseco 

All that needs to happen is when 'publish' is clicked in the editor, the checkpoint should be crossed to enable priority issue notices. This keeps everything in parallel. 

## Additional Context

Separated from #10115

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10766.


1. Warnings when story has 5 or more pages working as expected

https://user-images.githubusercontent.com/96055551/157076320-b4266b53-31df-4ca6-a7d4-1b44e420a955.mp4

2. Contributor flow working as expected  

![10766_01](https://user-images.githubusercontent.com/96055551/157076405-0f0c3bca-efe7-498d-bdd4-8c29858eb5f8.png)

![10766_02](https://user-images.githubusercontent.com/96055551/157076400-e31fcb6c-6b95-4787-b871-4ccdd1e8acb4.png)
