### ISSUE TITLE
UI Simplification: Slim color picker

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#10626]
## Feature Description

This concerns updating the color picker to the new and slimmer design.

Design: [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11394%3A457271)
Notes: This does not include design for the custom color picker state but it should be similarly sized and contents should be scaled to fit

## Additional information

<img width="604" alt="Screen Shot 2022-02-18 at 18 36 35" src="https://user-images.githubusercontent.com/637548/154774974-a9631196-1fba-431c-8dce-07a2b0803dd7.png">

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10704.

Regressed color picker for elements - all working as expected
