### ISSUE TITLE
Visibility Panel: Password Input

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10620]
## Feature Description

Right now, if visibility is set to 'password protected' and I publish my story without a password, it'll publish as public. 

Should the password input be required before publishing when password protected is selected? 

This is an option now that the publish button is in a dialog. 

## Additional Context

Follow up from #10115

**Comment by BrittanyIRL** [comment]
@swissspidy I'm not sure if there's anything specific to WordPress here about requiring this - want to make sure you see it though.

**Comment by swissspidy** [comment]
First and foremost the behavior should be the same as for the regular post editor.

**Comment by swissspidy** [comment]
In the WordPress block editor, the visibility is switched back to public if the password is empty. I think it should be fine to keep it that way in the story editor as well.

**Comment by BrittanyIRL** [comment]
> In the WordPress block editor, the visibility is switched back to public if the password is empty. I think it should be fine to keep it that way in the story editor as well.

Great, then i'm just going to close this - especially now that there are once more no required fields to enable the publish button. 

Thank you, Pascal.
