### ISSUE TITLE
UI Simplification: Floating menu: Font family

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#10628]
## Feature Description

Make the font family element in the floating design menu functional.

Design: [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11394%3A457149)
Menus: Text
Optional rendering: Always renders
Notes: Refactor the existing font family dropdown to meet the new style of this one and use the same dropdown in both places. Perhaps the width varies between the two to correspond to the original dropdown input.

## Additional information

<img width="772" alt="text-font-family" src="https://user-images.githubusercontent.com/637548/154775646-9981c1b7-a530-428c-b81f-0ad2e9fc45d5.png">

**Comment by BrittanyIRL** [comment]
I would consider splitting out updating the font family dropdown in the panel separately as a follow to this.
