### ISSUE TITLE
UI Simplification: Floating menu: Remove duplicate items from quick-action menu

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#10639]
## Feature Description

Remove duplicate items from quick-action menu:

- From text element, remove: Change Color; Edit Text
- From shape element, remove: Change Color
- From video, remove: Trim

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10796.

Shape

![shape](https://user-images.githubusercontent.com/96055551/156924375-7de6f184-c703-42f9-a7fb-1772c8f5f93c.png)


Text

![text](https://user-images.githubusercontent.com/96055551/156924378-e827c09e-fdc0-4ec6-bf45-6d4151f59801.png)


Video

![video](https://user-images.githubusercontent.com/96055551/156924385-661330ff-e48e-4a19-b68a-b87ad4122431.png)
