### ISSUE TITLE
UI Simplification: Floating menu: Text format toggles

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#10631]
## Feature Description

Make the text format toggle elements in the floating design menu functional.

Design: [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11394%3A457149) + [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11394%3A457514)
Menus: Text
Optional rendering: Always renders
Notes: This includes both the bold, italic, and underline toggles. This should use the existing functionality available in the rich-text helper utils. This should work both in and out of text edit-mode (and correctly reflect whether current selection is bold/italic/underlined while in edit-mode).

## Additional information

<img width="772" alt="text-toggles" src="https://user-images.githubusercontent.com/637548/154775994-c25afdf6-c742-4593-a515-65d761f74485.png">

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10875.

1. Created a new story
2. Added text elements (Title 1, Title 2, Title 3, Paragraph, Caption, Label)
3. For each of these elements, I clicked on Toggle bold, Toggle italic and and Toggle underline after selecting the entire box
4. For each of these elements I clicked on the toggle buttons selection a part of the text


https://user-images.githubusercontent.com/96055551/158322514-d3f7da3f-f702-4808-bba4-2ec9d3c5ce74.mp4
