### ISSUE TITLE
UI Simplification: Floating menu: Swap media

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#10635]
## Feature Description

Make the swap media element in the floating design menu functional.

Design: [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11394%3A457172)
Menus: Video + Image
Optional rendering: Always renders
Notes: This functionality already exists in the page action menu, so it can be copied from there.

## Additional information

<img width="642" alt="Screen Shot 2022-02-18 at 19 03 56" src="https://user-images.githubusercontent.com/637548/154776772-b76b17f2-74c1-40c1-a8d4-33329ff9572d.png">

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10759.

1. Created a new story
2. Added a video
3. Clicked on the video
4. Clicked on Swap Media
5. Selected another video - new video is displayed
6. Repeated steps above for images - working as expected
