### ISSUE TITLE
UI Simplification: Floating menu: Background element menu

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#10638]
## Feature Description

First of all, determine if the background element should have a floating menu when selected.

Secondly, display the correct menu whether the background element is shape, image, or video, without compromising the "lightness" of the floating menu layer (one option is to use a completely new layer for this).

## Additional Context

![Screen Shot 2022-02-18 at 13 51 46](https://user-images.githubusercontent.com/637548/154777111-09c69af3-550d-49dc-a65f-d25771c76b57.png)

**Comment by miina** [comment]
Confirmed with Amy that Quick-Actions menu and the Page menu will be sufficient and no need for a separate menu.
