### ISSUE TITLE
UI Simplification: Floating menu: Font color

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#10632]
## Feature Description

Make the font color element in the floating design menu functional.

Design: [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11394%3A457149)
Menus: Text
Optional rendering: Always renders
Notes: This should re-use the logic for a dropdown from elsewhere but note that this color element does not include a hex input field.

## Additional information

<img width="772" alt="text-color" src="https://user-images.githubusercontent.com/637548/154776055-293e380f-17d8-41b8-857e-825a57d09a94.png">

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10844.

1. Added a text
2. Clicked on the text
3. Clicked on Open Color Picker
4. Selected a color - text color changes
5. Tried selecting a gradient color - hint is displayed informing that "Gradient not allowed for Text"
6. Changed color from part of the text - allowed
7. Created a new custom color and set it to the text - allowed
8. Picked a color from canvas - allowed
