### ISSUE TITLE
Video Trimming: Don't change state for other instances

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10641]
## Feature Description

This is a follow-up to #10554 / #10409

When adding the same video multiple times to the canvas and trimming only one of them, each video's "Trim" button changes to "Trimming..." and gets disabled, because technically the underlying resource actually is being trimmed.

However, trimming one video doesn't really affect the other instances of it, so their buttons shouldn't get disabled in that case. This is different from muting or optimizing videos, which always affects all instances.

We need to somehow rework the `isResourceTrimming` check in `VideoOptionsPanel` to make that work.

My initial idea:

1. In `useProcessMedia`/`trimExistingVideo`, don't store `elementId` under `trimData`. Store it as a separate property on the upload queue item
2. In `useMediaUploadQueue`, rename `isResourceTrimming` to `isElementTrimming` and compare `item.elementId === elementId`

**Comment by spacedmonkey** [comment]
> In useProcessMedia/trimExistingVideo, don't store elementId under trimData. Store it as a separate property on the upload queue item

Question, is a new property really needed here? Couldn't we just do this?
```
item?.trimData?.elementId === elementId
```

**Comment by swissspidy** [comment]
A new property would also allow us to pass the `elementId` to the `onUploadStart`, `onUploadProgress`, `onUploadError` and `onUploadSuccess` callbacks.

It allows us to keep `trimData` as the metadata object that is sent to the server and does not contain any transient data.

**Comment by timarney** [comment]
Let me check my understanding here:

1) Add a param here

https://github.com/GoogleForCreators/web-stories-wp/blob/e2101cc98226d7400867d4d67ac9d654a65f402f/packages/story-editor/src/app/media/useUploadMedia.js#L228-L238

That data gets passed via `addItem`

https://github.com/GoogleForCreators/web-stories-wp/blob/e2101cc98226d7400867d4d67ac9d654a65f402f/packages/story-editor/src/app/media/useUploadMedia.js#L299-L311


Which in turn end up in "the media queue" => (state)

<img width="1041" alt="Screen Shot 2022-02-23 at 7 10 01 PM" src="https://user-images.githubusercontent.com/62242/155432201-4ee957c5-ee28-44b6-9f47-f225df48c508.png">


With that data available in the state we can update 

https://github.com/GoogleForCreators/web-stories-wp/blob/e2101cc98226d7400867d4d67ac9d654a65f402f/packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js#L840-L845

to 

```javascript

const isElementTrimming = (elementId) =>
      state.queue.some(
        (item) =>
          item.state === ITEM_STATUS.TRIMMING &&
          item.elementId === elementId
      );
```

The element ID can also be passed to `onUploadStart` etc...

elementId in turn can be removed from the Trim Data

All references to  `isResourceTrimming` i.e. videoOptions.js will need to be updated to `isElementTrimming` 

https://github.com/GoogleForCreators/web-stories-wp/blob/e2101cc98226d7400867d4d67ac9d654a65f402f/packages/story-editor/src/components/panels/design/videoOptions/videoOptions.js#L74-L94

**Comment by swissspidy** [comment]
At first glance that sums it up pretty nicely, yup 👍
