### ISSUE TITLE
Documentation: Document expected behaviour around video transcoding

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10645]
## Task Description

Discovered while working on https://github.com/GoogleForCreators/web-stories-wp/pull/10554. 

The number of places where videos is transcoding is the stories editor is growing. It can be confusing to understand when / where a file might will be / needs to be transcoded. Some documentation to explain might help users and developers alike.  

Some questions that might be useful to answer in this documentation. 

1. Under what conditions is a video transcoded? 
2. What is needed in the browser to support video transcoding? 
3. Why is the save button disabled while transcoding?
4. What happens when I mute a video? 
5. What happens when I trim a video? 
6. What happens to the original video when I optimize / mute / trim a video? 
7. What happens when I try to insert non web safe video into a story from the WordPress media library?
8. Where are poster image stored and why can't I see them in the media library?
9. What file types are supported to transcode? 
10. Why are animated gifs converted to mp4s?

There are other aspects we should document, but answering these questions is a good start.

**Comment by mxbclang** [comment]
@spacedmonkey Agreed that this would be great to have, as we get a lot of questions along these lines in support.

@gajasinski I know we had spoken previously about possibly adding documentation to https://wp.stories.google/docs/ – is this something we could consider adding? cc @swissspidy

**Comment by swissspidy** [comment]
@bethanylang Yes (parts of this) is definitely something worth adding to the website. I mentioned that to Jonny already today. Please don't hesitate to mention docs-worthy stuff to me and/or George and we can make it happen.

**Comment by samwhale** [comment]
💭 If this doesn't yet exist: adding 'why' a video needs to be transcoded - or rather, what the benefits are?

**Comment by mxbclang** [comment]
Noting that we have an internal Asana task for this; will close this issue once that task is complete.
