### ISSUE TITLE
Story Details Modal: Story title is unexpectedly required

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10644]
## Bug Description

With the new story details modal the story title is now suddenly required, whereas before it was possible to publish a story with an empty title. Something I do a lot in testing.

Now the publish button is disabled when the story title is left empty. But there is no indication for that anywhere, no tooltip or error message. Just a small unobtrusive asterisk next to the label.

## Expected Behaviour

The publish button should not be disabled when the title is empty.

We have the pre-publish checklist for that.

## Screenshots

<img width="861" alt="Screenshot 2022-02-21 at 16 53 49" src="https://user-images.githubusercontent.com/841956/154989106-2d07ebf9-1a36-4b64-ab61-47075ae1f376.png">

## Additional Context

- Plugin Version: 1.18.0-alpha
- WordPress Version: 5.9
- Operating System: macOS
- Browser: Chrome

**Comment by BrittanyIRL** [comment]
This was a design ask. I linked this issue in the design slack channel so that we can sort out anything more timely (since design doesn't check github super frequently).

**Comment by BrittanyIRL** [comment]
Removing the 'required' aspect of story title, per design discussion in slack.
