### ISSUE TITLE
Media: Video Muting affects all instances of video

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10648]
## Feature Description

This is a follow-up to https://github.com/GoogleForCreators/web-stories-wp/issues/10409

In #10409, the behaviour of the editor was changed, that when a user trims a video, if there are other instances of the same video then  within the story, then all instances of the video are updated. Updating all instances of the video, may not be the expected behaviour by the user. The question arises, should the same behaviour be put into place for muting? If a user has two instances of the same video in a story, on muting one of the instances of the video, all instances are updated. 

Muting is a different trimming, it is seems more likely that a user may want all instances muted, but there is now an inconstancy between the two editing operations.

**Comment by swissspidy** [comment]
Marking this as P4 for now since I don't recall any user feedback about the current behavior.

First we should get this properly documented in #10645 and then we can revisit if user feedback changes.
