### ISSUE TITLE
Story Details Modal: Wrong character limit for story description

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10646]
## Bug Description

In the document panel the displayed recommended character limit is 200 chars.

Now in the story details dialog it's suddenly 100 chars, which is way too few.

## Expected Behaviour

This should be 200 chars for consistency.

**Also**, the placeholder should be the same for both fields as well. No reason not to use the same.

## Screenshots

<img width="370" alt="Screenshot 2022-02-21 at 16 50 36" src="https://user-images.githubusercontent.com/841956/154990054-13b43e45-d6c2-4543-b841-848bb8a782b7.png">

<img width="443" alt="Screenshot 2022-02-21 at 16 50 47" src="https://user-images.githubusercontent.com/841956/154990046-8813deb0-4bda-4a4d-80a9-125f3eb87013.png">

## Additional Context

- Plugin Version: 1.18.0-alpha
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrittanyIRL** [comment]
Went off of figma. Thanks for the catch.
![Uploading Screen Shot 2022-02-21 at 9.21.49 AM.png…]()
