### ISSUE TITLE
New Story Details Modal: Background Audio Tooltips On Scroll

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10673]
In the Story Details Modal @BrookeGraham  found this edge case: 

- When the tooltip is on the publish modal and you scroll the anchor out of the modal, the tooltip stays mounted.

![image.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/b06737ca-939a-497c-bc0d-6e80ed28e6bc)

**Comment by BrookeGraham** [comment]
The tooltip only stays mounted while actively scrolling. As soon as you stop the scroll, it is removed. Though it still technically is visible when it perhaps shouldn't be, I think this is reasonable. Thoughts, @BrittanyIRL 
![tooltip](https://user-images.githubusercontent.com/1820266/156067986-8b8291cb-7051-42ab-a4a6-2d78858b8942.gif)

**Comment by BrittanyIRL** [comment]
> The tooltip only stays mounted while actively scrolling. As soon as you stop the scroll, it is removed. Though it still technically is visible when it perhaps shouldn't be, I think this is reasonable. Thoughts, @BrittanyIRL 

I think this is fine, when you spotted the issue it was staying mounted. Work you did last week in #10679 fixed that.
