### ISSUE TITLE
Author Search: Limited to matching at start

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10675]
Mentioned by @barklund during bug bash. 

The author dropdown only searches for first name (or to be specific: by substring from the start of the name only), so you cannot search for a last name to select an author. That seems wrong here (while still useful for font search, where it comes from).

**Comment by BrookeGraham** [comment]
@BrittanyIRL Do we want font and other consumer's of `DataList`'s search to be able to search any part of the string? So for fonts a search for `shade` will now include `bungee shade` for example.

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL Do we want font and other consumer's of `DataList`'s search to be able to search any part of the string? So for fonts a search for `shade` will now include `bungee shade` for example.

yes, i think all of the datalist searches should be partial. It follows Google Docs: 
<img width="888" alt="Screen Shot 2022-04-12 at 8 57 16 AM" src="https://user-images.githubusercontent.com/10720454/163004267-0bab2843-ff81-4598-a2be-f785052d3be4.png">

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11256.

1. On the Dashboard, searched by authors - term%, %term%, %term, %term, upper and lower case
2. On the Editor, searched for fonts - term%, %term%, %term, %term, upper and lower case

https://images.zenhubusercontent.com/235435637/5023868e-4380-4158-b219-ea1ed686d69d/search.mp4
