### ISSUE TITLE
Replace `worker-loader`

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10687]
## Task Description

This is a follow-up to #6304

In #5792 we experimented with replacing the now deprecated `worker-loader` with the new [recommended approach in webpack v5](https://webpack.js.org/guides/web-workers/).

We need to have an inline worker though, so we looked at using it in combination with [`asset/inline`](https://webpack.js.org/guides/asset-modules/#inlining-assets) but without much luck.

Needs some tinkering on how to make it work, as there doesn't seem to be any documentation about it. Not to mention that any change must not our Rollup builds either.

Related: #10133

**Comment by samwhale** [comment]
Some more context for the future:

[Was able to get it working by loading from a cdn here](https://github.com/GoogleForCreators/web-stories-wp/pull/5792/commits/1f5ce7893e7afbc373ea29c6c63299bb7777d9cd). However, getting the `blurhash` package to be loaded inline would be ideal. Was unable to figure out how to do that, so we went back to using the deprecated [worker-loader](https://v4.webpack.js.org/loaders/worker-loader/).

Some possibly helpful threads I came across when implementing: 
- https://github.com/webpack/webpack/discussions/14648#discussioncomment-1589272

---

Another idea I tried that didn't end up working: move the worker script to its own package, build that with webpack and inline `blurhash`, then load that in to the main app. [The branch where I was testing](https://github.com/GoogleForCreators/web-stories-wp/tree/split-out-worker-test) has some commits that may be helpful:
- 97cc89d
- 0cef385
