### ISSUE TITLE
Consider replacing Draft.js

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10684]
## Task Description

When we originally built the first version of text editing in the story editor, [Draft.js](https://draftjs.org/) was chosen for the job. At the time it was a proven and compelling rich text editor that fit our needs well.

For some extra functionality we also use the [`draft-js-import-html`](https://www.npmjs.com/package/draft-js-import-html), [`draft-js-export-html`](https://www.npmjs.com/package/draft-js-export-html) and [`draftjs-filters`](https://www.npmjs.com/package/draftjs-filters) packages.

For `draft-js-import-html` (which uses another package `draft-js-import-element`) we needed some extra functionality, so we patched the package ourselves using [`patch-package`](https://www.npmjs.com/package/patch-package). See https://github.com/GoogleForCreators/web-stories-wp/blob/5e01de8e6ad44c633b24dcfbbb0867ff4960f212/patches/draft-js-import-element%2B1.4.0.patch.

This patch has not been merged to this day. See https://github.com/sstur/draft-js-utils/pull/155.

As made evident by #10597, our editor does not work without this patch. Patching does not work for packages that we want to publish to npm, so if we want to make it work there we need to fork the package. That works fine for the short term, but is not something we'd like to maintain permanently.

Unfortunately things don't look too bright:

* `draft-js-import-element`/`draft-js-import-html` is not really maintained anymore. The last update was **3 years ago**
* `draft-js` itself is not really maintained anymore either. The last update was **2 years ago**
* On top of that, Facebook is even working on a new rich text editor instead (see [twitter.com/trueadm/status/1472377356044099587](https://twitter.com/trueadm/status/1472377356044099587))

Long term we need to look for a replacement. I know that [Slate](https://www.slatejs.org/) is a strong contender, but there are others as well.

**Comment by swissspidy** [comment]
cc @barklund as you originally implemented the rich text functionality. Curious to hear your preliminary thoughts.

**Comment by miina** [comment]
From @barklund:
> I don't think I found any reasonable libraries at the time. But I was already concerned about the abandonment then, so I did look around.

That was quite a long time ago so perhaps there are better options around now.

**Comment by c0b41** [comment]
btw lexical released today, but looks like unstable right now https://github.com/facebook/lexical

**Comment by timarney** [comment]
Here's a thread worth looking at 

https://twitter.com/buildsghost/status/1514294769198923778
