### ISSUE TITLE
Keyboard focus doesn't shift focus correctly for Empty State contextual menu

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10698]
## Bug Description

Originally reported by @BrittanyIRL 

Keyboard focus doesn’t shift to the selected pane when I click on Browse Page Templates but it does for other panes. 

Additionally @spacedmonkey found that "if I select page template once. Change tab and then why to go to page template again, nothing happens" and @BrookeGraham found that "similar with moving away from images tab and then selecting Choose Image or Video from right click menu" 
![image10](https://user-images.githubusercontent.com/58738530/155392150-0b5a0b1c-e6ba-44c7-bf70-538edefe8b1c.gif)

@merapi flagged that these are all likely the same issue.

## Steps to Reproduce

1. Open a new Story
2. right click within the canvas of the first page to trigger the "Empty State" contextual menu
3. Select "Browse Page Templates" and note that focus isn't changed as expected.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
@BrittanyIRL Since this is related to the general focus management of elements/canvas (#10850) that you'll be looking at, if I understood correctly, is this an issue that would make sense for Pea pod?

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL Since this is related to the general focus management of elements/canvas (#10850) that you'll be looking at, if I understood correctly, is this an issue that would make sense for Pea pod?

i think this falls into that, absolutely.

**Comment by BrittanyIRL** [comment]
Likely connected to #11291 - none of these are working on repeat actions. they used to, so something regressed here in the past few releases.
