### ISSUE TITLE
Right clicking outside of the canvas on a new "Empty State" page should not trigger the contextual menu

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10697]
## Bug Description

Originally reported by @BrittanyIRL 

Other right click menus only show up when you right click on the canvas, this one shows up if you right click outside of it too. Is this intentionally different?
![image11](https://user-images.githubusercontent.com/58738530/155389086-3fa3522b-7e19-4a1a-bbc4-9f859422e8c8.gif)

## Expected Behaviour

The contextual menu shown on an empty state page should only be shown when the user right clicks within the canvas area, not outside of that area as this is consistent with all other menus in the application.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
Looks like this is working as expected now, there were some changes meanwhile, such as #10701, perhaps this got fixed, too:
![empty-story](https://user-images.githubusercontent.com/3294597/158597072-25e3b082-a57b-4fc7-a318-4afa139add8e.gif)
