### ISSUE TITLE
A page with Page Attachment should not be considered empty state

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10700]
## Bug Description

Originally reported by @samwhale 

A Page with Page Attachment (CTA) is currently considered empty state.

## Expected Behaviour
If a Story has 1 page and that Page has a Page Attachment with no other changes, it is currently considered empty state and displays the empty state menu.
If Page Attachment is present, it shouldn't be considered empty state.

## Steps to Reproduce
1. Add a new Story
2. Select Background from the Layer Panel
3. Add Page Attachment
4. See the empty state UX still present.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
I think a more aptly description is that the "Add an image ... to get started" CTA is displayed even though the page is not blank anymore, since there is a page attachment on it.

**Comment by swissspidy** [comment]
cc @merapi

**Comment by miina** [comment]
@swissspidy I've changed the description.
#10701 should handle not being able to click "through" the empty state layer.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10870.

1. Created a new story - empty story message and icon are displayed in the canvas
2. Clicked on the background
3. Under "Layers", clicked on "Background"
4. Entered www.google.com into "Web address" field - empty story message and icon are hidden, "Learn More" is displayed on the footer
5. Deleted the address - empty story message and icon are displayed again in the canvas

https://user-images.githubusercontent.com/96055551/157980237-d5e310d0-d647-4726-a53d-2efb4afaa309.mp4
