### ISSUE TITLE
Empty Story State: User is unable to select a Page via clicking on it

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10701]
## Bug Description

User can't currently select the background / Page by clicking on it when in Empty State (only selecting via the Layer Panel works)

Originally reported by @barklund and @samwhale 

From Morten:
You cannot start adding background color (or page attachment or page background audio) to a page now. You have to start by adding an element.

From Sam:
If a user adds a background image to a page, then adds a link (Page Attachment) to that background image, and then removes the background image, the Page Attachment is retained and there is no way to remove it, as you are unable to select the background image associated with the Page Attachment to remove it. The user needs to add a background image back into the page for the Page Attachment to become selectable and be able to remove it.

![image6 2022-02-23 14_45_50](https://user-images.githubusercontent.com/58738530/155396300-3673618d-56a9-4486-a629-5a83029e9c56.gif)

## Expected Behaviour
User should be able to select a Page clicking through the Empty State Layer, too (except for clicking on the button)

## Steps to Reproduce
1. Add a new story
2. Try to select the Background via clicking on the Page directly.
3. It's not getting selecting.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Related / Duplicate: #10700

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10899.

1. Started a new story
2. Clicked on the background - design and document tabs are displayed

https://user-images.githubusercontent.com/96055551/158322968-6c7c2609-3883-4de8-afe3-f72564eb85cd.mp4
