### ISSUE TITLE
In-app comenting/feedback ability

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10713]
## Feature Description

In larger multi-author organizations it would be very helpful to enable editors a notes area and or commenting functionality to leave specific feedback for the story authors within the context of each story page. 

## Alternatives Considered

Teams are currently using tools that require screenshotting to ensure that context on the direction being given is understood and this is very time consuming.

**Comment by swissspidy** [comment]
Interesting suggestion!

This reminds me of the Commenting API proposal for Gutenberg: https://github.com/WordPress/gutenberg/issues/3026

I'll let @gajasinski weigh in, but I don't see this fit anywhere in our roadmap at all.

**Comment by gajasinski** [comment]
Thanks for the suggestion! Agreed this is a common user problem in larger organizations and the Gutenberg link is interesting. I'm not sure this is priority at the moment, but will keep it in the backlog.

**Comment by swissspidy** [comment]
Just closing as _maybelater_ to keep our backlog light. We can reopen once it becomes more relevant again.
