### ISSUE TITLE
Editor: Flakey Percy Snapshots

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10715]
## Task Description

I noticed some confusing Percy snapshots for the editor Karma tests. [Here is an example run](https://percy.io/google/web-stories-wp/builds/16051415/changed/904659737?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600).

Here's what I am seeing:

**`enableHotlinking` feature flag unexpectedly enabled**

In Karma tests, `enableHotlinking` is currently disabled by default and only active for the tests that need it, i.e. the hotlinking Karma tests.

For some reason it is also active for some completely unrelated tests, such as `Canvas keys integration should not be able to delete element from a dialog: color picker open`.

You can confirm this by seeing two media buttons with icons instead of the single "Upload" button when the feature is disabled.

![ea389da95046506458df45a8fc9e29ca541fcde7707b916863c773bc20799bb0](https://user-images.githubusercontent.com/841956/155692971-7fe324cc-10ff-4b12-b339-cd42aac6da91.png)

For some reason on `main` it looks as expected, with just the single "Upload" button active for this test.

Related: #10232 might resolve this by removing this code

**`floatingMenu` feature flag unexpectedly enabled**

Next up, there are lots of screenshots on the `main` branch where you can see the floating menu bar, even though that menu bar is only enabled for one specific test (Flip toggles).

Example test where the menu bar should not be visible:

![24e3697d099db69af7e4f67c1a388acc1ae6c3da26e65e8bf7561355baa33b55](https://user-images.githubusercontent.com/841956/155693503-e8891399-7b6a-4124-bdc8-052d0db7a187.png)

**Help center count off by one**

Sometimes the count of unread tips in the help center is 7, sometimes 8. Even when the test has nothing to do with the help center, e.g. `Panel: Style Presets CUJ: Creator can Apply or Save Text Style from/to Their Preset Library`

![Screenshot 2022-02-25 at 10 53 40](https://user-images.githubusercontent.com/841956/155694347-81d3040a-c2ed-4b0c-9291-4d983457a09c.png)

**Missing text sets**

Sometimes the text sets are not fully loaded before taking a snapshot, which causes a large diff:

![Screenshot 2022-02-25 at 10 54 31](https://user-images.githubusercontent.com/841956/155694493-10435935-ba92-4cfa-b45c-1a7bec8fca31.png)

Can happen for any text-related test I think, I just saw it in the `TextEdit integration add a multiline text element edit mode should not change height when entering and exiting edit mode` snapshot.

**Comment by BrittanyIRL** [comment]
@miina do you and Prometheus want to take this or do you want us to grab it? A lot of these seem in line with the UX updates ya'll have been making, but we're happy to help.

**Comment by miina** [comment]
@BrittanyIRL If you have capacity to take it, would be great!
