### ISSUE TITLE
Semantic Headings: Take Y position into account

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10725]
## Bug Description
Originally reported by @barklund 

> If I create two paragraphs of the same size (36pt), it seems like the first of these I created will become the h1 and the other the h2, even if I move the latter one to be topmost (both on canvas (lowest y coordinate). I have to change the order in the layer panel (and move the second one to the bottom of the layer panel) for the h1 and h2 to swap. Wouldn’t y coordinate be a better tie-breaker than position in elements array in case of a “tie” like this?

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10739.

1. Added 2 "Title 1" elements
2. Previewed story
3. Opened dev tools and checked both "Title 1" elements - the upper one is h1, the lower one is h2
4. Removed one of the title elements
5. Changed string to "SH"
6. Previewed story
7. Opened dev tools and checked the "SH" element - element is displayed as a paragraph <p>
