### ISSUE TITLE
Text Sets: make use of custom heading levels

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10724]
## Bug Description
Originally reported by @BrittanyIRL 
I added two of the same cover text sets and previewed, I have 0 h1s but 2 h2s. I think this is just because of how the text set was created? 

<img width="970" alt="image15" src="https://user-images.githubusercontent.com/58738530/155755402-f40ee505-8667-4b04-a7b4-5cb2a238bb31.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
H1s are only used if the font size is 36 or larger. The title here only has font size 31.

It's the only cover text set with such a font size.

We can consider lowering the threshold or simply forcing it to be an H1.

**Comment by BrittanyIRL** [comment]
> H1s are only used if the font size is 36 or larger. The title here only has font size 31.
> It's the only cover text set with such a font size.
> We can consider lowering the threshold or simply forcing it to be an H1.

🤔  I think it's probably ok as is. I feel like if we were to force an h2 into being an h1 just because there was no h1 present it could be more of a hinderance - like, how to select the "right" h2. Knowing it's for 36 or larger clears up my confusion and for users who notice this, they'll understand.

**Comment by swissspidy** [comment]
Forcing/Defaulting to h1 also really only works when there's UI to override that again, which is not currently planned. So yeah, probably easiest to just leave this as-is and make sure it's documented.

**Comment by swissspidy** [comment]
Related: #11363

**Comment by felipebochehin87** [comment]
Tested using PR #12031.

1. Added multiple text elements to a blank canvas
2. Changed their position and confirmed that the Title 1 that is at the top of the page is the H1
3. Other texts meet the expected too
4. Used a template
5. Changed font size:
H1: 36 or greater
H2: 27-35
H3: 21-26
P: 8-20
