### ISSUE TITLE
RTL: Background image - flip horizontally not working as expected

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10723]
## Bug Description
Originally reported by  @BrookeGraham:
When selecting flip background horizontally, and you attempt to move the background, the image is backwards. 

## Additional Context

- Plugin Version:
![background-flip](https://user-images.githubusercontent.com/58738530/155750420-0e6a5029-e731-4ae3-8b09-ee940fde2655.gif)

- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
@BrookeGraham To confirm: Was this in RTL mode only? Seeing the video is in RTL mode.

**Comment by BrookeGraham** [comment]
Correct. In rtl

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #11279.

Panned the background images right and left on both RTL and LTR, flipped and non-flipped images.
