### ISSUE TITLE
Semantic Headings: Take text length into account

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10726]
## Bug Description
Originally reported by @barklund 

> [Barklund] In the “steps” text sets, the number text fields are considered headlines too, which is bad semantics. It’s especially bad in this template (“Green soul mates”), because the number is in a larger font, so it becomes the h1 and the actual title is just a paragraph. I think we should go through all the text sets and encode their preference for HTML elements in each of them.
> 
> - Alternatively/additionally, we could make sure that very short text elements (3 characters or less?) are never “promoted” to headings, as they are probably just numbers or emojis. Or we could check that they at least have letters in there (by some definition of letters).

> - But then again, what if you’re making a story about unusual emojis - then a single large emoji in a text field would be the title of that page? It’s an unlikely scenario, but it exists. However most large emojis are probably not titles, but just “reactions” to whatever else is going on in the page.

## Screenshots
![image13](https://user-images.githubusercontent.com/58738530/155760976-9286be35-d858-437b-8561-0847355626ef.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10739.

1. Added 2 "Title 1" elements
2. Previewed story
3. Opened dev tools and checked both "Title 1" elements - the upper one is h1, the lower one is h2
4. Removed one of the title elements
5. Changed string to "SH"
6. Previewed story
7. Opened dev tools and checked the "SH" element - element is displayed as a paragraph <p>
