### ISSUE TITLE
CONTEXT_MENU_WIDTH variable not exported

### ISSUE THREAD

**Issue by c0b41** [swissspidy/web-stories-wp#10757]
## Steps to Reproduce

./node_modules/@googleforcreators/story-editor/dist-module/components/canvas/emptyStateLayer.js
Attempted import error: 'CONTEXT_MENU_WIDTH' is not exported from '@googleforcreators/design-system' (imported as 'l').

https://github.com/GoogleForCreators/web-stories-wp/blob/2010a9b3f6a43596b8eff792f6ac3dbca9add3b8/packages/story-editor/src/components/canvas/emptyStateLayer.js#L84

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Thanks for reporting!

That is really strange, since #10593 was supposed to fix this.

Maybe our Rollup config tries to bee smart and thinks it can be tree-shaken away.

We'll look into this 👍

**Comment by swissspidy** [comment]
Related: #10365

**Comment by c0b41** [comment]
nevermind some reason this warning go away, when i installed latest version @googleforcreators packages correctly.

**Comment by swissspidy** [comment]
Good to know, thanks for the update!
