### ISSUE TITLE
UI Simplification: Floating menu: More button

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#10761]
## Feature Description

Make the more button element in the floating design menu functional. Clicking this button should open and highlight the design panel for the current selection.

Design: [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11394%3A457149)
Menus: All single-selection (not multiple)
Optional rendering: Always renders
Notes: Should work for all single-selection menus and might have to work a little differently for each depending on the design panel tab.

## Additional information
<img width="951" alt="more-button" src="https://user-images.githubusercontent.com/637548/156187802-ceb92787-3413-4faa-b429-1cf437990eee.png">

**Comment by BrittanyIRL** [comment]
> and might have to work a little differently for each depending on the design panel tab.

Has this "differently" been discussed with design at all yet? Any anticipation of what this could mean?

**Comment by miina** [comment]
> Has this "differently" been discussed with design at all yet? Any anticipation of what this could mean?

@BrittanyIRL The information we have from UX currently is that it should open the Design Panel tab and highlight it. I suppose "differently" means that there might be different sections in the Design Panel tab, so it's not certain which part of it should be highlighted. All elements have the "Selection" panel though as the first one so perhaps highlighting that might make sense -- would be good to confirm with UX just in case -- thinking about it now, perhaps their idea was to highlight the whole panel?

cc @barklund

**Comment by BrittanyIRL** [comment]
@miina knowing it hasn't been further discussed is ok, we can chat with Amy about it on Tuesday ourselves and remove that from @barklund 's list of things to do. Thank you!

**Comment by samwhale** [comment]
This is blocked until the sidebar code is merged in. #10858 is based off of changes in the `sidebar` branch.
