### ISSUE TITLE
Saved Page Templates: Multiple images uploaded to WordPress

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#10787]
## Bug Description

We've received two reports in the support forum about multiple images for saved page templates being uploaded in `/wp-content/uploads/ `folder on the server. The purpose of this ticket is to track the reports and begin investigating the issue. 

## Expected Behaviour

Multiple images should not be generated.

## Steps to Reproduce

The steps to reproduce this issue are not clear at the moment.

## Additional Context

https://wordpress.org/support/topic/template-images-duplicates-in-uploads-folder/
https://wordpress.org/support/topic/duplicate-custom-template-images-in-uploads-folder/#post-15420708

- Plugin Version: 1.18.0
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
> I created a clean local environment with only Web Stories and Shortpixel installed.
> 
> I am able to reproduce the duplicate web stories page template image issue consistently.
> 
> Steps:
> - Select a default template (or create a fresh one)
> - Click 'Save current page as template' about 20 times
> - Scroll up and down the saved templates pane repeatedly
> 
> I was able to generate about 2000 images in my uploads folder in a few minutes.

**Comment by swissspidy** [comment]
Found the issue. Hint: the Shortpixel plugin is not relevant.

To reproduce:

1. Go the Templates tab
2. Save current page as template
3. Observe HTTP requests, notice image being uploaded
4. Go to another tab, e.g. Media
5. Switch back to Templates tab
6. Observe HTTP requests, notice image being uploaded

This is because the list of saved templates in the LibraryProvider is not updated after uploading the featured image.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11031.

1. Created a new story
2. Saved as a template - POST method called
3. Visited other tabs
4. Returned to the template tab - POST was not called
5. Repeated steps 3 and 4 multiple times - POST method was only called when template is saved, not when templates tab is visited
