### ISSUE TITLE
Autoset as Background: Do not display snackbar message all the time

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10782]
## Feature Description

This is a follow-up to #10458

As noted [on the forums](https://wordpress.org/support/topic/suggestion-option-to-hide-image-background-popup/), we display a `Full bleed images and videos are automatically set as background. Double click to scale and position at any time.` snackbar message **every time** the user performs this action.

![4VTVnr4](https://user-images.githubusercontent.com/841956/156379783-a4b150fe-cb32-46c9-a3ea-8b148e432833.jpeg)

This is annoying. We should only display it once and then store that in localStorage so we don't display it again in the future.

After the first time the user will know how it works.

**Comment by swissspidy** [comment]
FYI @agingoldseco @aaskedall @gajasinski @miina

**Comment by miina** [comment]
Interesting! Since it shows only when the user is positioning media on the Page and not actually setting it as a background via button / drop-targeting, then this might be the first proof it's useful to set it automatically and that setting as background was not a visible feature for everyone.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10957.

1. Created a new story
2. Added an image to the canvas
3. Expanded the image until the image became the background image - message is displayed: **_"Full bleed images and videos are automatically set as background. Double click to scale and position at any time."_**
4. Opened dev tools and checked Application tab > Local Storage > stories URL - _web_stories_background_is_set_dialog_dismissed_ is displayed, set to _true_
5. Repeated steps 1, 2, 3 and 4 - message is not displayed

https://images.zenhubusercontent.com/235435637/38c75404-c014-4910-8317-e3da7069adcf/10957.mp4
