### ISSUE TITLE
Tweak Floating Menu Styles

### ISSUE THREAD

**Issue by BrookeGraham** [swissspidy/web-stories-wp#10799]
## Feature Description
Let's clean up some styling tweaks on `Floating Menu`  once more components are in place. See [comment](https://github.com/GoogleForCreators/web-stories-wp/pull/10786#discussion_r819085047)

- [ ] make font input width smaller than ./shared `Input`, but larger than standard `NumericInput`
- [ ] check with @agingoldseco about the opacity input unit.

## Additional Context

The [Figma Designs](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11394%3A457172) show the input with no unit, but the opacity input in the original design panel has `%` unit.

| without | with | 
| --- | --- | 
| <img width="421" alt="Screen Shot 2022-03-10 at 5 24 28 PM" src="https://user-images.githubusercontent.com/10720454/157777957-84b1fcd4-8e7a-4825-b6d9-2014156eac04.png"> | <img width="452" alt="Screen Shot 2022-03-10 at 5 23 15 PM" src="https://user-images.githubusercontent.com/10720454/157777867-c36c4bac-08c1-4e92-a035-8968483783dc.png"> |

**Comment by felipebochehin87** [comment]
@BrookeGraham one thing that I noticed is that we have a bug again when the color is selected on the floating menu after being selected on the side menu (video below). Other than that, looks good.

https://images.zenhubusercontent.com/235435637/54e2b21a-e3bf-4b97-9342-e175383c4f6e/2022_04_07_16_30_24.mp4

**Comment by felipebochehin87** [comment]
@BrookeGraham never mind, it's in the main branch too, not caused by this PR.

https://images.zenhubusercontent.com/235435637/fe43bd51-e322-4973-979e-e26c4a83f79f/11192.mp4
