### ISSUE TITLE
Canvas elements cannot be focused/selected

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#10793]
## Bug Description

Elements on the Canvas cannot be selected via keyboard shortcut (Workspace) or via tabing.

![image](https://user-images.githubusercontent.com/21036224/156572994-50ac87f9-6190-4e8e-8444-0c56e38cf89b.png)

## Steps to Reproduce

Insert any element and press ESC to deselect it, try to re-select the element with keyboard only.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrittanyIRL** [comment]
@merapi pea pod is working on canvas focus (mostly done, #10999) - i'm going to steal this because it should be resolved and if it isn't we need to tend to it within our updates.

**Comment by BrittanyIRL** [comment]
This change exists in PR https://github.com/GoogleForCreators/web-stories-wp/pull/11328 so you can test it with #11003

**Comment by felipebochehin87** [comment]
Open question on PR #11328.

**Comment by sblinde** [comment]
Closing for Brittany.
