### ISSUE TITLE
Shortpixel Image Optimizer Incompatibility

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#10797]
## Bug Description

Plugins like Shortpixel are used for image optimizations within WordPress.

We upload an image for every custom saved page template. These are only used in the editor and should not be optimized by Shortpixel.

Otherwise, in combination with the bug where multiple images are being generated (#10787), this is pretty wasteful.

## Expected Behaviour

Shortpixel should not optimize page template images

## Steps to Reproduce

1. Install [Shortpixel Image Optimizer plugin ](https://wordpress.org/plugins/shortpixel-image-optimiser/)
2. Go to Web Stories > Explore Templates > Use (any) template
3. Go to Page template panel
4. Save page template
5. In Shortpixel stats, see that it cost a credit to optimize the page template image

## Additional Context
Here is the original report: https://wordpress.org/support/topic/duplicate-custom-template-images-in-uploads-folder

When this plugin is disabled, there are no erroneous images cloned. 
We will gather more details about the specific settings in Shortpixel and share them here when available. 

- Plugin Version: 1.18.0
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
FWIW, multiple images are optimized because multiple ones are generated (#10787)

There's no point in optimizing page templates images, because they're only used in the editor. So the expected behavior is for **_no_** such images to be optimized.

**Comment by swissspidy** [comment]
# Implementation Brief

As per https://wordpress.org/plugins/shortpixel-image-optimiser/, the plugin has quite a few filters

We should find a filter to disable Shortpixel for page template thumbnails.

This can then be done so in a new `Shortpixel` integration service.

If there's no suitable filter we'll need to revisit this and maybe even put it on hold.

If it works, we can look into similar plugins such as Imagify to potentially do the same for them.

**Comment by swissspidy** [comment]
Looking at the readme and the code, the `shortpixel_image_urls` filter looks like a good fit.

It filters the URLs that will be sent to optimisation and has the post ID as the second param.

```
apply_filters('shortpixel_image_urls', $URLs, $post_id);
```

https://github.com/short-pixel-optimizer/shortpixel-image-optimiser/blob/4d22e9e624088b72c2ea2c4b4eefdcd93aea922d/class/Controller/Queue/Queue.php#L584

We could:

1. Hook into that filter
2. Get the attachment's media source
3. If the media source is `page-template`, return an empty array
