### ISSUE TITLE
The background audio is playing twice, causing confusion

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#10791]
## Bug Description

When the user previews the story after checking "Loop", the background audio plays twice, causing confusion. The audio starts and a few seconds later, it starts again, so we have the same audio playing twice at the same time. (videos attached) 

## Expected Behaviour

We should only have one audio playing at a time during preview.

## Steps to Reproduce

1. Create a story
2. Add an image
3. Add an audio and the subtitles
4. Uncheck "Loop"
5. Preview - works fine
6. Close preview
7. Check "Loop"
8. Preview - that's when we have the bug, we have the audio playing twice
9. The same happens when you click on "Publish" and then on "View Story"

## Screenshots

https://images.zenhubusercontent.com/235435637/e627b53f-6a46-443d-95c7-efde53628cab/156364709_2d82b9e1_5df6_4198_a8fc_1b5ba9d70e62.mp4

https://images.zenhubusercontent.com/235435637/fd61b8c6-a21a-4ba5-a5e2-584a8d136eff/156357319_eb0e91cb_2029_4eda_830c_b6da90c741a3.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Hey Felipe

In your test story I can see that you've added both a story-level background audio as well as page-level background audio.

Hence you hear two audio files playing.

![Screenshot 2022-03-03 at 15 37 59](https://user-images.githubusercontent.com/841956/156586676-9beac122-661f-4f8b-a5a7-61dfc66d370f.png)
![Screenshot 2022-03-03 at 15 37 53](https://user-images.githubusercontent.com/841956/156586681-b2fa83f9-2107-4e2a-9b22-f6ffdbe2df52.png)


We do not currently forbid this practice, as there might be legit reasons for doing that (e.g. story-level background music and page-level narration).
