### ISSUE TITLE
Dashboard: Use deterministic image sources for fixtures

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10800]
## Task Description

`formattedTemplatesArray` in the dashboard uses https://placekitten.com for all image data.

While I love kittens, using this site means the images always change, which means our Percy snapshots always change.

We should use more deterministic images, ideally from our `__static__` folder.

**Comment by BrittanyIRL** [comment]
Indeed, the kittens had a long time in the sun.
