### ISSUE TITLE
UI Simplification: Sidebar Focus Regressions

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10806]
## Bug Description

Noted by Miina in PR #10760 : 

> When tabbing out of the library, the focus seems to get lost somewhere? (Previously went visibly to the canvas/workspace). E.g. tab to Shapes -> Stickers -> tab again -> not sure where the focus is.

([comment](https://github.com/GoogleForCreators/web-stories-wp/pull/10760#issuecomment-1058999666))

## Expected Behaviour

No focus regressions in new sidebar layout. 

## Additional Context

This ticket is to ensure that the new sidebar that @merapi is working on has no focus regressions. There's some outstanding issues, as noted here: #10698  and #10793 - to keep scope tight here, it's really just focused on making sure nothing new is regressing in this sidebar branch. @miina has requested that before the sidebar gets merged to main new focus issues are resolved. 

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrittanyIRL** [comment]
This will have to be branched off of `sidebar`

**Comment by samwhale** [comment]
After some investigation I found that this has existed for over 60 commits. Originally it was introduced in #10388 and should not block @merapi's work :). This can be merged into main instead of the `sidebar` branch too.

**Comment by samwhale** [comment]
Looked into this and chatted with @miina about it. We've concluded that there's not anything blocking the sidebar branch (in terms of focus). This ticket isn't needed.

We did find that focus was a little different. Tabbing across the canvas would eventually focus the title input on `main`.

On `sidebar` now the focus is given to the 'previous page button'. This is different, but I don't think it's a bad thing

|Main|Sidebar|
|--|--|
|https://user-images.githubusercontent.com/22185279/157310246-1e4c9b04-70b6-4534-8ef2-1e3e1e32c245.mp4|https://user-images.githubusercontent.com/22185279/157310287-66558bf9-f793-4456-b0c6-d33e60ebfd8c.mp4|

---

A conversation with UX is needed about what the focus _should be_ here, but that is not blocking the sidebar work.

**Comment by swissspidy** [comment]
@samwhale Those GIFs don't seem to work. Can you upload videos instead?

**Comment by samwhale** [comment]
Updated those to be videos. Turns out you can upload a gif that's greater than 10 MB in zenhub, but github doesn't like that.
