### ISSUE TITLE
Publish Modal: Apostrophe in site name not displayed correctly

### ISSUE THREAD

**Issue by freestylemama** [swissspidy/web-stories-wp#10809]
My site name is Let's Camp S'more and webstories is pulling the name with apostrophes as code. 

So `Let's` is `Let&#039;s`

What can be done?

**Comment by swissspidy** [comment]
Thanks for your report!

The site title is displayed in various places. Could you perhaps share a screenshot of where exactly it's displayed incorrectly? A URL to an affected story would be helpful as well.

**Comment by freestylemama** [comment]
![apostophe](https://user-images.githubusercontent.com/101015936/157052514-533a24e8-4c3d-4a9f-965d-f03646b13433.jpg)

**Comment by swissspidy** [comment]
Thanks. Is that in the pre-publish modal in the editor?

**Comment by freestylemama** [comment]
yes

**Comment by swissspidy** [comment]
Got it, thanks!

I can see the issue. We'll get this fixed.

Note that this is just a minor appearance issue in the editor. This should not affect appearance on places like Google Search and Discover.

**Comment by freestylemama** [comment]
Thank you!

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10823.

1. Changed site name to Felipe Bochehin's Tests
2. Created a new story
3. Clicked on Publish - name is displayed as inserted: Felipe Bochehin's Tests
4. Changed name to Felipe & Bochehin"s Tests
5. Created a new story
6. Clicked on Publish - name is displayed as inserted: Felipe & Bochehin"s Tests


https://user-images.githubusercontent.com/96055551/157497489-4af6cb47-ae61-41f5-ac8d-bce421ca6867.mp4
