### ISSUE TITLE
Text: Unexpected Padding / text-alignment values

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10802]
## Bug Description
Originally reported by @merapi, see https://github.com/GoogleForCreators/web-stories-wp/pull/10719#issuecomment-1058639480

Sometimes, there are unexpected padding values in the design panel, e.g. `null`, empty, or `Mixed` for a single element.

A similar issue happens with text-alignment which is also unset for presets, we should fix that, too. See [Pascal's comment](https://github.com/GoogleForCreators/web-stories-wp/issues/10802#issuecomment-1059073040).

## Expected Behaviour
Padding value should never be `null`, empty, or `Mixed` for a single element.

## Steps to Reproduce
1. Click on the "Title 1" preset.
2. See the Padding value in the design panel is empty.
<img width="300" alt="Screenshot 2022-03-04 at 12 07 24" src="https://user-images.githubusercontent.com/3294597/156743531-a74ca818-4662-4586-b09e-cf83406097c1.png">

3. Now assign text color from the color picker to the text.
4. See the Padding value is now `Mixed`
<img width="298" alt="Screenshot 2022-03-04 at 12 09 26" src="https://user-images.githubusercontent.com/3294597/156743707-53791ada-941e-44a7-8742-8fb09a4c1eab.png">

Note: I don't have the exact steps unfortunately to replicate `null` value but that also happens!

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Is this only happening for presets? Seems like they are incomplete and don't have default padding values set.

They also don't have text alignment by default, which is similarly confusing:

![Screenshot 2022-03-04 at 12 17 02](https://user-images.githubusercontent.com/841956/156753977-4e8866f8-3bc8-40e5-a927-c88f6684d830.png)

You also get `Mixed` padding value after setting text alignment.

**Comment by miina** [comment]
> Is this only happening for presets? Seems like they are incomplete and don't have default padding values set.

Not sure but all the texts are essentially presets.

> They also don't have text alignment by default, which is similarly confusing:

Will add it to the description for fixing.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10939. Padding is never set to null, mixed or empty.

1. Created a story
2. Added Text 1 - checked padding (set to 0)
3. Added color, changed alignment, changed text format (bold, italic, etc.) and checked padding - still 0

https://images.zenhubusercontent.com/235435637/22302088-84d3-43ee-9195-76029f86961a/10939.mp4
