### ISSUE TITLE
Sidebar: rename/reorganize files and components

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#10813]
## Description

Currently, in the PR for Sidepanel redesign #10931, we are not changing the naming in code. It was decided that since this kind of renaming would touch a lot of additional places in the code, it would likely constantly cause conflicts, delay merging, and it makes more sense to do the renaming once the PR gets merged.

Ideas for naming the components inside the code:

- Inspector -> Sidebar - this change got approval from various people
- Library -> Insert - since the name Library still accurately reflects what the panel does then maybe it doesn't make sense.
- Design -> Style - since the name Design still reflects what the panel does then maybe it doesn't make sense.

Generally, we wouldn't change all the components name if just the visible name/label changes, so perhaps we could keep the Library and Design as they currently are, unless the suggested alternatives generally seem more accurate and would be good to do anyway, regardless of the visible label change.

**Comment by miina** [comment]
As discussed in the Grooming today, this issue makes sense after the Sidebar has been merged to cause less conflicts that might start blocking merging. (It's not a user-facing issue)

**Comment by BrittanyIRL** [comment]
@merapi now that you're here, would you like to take this back?

**Comment by merapi** [comment]
> @merapi now that you're here, would you like to take this back?

Sure, working on it.
