### ISSUE TITLE
Performance: Story carousel integrate with page canvas provider

### ISSUE THREAD

**Issue by maxyinger** [swissspidy/web-stories-wp#10822]
Following [this ticket 10730](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/googleforcreators/web-stories-wp/10730) We should have infrastructure, to integrate the generation of story pages for page carousels into the page canvas provider. 

Should help cut down on expensive calls to generate images. Should also be pretty simple to integrate with the background task api like the current behavior.

More context: https://github.com/googleforcreators/web-stories-wp/issues/9749

**Comment by BrittanyIRL** [comment]
@felipebochehin87 there's testing directions in the PR for this (#11207) - the same PR will also fix #9958.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11207.

1. Created a new story
2. Added a background image to the first page - thumbnail updated
3. Duplicated page 1 to create page 2 - thumbnail displayed as expected
4. Changed the background image on page 2 - thumbnail displayed as expected
5. Duplicated page 2 to create page 3 - thumbnail displayed as expected
6. Changed images on 3 pages - thumbnail displayed as expected
7. Checked the thumbnails displayed on the checklist - thumbnails displayed as expected
8. Checked the preview page - thumbnails displayed as expected
