### ISSUE TITLE
Floating menu: Color picker positioning

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10825]
## Feature Description
Position the color picker so that it would always fit to the screen. Currently it's only positioned above the menu and can be cut off if there's not enough room:
<img width="525" alt="Screenshot 2022-03-07 at 15 19 10" src="https://user-images.githubusercontent.com/3294597/157074064-27fc73d4-0c69-4ea6-ae9a-f8792b27ef2f.png">

**Comment by miina** [comment]
@mariana-k It looks like @BrookeGraham is already addressing this issue as part of #10803, this would mean no additional work is required here.
Once @BrookeGraham confirms we can close the issue as getting fixed as part of #10803

**Comment by BrookeGraham** [comment]
I was just about comment here. Thanks @miina. Yes, I have to update the spacing for color picker anyways, so I this will be fixed @mariana-k. I'll be sure to tag you when I get that pr pushed up. It's wip atm. Draft pr is #10883

**Comment by BrookeGraham** [comment]
Fixed via #10883
