### ISSUE TITLE
Editor: Title input focus styles aren't correct

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#10849]
## Bug Description

The title input in the editor shows the old focus styles, but we want to see the new pretty focus styles.

## Expected Behaviour

Display correct styling when focused.

## Steps to Reproduce

Focus the title bar, tab away, and tab back. Should see the outline.

## Screenshots

![input-focus-state](https://user-images.githubusercontent.com/22185279/157289132-bc39c66e-86e7-46f0-bc5a-5e8c94410086.gif)

## Additional Context

- Plugin Version: 1.19.0-alpha.0
- WordPress Version: 5.9.1
- Operating System: MacOSX Big Sur 11.6.2
- Browser: Chrome

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11017.

1. Started a new story
2. Clicked on the "Add title" field - outline is displayed
3. Pressed tab and tabbed back to the "Add title" field - outline is displayed

https://images.zenhubusercontent.com/235435637/2af56409-9bf6-48e2-9ca5-5619d4c946a3/10849.mp4
