### ISSUE TITLE
Copy Story URL from the Dashboard doesn't work

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10857]
## Bug Description
In the Story Dashboard clicking on the kebab menu offers a couple of options, including "Copy Story URL" 

![Screen Shot 2022-03-08 at 4.28.11 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/98bcee83-363f-4539-a624-13b91077a800)

Selecting this doesn't seem to copy the URL to the system clipboard as expected

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrittanyIRL** [comment]
It's working fine for me, can you be more specific with additional context or try again? 

(video is from staging)

https://user-images.githubusercontent.com/10720454/157334004-9e938366-6986-4253-b275-3a87ef441a9d.mp4

**Comment by swissspidy** [comment]
Also working fine for me
