### ISSUE TITLE
Workspace: Add a keyboard navigation design doc

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#10850]
## Task Description

_For general enhancement to improve keyboard navigation in the canvas area._

The focus in the canvas can be a little confusing. Tabbing to images doesn't select them, but tabbing to text elements does. There are ways to get to the design panel from the canvas, but it can be a little confusing.

It would be good to tighten up and describe how to use the canvas with a keyboard. Write a design doc describing a high level idea of
- how a user should move between elements
- how a user should move between different parts of the editor
- how a user should move into temporary UI (such as the floating menu)
- how a user can interact with elements

Having a design doc that defines the way a user should traverse the document is essential for future updates and tightening up the current flow.

**Comment by BrittanyIRL** [comment]
Thanks for taking the initiative on this, @samwhale !! 

Focus has been coming up a bit within redesign issues - what do people think about adding a roadmap item for keyboard focus in a future release to straighten out where focus should go (following this doc creation so we have a jumping point to line up with). I think it absolutely qualifies as it's own feature in the roadmap and would be really great to solve before introducing multiple canvases. 

@miina @swissspidy @agingoldseco  @aaskedall what do you think?

**Comment by BrittanyIRL** [comment]
(see #10806 for more context on where this conversation started)

**Comment by swissspidy** [comment]
After reading this and #10806 I don't think I fully understand whether this is about a regression or a general enhancement to improve keyboard _navigation_ in the canvas area. Sounds like it's about the latter.

In that case, yes it's a bigger effort that would require synching with UX and our in-house a11y experts and writing such a design doc, and could definitely be put on the roadmap for increased visibility.

For context, here's the original a11y product spec: https://docs.google.com/document/d/15FHCukTDrWf7xYpPkBG3bGRgRQZeqzkCcglaNXgaw9s/edit (out of date, but helpful)

It mentioned that for initial release just being able to modify elements via the design panel is fine, but eventually we'd want to support keyboard-driven canvas manipulation if possible (plus other things like high contrast mode and reduced motion support). Worth noting that this was listed under "Recommended".

Given this context, I would not give it super high priority.

**Comment by samwhale** [comment]
Oh yup - sorry, the idea behind this was a general enhancement to improve keyboard navigation in the canvas area.

**Comment by miina** [comment]
Sgtm!

On priority -- when testing the current state with @samwhale to understand if there were regressions or not, the following came out:
- Currently it seems to be impossible to interact with the background using keyboard
- It also seems to be impossible to interact with masked elements (e.g. shapes, all media, etc.) using just keyboard
- As Sam found out then when tabbing from the library, the focus actually goes to a masked element (or background) on the page but since the events are disabled for masked elements, the masked elements do not get selected nor are interactive nor have any indicator that focus is on those elements, making it impossible to do anything with those.

This kind of makes the editor unusable with keyboard -- it's possible to add media etc. but if it gets unselected after adding, it's not possible to delete the element nor select it again nor change anything about it, if I understand correctly. So at least documenting and sorting those parts out seems like quite high priority (#10793, related: https://github.com/GoogleForCreators/web-stories-wp/issues/10642, https://github.com/GoogleForCreators/web-stories-wp/issues/10698), if the editor is generally unusable with the keyboard then all the keyboard efforts to make the editor accessible are kind of not very useful.

Thoughts?

**Comment by swissspidy** [comment]
That is indeed more concerning then!

**Comment by BrittanyIRL** [comment]
Thank you for the thorough description of why this should be prioritized, @miina ! 

I added this design doc to our current sprint. @samwhale will work on it next week at the latest and that'll give us proper time to run through with Amy and nail down what should happen so we can address this head on. 

Personally, I think (if we can get the flow nailed down and design updates are done) this should be added to 1.20.

**Comment by samwhale** [comment]
# Summary

Did some investigation on similar apps and into our own documentation (thanks Pascal for providing that).

I only found 2 apps (canva + visme) that deal with keyboard navigability, while 3 other competitors (Design Wizard, Easil, Snappa) don’t have any handling or completely ignore it :bangbang:

Canva + visme share a lot of the same ideas:
- Should be able to change selection using Tab
- Should be able to move the selection with the arrow keys
- Adding other keys like Cmd or Shift change the distance of each press
- Only allow basic manipulation of elements (position, moving it forward and back through the layers, add a border)

---

## Bugs

Pascal linked a very helpful doc that linked to what is essentially the [design doc for keyboard navigability](https://docs.google.com/document/d/1_3-_v4zH6bW9hOplOO8wYxj8l4C0soMgEbD7XLiXrrg/edit#heading=h.tmjqhakjzrs1) (and other stuff). I don't think we need a new design doc, because it already exists. We need to follow the existing one and fix the pieces that are broken. 

The broken pieces are:
- `Tab` should change focus _and_ element selection. Currently this only works for elements without masks
- The floating menu traps the focus, so users are unable to get back to the canvas

---

## Features

One key difference I saw:
**Canva needs you to press Enter to enter the canvas and Esc to exit it, but visme adds the canvas and all elements in the normal focus flow**

I think adding a focus container around the canvas (similar to the story grid, page templates, and text sets containers) would be beneficial. Canva has a good example of this:
1. Tabbing to the canvas should highlight the canvas
2. Pressing `Enter` drops the focus into the canvas. Pressing `Tab` from there will move focus and select different elements
3. Pressing `Esc` from the canvas will pull focus up into the container. Pressing `Tab` from there will continue moving focus into other parts of the app. This skips the need to traverse the entire story when they want to reach the footer. 💭 This should also be helpful when support for 'multiple pages' is added.

**Comment by BrittanyIRL** [comment]
created a new epic based on this discovery: #10999
