### ISSUE TITLE
Code Quality: Move `usePerformanceTracking` from `design-system`

### ISSUE THREAD

**Issue by mohdsayed** [swissspidy/web-stories-wp#10862]
## Task
As discussed in https://github.com/GoogleForCreators/web-stories-wp/pull/10452#discussion_r820499911 , `design-system` doesn't look like a suitable place to keep `usePerformanceTracking`.

## Alternatives Considered

May be its usage in the `mask` package needs to be refactored so that it will only be used in the `story-editor` package.

## Additional Context

https://github.com/GoogleForCreators/web-stories-wp/pull/10452

**Comment by mohdsayed** [comment]
`usePerformanceTracking` is being used only once in `packages/masks/src/frame.js`.

@swissspidy Do you know why we are tracking twice? 

Once in `story-editor` here which renders `FrameWithMask as WithMask`
https://github.com/GoogleForCreators/web-stories-wp/blob/91d4a638eb1492423831ba8d142a7a0d5654f5e3/packages/story-editor/src/components/canvas/frameElement.js#L207-L214

And then again from `masks` in `WithMask`

https://github.com/GoogleForCreators/web-stories-wp/blob/91d4a638eb1492423831ba8d142a7a0d5654f5e3/packages/masks/src/frame.js#L190-L197

If I can get some more details, maybe we can pass/forward `ref` somehow, and track only once from `story-editor`,

**Comment by swissspidy** [comment]
Looks like one is for masked elements, one for non-masked elements? Hence `node: null` if there is a mask.
