### ISSUE TITLE
Code Quality: Move `PanelTypes` from `design-system`

### ISSUE THREAD

**Issue by mohdsayed** [swissspidy/web-stories-wp#10863]
## Task

As discussed in https://github.com/GoogleForCreators/web-stories-wp/pull/10452#issuecomment-1060435885, `PanelTypes` shouldn't be in the `design-system` package.

## Additional Context

https://github.com/GoogleForCreators/web-stories-wp/pull/10452

**Comment by swissspidy** [comment]
After #11096 we can now theoretically just move the `PanelTypes` to `story-editor` again (making it a dependency of `element-library`.

**Comment by sayedtaqui** [comment]
> After #11096 we can now theoretically just move the `PanelTypes` to `story-editor` again (making it a dependency of `element-library`.

@swissspidy Just to clarify you mean, move to `element-library` right?

**Comment by swissspidy** [comment]
Hmm, no I meant from story-editor. [Quote](https://github.com/GoogleForCreators/web-stories-wp/pull/10452#issuecomment-1060771207):

> For context, the way Gutenberg has solved the elements <-> panels relationship is basically by making `element-library` a dependency of `wp-story-editor` (instead of `story-editor`) and then actually add `story-editor` as a dependency to `element-library`. Then each element (from `element-library` or an integration package) can import the panel types it wants from `story-editor`.

`story-editor` uses `PanelTypes` in `getDesignPanelsForSelection`, but `element-library` is not a dependency of `story-editor` anymore. So moving `PanelTypes` to `element-library` wouldn't work.

Or am I missing something?

**Comment by sayedtaqui** [comment]
Actually `element-library` is still a dependency of `story-editor` for many things, though ideally, it shouldn't be. So if we make `story-editor` a dependency of `element-library` it would create circular dependency.

**Comment by swissspidy** [comment]
Ah you're right; dang I did not realize that.
