### ISSUE TITLE
Move `VideoTrimmer` component to `element-library` package

### ISSUE THREAD

**Issue by mohdsayed** [swissspidy/web-stories-wp#10867]
## Task

As discussed in https://github.com/GoogleForCreators/web-stories-wp/pull/10452#discussion_r820525563 Video Trimmer is more element-specific and therefore should be moved to `element-library` package.

## Additional Context

https://github.com/GoogleForCreators/web-stories-wp/pull/10452

**Comment by swissspidy** [comment]
Seems like a tricky one due to the component's dependencies on `useLayout()` and `useLocalMedia()` from the editor.

cc @barklund for thoughts
