### ISSUE TITLE
Custom Fonts: Improve Accessibility on Settings screen

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10878]
## Bug Description

In #9966 we added a custom fonts section to the settings screen, to allow adding custom fonts by URL. It did not contain any a11y work, but there was also no follow-up ticket for that yet.

This feature right now is completely unusable with keyboard or assistive technologies. It's impossible to tab into it in the first place.

## Expected Behaviour

The `Current Fonts` list needs proper `role="list"` and `role="listitem"` attributes and keyboard support so that users can tab into it, select fonts using ArrowUp/ArrowDown keys and delete a font using the keyboard as well.

## Screenshots

![Screenshot 2022-03-10 at 18 53 07](https://user-images.githubusercontent.com/841956/157725736-ad468051-2a46-42a1-b399-43ee18332cae.png)
![Screenshot 2022-03-10 at 18 53 01](https://user-images.githubusercontent.com/841956/157725738-ca41e164-66aa-4d29-9dbb-d689b1f2f414.png)

## Additional Context

- Plugin Version: 1.18.0
- WordPress Version: 5.9
- Operating System: macOS
- Browser: Chrome

**Comment by timarney** [comment]
### Questions:
1) Do we have any other spots in the app that have this `hover` / `delete` pattern ?

2) How do we want to interact with the delete functionality for the highlighted row ?  i.e. are additional keyboard presses needed to select the delete button ? 

3) Should we add a `aria-labelledby={family}` to the delete buttons so the buttons don't have duplicated "Remove font" text

https://www.washington.edu/accessibility/checklist/links/

i.e. something like
```javascript
<DeleteButton
                      tabIndex={0}
                      aria-label={('Remove font', 'web-stories')}
                      aria-labelledby={family}
```




> select fonts using ArrowUp/ArrowDown keys and delete a font using the keyboard as well.

For a11y / keyboard nav

Tab -- gives font list (role="list") focus

<img width="400" alt="Screen Shot 2022-03-14 at 4 45 10 PM" src="https://user-images.githubusercontent.com/62242/158258215-a7673be6-50fc-457a-95b8-a5cf304915e2.png">

We can Arrow up / down to highlight the row --- 

<img width="400" alt="Screen Shot 2022-03-14 at 4 43 56 PM" src="https://user-images.githubusercontent.com/62242/158258421-3ed86310-23fd-4030-b131-d9bbb920d87e.png">

**Comment by swissspidy** [comment]
Re-reading my original description, I am now wondering whether `role=listbox` with `role=option` in it would make more sense 🤔 See https://www.w3.org/TR/wai-aria-practices-1.2/examples/listbox/listbox-grouped.html

It's been a while since I've personally actively used it, but we use it in a few places in the app

> * Do we have any other spots in the app that have this `hover` / `delete` pattern ?

The media library in the editor has a similar pattern. Buttons for each video/image are displayed on hover/focus. Can be achieved using `:focus-within` in CSS.

> * How do we want to interact with the delete functionality for the highlighted row ?  i.e. are additional keyboard presses needed to select the delete button ?

Pressing tab to select the delete button should work

> * Should we add a `aria-labelledby={family}` to the delete buttons so the buttons don't have duplicated "Remove font" text

Wouldn't that cause the delete button do be announced as "Overpass SemiBold"? 🤔 

`aria-label={sprintf(/*translators: %s: font family. */ __('Delete %s', 'web-stories'), fontFamily)` seems more appropriate

Curious to hear other thoughts.

**Comment by timarney** [comment]
Could we use  role="listbox" + role="option" 

https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-rearrangeable.html

Bonus this will also announce the # of items on the list

```html
<div role="listbox">
<div role="option">item 1</div>
<div role="option">item 2</div>
...
</div>
```

Also they talk about delete functionality here:

> and Delete performs a remove only when focus is in the chosen options list.

<img width="918" alt="Screen Shot 2022-03-14 at 8 10 21 PM" src="https://user-images.githubusercontent.com/62242/158281061-7464a3f4-c9f0-402d-9104-89e50be672ff.png">

**Comment by timarney** [comment]
role=listbox with role=option make sense and yes to the label ... I was looking at some grouping examples

**Comment by timarney** [comment]
Couple of more questions I thought of ...

- When you focus should it "auto select" the first font in the list?
- When you leave ... tab outside thinking it should reset the focus index i.e. resets to unselected state

**Comment by swissspidy** [comment]
IIRC in a listbox there always needs to be a selected element. Even before focus and even when tabbing out of it.

My Preferred Languages WP plugin does that, if looking for inspiration.

**Comment by BrittanyIRL** [comment]
Well i'm late to this party, apologies. 

Media library's the only other place where actions are available on hover/focus and keyboard accessible (layers panel also does this but it's purposefully hidden from keyboard users) 

+1 to using a listbox

You might find `useRovingTabIndex` useful here to not have to recreate the pattern of arrow navigation through a list + tab to access different actions of a list item. There's quite a few use cases of it if you just search for it in /packages that you can then go see in action and draw from.

**Comment by timarney** [comment]
Okay thanks @BrittanyIRL here's where I landed pre `useRovingTabIndex ` 

![keyboard-nav](https://user-images.githubusercontent.com/62242/158562961-26023e3d-a66c-4af3-9fcb-322af6b292e0.gif)

@swissspidy can you maybe take a look at https://github.com/GoogleForCreators/web-stories-wp/pull/10918 `as is` before I look at maybe using `useRovingTabIndex `  ?

**Comment by BrittanyIRL** [comment]
@timarney is this where the failing e2e tests are getting flagged? 
https://github.com/GoogleForCreators/web-stories-wp/runs/5630868893?check_suite_focus=true#step:9:27 

I'm trying to figure out the best path forward for making sure that enabling the floating menu isn't messing with other tests. If what you're working on will solve it then I will sit tight. Please let me know. thanks!
