### ISSUE TITLE
Media: Add support for hotlinking audio files 

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10888]
## Feature Description

Breakout ticket from #10515. Allow users select hotlink audio files served from a different source for background audio functionality. Like video hotlinking, user may want to offload audio assets to third party service to host large audio files. Unlike video, audio is not stored in google cache either.

**Comment by spacedmonkey** [comment]
While working on https://github.com/GoogleForCreators/web-stories-wp/pull/11122, a new component was added for hotlinking. This should make adding hotlinking extremely simple. Once this PR is merged, I maybe prototype it up, as it will not take long.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #11221.

1. On Experiments, enabled the option to allow audio hotlinking
2. On the editor, clicked on the background
3. Opened Style tab
4. Clicked on "Link to audio file"
5. Pasted https://ia800905.us.archive.org/25/items/EDIS-SRP-0197-06/EDIS-SRP-0197-06.mp3 and confirmed
6. Played/paused the audio - audio plays as expected
7. Previewed and published story - audio plays as expected
8. Regressed audio upload - no impact

Tested on Safari, Chrome and Firefox.
