### ISSUE TITLE
Fonts: remove unneeded values being saved to story data

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10885]
## Bug Description

While working on https://github.com/GoogleForCreators/web-stories-wp/pull/10877, I noticed that there are some unnecessary fields being saved to story data. See screenshot from example. 

<img width="574" alt="Screenshot 2022-03-10 at 18 16 24" src="https://user-images.githubusercontent.com/237508/157728778-ff1425d3-b258-48b6-ae1b-df3f57f681fa.png">

The name, id and value fields are not required. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by spacedmonkey** [comment]
Does this need a migration?

**Comment by swissspidy** [comment]
Yeah a migration would be nice. Of course the font picker should be fixed to not add these values in the first place.

**Comment by spacedmonkey** [comment]
> Of course the font picker should be fixed to not add these values in the first place.

Yes of course. I am more talking about existing stories / templates etc. Okay, I will add this as well.
