### ISSUE TITLE
Floating menu: Icon buttons not showing tooltip when in focus

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10884]
Originally reported by @barklund: https://github.com/GoogleForCreators/web-stories-wp/pull/10875/files#r824197428

## Bug Description
`IconButton` component shows a tooltip when hovering but not when focused.

## Expected Behaviour
`IconButton` should show a tooltip when focused, too.

## Steps to Reproduce
Focus on a flip toggle with keyboard -- see the tooltip not showing.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10920.

1. Created a new story
2. Added text elements
3. Added image elements
4. Clicked on the elements and used Tab to reach floating menu options - tooltips displayed as expected
5. Hovered over the floating menu options - tooltips displayed as expected

P.S.: there's an issue when using tab - not all elements are reached - but we have another PR to fix this - 

https://user-images.githubusercontent.com/96055551/158587266-fc9f6f4b-6386-452a-b9ea-66ec8d9e8e90.mp4
