### ISSUE TITLE
Page Templates: Add a refresh button to reload page templates

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#10898]
## Feature Description

As suggested in [this support topic ](https://wordpress.org/support/topic/suggestion-refresh-templates-with-button/#post-15456313) could we add a refresh button for the page templates.

An example scenario of when this feature would be needed:

- User has a story opened in tab 1. 
- The user then in tab 2 has a separate story open and saves a new page template. 
- If the user goes back to tab 1 that page template won't display without a page refresh. 

Switching the dropdown option to default and back to saved templates does not refresh the list and only a page reload does this. 

## Alternatives Considered

Users can always reload the page as mentioned above.

**Comment by swissspidy** [comment]
Related previous feature request: #9282

Marking as P3 for now since I doubt this is a common use case and simply reloading the page works well in the meantime.
