### ISSUE TITLE
Workspace: Updated Footer Toggle Button Style

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10891]
## Feature Description

This came up when redesigning the layers panel and moving it to the footer to be a toggle button instead of living in the inspector pane. 

A new toggle button style was introduced with it. Ideally, the toggle buttons used in the footer are uniform. 

| New | Existing | 
| --- | --- | 
| <img width="136" alt="Screen Shot 2022-03-11 at 1 43 26 PM" src="https://user-images.githubusercontent.com/10720454/157960098-53ae2e05-7470-4394-a539-93d0747773cd.png"> | <img width="709" alt="Screen Shot 2022-03-11 at 1 44 18 PM" src="https://user-images.githubusercontent.com/10720454/157960338-2e9726b1-7e2c-47e0-a30c-67ae1c0caab6.png"> |

The main differences here are the background color and circle for the number badge and a chevron.

## Additional Context

Let's figure out how to unify these before working on them. 

Related work #10847

**Comment by sblinde** [comment]
Intent:
- Would have a up-down chevron icon with the layers panel open and closed on the right of the number
- Would have a circle around the number of layers (turning it into a badge) (dark gray is background-dark-teritary)
- Some extra width to the button

**Comment by felipebochehin87** [comment]
![11737.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/510ae3c3-9872-4500-ba72-359291a35c4d)
