### ISSUE TITLE
Popup's getOffset util calculation incorrect when using dock

### ISSUE THREAD

**Issue by BrookeGraham** [swissspidy/web-stories-wp#10928]
## Bug Description

When moving the color picker popup to `dock` on the right of the new `sidebar` component it was discovered in #10883 that the `Popup`'s util function `getOffset` is [calculating the offset incorrectly](https://github.com/GoogleForCreators/web-stories-wp/blob/main/packages/design-system/src/components/popup/utils/getOffset.js#L28-L32). Currently, it check's for a truthy value for `dockRect?.left`. However, `dockReck.left` can be and now is a falsey value of zero. This means it unintentionally uses the anchor's left value instead of the dock's left value.  In this sidebar color picker use case, the dock element being passed into the `Popup` is a reference to the entire `inspector` element since we want it docked to right of the entire `sidebar`. Now that this element is on the left side of the screen, the dockRect's left value is zero. This is also the case for style presets.

We can not however simply change the check for dockRect since the it would still make the math for  `leftAligned` (and `rightAligned`) incorrect. When `dock`ing a popup, we shouldn't be adding the width of the anchor, as the anchor is no longer relevant to positioning. It should be noted however, that in the use case for tooltips, `rightAligned` would need to account for anchor width. 

It should also be noted that `leftAligned` and `rightAligned` mean something different when talking about where to `dock`, vs. `placement` of the popup -> tooltip. In addition to RTL mode. 

Currently, the  `Popup` component has 17 props, with another one being added to differentiate "normal popups" from the tooltip's implementation. While `Tooltip` _only_ sends down 8 to Popup, and yet has 16 of it's own props, trying to account for all use cases is getting problematic. Regressions are hard to manage since there are vastly different ui needs between Popups, Tooltips, and Dropdown. With so much complexity and the use cases diverging it may be time to split apart `Tooltip` from `Popup` and perhaps `Dropdown`as well.  

## Expected Behaviour

We expect the Popup to render in relation to the dock element whenever a dock ref is present. We also expect the offset calculations be based on the referenced element and that those calculations take into account whether we are docked on the right of an element or on the left. 
 
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
Not sure if this will get fixed here but found a tooltip out of place from the Percy Snapshots of the `sidebar` branch (Video element -> Accessibility -> when opening the menu for poster image):
<img width="139" alt="Screenshot 2022-03-17 at 14 43 12" src="https://user-images.githubusercontent.com/3294597/158811139-7af93eb0-ff01-4f24-afa5-ad670f4b774d.png">

**Comment by BrookeGraham** [comment]
> Not sure if this will get fixed here but found a tooltip out of place from the Percy Snapshots of the `sidebar` branch (Video element -> Accessibility -> when opening the menu for poster image): 

I missed this one. Thanks for flagging.
