### ISSUE TITLE
Custom Fonts: Enable by default

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10925]
## Task Description

Let's enable both relevant feature flags ahead of the release

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #11058.

1. Added font
2. Deleted font
3. Tried to add duplicate fonts - error message displayed as expected
4. Performed actions using the keyboard
5. Used fonts to create, preview and publish stories
6. Opened a new tab and logged out, then tried to delete font in the first tab - error message displayed as expected
7. Checked Experiments to confirm that Custom Fonts are enabled
8. Deleted fonts and opened stories - replacement message displayed
9. Open Anyway - resets the text to a selected font
10. Tried adding an invalid font (https://overpass-30e2.kxcdn.com/overpass-extrabolditalic.ttf) - removed the dash (-) between "extrabold" and "italic"


**Fonts added:**

![01 fonts added.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/3c60b500-5ba4-439d-91d2-48c8272d7098)

**Duplicate fonts:**

![02 dup font.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/c50a7804-c1c2-4d0c-84a1-714f7f5e5abc)

**Deleting font while logged out:**

![03 logged out.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/9e9996f0-9eb0-43b3-937f-6c039c998004)

**Custom font on editor:**

![04 custom fonts editor.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/acc01133-5536-45dd-9a06-8098572ea50a)

**Custom font on preview:**

![05 custom fonts preview.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/51d8e552-af90-4db1-829f-857e7550776e)

**Custom font on published stories:**

![05 custom fonts published.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/2cb0cc52-c751-4206-b325-0310da7d1090)

**Custom fonts enabled:**

![06 enable adding custom fonts.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/995a7b20-926d-4332-a770-caac3a0a5731)

**Open stories after removing fonts that have been used:**

![07 opening stories after deleting custom fonts that have been used.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/497d0834-d40e-462a-ba14-8dcffe17b0e8)

**Replacing removed fonts:**

![08 replaced font Bungee Shade.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/95770d56-f1c6-433c-a2b2-7a8b879345f4)

**Adding an invalid font:**

![09 invalid font.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/3da0755c-700c-454e-928c-58afd0ceaf70)
