### ISSUE TITLE
Dashboard: `document.title` not updating on Settings page

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10923]
## Bug Description

The dashboard package has this effect to update `document.title` for route changes:

https://github.com/GoogleForCreators/web-stories-wp/blob/fe78d62bf89ef320638c1f66984a91c1291e521c/packages/dashboard/src/components/interfaceSkeleton/index.js#L91-L118

Since this lives in `dashboard`, it's not aware of the `Settings` page which lives in 

## Expected Behaviour

The document title should be updated accordingly.

Maybe we should just move this to `wp-dashboard`?

Also, we can remove that backwards compatibility code there.

## Steps to Reproduce

1. Go to "Explore Templates", see document title updating to "Explore Templates"
2. Go to "Settings", see document title updating to ... "Dashboard"

## Additional Context

- Plugin Version: 1.18.0
- WordPress Version: 5.9
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
cc @sayedtaqui for thoughts. Do you think we should move this completely over to `wp-dashboard`, or do you have an idea on how this is best done?

**Comment by mohdsayed** [comment]
@swissspidy I think it should be fairly easy to update the document title since we have access to `leftRailSecondaryNavigation` from `useConfig`. Also, I see `\u2212 WordPress` in the document title, can we just remove that text from the string, or is it important to keep it in the title?

Tried in https://github.com/GoogleForCreators/web-stories-wp/pull/10942

**Comment by swissspidy** [comment]
It would be nice if we're able to keep that text, for consistency with other admin screens, but not a huge deal if not possible. Perhaps we could have a  `documentTitleSuffix` passed via config?

Then we could do something like this:

```js
const { documentTitleSuffix = __('Web Stories', 'web-stories') } = useConfig();

document.title = sprintf(
      /* translators: Admin screen title. 1: Admin screen name, 2: Network or site name. */
      __('%1$s \u2039 %2$s, 'web-stories'),
      dynamicPageTitle,
      documentTitleSuffix
    );
```

And `wp-dashboard` could pass

```js
documentTitleSuffix: __('Web Stories \u2212 WordPress', 'web-stories')`
```

Haven't tested it though.
