### ISSUE TITLE
Media Recording (Video/Audio/Image Capture)

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10930]
## Summary

Creating custom media today is a big pain due to asset management etc.

We want to explore adding video/audio recording capabilities to the story editor, so that you could record yourself, for example for narration.

## References

Quick prototype:

https://user-images.githubusercontent.com/841956/158474813-e816259e-1a1e-4d73-954c-11222265e183.mov

## Acceptance Criteria

* Video capture with or without audio -> insert as video to story
* Image capture -> capture current frame to take a picture -> add as image to story
* Audio-only capture -> upload as background audio

### Does this epic have any performance impact?

N/A

### Does this epic have telemetry?

Yes

**Comment by nicholassykes** [comment]
@swissspidy I wonder if the scope of this feature might be widened a little to include screen video recording in combination with webcam and audio so that users can provide a show and tell? Like Loom..

**Comment by swissspidy** [comment]
Thanks for the suggestion! We will consider this as an enhancement after building the initial feature. But I‘d imagine it‘s a bit difficult to get a useful screen recording in the size of a story.
