### ISSUE TITLE
Adding/Removing custom font doesn't reflect instantly 

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#10940]
## Bug Description

When user adds or removes a custom font, the list of custom fonts is not updated instantly. Sometimes the user needs to add or remove 2 or 3 times until changes are reflected. Please check video below.

## Expected Behaviour

Whenever user adds or removes a custom font, list should be updated instantly.

## Steps to Reproduce

1. Access Stories Settings screen
2. Add a custom font - the font is not displayed
3. Repeat the add flow until the font is added - now the font is added
4. Click on delete font - the font is not removed, list still displays the font
5. Repeat the delete flow until the font is removed - now the font is gone

## Screenshots

https://images.zenhubusercontent.com/235435637/bf3f656d-075e-4e6a-b8ac-8cc8c77ddec4/custom_font.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Weird. I don't see this locally, so I suspect this is something odd going on on the QA environment. Needs some testing.

**Comment by swissspidy** [comment]
Hmm looks like it’s cache related: Chrome serves the fonts list from cache instead of requesting it anew.
We’ve had issues with caching on the Pantheon environment in the past. Maybe we need to add some ETag or Cache-Control headers, or do cache busting using some other way.

<img width="1568" alt="Screenshot 2022-03-18 at 14 25 06" src="https://user-images.githubusercontent.com/841956/159011548-b70423dc-a578-4a38-b906-14d4c6a6660d.png">

**Comment by timarney** [comment]
Can we do a simple cache bust for this request like:


https://github.com/GoogleForCreators/web-stories-wp/commit/4de72ad10ec3b5bfd1e522e5ef83edc4b37fbd05

<hr>

<img width="549" alt="Screen Shot 2022-03-23 at 8 39 39 PM" src="https://user-images.githubusercontent.com/62242/159819575-791509ae-4185-40e7-bc6b-bfe2b0f1bdd2.png">

**Comment by swissspidy** [comment]
I would like to avoid such a hacky cache busting query param if possible.

Can we try sending a `Cache-Control', 'no-cache, must-revalidate, max-age=0'` header in `\Google\Web_Stories\REST_API\Font_Controller::get_items()` instead?

See https://pantheon.io/docs/cache-control

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11070.

1. Added custom fonts - fonts added
2. Deleted some of them - fonts deleted instantly
3. Added same fonts again - fonts added
4. Tried adding existing fonts - error message displayed
5. Deleted fonts again - fonts deleted instantly

Fonts used:

https://overpass-30e2.kxcdn.com/overpass-extrabold-italic.ttf
https://overpass-30e2.kxcdn.com/overpass-regular.ttf
https://overpass-30e2.kxcdn.com/overpass-semibold-italic.ttf
https://overpass-30e2.kxcdn.com/overpass-italic.ttf
https://overpass-30e2.kxcdn.com/overpass-extrabold.ttf
https://overpass-30e2.kxcdn.com/overpass-semibold.ttf

https://images.zenhubusercontent.com/235435637/07ddf7a2-968e-4915-9018-8b19c8a5fc34/11070.mp4
