### ISSUE TITLE
Quick Actions: Empty when multiple elements selected

### ISSUE THREAD

**Issue by BrookeGraham** [swissspidy/web-stories-wp#10950]
## Bug Description

When multiple elements which are of different types are selected, the quick actions menu is empty, but we are still showing the empty container.

## Expected Behaviour

The quick actions menu shouldn't show if there are no actions for the selected elements.
## Steps to Reproduce
Add two elements of different types, eg. a text element and a shape, or a an image and a video.
Select them both
Notice quick actions is an empty box. 

## Screenshots
![Screen Shot 2022-03-16 at 9.36.20 AM.png](https://images.zenhubusercontent.com/61252a26f86e89526edc42b7/30c1aaab-e665-4d2a-935b-7cc4c3eec0c0)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #11064.

1. Added an image
2. Added a video
3. Added a sticker
4. Added a text
5. Added a shape
6. Selected all elements at once - quick actions menu is not rendered (no empty menu).

![11064.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/3fc9efd8-b0f1-4414-9719-8140a1e23e0b)
