### ISSUE TITLE
Saved Styles: Provide ability for styles to be named

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10968]
## Feature Description

In larger organizations where there are many editors who are responsible for creating stories, it would be helpful for there to be an ability to name a saved text style so others can easily find and use a specific saved style quickly when it's necessary. 

This would require a UI to add the name at time of creation, a UI to edit/update the name if necessary, and UI updates to display the named style wherever they are presented.

**Comment by BrittanyIRL** [comment]
This idea should be run through @gajasinski @aaskedall @swissspidy for approval and priority. Moved to product brief needed.

**Comment by gajasinski** [comment]
@bmattb to clarify - we already provide standard font names, but this ask is to allow a user to save e.g. "TNR, bold, size 14" as a preset and to be able to save this as something like "Story present #4" ?

**Comment by swissspidy** [comment]
This is about adding names for these saved styles in this section of the editor:

<img width="351" alt="Screenshot 2022-03-22 at 13 26 48" src="https://user-images.githubusercontent.com/841956/159481786-9304d768-2be9-48f6-a0fa-a7eb27ac4a61.png">
<img width="644" alt="Screenshot 2022-03-22 at 13 27 44" src="https://user-images.githubusercontent.com/841956/159481935-697b8b0a-91a7-4500-b4b3-92f352c92489.png">

**Comment by gajasinski** [comment]
thanks @swissspidy makes sense.

Is there someone that has specifically asked for this feature? Do we know how many saved styles are typical?

**Comment by bmattb** [comment]
This was an ask from Newscorp. Here is the scenario - they have multiple editors using the same WP instance for Story authoring, and as such would like the ability to provide **custom** names on saved text styles such as "Title Page Story Header" or "Dow Jones image caption" on the text presets. Hope this clarifies!

**Comment by gajasinski** [comment]
@swissspidy i'm open to prioritizing this if we can make sure that the editing pencil isn't doing double duty as rn it allows you to delete a saved style. @agingoldseco @aaskedall cc
