### ISSUE TITLE
Image Capture: Initial implementation

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10962]
## Feature Description

In addition to video capture, capturing a still image of the webcam stream would be trivial to implement and be a nice feature addition.

This would mean displaying a "Take still picture" button or something after recording starts that allows us to do this.

**Comment by timarney** [comment]
Quick in browser test seems to work well. 
https://codepen.io/timarney/pen/JjMNpga

I should be able to use the existing video element from #10958 and have a canvas element to show save the photo if that's what you had in mind @swissspidy 

**Noting:**

I took a look at the `ImageCapture()`  --- but looks like it lacking some browser support 
<img width="500" alt="Screen Shot 2022-03-28 at 7 47 07 AM" src="https://user-images.githubusercontent.com/62242/160391624-1784806e-e940-47cd-a4c0-d99ada6632d6.png">

https://developer.mozilla.org/en-US/docs/Web/API/ImageCapture/ImageCapture
