### ISSUE TITLE
Text: Unexpected line wraps on mobile with Fill & Highlight mode

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#10973]
## Bug Description
Original Report: https://wordpress.org/support/topic/text-and-text-boxes-not-rendering-correctly-on-mobile/#post-15469856
Story: https://gringajourneys.com/web-stories/fun-facts-about-rome-italy-story/

There are unexpected line wraps when viewing the story on mobile iOS devices, in both Safari and Chrome browsers. 
This occurs when background mode has been set to "Fill" or "Highlight" to the text. See this example story on mobile: https://testsite.cmsdevrel.com/web-stories/test-317/

## Expected Behaviour
For there to be the same behavior on mobile.

## Steps to Reproduce

1. Add text
2. set background mode to Fill
3. Save the story and view it on mobile iOS device e.g. iPhone XR, iPhone 12, or any other iPhone and any browser.

## Screenshots

iPhone
![Screen Shot 2022-03-17 at 3 29 06 PM](https://user-images.githubusercontent.com/66372350/158882708-ee386614-7072-46a6-97f8-0669d9a5ffa4.png)

Android Samsung Chrome

![Screen Shot 2022-03-17 at 3 46 32 PM](https://user-images.githubusercontent.com/66372350/158883584-27b92533-6773-474d-b572-cad46a4b9a38.png)

Chrome - Desktop
![Screen Shot 2022-03-17 at 3 29 17 PM](https://user-images.githubusercontent.com/66372350/158882721-4753658f-b33d-41c4-ae8f-57f3daa9cf64.png)

Safari - Desktop
![Screen Shot 2022-03-17 at 3 29 43 PM](https://user-images.githubusercontent.com/66372350/158882733-afc54990-06db-4113-80a4-d73078817981.png)

Firefox - Desktop
![Screen Shot 2022-03-17 at 3 30 18 PM](https://user-images.githubusercontent.com/66372350/158882738-6a15df9b-a81e-4ced-82b5-31db5682093b.png)

## Additional Context
Simulated story on other Android devices and the text wraps displayed as expected. 

- Plugin Version: 1.18.1
- WordPress Version:
- Operating System: iOS - iPhone
- Browser: Safari, Chrome

**Comment by LuckynaSan** [comment]
Another similar report: https://wordpress.org/support/topic/text-formatting-incorrectly-desktop-vs-mobile/
Text has unexpected line wraps when previewing it on desktop & iPhone. 

The issue does not occur in Safari for [this user's story](https://holidaystoswitzerland.com/web-stories/things-to-do-in-montreux-and-vevey/), but it does occur in Chrome & Firefox.

When I tested with [this story](https://testsite.cmsdevrel.com/web-stories/1007/), the text with Fill applied does not display correctly in any browser.

Steps to repro:

1. Create story
2. Add Text Title 1 with a few more words
3. Apply fill mode
4. Preview story (on Desktop Chrome, Firefox, & iPhone 12)
5. Note missing text

**Editor:**
![image](https://user-images.githubusercontent.com/66372350/163030556-67db0dc5-3f56-45aa-bb95-c67091873608.png)

**Preview**
![image](https://user-images.githubusercontent.com/66372350/163030586-2b59f5ea-3b82-46aa-862e-6ceccc910714.png)

**User's story in Chrome**
![image](https://user-images.githubusercontent.com/66372350/163030623-1db31d97-54e1-4799-b9e0-46cd47b1bcb6.png)

**User's story in Safari**
![image](https://user-images.githubusercontent.com/66372350/163030686-2973a6d1-6091-4021-b1ad-74d7800861af.png)

**Comment by swissspidy** [comment]
Best addressed with manual soft line wraps
