### ISSUE TITLE
UI Simplification: Insert a text when using the `T+` quick-action

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10974]
## Feature Description
Previously, we had a `T+` icon inside the Insertion panel Text tab to add a text quickly. This was removed in #10493.
UX wants to bring back an option to insert a text quickly, but this will now be done from the quick-action menu.

Todo:

- [ ] Adjust the `T+` button in the quick-action menu so that it would insert a new text **in addition** to its current functionality (opening the Style panel and highlighting the presets area)
- [ ] The text content will be `Fill in some text` and it will have the same props as the [previous quick-action text had.](https://github.com/GoogleForCreators/web-stories-wp/pull/10493/files#diff-2ce9cbec9cb7bf2cc94d4207e01993a95353ae7cee46efe191f5ec86e830b8f8R57) We'll need to add the preset back to the text presets file.
- [ ] Add Karma tests for the new feature.

Note that everything else stays the same: when to display the button, its previous functionality will remain, etc.

## Additional Context

Props the text was previously added with:
```
const DEFAULT_PRESET = {
  content: __('Fill in some text', 'web-stories'),
  fontWeight: FONT_WEIGHT.NORMAL,
  fontSize: dataFontEm(1.2),
  lineHeight: 1.5,
  x: DEFAULT_LEFT_MARGIN,
  y: (PAGE_HEIGHT - dataFontEm(1.5)) / 2,
  font: TEXT_ELEMENT_DEFAULT_FONT,
  width: DEFAULT_WIDTH.DEFAULT,
  textAlign: 'center',
  borderRadius: DEFAULT_TEXT_BORDER_RADIUS,
  padding: DEFAULT_TEXT_PADDING,
};
```

T+ button in the quick-action menu:
<img width="283" alt="Screenshot 2022-03-17 at 16 53 50" src="https://user-images.githubusercontent.com/3294597/158972346-024b02c0-dff8-47f4-b649-ee4f241be64a.png">

**Comment by BrittanyIRL** [comment]
@mariana-k please tag @samwhale and myself for review on this. Peapod has historically "owned" the quick actions. Also happy to answer any questions you have as you do this.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11092.

https://images.zenhubusercontent.com/235435637/8ad276d0-bd66-462e-84b1-04dcd725b52c/2022_04_18_17_21_45.mp4
