### ISSUE TITLE
Unstable Karma Tests related to Element Types

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10985]
## Bug Description

There seems to be something off in Karma now with the merged elements packages (#8125 #8777 ) 

In that PR the integration tests failed here on deleting a saved template: https://github.com/GoogleForCreators/web-stories-wp/runs/5582288091?check_suite_focus=true#step:7:67  this failed in the first (of 4) shards to run for karma so the other three didn't ever run. Now depending on what order tests are run, we're getting random fails. These _feel_ related to this update because it's referencing element types. 

This needs to get updated quickly because it's blinding our entire integration test suite.

## Expected Behaviour

Passing karma tests in CI

## Examples of Failing Tests Post Merge  

[Grid view focus trap re element shape](https://github.com/GoogleForCreators/web-stories-wp/runs/5602758403?check_suite_focus=true#step:7:55) 
<img width="877" alt="Screen Shot 2022-03-18 at 10 18 31 AM" src="https://user-images.githubusercontent.com/10720454/159051816-a07890b3-ca75-456e-b49b-9354633f71a2.png">

[Unable to find shapes element](https://github.com/GoogleForCreators/web-stories-wp/runs/5602758403?check_suite_focus=true#step:7:55)
<img width="883" alt="Screen Shot 2022-03-18 at 10 16 11 AM" src="https://user-images.githubusercontent.com/10720454/159051625-6fc1c48a-1c48-4904-b707-72ef5ffe0699.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
FYI @sayedtaqui
