### ISSUE TITLE
Floating Menus: Enable Experiment

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10988]
## Feature Description

All of floating menu work was done behind `Floating Menu` experiment. This ticket is to enable said experiment by default. 

## Acceptance Criteria 

All floating menus should be functional. All of these actions are lifted from the design panel. They should work the exact same way unless noted as an exception. They should not be impacted by RTL vs LTR. 

Note: Keyboard functionality is not done! It's a little janky right now. Work for that will be completed [here](https://github.com/googleforcreators/web-stories-wp/issues/10872) and QA'd independently.  

There are 6 types of menus: 
1. Text
2. Shapes
3. Images
4. Videos
5. Stickers
6. Multiple elements selected (same or different type doesn't matter) 

**Text**
| Button | Expected Functionality | 
| --- | --- | 
| Font Picker | Picks font | 
| Font Size | Sizes font | 
| Text Align | Aligns text element | 
| Text Style Bold, Italic, Underline | Toggles respective styles | 
| Color Eyedropper | selects color from canvas | 
| Color Picker | selects font color |
| More | sends to style panel (design panel) | 
| Dismiss | Dismisses menu | 

**Shape (Rectangle)**
| Button | Expected Functionality | 
| --- | --- | 
| Color Eyedropper | selects color from canvas | 
| Color Picker | selects color |
| Opacity | sets opacity (doesn't have `%` appended like in the panel) |
| Corner radius | Sets corner radius, only visible if locked |
| Flip vertical | toggle flip | 
| Flip horizontal | toggle flip | 
| Border width | sets border width | 
| Border color | sets border color | 
| More | sends to style panel (design panel) | 
| Dismiss | Dismisses menu | 

**Shape (Round)**
| Button | Expected Functionality | 
| --- | --- | 
| Color Eyedropper | selects color from canvas | 
| Color Picker | selects color |
| Opacity | sets opacity (doesn't have `%` appended like in the panel) |
| Flip vertical | toggle flip | 
| Flip horizontal | toggle flip | 
| Border width | sets border width | 
| Border color | sets border color | 
| More | sends to style panel (design panel) | 
| Dismiss | Dismisses menu | 

**Image**
| Button | Expected Functionality | 
| --- | --- | 
| Opacity | sets opacity (doesn't have `%` appended like in the panel) |
| Flip vertical | toggle flip | 
| Flip horizontal | toggle flip | 
| Border width | sets border width | 
| Border color | sets border color | 
| More | sends to style panel (design panel) | 
| Dismiss | Dismisses menu | 

**Video**
| Button | Expected Functionality | 
| --- | --- | 
| Opacity | sets opacity (doesn't have `%` appended like in the panel) |
| Flip vertical | toggle flip | 
| Flip horizontal | toggle flip | 
| Border width | sets border width | 
| Border color | sets border color | 
| Loop | checkbox to loop video |
| Trim | Trim video (local only)|
| Mute | Only there if there is audio to remove | 
| More | sends to style panel (design panel) | 
| Dismiss | Dismisses menu | 

**Sticker**
| Button | Expected Functionality | 
| --- | --- | 
| Opacity | sets opacity (doesn't have `%` appended like in the panel) |
| Flip vertical | toggle flip | 
| Flip horizontal | toggle flip | 
| More | sends to style panel (design panel) | 
| Dismiss | Dismisses menu | 

**Multiple Elements**
| Button | Expected Functionality | 
| --- | --- | 
| Align left | align group left |
| Align center | align group center | 
| Align right | align group right | 
| Align top | align group top | 
| Align middle | align group middle | 
| Align bottom | align group bottom |
| Dismiss | Dismisses menu | 

<img width="878" alt="Screen Shot 2022-03-18 at 12 09 14 PM" src="https://user-images.githubusercontent.com/10720454/159073031-458ce1ad-09f5-4a4e-b9c8-fdbd7962dc15.png">

**Comment by BrittanyIRL** [comment]
@felipebochehin87 I accidentally merged this ahead of bug bash, could you do testing from /main instead?

**Comment by felipebochehin87** [comment]
Sure @BrittanyIRL , I'm on it!

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using Main branch.

1. Added a text and clicked on it - floating menu displays buttons and works as required on the AC section
2. Added a rectangle element and clicked on it - floating menu displays buttons and works as required on the AC section
3. Added a round element and clicked on it - floating menu displays buttons and works as required on the AC section
4. Added an image and clicked on it - floating menu displays buttons and works as required on the AC section
5. Added a video and clicked on it - floating menu displays buttons and works as required on the AC section
6. Added a sticker and clicked on it - floating menu displays buttons and works as required on the AC section
7. Added multiple elements and selected them all - floating menu displays buttons and works as required on the AC section
