### ISSUE TITLE
Floating Menu Return Focus to Element

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11003]
## Feature Description

When a floating menu is active and user has entered it, focus should return to the element and allow the user to 'tab' to the next element when the user hits `esc` from the floating menu. 

## Acceptance Criteria 

- Hitting `esc` from floating menu returns focus to active element, tabbing again selects the next element
- Karma test for the above

**Comment by BrittanyIRL** [comment]
this might actually be duplicated by #10872 - keeping it around for the time being.

**Comment by felipebochehin87** [comment]
Open question on PR #11328.
