### ISSUE TITLE
Floating Menus: Overlapping 'Mixed' Input

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11018]
## Bug Description

Found in bug bash by @samwhale  and confirmed by @BrittanyIRL 

<img width="363" alt="Screen Shot 2022-03-22 at 10 34 49 AM" src="https://user-images.githubusercontent.com/10720454/159541355-a34c1b03-7951-48e2-8d8c-012fda56e89a.png">

If a text element has more than 1 color it gets the 'mixed' input, this input overlaps with the 'more' button. If the input swaps to 'mixed' it should expand the allowed input space. This needs to happen for other languages too! 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11030.

1. Added a text to the canvas
2. Added multiple colors to the text - "Mixed" is not overlapping "More" anymore
3. Regressed color pickers - no impact

![11030.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/a8ab74c9-9884-4d89-ad5d-8b639c2d4107)
