### ISSUE TITLE
Floating Menu: Apply "Saved Color" as border color causes crash

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11019]
## Bug Description

Found by @LuckynaSan  during bug bash, confirmed by Brittany 

> Editor crashes when you add a masked border to an element & select a saved color on the floating menu bar.

Note, this isn't an issue if you apply color for a border in the panel because saved colors aren't available there for border colors. Furthermore, it seems like it's just gradients causing the crash. Makes sense. 

## Steps to Reproduce

1) Insert element 2) Apply border from floating menu bar 3) open color picker 4) Select saved color (green in this case) 5) Editor crashes with error message below
## Screenshots

<img width="798" alt="Screen Shot 2022-03-22 at 10 42 00 AM" src="https://user-images.githubusercontent.com/10720454/159542587-17db5194-6648-4344-96e9-ac20e55d463a.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #11025.

1. Added an image
2. Added border
3. Added a custom color to the border - no errors
4. Selected a default color to the border - no errors
