### ISSUE TITLE
Adaptive colors function not initially working as expected

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11022]
## Bug Description
Originally reported by @BrittanyIRL and confirmed by @BrookeGraham 

> If my background color is black and I toggle adaptive colors on and add a new text preset to the page, it should have a white font color right? This wasn’t the case but then I went back to screen capture and it’s fine now?

from @BrookeGraham 

> Firefox, similar. If I the background is selected when I add a preset, then the white text appears on the black background while adaptive colors is on. However if I am not on the background, the adaptive colors isn't working for the presets. It updates  the text colors once I clic
![image8](https://user-images.githubusercontent.com/58738530/159565120-79d613a2-39d8-4dbe-801b-56c71930668d.gif)
k on the background

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by merapi** [comment]
After testing it in different browser (Safari, Chrome, Firefox)/os (macOS, Windows) configurations I can say that it's working 100% of the time for me, the text is white on a black background and that other bug is also not happening. While it's working for me consistently it may not work for all people all the time but that's the nature of `html-to-image`.

Example: Safari/Chrome/Firefox on MacOS
![image.png](https://images.zenhubusercontent.com/5e974c555859f780ea7d294f/8b10871c-b7bf-4951-b40b-b4bba32342b3)

**Comment by merapi** [comment]
Let's check if Felipe can reproduce it.
