### ISSUE TITLE
Popup Sidebar Regression: Overlap

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11020]
## Bug Description

Seems a regression occurred somewhere in the sidebar work because these popups _were_ addressed. Now they are overlapping again. 

Text color is fine but now border and bg are overlapping. 

| Border | Text color | Background |
| --- | --- | --- | 
| <img width="642" alt="Screen Shot 2022-03-22 at 10 52 21 AM" src="https://user-images.githubusercontent.com/10720454/159544407-be4a94e3-aa67-4cd6-91ae-455fcc96a76d.png"> | <img width="641" alt="Screen Shot 2022-03-22 at 10 52 28 AM" src="https://user-images.githubusercontent.com/10720454/159544434-8393b1da-1b0e-4618-b243-79b8c3c35dac.png"> | <img width="632" alt="Screen Shot 2022-03-22 at 10 52 35 AM" src="https://user-images.githubusercontent.com/10720454/159544471-3fcfc481-6c78-449c-a209-5972b4acb894.png"> | 

## Additional Context

PR that originally fixed: https://github.com/GoogleForCreators/web-stories-wp/pull/10883 

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11033.

1. Created a new story
2. Added image, video, shape, text and gif
3. Clicked on the items and expanded their color pickers - opened as expected
4. Hovered over the buttons - tooltips are displayed as expected
5. Tested tooltips on the dashboard - ok
6. Repeated same steps on RTL and LTR - same results
