### ISSUE TITLE
Unable to delete a text selection - Safari

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11034]
## Bug Description

Originally reported by @samwhale 
Highlighting all text with `Cmd + a` and pressing `Backspace` does not delete the text. It only deletes one letter at a time

![image3](https://user-images.githubusercontent.com/58738530/159604822-d1677ede-8eb8-47bd-a79b-eee4a7caca4c.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Possibly related: #11061

**Comment by swissspidy** [comment]
Similar issue in Chrome:

1. Select all text using Cmd+A
2. Press backspace
3. Click outside the text element, e.g. on the canvas
4. The text is back

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11099.

1. Added text element to the canvas
2. Selected all and hit backspace (and also delete)
  * selected all clicking on the text
  * selected all using CTRL + A
  * selected all using Command + A
  * selected all clicking and dragging the cursor
