### ISSUE TITLE
Remove empty text element from the Canvas

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11035]
## Bug Description
Originally reported by @samwhale 

Selecting the text in a text set and deleting it, shows that the text is deleted. Clicking outside of the text element makes the previously deleted text reappear

Update: this was working as [intended](https://github.com/GoogleForCreators/web-stories-wp/pull/1323/files#r414933387), we are now changing the expected behavior.

## Expected Behaviour

The text element should be removed from the Canvas.

From Slack: "if the user gets rid of all the text in a box, the element should disappear. If it was a mistake, they can always undo, but it would be annoying have empty text boxes cluttering the canvas."

## Steps to Reproduce

1. Add a preset
2. Highlight all text by dragging or double clicking text
3. Press ‘backspace’
4. Click away from it. Text does not stay deleted.

## Screenshots
![image5](https://user-images.githubusercontent.com/58738530/159605363-06d7453a-83a8-47f3-aa8d-618f4886218d.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser: Safari

**Comment by merapi** [comment]
From my testing: this is not Safari only.

**Comment by swissspidy** [comment]
Possibly related: #11034, #11061

**Comment by merapi** [comment]
Since it's not a fresh bug and it worked like that for the last 2 years I've started to look for the reasoning and found [this](https://github.com/GoogleForCreators/web-stories-wp/pull/1323/files#r414933387). I will ask UX for confirmation.

**Comment by merapi** [comment]
**Expected Behaviour** updated, it should now remove the whole text element.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11124.

1. Added a text element to the canvas
2. Cleared text content
3. Selected all elements in the canvas (and also checked Layers) - text element is gone

https://images.zenhubusercontent.com/235435637/92506311-ece3-47a7-b30b-7979c1907e04/11035.mp4
