### ISSUE TITLE
Page audio not played in preview (old Safari)

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11044]
## Bug Description

Originally reported by @samwhale 
Unable to hear audio in ‘preview mode’ unless I switch tabs and then come back to the tab with the preview.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System: macOS BigSur 11.6.2
- Browser: Safari 14.1.2

**Comment by swissspidy** [comment]
What is "old Safari"? 🤔 @samwhale can you perhaps share some more details?

**Comment by samwhale** [comment]
Sure! My mac is on `BigSur 11.6.2` with `Safari 14.1.2`

During bugbash @spacedmonkey tested with Monterrey and I tested with BigSur (since I haven't updated my mac 😓 )

**Comment by swissspidy** [comment]
Thanks. Do you perhaps have some steps to reproduce or even a video?

Note that the preview mode is part of the stories format itself, it's not something we maintain or can control. So this sounds like a candidate for closing.

**Comment by samwhale** [comment]
The audio isn't included in this screen recording, but the captions show when the audio was playing. For this video, please use that as an indicator of when the audio is playing.
https://user-images.githubusercontent.com/22185279/159937805-ac5683dd-34f0-4064-aef9-3919bd24723e.mov

**Comment by swissspidy** [comment]
@samwhale Still happening also when you click on "Open story" in the top right? Can you publish the story so I can take a look too?

If the bg audio is correctly set in the source code but still not playing in your specific browser version, then this most likely would need to be reported at https://github.com/ampproject/amphtml as a general issue with stories, not something specific to the editor.

**Comment by samwhale** [comment]
Just confirmed that it is happening when clicking on `Open Story` in the top right as well. After clicking the unmute button, I have to change the tab and come back before the audio starts playing.

**Comment by swissspidy** [comment]
Can you publish the story so I can take a look?

I would really have to check the source code so I can confirm whether it's an upstream issue or not.

**Comment by samwhale** [comment]
Just published in staging: 
![image](https://user-images.githubusercontent.com/22185279/160147030-ae3da617-49ef-403a-a4da-f2fcdd09d768.png)

**Comment by swissspidy** [comment]
Thank you.

Source code looks good, playing works fine in all browsers here, so this would need to be reported as a browser compat issue upstream.
