### ISSUE TITLE
Eyedropper tool on custom fonts not working as expected

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11049]
## Bug Description

Originally reported by @merapi 

There might be some issues with Custom Fonts & Eyedropper (top 3 are existing fonts, bottom 3 are newly added custom fonts). Custom fonts appear differently in the editor when the eyedropper tool has been selected.

NB - also note that the second font (which is not a custom font) has also changed it's appearance.

Canvas:
![image15](https://user-images.githubusercontent.com/58738530/159717050-7ed0e6a0-6f91-4ccb-a05c-15c83b33322e.png)

Eyedropper:
![image17](https://user-images.githubusercontent.com/58738530/159717108-6234c5bd-5fe3-4fd2-8c6d-dc63adcd6ff5.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
@merapi This might be more of a bug with the eyedropper and `html-to-image` than with the custom fonts and you are a bit more familiar with that.

I briefly checked `htmlToImage.getFontEmbedCSS(fullbleedContainer)` in `prepareEyedropper()` and my custom fonts are definitely in there. So not sure what could be the issue.

**Comment by merapi** [comment]
> This might be more of a bug with the eyedropper

Totally. I've just noticed that none of the custom fonts worked in the eyedropper, so it might be the mix of both that is causing the issue.
