### ISSUE TITLE
Preview presents a Pantheon errror

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11045]
## Bug Description

Originally reported by @BrookeGraham 
Preview shows the following error:
`Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Pantheon_Cache' does not have a method 'no_cache_add_headers' in /code/wp-includes/class-wp-hook.php on line 307 `

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
That's an issue with the test environment, not with the plugin. Nothing we can do about it.

Reached out to their support but apart from that it's not in our hands.
