### ISSUE TITLE
Font preview is not working for custom local fonts

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11048]
## Bug Description

Originally reported by @merapi 
 Font preview doesn’t work (checked on Staging and locally)
![image7](https://user-images.githubusercontent.com/58738530/159714998-3d5bbed4-3bd7-485f-bf53-2f2b1495c22e.png)

It does work after you use the font.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
@merapi This might be more of a bug with the eyedropper and `html-to-image` than with the custom fonts and you are a bit more familiar with that.

I briefly checked `htmlToImage.getFontEmbedCSS(fullbleedContainer)` in `prepareEyedropper()` and my custom fonts are definitely in there. So not sure what could be the issue.

**Comment by felipebochehin87** [comment]
Works in Chrome and Firefox, but not in Safari.

**NOK - Safari:**

![Screen Shot 2022-03-23 at 15.17.05.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/34c0f1e5-192b-46b7-9dd5-a89cd5add6fb)

Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11050.

1. Added custom fonts on Stories > Settings > pasting the URLs below and clicking on Add Font
 - https://overpass-30e2.kxcdn.com/overpass-extrabold-italic.ttf
- https://overpass-30e2.kxcdn.com/overpass-regular.ttf
- https://overpass-30e2.kxcdn.com/overpass-semibold-italic.ttf
2. Created a new Story
3. Added a text element
4. Clicked on the element and expanded the font dropdown - custom fonts are displayed on their format

**OK - Chrome (the same for Firefox):**

![image.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/f94a24c3-9e6a-43f2-b83d-acd900870403)

**Comment by felipebochehin87** [comment]
@swissspidy the changes look good in Chrome and Firefox, but not in Safari. I do see the custom fonts, but their look is not correct.

**Comment by swissspidy** [comment]
@felipebochehin87 Thanks for testing in Safari. Looks like that is related to some other issue that warrants its own ticket. I'll create that accordingly.

**Comment by felipebochehin87** [comment]
OK! :) Thanks for letting me know, @swissspidy.
