### ISSUE TITLE
Multiple elements selected - Order of the buttons on Floating menu is not as the design

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#11059]
## Bug Description

When multiple elements are selected, the order of the buttons on Floating menu is not as designed. Please find below the design (first image) and how the menu looks like (second image).

## Expected Behaviour

Floating menu should be displayed as the design.

## Steps to Reproduce

1. Start a new story using the Main branch
2. Add videos, images, texts...
3. Select them all at the same time and see the order of the buttons on the floating menu

## Screenshots
**Design:**

![image (8).png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/2c04e8fa-3227-4ae3-8873-9e2efb473e34)

**Main branch:**

![image (7).png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/d4987844-caef-4808-9a04-7583b7936c5f)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
As per https://xwp.slack.com/archives/C01ESBB8ZN1/p1647419354023679, the design is incorrect/outdated. The order should match the one from the sidebar, which it now does:

<img width="348" alt="Screenshot 2022-03-23 at 21 00 41" src="https://user-images.githubusercontent.com/841956/159785561-5423d6b9-26f4-4d95-a277-c36376e64e36.png">

Thanks for keeping an eye on this though!
