### ISSUE TITLE
New Story details modal doesn't show the checklist icon in Safari (old)

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11052]
## Bug Description
Orignally reported by @samwhale 
No checklist icon in safari. Only visible issues to me in this state are 2 design and 1 accessibility. No high priority issues. Should the button be visible?
<img width="268" alt="image17" src="https://user-images.githubusercontent.com/58738530/159724107-071fd9b1-af29-42c7-a6e3-bc642b5a7025.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
1. Opened Safari and created a new story
2. Published the story - checklist icon renders

Checked in Firefox and in Chrome too.
