### ISSUE TITLE
Cross-Origin-Resource-Policy errors in Safari

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11060]
## Bug Description

Safari seems to interpret CORS and CORP headers differently than Chrome, throwing tons of console errors when displaying text sets or templates in the editor, and also preventing from enqueueing font stylesheets  (as mentioned at https://github.com/GoogleForCreators/web-stories-wp/issues/11048#issuecomment-1076746765)

The text sets and templates display fine in the browser though, so that part is not urgent.

The fonts not being loaded though is not nice.

## Expected Behaviour

No console errors

## Steps to Reproduce

Open Text Sets or Page Templates pane, or open font picker.

## Screenshots

<img width="746" alt="Screenshot 2022-03-23 at 21 04 49" src="https://user-images.githubusercontent.com/841956/159786213-b1a2e0d6-1f88-416f-b7c5-eefde16ee82f.png">
<img width="1066" alt="Screenshot 2022-03-23 at 21 05 21" src="https://user-images.githubusercontent.com/841956/159786283-d9e9b9fd-6f4d-4e71-bc02-5c4fa521cd92.png">

## Additional Context

- Plugin Version: 1.19.0
- WordPress Version: 5.9
- Operating System: macOS Monterey
- Browser: Safari 15.4

**Comment by ilovefreesw** [comment]
Same in Microsoft Edge. But Google Chrome appears to be working fine.

![image](https://user-images.githubusercontent.com/77317006/181693928-1322bb7d-839f-438d-b2e5-c5b2b3aa36e9.png)

**Comment by swissspidy** [comment]
@ilovefreesw The errors in your screenshot are about something else though and are unrelated.

You need to set up CORS headers for your CDN, check out https://wp.stories.google/docs/troubleshooting/common-issues/ to learn more
