### ISSUE TITLE
Video: Improved handling of video play button

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11068]
## Feature Description

Discovered while working on https://github.com/GoogleForCreators/web-stories-wp/issues/11046. 

Videos can be play / paused using media controls in the browser. ( See video ). But the play / pause button does not respect that. 

See this video, where I am using media keys on my laptop's keyboard. 

https://user-images.githubusercontent.com/237508/159931296-4f769a88-52dc-41d9-9bd7-eeb22afdeb49.mov

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11069.

1. Added a video to the canvas
2. Used Chrome media control - video plays/pauses
3. Used media control from the keyboard - video plays/pauses
4. Regressed other video control - video plays/pauses

https://images.zenhubusercontent.com/235435637/564f326a-6ebb-420d-940f-ef8a7add03c8/11068.mp4
