### ISSUE TITLE
Selecting all text and pasting does not replace text

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11061]
## Bug Description

It does not seem to happen consistently, but most of the time when I select all of the text in a text element using Cmd+A and then paste some new text, the existing one is not replaced.

## Expected Behaviour

Cmd+A and pasting should replace text

## Steps to Reproduce

1. Insert text from preset
2. Select all
3. Paste some text from the clipboard
4. See that existing text was not replaced, just appended

## Screenshots

Towards the end of the video you see it better:

https://user-images.githubusercontent.com/841956/159796985-258fccba-823e-49f5-9ad7-c0dbdfc5f69c.mov

## Additional Context

- Plugin Version: 1.19.0-alpha
- WordPress Version: 5.9
- Operating System: macOS Monterey
- Browser: Chrome

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11099.

1. Added text element to the canvas
2. Selected all and pasted text from the clipboard
  * selected all clicking on the text
  * selected all using CTRL + A
  * selected all using Command + A
  * selected all clicking and dragging the cursor
3. Pasted using Command / Control + V
