### ISSUE TITLE
Video: Replace set to currentTime manually with seekvideo

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11073]
## Feature Description

There are a number of places in the codebase where a video element's currentTime is set manually. However we have a helper function that with error handling called seekVideo. To improve error handling, we should replace these manual calls with calls to seekVideo. 

https://github.com/GoogleForCreators/web-stories-wp/blob/3f50de97c102d278a57f47ddde69fe500779701f/packages/element-library/src/video/playPauseButton.js#L143

https://github.com/GoogleForCreators/web-stories-wp/blob/3f50de97c102d278a57f47ddde69fe500779701f/packages/element-library/src/video/playPauseButton.js#L171

https://github.com/GoogleForCreators/web-stories-wp/blob/e00e50da7a02d956b993f4038ca1c15d46eda3ef/packages/story-editor/src/components/videoTrim/useVideoNode.js#L56

https://github.com/GoogleForCreators/web-stories-wp/blob/e00e50da7a02d956b993f4038ca1c15d46eda3ef/packages/story-editor/src/components/videoTrim/useVideoNode.js#L77

https://github.com/GoogleForCreators/web-stories-wp/blob/e00e50da7a02d956b993f4038ca1c15d46eda3ef/packages/story-editor/src/components/videoTrim/useVideoNode.js#L114

https://github.com/GoogleForCreators/web-stories-wp/blob/e00e50da7a02d956b993f4038ca1c15d46eda3ef/packages/story-editor/src/components/videoTrim/useVideoNode.js#L125

https://github.com/GoogleForCreators/web-stories-wp/blob/3f50de97c102d278a57f47ddde69fe500779701f/packages/story-editor/src/components/library/panes/media/common/mediaElement.js#L152

**Comment by swissspidy** [comment]
Hmm I think this would need closer testing on a case by case basis. Not every one of these instances necessarily needs this overhead.

**Comment by spacedmonkey** [comment]
Seeking video, specially a longer video that is not buffer can take a while and can randomly fail. I think the overhead is worth it to catch possible seek errors.

**Comment by spacedmonkey** [comment]
I put together a very quick PR.  https://github.com/GoogleForCreators/web-stories-wp/pull/11084

In my testing, seeking a video can fail. Wrapping this in a promise, allows us to handle this error.

**Comment by swissspidy** [comment]
Just wrapping in `seekVideo()` without awaiting the promise or catching errors does not help much. In fact, whereas the previous `video.currentTime = ...` call simply failed silently, this now potentially throws errors that aren't being caught anywhere.

Since this mostly affects video trimming, I would prefer to hold off on this and wait for @barklund to return so he can take a closer look at this.

There might be instances of `video.currentTime = ...` where this error handling for seeking is simply not needed.

**Comment by spacedmonkey** [comment]
My PR is a simple case of where these seekvideos might be useful. I think it is true, we should await the seek to complete before doing anything else. At the moment, the fact a seek make some time to complete or might fail altogether is not taking into account. Making this code my async and catching errors like in https://github.com/GoogleForCreators/web-stories-wp/issues/11085, can only serve to ensure that errors are handled.
