### ISSUE TITLE
Media Recording: Feature Detection

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11077]
## Feature Description

As part of the media recording feature we need more robust feature detection.

All our supported browsers support `MediaRecorder`, but the list of supported mime types is quite different.

At first glance:

* Safari on macOS: only supports `audio/mp4` and `video/mp4`, with codecs such as VP8, VP9, AV1, H.264, H.265, OPUS
* Firefox on macOS: only supports `audio/webm`, `video/webm` and `audio/ogg`, with codecs such as VP8, VP9, AV1, H.264, H.265, OPUS
* Chrome on macOS: only supports `audio/webm`, `video/webm` and `video/x-matroska`, with codecs such as VP8, VP9, AV1, H.264, H.265, OPUS  
  See https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/fast/mediarecorder/MediaRecorder-isTypeSupported.html / https://developer.chrome.com/blog/mediarecorder/ for details

We should use [`MediaRecorder.isTypeSupported`](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/isTypeSupported) to determine which mime types to use. Perhaps ideally with the `H.264` codec, but not specifying the codec should also work.

## Additional Context

https://cconcolato.github.io/media-mime-support/
https://stackoverflow.com/a/64656254/1185292

**Comment by spacedmonkey** [comment]
As discussed in sync, we need data for Window and linux,  Edge and chromium based browsers.

**Comment by swissspidy** [comment]
Right now this seems less of an issue actually since we just take what we receive from the browser and use that as-is.
