### ISSUE TITLE
Floating Menu: Clicking the border input focuses the opacity input

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#11088]
## Bug Description

Clicking the border input focuses the opacity input in the floating bar for images.

## Expected Behaviour

Clicking the border input should focus the border input in the floating bar for images.

## Steps to Reproduce

1. add an image
2. click the border input

## Screenshots

![click](https://user-images.githubusercontent.com/22185279/160150722-c52e73b2-a2c3-431e-99d5-94a9b730d0fd.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #11090.

1. Added a shape
2. Added border to the shape
3. Clicked on the border and on color picker related to the border - focus remains on those fields as expected - first element is not focused

**Comment by samwhale** [comment]
Thanks @felipebochehin87 !!
