### ISSUE TITLE
Text: Unexpected line wraps / overflowing text

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11117]
### Case 1
https://www.mansionglobal.com/visual-stories/beverly-hills-home-comes-with-butterfly-house-plans-01648229898

Issue is on page 6 of the story above

Mansion Global produces a number of web stories daily and has noted a couple of times that that the presentation of the story in the Discover app doesn't match that of the preview tool nor the editor itself. This ticket addresses one of these times that this discrepancy has been observed.

Here is how the story appears in the editor:
![Screenshot 2022-03-29 at 06.54.11.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/acafdcd6-d968-4d71-8bdf-95849a081f16)

Here is how the story appears after publishing on a desktop - you can see that one of the lines has extended past the text box.

![Screenshot 2022-03-29 at 08.01.18.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/31713242-b2cb-4261-a0a9-0aaf0263711a)

Here is how the story appeared in the Discovery Application on an iPhone 11, I have indicated the formatting concerns:

![IMG-3964](https://user-images.githubusercontent.com/58738530/160664937-5502a95a-73ae-4c59-a89f-586791a87a09.PNG)

Unfortunately, due to a local bug, the Mansion Global team is currently unable to use Preview functionality to identify issues like this prior to publishing.

### Case 2
https://www.mansionglobal.com/visual-stories/adele-filmed-easy-on-me-on-this-listed-quebec-estate-01648574383
Story as it appeared in the editor:

<img width="467" alt="Screenshot 2022-03-30 at 06 11 50" src="https://user-images.githubusercontent.com/58738530/160861643-f25a0ffc-ed18-47b7-8cb9-ec6e05f77174.png">

Story as it appeared post publish on all browsers - Safari, Chrome and Google Discover App
![ADELEslide8](https://user-images.githubusercontent.com/58738530/160862033-cf1669ec-9138-4ece-97b1-754db95d1200.PNG)

Story as it appeared in preview (looks fine)
<img width="1253" alt="Screenshot 2022-03-30 at 07 30 10" src="https://user-images.githubusercontent.com/58738530/160862199-cb644f01-871b-4a78-aa37-df1a14028983.png">

## Expected Behaviour

Text should appear with the same wrapping and positioning as created in the editor, and as shown in the preview tool.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Changed the title because the text wrapping is generally varying between browsers.

Example:

Chrome:
<img width="733" alt="Screenshot 2022-03-30 at 16 38 56" src="https://user-images.githubusercontent.com/841956/160861657-6a43f803-8ac5-4dd5-8a47-012f1a90988e.png">

Firefox:
<img width="849" alt="Screenshot 2022-03-30 at 16 39 25" src="https://user-images.githubusercontent.com/841956/160861686-56db045f-9fbe-4c8f-838e-ed2dd5cb120d.png">

Safari:
<img width="877" alt="Screenshot 2022-03-30 at 16 39 41" src="https://user-images.githubusercontent.com/841956/160861706-dbc8d1a6-1b1d-4324-b131-8a28072e78ca.png">

To some degree that's of course expected because browsers have different engines.

But maybe we can do something here by leveraging font metrics and text box size calculation? 🤷 

In the meantime, an easy workaround should be to manually enter line breaks where desired.

Example:

<img width="1310" alt="Screenshot 2022-03-30 at 16 52 20" src="https://user-images.githubusercontent.com/841956/160864287-b77417fb-105f-4930-8c39-01b7c3661f46.png">

**Comment by bmattb** [comment]
@swissspidy client has confirmed that they are already using manual line breaks to specify where wrapping should occur!

**Comment by bmattb** [comment]
Update: client confirmed with me today that this issue is no longer being presented, although no intervention or edits were made by them. Here is a screenshot from Case 2 showing this (iPhone 11 Pro - same device as previous screenshots)
![IMG-3975](https://user-images.githubusercontent.com/58738530/161099205-3ac66359-7bfd-4f63-b274-4c470eca28d4.PNG)

**Comment by swissspidy** [comment]
> client has confirmed that they are already using manual line breaks to specify where wrapping should occur!

Great. Given this existing workaround I'd consider this a P2 or P3 issue going forward.

**Comment by bmattb** [comment]
After further testing from NC, it appears that this issue is related to the size of the text box in relation to the text itself. If you delete text or use a hard return on some text, but the text box is larger in space than that text, this seems to provide the ability for the  text to unexpectedly wrap / overflow after publishing.

**Comment by RyanNeilson** [comment]
Is this issue slated to be worked on in any future update? Some editors I work with are very interested in seeing a fix for this one.

**Comment by swissspidy** [comment]
I might take another look at it, though it looks like a rather hard to reproduce issue due to the nature of browser differences in text rendering.
Adding hard line breaks is probably still the best solution. Does that work for you?

**Comment by RyanNeilson** [comment]
Yes, hard line breaks is what our editors have been doing until now. It works okay, they're just hoping for a more automated solution.

**Comment by swissspidy** [comment]
Closing for now since hard line breaks is probably the best way to solve this, given all the differences between browsers, devices, and user settings.
