### ISSUE TITLE
Story editor ui broken in storybook 

### ISSUE THREAD

**Issue by santoshgistto** [swissspidy/web-stories-wp#11113]
Story editor ui broken in storybook.
Branch : main
Steps : 
1. Click story editor 
2. Select story card
3. Select style tab

Here is the screenshot 
<img width="708" alt="Screen Shot 2022-03-28 at 4 40 10 PM" src="https://user-images.githubusercontent.com/12577046/160483736-a60b069d-2e03-462d-8c9d-b62b2e0b5b58.png">

**Comment by mohdsayed** [comment]
Thanks for creating an issue for this! Looks like the `StoryEditor` parent container needs some height with the latest UI changes. Fixed in #11115
