### ISSUE TITLE
Consider disabling automatic font scaling based on text box resizing

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11135]
## Feature Description

Some enterprise users are complaining about the automatic resizing of font when the associated text box is resized. The users note that increasing the size of the text box doesn't necessarily imply that an increase in font size is warranted.

Perhaps this could be a toggle in settings for users to set their preferences instead.

CC : @aaskedall @agingoldseco @gajasinski for visibility.

**Comment by swissspidy** [comment]
Curious to learn more about cases where this is not desired. For example, when would you want to have a 100px tall text box but only 1 line of text?

Note that horizontally text elements can be resized without automatically changing the font size. Just not vertically.
