### ISSUE TITLE
Embeds: Next Story button disabled in AMP mode

### ISSUE THREAD

**Issue by fellyph** [swissspidy/web-stories-wp#11137]
## Bug Description

A user has reported at the [AMP WordPress forum](https://wordpress.org/support/topic/next-button-not-working-in-webstories-when-using-amp-in-standard-mode/), about the "Next Story button" is disappearing between the AMP plugin modes, when he selects the **Standard mode** the next story button is disabled but when he switches to **Transitional mode** the buttons get enabled again.

Standard mode
<img src="https://i.imgur.com/2HrFqVb.png" />

Transitional mode
<img src="https://i.imgur.com/lyU1ksB.png" />

## Expected Behaviour

The next stories button should work between both modes, transitional and standard mode.

## Steps to Reproduce

1. Create more than one story
2. Install the AMP plugin
4. Switch between modes
5. Check the next stories button

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Background for this issue:

Normally we print markup like this for story embeds:

```html
<div class="web-stories-list__lightbox">
<amp-story-player width="3.6" height="6" layout="responsive">
	<a href="https://example.com/web-stories/story-1/">Story 1</a>
	<a href="https://webstory.news/web-stories/story-2/">Story 2</a>
	<a href="https://webstory.news/web-stories/story-3/">Story 3</a>
</amp-story-player>
</div>
```

This way, clicking on a single story in the carousel opens the lightbox with the story player, where the player allows you to jump from one story to the next one.

In AMP we cannot easily do this due to AMP's constraints. So we basically do this instead:

```html
<div class="web-stories-list__lightbox">
<amp-story-player width="3.6" height="6" layout="responsive">
	<a href="https://example.com/web-stories/story-1/">Story 1</a>
</amp-story-player>
</div>

<div class="web-stories-list__lightbox">
<amp-story-player width="3.6" height="6" layout="responsive">
	<a href="https://webstory.news/web-stories/story-2/">Story 2</a>
</amp-story-player>
</div>

<div class="web-stories-list__lightbox">
<amp-story-player width="3.6" height="6" layout="responsive">
	<a href="https://webstory.news/web-stories/story-3/">Story 3</a>
</amp-story-player>
</div>
```

**Comment by swissspidy** [comment]
Closing as _maybelater_
