### ISSUE TITLE
Font Check: Automatically update font metrics

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11147]
## Feature Description

I think this has been discussed before but I couldn't find a ticket for it anymore, hence creating this new one.

The current `FontCheck` component in 1.19.0 is super nice. It automatically detects if a story contains a missing font and then allows you to replace it.

Fonts can be missing if it's either a custom font that was deleted or one that was pulled from Google Fonts.

More often than not, fonts on Google Fonts simply get _updated_, not deleted. For example if a font is now available in a new font weight or the metrics have slightly changed.

#10734 is a good example of such an update.

It would be really nice to update `FontCheck` so that it goes through all fonts in a story and then updates them if we have newer information on file.

In order to not cause history updates in the editor for these font updates, we can update `ELEMENT_PROPS_TO_IGNORE` in  `useHistoryEntry.js` accordingly.

**Comment by timarney** [comment]
@swissspidy do we have any helpers for comparing objects already?

Thinking something like  
```javascript
const inUseFonts = getInUseFontsForPages(storyPages);
const allFonts = await getFonts({ include: inUseFonts.join(',') });

// loop over compare the fonts ...

...
updateElementsByFontFamily ...  with new properties 
```

https://github.com/GoogleForCreators/web-stories-wp/blob/main/packages/story-editor/src/app/story/useStoryReducer/test/updateElementsByFontFamily.js#L264

**Comment by swissspidy** [comment]
There's `shallowEqual` in the `react` package that might prove useful.

Theoretically we might not even need to compare any objects and just update the fonts straight away and let the reducer and history provider figure out if there were any actual changes. Because as long as we update `ELEMENT_PROPS_TO_IGNORE` to include `font.fallbacks`, `font.weights`, `font.styles`, `font.variants` and `font.metrics` (I think that's all) then it _should_ work by just updating the data without adding a new history entry (i.e. undo/redo should still be disabled).

But that needs some testing.
