### ISSUE TITLE
Animations: Remove "Coming soon" text

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11185]
## Feature Description

Related: #10577

When multiple elements are selected, the Animations panel currently displays a "Coming soon" text.

<img width="408" alt="Screenshot 2022-04-05 at 13 19 29" src="https://user-images.githubusercontent.com/841956/161744621-f8785d8a-099c-4a91-bce3-74c2cef8eee9.png">

We should not display the panel for multi-selection until this is actually implemented.

**Comment by BrittanyIRL** [comment]
Perhaps that was an optimistic "soon" :)

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11212.

1. Added multiple elements
2. Selected them all
3. Check available options on "Style" menu - "Animation" is not displayed

![no animation.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/7712f3df-5737-4de8-8c42-0b9440906159)
