### ISSUE TITLE
Story Locking: Disable deleting locked stories

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11187]
## Feature Description

In WordPress you cannot delete locked stories:

<img width="444" alt="Screenshot 2022-04-05 at 14 25 09" src="https://user-images.githubusercontent.com/841956/161753091-8a3dc8bd-8ea2-4200-a978-a89fdcd7e4f3.png">

We need to make sure to do the same in the dashboard by disabling the "Delete" button for locked stories.

<img width="428" alt="Screenshot 2022-04-05 at 14 25 21" src="https://user-images.githubusercontent.com/841956/161753080-cb368cc3-43d3-47d8-b6eb-5029d97ff1f9.png">

Should be as simple as adding `case STORY_CONTEXT_MENU_ACTIONS.DELETE:` here:

https://github.com/GoogleForCreators/web-stories-wp/blob/26291c8c18c2156c18241372dc70744fc6ba1bc9/packages/dashboard/src/components/popoverMenu/story-menu-generator.js#L55-L56

But needs Karma tests to verify this

**Comment by swissspidy** [comment]
Noticed that too today. All the more a reason why we should disable deletion in that case. Then this can‘t happen again

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11214.

1. Logged in as a Contributor in Firefox
2. Started a new story
3. Logged in as an Admin in Chrome
4. Visited dashboard (grid and list views) and also "All Stories" screen - unable to select the story to apply bulk action "Move to Trash" on "All Stories" screen and on the dashboard the option to delete is visible, but inactive

**Comment by felipebochehin87** [comment]
Also regressed the unlocked ones and removed them, it works.
