### ISSUE TITLE
Remove Elements Tab Experiment

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11186]
## Feature Description

Since the beginning of time we've had this `showElementsTab` experiment in the editor:

<img width="414" alt="Screenshot 2022-04-05 at 13 18 36" src="https://user-images.githubusercontent.com/841956/161744853-5815009a-f484-4836-a43e-04ebeff4a6ab.png">

<img width="491" alt="Screenshot 2022-04-05 at 13 18 49" src="https://user-images.githubusercontent.com/841956/161744848-d6741a09-7d3c-40f9-a64a-74f275ca798d.png">

While it was originally envisioned to hold some content, we never implemented it.

And now with shopping on the horizon this won't have space anymore anyway.

So let's just completely remove all traces of this experiment/tab.

**Comment by felipebochehin87** [comment]
Tested with all roles - experiment and tab are gone.

![0001.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/f0cb376e-312f-4a32-b7cc-491fc05b1d05)


![0002.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/fbda318e-616d-46a3-8c2d-bb635769f5c1)
