### ISSUE TITLE
Review Checklist/Story Details: Focus Lost

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11196]
## Bug Description

If I am in the story details modal and I click on "review checklist" the focus stays on the publish button making keyboard navigation super annoying to get to the checklist I wanted to review. 

## Expected Behaviour

If I am in the story details modal and I click on "review checklist" the focus should shift to the expanded checklist (just like it does when you open from the checklist button in the footer. 

## Steps to Reproduce

Click "publish" to get to story details modal
Click "review checklist" 
See that the publish button is focused and tooltip (probably) present.

## Screenshots

![Kapture 2022-04-05 at 15 57 30](https://user-images.githubusercontent.com/10720454/161864539-786f0a53-3843-49b0-866e-1a21ce108242.gif)

## Additional Context

I did some discovery into this thinking it could be an easy fix - it looks like the publish button is rerendering _alot_ and I can't quite place why - there's so many hoops it jumps through from story-editor to wp-story-editor back to story-editor. Anyways, I think that's the reason the focus is getting hijacked. 

Updating an e2e test to confirm the focus pattern is correct would be cool too. 

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrittanyIRL** [comment]
@felipebochehin87  - there's testing directions in the PR (#11230)

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11230.

https://images.zenhubusercontent.com/235435637/ecd1784b-3b4d-4e58-873c-d2568ec60e13/2022_04_12_21_43_48.mp4
