### ISSUE TITLE
Layers Panel Using Wrong Tooltip

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11201]
## Bug Description

Layers panel is getting negative values for some of the positioning because it's using the Tooltip outside of story-editor. 

Use Tooltip from Story-Editor, and update the placement to bottom-end since we are at the left edge of the screen anyways.

**Comment by BrookeGraham** [comment]
I was able to fix this with #11280

**Comment by BrookeGraham** [comment]
#11280 only partially fixed this. I will wrap it up in a separate pr.

**Comment by felipebochehin87** [comment]
A minor bug found in Firefox @BrookeGraham @BrittanyIRL are we fixing it in this PR or should I open a new one?

When I hover over "Open Media Picker" (on RTL), the tooltip presents a weird behavior:

The first time I hover over, the tooltip is displayed with no issues;
The second time I hover over, the right side of the tooltip is hidden by the side menu;
The third time ... it works;
The fourth time ... it fails;
...

https://images.zenhubusercontent.com/235435637/938fa37f-fb66-4a00-a99e-98efebfc5822/media_picker_firefox.mp4

**Comment by BrookeGraham** [comment]
Oooh, Thanks. Felipe. Let's make a new ticket for this.

**Comment by felipebochehin87** [comment]
Thanks @BrookeGraham I'll go ahead and create it :)
