### ISSUE TITLE
Shopping: Products JSON Schema Validation

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11210]
## Feature Description

Context: https://github.com/ampproject/amphtml/issues/37746

What is JSON Schema: https://json-schema.org/

Current schema: https://github.com/ampproject/amphtml/blob/main/examples/amp-story/shopping/product.schema.json

Possibly helpful utils for testing:

https://www.npmjs.com/package/jest-json-schema
https://github.com/martin-helmich/phpunit-json-assert

Using this JSON schema for shoppable products, we can verify that the data we return from WooCommerce & Shopify matches the expected format. So most likely this is something for the PHPUnit integration tests.

But this could also be useful for an e2e test, e.g.:

1. Set up WooCommerce with some products
2. Create a new story and add some products
3. Preview the story
4. Take the resulting shopping config
5. Compare the config against the schema

So for that a Jest helper might be useful.

Right now it doesn't look like the schema is hosted somewhere publicly, so we could just create a simply GitHub action workflow to regularly copy the file to this repo for easier usage.

**Comment by jshamble** [comment]
I'll be adding public-facing documentation with a link that points to the product json schema [here](https://github.com/ampproject/amphtml/pull/38042).

**Comment by timarney** [comment]
After digging into this a bit and starting down the PHP unit test road I think the e2e test is going to make the most sense here given the data want to match against and the way that data flows in and out / mocks etc...

**Comment by swissspidy** [comment]
Related: https://github.com/GoogleForCreators/web-stories-wp/pull/11340/files#r857646203

I feel like we shouldn't write off validation in PHP tests just yet, it seems useful to ensure that the query classes return data in expected format. Even if the inputs are just mocked.

**Comment by timarney** [comment]
> I feel like we shouldn't write off validation in PHP tests just yet

Agreed --- feels like there is some value on some PHP checks --- I did test the `phpunit-json` package and it seemed good.

**Comment by swissspidy** [comment]
Just occurred to me that `rest_validate_value_from_schema()` _might_ be able to perform this validation as well. So maybe we don't even need a separate package for this. Needs testing though.

(For context, I stumbled upon https://meta.trac.wordpress.org/changeset/11410)

**Comment by spacedmonkey** [comment]
I put together a little prototype of this - https://github.com/GoogleForCreators/web-stories-wp/tree/try/dynamic-schema. This some promising results. We would have to solve translated string problem, but this looks good. 
<img width="809" alt="Screenshot 2022-05-05 at 17 10 06" src="https://user-images.githubusercontent.com/237508/166966245-d4a2b068-97be-495f-aff7-e5364b6d86cb.png">

**Comment by swissspidy** [comment]
That's very interesting!

But just to be clear, that's not what I meant with my previous comment.

I was referring to validating the results returned `Product_Query` results to ensure that they adhere to the JSON schema, in PHPUnit tests. There are libraries that can do this, but maybe we don't need a library for this if `rest_validate_value_from_schema` can do this too.

While what you did is generating the REST API schema from the JSON file.

So two separate things.

But both are worthwhile!

If you can solve the i18n issue that would be a nice addition to make maintenance of the REST API schema easier.

**Comment by swissspidy** [comment]
Attempted to use `rest_validate_value_from_schema` in #11519. Works well.

Created #11520 for dynamically creating the schema.
