### ISSUE TITLE
Color picker from floating menu is not working as expected

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#11216]
## Bug Description

When I pick a color from floating menu after I selected a color on the right side (or left side) menu, under Style, the color doesn't change (color selected on Style menu prevails). I need to drag and drop the element so that the new color is set.

## Expected Behaviour

Color should be applied at the same second as it was selected.

## Steps to Reproduce

1. Open the editor
2. Add an image element
3. Add a border to the element
4. Click on the element and pick a color from Style menu - color is set
5. Click on the element and pick a color from floating menu - color is not set, unless user drags and drops the element (see video attached)

## Screenshots

https://images.zenhubusercontent.com/235435637/dde978ad-e7b3-4fbf-bd24-93b84c386a88/2022_04_07_16_30_24.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
@BrittanyIRL @BrookeGraham

**Comment by BrittanyIRL** [comment]
Thanks, @felipebochehin87 - looks like something in my fix here: https://github.com/GoogleForCreators/web-stories-wp/pull/11075/files got overwritten.

**Comment by felipebochehin87** [comment]
@BrittanyIRL I am using PR #11217 and I still see the same problem :(

**Comment by BrittanyIRL** [comment]
ok, let's go again @felipebochehin87!

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11217.

1. Opened the editor
2. Added an image element
3. Added a border to the element
4. Clicked on the element and picked a color from Style menu - color is set
5. Clicked on the element and picked a color from floating menu - color is set

https://images.zenhubusercontent.com/235435637/4adcc410-2b46-47e1-a85d-eb72607cb244/11216.mp4
