### ISSUE TITLE
Cannot save story after removing background audio

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11229]
## Bug Description

When removing background audio from a page, `page.backgroundAudio` becomes `null`.

When generating the story markup upon saving, `backgroundAudio` is referenced a few times here:

https://github.com/GoogleForCreators/web-stories-wp/blob/bbcf177fb35dcc6fb6abd5612de2e97e470bb3ba/packages/output/src/page.js#L107-L112

This will cause `Cannot read properties of null` errors.

**Solution:** To fix this we should use optional chaining there.

⚠️ Need to add tests to prevent regressions.

❓  One might think that this default value would catch this:

https://github.com/GoogleForCreators/web-stories-wp/blob/bbcf177fb35dcc6fb6abd5612de2e97e470bb3ba/packages/output/src/page.js#L54-L55

No. Default values are only used if the value is `undefined`; not when it is `null`.

Let's remove the default value for `backgroundAudio` and `pageAttachment` to avoid this kind of confusion.

## Expected Behaviour

After removing background audio, saving a story should still work.

## Steps to Reproduce

1. Add background audio to page
2. Remove background audio again
3. Try to save story
4. See error message

## Screenshots

<img width="642" alt="Screenshot 2022-04-11 at 15 37 10" src="https://user-images.githubusercontent.com/841956/162777840-ee0884d5-5db7-495f-a3d7-275e70919b91.png">

## Additional Context

- Plugin Version: 1.19.0
- WordPress Version: 5.9
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
@timarney Perhaps you have time this week to tackle this one?

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11272.

1. Opened editor
2. Created a new story
3. Add audio file to the background
4. Saved Story - worked
5. Removed audio
6. Saved Story - worked
7. Tested preview on both cases - worked
8. Tested publish in both cases - worked
