### ISSUE TITLE
Text: word only highlighted to end of box row with double click in Firefox

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#11225]
## Bug Description

When double-clicking a word in a text box that carries over two rows, the word is only highlighted up to the end of the row and doesn't carry onto the next row where the word ends. 

This only happens in a Firefox browser. Tested in Chrome, Edge and Firefox with Chrome and Edge highlighting the entire word on both rows as expected and Firefox not behaving the same.

## Expected Behaviour

The expected behaviour here should be that of how it performs in both Chrome and Edge browsers where the entire word is highlighted on both rows. See example of this here:

![image](https://user-images.githubusercontent.com/91896826/162693605-99425ddf-a324-4060-9ef7-6e93bb555620.png)

## Steps to Reproduce

1. Open a Firefox browser.
2. From the editor, add a new text box to a story.
3. Input a word that carries over two lines within that text box.
4. Double-click on that word to highlight.

## Screenshots

This is how this behaves in a Firefox browser:

![image](https://user-images.githubusercontent.com/91896826/162694119-daf1e15a-5b54-40b8-a319-0075f3619e3a.png)

## Additional Context

**Firefox version:** 99.0 (64-bit)

**Comment by swissspidy** [comment]
Perhaps this is simply by design and just how Firefox works?

Double click selects the first line, triple click the whole text box.

cc  @barklund @merapi
