### ISSUE TITLE
Next and Previous icons not visible

### ISSUE THREAD

**Issue by rishnarang** [swissspidy/web-stories-wp#11224]
## Bug Description

Next, Previous icons are not loading with the Web Stories Wordpress plugin.

## Expected Behaviour

The icons should be visible 

## Steps to Reproduce

www.andreaabroad.com 
Scroll to the 'Web Stories' section

## Screenshots

<img width="1354" alt="Screen Shot 2022-04-09 at 10 00 57 AM" src="https://user-images.githubusercontent.com/82465478/162583954-000f0ca7-c41b-4e93-a839-e880dbc369d3.png">

<img width="1721" alt="Screen Shot 2022-04-09 at 10 00 29 AM" src="https://user-images.githubusercontent.com/82465478/162583958-f596dee6-43e5-4988-bc7b-97201ec5833c.png">

## Additional Context

- Plugin Version: 1.19.0
- WordPress Version: 5.9
- Operating System: MacOS
- Browser: Chrome

**Comment by bethanylang** [comment]
@rishnarang Thanks for getting in touch! This looks like a CSS issue that may be specific to your setup as opposed to a bug for all Web Stories plugin users. In order for us to troubleshoot, can you please open a topic on our [WordPress.org support forum](https://wordpress.org/support/plugin/web-stories/)? We can work with you there to try to identify the issue.

I'll mark this issue as closed, but please do open a new support topic and we'd be happy to help there. Thanks!

**Comment by swissspidy** [comment]
I can reproduce this. Thanks for letting us know!

We will get this fixed.
