### ISSUE TITLE
Errors when using the "Search Stories" filter

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#11259]
## Bug Description

As using the "Search Stories" field, the app presents a weird behavior: sometimes it loads the stories when the filter is clear, sometimes it doesn't. Sometimes the filter works (returns stories), sometimes it doesn't. Video attached.

## Expected Behaviour

"Search Stories" should retrieve stories based on the terms that have been entered. And I kindly suggest adding the same search as we have in Fonts and Author fields, %term%.

## Steps to Reproduce

1. Access the Dashboard
2. Enter any term in Search Stories field
3. Clear filter
4. Visit Templates screen
5. Enter any term in Search Templates field
6. Return to the Dashboard 
7. Enter any term in Search Stories field
8. Clear filter
9. Repeat these steps and note that sometimes the filter works, sometimes it doesn't

## Screenshots

https://user-images.githubusercontent.com/841956/163216971-695e0a70-2831-4900-9e11-309b8a62da0b.mp4

## Additional Context

- Plugin Version: 1.19.0?
- WordPress Version: ?
- Operating System: ?
- Browser: ?

**Comment by swissspidy** [comment]
I can reproduce this too. No need to visit the templates screen. Just perform 1-2 searches.

Looks like the issue here is that the URL the dashboard ends up fetching contains the query params `page=0&per_page=24`. But `page` must not be zero. Hence the 400 error.

So somewhere the page number erroneously gets set to zero.

cc @BrittanyIRL

**Comment by BrittanyIRL** [comment]
Looks like this could be a regression from a recent update here #11256 @BrookeGraham could you take a look?

**Comment by BrookeGraham** [comment]
I can take it. It wasn't a regression, but @felipebochehin87 found it while testing #11256

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11367.

1. Opened the Dashboard
2. Searched for a story that doesn't exist
3. Cleared filter - all stories displayed
4. Searched for an existing story - story displayed
