### ISSUE TITLE
Shopping: Limit number of products per page

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11254]
## Feature Description

* [**Figma**](https://www.figma.com/file/ZrO763yvMWJjYeAPsRnNfW/_Editor---Sprint-Feature-Level-Designs_2022?node-id=503%3A15921)

The exact solution is still TBD, but we want to limit the number of products per page in some way.

For example by displaying a snackbar message when the limit (currently 6?) is reached:

<img width="315" alt="Screenshot 2022-04-12 at 14 49 26" src="https://user-images.githubusercontent.com/841956/162966003-3f3cd1e3-1768-4874-b056-6c96a153c39a.png">

**Comment by swissspidy** [comment]
Related: #11521

The easiest solution might be to add a new checklist item for this

**Comment by spacedmonkey** [comment]
It is okay to reductor like was done in https://github.com/GoogleForCreators/web-stories-wp/issues/11521?

**Comment by swissspidy** [comment]
The first step would be to disable the Insertion button and display a tooltip saying why it's disabled.

**Comment by swissspidy** [comment]
Looks like this is going to be two fold:

1. Essentially do the same as #11616 — disable the button when there are already **6** products on the page
2. Same as #11577 — display snackbar message when there are already **6** products on the page

Given the precedence for this it should be relatively easy to implement.

**Comment by swissspidy** [comment]
This is a good opportunity to add Karma tests btw, especially since #11577 didn't include any.

**Comment by felipebochehin87** [comment]
Tested using PR #11727.

![products.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/4a92a801-44a7-49c2-9207-35d8c7aa3e47)
