### ISSUE TITLE
Shopping: Improve REST API error handling

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11268]
## Feature Description

This ticket is for addressing the existing TODO in the products controller to improve error handling; especially for GraphQL responses from Shopify.

This is needed so we can for example distinguish between auth errors and other ones.

**Comment by timarney** [comment]
Noting -- 

Noticed while I was testing another PR locally --- the product dropdown remains in a loading state when the Product query errors.


<img width="800" alt="Screen Shot 2022-04-22 at 6 16 35 AM" src="https://user-images.githubusercontent.com/62242/164688557-bfb7aa5f-5171-4fad-ac11-aae79b56abc9.png">

**Comment by timarney** [comment]
Looking at the remaining todo in Shopify_Query ...

https://github.com/GoogleForCreators/web-stories-wp/blob/main/includes/Shopping/Shopify_Query.php#L234

> The Storefront API can return a 200 OK response code in cases that would typically produce 4xx errors in REST.

Looks like if anything falls through to that point we can grab some more detail via 



error[n].extensions.code 

<img width="500" alt="Screen Shot 2022-05-25 at 6 31 58 AM" src="https://user-images.githubusercontent.com/62242/170245974-7d7f0b60-636d-4463-8e8e-a606fafb08a8.png">

See: https://shopify.dev/api/storefront#status_and_error_codes

<hr>

For user facing types of errors I thinking we can look for 

```
THROTTLED
ACCESS_DENIED
SHOP_INACTIVE
INTERNAL_SERVER_ERROR
```

Anything other possible errors your thinking should be handled at that point in the code.  You covered auth errors etc... in https://github.com/GoogleForCreators/web-stories-wp/pull/11519
