### ISSUE TITLE
Performance: Prevent dashboard `usePagePreviewSize` from doing multiple DOM queries

### ISSUE THREAD

**Issue by mohdsayed** [swissspidy/web-stories-wp#11277]
## Task Description
We are using `document.getElementById` to get the container element  (`#wpbody`) to calculate the page preview size. However since it is directly used in `useRef` it is called several times. Maybe we can refactor, to query DOM only once.

https://github.com/GoogleForCreators/web-stories-wp/blob/0ea06521d3bd41f136878e7b06fb73940913f804/packages/dashboard/src/utils/usePagePreviewSize.js#L106-L110

**Comment by littlemilkstudio** [comment]
These two useState calls right below it will probably be more expensive & get called every render too (cause a [forced reflow](https://gist.github.com/paulirish/5d52fb081b3570c81e3a)):

https://github.com/GoogleForCreators/web-stories-wp/blob/0ea06521d3bd41f136878e7b06fb73940913f804/packages/dashboard/src/utils/usePagePreviewSize.js#L113

https://github.com/GoogleForCreators/web-stories-wp/blob/0ea06521d3bd41f136878e7b06fb73940913f804/packages/dashboard/src/utils/usePagePreviewSize.js#L117

That being said, this is relatively static code (haven't been a lot of updates to the dashboard in the past year), so if there's no noticeable performance issues that this code is causing, might not be worth the lift

**Comment by swissspidy** [comment]
Related:

* #11276
* #11270

For making SSR work we would need to touch this code too.
