### ISSUE TITLE
Document the differences in E2E vs Karma tests

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11286]
## Feature Description

One outcome of the April 2022 retrospective held by the project team was that it became clear that there was still some confusion around the differences in the project's end to end (E2E) tests versus the Karma tests, and as such, we would like a document created that can help clarify the following:

1. Detail the overall difference in purpose between the two test types
2. Detail the difference in coverage (scope) between the two test types.

**Comment by BrittanyIRL** [comment]
Did a quick search before spending time writing my own definitions and what do ya know - https://kentcdodds.com/blog/static-vs-unit-vs-integration-vs-e2e-tests this is pretty much exactly what we do here.

**Comment by swissspidy** [comment]
Besides the differences of coverage and purposes of the different types of tests, another key distinction to keep in mind in our code base:

Code living in the "integration" packages (i.e. the WordPress-specific packages), such as the settings page, the WP media picker, status checks, font checks, etc. can only be tested with our e2e test setup, not karma
