### ISSUE TITLE
Update Quick Tips Read Start Guide link text

### ISSUE THREAD

**Issue by mxbclang** [swissspidy/web-stories-wp#11282]
## Feature Description

The "Read Start Guide" text in the Quick Tips modal currently links to https://wp.stories.google/docs/, which is our main documentation page. To be clearer, we should change the link text to "Read Documentation."

<img width="333" alt="image" src="https://user-images.githubusercontent.com/12189958/163801136-6ff008ca-c2ce-4b29-b5e1-4f7009663289.png">

cc @swissspidy

**Comment by swissspidy** [comment]
Or just link to https://wp.stories.google/docs/getting-started/?
