### ISSUE TITLE
Dashboard: Filter stories by taxonomy

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11287]
## Summary

(Updated based on discussion in comments below) 

Adds a new filter option to Dashboard to filter stories by taxonomy. 

Adds a new dropdown to filter dashboard stories based on _hierarchical_ taxonomy. Please see the 'All Stories' default WP view for what that means. The functionality here should be the same. It'll be a dropdown just like the Author one in this screenshot. 

Awaiting finalized UX.  From there issues should be created as necessary to scope the work properly.

<img width="1263" alt="Screen Shot 2022-04-20 at 11 42 53 AM" src="https://user-images.githubusercontent.com/10720454/164309270-2b2497c3-7f97-4af8-b860-989c8222ce37.png">

**Comment by BrittanyIRL** [comment]
@swissspidy I'd love to get you to weigh on on this. Discussed with @agingoldseco as far as UX goes it makes sense for taxonomy to become part of Story search on the dashboard - so if I have a category of "zucchini" attached to my story and search "zucchini" in the dashboard, that story would show up. This makes me think that the actual work on this is related to PHP, grabbing the taxonomy and adding it to get looked at when fetching stories based on a search query. 

If that's the case this will need to be infra since you know we're no good at php. Otherwise, please shed some light on what you were intending.

**Comment by swissspidy** [comment]
Oh interesting, I never thought about somehow integrating this with the search form. That seems quite unexpected and from a technical perspective also super complex and not feasible at all in WordPress.

What I had in mind here was adding dropdowns to filter by categories\*, just like filtering by authors is possible this way. Like you can do on the "All Stories" page:

<img width="736" alt="Screenshot 2022-04-20 at 11 39 10" src="https://user-images.githubusercontent.com/841956/164199686-53b231cd-cccf-44be-8d67-3f97f39347f1.png">

And if there are absolutely no stories with any categories attached to them, we would simply not show it:

<img width="610" alt="Screenshot 2022-04-20 at 11 41 12" src="https://user-images.githubusercontent.com/841956/164200016-4e5bb487-de32-4cc9-9cd2-036dd10fb85b.png">


/* Interestingly, only hierarchical taxonomies (i.e. categories, but not tags) have a dropdown on the "All Posts" / "All Stories" page. So maybe we just do that as well.

**Comment by BrittanyIRL** [comment]
Ah, thank you! 

Felt like a kinda murky query update! I will pass this over to Amy to figure out what the best way would be to add this to the Dashboard is. I'm going to pull it from the release though because design is necessary for this. 

Could be as simple as a dropdown but I would like to run it past Amy first. 
<img width="1263" alt="Screen Shot 2022-04-20 at 11 42 53 AM" src="https://user-images.githubusercontent.com/10720454/164300942-76283423-22ec-4951-87c7-733ed27469cb.png">

**Comment by agingoldseco** [comment]
Seems like we'd be great with just adding that taxonomies dropdown in the same style as the "Author" dropdown. To be clear, users would be able to search the taxonomy options the same way as in the Author one, correct?

**Comment by swissspidy** [comment]
I think so, yes. That should be possible.

**Comment by sblinde** [comment]
This epic has been completed and can be closed.
