### ISSUE TITLE
Floating Menu: Tooltip Inconsistencies 

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11304]
## Bug Description

Tooltips on the floating menu are inconsistent. Some of them have tails and others don't. We should pick either tails or no tails and make sure that the menus are uniform.  (We pick tails, per design sync 4/19/22 with @agingoldseco )

## Expected Behaviour

Consistent tooltip tails on floating menus 

## Screenshots

![inconsistent tooltips](https://user-images.githubusercontent.com/10720454/163892693-2c632ab2-7ee8-431c-a45a-2258c69803a4.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11543.

1. Added elements to the canvas
2. Clicked on the elements
3. Hovered over the quick menu actions - tooltips and their tails displayed
4. Hover over the floating menu actions - tooltips and their tails displayed

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11543.

1. Added elements to the canvas
2. Clicked on the elements
3. Hovered over the quick menu actions - tooltips and their tails displayed
4. Hover over the floating menu actions - tooltips and their tails displayed
