### ISSUE TITLE
Insert Media Popup not getting correct `isRTL` placement

### ISSUE THREAD

**Issue by BrookeGraham** [swissspidy/web-stories-wp#11303]
## Bug Description

On the Insert Media Side Panel,  you click the + icon on an image and it opens a `Popup` to "insert the image" or add it as the background. When in RTL mode, the Popup is cutoff. Probably cause we are not sending `isRTL` to the Popup and thus not changing the placement. 

## Expected Behaviour

Popups shouldn't get cutoff, or layered underneath the admin sidebar. 
## Steps to Reproduce
Open Editor
Switch to RTL
Open Media panel
Click on the + icon that is shown over any image

## Screenshots
![Screen Shot 2022-04-15 at 3 37 45 PM](https://user-images.githubusercontent.com/1820266/163886755-3d33c27e-1f69-493f-8df0-f59855ae278e.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrookeGraham** [comment]
This will get fixed with #11325

**Comment by BrookeGraham** [comment]
Hi @felipebochehin87 you can test this with #11325

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #11325.

1. Tested RTL and LTR on Safari
2. Tested RTL and LTR on Firefox
3. Tested RTL and LTR on Chrome
