### ISSUE TITLE
Style tab design is incorrect

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11317]
## Bug Description

Originally reported by @BrookeGraham 

Not sure if this was part of the design, but the separating bar between the new section and where the panels begin, the horizontal line doesn’t extend fully.

<img width="370" alt="image1" src="https://user-images.githubusercontent.com/58738530/164282756-15273795-07fc-4d98-b3c0-7ee7b881e2e3.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
@sblinde the editor is crashing when I select PR #11781 to test this fix. Please see video and error attached.


[https://app.zenhub.com/files/235435637/0176058a-a54e-4968-9597-690a60ef460a/download](https://app.zenhub.com/files/235435637/0176058a-a54e-4968-9597-690a60ef460a/download)

https://images.zenhubusercontent.com/235435637/26dd4ee2-93b6-4511-9ed8-58c26eb26c32/2022_06_26_19_15_16.mp4

**Comment by felipebochehin87** [comment]
Please, is this something wrong in my end?

Ty!!

**Comment by sblinde** [comment]
@felipebochehin87 I see what you mean, I'll take a look. Thanks for the heads up!

**Comment by sblinde** [comment]
@felipebochehin87 I believe it should be resolved with the latest build!

**Comment by felipebochehin87** [comment]
Thanks @sblinde . Looks good in the PR.

**Comment by sblinde** [comment]
@felipebochehin87 Thank you!!
