### ISSUE TITLE
Style tab Corners tool doesn't fill panel correctly

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11318]
## Bug Description

Originally reported by @agingoldseco 
Small thing, but this Corners field doesn’t extend all the way to the right 
![Screen Shot 2022-04-20 at 1 44 09 PM](https://user-images.githubusercontent.com/58738530/164291296-f0087fa9-d90e-4641-83a9-326db0f4d1f9.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
![11801.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/2b41ddd8-d56d-4c1b-b260-8f4f57056db5)
