### ISSUE TITLE
Floating Menu: Color Opacity Focus 

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11312]
## Bug Description

We had to get a little creative to make all of the floating menu items focusable. The result was a button to facilitate moving focus and not getting stuck in freeform inputs. The color opacity input proves a unique challenge because of its design. 

These are the 2 options initially found in #11273 
| | | 
| --- | --- | 
| Overriding width and wrapping around dash and input |  ![image](https://user-images.githubusercontent.com/10720454/164112442-6318773a-9a7a-4dec-9e83-36a43cebe22a.png) | 
| Focus trap button wrapping only `OpacityInput` | <img width="395" alt="Screen Shot 2022-04-19 at 3 27 42 PM" src="https://user-images.githubusercontent.com/10720454/164112400-012296b5-68fa-40a0-9abb-88539f651fbb.png"> | 

We want this though, it's just really hard to get the positioning and sizing right? I think fixing this is going to need to refactor the whole input. Need to make sure that any solution doesn't cause regression on the other use cases of color opacity.  
![image](https://user-images.githubusercontent.com/10720454/164112480-2d5ef411-fd4b-473a-a7f0-eaec8ab5b1c2.png)

Relevant code is in `packages/story-editor/src/components/form/color/activeOpacity.js`

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested on Safari, Chrome and Firefox. Border is appropriately sized.

**Comment by sblinde** [comment]
Yay! Thanks for testing!
