### ISSUE TITLE
Active First Page: Disable Animation Toggle

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11322]
## Feature Description

AMP doesn't allow animation on the first page of a Story. Currently, users can add animations to the first page of a Story in the editor. We want to acknowledge the animations so we're not stripping them from the first page (page order can change). It would be helpful for a user to know why the animation isn't playing and that it's not a bug (see https://github.com/GoogleForCreators/web-stories-wp/issues/9987).

Inline with #11321 which disables the ability to add/update animation to a Story's first page, we want to also disable the playback button (and keyboard shortcut) for the first page canvas view. 

<img width="571" alt="Screen Shot 2022-04-20 at 11 33 13 AM" src="https://user-images.githubusercontent.com/10720454/164299095-d8251f2e-ccf5-4496-b36d-6aaa9543858b.png">

## Alternatives Considered

Instead of disabling this button, it could be hidden. Seems more consistent to disable it. 

## Additional Context

Play/Stop button only shows up if there's animation present on the page. We want to know if we're on the first page, and if we are and there's an animation then just disable that button as well as the shortcut. This will largely be the same logic as used in #11321 for disabling. 

AnimationToggle button lives here: `packages/story-editor/src/components/canvas/pagemenu/animationToggle.js`
Adding a karma test here: `packages/story-editor/src/components/canvas/karma` would be good form. 

## Acceptance Criteria 
- Animation Toggle button is disabled on first page if an animation is present.

**Comment by felipebochehin87** [comment]
Animations are disabled on the first page.

**Comment by felipebochehin87** [comment]
Animations are disabled on the first page.
