### ISSUE TITLE
Active First Page: Disable Animation Inputs

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11321]
## Feature Description

AMP doesn't allow animation on the first page of a Story. Currently, users can add animations to the first page of a Story in the editor. We want to acknowledge the animations so we're not stripping them from the first page (page order can change). It would be helpful for a user to know why the animation isn't playing and that it's not a bug (see https://github.com/GoogleForCreators/web-stories-wp/issues/9987).

This ticket is to disable the animation input(s) when the first page is active. We do NOT want to strip the animations from the first page, so if there is already an animation present on a page and the order changes, preserve the animation and just disable all of the inputs. 
If it is a fresh Story or the page has no animations on the first page then the dropdown will be disabled. 

To help users understand why this is disabled, we will reuse the  design panel `Warning` (`/packages/story-editor/src/components/panels/design/warning/warning.js`) to let the users know why this is disabled. Something like the below (which @BrittanyIRL did in photoshop so the dimensions are not perfect). 

Please work with @swissspidy and @aaskedall for better copy.

<img width="367" alt="Screen Shot 2022-04-19 at 2 23 56 PM" src="https://user-images.githubusercontent.com/10720454/164297968-4967883a-2aac-446b-aa3f-64b54e9a11dc.png">
<img width="365" alt="Screen Shot 2022-04-19 at 2 23 52 PM" src="https://user-images.githubusercontent.com/10720454/164297982-bfb0eb33-95a9-451b-9c2d-2e9742255f61.png">

## Additional Context

In `packages/story-editor/src/components/panels/design/animation` check to see if the current page (`useStory` hook) is page 1, if it is then disable the inputs for the animation and render warning. 

## Acceptance Criteria 
- If on page 1 of a Story, animations are disabled. 
- If I add animation to page 2 of a story and make that story page 1, the animation is present and all inputs are disabled. 
- If I am on page 1 looking at animation in side panel then I get a helpful warning message about why animations are disabled. 
- New Karma test in `packages/story-editor/src/components/panels/design/animation/karma` asserting the above.

**Comment by felipebochehin87** [comment]
Animations are disabled on the first page.
