### ISSUE TITLE
Background audio: Stop playback of audio on removal

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11337]
## Bug Description

If you are playing background audio, if you click the remove button on the audio, the audio keeps playing for a 1 second. 

## Expected Behaviour

On removal of background audio, the audio should automatically stop. 

## Steps to Reproduce

1. Create a new story. 
2. Add background audio to a page. 
3. Start playing background audio. 
4. Remove background audio. 
5. Hear audio still playing. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by timarney** [comment]
a) I don't seem to get the delay on my laptop.

That said...

Was thinking of passing an optional ref to the Audio Player to allow player.pause() to be called from `BackgroundAudioPanelContent` ... if the ref isn't passed Audio player can create it's own as it does now.  

Another approach might be to clear the `src` (local state) on remove but that would still require state and renders to happen (which still might result in a delay).

**Comment by felipebochehin87** [comment]
Once removed, audio stops playing immediately.
