### ISSUE TITLE
Title positioning in editor adversely impacted by metaboxes

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11338]
## Bug Description

When a third party plugin leveraging metaboxes is used within the editor, and the metaboxes are set at a min height of over 50% of the screen, this impacts the position of the story title in the editor

I used this plugin to test this (h/t to @landybryo for finding and creating this test plugin) 

[https://app.zenhub.com/files/235435637/90fd3b9b-bfda-4202-8e74-c1d7884d99d5/download](https://app.zenhub.com/files/235435637/90fd3b9b-bfda-4202-8e74-c1d7884d99d5/download)

![Screen Shot 2022-04-22 at 10.20.34 AM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/7803f793-40d0-4d9d-a8d6-00bd4d43cf5a)
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
This is best handled by Prometheus pod as this is an issue/regression with the CSS grid layout in the editor, not the behavior of meta boxes.
