### ISSUE TITLE
Page count text is displayed out of order when displayed RTL

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#11342]
## Bug Description

Page count text is displayed out of order when displayed RTL (it is displayed "of 14 pages 5" instead of displaying "5 of 14 pages").

## Expected Behaviour

The text should be displayed the same way on both RTL and LTR ("5 of 14 pages").

## Steps to Reproduce

1. Open the editor
2. Add a few pages (or only 1, it is enough too)
3. Switch to RTL
4. Check the page count text under the canvas

## Screenshots

![RTL of 1 page 1.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/29aa4558-0a4d-4919-8afd-a21e4664469f)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser: Safari, Firefox, Chrome

**Comment by swissspidy** [comment]
This is not actually an issue, just misleading because it's testing RTL layout with a LTR language.
