### ISSUE TITLE
Tracking: Add hardening for user role retrieval

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11352]
## Feature Description

According to [this report](https://wordpress.org/support/topic/php-warning-tracking-php-175/), there can be a PHP warning triggered here:

https://github.com/GoogleForCreators/web-stories-wp/blob/cefc2736398ab391e3fbd0a437b675b83bfa3039/includes/Tracking.php#L175

```
PHP Warning: Undefined array key 0 in /var/web/site/public_html/wp-content/plugins/web-stories/includes/Tracking.php on line 175
```

It's not clear to me how that can happen, but I suppose in theory a user can have zero roles, or the array can have non-numeric indices.

For extra hardening we can

* Wrap `wp_get_current_user()->roles` in `array_values()`
* Use an `isset()` check when trying to retrieve the first role

**Comment by madanpraba** [comment]
How about checking user logged in status (is_user_logged_in())?

**Comment by swissspidy** [comment]
This is irrelevant, this code only runs in the admin where all users are logged in.
