### ISSUE TITLE
Saving story output unexpectedly modifies story data

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11363]
## Bug Description

I just noticed this while debugging something related to a [support topic](https://wordpress.org/support/topic/h1-tags-not-working-showing/):

When you save a story, it unexpectedly modifies element objects since they are passed by reference.

`OutputPage` directly modifies `page.elements` here

https://github.com/GoogleForCreators/web-stories-wp/blob/6d32ea3cd648abcc262aa1ce26b6f360575bec3b/packages/output/src/page.js#L80-L94

Because of the way `tagName = 'auto'` is retrieved from `element` (which in theory should never exist), this also has the unfortunate side effect of "hardcoding" the tag name in story data. So if an element is saved as an h1 once, it can never be saved as an h2 or so. It will always stay an h1.

This is a simple possible solution to fix this `OutputPage`:

```js
const regularElements = otherElements.map((element) => {
  // Avoid edits to the original element object.
  const newElement = { ...element };
  const { id: elementId, type } = newElement;

  if ('text' === type) {
    newElement.tagName = tagNamesMap.get(elementId);
  }

  // Remove invalid links.
  // TODO: this should come from the pre-publish checklist in the future.
  if (pageAttachment?.url && isElementBelowLimit(element)) {
    delete newElement.link;
  }

  return newElement;
});
```

**Alternatives considered**

* `getStoryPropsToSave` in `packages/output` (or `useAutoSave` and `useSaveStory` in `packages/story-editor`) could use `clone-deep` before passing on the `story` and `pages` data.
* Maybe something else?

## Expected Behaviour

Saving a story should not modify story data, ever.

We should fix this and add some robust JS unit tests (in the output package) and Karma tests to prevent regressions.

We should also add a **data migration** to remove excess `tagName` properties from element objects.

## Steps to Reproduce

There are two easy ways to reproduce this:

**Headings**

1. Open the story dev tools
2. Add a new "Title 1" element
3. See in the story dev tools that it was added
4. Save the story
5. In the dev tools, see that the element now suddenly has a `"tagName": "h1"` property
6. Decrease font size of the element to something super small
7. Preview the story and see that it still is a h1, even if it should not be.

**Links**

1. Add a page attachment
8. Add a new element
9. Add a link to the element
10. Move the element to the lower part of the page (so it triggers a page attachment warning)
11. Save story
12. See that the link was irrevocably removed from the element

## Additional Context

- Plugin Version: 1.20.0-alpha
- WordPress Version: 5.9
- Operating System: macOS
- Browser: Chrome 100

**Comment by felipebochehin87** [comment]
1. Added elements
2. Resized elements
3. Removed elements
4. Used color pickers
5. Added audio and captions
6. Added and removed animations
7. Changed formatting, styling, borders, font style, size, etc...
8. Saved
9. Made changes
10. Saved again
11. Previewed
12. Made changes and saved
13. Duplicated and removed pages
14. Used floating menu
15. Used quick action icons (the ones at the right side of the editor: play, duplicate page, delete page, add animation, etc...)
