### ISSUE TITLE
E2E Tests: Flakey Dashboard CRUD Tests

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11362]
## Task Description

Example run:

* https://github.com/GoogleForCreators/web-stories-wp/runs/6172675191?check_suite_focus=true#step:8:35

```
  ● Stories Dashboard › should delete story

    TimeoutError: Element h3 (text: "Test Story") found

      waiting for function failed: timeout 1000ms exceeded
```

No surprise that these are flakey, as they use some seemingly arbitrary timeouts before assertions:

https://github.com/GoogleForCreators/web-stories-wp/blob/09299885d07a6c813986949219e4ee1ca04c42e7/packages/e2e-tests/src/specs/dashboard/myStories.js#L35-L50

It would be better to wait for successful API responses using `page.waitForResponse()` for example

Tip: For local debugging, using `page.screenshot()` is useful.

**Comment by sblinde** [comment]
Deprioritizing for now given reported bug.
