### ISSUE TITLE
Centered story not aligned to the center

### ISSUE THREAD

**Issue by fellyph** [swissspidy/web-stories-wp#11372]
## Bug Description

With the Twenty Twenty one theme, when I set the web story at the center of my post, the change is applied to the Editor but not on the front-end of my Application.

**Editor**
![Screen Shot 2022-04-27 at 12 07 36](https://user-images.githubusercontent.com/330792/165518984-27dde530-1d95-4f9a-a4c7-bdd1d29e2cef.png)

**Front-end**
![Screen Shot 2022-04-27 at 12 08 07](https://user-images.githubusercontent.com/330792/165519074-8d1f091e-a9ad-43e3-ab95-e152563f8c88.png)

## Expected Behaviour

Web story should be centered when it is defined by the editor 

## Steps to Reproduce

1. Select a unique stories block, at the post editor
2. Set the alignment to the center 
3. Save and check the preview of the post

## Additional Context

- Plugin Version: 1.19.0
- WordPress Version: 5.9.3
- Operating System: MacOS
- Browser: Chrome 100

**Comment by swissspidy** [comment]
Which theme are you using?

Do you have an URL of a page where this happens so that we can take a look?

Related: #6987

**Comment by fellyph** [comment]
@swissspidy I'm using twenty twenty on theme and you can check this URL: https://blog.fellyph.com.br/wordpress-2/dicas-de-canais-do-youtube-sobre-wordpress/

**Comment by swissspidy** [comment]
Thanks!

We'll look into it.

Meanwhile adding the following custom CSS in the customizer should fix this:

```css
.web-stories-embed.aligncenter .wp-block-embed__wrapper { text-align: center; }
```

**Comment by felipebochehin87** [comment]
Looks good to me.
