### ISSUE TITLE
Quick actions: Reset Element for image borders broken

### ISSUE THREAD

**Issue by BrookeGraham** [swissspidy/web-stories-wp#11379]
## Bug Description

When an image has borders, if you try to reset the element using quick actions the app blows up. 

## Expected Behaviour

App shouldn't explode, and borders should be removed. 

## Steps to Reproduce

Add an image and put some borders on it. 
Using the quicks actions, reset the element. 
💥
## Screenshots
![reset elements.gif](https://images.zenhubusercontent.com/61252a26f86e89526edc42b7/b789a584-be4b-42d3-b9c1-3c0e7be3ebf2)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #11404.

1. Opened editor
2. Added elements
3. Added border to the elements
4. Reset

Tested on Safari, Firefox and Chrome.
