### ISSUE TITLE
Firefox: Link icon tooltip is hidden by the side menu 

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#11375]
## Bug Description
The WordPress side menu hides the link icon tooltip after uploading an icon image. 

Note this issue is similar to #11346 . Please let me know if this deems its own ticket or should be closed as duplicate.

## Expected Behaviour
Tooltip to display within the editor frame.

## Steps to Reproduce
1. Create story > Add link to element
2. Scroll to link icon > Open media picker > add image
3.  Note tooltip is hidden

## Screenshots
<img width="638" alt="Screen Shot 2022-04-27 at 1 45 44 PM" src="https://user-images.githubusercontent.com/66372350/165588390-d569f872-5352-4f9b-817f-a85605628d54.png">

## Additional Context

Reported on WordPress forum: https://wordpress.org/support/topic/bug-in-link-icon-popup-position-on-editor/

- Plugin Version: 1.20.0
- WordPress Version:
- Operating System: macOS
- Browser: Firefox

**Comment by sblinde** [comment]
Of note: This can be replicated w/ Chrome on macOS, when you click on the Edit icon a second time after the initial click.

**Comment by felipebochehin87** [comment]
This one looks good on Firefox.

**Comment by felipebochehin87** [comment]
This one was moved back along with 11346. However, no change is needed for this one, it's working.

**Comment by felipebochehin87** [comment]
All set!
