### ISSUE TITLE
Editor: Embed not working for scheduled story

### ISSUE THREAD

**Issue by fellyph** [swissspidy/web-stories-wp#11371]
## Feature Description

When I create a post from a scheduled web story the preview shows my home page at the editor because the web story is not published yet. I know that is not a big deal:
 
![Screen Shot 2022-04-27 at 11 55 51](https://user-images.githubusercontent.com/330792/165504864-07c98ea9-7fc5-4e30-bb6a-1e16fa80b59c.png)

## Alternatives Considered

If the Web Story is not posted yet, display the Web Story, cover image as a placeholder

**Comment by swissspidy** [comment]
The screenshot is from your archive page I presume?

**Comment by swissspidy** [comment]
Thanks for reporting this!

I was now able to reproduce the issue and we'll look into fixing this.

Related: #11281 

-----

Removing the `esc_url()` here fixes this bug:

https://github.com/GoogleForCreators/web-stories-wp/blob/01eda997cd5b8dcaca43fb1dda1a5ec5c389cfa1/includes/Admin/Admin.php#L168

We should remove it and add a comment with an explanation why. Can add a PHP integration test for the expected format too (an e2e test seems a bit overkill)

**Comment by timarney** [comment]
> I was now able to reproduce the issue and we'll look into fixing this.

@swissspidy 

Steps to reproduce 

- Create a story 
- Set a poster image
- Schedule for a future date ... 
- Embed from post using the dialog that pops up?
--  without `the fix` shows as 404? 

I tried via story block but the list shows as empty

<img width="411" alt="Screen Shot 2022-05-11 at 6 56 26 AM" src="https://user-images.githubusercontent.com/62242/167833961-300e18e6-91f8-4dca-b30e-5b73227dc68e.png">

<img width="500" alt="Screen Shot 2022-05-11 at 6 55 25 AM" src="https://user-images.githubusercontent.com/62242/167834027-68f42085-2201-4826-b535-fd29833bf323.png">

**Comment by swissspidy** [comment]
Yes this happens when adding a single story embed via the dialog that appears after scheduling a story.
Your second screenshot is for the selected stories block, which is something else.

**Comment by felipebochehin87** [comment]
Followed steps below
1. Created a story
2. Scheduled for a future date
3. Embedded from post using the dialog that pops up


Story shows as the embed - no error.
