### ISSUE TITLE
Adding web story description at the Web Story archive page

### ISSUE THREAD

**Issue by fellyph** [swissspidy/web-stories-wp#11370]
## Feature Description

On the archive page for web stories, is just listened to the feature image and the story, is it possible to add the description to add more context to the story:

![Screen Shot 2022-04-27 at 11 56 56](https://user-images.githubusercontent.com/330792/165504116-629c91d7-16da-4bc0-a5c0-1ff0cc880f5f.png)

## Alternatives Considered

Add the story description after the feature image:

![Screen Shot 2022-04-27 at 11 56 56](https://user-images.githubusercontent.com/330792/165504339-07f8a16a-4fd3-46b1-b288-d4e71149890b.png)

**Comment by swissspidy** [comment]
The default archive page is coming from your active theme and is not controlled by the Web Stories plugin. You can modify the archive page template for example by creating a child theme and modifying the PHP template accordingly. Perhaps your theme even provides an option for that in WordPress admin, so probably best to consult the documentation.

On the Web Stories plugin's settings page you can also choose to use a custom page as the archive page. If you do that, you can edit a custom page in Gutenberg and have complete control over the look & feel using all the available blocks on your site.

**Comment by fellyph** [comment]
@swissspidy I was thinking that I will add on my side, Thank!
