### ISSUE TITLE
Shopping: Detect WooCommerce status

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11383]
## Feature Description

Add a check to see if the woocommerce plugin is installed. If not installed when show an error / warning message to user in the shopping settings in the dashboard. We will also need to check to see if the plugin is activated ( and setup correctly ). 

At the same time, we may want to define a minimum version that we support and show a message to user to upgrade. 

There is also code to see if woo is installed as pass this to config. 

https://github.com/GoogleForCreators/web-stories-wp/blob/782fd71d2f74752a62ea69fe1173f530b8f85664/includes/Tracking.php#L180-L182

**Comment by swissspidy** [comment]
This is indeed a good opportunity to display messages similar to what we do for Site Kit, with a new `Google\Web_Stories\Integrations\WooCommerce` class with a public `get_plugin_status()` method that returns information about the plugin status (`installed` / `active` / `link`).

Then we can display different messages on the Settings page depending on the status:

Current text for now:

**Not installed:**

```
Install <a>WooCommerce</a> to easily add shoppable products to Web Stories.
```

**Not active:**

```
Activate <a>WooCommerce</a> to easily add shoppable products to Web Stories.
```

**Active:**

```
Manage products in <a>WooCommerce</a> to make them available in Web Stories.
```

To detect whether WooCommerce is installed: `\array_key_exists( 'woocommerce/woocommerce.php', get_plugins() )`

To detect whether it's active: either `class_exists( 'woocommerce' )` or —probably better— check `\defined( 'WOOCOMMERCE_VERSION' )`

Link:

* If WooCommerce is not installed: `__( 'https://wordpress.org/plugins/woocommerce/', 'web-stories' )`
	* If user can install plugins: Link to `plugin-install.php` (like we do in the Site Kit class)
* Installed but not active:
	* If user can activate the plugin: Link to `plugins.php` (like we do in the Site Kit class)
* Active:
	* If `current_user_can( 'manage_woocommerce' )`: Link to `admin.php?page=wc-admin`
