### ISSUE TITLE
Desktop & Mobile Issue

### ISSUE THREAD

**Issue by DanielCryptoK** [swissspidy/web-stories-wp#11388]
Hi,

I have been trying for many days to get the web stories to work on any of the google tests such as AMP Test, URL Inspection Test and Rich Results Test. Can you tell me why the rich results test works when set to desktop but fails when set to mobile?

Also why do all my posts and pages work in the tests but the web stories dont? Is there a different type of bot that crawls the web stories compared with the posts and pages? Is there a way to test what is blocking that bot from being able to connect to the web stories in the google tests?

Here is a page example and I have cloudflare turned off at the moment.

https://nonfungibleownership.com/web-stories/megacryptopolis-mega-review/

I have just switched cloudflare off for the site as everyone seemed to think it was related but I still the tests dont work.

I have updated to the latest version of web stories.

I need to hire a developer to fix this, what skills and what programs will they need to be an expert in to be able to identify and fix this as the Google community is also stuck. See support here https://support.google.com/webmasters/thread/161366534?hl=en#

I hope your allowed to post links, if not I apologize.

Thanks

Daniel

**Comment by bethanylang** [comment]
Hi @DanielCryptoK,

All support for the Web Stories plugin is provided in our [WordPress.org support forum](https://wordpress.org/support/plugin/web-stories/), and we do not provide support in our GitHub repository.

Note that the AMP Test tool is not managed by the Web Stories team and we're not able to troubleshoot issues relating to it. 

I'll mark this issue as closed. Sorry we can't be of further assistance here.
