### ISSUE TITLE
Add "Copy story data" button to error boundary screen

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#11394]
## Feature Description

It would be useful to add an option for web stories users to export a story as a JSON file to provide to support for debugging. 

This would simply be an export function and would not allow users to export/import story data. This would allow us in the support forums to request this data from the user to help with our troubleshooting of their story issues.

The feature would work much like other plugins with an export settings feature.  

## Alternatives Considered

1. This could be included in the Site Health Information rather than adding an option for the user to download a JSON file. 

2. An alternative to this would be to continue using the process we have in place which is less efficient but does work. This improvement would eliminate many steps in the process making everything much more efficient. 

## Additional Context

N/A

**Comment by swissspidy** [comment]
Related: #4357

> The feature would work much like other plugins with an export settings feature.
> This could be included in the Site Health Information rather than adding an option for the user to download a JSON file.

Just noting that the difference there is that these are for site-wide debugging information, not for exporting a single piece of content.

**Comment by swissspidy** [comment]
I was just thinking, would a small Chrome extension perhaps help with this too? Then the user can share their story URL, you open the story and the Chrome extension would allow you to download the story data for it.

**Comment by swissspidy** [comment]
This functionality is especially useful when there's an editor crash, so we could add this as a button below the error crash message.
