### ISSUE TITLE
Hotlinked image not proxied on canvas

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11395]
## Bug Description

The change in #10206 caused image URLs on the _canvas_ not to be proxied anymore, even though the image was correctly proxied in other areas (e.g. the layers panel)

## Expected Behaviour

Image hotlinking should work fine, including actually using the proxied URL everywhere

## Steps to Reproduce

1. Hotlink an image that needs a CORS proxy (for example https://wp.stories.google/e2e-tests/example.jpg)
2. See that insertion etc. works successfully, but that the image is not displayed correctly on the canvas

## Screenshots

![Screenshot 2022-04-29 at 15 28 44](https://user-images.githubusercontent.com/841956/165953840-c5d56696-d1b5-486a-9c74-d541ced622a5.png)

## Additional Context

- Plugin Version: 1.20.0
- WordPress Version: 5.9
- Operating System: macOS
- Browser: Chrome

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #11396.

1. Started a new Story
2. Added image by hotlink - image is displayed in the canvas (https://wp.stories.google/e2e-tests/example.jpg)
3. Previewed and published story - image is displayed

**Comment by akashgelot44** [comment]
I am still facing this issue

Try this image: https://robbreport.com/wp-content/uploads/2021/05/Bitcoin1.jpg?w=1000

**Comment by swissspidy** [comment]
@akashgelot44 You will need to wait until our next release to get this bugfix.
