### ISSUE TITLE
Conflict With Cloudflare

### ISSUE THREAD

**Issue by DanielCryptoK** [swissspidy/web-stories-wp#11393]
Hi Just to let you know that there is a conflict between web stories and cloudflare, I have reported it to them so hopefully sorted. This support ticket explains everything:

https://support.google.com/webmasters/thread/161366534?hl=en#

**Comment by swissspidy** [comment]
Thanks for sharing. Sounds like the conclusion is that something on the CF side is blocking the AMP Test tool.

closing since this is not a bug in Web Stories.
