### ISSUE TITLE
Google Font "Noto Sans Symbols 2" fails to generate any symbols

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11397]
## Bug Description

User is trying to use some of the glyphs/symbols from the noted font, however selecting this and typing only outputs letters

https://fonts.google.com/noto/specimen/Noto+Sans+Symbols+2

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
i think this is kinda expected. This font does not magically turn your letters into symbols.

Check the demo on the https://fonts.google.com/noto/specimen/Noto+Sans+Symbols+2 page you linked to.

![Screenshot 2022-04-29 at 15 56 47](https://user-images.githubusercontent.com/841956/165958840-c3ef9105-b37c-461f-87ce-d36bfc55ab59.png)
