### ISSUE TITLE
Media: Only optimize videos not matching criteria

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11405]
## Feature Description

Since the introduction of FFmpeg-powered video optimization we have this long-standing todo to only optimize videos meeting certain criteria:

https://github.com/GoogleForCreators/web-stories-wp/blob/b8d9c09d50d2ba30b169097a6576b5c656fda25f/packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js#L504-L507

This way we can avoid needlessly optimizing videos which are already fine in file size / format / dimensions.

So far I always thought there is no good library to use for this, but the other day I stumbled upon https://mediainfo.js.org/#mediainfojs which might be a very good fit. It supports lots of formats and provides all the required information about formats, codecs, file sizes, etc. We can also use it to improve detection of muted videos.

Things to look for:

* Dimensions exceeding 720x1280
* Not MP4 with H.264 codec or not WEBM with VP9 codec
* mp4 but not using h624 codec
* File size over recommended 4MB

If a video meets the criteria, we can skip transcoding and mark it as `isOptimized` directly.

**Comment by felipebochehin87** [comment]
Looks good. Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #11454.
