### ISSUE TITLE
Carousel: change circle border depending on view status

### ISSUE THREAD

**Issue by mxbclang** [swissspidy/web-stories-wp#11413]
## Feature Description

[A user in the forum requested](https://wordpress.org/support/topic/some-requests-ideas-and-errors/) changing the circle border color on Circle Carousel block stories based upon if the user has already viewed them or not, similar to Instagram's story behavior.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/12189958/166293765-49771349-fa33-473f-adbb-5a09da339943.png">

Their specific request: "Maybe using browser cache, the stripe around unseen stories can be colored. Seen and invisible cookies…"

**Comment by halilesen** [comment]
or

![or](https://user-images.githubusercontent.com/73847687/167623598-6bb09c31-a5c9-4326-986f-b683b08ba38f.jpg)


This attracts the attention of users. They notice when a story is updated or a new one is added.
