### ISSUE TITLE
Add ability to add site icon, name, and link to top left of story

### ISSUE THREAD

**Issue by mxbclang** [swissspidy/web-stories-wp#11415]
## Feature Description

<a href="https://wordpress.org/support/topic/some-requests-ideas-and-errors/">A user in the forums requested</a> the ability to add the site title, logo, and a link back to the main site on the top left of a story.

Their specific request: "It would be nice to have a link with the site icon and name at the top left of the story to go to the main page when the story is opened only as a connection other the site or widget."

**Comment by swissspidy** [comment]
Not sure if that means they only want to add this if the story is opened directly and not in a lightbox.

If that's what they mean, then this is basically the existing "exit button" feature request.

Generally speaking adding a logo with a link on every page can be achieved pretty easily using an image element and page templates.

**Comment by halilesen** [comment]
Hi! I come.

First of all, I would like to show an example of the part you quoted from my message. For example, what should you do to exit the story [here](https://empireweekly.com/web-stories/best-fitness-exercises-for-weight-loss)? What you will do is just close the tab.

If you have a site with many authors it would be great to have the authors avatar and name in the top left. I think this should be left to choice. But it can help writers better interact and engage. Eg:

![misal](https://user-images.githubusercontent.com/73847687/167621771-25e931a0-c87f-4e1d-b28d-4cadec1c7594.jpg)

Accordingly, the exit icon can be moved to the right. Volume up is also his left. Or as appropriate.

**Comment by swissspidy** [comment]
While we appreciate your suggestion, an exit link in top corner of a single story is not something that is currently being considered.

https://empireweekly.com/web-stories/best-fitness-exercises-for-weight-loss is a web page, just like google.com is a web page. It's not something you can "exit" from. If you want to bring users back to your homepage, you can add call to action links to your story, and even add a repeating avatar in the corner if you'd like.

**Comment by halilesen** [comment]
Thank you for your answer.

True. You are right. Maybe for these, the site icon and the site name can be added next to it.

On second thought, adding an author avatar can cause keys like "share" "exit" "volume" to get stuck in the corner. I don't know, maybe it will be redesigned. But as I mentioned, it can be useful.

**Comment by halilesen** [comment]
How about [that](https://wordpress.org/support/topic/endless-feed-of-stories/#post-15634812)?
