### ISSUE TITLE
Allow users to swipe down to close a story

### ISSUE THREAD

**Issue by mxbclang** [swissspidy/web-stories-wp#11412]
## Feature Description

[A user in the forums requested](https://wordpress.org/support/topic/some-requests-ideas-and-errors/) the ability for users to swipe down to exit a story, similar to the behavior on the Facebook and Instagram apps.

**Comment by halilesen** [comment]
The reason why I want this is this: If they can't see this gesture, which is familiar from Facebook and Instagram in general, using the Stories feature, they will find it strange.
