### ISSUE TITLE
Dashboard: Add Filter by Taxonomy

### ISSUE THREAD

**Issue by sblinde** [swissspidy/web-stories-wp#11436]
## Summary

This issue will add a new filter option to the Dashboard to filter Stories, based on hierarchical taxonomy. 

<img width="1263" alt="Screen Shot 2022-04-20 at 11 42 53 AM" src="https://user-images.githubusercontent.com/10720454/164309270-2b2497c3-7f97-4af8-b860-989c8222ce37.png">

## References

UX: Still in progress, but this issue's implementation can be started prior to having fleshed out comps for this. We can mimic the experience described below.

For an example of what this could look like, please see `All Stories` in the default WordPress view for what this means. The functionality between these two spaces should be the same: a dropdown, similar to the Author in the screenshot seen above.

## Alternatives Considered

No alternatives.

### Does this epic have any performance impact?

This should not impact performance.

### Does this epic have telemetry?

We could capture usage of this dropdown via telemetry.

**Comment by spacedmonkey** [comment]
For reference, the post list page in WordPress looks like this. 
<img width="582" alt="Screenshot 2022-05-05 at 17 58 11" src="https://user-images.githubusercontent.com/237508/166974552-ed35d064-1833-45dc-bffd-44872fcbf237.png">

**Comment by sblinde** [comment]
Per conversation earlier this week with Amy, we'll lean towards renaming the dropdown to `Categories` similar to the categories dropdown. Taxonomies usually includes both Categories and Tags, but the use case here is for Categories, and because there are custom taxonomies that can be a part of WordPress, best if we're clear on what the filter is meant for to reduce confusion!

**Comment by felipebochehin87** [comment]
@mwritter @sblinde @swissspidy 

The functionality is ok, it's filtering stories based on the value selected in the filter. But please, one thing that is not clear, which should be the name of the dropdown: taxonomies or categories? I currently see "Taxonomies", but there's a comment from 15 days ago saying that the name should be "Categories". What's the expected? Thanks!

![dropdown.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/13c46c3f-3eef-496c-ab5f-1a0412d195df)

**Comment by spacedmonkey** [comment]
Why was this PR moved to QA? It does seem to have been approved by anyone.

**Comment by mwritter** [comment]
> Categories

https://github.com/GoogleForCreators/web-stories-wp/pull/11526#issuecomment-1132939949
@felipebochehin87  per the conversation on the PR, after our design meeting we were under the impression that this filter was only going to be used for filtering 'Categories'.  It is now understood that this filter is for 'hierarchical' taxonomies, so the name 'Category' would not really work here anymore.  🤔It should probably just be 'Taxonomy' though not 'Taxonomies'.

**Comment by mwritter** [comment]
> Why was this PR moved to QA? It does seem to have been approved by anyone.

https://github.com/GoogleForCreators/web-stories-wp/pull/11526#issuecomment-1138934921
@spacedmonkey per the conversation on the PR, @sblinde mentioned that we were going to move to qa while we work on writing a couple more tests for test coverage. 🤔 There should have been a review on it though I do agree, @sblinde I know we discussed the code change could you give it a formal review when you get a chance? - the main code change shouldn't change only test coverage is needed.

**Comment by spacedmonkey** [comment]
@mwritter This is not the normal process in this project. PRs must be approved before they go to QA. Also, someone from the WP pod should really review and approve this PR, as this PR touches WordPress apis.

**Comment by spacedmonkey** [comment]
Having a quick look at the functionality of this PR, it is a little confusing. Why is this dropdown a mixture of taxonomy terms from different taxonomies. If you had a term of rock, in two taxonomies, how would you know which one you are selecting here? I believe it best to have a dropdown per taxonomy, not one dropdown for everything.  This mirrors how WP list page does it. 
<img width="606" alt="Screenshot 2022-05-27 at 14 25 51" src="https://user-images.githubusercontent.com/237508/170708383-ebea3fe5-f1a6-494e-b8e4-a63b0097c851.png">

**Comment by sblinde** [comment]
@spacedmonkey Understood, I'm used to a more flexible QA process where QA can be either prior to or after approval, so I apologize. I had given an approval prior to the further changes to the PR being done, and also had helped throughout in parts to the PR myself as well. I do agree: someone from WP pod should review it (and by no means were we asking to have QA done and have this ready to merge, we all understand adequate approvals are required prior to that).

**Comment by sblinde** [comment]
> Having a quick look at the functionality of this PR, it is a little confusing. Why is this dropdown a mixture of taxonomy terms from different taxonomies. If you had a term of rock, in two taxonomies, how would you know which one you are selecting here? I believe it best to have a dropdown per taxonomy, not one dropdown for everything. This mirrors how WP list page does it. <img alt="Screenshot 2022-05-27 at 14 25 51" width="606" src="https://user-images.githubusercontent.com/237508/170708383-ebea3fe5-f1a6-494e-b8e4-a63b0097c851.png">


Totally understand what you mean and excellent point, and I think that's something that wasn't clear for us picking up on the prior work slated by the previous team. At first, we thought that we were supposed to be supporting Categories (as seen in that dropdown), and then the ask was that we include All Taxonomies. Your point is right: if you had more than one same-named custom taxonomy, it would show up similarly in the dropdown.

But as far as I'm aware, even with adding custom taxonomies within `Stories` and that similar page view, that there's not a space that actually shows any dropdowns for custom taxonomies, not even within the WP list style page for stories as seen below in my screenshot.

![Screen Shot 2022-05-27 at 10 03 41 AM](https://user-images.githubusercontent.com/7110244/170715241-2d276ba8-dc65-4d07-937a-570dd46c045f.png)
(Note: this one Story has two custom taxonomies assigned to it and one category, but there's no indication or view to know such within this page, and no category dropdown)

But I would have hoped this would have come up with initial conversations about designing and planning this work prior to our start implementing it. Our team is pretty fresh at this work, so it's harder for us to know (especially since our initial thought was that we were supporting categories) what's expected if it isn't clearly defined and scoped. If there are gaps between what's expected, those gaps will be larger for us as a team with fresh eyes coming into this.

**Comment by sblinde** [comment]
For clarification based on conversations, here are the expectations for this feature:

- This feature should support multiple taxonomies, including custom taxonomies that are defined as hierarchical (seen as: `hierarchical: true` coming from the Taxonomies endpoint)
- This feature should render an individual Taxonomy dropdown for each type of hierarchical taxonomy, and each filter should work independently of one another.
   - Example: Imagine a WordPress instance that had `Categories`, `Tags`, and `Colors` (the latter being a custom taxonomy). `Tags` would not have a dropdown, because `Tags` has `hierarchical: false`. `Categories` and `Colors` would have individual dropdowns on the Dashboard, respective of each item.
   - The title of each dropdown should correspond to the name of the type (i.e. `Categories` would be titled `All Categories`)

**Comment by swissspidy** [comment]
> The title of each dropdown should correspond to the name of the type

For context, the right `All Categories` labels will be provided in the REST API response under `labels.allitems`. See how the `story-editor` package uses `taxonomy.labels.[...]` everywhere as well.

There's no need to provide this label manually (and string concatenation like "All %s" should be avoided anyway)

**Comment by spacedmonkey** [comment]
Should we respect the "show ui" or "show admin column" visibility fields? 
<img width="218" alt="Screenshot 2022-06-09 at 12 05 35" src="https://user-images.githubusercontent.com/237508/172832857-e3fd87cf-cf10-4ae8-8a3b-9e9d09d6d8fb.png">

**Comment by swissspidy** [comment]
> Should we respect the "show ui" or "show admin column" visibility fields?

Yeah good call, I think we can filter by `visibility.show_ui` (not the other one).

We do that in the editor as well:

https://github.com/GoogleForCreators/web-stories-wp/blob/abb46513d451d1e39668fc0afb0345e852871a19/packages/story-editor/src/components/panels/document/taxonomies/taxonomies.js#L51-L59

^ @mwritter It should be easy to implement that in the same spot where you currently filter hierarchical taxonomies.

(ignore the `canAssignTerms` part!)

Let's continue the discussion about that on the PR though.
