### ISSUE TITLE
Animations: Editor crashes when using negative duration values

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11439]
## Bug Description

The editor crashes when trying to set a negative number as the animation duration.

## Expected Behaviour

No crash.

Negative duration values are not allowed, so we can just revert to the number `0` in that case.

This what we already do for the delay.

## Steps to Reproduce

1. Add new element to page
1. Add animation
1. Set animation duration to a negative number
1. See editor crash

## Screenshots

![Screenshot 2022-05-05 at 12 34 47](https://user-images.githubusercontent.com/841956/166907363-826dc856-ccb5-49c2-86bf-d05409cfff91.png)

## Additional Context

- Plugin Version: 1.20.0
- WordPress Version: 5.9
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
Let's also add some extra hardening to `sanitizeTimings()` to prevent this from falling through the cracks in some other way. Something like this:

```js
export const sanitizeTimings = (timings) => ({
  ...timings,
  easing: timings.easing || 'linear',
  // Prevent non-negative values from slipping through.
  // See https://github.com/GoogleForCreators/web-stories-wp/issues/11439
  duration: Math.max(timings.duration, 0),
  delay: Math.max(timings.delay, 0),
});
```

---

cc @littlemilkstudio

**Comment by mflorida** [comment]
@swissspidy Should a new Karma test be written to verify correct handling of values less than 0?

**Comment by swissspidy** [comment]
Makes sense 👍

**Comment by felipebochehin87** [comment]
Negative values, special characters and letters are set to 0. App is not crashing.
