### ISSUE TITLE
AMP Sanitization: Enforce HTTPS

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11444]
## Feature Description

In rare cases there are users with HTTP sites or mixed HTTP/HTTPS content, which results in confusion, AMP validation errors, and support requests.

The AMP plugin's video sanitizer and base sanitizer contain methods for forcing SSL on things like video URLs. See https://github.com/ampproject/amp-wp/blob/7c6018dc4dde1e2116558c881cd9843326be5926/includes/sanitizers/class-amp-base-sanitizer.php#L491-L515 for example.

However, we do not use the default video sanitizer. IIRC it didn't fit our needs very well.

There are also functions like `wp_replace_insecure_home_url` in core (see https://make.wordpress.org/core/2021/02/22/improved-https-detection-and-migration-in-wordpress-5-7/)

I think we could easily amend our existing story sanitizer to use HTTPS for URLs where needed (maybe only video URLS and captions URLs?). Either enforce it or by using something like `wp_replace_insecure_home_url`.

Needs some testing/evaluation.

**Comment by swissspidy** [comment]
Now that we bumped our WP requirement to 5.7 this is more feasible, though also low prio because it's not often causing issues.

**Comment by spacedmonkey** [comment]
> Maybe we can just replace the logic in there with calling wp_replace_insecure_home_url()?

Why not!
