### ISSUE TITLE
Button to lock element on the editor

### ISSUE THREAD

**Issue by fellyph** [swissspidy/web-stories-wp#11445]
## Feature Description

Sometimes editing the stories, a common scenario is to spend a few minutes trying to arrange elements, for example, a graphic behind a text, this happens especially when I reuse web stories, a title changes and the box behind should increase to cover the new text and other elements need to move around. 

Would be good to have a button to lock the element on the screen temporarily, and move the elements behind the locked element.

Add a button at the context menu, for example:

![Screen Shot 2022-05-06 at 14 22 12](https://user-images.githubusercontent.com/330792/167141043-ac4b0458-c73b-41f1-ae3e-676444834630.png)

**Comment by swissspidy** [comment]
Hi Fellyph

We're actually working on this already. See #7332

**Comment by fellyph** [comment]
Awesome! @swissspidy
