### ISSUE TITLE
Karma: Null Error from Percy Snapshots

### ISSUE THREAD

**Issue by sblinde** [swissspidy/web-stories-wp#11447]
## Bug Description

Percy snapshots seem to indicate an error on the `main` branch for the `getDisplayTextStyles` in several open PRs on the repo. I've only seen this so far within the Editor space of the Percy snapshots.

## Expected Behaviour

No errors displayed within Percy screenshots for the Editor.

## Steps to Reproduce

- Open a current PR
- (examples: https://github.com/GoogleForCreators/web-stories-wp/pull/11404 https://github.com/GoogleForCreators/web-stories-wp/pull/11443)
- Open the Percy check to review the Percy snapshots
- See an error in both the PR branch and `main`

I have not been able to replicate this error when running the code locally on my machine as of yet, but if I capture reproduction steps there, I'll add to this issue.

## Screenshots

![Screen Shot 2022-05-06 at 10 40 52 AM](https://user-images.githubusercontent.com/7110244/167156893-eb5da179-2ccc-4f30-8273-1e3d89a5bf06.png)

## Additional Context

- Plugin Version: N/A, locally run main branch
- WordPress Version: within Percy's screenshot
- Operating System: within Percy's screenshot
- Browser: within Percy's screenshot

**Comment by swissspidy** [comment]
The code in question:

https://github.com/GoogleForCreators/web-stories-wp/blob/3eb6047a4ed1b7540cdd4a7035f82d44f305f9bb/packages/story-editor/src/karma/richText/inlineSelection.karma.js#L402-L411

https://github.com/GoogleForCreators/web-stories-wp/blob/3eb6047a4ed1b7540cdd4a7035f82d44f305f9bb/packages/story-editor/src/karma/richText/inlineSelection.karma.js#L439

Looks like the util should be made a bit more robust, but maybe there's more at play here.

Aside: It doesn't help that this util is **async** but there is no **await**.

Assigning to Prometheus pod who wrote these tests originally. cc @barklund @merapi
