### ISSUE TITLE
Audio Hotlinking: Enable by default

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11452]
## Feature Description

While some UX details are yet to be flushed out in #10515, these are not release-blocking.

Thus, we should be able to enable these two features by default ahead of the 1.21.0 release, making sure that they are properly QAed.

**Comment by felipebochehin87** [comment]
@swissspidy I don't see the subtitles on the Preview Story mode, only on the editor. Am I missing anything please?

https://images.zenhubusercontent.com/235435637/f6713b54-4213-43be-8332-1e094111baf2/no_subtitles.mp4

**Comment by swissspidy** [comment]
@felipebochehin87 Not missing anything. Looks like it's because of CORS (see the console errors). We'll need to get back to the drawing board on this one. Thanks for testing!

**Comment by felipebochehin87** [comment]
Thanks :)

**Comment by swissspidy** [comment]
@felipebochehin87 The audio hotlinking did work well though?

**Comment by felipebochehin87** [comment]
@swissspidy yes!

**Comment by felipebochehin87** [comment]
New bug created for fixing CORS that blocks the subtitles on the Preview Story mode. PR #11479. Moving this ticket to QA approved given that the audio hotlinking is working.
