### ISSUE TITLE
Some Problems in iOS and Standalone Display Mode (PWA)

### ISSUE THREAD

**Issue by halilesen** [swissspidy/web-stories-wp#11469]
I have reported this problem before on the forum ([Web Stories](https://wordpress.org/support/topic/closing-opening-in-new-tab/) and [PWA](https://wordpress.org/support/topic/related-to-new-tab-links-that-can-be-considered-as-external-or-external/)). However, I think it would be useful to reiterate here in a more concise and clear way.

 When we open the links in the story by swiping, the theme color will be affected or deleted and there will be some scrolling issues.

There is no problem when in the normal Safari tab. It only happens when saved as PWA (Share > Add to Home Screen > Add) and when in standalone display mode.

https://youtube.com/shorts/slOJGVSjXQQ?feature=share

There is a scrolling problem as seen at 0:15. This error may not happen all the time, but it does happen most of the time.

After 0:28 it can be seen that the theme-color and background change. This happens when scrolling to the bottom and top.

It may disable some codes like "viewport-fit=cover" as will be seen after 042. The found portion of this code is located of a subfolder in phpBB forum. It also affects the theme color again, as [here](https://youtube.com/shorts/X-k-3f9hsgo) at 0:14.

- Plugin Version: 1.20.0
- WordPress Version: 5.9.3
- Operating System: iOS 15.4.1
- Browser: Safari

**Comment by swissspidy** [comment]
I am repeating my question from the forum again:

Does this happen for **any story** (for example also [this demo story](https://wsdemos.uc.r.appspot.com/cta-buttons)) _when you open it in a PWA_?

If so, you might want to consider submitting a new issue at https://github.com/ampproject/amphtml, where the Web Stories format itself is being developed. Also, as per the reply on the PWA forum, this sounds like an PWA implementation issue for Safari, so you might want to consider filing a bug to Safari/Webkit.

**Comment by halilesen** [comment]
> Does this happen for **any story** (for example also [this demo story](https://wsdemos.uc.r.appspot.com/cta-buttons)) _when you open it in a PWA_?

If I said it before: This page you're showing doesn't add in standalone display mode, so I can't test it.

**Comment by swissspidy** [comment]
What I am trying to figure out is whether this is a problem with the Web Stories WordPress plugin, Web Stories in general, or Safari.

I doubt that this bug is specific to the WordPress plugin, so now we need to figure out whether it's a bug with Web Stories or Safari.

If it's the former, I recommend filing a bug at https://github.com/ampproject/amphtml.

If it's the latter, I recommend filing a bug at Safari.
