### ISSUE TITLE
Prevent non-numeric values in numeric input fields

### ISSUE THREAD

**Issue by mflorida** [swissspidy/web-stories-wp#11470]
## Bug Description

Numeric inputs should not allow non-numeric values.

## Expected Behaviour

Inputs that require a numeric value, should block non-numeric values from being entered.

> Typing 'xyz' should not change the input value - keystrokes should produce no effect.

## Steps to Reproduce

- Enter a non-numeric value into a numeric input (ie: image position).
- Input updates with non-numeric value (it does reset to previous value when losing focus, but a better UX would be to prevent input of invalid values)

## Screenshots

!['xyz' non-numeric value](https://user-images.githubusercontent.com/4173034/167670498-b780d2f1-6104-467d-9bcd-9a882f0bd474.png)

## Additional Context

- Plugin Version: Web Stories 1.21.0-alpha.0
- WordPress Version: 5.9.3
- Operating System: macOS 12.3.1
- Browser: Chrome 101.0.4951.54

**Comment by swissspidy** [comment]
Curious, where is this coming from?

> Input updates with non-numeric value (it does reset to previous value when losing focus, but a better UX would be to prevent input of invalid values)

IIRC we deliberately implemented it this way in #6414 / #6419. Maybe @barklund or @BrittanyIRL recalls.

**Comment by mflorida** [comment]
If this is by design, please close the issue. In my experience working with similar editors, non-numeric input is blocked, and any allowed unit types are presented in a menu, or if only one type is allowed, shown as text outside the input field (`px` for pixels, `ms` for milliseconds, etc). It was something I ran across working on the negative animation value bug #11439.

**Comment by swissspidy** [comment]
It's always good to challenge the status quo, so thanks for raising this. I recommend checking with UX to see whether we want to make any changes in this regard, I was just trying to provide some context

**Comment by mflorida** [comment]
@swissspidy Thanks for the info. Since I'm new to the team, any context that can be provided is certainly appreciated!
