### ISSUE TITLE
Media: Require CORS for captions hotlinking

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#11479]
## Bug Description

Subtitles are not displayed on the frontend when the VTT file does not have the required CORS headers set.

## Expected Behaviour

Handling of caption files with missing CORS header needs to be improved.

First, the parent `<amp-video>` needs `crossorigin="anonymous"` for it to work ([see docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track#attr-src)).
Second, if the VTT file doesn’t have CORS headers it won’t work.

Since we can't use the CORS proxy on the frontend, we must not use the CORS proxy for captions in the editor, as it gives the false impression of any VTT file working. Basically give an error message straight away.

## Steps to Reproduce

1. Start a new story
2. Click on the background
3. Click on Style tab
4. Click on "Link to audio file" and paste https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/uploads/2022/02/file_example_MP3_1MG.mp3
5. Click on "Use audio file"
6. Click on "Link to caption file" and paste https://wp.stories.google/stories/how-to-optimize-videos-for-web-stories/tracks/wst024_page2_my_captions.vtt
7. Click on "Use caption"
8. Click on preview story button - the audio will play, but the subtitles won't be displayed

## Screenshots

https://images.zenhubusercontent.com/235435637/e8191c4e-1967-4674-b69d-0a59a48a56ee/no_subtitles.mp4

![CORS.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/23e8da7e-22b0-4a31-8f90-acdf871536f0)

## Additional Context

- Plugin Version: 1.21.0-alpha
- WordPress Version: 5.9
- Operating System: macOS
- Browser: Chrome

**Comment by spacedmonkey** [comment]
Another idea, that needs work, we could download the VTT file and serve this as a blob. That way we can avoid hotlink the file all together. A VTT is normally extremely small, so a blob, should not be very big here.

**Comment by swissspidy** [comment]
You mean inlined `'data:text/vtt;base64;....` URLs? Good idea, but that's not valid AMP.

**Comment by spacedmonkey** [comment]
I did mean a base64 encoded string. That is a pain that is not valid amp. 

Is the CORS issue an issue with the amp standard or it is a browser issue?

**Comment by swissspidy** [comment]
It's a browser thing. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track#attr-src and also this demo: https://codepen.io/swissspidy/pen/OJQpXLE

So for now we will require VTT files to have proper `Access-Control-Allow-Origin` headers, so I'll look into this

**Comment by felipebochehin87** [comment]
Hi @swissspidy @spacedmonkey 

I'm seeing something here... When I add the invalid caption link it works as expected, the CORS message is displayed. However, when I add the audio and the link to the caption that should work, I get a message saying "Video failed to play" on the preview screen. If I remove the caption link and leave only the audio, then it works. I tried with both empty canvas and adding images to the canvas, got the same result in both cases.

Only audio - works (https://download.samplelib.com/mp3/sample-3s.mp3)
Invalid caption - works (https://wp.stories.google/stories/how-to-optimize-videos-for-web-stories/tracks/wst024_page2_my_captions.vtt)
Audio + valid caption - fails (https://api.ardmediathek.de/subtitle-format-service/webvtt/urn:ard:subtitle:74cfd50da83320c6.vtt)

https://images.zenhubusercontent.com/235435637/41590613-a1e8-462d-b3d9-93a6fdadafb7/2022_05_23_07_59_45.mp4

![errors.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/31db6bc6-19b1-44cb-908f-72316c117fbd)

**Comment by swissspidy** [comment]
@felipebochehin87 Thanks for raising this. I'll take a look.

At first glance this might be a bit of an edge case that warrants its own ticket/PR.

**Comment by felipebochehin87** [comment]
@swissspidy thanks :)

**Comment by swissspidy** [comment]
@DanielCryptoK This ticket here is about a new feature that we have not released yet, so what you are describing is not related. Could you please open a new support topic on WordPress.org about your case and provide details? FWIW, the AMP Test report you linked to does not show any errors, and captions are appearing just fine on your story. So I don't see any issue there at all. But if I am missing something, please add some context in the support topic. Thanks!

**Comment by DanielCryptoK** [comment]
I opened a ticket, sorry I did not realize it was a new feature as I have had the CORS errors before. Are you sure you can not see the errors your side? 
![Web capture_23-5-2022_204454_search google com](https://user-images.githubusercontent.com/45933242/169833697-c30bc660-2ba1-40a4-9a84-80f6fcaf151b.jpeg)

**Comment by felipebochehin87** [comment]
Error messages being displayed as expected.
