### ISSUE TITLE
Mobile App?

### ISSUE THREAD

**Issue by halilesen** [swissspidy/web-stories-wp#11486]
I'm sure you have thought of this idea too. Web Stories are nice, but it is necessary to use a computer to share stories instantly. Things would be smoother and nicer if Web Stories had an app and had the same functions.

After thinking about it, I thought about how to log in to the app. For example, even WooCommerce requires a Wordpress.com membership. (I'm a member). However, it may be possible to somehow specify the website first and open the classic Wordpress login screen. I am not sure. I don't have much coding knowledge.

**Comment by swissspidy** [comment]
Thanks a lot for opening this feature request.

Mobile is a very important aspect for us.

While the primary focus of this editor is desktop story creation, we are looking for ways to improve its usability on touchscreen devices such as smartphones and tablets. See #1686 for that.

Building actual mobile apps for this editor are not something we are planning on pursuing. However, mobile story creation capabilities in general is something that we are looking into.

While we acknowledge your feature request, I am closing this issue simply for organizational purposes.
