### ISSUE TITLE
Option to open link in a single click

### ISSUE THREAD

**Issue by harishtewari** [swissspidy/web-stories-wp#11489]
## Feature Description

In current scenario if we add a link on the web stories and when we click on this link first it's open in the tool tip and then again need to click on this tooltip text to open link. So Need an option to add links as a button and open this link on single click.
Example:  https://timesofindia.indiatimes.com/entertainment/hindi/web-stories/a-peek-into-urvashi-rautelas-glamorous-wardrobe/photostory/91318928.cms

![last-slide](https://user-images.githubusercontent.com/42132626/168590120-6d0b20eb-9bbc-4e1c-be19-f4a1befe322d.png)

**Comment by swissspidy** [comment]
Page attachment links open after a single click. So does the "Find out More" page attachment link in your example story. Proof:

https://user-images.githubusercontent.com/841956/168594637-b67abc6a-6171-475a-a2c2-d59842e5563e.mov

So I don't see any issue here.

Any other links, for example links on a text element, require two clicks by design.

**Comment by harishtewari** [comment]
Thanks for your quick response.

There is not an issue. I am using This https://wordpress.org/plugins/web-stories/ plugin for web stories.

As you mention on above comment [Any other links, for example links on a text element, require two clicks by design.]  So Need a option to do this process on single click in this plugin.

![screen-shot](https://user-images.githubusercontent.com/42132626/168600751-7b0eca59-83b5-416c-ae28-1112adca934b.png)


https://www.jansatta.com/web-stories/fashion/stunning-tina-dutta-in-short-dress/

**Comment by swissspidy** [comment]
Got it, thanks.

Such links require two clicks _by design_. It is defined as such in the Web Stories format for UX reasons and is unlikely to get changed.

However, if you have very good arguments for changing that, you can file a feature request at https://github.com/ampproject/amphtml for this. That's the right place.
