### ISSUE TITLE
Animation preview shortcut cmd + space conflicts with Spotlight on macOS

### ISSUE THREAD

**Issue by mflorida** [swissspidy/web-stories-wp#11498]
## Bug Description

Using the recently modified keyboard shortcut `cmd + space` to play/pause animation previews conflicts with Spotlight on macOS and brings up the Spotlight search UI.

## Expected Behaviour

Using the keyboard shortcut shown in the tooltip for the play/pause button should start and stop the animation preview.

## Steps to Reproduce

On macOS, while viewing a story editor page that contains animations, use the `cmd + space` keyboard shortcut to try to preview the animation. The macOS Spotlight UI will render over all other on-screen elements.

## Screenshots

https://user-images.githubusercontent.com/4173034/168679015-e15c51a3-9377-4e68-8d43-375ba2fb8f57.mov

## Additional Context

- Plugin Version: 1.21.0-alpha.0
- WordPress Version: 5.9.3
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
Google Slides uses <kbd><kbd>⌘</kbd><kbd>Enter</kbd></kbd> to start a presentation, and <kbd><kbd>⌘</kbd><kbd>⇧</kbd><kbd>Enter</kbd></kbd> to start from the beginning.

Maybe we can use that?

**Comment by felipebochehin87** [comment]
CMD + Enter (macOS) and Control + Enter (Windows) control the animation preview. Tested on Safari, Chrome and Firefox.
