### ISSUE TITLE
Media: Safari not retrieving length of hotlinked audio

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11511]
## Bug Description

Identified by Marcin during bugbash using this file: https://download.samplelib.com/mp3/sample-3s.mp3.

The audio length retrieved by Safari was 0, so no loop controls were shown.

Plus, because of a slight bug the number "0" was printed on the page.

## Expected Behaviour

Loop controls should be visible if audio length can be retrieved.

No "0" should be displayed if audio length cannot be determined

## Screenshots

![Screenshot 2022-05-18 at 10 02 25](https://user-images.githubusercontent.com/841956/168996465-38095d52-6739-4445-a995-12fc67f09c60.png)

## Additional Context

- Plugin Version: 1.21.0-alpha
- WordPress Version: 5.9 / 6.0
- Operating System: macOS
- Browser: Safari

**Comment by felipebochehin87** [comment]
No "0" is displayed
Loop is displayed and works as expected when on/off.
