### ISSUE TITLE
Request to disable "add new story to post" dialogue box feature

### ISSUE THREAD

**Issue by nicholassykes** [swissspidy/web-stories-wp#11523]
I posted an issue about this some time ago but can't find it now. I'm seeing the same "add story to post" dialogue box showing again and would like to disable this, if possible. 

[Process Stories](https://process-stories.app/) is a tool currently in development for creating async discussions about web stories and users aren't intended to have access to creating posts. 

Please let us know how we might go about disabling this feature for our users.

![New post in draft form](https://user-images.githubusercontent.com/16689918/169271608-4480216e-503a-4452-8510-bca860f0ab69.png)
![would like to add story to a new post dialogue box](https://user-images.githubusercontent.com/16689918/169271612-80b51602-3168-4e59-a273-00796283bded.png)

_Originally posted by @nicholassykes in https://github.com/GoogleForCreators/web-stories-wp/issues/2275#issuecomment-1131516238_

**Comment by nicholassykes** [comment]
Apologies - I perhaps should have posted this in the Wordpress forum;
https://wordpress.org/support/plugin/web-stories/
please remove this - if inappropriate.

**Comment by swissspidy** [comment]
Submitting feature requests directly here is fine, but we prefer to use the forums for everything else. So thanks for thinking about that!

It looks like you have a very custom story editor integration on your platform that doesn't look at all like wp-admin anymore. I understand why you would not need this dialog in such a scenario.

In this case I'd recommend you to look into using our standalone npm packages such as `@googleforcreators/story-editor` to build your own story editor that fits your needs better. See https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/third-party-integration/story-editor/getting-started.md for some details.

This package contains the "core" story editor without things like this dialog, so you could better tweak it to your needs.
