### ISSUE TITLE
Shopping: Prevent duplicate products on a page

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11521]
## Feature Description

Right now the idea is that a single product can only appear on a page once.

Currently, it's possible to end up with multiple products by duplicating or pasting elements.

How can we avoid that?

Possible options:

* Do not add element and display a snackbar message
* Add the element but without the product attached

Not sure where's the best place to do this.

Relevant code:

* `useCanvasCopyPaste`: handles keyboard cop/paste
* `useCanvasKeys`: handles element duplication via `mod+d`.
* `duplicateElementsById` reducer
* `useAddPastedElements` hook

**Comment by spacedmonkey** [comment]
Couldn't we just add something in insertElement to stop this?

**Comment by swissspidy** [comment]
Not all code paths go through `insertElement` from `useInsertElement`.
For example element duplication (`useCanvasKeys`) does not use that.

**Comment by swissspidy** [comment]
@barklund @merapi Would love to get your advice on this one. It's also related to #11254

**Comment by spacedmonkey** [comment]
One of the issues with this ticket, is there no central place to make this change. I think the first step would be revert all parts to use the `useInsertElement` hook and add the check there.

**Comment by swissspidy** [comment]
Such a refactoring is a bit out of scope for this ticket, but maybe that's something that can be looked into in the future. It should not block this ticket though ideally.

**Comment by felipebochehin87** [comment]
Tested in Chrome, Firefox and Safari.

Questions @swissspidy @spacedmonkey please:

- if I add only 1 product, the message informing that the product already exists on the page is displayed - ok
- but if I add 2 or more products and select them all at the same time, copy and try to paste them, I only see the message for 1 of the products (the last one that was added). What should we do in this case? Please see video below.

1. Should we display the product names in the same message, separated by comma?
2. Should we display each product in a separate message?
3. Should we leave it as it is right now?
4. If we are fixing this, should I create a new bug for that or should I kick back this one?

Thanks!

Video:

https://images.zenhubusercontent.com/235435637/b6385bd2-41ca-4485-8247-af7e2efcf07a/2022_06_08_12_27_19.mp4
