### ISSUE TITLE
Provide way to set manual page advancement as default

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#11528]
## Feature Description

Each new story has a default page advancement set to “Auto” with 7 seconds. [One user in the support forum](https://wordpress.org/support/topic/disable-autoplay-page-advancement-to-manual-by-default/) has asked if it would be possible to allow users to be able to disable the auto page advancement option so that each new story created has a manual page advancement set.

Current default setting for each story:

![image](https://user-images.githubusercontent.com/91896826/169516479-52926eaf-49e0-47aa-a4c1-66758b1477c0.png)

## Alternatives Considered

Rather than allow users to disable the auto option, there could be a setting to change what is used as the default setting for page advancement. 

This setting could be solely something for developers to change, **not** a UI option.

**Comment by nicholassykes** [comment]
We are currently embedding the story editor into a wordpress site called Process Stories.
I'd like to suggest a feature in addition to switching default page advancement to manual;
**If the story editor can please support auto-advance on a per page basis.**
It would be super useful to control the extent to which each page advances.

**Comment by swissspidy** [comment]
Thanks for sharing your feedback.

As per that above doc (which is quite outdated FWIW) we have deliberately not added support for this in the editor for UX reasons. We might reconsider this in the future, though there are no plans for that right now.

**Comment by swissspidy** [comment]
Tracking the above separately in #12210 now
