### ISSUE TITLE
Hotlinking: Allow video poster image to be hotlinked

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11535]
## Feature Description

Allow for video poster image to be looked, similar to how background audio can be current be hotlinked. 

Original discussion - https://github.com/GoogleForCreators/web-stories-wp/issues/10515#issuecomment-1122377803

This change will require UX, as is it not simple to add a hotlink button in current implementation. 

<img width="140" alt="Screenshot 2022-05-10 at 14 16 32" src="https://user-images.githubusercontent.com/237508/167637407-da7dc815-65ed-4d39-a1cc-951cf2f253cc.png">

Also worth noting that this change may also need, CORS checks.

**Comment by spacedmonkey** [comment]
<img width="274" alt="Screenshot 2022-05-23 at 17 12 20" src="https://user-images.githubusercontent.com/237508/169862318-eaedd050-75c9-48b0-ac4c-f4d68d46734c.png">
This UX might be able to be re-used.

**Comment by felipebochehin87** [comment]
![icon video.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/a77928a1-de8a-4621-bfa5-6917092f7892)
