### ISSUE TITLE
Hotlinking: Allow story poster image to be hotlinked

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11536]
## Feature Description
Allow for story poster image to be looked, similar to how background audio can be current be hotlinked.

Originally discussion - https://github.com/GoogleForCreators/web-stories-wp/issues/10515#issuecomment-1122377803

This change will require UX, as is it not simple to add a hotlink button in current implementation. 

<img width="140" alt="Screenshot 2022-05-10 at 14 16 32" src="https://user-images.githubusercontent.com/237508/167637407-da7dc815-65ed-4d39-a1cc-951cf2f253cc.png">

**Comment by spacedmonkey** [comment]
Related: https://github.com/GoogleForCreators/web-stories-wp/issues/11535

**Comment by swissspidy** [comment]
A couple of notes after discussing this the other day:

1. It's important that we verify that the poster image has the correct dimensions. Need to display an error dialog otherwise.
2. We can reuse the new `DropDownMenu` component that I've used in the `FileRow` component.
    Clicking on the pencil button would open a dropdown menu with two options:
	1. Upload a file
	2. Link to a file
