### ISSUE TITLE
Hotlinking: Allow publisher logo image to be hotlinked

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11537]
## Feature Description

Allow publisher logo image to be hotlinked. See https://github.com/GoogleForCreators/web-stories-wp/issues/11535 and https://github.com/GoogleForCreators/web-stories-wp/issues/11536 for more detail.

**Comment by swissspidy** [comment]
A couple of notes after discussing this the other day:

1. It's important that we verify that the publisher logo has the correct dimensions. Need to display an error dialog otherwise.
2. We can reuse the new `DropDownMenu` component that I've used in the `FileRow` component.
    Clicking on the pencil button would open a dropdown menu with two options:
	1. Upload a file
	2. Link to a file
