### ISSUE TITLE
Firefox: Image (1920 x 1080) stretched & low quality when previewing

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#11538]
## Bug Description

A [1920 x 1080 image](https://selectgame.gamehall.com.br/wp-content/uploads/2022/05/Obi-Wan-Kenobi-em-Fortnite-01.jpg) that has been set as background is stretched when viewing it on Firefox but looks okay in the story editor. Another image that was added to the canvas and resized looks fine in the editor but in Firefox appear to be blurry. 

Here is an example story: https://testsite.cmsdevrel.com/web-stories/testing-user-story-bad-image/
Here is the original report: https://wordpress.org/support/topic/bad-image-quality-in-desktop-browsers/ & [story](https://selectgame.gamehall.com.br/web-stories/obi-wan-kenobi-de-star-wars-chegara-em-fortnite/)

Editor:
<img width="545" alt="Screen Shot 2022-05-23 at 12 15 08 PM" src="https://user-images.githubusercontent.com/66372350/169862975-40f63447-9003-49ed-a802-5fab29a3fc96.png">

Firefox:
<img width="789" alt="Screen Shot 2022-05-23 at 12 16 14 PM" src="https://user-images.githubusercontent.com/66372350/169863002-41a71328-145e-49fb-bfbb-f1089215584b.png">

<img width="692" alt="Screen Shot 2022-05-23 at 12 21 43 PM" src="https://user-images.githubusercontent.com/66372350/169864092-a383717c-b94d-441e-a300-4a58706d6764.png">

## Expected Behavior
Image should display clearly on the browser.

## Steps to Reproduce

1. Insert 1920x1080 image as background
2. Note display in editor
3. Preview on Firefox Browser

- Plugin Version: 1.21.0
- WordPress Version:
- Operating System:
- Browser: Firefox

**Comment by swissspidy** [comment]
Alright. And the issue with the blurriness also occurs in other browsers?

**Comment by LuckynaSan** [comment]
I've retested this story on Firefox, Chrome, and Safari private windows, and the images rendered fine without blurriness. Closing this ticket as not able to reproduce.
