### ISSUE TITLE
Media Recording: Move on canvas

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11542]
## Feature Description

The initial media recording prototype was built in a dialog. We now want to bring the media recording capabilities directly to the canvas. It will somewhat resemble the video trimmer feature.

There is **a lot** going on in the current Figma designs as depicted below, showing plenty of functionality that won't be in V1 of this feature.

As a start, we want to port over the existing media recording capability that we have to the canvas.

In essence that means:

1. Clicking on the recording button in the sidebar will enable "recording mode" on the canvas
2. In recording mode, a start/stop/insert/retry button is displayed below the canvas
3. A timer is displayed above the canvas, counting the seconds since recording started / how long the video already is
4. A menu on the right side of the canvas (which should like the quick actions menu) allows a few actions:
	1. "X" will cancel recording and end recording mode 
	2. A gear icon button that opens a dialog for changing the camera/microphone
	3. If easily possible: a trim button that allows trimming the recorded video before it is uploaded to the server

(We can update this section as progress is made on the UX side)

Previous Slack discussion: https://xwp.slack.com/archives/C0135V8LYJE/p1652884370376849

Current design on Figma: https://www.figma.com/file/ZrO763yvMWJjYeAPsRnNfW/_Editor---Sprint-Feature-Level-Designs_2022?node-id=661%3A24394

Current mock (still WIP)
![Screenshot 2022-05-18 at 15 31 33](https://user-images.githubusercontent.com/841956/169895083-5c31b15b-b044-4769-9633-b89b2439b631.png)

**Comment by swissspidy** [comment]
@merapi It might make sense turning this into its own sub-epic with tickets for the initial move to on-canvas + all the individual features, but I'll leave that up to you.

**Comment by bmattb** [comment]
This work will not be picked up until current roadmap items (layer grouping, naming, masking) are completed.
