### ISSUE TITLE
Unable to select text in pre-publish checklist

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11540]
## Bug Description

I noticed that users are currently unable to select text in the pre-publish checklist (and the keyboard shortcuts menu).

This is because they're part of the canvas layer where selection is disabled somewhere higher up

For the quick tips panel we solved this by adding `*{ user-select: text; }` 

## Expected Behaviour

It would be nice if text could be selected.

## Steps to Reproduce

1. Open checklist or keyboard shortcuts dialog
2. Try to select text

## Screenshots

Cannot select text:
<img width="347" alt="Screenshot 2022-05-23 at 21 40 16" src="https://user-images.githubusercontent.com/841956/169894220-a22e9a28-66cb-434b-8adc-791a112a7ac4.png">

<img width="384" alt="Screenshot 2022-05-23 at 21 40 20" src="https://user-images.githubusercontent.com/841956/169894214-f3c36241-d177-471e-80ee-2c19c1954d86.png">

But here it is possible:

![Screenshot 2022-05-17 at 10 24 06](https://user-images.githubusercontent.com/841956/169894241-f18c049f-95be-4d10-880a-83a833cb553d.png)

## Additional Context

- Plugin Version: 1.21.0
- WordPress Version: 6.0
- Operating System: macOS
- Browser: Chrome

**Comment by mflorida** [comment]
Does the keyboard shortcut text need to be selectable? Are there accessibility issues if not?

**Comment by swissspidy** [comment]
I think it would be good if all text inside the panel would be selectable, including the keyboard shortcut text.

It's an a11y issue in the sense that this hinders me to select text, for example when I want to share the text with someone.

----

For reference, here's how it's solved for the help center:

https://github.com/GoogleForCreators/web-stories-wp/blob/9db395da8c1c0447326c171363de03851977fb2f/packages/story-editor/src/components/helpCenter/quickTip/index.js#L39-L46

https://github.com/GoogleForCreators/web-stories-wp/blob/9db395da8c1c0447326c171363de03851977fb2f/packages/story-editor/src/components/helpCenter/menu/index.js#L30-L38

**Comment by mflorida** [comment]
@swissspidy Do we want the 'landmark' shortcuts selectable as well?

**Comment by swissspidy** [comment]
Do you mean the 3 ones at the top?

It would be nice, but not super important compared to the rest I guess. Is it easy to accomplish?

**Comment by mflorida** [comment]
Super easy. Done.

**Comment by felipebochehin87** [comment]
Looks good in Safari, Chrome and Firefox.

![selected.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/0da46e5c-7ce9-4c71-8e54-9797f26a9900)
