### ISSUE TITLE
Consider locking aspect ratio of image on first placement on canvas

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11562]
Client has requested that when an image is first place on the canvas it might make sense that the aspect ratio is initially locked as default. 

Currently images do not have aspect ratio locked on first placement, and this is cumbersome for initial image sizing. User is aware that holding shift will lock aspect ratio during resize

NB - also noting that holding shift on resize to lock aspect ratio is an undocumented control.

**Comment by swissspidy** [comment]
So is this basically suggesting to reverse the current behavior? i.e.

* resize = does not change aspect ratio
* shift + resize = does change aspect ratio

**Comment by swissspidy** [comment]
I think we'll probably just improve documentation for the Shift+Move part
