### ISSUE TITLE
Layer Naming&Grouping integration

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#11567]

**Comment by felipebochehin87** [comment]
![group.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/f61e5ef5-bc09-4571-b79e-c7650fd7a681)

**Comment by felipebochehin87** [comment]
![copy copy copy.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/a2000256-59a9-4e9a-91e3-674d755ea6a4)
