### ISSUE TITLE
Removing Blurred Background Web Storie on Desktop

### ISSUE THREAD

**Issue by ArashA007** [swissspidy/web-stories-wp#11565]
Is there a way to remove the blurred background that shows up on Desktop view. 

![blurrred background](https://user-images.githubusercontent.com/25650595/170267518-5816a4b3-471b-4026-98c7-77df77ccbd35.PNG)

**Comment by ArashA007** [comment]
*** Made with the Wordpress Plugin ***

**Comment by ArashA007** [comment]
This is also embedded, because the theme I use does not understand web stories (unfortunately).

**Comment by swissspidy** [comment]
There is currently no way to turn this off. However, you can subscribe to https://github.com/ampproject/amphtml/issues/35638 to get any updates for when such a functionality might become available.

**Comment by swissspidy** [comment]
Closing in favor of https://github.com/ampproject/amphtml/issues/35638
