### ISSUE TITLE
Floating Menu: Consider ability to disable or change the default positioning

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11570]
## Feature Description

Users that are creating many web stories daily (power users) are unhappy with the floating toolbar introduced in v1.19 of the plugin, and have requested the ability to :
1. disable the presentation of the toolbar for individual users
2. move the default location of the floating toolbar to another, consistent location on the canvas.

**Comment by rodrigofglima** [comment]
Hi! Any chances to get an option to show the floating bar too, in default location (like "reset bar")? Im some situations (in Firefox) the bar its gone and impossible to show again until i insert a new text field (for example).

**Comment by swissspidy** [comment]
@rodrigofglima That part is a bug that we‘re working on fixing

**Comment by bmattb** [comment]
Additional recent feedback from a user on this:

> its having a real impact on my productivity… a major increase in extra clicks and lots of accidental type formatting is being applied

**Comment by felipebochehin87** [comment]
Two issues were found - PR #12095:

1. Add an element
2. Click on the element
3. Click on the Settings button
4. Click on "Fix to element"
5. Click on the Settings button again - see that "Fix to top" is always selected, no matter if I clicked on "Fix to element" or "Fix to top". However, if I click out of the canvas, click on the element and then on the Settings button, the correct option is marked as selected (vide below)
6. Also, see that the hint that is displayed when the cursor is over the Settings button remains displayed until the next click (image below)

https://images.zenhubusercontent.com/235435637/7c2547f4-41d8-41a7-af53-d8292f06a455/2022_08_25_09_16_16.mp4


![image.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/694f24ae-5398-4f0b-b599-2f9539b4a163)

**Comment by miina** [comment]
> Two issues were found - PR #12095:
> 
> 1. Add an element
> 2. Click on the element
> 3. Click on the Settings button
> 4. Click on "Fix to element"
> 5. Click on the Settings button again - see that "Fix to top" is always selected, no matter if I clicked on "Fix to element" or "Fix to top". However, if I click out of the canvas, click on the element and then on the Settings button, the correct option is marked as selected (vide below)
> 6. Also, see that the hint that is displayed when the cursor is over the Settings button remains displayed until the next click (image below)
> 
> https://images.zenhubusercontent.com/235435637/7c2547f4-41d8-41a7-af53-d8292f06a455/2022_08_25_09_16_16.mp4
> 
> ![image.png](https://camo.githubusercontent.com/a7dcb53e470c41ce36d185fbb9882163d0a7704ebef996be37a710284749d5e5/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631643566313132616361313965326335626232343431662f36393466323461652d353339382d346630622d623539392d326639353339623461313633)

Thanks for testing!

The selected option issue should be fixed now, please test that again. I'll create a follow-up issue for the tooltip since that's a bit more complex general problem.

**Comment by felipebochehin87** [comment]
Thanks @miina :) approved.
