### ISSUE TITLE
Quick action menu is sometimes incorrectly placed and blocking ability to select elements underneath

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11580]
## Bug Description

A user has encountered a scenario where the quick action menu is incorrectly placed on the canvas and is preventing her from accessing elements underneath

Changing the view from Fit to Fill did not move the QA menu to a location that unblocked.

Here you can see that although the user has resized to Fit, the Quick action menu is not in the correct location, and is placed on top of the page.

![Screen Shot 2022-05-26 at 12.48.18 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/a476b192-4a05-4715-8082-2bd6509a1544)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by mflorida** [comment]
Do you know which browser and OS?

**Comment by bmattb** [comment]
I have personally experienced this on Mac OS 11.6 Big Sur using Chrome Version 101.0.4951.64

**Comment by bmattb** [comment]
OS is Big Sur version 11.6 and I use Chrome

**Comment by swissspidy** [comment]
@bmattb Is this still an issue?
