### ISSUE TITLE
Standardize position where tooltips are displayed on the side menu

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#11584]
## Feature Description

I kindly suggest standardizing the position where the tooltips are displayed when the user hovers over the side menu quick actions. Nowadays, we have:

1. The ones at the top right display the tooltip at the right side of the button (video attached)
2. The ones at the bottom right display the tooltip below the button (video attached)

https://images.zenhubusercontent.com/235435637/2367225e-7fc7-4ac1-a817-41e76f16d00f/tooltips_v2.mp4

## Alternatives Considered

My suggestion is to make them all be displayed at the right side of the button so that we don't have a tooltip covering/hiding the button below it.

**Comment by mflorida** [comment]
This has been fixed and will be included in the next release. Thanks!

https://github.com/GoogleForCreators/web-stories-wp/issues/11561
