### ISSUE TITLE
Consider adding in Samsung devices into Preview

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11585]
## Feature Description

User have flagged that Samsung devices will render Web Stories differently than anticipated. Please consider being able to add current Samsung devices into the available device selection options in Preview, this would be helpful in understanding how these devices will render content uniquely. 

## Additional Context
Samsung currently has almost a 30% market share worldwide ([source](https://gs.statcounter.com/vendor-market-share/mobile))

**Comment by swissspidy** [comment]
This needs to be requested on the amphtml repository
