### ISSUE TITLE
Shopping: Prevent inserting products without images

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11591]
## Feature Description

In the shopping tab in the editor, we want to disable the Insertion button for products without images.

The button should just appear disabled but still be focusable (for a11y). (There's precedence for this in the code base, see also `aria-disabled`)

The insertion button should have a tooltip that says "Products without images cannot be added"

Ideally that's also somehow mentioned via `aria-label` (for a11y)

## Developer Notes

For working with this locally, make sure to do the following:
- Enable the Shopping Experiment in Stories > Experiments
- Enable WooCommerce Plugin
- In Stories > Settings, make sure `WooCommerce` is selected as your Shopping Provider.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #11616.

I wasn't able to add to the story products that have no image. Tested with different profiles and in different browsers.

![no image products.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/bf6bdf92-c30a-4b30-aae7-d45851022787)
