### ISSUE TITLE
Shopping: Infinite Scroll Pagination

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11593]
## Feature Description

Adding pagination support on the API side is being handled in #11592

This ticket is about implementing pagination for the shopping tab in the editor using infinite scroll.

We already have a few different infinite scroll implementations in the editor and the dashboard, so ideally we can reuse an existing one.

While this is somewhat blocked by #11592, I think some parts can be worked on already now, and tested with Karma tests (see also #11314 #11590)

## Developer Notes

For working with this locally, make sure to do the following:
- Enable the Shopping Experiment in Stories > Experiments
- Enable WooCommerce Plugin
- In Stories > Settings, make sure `WooCommerce` is selected as your Shopping Provider.

**Comment by spacedmonkey** [comment]
This is going be a little hard. Spofity does not give us the max matching products as part of query result. Meaning, we only know if there is one more page to come. This is different from WP implementation, that gets total pages.

**Comment by swissspidy** [comment]
I feel like we can implement this without knowing the total number of pages. For infinite scroll pagination all we need to know is whether we can fetch some more pages, not the total number of pages.

**Comment by spacedmonkey** [comment]
Agreed, see what I have done here - https://github.com/GoogleForCreators/web-stories-wp/pull/11575/commits/8e999799bd30c107349764a38263d3ad19b86f8c#diff-d63a5db72175c075c392d1a09813775e42ba439585a4a990755fcefaa809947eR216

**Comment by felipebochehin87** [comment]
Scrolling down display more products until you reach the end and see "No more products".
