### ISSUE TITLE
Editor: 'Add animation' quick action button should not be shown on first page

### ISSUE THREAD

**Issue by mflorida** [swissspidy/web-stories-wp#11602]
## Bug Description

Since animations are not allowed on the first page of a story, the 'Add animation' button should not be displayed in the 'quick actions' menu to the upper-right of the page layout area.

## Expected Behaviour

The 'Add animation' button should not be shown on the first page.

## Steps to Reproduce

On the first page of a story, select any element that could potentially be animated on other pages. The 'Add animation' button is shown in the upper-right menu.

## Screenshots

<img width="579" alt="Screen Shot 2022-05-30 at 1 50 20 PM" src="https://user-images.githubusercontent.com/4173034/171047859-d179a3d0-b084-461a-b8d3-7c463032aaf6.png">

## Additional Context

- Plugin Version: Version 1.22.0-alpha.0
- WordPress Version: 6.0
- Operating System: macOS 12.3.1
- Browser: Chrome 102.0.5005.61

**Comment by swissspidy** [comment]
Good catch!

**Comment by felipebochehin87** [comment]
![1st page.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/6be1b777-38eb-44b2-90df-f9535e2ae7ad)
