### ISSUE TITLE
Wrong time zone in the Publish date picker

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#11601]
## Bug Description

Tested with UTC+0/UTC+2/Warsaw set in the WordPress Settings.
It looks like the date picker displays the wrong date/time when there is a mismatch between the WordPress timezone and your OS timezone.

## Expected Behaviour

When I add 1 minute to the publish date, it should schedule the publishing 1 minute into the future (not e.g. 7h and 1min).

## Steps to Reproduce

1. Set WordPress timezone to Warsaw.
2. Set your OS timezone to Tokyo.
3. Create and publish a story.
4. Refresh the story and change the publish date to +1 minute.
5. Check the Dashboard - it will say scheduled in 7 hours (should be in less than 1 min).

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
There's definitely something funky going on.

It's probably related to how the `DateTime`, `DatePicker` and `PublishTime` components use `new Date()` and `Date.now()` to get the current date. This will always get the date in the current browser/OS timezone, not the timezone set in the WordPress.

**Comment by spacedmonkey** [comment]
Related: https://github.com/GoogleForCreators/web-stories-wp/issues/11651

**Comment by spacedmonkey** [comment]
So is the expected solution, to have someway of setting the location? 

This seems like this is the line that needs to change. 

https://github.com/GoogleForCreators/web-stories-wp/blob/918787a8819d6911c15b5f5485a187a97426cb14/packages/wp-story-editor/src/components/documentPane/publish/publishTime.js#L87

**Comment by swissspidy** [comment]
Dates should always be set in the WordPress timezone
