### ISSUE TITLE
Shapes causing 413 errors

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11615]
## Feature Description

Users who make liberal use of shapes have discovered that when attempting to publish, they are presented with a ` 413 Request Entity Too Large error.` 

On further investigation it was discovered that the entity was over 1mb in size, which happens to be the NGINX default value at which this error occurs.

The user was forced to remove a number of shape elements from the story to get it to come under the 1mb size, which resulted in the error no longer occurred and the user was able to successfully publish the story to production https://www.marketwatch.com/visual-stories/musk-bezos-gates-and-other-billionaires-have-lost-200-billion-in-2022-01653664285?mod=visual-stories

Perhaps we should consider the following options:
1. If the user creates a story that is "big" we should warn them
2. Improve the performance of the plugin so that "big" stories don't occur as easily
3. Update the plugin documentation to include this detail to assist users who may experience this in the future.

**Comment by swissspidy** [comment]
It would be better if stories wouldn't end up this big in the first place 🙂 

----

Related:

* #9858 
* #8511
