### ISSUE TITLE
Dashboard: Consolidating the FilterProvider to include Author Filter

### ISSUE THREAD

**Issue by sblinde** [swissspidy/web-stories-wp#11620]
## Feature Description
As part of the feature for Dashboard: Filter by Taxonomy (#11436), our team had to make a larger Filter Provider that held information specific to Taxonomies in order to properly create filters. However, the logic between the Filter by Author work and the Filter by Taxonomy work is separate, in two different places. 

This body of work is to unite the two into the larger FilterProvider, so that as we continue onto more filter work in the future (see: #11586), we have one space that holds the logic for each filter, based on the logic of each type of filter that's needed.

This story will block the work needed to accomplish #11586, as it would be better to improve upon the filter provider the team has built before moving on to adding more filters within the Dashboard space.

This tackles both Code Quality and an Enhancement, supporting further filter work, and improving upon the work delivered by #11436.

## Acceptance Criteria

- Both the Taxonomies filters and the Author filters will exist under one `FilterProvider`
- Adding another filter in the future should be made easier by this work: this work should allow one to extend the filters as needed for future work

## Alternatives Considered

The alternative would be moving forward to add more filters, which would add more separation between filters (which is what exists today with the last body of work to support Filtering by Taxonomies). It would be ideal if we could accomplish this body of tech debt work prior to that work.

**Comment by swissspidy** [comment]
Appreciate you all keeping an eye on code quality 👍 🚀

**Comment by swissspidy** [comment]
Another thing I mentioned at https://github.com/GoogleForCreators/web-stories-wp/pull/11625#discussion_r892222772 is to show the taxonomies & author filters also on the list view

Might be something we can do as part of this ticket as well.

**Comment by mwritter** [comment]
https://user-images.githubusercontent.com/14057928/173854259-6aaf2224-b3db-4c49-a324-bdeda906db05.mp4
Currently we're making a request on every key stroke to search within the 'datalist' - will fix here
