### ISSUE TITLE
Tags & categories assigned in All Stories dashboard does not match the editor document panel

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#11623]
## Bug Description

The tags & categories assigned on the All Stories dashboard do not match when viewing it on the editor document panel. Additionally, if you open a story and update it with tags and categories in the editor, the changes do not apply when exiting and returning to the editor. 

## Expected Behaviour

Tags & categories should be the same on the story on the All Stories dashboard as well as in the editor.

## Steps to Reproduce
1. Navigate to All Stories dashboard > open Quick Edit menu > assign Tags and Categories
2. Navigate to Stories Dashboard > open the story you just assigned Tags and Categories to > See Document panel
3. Note there are some tags and categories unchecked or missing

4. Open story editor > Add new category and assign another tag > Update > Exit story editor > Go back in the editor > Note the changes do not apply

## Screenshots

Here are some screenshots to show what is assigned under All Stories versus what displays in the Editor. There is also a recording below to show the changes not saving.

<img width="1261" alt="Screen Shot 2022-06-02 at 10 25 11 AM" src="https://user-images.githubusercontent.com/66372350/171652319-d35191a3-4439-422a-ba23-e73ba806df51.png">

<img width="1197" alt="Screen Shot 2022-06-02 at 10 25 48 AM" src="https://user-images.githubusercontent.com/66372350/171652342-19c3d4a2-2d93-47a7-9f9f-fa7b266837ed.png">

<img width="666" alt="Screen Shot 2022-06-02 at 10 26 06 AM" src="https://user-images.githubusercontent.com/66372350/171652352-01070afd-fcd6-468e-a443-f88236850e9d.png">

https://user-images.githubusercontent.com/66372350/171652839-a919698e-a76f-4a0a-b792-4bdd0a50a0ae.mov

- Plugin Version: 1.21.1
- WordPress Version: 6.0
- Operating System: macOS 
- Browser: 12.3.1

**Comment by sblinde** [comment]
Thanks for the details.

Trying to replicate this on the `main` branch, I haven't been able to. I wonder if it's around some of the changes around stale story data that were delivered during the last release.

**Comment by sblinde** [comment]
Digging into this further, I think this is likely beyond my team's scope of knowledge.

When I look at the data we get back from stories, I see that `terms` is always each type of term, with a maximum number of ten items in the array. 

Screenshot below is the data we receive (near the bottom, you'll see `wp-term` which only returns as maximum for categories and tags, despite more than ten being assigned to this Story):
<img width="1044" alt="Screen Shot 2022-06-06 at 2 26 49 PM" src="https://user-images.githubusercontent.com/7110244/172223429-17a1a3f6-b0cf-421c-98b5-285c20dcc11e.png">

I went deeper into the code, and realized that the following function that queries for the `storyById` only returns a maximum of ten terms, shown as `wp:term`. 

https://github.com/GoogleForCreators/web-stories-wp/blob/aade27ebe43692e6b6fc7ec2730582f81399781c/packages/wp-story-editor/src/api/story.js#L34-L42

These are the referenced lines that query for the Story data to load. In the example of my machine locally, the path resolves as `/web-stories/v1/web-story/201/`. The data that loads from the endpoint shared there is the data that returns the terms as `embedded?.['wp:term']`, which is subsequently flattened by the `transformStories` function at this line shown below.

https://github.com/GoogleForCreators/web-stories-wp/blob/main/packages/wp-story-editor/src/api/utils/transformStoryResponse.js#L52

Based on this, it sounds like the data returned from the actual endpoint for fetching a story by id is the limitation here. If we only receive a maximum of ten term results, the UI in the editor will only support what it knows about. I don't see anything else built underneath this that limits this functionality.

@swissspidy FYI, happy to chat about this in more detail if this is helpful.

**Comment by swissspidy** [comment]
Thanks for the thorough analysis!

So the embedded terms list (`embedded?.['wp:term']`) from the REST API response (`getStoryById` / `/web-stories/v1/web-story/12345/`) only contains 10 items, but we need more than that.

#11641 does increase the limit to 100, but there is still a limit, so this does not fully solve the issue, just make it less likely to occur. In other words: What if there are 200 terms on a post...?

Ideally, this is solved by using REST API pagination using the `&page=` query argument. See https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/

For this, instead of getting the embedded terms from the story response, we would need to call each terms endpoint (from the list in `_links.['wp:term']`) separately and paginate based on the `X-WP-TotalPages` response header, fetching `/web-stories/v1/web_story_category?post=9315`, ``/web-stories/v1/web_story_category?post=9315&page=2`, `/web-stories/v1/web_story_category?post=9315&page=3` and so on...

Apologies for the somewhat short answer. I am fully back later this week and then we can discuss this in detail.

----

> even if I specify a number (for example, `&number=15`) per WordPress's [developer documentation](https://developer.wordpress.org/reference/classes/wp_term_query/__construct/) on this.

Note that this documentation is for taxonomy/term database queries in WP, not for the REST API.

**Comment by sblinde** [comment]
@swissspidy Thank you for the explanation, much appreciated! And you're totally right: there still is a limit (even if that limit is 100 vs 10, an ideal fix would be more accommodating). Given the impact when ten is a very likely scenario one can run into, I was focused on building a fix for the now, but will be honest that PHP is not a language I'm comfortable with. Let's definitely talk about it when you're back and more available! And thanks again for hopping in here to give some additional context, it's appreciated!

Also yes, you're totally right on that documentation I linked re: database queries. As I dug further yesterday in this, I realized it was not applicable to the situation at hand.

**Comment by swissspidy** [comment]
cc @spacedmonkey - would appreciate your thoughts here, let's discuss this today so that we can then sync with Sam on the right approach.

**Comment by spacedmonkey** [comment]
Instead of using the embedded terms, you can make a request to "http://localhost:8899/wp-json/web-stories/v1/web_story_category?post=115" with per_page of -1. What would get all the terms for the story. 

We could also, just add a limit of 100 items that can be selected in the editor and say that is a hard limit for the editor / post type. I can't personally think of a good reason why you would have more than 100 terms on a single taxonomy per story...

**Comment by spacedmonkey** [comment]
![Screenshot 2022-06-08 at 13 51 22](https://user-images.githubusercontent.com/237508/172620797-c0330681-c060-4191-8c0a-11acc42f42c8.png)

You can also do a length on property in the api response. If more than 100, do something different.

**Comment by spacedmonkey** [comment]
> per_page=-1 is not supported by WordPress for taxonomy terms.

Does it? Even with [fetch-all-middleware.js](https://github.com/WordPress/gutenberg/blob/trunk/packages/api-fetch/src/middlewares/fetch-all-middleware.js).

**Comment by sblinde** [comment]
@spacedmonkey Ooh! I didn't even know we could do this alternatively. That could be the solution there, to get them all. I think it's an easier lift than trying to refactor the way we get stories, which would be a larger lift.

If we're more comfortable with 100 as a limit, that's fine too, but we should note that. Both solutions are certainly better than a limit of 10 (which is pretty low and I would bet many have likely hit that, especially larger organizations)

**Comment by sblinde** [comment]
@swissspidy Based on what I looked at, your suggestions would not solve the issue at hand reported in the ticket. 

The loading of the initial story data utilizes `getStoryById`, and it uses that endpoint linked in my PR. From there, the terms that are fetched are used to pre-select the selected terms (such as tags, categories, etc). 

The only place where this change can be made is there in the PHP file, the alternative being that we would need to refactor the entire way we load stories within the editor to fetch terms additionally and separately and then manually add them as part of the data we utilize.

You can see what I'm referencing here:
https://github.com/GoogleForCreators/web-stories-wp/blob/main/packages/wp-story-editor/src/api/story.js#L34-L42

That's not to say your suggestion isn't a good one, we still would need to tackle other areas that have limits on how many can be fetched, it just wouldn't solve the problem. The TaxonomyProvider, to my understanding, does not hold the logic for taxonomies that are selected initially, but it does add to the initial list (depending on the actions one takes in the UI).

**Comment by swissspidy** [comment]
Ah, right, forgot about that part again.

> the alternative being that we would need to refactor the entire way we load stories within the editor to fetch terms additionally and separately and then manually add them as part of the data we utilize.

Yes, that's essentially what I meant in my previous comment 2 days ago.

Perhaps you could do a brief assessment to see how big of a change that would be?

**Comment by sblinde** [comment]
@swissspidy Will do, I'll see if I can later today or tomorrow and get back to you both in this conversation. Really appreciate the feedback, additional context, and ideas around this!

**Comment by spacedmonkey** [comment]
I think that https://github.com/GoogleForCreators/web-stories-wp/pull/11641 is a good start. It embeds the first 100 terms. I think once we merge that, then in later we could look into counting the number of terms that are assigned for a taxonomy and then loading them in another REST API request, if more than 100.

**Comment by sblinde** [comment]
While I don't think it would be a heavy lift to implement, I do think there would have to be a good amount of tests refactored to accomplish this (if we removed `terms` from the `getStoryById` call to the endpoint and instead did it on the front-end). I'd estimate it somewhere between a 3 and 5 given my own familiarity with the space, and accounting for a good amount of time to fix and change tests associated with where this is huge.

cc: @swissspidy && @spacedmonkey

**Comment by felipebochehin87** [comment]
Tested adding and removing tags, categories and verticals.


https://images.zenhubusercontent.com/235435637/cc0ffe0d-2b4d-4c59-ac80-e9f08930fc2f/2022_06_13_12_17_25.mp4

**Comment by felipebochehin87** [comment]
Limits of categories and tags look good too.

**Comment by swissspidy** [comment]
@sblinde With this now merged, could you perhaps create the follow-up ticket? Thanks in advance!
