### ISSUE TITLE
The right arrow in the page carousel is sometimes hidden and unavailable

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11631]
## Bug Description

If a user has a large enough number of pages in thier story to warrant the presentation of the left and right navigation arrows, sometimes the right arrow is hidden under other app elements and not able to be selected.

In the image below you can see that the right arrow is hidden under the Fit button and cannot be used.

![Screen Shot 2022-06-06 at 1.01.37 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/108cab2c-d26c-48b0-bd7b-957ba2069022)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by mflorida** [comment]
This may be resolved with PR #11737 - the width of the carousel was reduced to accommodate the wider update left and right button groups. The spacing between the thumbnails may need adjusting.

**Comment by miina** [comment]
Closing as not able to repro currently.
