### ISSUE TITLE
Contributors Template creation is not working as expected

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11647]
## Bug Description

As a contributor I am permitted to create templates, however when the template is created, there is no content within the newly created template

## Expected Behaviour

I am not sure if template creation by a contributor is considered acceptable.

## Screenshots

https://images.zenhubusercontent.com/235435637/0e886897-7ce5-49ed-86e4-86d86963cabb/screen_recording_2022_06_07_at_4_05_28_pm.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
This might be more of a WP pod issue actually, due to how caps are handled server-side.

> I am not sure if template creation by a contributor is considered acceptable.

Good question. It ought to be, but maybe we need revisit this. Or at least implement some capability checks in case we ever revisit it.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11662.

1. Logged in as a Contributor
2. Visited Explore Templates
3. Used a template
4. Made changes to the template and saved page as template - elements were displayed successfully
5. Refreshed page, added newly saved page to the template - elements were added successfully
6. Repeated these steps for a brand new story and saved it as a template - elements were added/displayed successfully
