### ISSUE TITLE
Toggle the visibility of layers

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11646]
## Feature Description

Users have indicated that they are looking forward to the ability to enable/disable layer visibility on demand in the editor, similar to how Figma & Photoshop are able to do this.

**Comment by bmattb** [comment]
@gajasinski @aaskedall @swissspidy for your consideration

**Comment by swissspidy** [comment]
Seems reasonable to me. Might help if there's lots of layers on top of each other.

@gajasinski @aaskedall Thoughts?

**Comment by gajasinski** [comment]
Agreed. Do we have any metrics on avg # of layers used? Can help with prioritization

**Comment by swissspidy** [comment]
I don't think we currently track that, unfortunately.

**Comment by gajasinski** [comment]
I would still support the work. @aaskedall ??

**Comment by miina** [comment]
> Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Web-Stories-5e94d3aced449034e1e9b226/issues/GoogleForCreators/web-stories-wp/11646?planning-poker) with Zenhub 

Doesn't allow doing that, perhaps because the points are already assigned? Seems ok to me as is.

**Comment by merapi** [comment]
Designs: https://xwp.slack.com/archives/C01ESBB8ZN1/p1666623419355339

Things to note:
- hidden elements should move with the group
