### ISSUE TITLE
Remove First Page Animations from Templates

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11648]
## Feature Description

Animations on the first page of a story are not supported and we add warnings for them in the editor.

The other day I noticed that our templates still contain animations on the first page though. For users it's kinda confusing to see such warnings for templates that we provide them.

We should remove first page animations from the actual template files, since they don't work.

**To-do**

* Remove first page animations from all templates JSON files. Might be easiest to do this manually or using a small script instead of [modifying every template in the editor](https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/external-template-creation.md).
* Add new test in `packages/templates/src/test/raw.js` to document the expected behavior & prevent regressions

**Comment by sblinde** [comment]
Nice catch!
