### ISSUE TITLE
Respect first day of the week setting

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11651]
## Bug Description

WordPress has a setting for selecting the first day of the week. However, our date picker does not respect that. 

![Screenshot 2022-06-08 at 13 57 33](https://user-images.githubusercontent.com/237508/172622273-35f5731a-cf18-4cc5-b079-f01fda46227c.png)
![Screenshot 2022-06-08 at 13 57 18](https://user-images.githubusercontent.com/237508/172622278-37a32dd7-fd51-40ab-8203-24fd0f0ea30c.png)

See related WP core issue. [#55826](https://core.trac.wordpress.org/ticket/55826).

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by spacedmonkey** [comment]
https://github.com/WordPress/Gutenberg/issues/41078

**Comment by spacedmonkey** [comment]
There is a PR on the gutenberg side - https://github.com/WordPress/gutenberg/pull/41648

**Comment by swissspidy** [comment]
Gutenberg uses a different library for the date picker, so what works for them probably does not work for us.

**Comment by spacedmonkey** [comment]
> Gutenberg uses a different library for the date picker, so what works for them probably does not work for us.

I know that 😉 Just sharing as this might help with our solution. There maybe also be parts of code, we need to consider for our solution.

**Comment by felipebochehin87** [comment]
@swissspidy morning!

While testing this PR (#11732) I noticed that Saturday, Sunday and Monday can be set as 1st days, but Friday can't. Is this something that we need to fix in this PR or can we create a new one for this scenario?

**Comment by swissspidy** [comment]
Nothing we can fix. The calendar we use does not support it.
