### ISSUE TITLE
Design System: only 1 snackbar message shown when adding multiple at once

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#11654]
## Feature Description

PR #11521 prevents users from adding the same product to the same page more than once. However, if the user selects 2 or more products at the same time and tries to paste them, the error message doesn't display all the products that are already added to the page. It only displays the name of the last one that was added. For example:

1. Add 3 products, A, B and C to the page, in this order
2. Use the mouse to select them all
3. CTRL (or command) +C to copy them
4. Click out of the page
5. CTRL (or command) + V to paste them

Message displays "Product C already exists on the page."

Video below.

## Alternatives Considered

To be discussed and defined. A few suggestions:

1. Display the product names in the same message, separated by comma ("Products A and B already exist on the page");

2. Display each product in a separate message ("Product A already exists on the page", "Product B already exists on the page").

## Additional Context

Video:

https://images.zenhubusercontent.com/235435637/6435f328-3b82-41c1-89f2-d2e27ee533ae/2022_06_08_12_27_19.mp4

**Comment by swissspidy** [comment]
This is not necessarily about products. The issue is thst when adding multiple snackbar messages at once, only one is shown. Changing the message text and only showing one is just a workaround and does not address the issue itself.

**Comment by felipebochehin87** [comment]
Looks good in QA, PR #11655.

![dup products.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/a53f6b4d-5134-4fb5-9848-3eb413aed9d7)
