### ISSUE TITLE
Mixed Content Bug For VTT 

### ISSUE THREAD

**Issue by DanielCryptoK** [swissspidy/web-stories-wp#11659]
Hi,

Yet again web stories is broken and think it is related to the below after your last update:

Mixed Content: The page at 'https://bitcoin-casino-no-deposit-bonus.com/web-stories/bitstarz/' was loaded over HTTPS, but requested an insecure resource 'http://bitcoin-casino-no-deposit-bonus.com/wp-content/uploads/2022/05/WC-29.vtt'. This request has been blocked; the content must be served over HTTPS.

https://bitcoin-casino-no-deposit-bonus.com/web-stories/bitstarz/

How do I fix?

**Comment by swissspidy** [comment]
Okay, I can see that there are some log messages when looking at the logs from the AMP Test tool.

However I am unable to reproduce that in an actual browser.

So if there's no actual issue for you when viewing the stories I think you can just ignore those messages.

I am no htaccess expert, so if you have any issues with mixed content despite Really Simple SSL, I would recommend reaching out to their support for help, or a place like StackOverflow.

-----

The only issue I see with your story is that background audio doesn't seem to be loading consistently:

![Screenshot 2022-06-09 at 14 46 11](https://user-images.githubusercontent.com/841956/172851753-92c95f78-641e-4578-89c1-88300a71b933.png)

We'll look into that.

**Comment by DanielCryptoK** [comment]
The background audio along with the subtitles do not work on all of the stories. Thanks for looking into it as really simple ssl support is down they have a remote server is misconfigured with their support email so can not get through to them.

**Comment by DanielCryptoK** [comment]
Hi,

Please can I have an update with regards this problem as causing me a lot of stress. Really simple ssl have come back to me please see below what they say:

Hi Daniel,

Thank you for your reply.

As for the Subtitles not appearing, can you check what the URL to the file in question looks like? It should have a HTTPS url in your case. If it has a HTTP url instead: that would be the cause of the issue, and changing it to an HTTPS File URL should fix it.

Please see the file URL in my screenshot below. Your subtitle/caption file that reports the Mixed Content warning should have a HTTPS:// url.

The "Video can't load" message appears both with and without SSL activated (which I just verified on my testing site), as soon as you add that VTT file as an Audio Caption. This looks unrelated to Really Simple SSL, as the commenter also indicated in your WebStories Github thread that they would look into this.

Hope this helps!
Kind regards,

Jarno Vos
Really Simple SSL Support

I have checked and the VTT files are on https see picture here: https://www.webpagescreenshot.info/#v2=5izOHJJZ2

Could the VTT files error be related to the fact that I deleted the AMP plugin and added the below code to redirect the AMP pages. The only reason I say this is that for that error it says redirection issue in the AMP test under Page Resources that could not be loaded.

<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteCond %{QUERY_STRING} amp [NC]
	RewriteRule (.*) /$1 [R=301,L,QSD]
</IfModule>

Redirection error
XHR
https://bitcoin-casino-no-deposit-bonus.com/wp-content/uploads/2022/05/WC-27.vtt?__amp_source_origin=https%3A%2F%2Fbitcoin-casino-no-deposit-bonus.com

Even when I do not have any voice over and VTT added I still get the below js errors showing in amp test results: See example story here: https://bitcoin-casino-no-deposit-bonus.com/web-stories/betfury-review/

These are the errors showing when you go to test page results on amp test

Powered by AMP ⚡ HTML – Version 2205270638004 https://bitcoin-casino-no-deposit-bonus.com/web-stories/betfury-review/
https://cdn.ampproject.org/v0.mjs:2

Error
00:13.000
Failed to load: [object HTMLVideoElement]​​​
https://cdn.ampproject.org/v0.mjs:2

Error
00:13.000
Uncaught (in promise) Error: Failed to load: [object HTMLVideoElement]​​​at o (https://cdn.ampproject.org/v0.mjs:2:965) at Et.createError (https://cdn.ampproject.org/v0.mjs:2:202974) at https://cdn.ampproject.org/v0.mjs:2:32396 at https://cdn.ampproject.org/v0.mjs:2:32414
https://cdn.ampproject.org/v0.mjs:1

Error
00:13.000
Failed to load: [object HTMLVideoElement]​​​
https://cdn.ampproject.org/v0.mjs:2

Error
00:13.000
Uncaught (in promise) Error: Failed to load: [object HTMLVideoElement]​​​at o (https://cdn.ampproject.org/v0.mjs:2:965) at Et.createError (https://cdn.ampproject.org/v0.mjs:2:202974) at https://cdn.ampproject.org/v0.mjs:2:32396 at https://cdn.ampproject.org/v0.mjs:2:32414
https://cdn.ampproject.org/v0.mjs:1

Warning
00:15.000
The resource https://cdn.ampproject.org/v0/amp-story-1.0.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
https://bitcoin-casino-no-deposit-bonus.com/web-stories/betfury-review/

Obviously it is impossible for me to speak with someone from the AMP test team, are you able to speak with them and find out why these errors not show in console but do show in test??

Also the schema data is not working check the example story that I added and see here https://www.webpagescreenshot.info/#v2=ztD2-Uebz and here https://www.webpagescreenshot.info/#v2=ExgMBoOHJ

Also any idea when it will be possible to add the web stories as a single as been waiting a long time on this now.

I do hope you can help because as you know it has been over 1 year and I have never been able to get your plugin to work correctly.

**Comment by swissspidy** [comment]
Hi Daniel

You're mixing quite a few topics here. Let me try to unpack this a bit and go over them one by one.

> Also the schema data is not working check the example story that I added and see here [webpagescreenshot.info/#v2=ztD2-Uebz](https://www.webpagescreenshot.info/#v2=ztD2-Uebz) and here [webpagescreenshot.info/#v2=ExgMBoOHJ](https://www.webpagescreenshot.info/#v2=ExgMBoOHJ)

You appear to be using the [Schema & Structured Data for WP & AMP](https://wordpress.org/plugins/schema-and-structured-data-for-wp/) plugin, which disables schema output from Yoast SEO. The plugin does not appear to be compatible with Web Stories. You need to reach out to their support for help with that (or disable the plugin).

It's not an issue with the Web Stories plugin.

> These are the errors showing when you go to test page results on amp test

Thank you. You've shared these logs before.

As I said before, I don't know why they only appear there but not when viewing the actual story in the browser.

But if everything else is fine, you can really **just ignore them**.

> Also any idea when it will be possible to add the web stories as a single as been waiting a long time on this now.

I don't know what you mean by that. Can you elaborate?

**Comment by DanielCryptoK** [comment]
Did you read this part of the post from Really Simple SSL who stated:

The "Video can't load" message appears both with and without SSL activated (which I just verified on my testing site), as soon as you add that VTT file as an Audio Caption. This looks unrelated to Really Simple SSL, as the commenter also indicated in your WebStories Github thread that they would look into this.

**Comment by swissspidy** [comment]
As I told you before a few comments above, we've noticed that background audio doesn't seem to be loading consistently and that we will look into it.

**Comment by DanielCryptoK** [comment]
Sorry for being impatient its just that my web stories make zero sense without audio and subtitles working, which is damaging my business.

**Comment by DanielCryptoK** [comment]
And I meant when is the ability to add a web story as a single post via the plugin going to be added as we were using a separate plugin to do this but we had to delete it due to a conflict and there was only one plugin that gave this ability. Hope that makes sense. Removing the single web stories greatly damaged our website as google bot was kind to use and combined our review pages with the relevant web stories under them in search results but now that has gone.

**Comment by DanielCryptoK** [comment]
yes, sorry I have Dyslexia so find things hard to explain sometimes.

**Comment by DanielCryptoK** [comment]
Just updated the web stories plugin and zero change as the voice over not playing. I really dont think I am ever going to get the web stories working. https://bitcoin-casino-no-deposit-bonus.com/web-stories/bitstarz/

**Comment by swissspidy** [comment]
Try re-saving your story to make sure everything is updated
