### ISSUE TITLE
Dashboard: Status filter + author filter not working well together

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11668]
## Bug Description

If you have a story status filter set and then you filter by author, if that author does not have a anything in that status, then story status should reset to all or something. 

See video. 

## Steps to Reproduce

1. Open dashboard. 
2. Filter by pending. 
3. Filter by author ( author must not have pending story ). 
4. See status filter not highlighted. 

## Screenshots

https://user-images.githubusercontent.com/237508/173048393-24a5300f-5809-4fb0-bb48-ac71f7d8012b.mov

## Additional Context

- Plugin Version: 1.22.0
- WordPress Version: 6.0
- Operating System:
- Browser:

**Comment by sblinde** [comment]
Great find! We added this to the epic for filtering improvements / enhancements.

**Comment by sblinde** [comment]
Linking this reported issue to https://github.com/GoogleForCreators/web-stories-wp/issues/11789, and removing estimate as this will be an incident report that should be resolved with that greater work.

**Comment by mwritter** [comment]
@spacedmonkey @swissspidy  @sblinde - Im currently addressing this issue in #11789 and Im working on implementing a solution but wanted to get some feedback on how to handle this issue.

> if that author does not have anything in that status, then story status should reset to all or something.

🤔 The 'status filter' updates every time the user changes any other filter, so once the other filter updates we make a call to the backend for the stories, which gives us the 'status counts' for the given set of filters.  So once we found that there are no stories for the given set of filters we would have to make a second call to the backend to 'reset' the status filter.  Im not sure if we want to do that.  Any insight on a better way to 'reset' would be greatly appreciated if we do wanna go do that path.

I do have a working solution that gives a better visual queue to the user though to let them know they're filtering by a status that has no results, any feedback on this implementation or suggestion would be great.

https://user-images.githubusercontent.com/14057928/176257578-361f1e86-620f-4845-bf86-54775e38209f.mov

**Comment by sblinde** [comment]
Agreed w/ @swissspidy as well!
