### ISSUE TITLE
Dashboard: Add No Results Message To Filters

### ISSUE THREAD

**Issue by sblinde** [swissspidy/web-stories-wp#11664]
## Feature Description

In the case in which a filter is used and no results are found, the UI should give feedback to the user that there were no results found for the filter. 

## Acceptance Criteria

- When no results are found for an active filter search on the Dashboard, the UI should indicate `Sorry, we couldn't find any results.`

## Additional Context

This feedback was a part of https://github.com/GoogleForCreators/web-stories-wp/pull/11625#issuecomment-1150104862

Additionally, it may be easier to accomplish this logic once #11620 has been completed.

**Comment by felipebochehin87** [comment]
![no results text.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/212dbbc2-ea81-4b31-a22c-4c5642381a36)

![no results filters.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/2118fb4a-a30d-4ea6-b023-6d149f8e4591)
