### ISSUE TITLE
Dashboard: Filtering Improvements and Enhancements

### ISSUE THREAD

**Issue by sblinde** [swissspidy/web-stories-wp#11663]
## Summary

This Epic holds all of the Dashboard: Filter improvements and additions as subsequent work related to #11287.

As part of adding a filter for taxonomies to the Dashboard, we want to further improve, extend, and enhance the filters.

**Comment by mwritter** [comment]
@sblinde - just noticed while working that we are tracking filters, keyword, sort and order by when searching stories with a keyword in `useStoryView.js`
