### ISSUE TITLE
Templates: Make use of layer naming/grouping/locking

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11697]
## Feature Description

With the new layers naming/grouping/locking features there's an opportunity to improve UX when using them.

Here's an example of the "All About Cars" template, where grouping layers would make it way more user friendly:

<img width="811" alt="Screenshot 2022-06-14 at 00 46 49" src="https://user-images.githubusercontent.com/841956/173459996-7d9e179e-a7b1-4dc7-a47f-039b1716f446.png">

At first glance it seems like every template page with more than 10 layers on it is a good candidate for manual review and potentially grouping the layers.

Then, the groups could have more meaningful names to make them easier to distinguish.

**Comment by swissspidy** [comment]
cc @sblinde @aaskedall since this was mentioned in today's demo call

**Comment by felipebochehin87** [comment]
Tested using PR #11924.

1. Used templates
2. Selected all or some elements and grouped them
3. Renamed
4. Locked
5. Changed their position (couldn't do it while locked)
6. Added multiple groups, renamed, ungrouped, changed their position in the layer panel
