### ISSUE TITLE
Shopping: Reset pulse animation when adding products

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11705]
## Feature Description

From bug bash:

> When you add multiple products, they pulse, but out of phase and it’s really bugging me that it is out of phase!

We might be able to solve this by passing the number of sibling elements as a prop to `<Display>` in `packages/story-editor/src/components/canvas/displayElement.js` and then in `ProductDisplay` use that as the `key` prop on `ShoppingTagDot` to force React to re-render all product dots when the number of products changes. This will cause the animations to restart.

**Comment by felipebochehin87** [comment]
I still see them pulsing out of sync. If I add 6 products, they will pulse in 3 different times (2 products each time). If we add 2 products, the sync is fine, but if we add 3 or more, it's not.

https://images.zenhubusercontent.com/235435637/c173728c-925f-49c3-a6ad-ac6e7b90af32/2022_06_21_09_34_58.mp4

**Comment by swissspidy** [comment]
@felipebochehin87 looks like the PR didn't properly build. Please test again in like 30mins or so.

**Comment by felipebochehin87** [comment]
Approved. Tested in #11728.
