### ISSUE TITLE
Link preview tooltip has broken tail

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11701]
## Steps to Reproduce

1. Add a new element
2. Add a link
3. Hover over the element on the page
4. See broken tooltip tail

## Screenshots

<img width="284" alt="Screenshot 2022-06-14 at 18 41 53" src="https://user-images.githubusercontent.com/841956/173631272-4e6ba077-3d7a-4eed-9756-53d2adc96729.png">

## Additional Context

- Plugin Version: 1.22.0-alpha
- WordPress Version: 6.0
- Operating System: macOS
- Browser: Chrome v102

**Comment by mflorida** [comment]
Has the tooltip for this always had a tail? As a fix for many of the tooltips rendering with tails, the `hasTail` prop was added as a default, requiring opting out of tails, rather than opting in. A 'tooltip' usually _does_ have a tail, so setting that as the default made sense.

**Comment by swissspidy** [comment]
Great question!

A quick check in version 1.20.0 reveals that it did not have a tail before:

<img width="340" alt="Screenshot 2022-06-21 at 22 11 01" src="https://user-images.githubusercontent.com/841956/174888879-9cb97929-903d-4906-8b80-a4eff280622b.png">

So I guess we could remove it again for this one.

Though it's odd that it's broken with a tail 🤔

**Comment by mflorida** [comment]
Likely some conflicting positioning values. Easy fix to remove the tail. 🙂

**Comment by swissspidy** [comment]
Duplicate of #12834
