### ISSUE TITLE
Shopping: Support drag & drop from library

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11708]
## Feature Description

For consistency it would be nice to eventually support dragging products from the library to the canvas.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11913. In Safari, Chrome and Firefox. Author, Editor, Contributor.

1. Created new story
2. Dragger product to canvas (clicking on the image and dragging it) - OK
3. Tried to drag the same product again - not allowed - OK
4. Added 6 products and tried to drag the 7th - not allowed - OK
