### ISSUE TITLE
Layer Grouping: Better default and duplicate naming

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#11714]
## Feature Description

From the Bug Bash:
[Matt] Should each new group have the name ‘Group 1’?
[Mark] Regarding the above comment, is it possible to increment the default group name? ‘Group 1’, ‘Group 2’, ‘Group 3’, etc.? That raises the question: how would you handle a user changing the default name - renaming ‘Group 2’ to ‘Main text’ - would the next default name be ‘Group 2’ or ‘Group X’?

We need to improve our [function for generating the group name](https://github.com/GoogleForCreators/web-stories-wp/blob/add/11566-layer-intergration-lng/packages/story-editor/src/utils/generateGroupName.js).

Test cases:
The first group created: `Group 1`.
The second group created: `Group 2`.
The second group renamed to `Group Two`.
The third group created: `Group 2` - because `2` is now the next available number.
The first group duplicated: `Group 1 Copy`, again: `Group 1 Copy Copy`, again: `Group 1 Copy Copy Copy` - we always add ` Copy` suffix to the group name - this should be already implemented.

Ideally, we want to support group names in multiple languages (`Group 1`, `Grupa 1` etc), so we will look for a pattern that will have a localized word `Group` then space and ends with a number (so both `Group ` and ` Copy` part needs to be localized).

**Comment by timarney** [comment]
Added code + tests

See: https://github.com/GoogleForCreators/web-stories-wp/pull/11676#pullrequestreview-1008939701

**Comment by merapi** [comment]
It is already merged into the integration branch and will be QA'd on Monday (works as expected).

**Comment by felipebochehin87** [comment]
Group names are not adding "copy" to it, we have multiple groups with the same name.

![group.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/91c95553-12d1-45b0-8ed1-2c4366f2563d)
