### ISSUE TITLE
Layers - Collapse via layers menu icon is not working on Windows/Chrome

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11718]
## Bug Description

Originally reported by @mwritter 

Collapsing Groups in the Layers menu by clicking the icon is not working.
This was tested on Windows, Chrome.
At the same time other things were also broken:
- double click to rename the layer
- double click to enter the image edit mode

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
This seems to be an issue when using a mouse -- drag event handling is initiated instead of clicking. Doesn't happen with touchpad for me.
