### ISSUE TITLE
Layer Grouping: Missing icons in Safari

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#11713]
## Bug Description

[Barklund on Safari] There’s no chevron nor group icon in Safari.

We can also try to enlarge the clickable area of the arrow so it will be easier to hit, maybe make it full height and expand it to the left (remove the padding from the outer element and put it on the arrow icon?).

## Screenshots

![image](https://user-images.githubusercontent.com/21036224/173817273-fc8a3c95-ad69-434e-8143-9b7a6d3f0126.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by merapi** [comment]
It is already merged to the integration branch, will be QA'd on Monday (but I can already see that it's working in Safari).

**Comment by felipebochehin87** [comment]
Icons displayed in Safari. PR #11676.
