### ISSUE TITLE
Shopping: Add right click menu for products

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11711]
## Feature Description

Right now there's no right click menu defined for products (in `packages/story-editor/src/components/canvas/rightClickMenu.js`). So when you try to right click on a product you'll actually see the menu for the page underneath it.

It would be useful to add this for products so you can easily send products to the front etc.

I'd assume initially the list of menu items will be identical to the one for stickers:

<img width="230" alt="Screenshot 2022-06-15 at 00 26 56" src="https://user-images.githubusercontent.com/841956/173699626-82db73e1-2df5-49cd-9a28-16a21ad199a5.png">

**Comment by felipebochehin87** [comment]
Right-click and all its options work for products now.
