### ISSUE TITLE
Dashboard - Loading spinner is presented at end of results

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11716]
## Bug Description

On the dashboard, selecting "Created By" as a filter and scrolling to the end of the results, the loading spinner is presented, implying that more results are forthcoming, however that's not the case

## Screenshots
![Screen Shot 2022-06-15 at 9.12.36 AM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/003bc56e-6d44-4aac-993e-c7ad75c64f94)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by mwritter** [comment]
It seems like this issues may be resolved by #11736 
Noticed while working on this:
![image](https://user-images.githubusercontent.com/14057928/175561098-6a997a2a-ccbb-4c04-babd-ff590063d8a3.png)
If the user scrolls and the 'infinite scroll' functionality is triggered (user gets to the bottom of the page and there are more stories that can be loaded) and more stories are loaded and the user now attempts to 'filter' it is possible that they can receive  a http status code `400`.  This ticket will address that issue.
