### ISSUE TITLE
Lasso Selection: Group elements

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#11720]
## Bug Description

[Matt] Using ‘lasso’ (click and drag) to select an element can select an individual element in the group. Is this correct functionality or should the whole group be selected?

Marcin: It's a bug, maybe it should work with Alt/Option like that.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Now we cannot click on an individual item of the group. When we click on the group, no matter where, the whole group is selected.
