### ISSUE TITLE
I18N: Date picker does not respect language settings

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11734]
## Bug Description

When setting WordPress to another language, the date picker does not respect the langauge WordPress is set on. 

## Steps to Reproduce

1. Go to settings > general.
1. Set language to Spanish.
1. Go to story editor.
1. Go to document panel.
1. Change date of story.
1. Set translated date picker.

## Screenshots
<img width="1013" alt="Screenshot 2022-06-17 at 12 54 36" src="https://user-images.githubusercontent.com/237508/174298243-ea181bdd-d4c7-473a-9cd6-d09ab9d4128c.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by spacedmonkey** [comment]
Created a simple workaround for this issue. See https://github.com/GoogleForCreators/web-stories-wp/pull/11733

**Comment by swissspidy** [comment]
#11745 is an alternative approach, as previously discussed. PTAL

Also opened https://github.com/wojtekmaj/react-calendar/issues/620 since not everything can be localizad that way yet.

**Comment by swissspidy** [comment]
Yes. The screenshot on that PR is an example from when I used the Romansh locale in WordPress. Works out of the box.
