### ISSUE TITLE
Improving styled-components class names for debugging

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11749]
## Task Description

Re-sharing feedback from https://github.com/GoogleForCreators/web-stories-wp/pull/11737#discussion_r901929974:

> I understand and agree with your point about consistency. This may be more of a concern related to the patterns required to use Styled Components than anything specific to this project.
> 
> A lot of the classNames generated by Styled Components can be redundant and hard to track up the component tree. For example, classNames like `components__Container-sc-xxxxxx` and `components__CardWrapper-sc-xxxxxx` are generic and lose meaning because they're repeatedly redefined in components to accommodate the patterns required for composition using the Styled Components library.
> 
> Going up the component tree offers a little context, but navigating the codebase to find specific instances of general-use components isn't obvious (maybe just to developers new to the codebase and patterns used, myself included).

### Additional Context

Related links:

https://styled-components.com/docs/tooling#better-debugging

**Comment by barklund** [comment]
> `"meaninglessFileNames": ["index", "styles"]`

This looks like a great option to use. We sometimes have our S-C components in a single file named `components.js` or `styles.js`, so this would make their debuggable names more traceable.

**Comment by mflorida** [comment]
Using meaningful classNames on child components could eliminate layers of wrapping and prop drilling for styling when state changes on one of its ancestors.

**Comment by spacedmonkey** [comment]
What is the needed for this ticket?

**Comment by swissspidy** [comment]
Updating [our Babel config](https://github.com/GoogleForCreators/web-stories-wp/blob/91ded8a05f2d22dccaadc2b21a2fd9b906d2bc03/babel.config.cjs#L49):

To this:

```js
{
  "plugins": [
    [
      "babel-plugin-styled-components",
      {
        "meaninglessFileNames": ["index", "styles", "components"]
      }
    ]
  ]
}
```

**Comment by spacedmonkey** [comment]
I updated the babel config and seeing see any change in markup / class.
