### ISSUE TITLE
Story editor CPU utilization

### ISSUE THREAD

**Issue by alcarazzam** [swissspidy/web-stories-wp#11765]
## Bug Description

The CPU utilization goes to 100% (one core) on Chrome using a minimal example of the default visual story editor. I can only reproduce the issue on Chrome, Firefox works fine. After profiling the code, I found that the issue is related to blurhash.

## Expected Behaviour

No CPU utilization.

## Steps to Reproduce

1. Clone the https://github.com/m-alzam/test-story-editor repository (minimal example based on the [Getting Started](https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/third-party-integration/story-editor/getting-started.md) guide)
2. Run `npm i` & `npm start`
3. Open the webpage on Chrome and see the bug

## Additional Context

- Operating System: Arch Linux
- Browser: Chrome 102.0.5005.115 (Firefox 101.0.1)

**Comment by swissspidy** [comment]
Thanks a lot for your report and setting up a repo for testing as well. Much appreciated!

Could you perhaps share some more details about the profiling you did, perhaps with some screenshots?

The only thing I see when running the editor from your repo are some bundle size warnings. No excessive CPU or memory usage.

BlurHash generation is supposed to only kick in when adding new media items and when a media item does not have a BlurHash already.

Possibly related: #10133.

**Comment by m-alzam** [comment]
I used the DevTools' Performance tool. Here's the profile I generated: [Profile-20220622T135758.zip](https://github.com/GoogleForCreators/web-stories-wp/files/8957327/Profile-20220622T135758.zip) (unzip to load on Chrome). Here's a screen recording of the issue (I added source maps to the repo):

<details><summary>Video</summary>

https://user-images.githubusercontent.com/47950933/175024954-c8063051-f658-4f29-b6ed-783ac643f3ba.mp4

</details>

Let me know if you need any additional details.

**Comment by swissspidy** [comment]
Thanks, that's helpful!

Looks like the BlurHash web worker was needlessly responding to other messages it received (e.g. from webpack or React dev tools). We'll fix this in #11783
