### ISSUE TITLE
Dashboard: Add All Filters to List View

### ISSUE THREAD

**Issue by sblinde** [swissspidy/web-stories-wp#11767]
## Feature Description

As a part of our Filters improvement and enhancement work, we should have the filters that are on the grid view of the Dashboard also be visible in the List view.

This work was originally scoped to part of #11665, but was separated to accommodate UX resourcing needs.

## Acceptance Criteria

- All filters that exist within the Dashboard Grid View should also exist as filters for the list view of the Dashboard
- This should be built in a way that adding filters in the future should work in both the List and Grid views of the Dashboard.

## Additional Context

This feedback was requested as a part of https://github.com/GoogleForCreators/web-stories-wp/pull/11625#discussion_r892222772

It may be easier to accomplish this after the core work is done with #11620
This work was originally scoped to part of #11665, but was separated to accommodate UX resourcing needs.

**Comment by mwritter** [comment]
Notice while working on this
@swissspidy - It seems these filters work just fine 'as is' on both the list view and grid view, not sure exactly why they were intentionally excluded.  The only thing I noticed is when switching to the 'list view' we are intentionally changing the 'sort' to ascending which can cause the stories to be re fetched in a different order when toggling to the 'list view' - the code was modified here: https://github.com/GoogleForCreators/web-stories-wp/commit/e651108c5400c4d8dbc5a034ac0bde8d2fceb362#:~:text=%5D)%3B-,const%20toggleViewStyle%20%3D%20useCallback(()%20%3D%3E%20%7B,-const%20newViewStyle%20%3D but I not quite sure what the underlying intent is so I dont wan't to remove this logic if its needed.

**Comment by swissspidy** [comment]
Interesting. That's quite confusing 🤔 

That whole logic seems to be suuper old. Even in #1647 it was not introduced, just moved around.

I don't see why we would want to change the sort direction when switching between list view and grid view though...

It should be fine to create a ticket to remove this special logic.

**Comment by felipebochehin87** [comment]
PR #11769 - filters displayed and working as expected in both views (grid and list). The change sort direction when switching between list view and grid view will be fixed in another ticket.
