### ISSUE TITLE
Editor: Elements in text style floating menu shift based on width of selected font name

### ISSUE THREAD

**Issue by mflorida** [swissspidy/web-stories-wp#11779]
## Bug Description

Widths of elements in the text style floating menu change (seemingly based on the width of the selected font name).

Also, the font menu becomes very difficult to use when a font with a short name is selected.

## Expected Behaviour

These elements should remain in-place and the font menu should remain readable.

## Steps to Reproduce

Click a text element on the canvas to bring up the text style menu. Change the font. Menu elements shift and the font menu width changes.

## Screenshots

https://user-images.githubusercontent.com/4173034/175104632-eca22d7d-1e37-4981-9f98-85e7d0ace548.mov

## Additional Context

- Plugin Version:  1.23.0-alpha.0
- WordPress Version: 6.0
- Operating System: macOS
- Browser: Chrome 102.0.5005.115

**Comment by felipebochehin87** [comment]
@mflorida @sblinde I still see the issue with the More button

https://images.zenhubusercontent.com/235435637/3f9eb91c-08d6-47c8-ac84-43c4d6cccbbe/2022_06_30_09_44_29.mp4

**Comment by sblinde** [comment]
@felipebochehin87 I think I see what might have happened here. Based on my time (east coast US), we marked this in ready for QA, but the automation didn't make a build until yesterday around 12pm, which was after you went to QA it. I think you should see the changes now if you give it another chance. I couldn't replicate seeing what you could locally.

Sorry about the timing with that, not sure why that happened!

![Screen Shot 2022-07-01 at 12 52 52 PM](https://user-images.githubusercontent.com/7110244/176937569-cff8cd0a-b01f-4f59-b433-82d0e31dfd97.png)

**Comment by felipebochehin87** [comment]
Thanks for explaining, @sblinde . Looks good now!

**Comment by sblinde** [comment]
@felipebochehin87 Thanks! And thanks for checking it again, we appreciate it!
