### ISSUE TITLE
Stories are cascaded on page load

### ISSUE THREAD

**Issue by pirmax** [swissspidy/web-stories-wp#11778]
## Bug Description

When I load the page, stories are in cascade. When I move the mouse, stories are correctly disposed.

## Expected Behaviour

I want stories are correctly disposed.

## Steps to Reproduce

Fresh installation with WordPress 6.0 with just the the last version of Web Stories plugin (1.22.0).

## Screenshots

https://user-images.githubusercontent.com/1739235/175093450-0ed5482b-caee-4ac6-bc81-856cdd4f00b1.mp4

## Additional Context

- Plugin Version: 1.22.0
- WordPress Version: 6.0
- Operating System: MacOS
- Browser: Safari / Chrome

**Comment by swissspidy** [comment]
Thanks for your report!

This looks like something we can easily improve. We'll look into it!

**Comment by timarney** [comment]
Looking into this looks like there's a bunch of small things going on causing the issue(s).

1) On a throttled or slow connection the initial list styling doesn't match the direction of the end result

<img width="369" alt="no-flex" src="https://user-images.githubusercontent.com/62242/176796713-9d1f5826-bdce-46a9-bf0e-d3131f13ad1f.png">


2) Adding `display:flex` could be a quick win to make the render a little better

<img width="940" alt="with-flex-box" src="https://user-images.githubusercontent.com/62242/176796895-5be07d14-d5c9-41fe-9a0a-8fd22597c403.png">

Fully rendered for my test the result looks like

<img width="697" alt="rendered" src="https://user-images.githubusercontent.com/62242/176796953-2401c98a-2eaa-4f97-ba80-650f50f8291d.png">

3) There is a glider-track wrapping div that gets added by JS (once it loads) --- this is causing issues as the markup prior to the JS executing ends up being different vs the initial render

 That could be removed via skipTrack -- but various JS adjustments likely would need to be made to get things to work  
<img width="400" alt="skip-track" src="https://user-images.githubusercontent.com/62242/176797094-8c5ebd6e-d4ee-4dd4-bdba-cbf0a53f83d3.png">

With that wrapping div 


![wrapping-div](https://user-images.githubusercontent.com/62242/176797214-37ba59c9-70d0-4759-8634-c54a5a884988.gif)

**Comment by swissspidy** [comment]
Yeah I was also thinking of doing `display: flex` on the container until Glider has loaded. But so that we  do not have to change the JS options at all.

Something like:

```css
.web-stories-list.is-carousel.is-view-type-carousel .web-stories-list__carousel:not(.glider) {
  display: flex;
  overflow-y: scroll;
}
```

That leaves us with the minor layout shift afterwards when the height of the tracks changes, but I think that's negligible for now and also a bit more tricky to do.

Better to focus on that in something like #8439
