### ISSUE TITLE
Hotlinking: Allow Link icon to be hotlinked 

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11777]
## Feature Description

Allow Link icon to be hotlinked.

**Comment by felipebochehin87** [comment]
![icon 01.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/52cff026-f189-461f-9e7c-7cce85979d44)

![icon 02.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/b84f4268-eeac-4c71-8a3a-c9d8e7927291)

![icon 03.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/0499c9ce-d75d-43bf-9722-fefc755d7cf5)

![icon 04.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/f5320cb7-869e-49a3-82e5-c97df500e217)

![icon 05.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/63851398-42c4-434b-bc7a-5f4c1558a0f8)
