### ISSUE TITLE
Dashboard: Stories resorted when switching from grid view to list view

### ISSUE THREAD

**Issue by mwritter** [swissspidy/web-stories-wp#11780]
## Bug Description

On the Dashboard, when switching from the stories 'grid view' to 'list view' the stories sort is always set to ascending, which is causing a re fetch of the stories in some cases.

## Expected Behaviour

The stories should not be 're fetched' or 're sorted' when changing between the Dashboard grid view and list view.

## Steps to Reproduce

1. Go to the Dashboard
2. Click the 'Switch to List View' toggle
3. Click the 'Switch to Grid View' toggle
- Notice no 're fetch' no 're sort'
4.  Click the 'Switch to List View' toggle
5. Sort the stories descending by any column by clicking the column name
6. Click the 'Switch to Grid View' toggle
- Notice no 're fetch' or 're sort'
7.  Click the 'Switch to List View' toggle
- Notice a 're fetch' and 're sort'.  See clip below.

## Screenshots

https://images.zenhubusercontent.com/235435637/da306c2a-e205-4a36-8575-1553823318a7/2022_06_22_14_18_51.mp4
## Additional Context
Found while working on #11767.
https://github.com/GoogleForCreators/web-stories-wp/issues/11767#issuecomment-1162380467

The issue is caused in `useStoryView.js` by the `toggleViewStyle` function.  For some reason we are intentionally setting the story sort to ascending.  The intent is not known and needs to be removed to eliminate re fetching and re sorting the stories.

- Plugin Version: 1.22.0-alpha.0
- WordPress Version: Version: 6.0
- Operating System: Windows 10
- Browser: Chrome 102.0.5005.115

**Comment by sblinde** [comment]
@mwritter Awesome, thanks!
