### ISSUE TITLE
Editor: Add Semantic Headings to the Editor Sidebar

### ISSUE THREAD

**Issue by sblinde** [swissspidy/web-stories-wp#11788]
## Feature Description

This feature will allow a user to select the text within a page and see and change the text element within the sidebar.

Many thanks to @swissspidy for the implementation idea, and to @aaskedall for the UX guidance.

## Acceptance Criteria

- This should be under a new experimental feature flag.
  -  The semantic headings experiment flag is on the branch titled: `feature/11788-experiment-semantic-headings`... Please branch off of this when working on this feature.
  - For an example of how to use it with a feature, see this PR: https://github.com/GoogleForCreators/web-stories-wp/pull/11626/files
- Within the Accessibility area of the Editor when text is selected, there should be a new Dropdown
- This dropdown should be titled "Heading Level" and should show the following properties:
	- `Automatic (xyz)` (stored as `auto`)
	- `Heading 1` (stored as `h1`)
	- `Heading 2` (stored as `h2`)
	- `Heading 3` (stored as `h3`)
	- `Paragraph` (stored as `p`)
- When the dropdown item is changed to another option in the dropdown, it should update the text element's `tagName property` 

Example of implementation from @swissspidy (approved by @aaskedall):
![Screenshot 2022-05-30 at 16 19 17](https://user-images.githubusercontent.com/841956/171011226-89837c67-d701-4fc7-af29-7566fdfcae9d.png)

## Developer Notes

Notes from @swissspidy  on implementation:
`xyz` is replaced with whatever `getTextElementTagNames()` returns for the element.

When changing this option, the text element's `tagName` property is updated.

`getTextElementTagNames()` is updated to take this `tagName` property into account.

Below the dropdown we can add a helper text `<a>Learn more</a> about using headings in Web Stories.`, where we can link to the docs

## Alternatives Considered

In addition to this space, this functionality will also be accomplished within a right-click menu on the text element.

**Comment by sblinde** [comment]
@swissspidy A question:

I understand that `Automatic (tag name)` refers to when the `getTextElementTagNames` has chosen, based on certain criteria within that function ,what the tag name is defined as.... but if a user changes it, what exactly defines a tag name as "automatically" set vs. set by the user? I don't think there's any way, the way the implementation is today, for us to know whether it was automatically set OR user set manually. 

Tell me if I'm thinking of this right. What we might be able to do here: show the current tag selected (which I have working now, so "Heading 1" should be correct, and if two different elements are selected, we can show "Mixed" as we do in other spaces), and allow a user to set a new one (which I'm working on now), but either doesn't have the knowledge of whether a tag was automatically selected or manual beyond that.

**Comment by swissspidy** [comment]
Disclaimer: It's been a while since I wrote the original ticket, so my memory is a bit fuzzy off the top of my head. Maybe easiest to discuss in a quick call to clear up confusion.

> I don't think there's any way, the way the implementation is today, for us to know whether it was automatically set OR user set manually.

I was originally thinking something along these lines.

The chosen heading tag is stored on the element's `tagName` property. By default it is `'auto'` (or `null` I guess for older stories). So if it's `auto`, we know that whatever we get was set automatically.

So if we have text elements like this:


```js
[
  {
    id: 123,
    tagName: 'auto',
    // ...
  },
  {
    id: 456,
    tagName: 'h1',
    // ...
  },
  {
    id: 789,
    tagName: 'h2',
    // ...
  },
]
```

And then you call `getTextElementTagNames()` on them, you'll get:

```
{
  123: 'h2' // or something else, depending on its properties
  456: 'h1',
  789: 'h2',
}

Now, since 'h2' ≠ 'auto' we know that the tag name for element 123 was chosen automatically.

Does that make sense?

----

Aside:

I think the `hasH1` check in `getTextElementTagNames` needs to be changed to this, now that we allow customizing the tag name:

```js
const hasH1 =
  Array.from(tagNamesMap.values()).includes('h1') ||
  elements.find(({ tagName }) => tagName !== 'h1');
```

----

If none of that works or it's too complicated or whatever, we can always keep it simple for now and just say `Automatic`, then we don't need to know whether it was set automatically/manually. Would that help?

**Comment by sblinde** [comment]
@swissspidy Thanks so much for the awesome writeup. I think the automatic part you've explained makes sense. I haven't been able to replicate seeing `auto`, but I think I can write in support for it regardless. The other use cases (h1, h2, h3, paragraph) are all things I can easily replicate without problem.

I think the biggest thing I'm running across is making sure the change in the `tagName` is saved and preserved, especially since it doesn't seem like it's a part of the element's data. I think we could probably use a conversation about that at some point this week to figure that part out once I dig in a bit further, but making some good progress so far.

**Comment by sblinde** [comment]
Re-estimating this work to a 5. The right-click menu for supporting semantic headings should be easier once this initial work is done, but with what I've written so far, plus tests + QA, this is more of a `5` pointer than a `3`.

**Comment by swissspidy** [comment]
> I think the automatic part you've explained makes sense. I haven't been able to replicate seeing `auto`
> [...] since it doesn't seem like it's a part of the element's data

It's something new we have to add with this feature 🙂  When you select e.g. "Heading 2" in the dropdown, it should set the element's `tagName` property to `'h2'`. And if you then go back to "Automatic", it should set the property to `'auto'`.

We can treat an absent value as `'auto'`. The property is absent for example when you open an older pre-existing story.

LMK if I am missing something.

**Comment by sblinde** [comment]
> > I think the automatic part you've explained makes sense. I haven't been able to replicate seeing `auto`
> > [...] since it doesn't seem like it's a part of the element's data
> 
> It's something new we have to add with this feature 🙂 When you select e.g. "Heading 2" in the dropdown, it should set the element's `tagName` property to `'h2'`. And if you then go back to "Automatic", it should set the property to `'auto'`.
> 
> We can treat an absent value as `'auto'`. The property is absent for example when you open an older pre-existing story.
> 
> LMK if I am missing something.

Totally, that part makes sense to me, and I've been able to accomplish such in component state (not only updating the tag name, but having the dropdown reflect the change). As well as support for `auto` there. However, I think the part of it I'm missing is actually changing the tag name beyond that component state.

So there's a file where there's logic done to add semantic headings, and a function is a part of this to change the tag name. See here: https://github.com/GoogleForCreators/web-stories-wp/blob/feature/11788-semantic-headings-editor-sidebar/includes/AMP/Traits/Sanitization_Utils.php

Seems like the file I linked above mimics the logic seen in this file, but that this file for `getTextElementTagNames` doesn't actually change anything, it just creates a map that can be used in other spaces in the application with each element mapped, and you could utilize this to get back the selected elements with an appropriate tag name (which is what I've done thus far): https://github.com/GoogleForCreators/web-stories-wp/blob/feature/11788-semantic-headings-editor-sidebar/packages/output/src/utils/getTextElementTagNames.js (note that I made two small changes to it in my branch, just supporting if a tag name has been already set, and passing a tag name if we choose to do so).

In order to support the idea of us updating the name of a tag, we need it to be beyond the component state, so that it's saved as part of the published data of the selected element. But I don't see that we have anything tied to any utility to do so: it seems like the `getTextElementTagNames.js` serves for front end logic, but that the work in `Santization_Utils.php` is what actually changes the tag name. 

Does that make sense or is that different from your understanding?

**Comment by swissspidy** [comment]
> So there's a file where there's logic done to add semantic headings, and a function is a part of this to change the tag name. See here: [https://github.com/GoogleForCreators/web-stories-wp/blob/feature/11788-semantic-headings-editor-sidebar/includes/AMP/Traits/Sanitization_Utils.php](https://github.com/GoogleForCreators/web-stories-wp/blob/feature/11788-semantic-headings-editor-sidebar/includes/AMP/Traits/Sanitization_Utils.php?rgh-link-date=2022-07-05T15%3A47%3A44Z)

You should be able to safely ignore that file. The only thing it does is trying to retrofit heading tags for older stories. If there are are any heading tags anywhere in the story already it's a no-op:

https://github.com/GoogleForCreators/web-stories-wp/blob/feature/11788-semantic-headings-editor-sidebar/includes/AMP/Traits/Sanitization_Utils.php#L142-L145

> but that this file for `getTextElementTagNames` doesn't actually change anything, it just creates a map that can be used in other spaces in the application with each element mapped

That map is used when generating the story output in `OutputPage` here:

https://github.com/GoogleForCreators/web-stories-wp/blob/54d0be958acc0fb9a02f692171fe8b6610a31998/packages/output/src/page.js#L77-L79

Which is then used to set/change/override the tag name for every text element here:

https://github.com/GoogleForCreators/web-stories-wp/blob/54d0be958acc0fb9a02f692171fe8b6610a31998/packages/output/src/page.js#L99

> In order to support the idea of us updating the name of a tag, we need it to be beyond the component state, so that it's saved as part of the published data of the selected element.

In `TextAccessibilityPanel` you can use the `pushUpdate` callback (which is passed as a prop to every panel) to update the element's `tagName`.

Here's an example of `pushUpdate` in another panel:

https://github.com/GoogleForCreators/web-stories-wp/blob/657866a2574ae5a02ece3ab88c990bec75eb0f3d/packages/story-editor/src/components/panels/design/videoAccessibility/videoAccessibility.js#L89-L102

`pushUpdate` updates the element only once you step out of the design panel again (e.g. when you click on the canvas)

You can verify that the `tagName` property is set on an element by [inspecting the story data in the dev tools](https://github.com/GoogleForCreators/web-stories-wp/blob/8adb601ce8485365e2309429b580ead5c7c1a7b6/docs/devtools.md).

Circling back to `OutputPage` and `getTextElementTagNames`: With the `tagName` being properly set in the story data and your new change to `getTextElementTagNames`, this `tagName` should now be picked up when generating the story HTML that is visible on the frontend.

Hope that makes sense.

Happy to explain it with code too if that is helpful. But from what I can see you seem to be close–the `pushUpdate` thing to update the story data seems to be the main missing piece.

**Comment by felipebochehin87** [comment]
**H1:** 

![H1.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/a152b505-2c80-490a-9ec2-a422e7994800)

**H2:**

![H2.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/1b91ea83-21f0-407b-be0d-6338c03cfd5e)

**H3:**

![H3.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/75e93602-b80d-46aa-8b3e-4de556e46956)

**Paragraph:**

![Paragraph.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/b99b1fd8-9b82-402f-91fb-efa222f89321)

**Comment by sblinde** [comment]
I think the last refactor of this brings some things to mind that should be considered with building this going forward:

The last refactor tackled a few of the things we talked about: it added the tag name to the elements at the top level within the StoryProvider. That way, the calculated "tagName" is based on the algorithmic logic within `getTextElementTagNames` and inclusive of both the selected tag as well as the other tags on the page being viewed/edited itself. So there doesn't need to be a component state anymore for the tag names or the elements.

However, this change introduces a fork in the road in terms of what we move forward to build past this:

### Solution 1
**We continue to support and allow for someone to make the tag name "Automatic" within the dropdown:**
1. We use the `getTextElementTagNames` functionality, the way it's built right now with the latest changes, will change anything that is set to an `auto` tagName to display as the appropriate text. So we should only get `h1`, `h2`, `h3`, `p`.  But there is no way to indicate in the UI that a `tagName` has been assigned automatically by the `getTextElementTagNames` function, or to know that a user set it.
2. If we do support "Automatic", we may need a property on the element to indicate that it has been set automatically and not in actual data. Meaning, if the algorithm chose for a text element to be `h1`, we could indicate that it was automatically selected in the UI with something like `automaticAssignedTagName: true` or a property like that. This could be set in the `getTextElementTagNames` function, and any element that does not have an actual `tagName` as part of its data would be `automaticAssignedTagName: false`. This is a way we could accomplish allowing someone to automatically assign the tag name in the dropdown, and also show the user that the semantic heading was chosen automatically.

### Solution 2
**We no longer support `auto` and users can choose only the predefined options.**
1. The change made to this code will not display any text element as `auto`, because of the way `getTextElementTagNames`  works (`auto` will be overridden by other logic). `Automatic` is removed from the dropdown.
2. We show a user that they either have an `h1`, `h2`, `h3`, or `p` element, and we allow them to change to any of these, but automatically setting it with the dropdown is not a feature.

I think that's the path this code needs to take in order to finish this feature, and because the most ideal solution to add functionality (keeping automatic) means adding a property to the element that wasn't previously defined, I leave it in the hands of the teams involved to decide.


### To Do:
1. Depending on the solution at hand, we'll need to accomodate either removing `auto` support in the dropdown, or add the property within the `getTextElementTagNames` to support a user knowing whether the text is automatic.
2. A test will need to be updated for the addition of tag names to the storyProvider.
3. Depending on the path decided for the rest of the work, some logic remains to be built for what displays in the dropdown if automatic is supported.
