### ISSUE TITLE
Dashboard: Incorporate all filtering state into the FiltersProvider

### ISSUE THREAD

**Issue by mwritter** [swissspidy/web-stories-wp#11789]
## Feature Description
Currently only the taxonomy filters and the author filter utilize the FiltersProvider.  Any state that can update which stories are shown (ie Taxonomy filters, Author filter, Sort, Status Filter, Keyword search) should utilize the FiltersProvider.

Currently we are handling 'filtering' in multiple different places `FiltersProvider`, `mystories/index`, and `useStoryView`.  This makes it hard to debug issues on the dashboard and to update filtering logic on the dashboard.  Moving all filtering logic into one place will remove complexity in this area and should increase DX while working on the dashboard.

As part of this work, we should expect that https://github.com/GoogleForCreators/web-stories-wp/issues/11668 should be resolved as a test case to get this consolidated.

## Alternatives Considered

Let the filtering logic be in multiple places.  This would lead to ambiguity on how to add / update the logic surrounding dashboard filters and the complexity in this area will continue to rise.

## Additional Context

![Filters Improvement](https://user-images.githubusercontent.com/14057928/175395817-118f9350-78b9-4ba0-95bf-f6ca9b4f2e06.png)

**Comment by sblinde** [comment]
This ticket should also take care of the issue seen in https://github.com/GoogleForCreators/web-stories-wp/issues/11668
