### ISSUE TITLE
When removing a layer from a group, it can appear still inside the group

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#11785]
## Bug Description

If you remove a middle layer from a 3+ element group using the RCM option "Remove layer from group", it is still z-indexed "inside" the group.

## Expected Behaviour

When removing a layer from a group, it should be position either above or below all the other group elements.

## Steps to Reproduce

1. Add 3 elements to a group
2. In the layer panel, select the middle element, right-click and select "Remove layer from group"
3. Observe that the list of layers is now in an invalid state.

## Screenshots

![layer-remove-from-group-bug](https://user-images.githubusercontent.com/637548/175277867-481d3eca-9030-436e-959f-b5e2030e0a65.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
https://images.zenhubusercontent.com/235435637/0b5942ac-91a5-48fe-9431-2142572dc0af/2022_07_07_08_25_29.mp4
