### ISSUE TITLE
Block: Block not registered when running `npm run dev`

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11805]
## Bug Description

When running `npm run dev`, gutenberg block has javascript error and is not registered. The error is following. 
```
edit.js:134 Uncaught ReferenceError: $RefreshSig$ is not defined
    at ./packages/stories-block/src/block/icons.js (edit.js:134:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./packages/stories-block/src/block/index.js (icons.js:88:14)
    at __webpack_require__ (bootstrap:19:1)
    at make namespace object:7:1
    at web-stories-block.js?ver=60bdb92a34a30a112dab22dcbafaf922:12174:3
    at edit.css?09b0:1:1
```
<img width="1884" alt="Screenshot 2022-06-27 at 15 13 01" src="https://user-images.githubusercontent.com/237508/175964407-3e663b82-6677-4a38-b0f8-d6527a9bc243.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
The reason for this is that we include `ReactRefreshWebpackPlugin` only for the editor & dashboard bundle and not for the rest, but the Babel transform is always included even for the other bundles.

**Comment by spacedmonkey** [comment]
I have put together a draft PR to fix this issue at https://github.com/GoogleForCreators/web-stories-wp/pull/11927. I am not sure of this as the solution. Love feedback from @swissspidy

**Comment by swissspidy** [comment]
Well, does it work?

I doubt that Fast Refresh works properly in a Gutenberg, which is why I didn't include it for the block originally. But if it works then why not 🤷
