### ISSUE TITLE
Links: Icon displays as broken image on the element

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#11848]
## Bug Description

The link icon displays as a broken site icon on the element it was applied to. 

## Expected Behaviour

The link icon should render the image on the element. 

## Steps to Reproduce

1. Add element to the page
2. Add a link to the element
3. See the icon image on the panel but on hover of the element the icon image is broken

## Screenshots

<img width="253" alt="Screen Shot 2022-06-30 at 11 06 57 AM" src="https://user-images.githubusercontent.com/66372350/176720298-7c0b4e48-4922-472e-8a3c-eb4628fc4054.png">

## Additional Context

- Plugin Version: 1.22.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
Similar to #11847, with the difference that the link icon in the tooltip is already an image, it just needs the `crossorigin=anonymous` attribute.

Related: #11777

**Comment by timarney** [comment]
This seems to be fixed in https://github.com/GoogleForCreators/web-stories-wp/pull/11792 .
