### ISSUE TITLE
Multipage Canvas: Apply design feedback

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#11845]
## Feature Description

To do after UX review (from https://github.com/GoogleForCreators/web-stories-wp/pull/11669):
- [x] Resize all page previews to also show non-safe space (includes page carousel and grid view)
- [x] Don't show hover state when dragging from canvas to neighbor page
- [x] Don't allow neighbor pages to be draggable
- [x] Fade pages even more further away, show max 4 either direction

**Comment by merapi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Web-Stories-5e94d3aced449034e1e9b226/issues/GoogleForCreators/web-stories-wp/11845?planning-poker) with ZenHub @barklund @miina

**Comment by felipebochehin87** [comment]
https://images.zenhubusercontent.com/235435637/ac534731-5191-436d-b885-7ad64f0f7c47/2022_07_19_14_47_07.mp4


https://images.zenhubusercontent.com/235435637/0bf593f6-47fa-492e-9887-cf241d686776/2022_07_19_14_46_21.mp4
