### ISSUE TITLE
Filters open and close on first click when switching from All Categories to All Authors (and vice-versa)

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#11840]
## Bug Description

When the user expands "All Categories" filter and then clicks on "All Authors" to expand it, the filter by authors opens and closes, forcing the user to click again on the filter so that it can be used. The same happens when user switches from "All Authors" to "All Categories". 

## Expected Behaviour

Filter options must be displayed on first click, and filter must remain open.

## Steps to Reproduce

1. Go to the Dashboard
2. Click on "All Authors"
3. Click on "All Categories" - here the categories filter will open and close
4. Click again on "All Categories" - here the filter will remain open
5. Click on "All Authors" - here the authors filter will open and close

## Screenshots

https://images.zenhubusercontent.com/235435637/e4cf3992-3e7b-4215-aaec-4d756b060ea6/2022_06_29_08_51_11.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by mflorida** [comment]
This bug affects other menus throughout the app and is accounted for in #11889.
