### ISSUE TITLE
Multipage Canvas: Performance testing

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#11844]
## Feature Description

We want to test the performance of the multipage canvas, especially on less powerful devices.
Things like switching between pages should not result in a noticeable delay - at least not vs our current single-page version, we realize that the editor is less snappy in general on slower devices.
Based on that knowledge we can either release the feature for all users or add a toggle button to switch between single and multi-page canvas.

**Comment by barklund** [comment]
From my rough testing of changing page in a big story with lots of complex pages (after they've all been captured as images) increases the average click response time by 40 ms (from ~240ms to ~280ms). It's of course hard to do in isolation as other stuff accidentally happening on my computer can skew this, but in general, I would agree with the numbers, that the response time is "a bit" slower now with this feature enabled, that without. That's on the development version of course, could be different in the production environment.

**Comment by merapi** [comment]
Tested on 8yo 4c old laptop:

https://user-images.githubusercontent.com/21036224/180755962-ae44e7ac-030f-4dc6-8b2e-ba9352dda3fa.mov

My impressions: initial load and switching between the pages takes longer - noticeably (on that old laptop) but not to the state where you are annoyed by it. Editing feels the same. No big need to include a multi/single canvas toggle button, unless we will get reports about it being slow (e.g. on 2c devices).

**Comment by merapi** [comment]
Based on the above we will just enable the flag (remove it?).
