### ISSUE TITLE
Media: Unable to upload transcodable videos

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11881]
## Bug Description

While testing uploading a MKV file, it was rejected by the editor. This is because the MKV file returned an empty type ( mime type ). 

<img width="572" alt="Screenshot 2022-07-06 at 18 19 20" src="https://user-images.githubusercontent.com/237508/177607549-c24208bf-98bd-4a48-8a06-47bff01923f6.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by spacedmonkey** [comment]
I also had issues with .avi files not working. This is because video/avi is not in the allowed list.

**Comment by swissspidy** [comment]
Hmm not sure why it's not in `TRANSCODABLE_MIME_TYPES`. AVI is even in the ffmpeg.wasm demo, so it should work.

We can add it once we've tested it.

**Comment by spacedmonkey** [comment]
AVIs can be multiple mime types. One of which is in the array. 

https://github.com/GoogleForCreators/web-stories-wp/blob/1ee1f1f82203df29da0f9aaa8e75312348d5cba7/packages/story-editor/src/app/media/constants.js#L32

But according to this [list](https://www.sitepoint.com/mime-types-complete-list/), it can be.
application/x-troff-msvideo, video/avi, video/msvideo, video/x-msvideo. 


.avi | application/x-troff-msvideo
-- | --
.avi | video/avi
.avi | video/msvideo
.avi | video/x-msvideo


application/x-troff-msvideo
--
.avi | video/avi
.avi | video/msvideo
.avi | video/x-msvideo




application/x-troff-msvideo
--
.avi | video/avi
.avi | video/msvideo
.avi | video/x-msvideo

**Comment by spacedmonkey** [comment]
Sadly it is a known issue with mkv file being uploaded

https://stackoverflow.com/questions/56454681/why-is-no-file-type-returned-when-adding-an-mkv-file-to-a-file-input
