### ISSUE TITLE
Background audio recording stop button has wrong icon

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11917]
## Bug Description

The icon on the background audio playback controls shows "Stop" icon however the button is a pause button
<img width="354" alt="image1" src="https://user-images.githubusercontent.com/58738530/179244966-029a2674-9996-4230-97ca-379729ef7e7c.png">

## Expected Behaviour

The icon should be "Pause" [ | | ].
See https://github.com/GoogleForCreators/web-stories-wp/issues/10561

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
> The tool tip should say "Stop" as this is the universal understanding of this square icon

The button _pauses_ the audio though, so it's rather the icon that needs changing.

**Comment by merapi** [comment]
Looks like a project-wide issue, was reported here:

https://github.com/GoogleForCreators/web-stories-wp/issues/10561

Ticket updated.

**Comment by swissspidy** [comment]
Oh, forgot about that one. Then we can close this as a dupe, no?
