### ISSUE TITLE
Background Audio: M4A files not supported

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11919]
## Bug Description

Originally reported by @sblinde in Bug Bash 1.23

When a m4a file is manually uploaded in uploader , and when a user copies the URL of the valid file to be used as background audio, it says “invalid link” for the URL from the WordPress file. Note: It may be because the background audio file type is not the same formats allowed for a background audio. [Seen in Windows 11, Chrome] - 

## Additional Context

@swissspidy flagged that "The specific mime type might not be in the allowlist yet"

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
> Note: It may be because the background audio file type is not the same formats allowed for a background audio. 

Exactly this.

We do not currently support M4A files, so this is absolutely expected.

Would need to add `audio/x-m4a` to the allowlist.

**Comment by spacedmonkey** [comment]
m4a are supported by core. [See](https://github.com/WordPress/wordpress-develop/blob/b01c8f193b93b0cf0627a4e29008e933206e73b4/src/wp-includes/functions.php#L3376). 

However `audio/x-m4a` is not in the [allowed list](https://github.com/WordPress/wordpress-develop/blob/b01c8f193b93b0cf0627a4e29008e933206e73b4/src/wp-includes/functions.php#L3339-L3443). Adding it our allowed list, is not useful here, as it would be filtered out.

**Comment by swissspidy** [comment]
Hmm okay, putting this back to the backlog for now
