### ISSUE TITLE
Semantic Heading indicator "Learn More" text is too large

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11916]
## Bug Description

originally reported by @sblinde 
Font size for “Learn More” needs to be smaller
<img width="366" alt="image2" src="https://user-images.githubusercontent.com/58738530/179243056-8260ad96-a97e-495e-bbb8-9f6d0d7fa378.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by sblinde** [comment]
This is fixed in the open PR for https://github.com/GoogleForCreators/web-stories-wp/pull/11888

**Comment by felipebochehin87** [comment]
Checked:

* Changes made on the style tab are applied to the text;
* H1, H2, P tags on preview story;
* Applied multiple styles to the texts;
* Applied the same style to the texts;
* Tested Automatic (Mixed) and Mixed scenarios;
* Heading changes depending on the text position (H1 becomes H2 if another H1 is located above it).
