### ISSUE TITLE
Templates: make use of custom heading levels

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11928]
## Feature Description

Originally mentioned during bug bash:

Templates should use semantic heading levels to correctly prioritize the different headings. A bad example is the "Plant Based Dyes DIY" template, where the “1” is an h1 and the “Prepare your fabric” is an h3. The latter should be the most important heading on the page or at least as important as the number

![image](https://user-images.githubusercontent.com/841956/179497790-60dbf3fc-7852-41ce-9395-cf63804d466e.png)

To address this, we should go through all templates and identify issues like these and manually set the right headings as h1 etc. and the incorrect ones as paragraphs or subheadings

**Comment by felipebochehin87** [comment]
Headings look good. Tested with different templates, changed headings, reset headings, confirmed that they're tag as expected when publishing and previewing the story.
