### ISSUE TITLE
User cannot initiate Audio Self Recording if they don't have a webcam

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11920]
## Bug Description

When someone wants to record an audio file on a computer that does not have a webcam, they get a message that says “Error: Could not initialize recording. Reason: No Camera Found.” [Seen on Windows 11, Chrome, on two machines that do not have web cameras (desktop, laptop w/o webcam)] - Reporter: Sam
Of note: When you do get this error, the buttons below that say “Record Video” and “Take a photo” look to still be enabled, but nothing happens when you click on them.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Worth noting that we have a todo for this in the code already:

https://github.com/GoogleForCreators/web-stories-wp/blob/64c67ffcfd727e835cb1110709bbee33251638d4/packages/story-editor/src/components/mediaRecording/provider.js#L140-L148

I suppose we can use something like this to detect whether there is any camera or microphone available and then change the `mediaStreamConstraints` accordingly:

```js
let hasCamera = false;
let hasMicrophone = false;

try {
	const mediaDevices = await navigator.mediaDevices.enumerateDevices();
	hasCamera = mediaDevices.some((device) => device.kind === 'videoinput');
	hasMicrophone = mediaDevices.some((device) => device.kind === 'audioinput');
} catch (err) {
	// Do nothing.
}
```

Then:

* No camera, no microphone: show error message
* Only camera: muted video + image recording only
* Only microphone: audio recording only

> Of note: When you do get this error, the buttons below that say “Record Video” and “Take a photo” look to still be enabled, but nothing happens when you click on them.

Not sure how this could happen. When there is an error message, the footer buttons are not supposed to render in `MediaRecordingLayer`

**Comment by merapi** [comment]
@swissspidy I did some testing and came up with something in https://github.com/GoogleForCreators/web-stories-wp/pull/11939.

I didn't test the `camera without a mic` case because I don't have such a device yet.
From my testing: you can't just disable mic permission - it will not work the same way as a real device would, like you cannot just disable the camera in macOS and leave the mic only I had to use a desktop machine with a separate mic for this.

**Comment by merapi** [comment]
> I suppose we can use something like this to detect whether there is any camera or microphone available and then change the mediaStreamConstraints accordingly:

Yep, that was my 2nd way of doing it, but I had some issues with it - it will still list the device but it can be unavailable for use or can have a not working video feed.
