### ISSUE TITLE
Play button is unavailable to users when trimming a gif

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11922]
## Bug Description

[Jonny] If you switch to gif and try to trim the video, there is no play icon. This can make it hard to trim the video, as you can not pause a looping video. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
![trim gif.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/efc1f583-1a4d-4bc9-9191-9a3191141091)
