### ISSUE TITLE
Media Recording: Allow functionality to pause recording 

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#11923]
## Feature Description
Some users might find it useful to pause an audio/video recording and then continue/stop recording as desired.

## Alternatives Considered
A user can rerecord an audio or video recording all over, but it may be helpful to pause/continue certain segments of the recording.

**Comment by felipebochehin87** [comment]
Tested using PR #12000.

1. Started a recording
2. Paused
3. Resumed
4. Paused again
5. Resumed
6. Stopped
7. Trimmed
8. Inserted

Tested on Safari, Chrome and Firefox.
