### ISSUE TITLE
Media Library: Clear relevant story metadata when deleting media

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11969]
## Feature Description

When deleting media from WordPress in the story editor, if an image is used as a attribute, such as poster image for video, poster for story, publisher logo or link icon, value is not reset. When removing media from WordPress all instances in the current story should be reset to empty / default values. 

Relevant code:

https://github.com/GoogleForCreators/web-stories-wp/blob/cc6003f1e4689e04b4fa7f6cf88e3c67a5dfcf0d/packages/story-editor/src/components/library/panes/media/local/deleteDialog.js#L61-L74

**Comment by swissspidy** [comment]
Still makes sense, but no capacity right now
