### ISSUE TITLE
Outdated Integration Documentation

### ISSUE THREAD

**Issue by alcarazzam** [swissspidy/web-stories-wp#11967]
Hi,

I think that the [First Party Media Support documentation](https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/third-party-integration/story-editor/api-callbacks.md#first-party-media-support) is outdated. For the `getMedia` function, the HTTP response from the WordPress plugin seems to be very different from the documentation, which makes the editor not load any image.

Regards.

**Comment by m-alzam** [comment]
Thanks! I see that I also need to return `totalItems` and `totalPages`, which seems not to be documented. The following works for me:

<details><summary>JSON</summary>

```json
{
    "data": [
        {
            "src": "...",
            "id": 643,
            "alt": "",
            "mimeType": "image/jpeg",
            "width": 5184,
            "height": 3456,
            "type": "image",
            "sizes": {
                "full": {
                    "file": "...",
                    "width": 5184,
                    "height": 3456,
                    "mimeType": "image/jpeg",
                    "sourceURL": "..."
                },
                "thumbnail": {
                    "file": "...",
                    "width": 30,
                    "height": 20,
                    "mimeType": "image/webp",
                    "sourceURL": "..."
                },
                "medium": {
                    "file": "...",
                    "width": 300,
                    "height": 200,
                    "mimeType": "image/webp",
                    "sourceURL": "..."
                }
            }
        },
    ...
    ],
    "headers": {
        "totalItems": 101,
        "totalPages": 4
    }
}
```

</details>

But only when the `sizes` object only has the `thumbnail` item and not any other. Any suggestions?

**Comment by swissspidy** [comment]
You mean it does not work at all if there are other sizes? That sound odd
