### ISSUE TITLE
Media: Button empty after crop

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#11968]
## Bug Description

When using the media library, if you crop an image, then return the button has no text. See screen recording.

## Screenshots

https://user-images.githubusercontent.com/237508/179956122-299c4882-dc60-46d0-a316-960e3f8e834b.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Sounds like a missing label somewhere?

**Comment by spacedmonkey** [comment]
> Sounds like a missing label somewhere?

Had a quick look, couldn't work it out.
