### ISSUE TITLE
Blocks: Grid layout setting for 4 columns does not apply

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#11960]
## Bug Description

When I set the number of columns to 4, the grid layout remained at 3 columns. 

## Expected Behaviour

Changing the number of columns to 4 should display the grid layout in 4 columns. 

## Steps to Reproduce

1. Add Web Stories block
2. Select Grid Layout
2. Change number of columns to 4
3. Note the number of columns displayed has not changed from 3 to 4

## Screenshots

https://user-images.githubusercontent.com/66372350/179762339-ba1fcccf-4aff-4b73-9702-be611649cd75.mov

## Additional Context

Used default WP theme Twenty Twenty-Two. Also occurred with Twenty Twenty-One. 
Site: https://testsite.cmsdevrel.com/2022/07/19/test-4-columns-grid-layout/

- Plugin Version: 1.23.0
- WordPress Version: 
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
What theme is this happening with? Or does this happen with all themes?

**Comment by LuckynaSan** [comment]
Both Twenty Twenty-Two & Twenty Twenty-One.

**Comment by spacedmonkey** [comment]
I have worked on this issue. There is a very simple solution. https://github.com/GoogleForCreators/web-stories-wp/pull/12469. Removing min width, fixes the issue, but changes the styling a little. Let me know what you think of the solution.
