### ISSUE TITLE
Horizontal scrollbar in Text panel

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11979]
## Bug Description

There's an ugly horizontal scrollbar in the Text panel.

Observed when there are no saved styles, but maybe it happens also when there are some.

## Expected Behaviour

No horizontal scrollbar

## Steps to Reproduce

1. Add text element

## Screenshots

![Screenshot 2022-07-21 at 10 49 06](https://user-images.githubusercontent.com/841956/180172421-e46cd604-99fa-46f6-a630-fbec9cd234f8.png)

## Additional Context

- Plugin Version: 1.23.0
- WordPress Version: 6.0.1
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
Would be great to prioritze this, it's a bit annoying and should be trivial to fix.

**Comment by miina** [comment]
@swissspidy Can you still see this?

From my testing:
![Uploading Screenshot 2022-12-06 at 11.17.02.png…]()

**Comment by swissspidy** [comment]
@miina Yes, but you need to delete all saved styles first:


<img width="426" alt="Screenshot 2022-12-06 at 15 23 18" src="https://user-images.githubusercontent.com/841956/205937313-7a3249c0-d418-4ffc-a4bb-9f8b6edb78f5.png">

**Comment by miina** [comment]
Oh, for some reason my image didn't upload before... I removed all the styles and it's not showing:
<img width="361" alt="Screenshot 2022-12-06 at 11 17 02" src="https://user-images.githubusercontent.com/3294597/205940701-5465f389-077e-4dc7-b7d4-9d2ea2aee464.png">

Hm, why is your screenshot showing "Recently Saved Styles" though 🤔

**Comment by swissspidy** [comment]
Is that a different section? It‘s what I see when adding/editing a text element

**Comment by miina** [comment]
Ah, yes, it's a different section, now I understand :D I'm in the Insert tab, not the Style tab 💡
