### ISSUE TITLE
Preview uploaded images is not working and uploaded images are not displayed on canvas

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#11971]
## Bug Description

**Tested on Local**

When an image/video is uploaded to the app, the preview is not displaying the image/video, only a grey square is displayed. The same when I add this image straight from the upload screen - the image is added, but only a gray square is displayed.

## Expected Behaviour

Image/video preview should be displayed + when added to the canvas it should be displayed too.

## Steps to Reproduce

1. Go to Stories > New > Upload media
2. Go to the upload media tab
3. Select a file from local PC
4. Upload it and insert it to the canvas

## Screenshots

https://images.zenhubusercontent.com/235435637/cffb5e55-8447-4f79-bb6d-7549a1e3c8e3/2022_07_20_09_19_13.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
As per Slack:

Something is seriously wrong with your local environment.

In the WordPress media modal you’re supposed to see actual images, not gray squares.

I assume it’s related to your site being mixed HTTP and HTTPS. Check your URLs under Settings -> General and make sure they use HTTPS
