### ISSUE TITLE
Trimming UI takes a long time to appear

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#11987]
## Bug Description

It takes a while to show the trimming UI, sometimes it takes more time to show the trimming UI than to process the video - so that might be an even bigger issue than the final processing.
Here are the results:

<table>
<tr>
	<td><b>Video length
	<td><b>Computer
	<td><b>Time to process (insert)
	<td><b>Trim UI wait time
<tr>
	<td>10s
	<td>8yo 4c laptop
	<td>24s
	<td>3s
<tr>
	<td>10s
	<td>M1
	<td>7s
	<td>3s
<tr>
	<td>60s
	<td>8yo 4c laptop
	<td>80s
	<td>20s
<tr>
	<td>60s
	<td>M1
	<td>18s
	<td>54s
<tr>
	<td>120s
	<td>8yo 4c laptop
	<td>150s
	<td>43s
<tr>
	<td>120s
	<td>M1
	<td>25s
	<td>110s
</table>

## Expected Behaviour

Trimming UI needs to show instantly.

## Steps to Reproduce

Try on 1min+ video.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested using PR #12001.

Tested using my PC:

Windows 10
Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz  2.21 GHz
RAM 16 GB

And also my MacBook

macOS Monterey
Processor 2.6 GHz 6-Core Inter Core i7
Memory 16 GB 2667 MHz DDR4

Safari, Firefox, Chrome.
