### ISSUE TITLE
Media Recording - Trimming: Better user experience

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#11988]
## Feature Description

Current version:
When you click the Insert button after trimming - we insert the full-length video on the Canvas and the trimmed video will appear in the Media panel after the processing is done.

We want to change it so that you wait on the trimming UI (with a proper message) until the processing is done and we insert the trimmed video. It should also be easier to generate a correct thumbnail for the trimmed video that way?

So it will fix the issues from https://github.com/GoogleForCreators/web-stories-wp/pull/11908:
- [x] The preview on-canvas while the video is being trimmed and uploaded is also not trimmed, but shows the full duration
- [x] The generated thumbnail is taken from the start of the full video, not the start of the trimmed video

**Comment by bmattb** [comment]
@aaskedall as discussed yesterday we are awaiting your input on the trimming UX

**Comment by felipebochehin87** [comment]
Followed steps below and they worked:

Start a video recording and record 10+ seconds of video
Click the trim button to start trimming the recording
Move any trim offset and press trim
Observe that trim happens instantly with a dialog informing you of this
Wait until trim completes (the shorter the faster)
Observe that the displayed video is only the trimmed bit
Click the trim button again
Observe that the original video is available to trim from, with the previously trimmed bit "preselected"
Abort trimming
Observe that the original trimmed video still displays correctly
Press insert
Observe that the trimmed video is uploaded and inserted to the page
Observe that the trimmed video has the correct duration and thumbnail
