### ISSUE TITLE
Continued issues with story poster in v1.23.1

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12029]
## Bug Description

This is a follow-up to #11980

Apparently #11982 didn't fully address all issues with story posters, so we need to look into this again.

Related: #12028

## Expected Behaviour

Setting/updating/removing the story poster should "just work".

## Steps to Reproduce

1. Create story with some poster image, publish.
2. Refresh editor, change poster image, save
3. Refresh editor (or go to dashboard), see old poster image
4. Repeat with a hotlinked image

## Additional Context

- Plugin Version: 1.23.1
- WordPress Version: 6.0.1
- Operating System: macOS
- Browser: Chrome

**Comment by felipebochehin87** [comment]
Tested using PR #12030.

1. Created a new story
2. Added a new poster image from the media library
3. Saved story
4. Visited the Dashboard and saw the poster image
5. Reopened the story and saw the poster image
6. Added a hotlinked image and saved
7. Image was updated on both editor and dashboard
