### ISSUE TITLE
Media Recording: Broken image capture

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12033]
## Bug Description

When trying to take a still picture in media recording mode, the photo is taken straight away instead of waiting for the countdown to finish.

## Expected Behaviour

The photo should only be taken after the countdown

## Screenshots

https://user-images.githubusercontent.com/841956/181281069-b89babde-f5aa-48d8-bf28-983c1c7e07b6.mov

## Additional Context

- Plugin Version: 1.24.0-alpha
- WordPress Version: 6.0.1
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
Maybe this broke with the recent trimming addition? cc @barklund @merapi

**Comment by felipebochehin87** [comment]
Tested using https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, PR #12067.

1. Started a new story
2. Took a picture - takes the photo after the countdown
3. Recorded a video - starts recording after the countdown
4. Used blur - background blur works for both pics and videos
