### ISSUE TITLE
Review Templates to improve / fix text element usage

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#12032]
## Feature Description
In the templates, instead of using the Text Fill (background color) feature, a separate shape element is added behind it. In some cases, the same is done with borders instead of just using element border feature. This means that the text is not always centered either, even though intended.

EDIT: The following will be fixed within #12044 

Additionally, it looks like there are many cases where the text is not correctly displayed and takes more room than assigned, some examples:
![Screenshot 2022-07-26 at 11 08 52](https://user-images.githubusercontent.com/3294597/181256587-aaebb6e5-c9f8-4157-9d0d-9eeff93699d3.png)
![Screenshot 2022-07-26 at 11 07 32](https://user-images.githubusercontent.com/3294597/181256601-c6bdfe41-450b-42b8-a6d1-c13f3db701c7.png)
![Screenshot 2022-07-26 at 11 04 53](https://user-images.githubusercontent.com/3294597/181256605-415c84ae-1c7a-45aa-afb8-3949d0be8f6d.png)
![Screenshot 2022-07-26 at 11 02 31](https://user-images.githubusercontent.com/3294597/181256608-bceb7005-ca48-4181-b90c-7d081b576176.png)

**Comment by miina** [comment]
Looks like the text taking more room is due to font issues: in the templates' original files, there doesn't seem to be any font metrics information  nor variants information. When a template is updated and we copy the full template information from our dev tools, it also includes the full font information (metrics + variants) and that seems to break the texts. So seems like templates that have been updated meanwhile and now include full font information can look broken.

**Comment by swissspidy** [comment]
Good catch with the font metrics! Searching for `"metrics"` in `packages/templates` reveals only a handful of templates with font metrics. We might be able to do a one-off migration here.

**Comment by merapi** [comment]
For me, it's a font loading issue.

Please test this case:
1. Create a story
2. Add a text element
3. Change font to Teko
4. Save
5. Reload
6. Text is broken (not Teko).

**Comment by swissspidy** [comment]
Are we lacking an effect somewhere that enqueues all required font stylesheets when opening the editor?

**Comment by merapi** [comment]
Moved to Slack https://xwp.slack.com/archives/C013J2EGH8R/p1658936309346839
