### ISSUE TITLE
Error 500 when clicking on "Remove audio"

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#12040]
## Bug Description

When user clicks on "Remove audio" after recording a new video with audio, an error 500 is retrieved and audio is not removed.

## Expected Behaviour

No error should be displayed and audio must be muted (removed from the video).

## Steps to Reproduce

1. Create a new story
2. Record a video with audio
3. Insert this video
4. Go to the Style tab and click on "Remove audio" - here is where you'll see error 500

## Screenshots

https://images.zenhubusercontent.com/235435637/1eb6fa94-ef0d-472a-8f2e-3780de73c179/2022_07_28_09_28_32.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System: Windows 10
- Browser: Firefox

**Comment by swissspidy** [comment]
@felipebochehin87 Is it just me or is it generally broken for all videos?

**Comment by swissspidy** [comment]
^ @felipebochehin87 friendly ping. #12042 should fix this in case you wanna take an early look

**Comment by felipebochehin87** [comment]
@swissspidy sorry, I missed your first comment. Now I tested using PR #12042 and I don't see any error, the mute version is uploaded to a separate video and no audio is played.
