### ISSUE TITLE
Numerous Error Displaying In Console

### ISSUE THREAD

**Issue by DanielCryptoK** [swissspidy/web-stories-wp#12047]
I have a number of different errors showing that are related to the web stories plugin I am hoping you can help me fix.

First error:

I have a very strange error as it only shows when you view in a certain order. To find the error you have to go to my home page bitcoin-casino-no-deposit-bonus.com, scroll down to the first web story - BC Game and when you click on it, the story does not load correctly, however when you click on it a second time it works but two errors show in the console. These errors are:

First Error

amp-story.js:1280 Uncaught TypeError: Cannot read properties of null (reading 'next')
    at jn.Er (amp-story.js:1280:12)
    at jn.wht (amp-story.js:1362:12)
    at amp-story.js:696:12
    at page-advancement.js:229:7
    at Array.forEach (<anonymous>)
    at Vo.onTapNavigation (page-advancement.js:228:34)
    at Vo.Mot (page-advancement.js:736:10)

Second Error

Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported
    at superpwa-sw.js:9:178

I have spoken with the developer of this plugin who confirms it is an error and they have a ticket open here https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/311

The first error does not show if you go directly to the BC Game web story, it only shows when being clicked on via the display. Also the other web stories do not display this error a lot of the time. 

Here is a picture of the next error showing related to your plugin: https://i.vgy.me/X2RhRu.png

To see this error, go to the homepage again and slowly start scrolling down the page and the error shows within 1 or 2 minutes.

I don't see this script listed anywhere in my page's source code, so I think it's being loaded into the page dynamically after everything has loaded. Given the URL of the script, it seems related to AMP (Accelerated Mobile Pages) and I have checked with the AMP developers who say it is related to web stories.

Many thanks for your help

**Comment by swissspidy** [comment]
You wrote that the second error is caused by the SuperPWA plugin and I agree with that.

**Comment by swissspidy** [comment]
Oh, and if you are referring to

> Here is a picture of the next error showing related to your plugin: [i.vgy.me/X2RhRu.png](https://i.vgy.me/X2RhRu.png)

Then please subscribe to https://github.com/ampproject/amphtml/issues/35959 for updates as this bug is tracked there.

**Comment by DanielCryptoK** [comment]
Hi swissspidy, 

The first error I mentioned in this thread, you said to follow https://github.com/ampproject/amphtml/issues/38140

I replied to this post asking for a date of when it will be fixed as reported back in April and it looks like ticket has been closed. I still have the problems caused by this issue which makes it so that users have to click two times to view the web stories and most wont know to do that so will presume they are broken.

Please can you let me know what is going on with this issue and why I am suffering from it still even though the job has been closed.

**Comment by DanielCryptoK** [comment]
Can anyone help me with these issues as web stories broken since April and no one seems to care. All my pages effected by this issue and now most of my videos in the web stories are showing as not indexed in googles new webmaster reported.
