### ISSUE TITLE
VideoPress: Fix new compatibility issues

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12082]
## Feature Description

When uploading a video to VideoPress, the service creates various versions of it with different dimensions, e.g. std, hd, hd 1080, etc.

When we originally added our VideoPress compatibility, we chose to use the hd mp4 version because they have the right dimensions.

At some point recently, VideoPress changed their infrastructure to use HLS. The result is that all the intermediate versions are split up into audio and video channels.

So the version we're using no longer has any sound, which means the editor thinks all these videos are muted.

The only way to fix this is by using the original file instead of an intermedia size.

That also means we can no longer safely mark these videos as optimized.

The problem: the original file might not be an mp4 :warning:

So right now the recommendation is to not use VideoPress with Web Stories due to incompatibility.

**Comment by JosefJezek** [comment]
@swissspidy Please set high priority to this issue. We need HLS for an unstable mobile network!!! VideoPress is a good solution. Thank you.

**Comment by swissspidy** [comment]
@JosefJezek This issue is really outside of our control. The problem with HLS is that it's not natively supported by most browsers (only Safari supports it), so VideoPress uses their own video player with custom JavaScript to work around that. However, AMP (the format Web Stories builds upon) does not support custom JavaScript nor custom players like that.

So if you'd like to use VideoPress with Web Stories, I recommend you to either:

1. Ask VideoPress to implement an AMP-compatible solution so that we can use their videos with `<amp-video>` without the custom VideoPress player and even if the browser does not support HLS.
2. Or ask [AMP](https://github.com/ampproject/amphtml) to add their own HLS polyfill so that HLS can be used even if the browser does not support it.
