### ISSUE TITLE
TypeScript: Convert `output` package

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12089]

**Comment by amovar18** [comment]
@swissspidy can i pick this I know this is blocked by `@googleforcreators/elements`, `@googleforcreators/masks`,  `@googleforcreators/element-library` and `@googleforcreators/animation` packages. I would resolve the errors once those PR are merged.

**Comment by swissspidy** [comment]
It might not be the best issue to pick up, but you're definitely welcome to try if you want to :-)

**Comment by amovar18** [comment]
@swissspidy I did manage to convert the package should I raise a draft PR for the same?

**Comment by swissspidy** [comment]
Amazing! Yeah sure why not 👍  Then the team can provide feedback already in this early state

**Comment by spacedmonkey** [comment]
This ticket is blocking other package migration. Is there anyway we move this on?

**Comment by swissspidy** [comment]
Feel free to provide feedback on #12382 if you'd like.

This should not be blocking anything else though. Other packages can be migrated even without the `output` package being fully migrated.

Check out the `design-system` package as prior art.

**Comment by swissspidy** [comment]
FWIW this ticket is not the blocking factor. There are three other ones currently blocking it.
