### ISSUE TITLE
Media3P: GIFs Tab not working

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12083]
## Bug Description

Something I noticed during yesterday's demo call and am still experiencing today: the GIF tab does not work.

There's some error loading the GIFs and unfortunately the error message is swallowed.

I suspect there's some error in `getGifResourceFromMedia3p` / `getResourceFromMedia3p` or similar, because the HTTP request is working just fine.

## Expected Behaviour

The GIF tab should work just fine

## Steps to Reproduce

1. Open editor
2. Go to third-party media tab
3. Go to GIFs tab
4. See error snackbar message

## Screenshots

![Screenshot 2022-08-09 at 14 46 59](https://user-images.githubusercontent.com/841956/183651020-30125bb4-8bab-4776-93df-f0bacbf392d8.png)

## Additional Context

- Plugin Version: 1.24.0-alpha
- WordPress Version: 6.0.1
- Operating System: macOS
- Browser: Chrome

**Comment by timarney** [comment]
Looks like the error message is 
<img width="1446" alt="Screen Shot 2022-08-09 at 3 10 52 PM" src="https://user-images.githubusercontent.com/62242/183741958-4eea8691-a21b-40f5-bb67-aef5c1af6171.png">


Which traced back is because of an empty array
 
 getOriginalSize(
```
originalWidth: mediaUrls[0].width,
originalHeight: mediaUrls[0].height,
```


<img width="757" alt="Screen Shot 2022-08-09 at 3 25 14 PM" src="https://user-images.githubusercontent.com/62242/183744458-693e5348-7d0d-4b5b-b9cd-6b5cbaf9ba82.png">

**Comment by swissspidy** [comment]
Interesting 👀  So some media item does not have any URLs? Can you show the full item that causes this issue? Really curious to learn more to make sure we add a fix/hardening at the right place.

Also, would be nice to not swallow these errors. At the very least a `trackError()` call in the right place would be valuable.

----

The weird thing is, I don't see this issue anymore right now. Makes me wonder whether this was some temporary glitch on the API side...

**Comment by timarney** [comment]
Seems the only way I can re-create now is 

- "fresh load of the page" 
- visit tab
- scroll to down --- at some point the error happens 

```
[
    {
        "url": "https://c.tenor.com/3XlNS53nHQoAAAAC/happy-friendship-day---sticky-figures-happy-friendship-day.gif",
        "imageName": "gif",
        "mimeType": "image/gif",
        "width": 360,
        "height": 293
    },
    {
        "url": "https://c.tenor.com/3XlNS53nHQoAAAAM/happy-friendship-day---sticky-figures-happy-friendship-day.gif",
        "imageName": "tinygif",
        "mimeType": "image/gif",
        "width": 220,
        "height": 180
    },
    {
        "url": "https://c.tenor.com/3XlNS53nHQoAAAAM/happy-friendship-day---sticky-figures-happy-friendship-day.gif",
        "imageName": "nanogif",
        "mimeType": "image/gif",
        "width": 220,
        "height": 180
    }
]
```


This is the output of 

```
const sortedUrls = mediaUrls.sort((x, y) => {
    console.log((y.width ?? 0) - (x.width ?? 0))
    return (y.width ?? 0) - (x.width ?? 0)
  
  });
```

<img width="1038" alt="Screen Shot 2022-08-09 at 4 11 20 PM" src="https://user-images.githubusercontent.com/62242/183751638-a61e7ecd-e2e0-415f-b4e3-3e866499b142.png">

**Comment by swissspidy** [comment]
Ah, neat! Nice debugging, thanks for jumping through these hoops.

I'm interested in the actual GIF that has this empty array. Was able to find it:

```json
{
    "name": "media/tenor:15958871741731118346",
    "provider": "TENOR",
    "type": "GIF",
    "author": {
        "displayName": "kulfy",
        "url": "https://tenor.com/official/kulfy"
    },
    "title": "Happy Friendship Day - Sticky Figures.Gif GIF",
    "createTime": "2021-12-11T13:51:04Z",
    "registerUsageUrl": "https://media3p.googleapis.com/v1/media:registerUsage?token=ARX97wOGMJFv46eHkc8YM9xSXtYAzvfGs/ST4BCYtbkbWF2%2BjK7c1XaTXFliGKoHpqCBPh6ilOA9tpR/TN3MKaaxVNWE6nw%3D",
    "imageUrls": [
        {
            "url": "https://c.tenor.com/3XlNS53nHQoAAAAC/happy-friendship-day---sticky-figures-happy-friendship-day.gif",
            "imageName": "gif",
            "mimeType": "image/gif",
            "width": 360,
            "height": 293
        },
        {
            "url": "https://c.tenor.com/3XlNS53nHQoAAAAe/happy-friendship-day---sticky-figures-happy-friendship-day.png",
            "imageName": "gifpreview",
            "mimeType": "image/gif",
            "width": 360,
            "height": 293
        },
        {
            "url": "https://c.tenor.com/3XlNS53nHQoAAAAM/happy-friendship-day---sticky-figures-happy-friendship-day.gif",
            "imageName": "tinygif",
            "mimeType": "image/gif",
            "width": 220,
            "height": 180
        },
        {
            "url": "https://c.tenor.com/3XlNS53nHQoAAAAM/happy-friendship-day---sticky-figures-happy-friendship-day.gif",
            "imageName": "nanogif",
            "mimeType": "image/gif",
            "width": 220,
            "height": 180
        }
    ],
    "videoUrls": [
        {
            "url": "https://c.tenor.com/3XlNS53nHQoAAAPo/happy-friendship-day---sticky-figures-happy-friendship-day.mp4",
            "videoName": "mp4",
            "mimeType": "video/mp4",
            "width": 360,
            "height": 294
        },
        {
            "url": "https://c.tenor.com/3XlNS53nHQoAAAP1/happy-friendship-day---sticky-figures-happy-friendship-day.mp4",
            "videoName": "tinymp4",
            "mimeType": "video/mp4",
            "width": 294,
            "height": 240
        },
        {
            "url": "https://c.tenor.com/3XlNS53nHQoAAAP2/happy-friendship-day---sticky-figures-happy-friendship-day.mp4",
            "videoName": "nanomp4",
            "mimeType": "video/mp4",
            "width": 150,
            "height": 124
        }
    ],
    "videoMetadata": {
        "duration": "2s"
    }
}
```

See how this GIF does not have any `image/webm` entries.

Yet we assume every GIF has one:

https://github.com/GoogleForCreators/web-stories-wp/blob/3041c6cacb733be3500e266815c9fadae21f260c/packages/story-editor/src/app/media/utils/getResourceFromMedia3p.js#L139-L142

https://github.com/GoogleForCreators/web-stories-wp/blob/3041c6cacb733be3500e266815c9fadae21f260c/packages/story-editor/src/app/media/utils/getResourceFromMedia3p.js#L163-L166

But in the end we don't even use it, as we always use the MP4 version when assembling the actual resource:

https://github.com/GoogleForCreators/web-stories-wp/blob/3041c6cacb733be3500e266815c9fadae21f260c/packages/story-editor/src/app/media/utils/getResourceFromMedia3p.js#L310-L313

It's a shame, because the webm version can often times be quite smaller. I'll create a ticket to change that. Would be a nice enhancement to use both versions.

In the meantime, your fix in #12091 makes sense to me.

One downside is that we still set `videoUrls.webm` here, even if there aren't any:

https://github.com/GoogleForCreators/web-stories-wp/blob/3041c6cacb733be3500e266815c9fadae21f260c/packages/story-editor/src/app/media/utils/getResourceFromMedia3p.js#L162-L166

So this will be `webm: { full: undefined, preview: undefined }`

Something that can be addressed in that ticket I'm going to create.

**Comment by swissspidy** [comment]
Created #12092 for what I had in mind here regarding using the webm versions.

**Comment by felipebochehin87** [comment]
I can still reproduce the issue on PR #12091. 

**Main:**

![01 main.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/960a2a70-1984-44a7-a475-7e18104fd9c6)

**PR:**

![12091.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/baa05328-0147-4125-b9c0-143a8a080855)

https://images.zenhubusercontent.com/235435637/be66c7b1-8eb9-4de5-97b5-5da8a4590965/2022_08_14_10_10_04.mp4

**Comment by felipebochehin87** [comment]
I can still reproduce the issue on PR #12091. 

**Main:**

![01 main.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/960a2a70-1984-44a7-a475-7e18104fd9c6)

**PR:**

![12091.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/baa05328-0147-4125-b9c0-143a8a080855)

https://images.zenhubusercontent.com/235435637/be66c7b1-8eb9-4de5-97b5-5da8a4590965/2022_08_14_10_10_04.mp4

**Comment by swissspidy** [comment]
@felipebochehin87 Please try again now; the actual update wasn't deployed yet.

**Comment by felipebochehin87** [comment]
Thanks @swissspidy. Unfortunately, I still see the error. What I did:

1. Started a new story using PR #12091
2. Clicked on Third-party Media > Gifs
3. Scrolled down, down, down... and when the list reaches its end, scrolled down some more

https://images.zenhubusercontent.com/235435637/85c6777a-3d1b-41a1-810b-c35555dae8d4/2022_08_15_12_50_33.mp4

**Comment by felipebochehin87** [comment]
@swissspidy never mind. After reloading the branch, it worked. I can scroll down many times and no error is displayed.
