### ISSUE TITLE
Videos: Generated poster files are too large and in wrong format

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#12132]
## Bug Description

A user in the support forum has reported that when uploading a video via the editor, the video poster image created automatically from that video is lager in size than the original video file size. The image is also created as a PNG rather than a JPG.

I have been able to replicate this using the files provided by the user in the support forums as well as with other videos. The user provided the video file that they uploaded to the editor and the poster image that was generated here: https://drive.google.com/drive/folders/1EUCFis84NSbzpjC839uuQjMWQGy5SbU2. 

The original video file is 2.5mb in size while the poster image created is 2.8mb. 

## Expected Behaviour

The video poster images created should be much smaller in file size to the original videos as well as JPG instead of PNG. 

## Steps to Reproduce

1. Create a new Story in the editor.
2. Upload a video file to the editor and add to the Story.
3. Go to **Style > Accessibility** section and save the generated poster image.
4. Check the file size and compare with the original video.

## Screenshots

N/A

## Additional Context

Video and generated poster image supplied by user in the support form: https://drive.google.com/drive/folders/1EUCFis84NSbzpjC839uuQjMWQGy5SbU2

Support topic: https://wordpress.org/support/topic/why-is-the-automatically-generated-poster-image-of-a-video-so-large

**Comment by swissspidy** [comment]
Looks like #12127 at least partially fixes this by accident due to an uncovered bug in `getCanvasBlob` and the type that is used for posters. Now the posters will be actual JPEGs and not PNGs anymore.

**Comment by spacedmonkey** [comment]
I was unable to replicate this issue locally. Is this still an issue?

**Comment by swissspidy** [comment]
Yes. #12127 fixed the issue with the mime type, but I still wanna look into tweaking the quality settings for the generated JPEG. Maybe there's room for further improvement.
