### ISSUE TITLE
SEO: `<title>` tag removed when using SEO plugin and block theme

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12139]
## Bug Description

The <title> tag is not accurately printing when using other plugins like Yoast SEO. When the plugin has been disabled, the title tag is present like so: <title>Episode 2 – Guide to be a boss – My Blog</title>. Once SEO plugin has been enabled again with default settings, the tag is no longer present in source code.

Original WordPress Support Topic: https://wordpress.org/support/topic/yoast-web-stories-conflict/

## Expected Behaviour

<title> tag should be present.

## Steps to Reproduce
1. Enable Web Stories and Yoast together
2. View the page source code and note the correct <title> tag is not present

## Additional Context

- Plugin Version: WS 1.24.0 / Yoast 19.5.1
- WordPress Version: 6.0.1
- Operating System: macOS
- Browser: Chrome

**Comment by felipebochehin87** [comment]
Tested using PR #12162.

![image.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/18f4967b-c04e-44bf-a1c6-128531c80275)
