### ISSUE TITLE
Color Picker: Apply gradient to text

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12143]
## Feature Description
Currently, we allow gradient colors to the background of a filled text box. 

A user in the forum has requested a feature to apply gradient colors to the actual text. 

WordPress Support Topic: https://wordpress.org/support/topic/feature-request-gradient-text/

For example:
<img width="585" alt="Screen Shot 2022-08-19 at 10 38 58 AM" src="https://user-images.githubusercontent.com/66372350/185994275-ad380ba6-75bd-492d-863a-4d2e1484d527.png">

**Comment by swissspidy** [comment]
@gajasinski @aaskedall Thoughts on this?

@barklund @miina Do you perhaps recall if we have looked into this before? Maybe browser support was an issue?

**Comment by gajasinski** [comment]
Great idea and would include it in the backlog, but not a priority at this time IMO

**Comment by miina** [comment]
> Do you perhaps recall if we have looked into this before? Maybe browser support was an issue?

We haven't looked into it as far as I remember. Searched around a bit and didn't find issues / mentions either.

**Comment by swissspidy** [comment]
Just stumbled upon https://github.com/m-muhsin/wp-gradient-text the other day which does this for Gutenberg.

**Comment by swissspidy** [comment]
Changing milestone for visibility/consideration
