### ISSUE TITLE
Tooltip displayed on hovering over "Settings" on the floating toolbar remains displayed on the previous location of the floating menu

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#12168]
## Bug Description

Tooltip displayed on hovering over "Settings" (on the floating toolbar) remains displayed on the previous location of the floating menu until another click happens.

## Expected Behaviour

Once the floating menu changes its position, the tooltip should be hidden.

## Steps to Reproduce

1. Add an element
2. Click on the element
3. Click on the Settings button
4. Click on "Fix to element" - see that the hint that is displayed when the cursor is over the Settings button remains displayed until the next click (image below)

## Screenshots

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631643566313132616361313965326335626232343431662f36393466323461652d353339382d346630622d623539392d326639353339623461313633.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/9634f44a-ba41-4f1a-baf0-c2133989760f)

https://images.zenhubusercontent.com/235435637/6606abf9-7b22-437b-b37b-4aaa54d18303/2022_08_25_09_16_16.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Related to #12095 and #11570.

CCing @miina @swissspidy @bmattb

**Comment by miina** [comment]
This seems to be a general issue with tooltips and can't be changed from the component that's using the tooltip. Tooltip is not considering that its parent element can move while the tooltip is visible.
