### ISSUE TITLE
TypeScript: Convert `templates` package

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12176]

**Comment by barklund** [comment]
@swissspidy, this is (kind of) blocked by the `migration` package, so should wait until after that (and that package includes Rollup, so it's a bit trickier to convert, I think?).

**Comment by swissspidy** [comment]
That's a great question.

Since it only uses `DATA_VERSION, migrate` from the `migration` package, it should be possible to only migrate these two things and not the whole `migration` package.

See for example the `design-system` package which isn't fully migrated yet but still can be referenced.

So it should not be a complete blocker I think. Let's give it a try.

And if that doesn't work, yeah I guess we'd have to migrate the `migration` package first.
