### ISSUE TITLE
Block: carousel layout responsiveness issues

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12170]
## Bug Description

Most notably on Firefox on smaller screens, the Glider track width calculation is quite off, causing white space to appear at the beginning of the carousel.

## Steps to Reproduce

1. Add Web Stories block with carousel layout, make sure there are plenty of stories in it
2. View in Firefox w/ small viewport
3. Notice huge gap

## Screenshots

![Screenshot 2022-08-29 at 11 45 40](https://user-images.githubusercontent.com/841956/187175877-2657a3bf-5c67-44ab-9a5d-a6cfe7bfbbec.png)

## Additional Context

- Plugin Version: 1.24.0
- WordPress Version: 6.0.1
- Operating System: macOS
- Browser: Firefox

**Comment by timarney** [comment]
Taking a quick look at this 

Some notes for sure there's an issue with the glider track calc --- 

In this screen 2 carousel one seems to have the issue but the other is okay

![Screen Shot 2022-10-28 at 6 10 14 AM](https://user-images.githubusercontent.com/62242/198563268-fb8655b2-c84b-40ef-a130-a618f953c319.png)

Resizing the viewport both end up in better shape

![Screen Shot 2022-10-28 at 6 10 47 AM](https://user-images.githubusercontent.com/62242/198563289-8409633e-998e-4299-8a33-5a10591b028f.png)

**Comment by timarney** [comment]
Can re-create in Chrome as well --- 

Looks like it's maybe a CSS / How many slides can fit in the area issue 

![ScreenFlow](https://user-images.githubusercontent.com/62242/198573093-e734e679-3f79-4712-b5a6-9501fa012e14.gif)

**Comment by timarney** [comment]
Toggling justify content - 

![toggle-css](https://user-images.githubusercontent.com/62242/198574034-42832c73-f830-48c8-9a55-a0a87a80f482.gif)

**Comment by swissspidy** [comment]
Does it break anything else? On bigger screens? When scrolling/swiping?

**Comment by timarney** [comment]
> Does it break anything else? On bigger screens? When scrolling/swiping?

From my testing seems to cover both large and smaller screens
 
 See:
https://www.youtube.com/watch?v=dCpdV3PurC0

Opened a PR
https://github.com/GoogleForCreators/web-stories-wp/pull/12562
