### ISSUE TITLE
Video Cropping: Handle element rotation 

### ISSUE THREAD

**Issue by timarney** [swissspidy/web-stories-wp#12203]
## Feature Description

PR #12156 handles off-screen cropping but not for rotated elements 

Per

> Would be nice to cater for element rotation here as well. Maybe in a follow-up, but I think we can avoid using custom checks for each side of the element here. Basically calculating the area of two overlapping rectangles.

This issue covers added detection for rotated off-canvas elements

https://github.com/GoogleForCreators/web-stories-wp/pull/12156#discussion_r959410395

**Comment by swissspidy** [comment]
Som example cases that would need to be covered when having to crop off-screen parts of a video:

![Screenshot 2022-09-20 at 14 00 57](https://user-images.githubusercontent.com/841956/191252434-bfdba296-5be5-4ce9-93e7-b49ad3561ce9.png)

![Screenshot 2022-09-20 at 14 00 01](https://user-images.githubusercontent.com/841956/191252436-b2acd13d-57be-4a8f-b0e6-da8cb0529051.png)


@miina Do we have any existing utils to help calculate this? Perhaps with SAT?

**Comment by miina** [comment]
https://www.npmjs.com/package/sat#satresponse - this is the information we get when testing two polygons colliding, looks like currently it doesn't reveal the collision points. Also found this issue in the repo with a link to an article about how to potentially get those points (didn't have time to check the link in detail right now):
https://github.com/jriecken/sat-js/issues/63
