### ISSUE TITLE
Media: Allow changing video volume

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12211]
## Feature Description

Allow changing video volume, perhaps with a simple range slider.

Volume can be passed via the `volume=""` attribute on `video`/`amp-video` (number between 0.1 and 1.0.)

Let's put something together behind a flag & then get UX feedback on it.

Of course with unit & Karma tests etc.

## Additional Context

* `1.0` is the default value, so in other words this can only be used to _reduce volume_ of a video. For increasing volume we'd need to use FFmpeg, which is a bit overkill for now.

**Comment by spacedmonkey** [comment]
Is there plans to add a volume option for background audio?

**Comment by swissspidy** [comment]
Not at the moment, because that doesn't work if not using `<amp-video>`. For that we'd need something more elaborate, like changing volume with FFmpeg etc. Maybe something for the future.
