### ISSUE TITLE
TypeScript: Convert `wp-story-editor` package

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12238]
https://www.npmjs.com/package/wp-types could be useful for typing REST API responses.

**Comment by swissspidy** [comment]
@spacedmonkey Just a heads up that this is still blocked by a few other tickets (mainly converting core story-editor types themselves), so it won't be easily possible to finish this just yet. Which is why this wasn't actually in the sprint yet.

**Comment by spacedmonkey** [comment]
Marked as blocked by design system type script conversion.
