### ISSUE TITLE
Date Picker: show timezone abbreviation if possible

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12234]
## Feature Description

In the WordPress block editor, the date picker shows the timezone abbreviation instead of the GMT offset if available:

<img width="345" alt="Screenshot 2022-09-06 at 10 10 23" src="https://user-images.githubusercontent.com/841956/188697991-03a72755-1ac8-4f9f-a62d-30a2ddb6349c.png">

https://github.com/WordPress/wordpress-develop/blob/9c45c9067903d9a80100d67db984bf25e5825865/src/wp-includes/script-loader.php#L379-L386

https://github.com/WordPress/gutenberg/blob/43d9c82922619c1d1ff6b454f86f75c3157d3de6/packages/components/src/date-time/time/timezone.tsx

It would be nice to do that as well in the story editor.

Should be trivial to adapt the code accordingly.

**Comment by spacedmonkey** [comment]
So should we just add some fields to Locale class called timezone abbr. Then we can just read this value in the editor.

**Comment by swissspidy** [comment]
Yes
