### ISSUE TITLE
Self Recording blur background causes image to freeze

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#12246]
## Bug Description
Originally reported by @spacedmonkey 
Mac OS - Safari, after setting blur background image freezes and never moves again. ( built in web cam and external web cam ). 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested using PR #12067 - bug still happens.

**Comment by felipebochehin87** [comment]
@merapi

**Comment by felipebochehin87** [comment]
Image is not freezing anymore, but once I switch on and off, it becomes super slow. Waiting to hear from devs about that. :)

**Comment by felipebochehin87** [comment]
Not freezing and performance improved. It's still a biiiiit slow, but way better if we compare to how it was before.
