### ISSUE TITLE
Self Recording - Blur background not working as expected in Firefox

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#12249]
## Bug Description

Originally reported by @spacedmonkey 

Mac OS - Firefox. Open the webcam dialog, select blur background. Close dialog. Reopen, see weird glitchy version of my image.
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Weird glitchy version of my image not happening anymore.

**Comment by spacedmonkey** [comment]
I am not seeing this issue anymore.
