### ISSUE TITLE
Media: `web_stories_muted_id` not cleaned up on attachment deletion

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12240]
## Bug Description

When muting a video, we set the `web_stories_muted_id` post meta on the original pointing to the muted version.

When deleting the muted version of a video, we do not reset/delete `web_stories_muted_id` accordingly, causing an invalid ID to be lingering in post meta.

## Expected Behaviour

**Cleanup**

Delete `web_stories_muted_id` post meta on the original when the muted version is deleted.

Similar to how we delete video posters when deleting an attachment in `\Google\Web_Stories\Media\Video\Poster::delete_video_poster()`

**Hardening**

In addition to that, we should update the `getMutedMediaById` API callback to catch errors from calling `getMediaById()` and return `null` in that case.

## Steps to Reproduce

1. Add video
2. Mute video
3. Delete muted video
4. Try to mute video again
5. Get error

## Additional Context

- Plugin Version: 1.24.0
- WordPress Version: 6.0
- Operating System: macOS
- Browser: Chrome

**Comment by spacedmonkey** [comment]
@swissspidy What about `web_stories_optimized_id`? Muted was copied from optimized? Should we fix both while we are at it?

**Comment by swissspidy** [comment]
Good catch! Yes let's fix both!
