### ISSUE TITLE
Embeds: Width and height not being respected

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#12241]
## Bug Description

When using a single Story embed code on a post/page you have the **width** and **height** values as part of this code. These by default are set to 360x600. A [user has reported](https://wordpress.org/support/topic/web-story-embed-into-classic-editor/#post-15986151) in the forums that when trying to adjust these values that they aren't changing. 

I have also been able to reproduce this on one of my test sites. If you look at https://acdwptesting.co.uk/2022/09/07/story-block/ the story on this page has width and height values set to 1000x1000. This doesn't always seem to happen with all of the embed codes I have tried with so I am not sure what is causing this to happen. With the example given above this seemed to happen after setting both values fairly low such as 200x200 and when trying to change back the Story remains at the same size whatever I try to change the values to.

Here is the current embed code for the example I have given above:

`[web_stories_embed url="https://acdwptesting.co.uk/web-stories/testpublish1/" title="TestPublish1" poster="https://acdwptesting.co.uk/wp-content/uploads/2022/08/cropped-2-abstract-art-original-tree-moon-landscape-painting-prints-home-decor-megan-duncanson-megan-duncanson-1.jpg" width="1000" height="1000" align="none"]`

## Expected Behaviour

When changing the width and height values the Story should update to the values set in the embed code. 

## Steps to Reproduce

Not always able to reproduce but these are the steps taken:

1. Create and publish a Story making sure to add to post to get the embed code.
2. On that post or another use the embed code.
3. Change the values gradually lowering them.

## Screenshots

N/A

## Additional Context

This seems to happen on a clean WordPress install with just the Stories plugin with the Twenty Twenty theme so doesn't seem to be related to any conflict.

**Comment by marsboul2d** [comment]
Hi Adam,
We have this problem on our website : 
[https://vracnroll.com/consigne/](https://vracnroll.com/consigne/)

It was previously working fine earlier on our website (2 months ago), so I think it could be a recent WordPress update.

Here is the embed code used : 
`[web_stories_embed url="https://vracnroll.com/web-stories/la-consigne-gratuite/" width="360" height="600" align="center" title="La consigne gratuite à vie"]`

**Comment by barbler** [comment]
Yes, I am looking forward to the resolution of this bug.  I am using Classic editor.

**Comment by barbler** [comment]
@swissspidy Will you be getting to my issue soon? Again, I am the one who uses classic editor and changing the dimension on the short code does not make a change in the size of the story.  Therefore, on the laptop, the story shows up way too large.  Thank you

**Comment by swissspidy** [comment]
I can‘t provide an ETA for when this will be fixed, but this is clearly on our radar.

**Comment by barbler** [comment]
@swissspidy Hi again.  I just wanted to point out my exact code...and thinking is it possibly the alignment what is keeping the post not adjusting?  and I originally asked, would this be a theme issue overriding the sizing on my post page?

<p>[web_stories_embed url="https://www.lepplerinjurylaw.com/web-stories/motorcycle-accident-causes/" title="The Most Common Motorcycle Accident Causes" poster="https://www.lepplerinjurylaw.com/wp-content/uploads/2022/03/cropped-Motorcyle-safety-is-priority-1-640x853.jpg" width="270" height="450" align="none"]</p>

Here is the link to the post that I have the web story on:
https://www.lepplerinjurylaw.com/blog/motorcycle-accident-claim-denial/

Thank you.

**Comment by swissspidy** [comment]
Yes there can be theme issues and yes alignment can play a role. You could try `align="center"`, that should work for your theme / use case.

**Comment by barbler** [comment]
Wow.  That was it. It fixed the size of my google web story.  You can close my case.  Wonderful!  Thank you so much!
