### ISSUE TITLE
Self Recording blur background is not handling all cameras aspect ratio properly

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#12245]
## Bug Description
Originally reported by @spacedmonkey 
Mac OS - Chrome. Image is looked strange. ( before and after adding blur ). Makes me look thinner. Only does this on external webcam. 

![image1](https://user-images.githubusercontent.com/58738530/188935274-238e8092-98bd-4811-80cf-f4b68f3cd9a6.png)

## Expected Behaviour

Camera image aspect ratio should be retained for all resolutions.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
@merapi @spacedmonkey I don't have an external webcam to test this one. I checked on Firefox, Chrome and Safari, the three browsers on both Windows and Mac, it looks good using built-in camera. Would you please check with an external camera? Thanks!

**Comment by spacedmonkey** [comment]
@felipebochehin87 You could use an app like [camo](https://reincubate.com/camo/), that let's you use your phone as a webcam, as a way to test. Camo seems to work on ios and andriod, so you should be able to get something working. Also, if you have a canon camera, you can use [Canon EOS Webcam Utility](https://www.canon.co.uk/cameras/eos-webcam-utility/).

**Comment by spacedmonkey** [comment]
https://user-images.githubusercontent.com/237508/189877700-6f08efa8-a9b7-4b52-aa64-6d59216de00c.mov

I am not seeing this issue anymore.
