### ISSUE TITLE
Add data migrations to remove lingering properties

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12258]
## Feature Description

This is a follow-up to #12131.

Despite previous migrations, there can be stories with lingering `backgroundOverlay` and `fontWeight` properties on elements. Let's add two migration functions that remove these.

See ac52897ed23f4b3e3233a495d54637119c970652

**Comment by miina** [comment]
Hm, any idea where these come from?
`fontWeight` was removed in migration V17 and `backgroundOverlay` was converted into `overlay` in V26. Are these still added somewhere in code, or did it come from the templates?

**Comment by swissspidy** [comment]
Not sure, couldn‘t find anything in the code. Seems to be coming from the templates
