### ISSUE TITLE
Floating Toolbar - Lock Placement - Icon to show menu impacts the carousel thumbnail location

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#12251]
## Bug Description

Selecting the “Always hide option” presents an icon along the bottom that bumps the carousel thumbnails to the left and they are no longer centered in the canvas

![image6](https://user-images.githubusercontent.com/58738530/188946184-a5233684-dae6-43d7-af04-579f396cb9ee.png)

****
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by barklund** [comment]
This is actually now fixed better in #12929, as there's a slight redesign there as well.

**Comment by kkalarickal** [comment]
Confirmed fix in `12929 branch`

Before:
![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/407cc644-a447-43d9-8708-742d00e63ebe)

After:![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/47a799ac-a65d-4e63-a0ed-610862a6a7c6)
