### ISSUE TITLE
On small screens the floating toolbar's menu items are not responding to mouse events correctly.

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#12253]
## Bug Description

Originally reported by @timarney 

Seems to be an issue if floating menu is at the bottom (other elements blocking mouse events) see
https://drive.google.com/file/d/1Lf1m8QFhm6sUMOr8CtioxuAHZAk36wyP/view?usp=sharing

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
This is a duplicate of #10406 -- different symptoms, same issue.

**Comment by miina** [comment]
Closing as duplicate of #10406
