### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'top')

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12273]
## Bug Description

Two users have reported that editing text on the last page of the Web Story caused the editor to crash. 

Support topics: 
https://wordpress.org/support/topic/click-double-on-text-giving-error/
https://wordpress.org/support/topic/editor-is-crashing/

This user reported editor crashed when editing text as well. 
https://wordpress.org/support/topic/editor-is-crashing-when-creating-new-and-updating-webstories/

## Expected Behaviour
As a user, I want to be able to edit the text on the last slide without the editor crashing. 

## Steps to Reproduce

Unable to reproduce it at the moment.

## Additional Context

Site Health information:
https://docs.google.com/forms/d/1CSdMaWCwfivOaImRfcUpMJELhjO9Lk7sbqbQlzvh0u0/edit#response=ACYDBNh9Vse_02xKzSS-73h-TOrPudKn3nJJXkzJJ50fcMQ6vWeFNGpKIl1-1K9CEnhOfhc

https://docs.google.com/forms/d/1CSdMaWCwfivOaImRfcUpMJELhjO9Lk7sbqbQlzvh0u0/edit#response=ACYDBNhjZrUhp0meqWlwYTGGzsR2nDXf03WWH7E0kSm8iFZEqkStOqQO1VPqegYkBtdtBpo

- Plugin Version: 1.24.0
- WordPress Version: 6.0.2
- Operating System: Windows
- Browser:

**Comment by swissspidy** [comment]
After looking through the code I found how this could happen.

When using the "Reset element" quick action, the element's `border` property is reset to `null`.

https://github.com/GoogleForCreators/web-stories-wp/blob/7b39d7209bd461c4a98dc6df46c3ef1535ab2abe/packages/story-editor/src/app/highlights/quickActions/useQuickActions.js#L383-L387

The `TextEdit` component breaks when `border` is not an object:

https://github.com/GoogleForCreators/web-stories-wp/blob/7b39d7209bd461c4a98dc6df46c3ef1535ab2abe/packages/element-library/src/text/edit.js#L135-L142

Remember: default values for props only works if the props is absent/undefined, not when it's `null`.

So this needs extra hardening to also cater for `null` values.

**To reproduce:**

1. Create a new text element
2. Add a border
3. Click on "Reset element" quick action
4. Click on text element to edit it
5. See editor crashing

cc @merapi @miina

**Comment by felipebochehin87** [comment]
No crash detected! Tested on Firefox, Chrome and Safari on both Windows and MacBook. PR #12299.

https://images.zenhubusercontent.com/235435637/0231008b-6e1a-4b6f-970c-ad645e1ae678/2022_09_13_21_12_37.mp4
