### ISSUE TITLE
'The post type web-story is not registered' error when inserting web story using `wp_insert_post` function.

### ISSUE THREAD

**Issue by nitishkgupta** [swissspidy/web-stories-wp#12319]
## Bug Description

Getting the following error while inserting web stories programmatically using the `wp_insert_post` function. Note: The error is occurring only when the insert function is called while being logged out and works fine if the user is logged in.

> Function map_meta_cap was called incorrectly. The post-type web-story is not registered...

## Possible Fix

I checked the plugin source code and found that this might be occurring as the `register_post_type` function in this plugin is not hooked with the `init` hook. According to [WordPress documentation](https://developer.wordpress.org/reference/functions/register_post_type/#description): 'Note: Post type registrations should not be hooked before the ‘init’ action.

I think this error might get fixed if the `register_post_type` is hooked properly after the `init`.

## Additional Context

- Plugin Version: 1.24.0
- WordPress Version: 6.0.2
- Operating System: Windows 11
- Browser: Google Chrome

**Comment by swissspidy** [comment]
The web-story post type is registered on `init` with priority `10`.

So as long as you insert your post on a later priority, it should work just fine.

Proof:

```php
add_action(
	'init',
	static function() {
		if ( ! is_user_logged_in() ) {
			wp_insert_post([
				'post_title' => 'This works',
				'post_type'  => 'web-story',
			]);
		}
	},
	11
);
```

**Comment by nitishkgupta** [comment]
Thanks, @swissspidy. The error gets resolved after I moved the inserting function from the default `init` to `wp_loaded`.

I'm currently inserting the custom amp HTML source code directly using the 'post_content'. This is working fine until the function is called while logged in. When the function is called without being logged in, the web story gets inserted but has formatting issues (invalid amp HTML), and as a result, the web story is broken and not valid. Let me know if this can be fixed, and how if so.

**Comment by swissspidy** [comment]
If you are not logged in as an administrator or editor or someone else with `unfiltered_html` capabilities, the KSES functionality in WordPress will strip a lot of HTML and CSS from the `post_content` for security reasons. That's why our plugin makes changes to KSES to prevent that.
Second, the plugin uses so-called AMP sanitization to ensure valid AMP HTML. Check out the code base to see how it's done.

So if your doing something completely custom you'd have to deal with KSES and AMP sanitization accordingly yourself.
