### ISSUE TITLE
Video Cropping: Add post meta for original

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12310]
Add post meta to the cropped video containing the ID of the original, if we ever need it.

**Comment by spacedmonkey** [comment]
Should this post meta work similar to trimming? So it links to the original video. What happens if you crop multiple times. Do you link to the original video on the last crop?

**Comment by swissspidy** [comment]
I think that would be overkill und not informative, since the cropping is never based on the original. So it should just reference the current version, not the original. So no, not the same as trimming.

We can of course always revisit this later if needed.

**Comment by spacedmonkey** [comment]
I agree. I think it should just store the video being cropped. If we add functionality to revert / undo a crop, you should have to revert / undo until you get back to the original video.
