### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'scale')

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12323]
## Bug Description

This issue has been reported in the support forums twice in the last two weeks so I am opening this ticket to track. Unfortunately, there isn't much information or details on the steps leading up to this error, but I will update this issue with more details once provided.

Please see the support topics for the full TypeError message.

## Additional Context

https://wordpress.org/support/topic/keep-getting-this-error-something-went-wrong-the-editor-has-crashed-please-t/
https://wordpress.org/support/topic/web-stories-the-editor-has-crashed/

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Haven't seen this in a while and unable to reproduce, closing for now.
