### ISSUE TITLE
Resolve normal vs regular font styles

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#12333]
## Bug Description

Font styles should only be _normal_ or _italic_. However, we use _regular_ in some places. Mostly when referring to font families (where _regular_ is common parlance rather than _normal_), but we should make sure we never assign _regular_ as the font style of a text element anywhere.

Edit: When removing `regular` from the codebase, please remove it from the FontStyle type, too.

**Comment by swissspidy** [comment]
Probably comes from the Google Fonts API. See fonts.json / https://developers.google.com/fonts/docs/developer_api
