### ISSUE TITLE
Page background audio is not playing as expected when there is a Story background audio file set

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#12339]
## Bug Description

A story that has a background audio set will not play individual page audio as expected when it encounters such a page. It just continues playing the same audio.

eg - https://stories-new-wordpress-amp.pantheonsite.io/web-stories/bg-audio-test/

## Expected Behaviour

It was my understanding that specifying a bg audio file for a specific page in a story will play mean that this file is played instead of any story level bg audio. 
## Steps to Reproduce

I created a 3 page story to validate that a story that has a audio background set for a specific page will play instead of the background audio set for the story.

For the story I used the following file to link to and set as the story background audio file 
https://www.dofactory.com/media/epic.mp3
 
I linked to this file in the Document panel and set it as the story background

I then created a second page where I set a different audio file (local) to use as the page background in this specific page.

Then I added a third page to confirm that the audio can go back to the global background audio file when a specific bg audio file for this page hasn't been set.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
> It was my understanding that specifying a bg audio file for a specific page in a story will play mean that this file is played instead of any story level bg audio.

*Both* are supposed to be playing in that case

**Comment by swissspidy** [comment]
I see that the page bg audio on the 2nd page isn't always consistently playing. For that there are several related issues on the AMP repo:

* https://github.com/ampproject/amphtml/issues/38139
* https://github.com/ampproject/amphtml/issues/37243
* https://github.com/ampproject/amphtml/issues/36710
