### ISSUE TITLE
TypeError: Cannot destructure property 'Display' of 'TV(...)' as it is undefined.

### ISSUE THREAD

**Issue by ashita260120** [swissspidy/web-stories-wp#12352]
TypeError: Cannot destructure property 'Display' of 'TV(...)' as it is undefined.
    in DisplayElement
    in div
    in pagepreview__PreviewWrapper
    in button
    in pagepreview__Page
    in Unknown
    in TransformProvider
    in Unknown
    in UnitsProvider
    in PagePreview
    in div
    in reorderableItem__Container
    in ReorderableItem
    in carousel__ReorderablePage
    in div
    in carousel__ItemContainer
    in div
    in reorderable__ReorderableContainer
    in Unknown
    in ForwardRef(Reorderable)
    in carousel__PageList
    in section
    in carousel__Wrapper
    in Carousel
    in div
    in layout__CarouselArea
    in section
    in layout__Layer
    in NavLayer
    in div
    in selectionCanvas__Container
    in Unknown
    in ForwardRef(WithOverlay)
    in SelectionCanvas
    in div
    in canvasElementDropzone__Container
    in CanvasElementDropzone
    in div
    in dropTarget__Content
    in Unknown
    in div
    in dropTarget__DropTargetComponent
    in UploadDropTarget
    in CanvasUploadDropTarget
    in section
    in canvasLayout__Background
    in se
    in CanvasLayout
    in Canvas
    in lK
    in div
    in layout__CanvasArea
    in Unknown
    in RichTextProvider
    in Unknown
    in UnitsProvider
    in Unknown
    in CanvasProvider
    in Workspace
    in section
    in layout__Editor
    in Unknown
    in LayoutProvider
    in m$
    in Unknown
    in DropTargetsProvider
    in Unknown
    in TransformProvider
    in Unknown
    in MediaProvider
    in Unknown
    in FontProvider
    in Unknown
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in FileProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in lK
    in Ge
    in se
    in App
    in StrictMode
    in FlagsProvider

**Comment by swissspidy** [comment]
Heya, thanks for reaching out.

Could you perhaps provide more information about the steps to reproduce this error?

If you could share the URL to your story, that would be great.
