### ISSUE TITLE
Video cropping: Allow for video cropping of background media

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#12358]
## Feature Description

Allow for video set as background to be cropped. 

<img width="436" alt="Screenshot 2022-09-22 at 10 05 30" src="https://user-images.githubusercontent.com/237508/191713754-ab70e1c6-115e-4056-830a-755263b2a7ff.png">
<img width="434" alt="Screenshot 2022-09-22 at 10 05 18" src="https://user-images.githubusercontent.com/237508/191713764-d02ac59f-0875-4e8a-bbcc-a2f9082bd4ff.png">

**Comment by swissspidy** [comment]
Closing in favor of #5985
