### ISSUE TITLE
Editor Media Library Not loading any content - infinite AJAX requests to context API endpoint

### ISSUE THREAD

**Issue by kujain** [swissspidy/web-stories-wp#12368]
## Bug Description
The media library does not load any media/images in the container at the left. We can observe an infinite loop issue with the context ajax call loading multple pages without any end, even though that story does not have do many image files!
The ajax call seems to be worjing as expected as it returns the media info (screenshot 2) but it appears that due to so many sequential ajax calls, the browser engine is not getting time to refresh the UI.

## Expected Behaviour
The media loader should stop after the first call since we do not have more than 50 images in the story.

## Screenshots
![image](https://user-images.githubusercontent.com/120631/192053970-14849a5a-c8f4-45da-bbe1-b4d806db5fea.png)
![image](https://user-images.githubusercontent.com/120631/192054480-4cf65948-7c0b-4cca-a22e-c5466b8a874c.png)

https://user-images.githubusercontent.com/120631/192056121-4cd2137b-f405-47a8-87d0-31e9ec85106a.mov

## Additional Context

- Plugin Version: 1.25.1
- WordPress Version: 5.9.4
- Operating System: NGINX
- Browser: Chrome 105.0.5195.125

**Comment by swissspidy** [comment]
> The media loader should stop after the first call since we do not have more than 50 images in the story.

The number of images in the _story_ is irrelevant. Did you mean in your _WP media library_? It says you have over 174000 items in the library.

That shouldn‘t cause this bug though.

Please try updating WordPress to the latest version. Also try temporarily disabling all other plugins and please share your Site Health information so that we can try to investigate further.

**Comment by kujain** [comment]
Thanks for your quick response @swissspidy !

> The number of images in the story is irrelevant. Did you mean in your WP media library? It says you have over 174000 items in the library.
I agree. As you saw, we have 170K+ images in our media library but the stories media uploader interface shows the latest 50 images only in one load call, so our total should be irrelevant to this issue. 

We are not currently able to upgrade to 6.x at this time unfortunately. Our site health status shows the following:
![image](https://user-images.githubusercontent.com/120631/192162098-b37a71e4-1ebd-4ced-9906-7e8149eb429c.png)

I see a REST API error here and I will investigate that further.

However, one thing I would like to point out is that we have a mirror test environment which has the same codebase as our live - only content is a little older. The above issue does NOT occur there - which may point to a configuration or content related issue?
![image](https://user-images.githubusercontent.com/120631/192162526-567aa050-d9fe-4765-902c-014c90dd5643.png)

Thanks!

**Comment by swissspidy** [comment]
> Our site health status shows the following:

Please go to the "Info"  tab and click on "Copy site health data to clipboard" and share this information here.

<img width="990" alt="Screenshot 2022-09-28 at 09 12 50" src="https://user-images.githubusercontent.com/841956/192712587-1286205c-076f-41ea-8c8d-7a0d6ff31a45.png">

> I see a REST API error here and I will investigate that further.

Let us know once you have addressed this.

> One thing we also noticed in our console are a number of secutity-related errors eg.

Try temporarily disabling all other plugins and use a different theme (e.g. Twenty Twenty) to see if that makes a difference.

The [Health Check & Troubleshooting](https://wordpress.org/plugins/health-check/) plugin is a great way to do that without interrupting your visitors.
