### ISSUE TITLE
Some templates are displaying "Prompt" in the floating toolbar font dropdown

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#12367]
## Bug Description

When using a Story template I noted that when I selected some text elements the toolbar showed "Prompt" instead of the font name as expected
![Screen Shot 2022-09-23 at 11 51 24 AM](https://user-images.githubusercontent.com/58738530/192002295-59438c26-28ef-4684-9909-64938ecda258.png)

## Steps to Reproduce

1. Go to the Dashboard and select Explore Templates
2. Select the template titled "Sustainability Tips"
3. Select a text element on a page
4. Note that the floating toolbar displays the font of the selected element as "Prompt"
5
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
The font is called [Prompt](https://fonts.google.com/specimen/Prompt?query=Prompt).
