### ISSUE TITLE
window.MediaInfo is not a function

### ISSUE THREAD

**Issue by timarney** [swissspidy/web-stories-wp#12377]
Seeing `window.MediaInfo is not a function` in some cases while working on #12335

https://github.com/GoogleForCreators/web-stories-wp/pull/12335#issuecomment-1255910357

<img width="1209" alt="191624734-29f3c2ea-dc4d-40f1-98f9-d63d80994a1d" src="https://user-images.githubusercontent.com/62242/192462478-8582fa37-f19a-4618-95ff-10ca89093918.png">

**Comment by swissspidy** [comment]
#12335 has a fix for this now (d4dfd4e7be9179b639ef2667570c2731e2594294), so I'll close this one
