### ISSUE TITLE
Video trim does not work in Windows 10 + Opera

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#12378]
## Bug Description

Video trim fails in Windows 10 + Opera as reported in https://github.com/GoogleForCreators/web-stories-wp/pull/12344#issuecomment-1258882014.

## Expected Behaviour

Trim should work.

## Steps to Reproduce

1. Add a local video to canvas
2. Try to trim it

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/10549936-430a-44bf-8e1a-09cf901232f1)

## Additional Context

- Plugin Version: main
- WordPress Version:
- Operating System: Windows 10
- Browser: Opera

**Comment by swissspidy** [comment]
Seeing some `RangeError: WebAssembly.Memory(): could not allocate memory` errors in Opera on Windows 10
