### ISSUE TITLE
Prevent user from publishing until poster image has been set

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12374]
## Feature Description

A User would like a way to prevent the story from getting published until the poster image has been set or critical errors are resolved.

Original support topic: https://wordpress.org/support/topic/post-image-upload-mandatory

## Alternatives Considered

Review the pre-published checklist in the editor and in the modal for issues to resolve.

**Comment by swissspidy** [comment]
The pre-publish checklist is already quite prominent, closing for now
