### ISSUE TITLE
Background Audio conflicting with links

### ISSUE THREAD

**Issue by DanielCryptoK** [swissspidy/web-stories-wp#12384]
Hi

I have just noticed that all of my web stories are not working correctly due to the links not being clickable. See example below with picture of page to check in this image. https://www.webpagescreenshot.info/#v2=s2kNKTH_c

https://bitcoin-casino-no-deposit-bonus.com/web-stories/bc-game-review/

**Comment by swissspidy** [comment]
Thanks for your report. We'll look into what's causing this exactly.

In the meantime, can you try removing background audio on these pages to see if it helps? As odd as it may sound, there could be a clash there.

**Comment by DanielCryptoK** [comment]
Hi

I removed the audio which also removed the subtitles and the click now works. How to fix so can add back?

Also the button after updating the post in editor to view the web story is missing.

**Comment by swissspidy** [comment]
> How to fix so can add back?

I repeat, we will look into it.

> Also the button after updating the post in editor to view the web story is missing.

Can you clarify / share a screenshot? Are you referring to this Preview button?

![Screenshot 2022-09-29 at 15 33 11](https://user-images.githubusercontent.com/841956/193045597-981d3808-d806-42cc-b366-717ef7c733d9.png)

**Comment by DanielCryptoK** [comment]
My mistake as I was sure a button in the bottom left corner used to pop up to say view story after editing, but maybe I am getting confused.

**Comment by swissspidy** [comment]
This will be fixed in our next release

**Comment by DanielCryptoK** [comment]
When is the next release date as this problem is costing me money.

**Comment by swissspidy** [comment]
In the next 1-2 weeks

**Comment by DanielCryptoK** [comment]
OK, please can you help me on the video indexing problem as no one is answering my ticket and I am completely stuck and dont know what to do. Google says tickets are normally answered in 48 hours and its been 1 month https://support.google.com/webmasters/thread/177831693?hl=en

**Comment by swissspidy** [comment]
I'm afraid we do not provide support for video indexing or other search-related topics here.

I recommend waiting for a reply on your topic and reading the [help article about the video indexing report](https://support.google.com/webmasters/answer/9495631?hl=en).

**Comment by DanielCryptoK** [comment]
@swissspidy Hi, you said that this would be fixed in two weeks and its been 15 days. That means I have gone half a month without my main source of income working and this is at a horrible time with the world collapsing. Please can you let me know when this will be fixed so that your plugin stops costing me money. Thanks

**Comment by swissspidy** [comment]
We hit some delays with the current release, but we should be able to release it next week or so. You'll get a notification in your WordPress admin once it is out.

**Comment by DanielCryptoK** [comment]
@swissspidy any update on this as it is simply not acceptable to have my income effected for so long due to an error with your plugin. Surly I can not be the only person to think that this is extremely unreasonable and no plugin should cost a user money due to it been broken for so long. I have also just had my hosting company check what is causing the error below and they say it is your plugin:

[Tue Oct 25 00:21:53.243751 2022] [proxy_fcgi:error] [pid 21219:tid 140029196125952] [client 2601:601:1281:17b0:2c49:53b2:4ce1:4264:0] AH01071: Got error 'PHP message: slide list from 0 to 1', referer: https://bitcoin-casino-no-deposit-bonus.com/cafe-casino-no-deposit-bonus-code-february-2022/

See the attached errors

![web stories](https://user-images.githubusercontent.com/45933242/197764783-81f87c3f-7795-4aa0-b4e4-31cff80c47fd.png)

**Comment by DanielCryptoK** [comment]
We are now over 1 month since I reported this error and you said 1 to 2 weeks for a fix. I am very certain that you would not be happy if a plugin had been costing you money for over 1 month because the advertisement links don't work. Is there anywhere I can make an official complaint about this?

I am also getting images blocked now and it says by robot txt but that does not make sense to me. Please see my robot txt below and advise what to change or if this is yet another bug.

User-agent: *
Disallow: /wp-admin/
Disallow: /wp-login.php
Allow: /wp-admin/admin-ajax.php
Sitemap: https://bitcoin-casino-no-deposit-bonus.com/sitemap_index.xml

EXAMPLE ERROR

Googlebot blocked by robots.txt
Image
https://bitcoin--casino--no--deposit--bonus-com.cdn.ampproject.org/i/s/bitcoin-casino-no-deposit-bonus.com/wp-content/uploads/2021/07/bcnbd-rounded-512-250x250.png

**Comment by swissspidy** [comment]
@DanielCryptoK We released a plugin update last week.

**Comment by DanielCryptoK** [comment]
@swissspidy Do you know why googlebot is blocking web stories images?????

**Comment by swissspidy** [comment]
We do not provide support for crawling and indexing questions here, please check out https://developers.google.com/search/docs/crawling-indexing and the help community there for these kind of questions.

That said, this looks as expected.

`https://bitcoin--casino--no--deposit--bonus-com.cdn.ampproject.org/i/s/bitcoin-casino-no-deposit-bonus.com/wp-content/uploads/2021/07/bcnbd-rounded-512-250x250.png` is cached version of your image `https://bitcoin-casino-no-deposit-bonus.com/wp-content/uploads/2021/07/bcnbd-rounded-512-250x250.png` in the AMP cache.

The AMP cache blocks indexing from crawlers, because obviously a crawler should index the original at `https://bitcoin-casino-no-deposit-bonus.com/wp-content/uploads/2021/07/bcnbd-rounded-512-250x250.png` and not the cached version.

So I don't see an issue here. But again, please use https://developers.google.com/search/help for any questions related to search rankings.
