### ISSUE TITLE
Changing animation pan direction doesn't always work

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#12380]
## Bug Description

Changing pan animation direction can fail as reported in https://github.com/GoogleForCreators/web-stories-wp/pull/12344#issuecomment-1258882014.

## Expected Behaviour

Animation should change to "Pan right" as intended.

## Steps to Reproduce

1. Add a landscape background image
2. Go to the animation panel and select "pan left" from the drop down
3. Close the drop down and click the right arrow to change pan from left to right
4. Observe that a warning is thrown and the animation is set to "none"

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/ac434284-6f9c-4dc7-9e8a-12088cad50e5)

## Additional Context

- Plugin Version: main
- WordPress Version:
- Operating System: Windows 10
- Browser: Opera

**Comment by miina** [comment]
To confirm: Is this in Opera only? As mentioned in additional context.

**Comment by swissspidy** [comment]
cc @kkalarickal as you originally reported it
