### ISSUE TITLE
Story Locking - multiple notifications shown for users who have bypassed the first dialog

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#12436]
## Bug Description
Originally reported by @barklund 

Using the above workaround (#12434) to keep working on a story I don’t have the lock for, I was able to create a situation where I both have a local backup of the story but not the lock for it, so I get double dialogs (the local backup dialog is on top):

![image2](https://user-images.githubusercontent.com/58738530/194154136-434e2aea-cec1-47a1-bc8b-3eda861a5ad8.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
We'll just fix the root cause so that users don't ever get this far. -> #12430
