### ISSUE TITLE
Design System: Dialog overlay prevents access to WP admin menu

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#12433]
## Bug Description
Originally reported by @barklund 

When a dialog (e.g. the “story is locked” dialog) is showing, the dialog grayout is above the main WP menu dropdowns, so you cannot actually use the WP menu while any dialog is showing.

## Additional Context

This was flagged as something that should be fixed prior to the 1.26 release next week.

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
FWIW, same goes for the publish modal as well, it's really any kind of dialog.

The admin submenu has z-index 3, while our overlay has z-index 10.

#12443 might fix this, though I couldn't test it right now.
