### ISSUE TITLE
Story Locking - delay in notification allows for concurrent editing by more than one user

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#12435]
## Bug Description

If someone takes over your story, you are not informed immediately. But you are allowed to make changes and save them (thus effectively still being in control) for a few minutes. I get that we can’t push the take over message instantly to the client, but we should at least not allow saving and display the message as an error if you do try to save.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
The timeout is defined by WordPress.

As for saving, we should check what WordPress does there.

**Comment by swissspidy** [comment]
From #12413 

> It seems to me that the window of opportunity where both sessions can be edited simultaneously is different from the workflow for the WP Post, where the momment user B takes over, user A can no longer edit.

So while we use the same interval as WP, for some reason in Gutenberg the dialog is displayed much quicker.

Also, it leads to this bug:

> However, I also tested the scenario where in step 6 the user B makes some changes in return and there are two different autosaves present in each browsers session storage. This yields a overlapping set of overlays for user A that is very confusing
