### ISSUE TITLE
Story Locking: Improve wording

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12442]
## Feature Description

The wording in the WP story locking dialog is better than ours. We can improve that a bit.

![Screenshot 2022-10-07 at 17 20 54](https://user-images.githubusercontent.com/841956/194590777-924f0ee2-1fe5-42b3-88cb-fc9d7a5630a0.png)
<img width="697" alt="Screenshot 2022-10-07 at 17 21 28" src="https://user-images.githubusercontent.com/841956/194590781-916bbd4c-296c-4ab3-aa02-e6d9f61a1e91.png">

**Comment by spacedmonkey** [comment]
@swissspidy What do you recommend here?

**Comment by swissspidy** [comment]
I‘ll whip something up
