### ISSUE TITLE
Web-story auto save session storage key is not deleted after saving draft resulting in unnecessary keys left behind in session storage

### ISSUE THREAD

**Issue by kkalarickal** [swissspidy/web-stories-wp#12444]
As part of testing the auto-save feature, I compared how auto-save works for wp-post vs wp-web-story.

I noticed that when a draft story is edited, there is a `wp_stories_autosave_story_12345` created (where 12345 is the post-id for the web-story). This is similar to the `wp-autosave-block-editor-post-67890` that is created when a draft wp-post is edited (here 67890 is the post-id for the wp-post)

However, when the wp-post draft is saved, the corresponding `wp-autosave-block-editor-post-67890` key is deleted immediately.

However, when the wp-story draft is saved, the corresponding `wp_stories_autosave_story_12345` is NOT deleted.

This results in several `wp_stories_autosave_story_NNNN` remaining in session storage even though the corresponding draft stories were saved to database.

![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/d9e1fbcb-af5e-4fc6-8028-2dd851d1f4d7)

**Comment by kkalarickal** [comment]
Note: the key is deleted when the story is re-opened within the same browser session. This means that if the story is NOT reopened, then the session storage will continue to retain these keys, even if the same story is published/deleted or otherwise manipulated in another browser session.

**Comment by swissspidy** [comment]
Wait, isn‘t that exactly what #12417 was supposed to fix? cc @miina

**Comment by kkalarickal** [comment]
@swissspidy -- I believe #12417 handles deletion of the `wp_stories_autosave_story_auto-draft`. This is the key created for unsaved draft story.

My observation was about the ` wp_stories_autosave_story_12345`. This is the key for unsaved changes for a saved draft.

There seems to be a difference in how wp-stories and wp-post behaves when dealing with the keys in the session storage. I wanted to point out this difference since the functionality seems to work for the user, but the way the keys are handles leaves old info hanging around when it does not seem necessary.

**Comment by miina** [comment]
> Wait, isn‘t that exactly what https://github.com/GoogleForCreators/web-stories-wp/pull/12417 was supposed to fix? cc @miina

Yep, that PR addressed drafts specifically... need to adjust it again for non-drafts.
