### ISSUE TITLE
Author users and below not seeing story takeover dialog

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12441]
## Bug Description

I noticed in testing that when an author user's story is taken over by someone else, they don't see the dialog at all. This is because there's no `user` object since it's absent from the REST API due to lack of capabilities to list users.

## Expected Behaviour

Author users or contributors should still be able to see a takeover dialog.

## Steps to Reproduce

1. Create story as author
2. In a new window, take over editing as an admin
3. As an author, there should be a takeover message, but there isn't

## Screenshots

<img width="764" alt="Screenshot 2022-10-07 at 17 15 25" src="https://user-images.githubusercontent.com/841956/194589687-18b5d9dc-b78d-4a8f-a95a-e1d3a644961b.png">

https://github.com/GoogleForCreators/web-stories-wp/blob/31d01788be3a19732f0fc03085183cb6223260ca/packages/wp-story-editor/src/components/postLock/postLock.js#L189

It works in WordPress:

<img width="697" alt="Screenshot 2022-10-07 at 17 21 28" src="https://user-images.githubusercontent.com/841956/194590425-f079859c-577d-40d2-907c-f3166568cf32.png">

## Additional Context

- Plugin Version: 1.26.0-alpha
- WordPress Version: 6.1-beta
- Operating System: macOS
- Browser: Chrome

**Comment by spacedmonkey** [comment]
<img width="1754" alt="Screenshot 2022-10-10 at 14 19 24" src="https://user-images.githubusercontent.com/237508/194875832-0f5372fa-f23f-4a47-9001-6c4b7c40d55c.png">

@swissspidy I am not seeing this issue. Is anyone else about to replicate this? I tested with an author and contributor.

**Comment by swissspidy** [comment]
I‘ll re-test again.

Just a quick thought: maybe it happemed when editing a story with a different user set as the author? i.e. the user with author role editing a story created by an admin

**Comment by spacedmonkey** [comment]
Still can't replicate it. If you can replicate, can you upload a video? Maybe I can do it locally as well.

**Comment by swissspidy** [comment]
Here you go:

https://user-images.githubusercontent.com/841956/194913293-0e860fcd-349e-4a15-84f8-38a3d8edac70.mov

The author user is not seeing the takeover dialog, and weirdly enough then it simply takes over the lock again from the admin, very strange.

**Comment by spacedmonkey** [comment]
I am not seeing this. 


https://user-images.githubusercontent.com/237508/195352280-45117a3f-226f-4def-ab1b-a268095b192c.mov

<img width="449" alt="Screenshot 2022-10-12 at 14 14 20" src="https://user-images.githubusercontent.com/237508/195352386-b08a6162-3dc8-4532-a7bc-90ee22c54b55.png">

@timarney Can you replicate?

**Comment by swissspidy** [comment]
@kkalarickal Can you reproduce this?

**Comment by kkalarickal** [comment]
No. Author does get a take over dialog.![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/917adc78-e4f2-4dc3-8f7c-ea171b5996e4)

But comparing with the similar WP Post scenario it takes a significantly long time to get the dialog.

@swissspidy -- the weirdness you observed:
> weirdly enough then it simply takes over the lock again from the admin, very strange

This is explained by the bug where Author can click into a story even if you see the dialog. The auto-save may have kicked in and "re-taken" the story.

**Comment by swissspidy** [comment]
> This is explained by the bug where Author can click into a story even if you see the dialog.

I don't think I was doing that, but I will check again.

**Comment by spacedmonkey** [comment]
The bug could come from this crunk of [code](https://github.com/WordPress/wordpress-develop/blob/70dedb086602287f4e0ee97fbf477adda8310963/src/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php#L439-L451). 

As we are using our own endpoint, it would simple to override this method with our own logic. Check if the request is embedded and not show that permission message.

**Comment by swissspidy** [comment]
Yes! The second condition looks like the culprit. Wondering why you don't run into it though. 🤔 

> Check if the request is embedded and not show that permission message.

The capability checks are there for a reason, I don't wanna introduce any security issue with that. Especially since user requests could be embedded in other requests too, not just in the lock controller.

**Comment by swissspidy** [comment]
Maybe we should just pass the user name & avatar as regular REST fields instead of using embeds?

**Comment by swissspidy** [comment]
> Maybe we should just pass the user name & avatar as regular REST fields instead of using embeds?

We discussed that this will be the way forward.
