### ISSUE TITLE
Auto-saving: saving after auto-saving causes an error

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#12474]
## Bug Description
Looks like after auto-save happens on a published story, saving causes an error:

![Screenshot 2022-10-14 at 12 17 24](https://user-images.githubusercontent.com/3294597/195811003-62daf4f1-b465-4618-b75c-4e73ab814f3d.png)

## Steps to Reproduce
1. Save a story
2. Make some changes
3. Wait until auto-save happens
4. Now click "Update"
5. See error happening and the editor crashing

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
cc @spacedmonkey (since you worked on auto-saving, IIRC.

**Comment by spacedmonkey** [comment]
The autosave endpoint, will return if the content ( amp markup ) does not change, then it will result in this error. So you make a change, those does change how the story looks like or amp that is generated, you will see this error. See this [snippet](https://github.com/WordPress/wordpress-develop/blob/244a20948092d21aaae12b31828f79f57b166315/src/wp-includes/rest-api/endpoints/class-wp-rest-autosaves-controller.php#L374-L390) from the autosave endpoint. 

To fix this, we could use the filter (_wp_post_revision_fields) in [_wp_post_revision_fields](https://developer.wordpress.org/reference/functions/_wp_post_revision_fields/). If we add `post_content_filtered` field to the field that the autosave endpoint compares for a change. 

That also said, unless there is a change, we should not be autosave unless there is a change. I check to see if there is a change in post locking. 

https://github.com/GoogleForCreators/web-stories-wp/blob/d1f43dfdec69c50e57aac108c156637e511dbc85/packages/wp-story-editor/src/components/postLock/postLock.js#L171-L179

**Comment by swissspidy** [comment]
We already use that filter in the Story_Revisions class and have so for years.

**Comment by spacedmonkey** [comment]
> We already use that filter in the Story_Revisions class and have so for years.

Since version 1.0.0. Wow. I forgot we did that. 

@miina What exactly did you change? Can you show a video to replicate the issue?

**Comment by miina** [comment]
> What exactly did you change? Can you show a video to replicate the issue?

This is on `main`, I didn't change anything. Or do you mean what did I change in the Story? Nothing :) I just clicked "Update" after auto-saved had triggered. See video, the first save is auto-save:

https://user-images.githubusercontent.com/3294597/195904944-47794928-4dbe-4be4-9e64-c133e9793efc.mp4

Error on the screen:
<img width="955" alt="Screenshot 2022-10-14 at 20 18 38" src="https://user-images.githubusercontent.com/3294597/195904991-88b4f48c-8f65-4ddd-9cdb-a9059e5a543b.png">

**Comment by swissspidy** [comment]
> Looks like after auto-save happens on a published story, saving causes an error:

I am a bit confused by the error, because it's coming from the autosaves endpoint and not the regular story/save endpoint.

> * Save a story
> * Make some changes
> * Wait until auto-save happens
> * Now click "Update"
> * See error happening and the editor crashing

OK what's missing here is that this applies to a _published_ story.

**I see a serious bug here: The problem is that the story is constantly autosaving.**

Move element around? Autosave! Move it again? Autosave! **Save the story? Autosave!**

The last part is what causes the error: clicking "Update" saves the story and then right away another Autosave happens, but of course nothing has changed, thus causing this error.

**Comment by miina** [comment]
Hm, I started looking into the issue but for some reason can't repro it anymore 😕 @swissspidy Can you still see it happening?

**Comment by miina** [comment]
I can repro it on the calendar styling PR though (#12481)  for example which is out of date with `main` -- did this issue get fixed on `main` meanwhile? 🤔

**Comment by swissspidy** [comment]
That PR is not really out of date, the only change missing there is 6f42a6d93c7f7f77af550ecf30ae6c8592dca19b

**Comment by swissspidy** [comment]
I was just able to reproduce it this way:

1. Publish story
2. Make some changes (e.g. adding an element)
3. Update story
4. Click Preview (triggers autosave)
5. Click Preview again (triggers autosave that fails because it's identical)

**Comment by merapi** [comment]
> I was just able to reproduce it this way:
> 
> 1. Publish story
> 2. Make some changes (e.g. adding an element)
> 3. Update story
> 4. Click Preview (triggers autosave)
> 5. Click Preview again (triggers autosave that fails because it's identical)

I can repro it, but it doesn't crash the editor, I just see this - same for you?
![image](https://user-images.githubusercontent.com/21036224/196216212-e55ba8d2-bd2e-4cd4-951d-7ca029cfec8a.png)

**Comment by miina** [comment]
Other thing I'm currently seeing on a published story (unless it crashes or auto-saves with every change which I'm unable to consistently repro) is that the auto-save triggers only once after saving a published story -- it's probably because the auto-save happens in case of `hasNewChanges` but `hasNewChanges` means having new changes compared to the saved story, not compared to the latest autosave. 

To repro:
- Add a story and publish
- Make some changes
- See the auto-save triggering
- Make more changes (without saving the story meanwhile!)
- Auto-save does not trigger anymore

**Comment by spacedmonkey** [comment]
It seems to me that the fix is here is simple. Unless I am missing something. The REST API call to apiFetch is returned rejected promise. So to fix this, just add a try / catch or catch here. 

https://github.com/GoogleForCreators/web-stories-wp/blob/cf9dd7ff1fbae9992f983026da2b2aef73283ce0/packages/story-editor/src/app/story/actions/useAutoSave.js#L45-L57
