### ISSUE TITLE
SEO: <title> tag duplicated when using SEO plugin

### ISSUE THREAD

**Issue by oksanayoast** [swissspidy/web-stories-wp#12487]
## Bug Description

When using the latest Web Stories and the latest released Yoast SEO plugin (v19.8) I noticed that the `<title>` tag behaves incorrectly.
The page has a single `<title>` only when using Twenty Twenty Two theme, while in these others: Twenty Twenty, Twenty Twenty One, Hello Elementor, Astra, GeneratePress, OceanWP - I see **two** titles in the page source.

This is a continuation of #12139, which was fixed in #12162 but (according to test instructions in PR) has been tested only with the 2022 theme.

## Expected Behaviour

There should always be only one `<title>` tag in the page source, regardless of plugins/themes activated.

## Steps to Reproduce

1. Activate Yoast SEO plugin
1. Activate not a Twenty-Twenty Two theme, for example: Astra, OceanWP, GeneratePress, etc.
1. View a single story
1. Verify the <title> tag is added

## Screenshots

Note the two search results when searching for `<title>`:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/88657898/196269006-2a5652ca-1ddc-4cf8-9356-0675191df9d6.png">

## Additional Context

- Plugin Version: 1.25.1
- Yoast SEO: 19.8 (default settings)
- WordPress Version: 6.0.2
- Operating System: MacOS Monterey
- Browser: Safari/Chrome/Firefox

**Comment by swissspidy** [comment]
Thanks for your report @oksanayoast!

While we got reports for this ourselves, we haven't been able to reproduce it so far, so your suggestion to use a different theme was very helpful! We'll get this sorted ASAP.

**Comment by LuckynaSan** [comment]
@oksanayoast Hi there! Just to follow up that Web Stories version 1.26.0 has been released which includes the fix for this. Please update to the latest version and confirm on your end. Thanks!
