### ISSUE TITLE
Permalink: Slug input field strips unicode characters

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12546]
## Bug Description

The permalink slug field does not show foreign language special characters when using it as a title or when entering it in the slug field.

<details>
<summary>AMP Bug (out of scope for this project)</summary>

The story bookend is being displayed with HTML markup when the story title or permalink slug contains language special characters.

Example story URL: https://feignednorth.s4-tastewp.com/web-stories/%e0%b0%87%e0%b0%82%e0%b0%a1%e0%b0%bf%e0%b0%af%e0%b0%be-%e0%b0%b8%e0%b0%bf%e0%b0%ae%e0%b1%86%e0%b0%82%e0%b0%9f%e0%b1%8d%e0%b0%b8%e0%b1%8d-%e0%b0%aa%e0%b1%88%e0%b0%a8-%e0%b0%95%e0%b1%87%e0%b0%b8/

</details>

## Expected Behaviour

The slug should display the language characters. 

## Steps to Reproduce

1. Create a new story
2. Use “ఇండియా-సిమెంట్స్-పైన-కేస” as title
3. Publish the story.
4. Note Permalink Slug field.

-> Compare the same with Gutenberg where this just works.

## Additional Context

<img width="1405" alt="Screen Shot 2022-10-25 at 9 41 28 AM" src="https://user-images.githubusercontent.com/66372350/197790048-2671662d-56ae-4cf7-b861-af8be395d347.png">

Support Topic: https://wordpress.org/support/topic/doesnt-tech-url

- Plugin Version: 1.25.1
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
The issue with the permalink field is something we can fix, the other part is not in our hands and needs to be reported in the amphtml repo.

**Comment by LuckynaSan** [comment]
I have opened the other part here: https://github.com/ampproject/amphtml/issues/38510

**Comment by swissspidy** [comment]
Gutenberg nowadays uses the MIT [`remove-accents`](https://www.npmjs.com/package/remove-accents) package. We can potentially use that one as well.

Also, I think we should use `String.prototype.normalize()` with `NFC`, not `NFD`

We can also use `replaceAll()` to make the `cleanForSlug` function more readable
