### ISSUE TITLE
Restore from autosave does not revert changes in pages (but story data is restored)

### ISSUE THREAD

**Issue by kkalarickal** [swissspidy/web-stories-wp#12547]
## Bug Description

Restoring an autosaved webstory that is different from the local version does not work in reverting changes to pages. However, a change in the story data (like title) is reverted !

## Steps to Reproduce
The following steps consistently reproduce the problem:

1. Create a new story with 1 page
2. Publish it with poster and description etc
3. Add another page and move it to first position
4. Update this story
5. Now add a third page, change the title & wait for a min to create the autosave session key
6. exit to dashboard without saving to DB
7. reopen the now published & updated story
8. you will get two overlays - one for restoring from local backup (dismiss this) and another for restoring from saved version ...
9. Here, view the different versions and restore the latest (3 slides)

ISSUE: the version with 2 slides is restored instead of the last saved version

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/1fde2cc5-41a0-4452-9ee8-bcf1fd6871ce)

![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/ab54c441-4499-427b-8bc8-843c38517a41)
## Additional Context

This issue was observed in #12521 as well.

- Plugin Version: `main branch` as of 10/25/2022
- WordPress Version: 6.0.3
- Operating System: Win10
- Browser: Chrome

**Comment by kkalarickal** [comment]
Confirmed that this issue exists in Google Web Stories Version 1.25.1 as well.

**Comment by swissspidy** [comment]
From Slack:

> Not sure if it's restore function, `loadStory` has wrong data, is it possible that `$preload_data` doesn't take revision into account?

**Comment by kkalarickal** [comment]
@swissspidy - regarding the two dialogs .. Comparing the way autosave/local-backup behaves for WP Post with how its implemented in web stories, it appears that after local changes are made to a draft, if the user exits the editor:
- in the WP post case, the changes are saved to disk and the local-session backup is deleted
- in the WebStories case, the changes are saved to disk but the local-session backup is retained

This is ok so long as the story is not published. Because after published status, the changes made after autosave are not written to db when exiting the editor. So now there is a legitimate difference between the local-session backup and the story in db which is why we have two dialogs (correctly).

![image](https://user-images.githubusercontent.com/3719412/198062179-69816c5a-6d54-40af-9a07-237a5bf8c85b.png)

**Comment by swissspidy** [comment]
Ah, I see. We should definitely remove the local autosave whenever we successfully write to the DB.

**Comment by spacedmonkey** [comment]
> Ah, I see. We should definitely remove the local autosave whenever we successfully write to the DB.

By this, do you mean, when we save the story or autosave?

**Comment by swissspidy** [comment]
Both. At that point they‘re identical after all.

**Comment by swissspidy** [comment]
cc @miina who worked on this

**Comment by miina** [comment]
Just read through the comments -- do I understand correctly there are two issues:
1. Issue with DB autosave -- the page data is not correctly loaded
2. Issue with the local autosave -- the local autosave is not dismissed when creating an autosave ([basically this todo](https://github.com/GoogleForCreators/web-stories-wp/blob/main/packages/story-editor/src/components/localAutoSaveHandler/localAutoSave.js#L134)).

Should we create a separate issue for the local autosave issue and leave this for the DB autosave?

**Comment by miina** [comment]
Added #12578 to address the issue with local backup not being removed when auto-saving, the other issue with auto-saving seems to be for WP Pod.

**Comment by bmattb** [comment]
@swissspidy can you provide an estimate on this?
