### ISSUE TITLE
Link Icon Menu Shows Edit Option

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12555]
## Bug Description

The Call to Action link icon pencil menu displays an option to "Edit" which functions the same as "Upload a file".

## Expected Behaviour

To have 1 option to "Upload a file".

## Steps to Reproduce

1. Add link in the Call to Action section
2. Click pencil on Link Icon 
3. Notice menu option: Edit

## Screenshots

<img width="252" alt="Screen Shot 2022-10-27 at 11 14 34 AM" src="https://user-images.githubusercontent.com/66372350/198335858-0b45b3d1-100d-4535-9185-93cbd4ce7854.png">

-->

## Additional Context

- Plugin Version: 1.26.0
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
No because they‘re identical anyway
