### ISSUE TITLE
Eyedropper not working

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12560]
## Bug Description

On Firefox browser, the eyedropper to pick a color from the canvas loads continuously and does not open the focus circle. This occurs anywhere the eyedropper color picker is available. 

## Expected Behaviour

The eyedropper should allow the user to select a color from the canvas on Firefox browser.

## Steps to Reproduce

1. Add a new story on Firefox browser
2. Add an element
3. Click on eyedropper
4. Note endless load

## Screenshots
Current Behavior on Firefox:

https://user-images.githubusercontent.com/66372350/199023978-edf65069-aaca-4f4c-b453-2e870300a6d7.mov

Expected Behavior (on Chrome):

https://user-images.githubusercontent.com/66372350/198608683-44bd27b9-9a3d-45e8-8338-7a164a3e0370.mov

## Additional Context
Support topic: https://wordpress.org/support/topic/infinite-loop-on-color-picker-arrow-in-firefox/

- Plugin Version: 1.26.0
- WordPress Version:
- Operating System: macOS
- Browser: Firefox

**Comment by swissspidy** [comment]
Looks like the `Eyedropper should get color from the image to page background` Karma test is failing, might be related.

**Comment by swissspidy** [comment]
@merapi Should this have been fixed by the recent html-to-image patch changes?

Asking because we just got a user report saying that it's still not working.

**Comment by rodrigofglima** [comment]
Hi! Sorry for respond here. I recorded the problem and it's interminent. Sometimes work and sometimes don't. I use Firefox in first video

https://www.youtube.com/watch?v=THATJpY-J78

The second video ints in Google Chrome:

https://www.youtube.com/watch?v=UIvxWtn_l0w

**Comment by swissspidy** [comment]
Another more general issue reported in #12681 with the eyedropper not opening / working correctly
