### ISSUE TITLE
E2E Tests: Remove WP 5.8 compatibility code

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12571]
This includes things like `minWPVersionRequired('5.8');` checks and similar WordPress < 5.9 checks in the `visitBlockWidgetScreen` util.

**Comment by timarney** [comment]
@spacedmonkey 

The FYI `minWPVersionRequired('5.8');` checks are removed in 
https://github.com/GoogleForCreators/web-stories-wp/pull/12606 to get the runs passing.

**Comment by swissspidy** [comment]
FWIW, I don't think it was technically required to remove those in #12606. A `minWPVersionRequired('5.8');` check when testing against 5.9 should just work, since obviously the condition is met.

**Comment by timarney** [comment]
> FWIW, I don't think it was technically required to remove those in https://github.com/GoogleForCreators/web-stories-wp/pull/12606. A minWPVersionRequired('5.8'); check when testing against 5.9 should just work, since obviously the condition is met.

Agree removed per

https://github.com/GoogleForCreators/web-stories-wp/pull/12606#discussion_r1011599360
