### ISSUE TITLE
Block: Use data selectors instead of `api-fetch` directly

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12576]
## Task Description

IIRC, we originally had to use `apiFetch` in the block because WP / GB didn't have proper support for custom post types with custom namespaces and controllers.

But now we might be able to use `wp.data.select` and the like to make maintenance a bit easier.

Needs testing/verification though

**Comment by spacedmonkey** [comment]
I put together a draft PR https://github.com/GoogleForCreators/web-stories-wp/pull/12846. It does seem to work but it is a large refactor than I thought, as the code is not async and we can't easily keep the loading stats.

**Comment by swissspidy** [comment]
> I put together a draft PR #12846. It does seem to work but it is a large refactor than I thought, as the code is not async and we can't easily keep the loading stats.

You can use the `isResolving()` selector to get the loading state. I just pushed a small change to your PR to demo it.

Also, can we perhaps use that in the `StoryPicker` component too?

**Comment by spacedmonkey** [comment]
> Also, can we perhaps use that in the StoryPicker component too?

I looked into doing that ( the PR is still draft ). Sadly as we use get headers, see this line. 

https://github.com/GoogleForCreators/web-stories-wp/blob/7c1ddb58fc8e770abfc67c71e0acddb2f4523e9c/packages/stories-block/src/block/components/storyPicker/storyPicker.js#L96

I haven't worked out a clever way to do this. It also means a large refactor to `StoryPicker`, as `fetchStories` is function. This function does a lot of state management, with loading and error states. It also get headers to check to see if there are more stories to come. I think it maybe worth having a chat to see what we can do here, I am not sure the large refactor is worth the effort here.

**Comment by swissspidy** [comment]
Indeed looks like that‘s not easily possible: https://github.com/WordPress/gutenberg/issues/12083

I think we can leave that one for now then.
