### ISSUE TITLE
Use newer PHP 7.3 & PHP 7.4 language features

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12575]
## Task Description

Typed properties are among the new useful things in PHP 7.4, and there's also useful stuff in PHP 7.3 of course.

Some useful links:

https://php.watch/versions/7.4
https://php.watch/versions/7.3
https://kinsta.com/blog/php-7-4/

**Comment by swissspidy** [comment]
At first glance looks reasonable. Would be nice to include typed properties as well, as those would help a lot with static analysis.

If we use `JSON_THROW_ON_ERROR` we also need to decided if/how to catch those exceptions being thrown.

**Comment by swissspidy** [comment]
Since we discussed property type hints today:

* There should be no need to use full namespaces for property types
* We can enable `SlevomatCodingStandard.TypeHints.PropertyTypeHint` to help here (we already use `ReturnTypeHint`)

**Comment by spacedmonkey** [comment]
I have marked https://github.com/googleforcreators/web-stories-wp/issues/9817 as blocking, as I have added a lint to force this strict types on all files.
