### ISSUE TITLE
Run unit tests only against PHP 7.4+

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12574]
## Task Description

Instead of testing WP 5.7 / 5.9 against PHP 7.2, we should test it against 7.4 instead.

**Comment by spacedmonkey** [comment]
Agreed, as WordPress is mostly PHP 7.4 now - https://wordpress.org/about/stats/

**Comment by swissspidy** [comment]
@spacedmonkey Just note that I haven't technically added this to the sprint yet, I am still creating tickets

**Comment by spacedmonkey** [comment]
We also update composer.
Remove [this](https://github.com/GoogleForCreators/web-stories-wp/blob/5df575735aa14ca85ac0190815c0f4906f171178/composer.json#L108-L112). 
Convert [these](https://github.com/GoogleForCreators/web-stories-wp/blob/5df575735aa14ca85ac0190815c0f4906f171178/composer.json#L83-L102) to packages.  
Update [this](https://github.com/GoogleForCreators/web-stories-wp/blob/5df575735aa14ca85ac0190815c0f4906f171178/composer.json#L78) to 7.4.
Remove [this](https://github.com/GoogleForCreators/web-stories-wp/blob/5df575735aa14ca85ac0190815c0f4906f171178/.github/workflows/tests-unit-php.yml#L135-L146) for github actions.

**Comment by swissspidy** [comment]
This is all in a separate ticket, see #12583 and also #12573
