### ISSUE TITLE
Page templates: Saved templates trash icon and plus sign does not display on the thumbnail

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12584]
## Bug Description
The thumbnails on the saved templates panel are sometimes missing the trash & plus icons or both. 

When saving a page with a text element only the thumbnail displays plus and trash icons.
When saving a page with a media element the thumbnail displays a trash icon only.
When saving a page that originally was a default template page, no icons display at all.

## Expected Behaviour

There should be a trashcan icon to delete the page template, or a plus sign to insert the page template. 

## Steps to Reproduce

1. Create a story
2. Design page (one with text only, one with media, one from default page template)
3. Save the page as template. Notice trash and plus icons missing

## Screenshots

text only

<img width="1106" alt="Screen Shot 2022-10-31 at 12 46 49 PM" src="https://user-images.githubusercontent.com/66372350/199063328-6e089795-0cec-4e60-b6f1-5065cc9f3021.png">

added media from own library

<img width="1171" alt="Screen Shot 2022-10-31 at 12 47 07 PM" src="https://user-images.githubusercontent.com/66372350/199063318-88dd010a-10c6-4b79-a248-5f5006883826.png">

Stock photo
<img width="1064" alt="Screen Shot 2022-10-31 at 12 47 36 PM" src="https://user-images.githubusercontent.com/66372350/199063300-00a45235-3cef-45bc-90f3-913fc3b33565.png">

Default page templates

https://user-images.githubusercontent.com/66372350/199063276-d616b8b6-3e11-413b-8de9-02d51e016eaa.mov

## Additional Context

Support topic: https://wordpress.org/support/topic/saved-templates-not-show-the-option-to-delete-with-crossorigin/
Example story URL: **https://lucksany.com/web-stories/test-2/**

- Plugin Version: 1.26.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
Related: #12513

**Comment by miina** [comment]
Taking a look at this cc @merapi
