### ISSUE TITLE
max-width: max-content is causing a display issue

### ISSUE THREAD

**Issue by ziodave** [swissspidy/web-stories-wp#12598]
## Bug Description

The web stories element doesn't show right:
<img width="148" alt="image" src="https://user-images.githubusercontent.com/11438/199211897-e8abe955-05e2-4316-976e-02d0684f4eef.png">

## Expected Behaviour

It should show like this:
<img width="495" alt="image" src="https://user-images.githubusercontent.com/11438/199211943-7f79bc95-9683-46c3-a450-53c7668f1008.png">

## Steps to Reproduce

Using Divi theme with Block Editor and the Web Stories block:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/11438/199212200-9deb15c1-43a6-4acc-a6df-f1f030523ab2.png">

As a workaround, removing the `max-width: max-content` from the `.web-stories-list.is-carousel .web-stories-list__inner-wrapper` class, fixes the issue:
<img width="108" alt="image" src="https://user-images.githubusercontent.com/11438/199212335-4aa0b722-4da6-45f7-ac16-aac3c1f808a4.png">

## Screenshots

See above.

## Additional Context

- Plugin Version: 2.6.0
- WordPress Version: 6.0.3
- Operating System: macOS
- Browser: Chrome/Firefix

**Comment by swissspidy** [comment]
Thanks a lot for your report!

We're already tracking this in #12563, with a fix in progress at #12564

You can [try the fix here](https://github.com/GoogleForCreators/web-stories-wp/pull/12564#issuecomment-1296806901). If it doesn't work for you, please let us know.
