### ISSUE TITLE
Code Quality: use PHPStan for test files

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12614]
## Task Description

Right now we only run PHPStan on the `includes` folder.

It might be worth running it on test files as well to make tests more robust.

Related:

* https://github.com/phpstan/phpstan-phpunit
* https://github.com/szepeviktor/phpstan-wordpress/issues/30

Probably need a [dynamic return type extension](https://phpstan.org/developing-extensions/dynamic-return-type-extensions) for `PrivateAccess`

**Comment by spacedmonkey** [comment]
As a talking point, I have created two PR. 

1. Run against php unit tests against phpstan. https://github.com/GoogleForCreators/web-stories-wp/pull/12731. 
This seems to work and just need to apply fixes. 

2. Run against php integration tests against phpstan. https://github.com/GoogleForCreators/web-stories-wp/pull/12732
Does not work, as the bootstrap process is broken. A very custom bootstrap process will be need for phpstan to work here. Not sure if this is worth it / possible.

**Comment by swissspidy** [comment]
Good idea to split this up into two PRs 👍 

If you could work on addressing the unit test one, that would be great.

For integration tests we need to add some stub files since we install tests via `bin/install-wp-tests.sh` and thus all the test classes etc. are not known to PHPUnit. I can take a look at that if you like. (Related: #10541)

Not sure about errors like `Access to an undefined property WP_Site::$blog_id.` though 🤔
