### ISSUE TITLE
Block: Stories selector styling issues

### ISSUE THREAD

**Issue by kkalarickal** [swissspidy/web-stories-wp#12620]
## Bug Description

Reporting based on the pointer from @spacedmonkey regarding "[_Some of the styling in the block’s story editor is kind of wonky_](https://xwp.slack.com/archives/C013J2EGH8R/p1667478189974889)"

Basically, if user wants to add stories to the carousel, the selector overlay that appears is difficult to search for and navigate due to styling issues.

![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/7d0dc156-84a3-462e-b1cb-e91fee91123e)

![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/8a3ddd6f-5388-4d78-b198-f43f831ecf82)
![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/ca487335-60b3-46a1-9c1f-f74ee236731f)

## Expected Behaviour

It should be easy for a user to search for, select and rearrange stories within the carousel stories selector overlay.

## Steps to Reproduce

1. As an editor or above, create a WP post and embed web story carousel block into it
2. Now pick a list type carousel and select stories to add to the list
3. An overlay opens that allows user to select stories
4. Find the issues listed above in that overlay.

## Additional Context

- Plugin Version: 1.27.0-alpha.0+f412972
- WordPress Version: 6.1
- Operating System: win10
- Browser: Chrome

**Comment by spacedmonkey** [comment]
This dialog is based on media picker. I believe this dialog should match and be styled the same. The height is the key different, but I also believe that the filters should be moved to the left. 

<img width="1758" alt="Screenshot 2022-11-04 at 11 42 42" src="https://user-images.githubusercontent.com/237508/199964764-0c9a68ed-65b2-4886-9dd9-c23fa8e53446.png">
<img width="1764" alt="Screenshot 2022-11-04 at 11 42 32" src="https://user-images.githubusercontent.com/237508/199964772-ef2e85ea-cf6a-4e27-80a3-0225979d7e08.png">

**Comment by spacedmonkey** [comment]
<img width="378" alt="Screenshot 2022-11-04 at 11 46 57" src="https://user-images.githubusercontent.com/237508/199965341-593d4a9a-2f29-4ec1-85bd-655671723a8b.png">

Another styling issue.

**Comment by spacedmonkey** [comment]
I haven't done a tone of work on this, but I believe the accessibility of this picker will likely need some work. Like using announcements to screen readers and keyboard accessibility.

**Comment by timarney** [comment]
@spacedmonkey are you picking this one up?

**Comment by swissspidy** [comment]
> This dialog is based on media picker. I believe this dialog should match and be styled the same. The height is the key different, but I also believe that the filters should be moved to the left.

It's certainly inspired by it, but does not need to look the same. No need to change the filter position.

> I haven't done a tone of work on this, but I believe the accessibility of this picker will likely need some work. Like using announcements to screen readers and keyboard accessibility.

A11y related improvements can be in their own ticket.

Let's just use this one to focus on fixing the few obvious styling issues.
