### ISSUE TITLE
The first story created from a template has the old page timeout setting

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#12648]
## Bug Description

The first story created from a template has the old page timeout setting.
This only happens if you don't reload the page after setting a new value on the Settings page.
We have stale values in config because we bind the functions on page load:
https://github.com/GoogleForCreators/web-stories-wp/blob/ff2e61e280a8cad3550d600623d4933be9a5df75/packages/wp-story-editor/src/index.js#L92

## Expected Behaviour

Every story should have up-to-date settings regarding page advancement.

## Steps to Reproduce

1. Go to the Setting page.
2. Change the Page Advancement duration to a different value (from X to Y).
3. Click Explore Templates (any of two links).
4. Click Use Template on any template.
5. Confirm the old value (X) in the Document -> Page Advancement.

Stories created from the Create New Story are fine because there is a page reload with new config values.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
This is about the `createStoryFromTemplate` callback, right?

Since we bind the functions on page load, perhaps we can just pass the values as params instead of reading them from `config`

**Comment by merapi** [comment]
@swissspidy Yes, we can read them from the state (input) or update the config and use that new config somehow, for example: https://github.com/GoogleForCreators/web-stories-wp/pull/12645/commits/960f521f5cb88d3b699793023e75aee5bd8866e6
