### ISSUE TITLE
Web Stories plugin not printing title tag by default

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12655]
## Bug Description
Stories are missing the <title> tag when using a theme like Astra (astra) Version 3.9.3 or Twenty Twenty Version 2.1.

Example Story URL: https://testsite.cmsdevrel.com/web-stories/testing-nov-9-5

## Expected Behaviour

Web Stories plugin prints title tags by default.

## Steps to Reproduce

1. Activate a theme like Astra or Twenty Twenty
2. View a single story
3. Verify there is no  <title> tag in the source code

## Additional Context

- Plugin Version: 1.27.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
We previosuly had issues with missing title tags and duplicate ones

First attempt:

* #12139
* #12162

Second attempt:

* #12487
* #12507

Things to test:

* Twenty Twenty
* Twenty Twenty Two / Twenty Twenty Three (block themes)
* Astra
* GeneratePress
* OceanWP

Web Stories meta data output should be theme-independent, so I am inclined to just always print the document title and use AMP sanitization to avoid any future regressions.

**Comment by swissspidy** [comment]
Could also add an AMP sanitizer to remove duplicate meta descriptions.
