### ISSUE TITLE
WordPress: Use post type / taxonomy labels in dashboard / editor

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#12707]
## Feature Description

WordPress provides a way to translate common actions for post types and taxonomies. There are defined when you define the post type or taxonomy.

<img width="412" alt="Screenshot 2022-11-18 at 11 33 44" src="https://user-images.githubusercontent.com/237508/202710396-c6e05add-40c7-4073-ab42-11285715bc70.png">

We are already use these values here

https://github.com/GoogleForCreators/web-stories-wp/blob/64c67ffcfd727e835cb1110709bbee33251638d4/packages/dashboard/src/app/views/myStories/filters/StoryFiltersProvider/taxonomy/useTaxonomyFilters.js#L105-L108

So of these values could mapped like this. 

<img width="258" alt="Screenshot 2022-11-18 at 13 00 25" src="https://user-images.githubusercontent.com/237508/202711071-81b33b9e-d363-4da7-a0c5-61eeeb858418.png">
<img width="282" alt="Screenshot 2022-11-18 at 13 00 48" src="https://user-images.githubusercontent.com/237508/202711139-e1265a30-1950-4eb0-a15e-85a5406454c4.png">
<img width="431" alt="Screenshot 2022-11-18 at 13 02 54" src="https://user-images.githubusercontent.com/237508/202711486-de858bdf-37ca-47a1-afa7-e25659b0c532.png">
<img width="209" alt="Screenshot 2022-11-18 at 13 03 45" src="https://user-images.githubusercontent.com/237508/202711680-06e91a87-172f-471e-a996-708d4b80aeee.png">
<img width="373" alt="Screenshot 2022-11-18 at 13 04 43" src="https://user-images.githubusercontent.com/237508/202711837-dabfb4c7-3161-4404-bde3-c358ada56b94.png">

**Comment by swissspidy** [comment]
Closing per discussion at #12958
