### ISSUE TITLE
Improve PHPCS configuration

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12729]
## Task Description

We discussed potentially enabling many more rules from https://github.com/slevomat/coding-standard

Let's go through them to see which ones are useful for the project

**Comment by spacedmonkey** [comment]
https://github.com/slevomat/coding-standard/blob/master/doc/variables.md#slevomatcodingstandardvariablesunusedvariable

https://github.com/slevomat/coding-standard/blob/master/doc/variables.md#slevomatcodingstandardvariablesuselessvariable-

https://github.com/slevomat/coding-standard/blob/master/doc/namespaces.md#slevomatcodingstandardnamespacesreferenceusednamesonly-

https://github.com/slevomat/coding-standard/blob/master/doc/namespaces.md#slevomatcodingstandardnamespacesuselessalias-

https://github.com/slevomat/coding-standard/blob/master/doc/namespaces.md#slevomatcodingstandardnamespacesunuseduses-

https://github.com/slevomat/coding-standard/blob/master/doc/namespaces.md#slevomatcodingstandardnamespacesusedoesnotstartwithbackslash-

https://github.com/slevomat/coding-standard/blob/master/doc/classes.md#slevomatcodingstandardclassesclassconstantvisibility-

https://github.com/slevomat/coding-standard/blob/master/doc/complexity.md#slevomatcodingstandardcomplexitycognitive

https://github.com/slevomat/coding-standard/blob/master/doc/php.md#slevomatcodingstandardphpshortlist-

https://github.com/slevomat/coding-standard/blob/master/doc/php.md#slevomatcodingstandardphprequirenowdoc-

https://github.com/slevomat/coding-standard/blob/master/doc/operators.md#slevomatcodingstandardoperatorsspreadoperatorspacing-

The following are some of the rules I would look at implementing. 

Some good examples to follow 

https://github.com/wearerequired/coding-standards/blob/master/Required/ruleset.xml

**Comment by spacedmonkey** [comment]
Also for reference. https://github.com/GoogleForCreators/web-stories-wp/pull/12760

**Comment by swissspidy** [comment]
Soo many rules!

From the above we already use a few, so that's good.

The cognitive complexity rule definitely needs tweaking 

There's even more I find useful. For example:

* [`SlevomatCodingStandard.Classes.ClassStructure`](https://github.com/slevomat/coding-standard/blob/master/doc/classes.md#slevomatcodingstandardclassesclassstructure-) - Checks that class/trait/interface members are in the correct order.
* [`SlevomatCodingStandard.Files.LineLength`](https://github.com/slevomat/coding-standard/blob/master/doc/files.md#slevomatcodingstandardfileslinelength) - Enforces maximum length of a single line of code.
[`SlevomatCodingStandard.Functions.StaticClosure`](https://github.com/slevomat/coding-standard/blob/master/doc/functions.md#slevomatcodingstandardfunctionsstaticclosure-) - Reports closures not using `$this` that are not declared static.
* [`SlevomatCodingStandard.TypeHints.ParameterTypeHint`](https://github.com/slevomat/coding-standard/blob/master/doc/type-hints.md#slevomatcodingstandardtypehintsparametertypehint-)
Checks for missing parameter typehints in case they can be declared natively. This sniff causes errors when overriding or implementing parent methods from a WP class which does not have typehints, like `WP_Widget` or `WP_REST_Controller`. So for these cases we need lots of overrides.
* [`SlevomatCodingStandard.Numbers.RequireNumericLiteralSeparator`](https://github.com/slevomat/coding-standard/blob/master/doc/numbers.md#slevomatcodingstandardnumbersrequirenumericliteralseparator) - Requires use of numeric literal separators.

I have some WIP config locally including a mix of these rules, will refine it in the new year.

**Comment by spacedmonkey** [comment]
> SlevomatCodingStandard.Files.LineLength 

I have tried to implement this rule, but it resulted in many many false positive and added more overhead than value. I would recommend not using this lint rule.

**Comment by spacedmonkey** [comment]
> SlevomatCodingStandard.Numbers.RequireNumericLiteralSeparator - Requires use of numeric literal separators.

https://github.com/GoogleForCreators/web-stories-wp/pull/12911

**Comment by spacedmonkey** [comment]
> SlevomatCodingStandard.Classes.ClassStructure - Checks that class/trait/interface members are in the correct order

I really like this rule. I have put together a demo PR - https://github.com/GoogleForCreators/web-stories-wp/pull/12912

**Comment by spacedmonkey** [comment]
[Complexity Cognitive](https://github.com/slevomat/coding-standard/blob/master/doc/complexity.md#slevomatcodingstandardcomplexitycognitive) seems very similar to [Cyclomatic Complexity](https://phpmd.org/rules/codesize.html#cyclomaticcomplexity). 

After setting up the rule, there are lots of places where the rule would have to be ignored. Examples of code that is marked as complex. 

- [prepare_item_for_response](https://github.com/GoogleForCreators/web-stories-wp/blob/a8b3261145020266209195f8ba31be80ddd8438e/includes/REST_API/Stories_Controller.php#L71-L175) - 28
- [safecss_filter_attr](https://github.com/GoogleForCreators/web-stories-wp/blob/a8b3261145020266209195f8ba31be80ddd8438e/includes/KSES.php#L232-L547) - 53
- [ensure_required_markup ](https://github.com/GoogleForCreators/web-stories-wp/blob/d06a10bdf3c06265e392375024c1cca1087765e2/includes/AMP/Sanitization.php#L93-L316) - 44

The lint has some use. If you set the value to say 20.

**Comment by swissspidy** [comment]
> [Complexity Cognitive](https://github.com/slevomat/coding-standard/blob/master/doc/complexity.md?rgh-link-date=2023-01-09T15%3A07%3A32Z#slevomatcodingstandardcomplexitycognitive) seems very similar to [Cyclomatic Complexity](https://phpmd.org/rules/codesize.html#cyclomaticcomplexity).

Yes, they're [similar](https://docs.codeclimate.com/docs/cognitive-complexity#:~:text=Cognitive%20Complexity%20is%20a%20measure,be%20to%20read%20and%20understand.).

> After setting up the rule, there are lots of places where the rule would have to be ignored. Examples of code that is marked as complex.

Yeah I noticed the same in my WIP config I mentioned further above.

**Comment by spacedmonkey** [comment]
I think ticket is good to be closed now.

**Comment by spacedmonkey** [comment]
My bad, there is still https://github.com/GoogleForCreators/web-stories-wp/pull/12911 and https://github.com/GoogleForCreators/web-stories-wp/pull/12760 need to be merged.
