### ISSUE TITLE
Opera: Color picker / eyedropper fails to open

### ISSUE THREAD

**Issue by kkalarickal** [swissspidy/web-stories-wp#12728]
## Bug Description

Found while validating [fix for #12684](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/googleforcreators/web-stories-wp/12684#issuecomment-1322870669)

When using google web stories editor on Opera browser, it is NOT possible to open the color picker by clicking the eye-dropper icon. A console error is thrown saying

> Failed to execute 'open' on 'EyeDropper': The user canceled the selection.

## Expected Behaviour

Since we support all modern browsers, we should allow Color Picker via clicking the Eye-Dropper icon.

## Steps to Reproduce

1. Open/edit a story via a GWS editor session on Opera browser (Mac or PC)
2. Add a text element and go to Style panel
3. Scroll down to the Text section and click on the EyeDropper icon

Issue - the color picker is not activated and there is a console error

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/e9bfd5d4-832f-45c7-9560-c6162d39f860)
## Additional Context

![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/7f7ca1e7-8a9a-42ee-9c59-df6ab1dc63b1)

- Plugin Version: `main branch` as of 22-Nov-2022
- WordPress Version: 6.1
- Operating System: Win11
- Browser: Opera Version:92.0.4561.30

**Comment by swissspidy** [comment]
Also happens in Opera on macOS

cc @miina @timarney

**Comment by swissspidy** [comment]
Closing as it's an Opera implementation issue
