### ISSUE TITLE
Add a 'view all' button option for the Web Stories shortcode

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#12734]
## Feature Description

A user in the support forum has suggested adding the ability to place a 'view all' button via the [web_stories] shortcode. Currently this is not a configurable option. The new option could be added to the shortcode with a view_all option set to either true or false as seen at the end of the example shortcode below:

`[web_stories title="false" excerpt="false" author="false" date="false" archive_link="true" archive_link_label="" circle_size="50" sharp_corners="false" image_alignment="left" number_of_columns="1" number_of_stories="7" order="DESC" orderby="post_title" view="circles" view_all="true" /]`

This would add the view all button for user on the page allowing them to view all Stories.

## Alternatives Considered

N/A

## Additional Context

Support topic: https://wordpress.org/support/topic/webstories-shortcode/

**Comment by swissspidy** [comment]
Closing for now since the user did not respond to the follow-up question and there's already an option to link to the archive page.
