### ISSUE TITLE
Transition between story pages on mobile is not smooth

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12733]
## Steps to Reproduce

1. Trim the video into short clips (1 sec, 2 secs)
2. Upload video clips
3. Set page advancement to auto
4. View story on mobile device such as iPhone / Android
5. Notice the transition between story pages is choppy

User's story: https://www.mmjones.be/web-stories/640/

## Additional Context

Support topic: https://wordpress.org/support/topic/transition-between-story-pages-is-ugly-and-not-smooth/

- Plugin Version: 1.27.0
- WordPress Version:
- Operating System: Android, macOS
- Browser:

**Comment by swissspidy** [comment]
Seems pretty smooth for me. But this would be something for the amphtml repository.
