### ISSUE TITLE
TypeScript: Convert utils folder

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#12740]
## Feature Description

Most of the utility functions inside the `story-editor `package are isolated and only dependent on other already-converted packages. However, many providers inside the `story-editor` package depend on utilities and can't easily be converted unless their utilities are done so as well.

There are a few exceptions to the above though:

* `contrastUtils` depend on the external library [`@ap.cx/hues`](https://www.npmjs.com/package/@ap.cx/hues) which does not appear to be typed or have types available
* `getUpdatedSizeAndPosition` and `presetUtils` depend on un-converted functions inside the `element-library` package
* `storyPageToCanvas` and `storyPageToDataUrl` depend on `storyPageToNode`, and
* `storyPageToNode` depends on the `font` provider and the canvas component
* `useAddPreset` depends on the `story` provider
* `useApplyTextAutoStyle` depends on the `pageCanvas` provider and the style panel component
* `useCORSProxy` depends on the `api` provider
* `useElementPolygon` depends on the `story` and `canvas` providers
* `useElementWithLink` depends on the `story` and `canvas` providers
* `useIsUploadingToStory` depends on the `story` and `localMedia` providers
* `useShapeMask` depends on the `story` and `canvas` providers
* `useShapeMaskElements` depends on the `story` provider

These functions should be moved to their respective providers (mostly to live inside the story provider) and or other relevant parts of the codebase, or their dependency types should be mocked.

**Comment by swissspidy** [comment]
@barklund Coordinate with @spacedmonkey who started converting some utils in #12737

**Comment by barklund** [comment]
> @barklund Coordinate with @spacedmonkey who started converting some utils in #12737

Oh, I tried searching for a matching ticket and didn't find this one. My bad. I'll coordinate.
