### ISSUE TITLE
Layer Visibility: Background Element

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12778]
## Feature Description

Right now, all layers except the background element can be hidden.

Now the question was:

Should one be able to hide the background element?

There are two parts to this:

1) hide/show the background in the layers panel - pretty straightforward
2) output - how it should behave if there is a hidden background image/video/gif with or without background color because right now if you set the background video and hide it, it will not output a white background (like you see in the editor) it also doesn't account for the background color

**Comment by kkalarickal** [comment]
@swissspidy - you asked : _how you were able to set a hidden layer as the background element in the first place_

Steps:
- add an image asset to a group
- hide the image layer within the group
- right click the layer and "set it as background"

Note: you cannot set the asset as a background if the layer is outside the group and is hidden.

![image](https://user-images.githubusercontent.com/3719412/205956549-734103c6-2371-4d6c-82e0-ac3396285172.png)
