### ISSUE TITLE
Replace colorthief library

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12792]
## Task Description

[`colorthief`](https://www.npmjs.com/package/colorthief) has not been updated in years, does not support image formats like webp, and seems to cause issues related to node-gyp as well.

At first glance, [`extract-colors`](https://www.npmjs.com/package/extract-colors) seems like a viable alternative, but there might be others

There's also the `@pioug/colorthief` fork.

**Comment by swissspidy** [comment]
In #12785 I tried using `@pioug/colorthief`

**Comment by spacedmonkey** [comment]
@swissspidy Seems like this PR is done.

**Comment by spacedmonkey** [comment]
@swissspidy Seems like this PR is done.
