### ISSUE TITLE
Code quality: Use `elementIs` util in codebase.

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#12806]
## Feature Description

Added in https://github.com/GoogleForCreators/web-stories-wp/pull/12652 the `elementIs` util is a set of handy tools to check an element's type. These utils could replace code like this, 

https://github.com/GoogleForCreators/web-stories-wp/blob/d468fbb0a7a502982bdd74f83537bfe1031395d4/packages/story-editor/src/components/checklist/checks/pageBackgroundLowTextContrast/check.js#L379

This will help in typescript migration and it improves typing.

**Comment by swissspidy** [comment]
Related: #10865
