### ISSUE TITLE
Text: Save styles changing to lorem ipsum or default text

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12807]
## Bug Description
The saved text style changes when clicking out of the element. The text is not saving when saving a style.

Notice the first save text saved "Test text today" changed to lorem ipsum. Then clicking out of the text element and back changed it to "Fill in some text".

## Screenshots

https://user-images.githubusercontent.com/66372350/207115358-2744ab7d-adf4-44db-97ea-749a588fefea.mov

## Additional Context

- Plugin Version: 1.28.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
Hmm I don't see an issue here.

By default, the saved styles use some "Lorem ipsum" placeholder text.

But when you have some text element selected, we use that element's content for the saved style placeholder text, so it's more WYSIWYG style.

Does that make sense?

**Comment by miina** [comment]
> Then clicking out of the text element and back changed it to "Fill in some text".

Note that a new element with "Fill in some text" is added on top of the old one -- the text of the existing element is not changed, it's just below the new element.

Seems to work per design currently.
