### ISSUE TITLE
Canvas: Rotated text element position wrong in preview thumbnails

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12829]
## Bug Description

I noticed issues with the position of text elements in the generated thumbnails if the text element is rotated.

## Expected Behaviour

Position should not be off like this.

## Steps to Reproduce

1. Insert "Almodo Films Cover" page template to story
2. Go to previous page
3. See that the `WOMEN IN ALMODO’S FILMS` text element, which is rotated, is not fully on the page anymore in the preview thumbnail

## Screenshots

https://user-images.githubusercontent.com/841956/207278739-cdf2510b-dcef-4ffa-bda2-7cd5b122754a.mov

## Additional Context

- Plugin Version: 1.28.0
- WordPress Version: 6.1
- Operating System: macOS
- Browser: Chrome

**Comment by ayushnirwal** [comment]
https://github.com/GoogleForCreators/web-stories-wp/blob/943d76225e4fc2950415c4140f4eb2bcba052ac2/packages/element-library/src/text/display.js#L126

The above line of code adds a second `px` so the generated margin style becomes `margin: 20pxpx 0`. Since these styles are only generated for preview incorrect margins can only be seen in previews.

**Comment by swissspidy** [comment]
Confirmed that this is the cause & that the suggested fix resolves the issue!

**Comment by swissspidy** [comment]
Not sure why the position is initially incorrect though:

https://user-images.githubusercontent.com/841956/225349979-318d5838-c8aa-4110-aaac-4277ed3b7014.mov

**Comment by ayushnirwal** [comment]
> Not sure why the position is initially incorrect though:

It could be that case that the editor was showing you the previously cached image before generating a new one. It seems fine on my end.
