### ISSUE TITLE
Media: Add option to change video playback speed

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12824]
## Feature Description

When creating a story the other day I was missing an option to speed up video playback.

Having such an option in the editor would be one less reason for having to edit media locally.

**Comment by spacedmonkey** [comment]
Is the plan here, to change the speed of the video player or to retranscode the video with the new speed?

**Comment by spacedmonkey** [comment]
Is the plan here, to change the speed of the video player or to retranscode the video with the new speed?

**Comment by swissspidy** [comment]
AFAIK only the latter would be possible
