### ISSUE TITLE
Animations: new duration and delay values sometimes rejected

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12832]
## Bug Description

Sometimes when changing animation duray or duration, my new values are simply not used, falling back to the previous value.

Takes me 2 or 3 attempts to get it working.

## Expected Behaviour

My duration and delay values should not be rejected

## Steps to Reproduce

1. Add animation to element
2. Try changing delay and duration values
3. Sometimes the new change is not accepted

## Screenshots

https://user-images.githubusercontent.com/841956/207281048-6d4fb50c-2c2a-4aeb-8971-9eff3ed02d17.mov

## Additional Context

- Plugin Version: 1.28.0
- WordPress Version: 6.1
- Operating System: macOS
- Browser: Chrome

**Comment by barklund** [comment]
It appears that you cannot edit the values while the animation preview is playing on-canvas.

I'll look into it.

**Comment by barklund** [comment]
Well, [it's by design](https://github.com/GoogleForCreators/web-stories-wp/blob/main/packages/story-editor/src/app/story/useStoryReducer/reducers/updateElements.ts#L55-L62). What to do?

**Comment by swissspidy** [comment]
Interesting! In that case, can we disable the input fields while animation is playing?

**Comment by barklund** [comment]
> Interesting! In that case, can we disable the input fields while animation is playing?

@swissspidy yes, that's a great idea. But in that case, we should do that for every panel in the style pane as well as all the buttons and options in the floating design menu. It's a pretty big task then, so not trivial. Should we keep this ticket or make a new one specifically to address this?

**Comment by barklund** [comment]
Thinking a bit more about, we should actually restrict all actions editing elements on canvas. Currently you can actually still delete or add elements, while the animation is playing, which is pretty confusing.

Either that, or we should allow all edits of on-canvas elements, and just abort any ongoing animation. We already do that if you change selection while an animation is playing.

**Comment by swissspidy** [comment]
Hmm I see, it's more complex than I originally though!

> But in that case, we should do that for every panel in the style pane as well as all the buttons and options in the floating design menu.

True, but I think here it's especially confusing because changing duration/delay automatically plays the animation, which might not be obvious. I probably didn't realize that when I ran into this.

> Either that, or we should allow all edits of on-canvas elements, and just abort any ongoing animation. We already do that if you change selection while an animation is playing.

Would that be difficult to implement?

**Comment by barklund** [comment]
> > Either that, or we should allow all edits of on-canvas elements, and just abort any ongoing animation. We already do that if you change selection while an animation is playing.
> 
> Would that be difficult to implement?

No, I think that's fairly easy to implement. Probably easier than disabling everything while it's playing.
