### ISSUE TITLE
Editor/Authors unable to list users for dropdown

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#12842]
## Bug Description

While editing a Story with an editor user role and navigating to the Document tab, the Author drop down is always stuck on an infinite load. This is accompanied by constant console errors and network errors (see screenshots below).

This happens no matter what the author value is set to and there is no way for the editor to amend this. This was initially raised in the support forum [here](https://wordpress.org/support/topic/user-compatibility-issue-while-changing-author-of-a-web-story/). 

This happens when both trying to edit an existing Story and creating a new Story.

## Expected Behaviour

Users with the editor role should be able to update the Author drop down and it should not be stuck on an infinite loop.

## Steps to Reproduce

1. Log into a site with the latest Web Stories with the editor role.
2. Create a new Story or edit a Story
3. Go to the Document tab 

## Screenshots

Console errors:
![image](https://user-images.githubusercontent.com/91896826/207830375-9bc66e0a-929c-40c7-a311-a81166fb121b.png)

Network errors:
![image](https://user-images.githubusercontent.com/91896826/207830465-551573aa-a111-4e15-8742-45d3c3d03bbe.png)

**Comment by swissspidy** [comment]
FYI @spacedmonkey 

I think we have to override the user controller get_items_permission_check to allow filtering by capabilities like that. WDYT?
