### ISSUE TITLE
Snackbar: Nice to have one notification  instead of multiple

### ISSUE THREAD

**Issue by santoshgistto** [swissspidy/web-stories-wp#12845]
## Description

When we add page template multiple times we are showing multiple notification at the same time.

## Expected Behaviour
Nice to have one notification instead of multiple for same action

## Steps to Reproduce
 Please see the video video for steps 

## Video 

https://user-images.githubusercontent.com/12577046/207974227-46045f78-a6fb-43e7-8d20-66c55e9978c0.mp4

## Additional Context

- Plugin Version: v1.28.0
- WordPress Version: 
- Operating System: MAC
- Browser: Chrome

**Comment by swissspidy** [comment]
Thanks for sharing this enhancement suggestion with us.

The current behavior is indeed not consistent with [Material Design recommendations](https://m3.material.io/components/snackbar/guidelines), so we will look into it.

**Comment by santoshgistto** [comment]
This looks good https://github.com/emilkowalski/sonner
Thought to share here
