### ISSUE TITLE
Setting the heading tag to Paragraph outputs H1

### ISSUE THREAD

**Issue by prathamesh-gharat** [swissspidy/web-stories-wp#12850]
## Bug Description
I noticed that even after setting the heading tag to a paragraph manually the plugin outputs H1 tag (even though there is an existing H1 tag on the first page). Just for reference, I am setting a piece of text on Page 4 in my content to a paragraph tag and it instead outputs H1.

## Expected Behaviour
The tag specified in the backend should be used without any additional corrections/checks by the plugin. (A duplicate check on H1 is ok but for rest of the tags try to minimize the number of checks to avoid such issues)

## Steps to Reproduce
1. I just have a small piece of text on Page 4 marked as a header > paragraph in accessibility settings.
2. Checked frontend HTML code using dev tools and I see a `<h1>` tag being ouput for this text rather than a `<p>` tag.

## Screenshots
https://i.imgur.com/LOAyFgo.png
https://i.imgur.com/jNQLafm.png

## Additional Context

- Plugin Version: 1.28.0
- WordPress Version: 6.1.1
- Operating System: Windows 10
- Browser: Chrome (latest)

**Comment by swissspidy** [comment]
Thanks for your report. I see now why that happens & will make sure we fix this in an upcoming release.
