### ISSUE TITLE
Dashboard: editor/author user not able to see author information

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12866]
## Bug Description

Originally reported at https://github.com/GoogleForCreators/web-stories-wp/pull/12848#issuecomment-1359570818

Very similar to #12604

A user with editor or author role doesn't necessarily have `list_users` capabilities, thus the embedded `author` information is missing due to a `rest_user_cannot_view` error.

This happens when the other user does not have any published posts.

It's confusing because the author information is available on the classic list table.

## Expected Behaviour

Ideally the user should see the author name on the dashboard.

## Steps to Reproduce

1. Create a new admin user
2. Create a draft story with that admin user
3. Switch to an editor/author user
4. Go to stories dashboard
5. See draft story without admin user's name on it

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/32139694-1303-42e8-90c8-aebc20d6eb41)

Same list view when logged in as admin-user is like this:
![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/f598b672-9c8b-4d21-8615-7439d88361c0)

## Additional Context

- Plugin Version: 1.28.0
- WordPress Version: 6.1.1
- Operating System: macOS
- Browser: Chrome

**Comment by spacedmonkey** [comment]
I can't replicate this issue. 

<img width="1424" alt="Screenshot 2023-01-16 at 16 26 31" src="https://user-images.githubusercontent.com/237508/212726121-67c9e0d4-4b1b-45e0-92cb-7fe942b880d7.png">

**Comment by swissspidy** [comment]
Try creating a new editor/author user that does not have any published posts yet.

IIRC the issue happens here where there is a `count_user_posts` check:

https://github.com/WordPress/wordpress-develop/blob/f438c0bff6674eed40a8300dc8145386e9016a5b/src/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php#L445

**Comment by spacedmonkey** [comment]
> So this is fixed now? Fixed by #12848 ?

I could not replicate this error when I checked out https://github.com/GoogleForCreators/web-stories-wp/commit/88cd0cbed9cca32e7fd09ad4108a703063586f8f. I could replicate in 1.27. Something in 1.28 / 1.28.1 fixed it. I believe it was https://github.com/GoogleForCreators/web-stories-wp/pull/12848. I can spent more time to find out what fixed  it. This change makes sense. Unless we can replicate this error, we should close this ticket out.

**Comment by swissspidy** [comment]
Works for me!
