### ISSUE TITLE
RTL: Scroll arrows not working correctly and they are not positioned correctly on their place

### ISSUE THREAD

**Issue by MMaKenZi** [swissspidy/web-stories-wp#12874]
## Bug Description
In the RTL mode, the scrolling arrows are not positioned correctly in their place and not working correctly, I attached a video

https://user-images.githubusercontent.com/20024403/209428098-657eed03-274b-4817-bd00-2a7aa31dd447.mp4

## Expected Behaviour
I expect to use the arrows just like the LTR mode, the arrows should be on their corresponding location and when I click on the next or previous button, they should do what they are designed to do

## Steps to Reproduce
Try to use the web story template on RTL mode

## Screenshots
![SNAG-0018](https://user-images.githubusercontent.com/20024403/209428159-7c9d1854-e705-4535-a596-f71066fd162b.jpg)

## Additional Context
- Plugin Version: 1.28.1
- WordPress Version: 6.1.1
- Operating System: Windows 10
- Browser: Chrome 108.0.5359.125

**Comment by swissspidy** [comment]
To clarify, is this when using the Web Stories block?

**Comment by MMaKenZi** [comment]
Hi @swissspidy 

Yes, I think so
![SNAG-0021](https://user-images.githubusercontent.com/20024403/209428806-b9628931-d713-458c-a2c8-0822166f18ac.jpg)
![SNAG-0019](https://user-images.githubusercontent.com/20024403/209428808-4e518ba7-d37d-4140-82f5-655c1dfbabe6.jpg)
