### ISSUE TITLE
Support for Vimeo videos

### ISSUE THREAD

**Issue by JosefJezek** [swissspidy/web-stories-wp#12873]
Could you add support for Vimeo videos? We have amp component.

Vimeo supports AV1 codec and HSL.

https://amp.dev/documentation/components/amp-vimeo

**Comment by swissspidy** [comment]
Unfortunately we can’t decide that alone. You‘ll need to ask for amp-vimeo support in the Web Stories format in general over at the AMP repository.

Given that seeing Vimeo player controls all over a story would not look great, it sounds unlikely though to be supported. But can‘t ask to hurt over there.
