### ISSUE TITLE
Critical Error on Dashboard, Templates, & Settings

### ISSUE THREAD

**Issue by shelb-elliott** [swissspidy/web-stories-wp#12906]
## Bug Description

In version 1.28.1 of the Web Stories Plugin: 
When a new nameless user is created (First Name, Last Name fields left blank), a critical error is triggered when that user (& sometimes other users) try to access the Web Stories Dashboard, Templates or Settings ([screenshot](https://d.pr/i/WIrRHd)).

Confirmed with multiple sites on Newspack.

## Expected Behaviour

All users should be able to access those, regardless of the values (or lack there of) in the First & Last Name fields.

## Steps to Reproduce

With Web Stories 1.28.1 installed & activated: 

- Navigate to Stories dashboard (to ensure it's working)
- Add a user with no first or last name
- Log out of your account
- Log in as unnamed user
- Navigate to Dashboard, Templates, or Settings in Web Stories

## Screenshots

[Loom screen recording](https://www.loom.com/share/46a3298d962a41a4bd39ca2f43e9c05d)

## Additional Context

- Plugin Version: 1.28.1
- WordPress Version: 6.1.1
- Operating System: Mac OS
- Browser: Chrome

**Comment by swissspidy** [comment]
Thanks for your detailed report & the screencast!

We‘ll look into this for sure so we can fix any existing bug in our next release.

**Comment by swissspidy** [comment]
@shelb-elliott Unfortunately I have been unable to reproduce this error with the steps you mentioned.

I suspect the error is somewhere else in your setup, maybe with another plugin. After all Newspack sites are rather complex. I recommend following the troubleshooting steps to find the exact error information in the logs and trying to disable all other plugins to see if the error still occurs.
