### ISSUE TITLE
Can't disable automatic assignment to background layer for full bleed content

### ISSUE THREAD

**Issue by RyanNeilson** [swissspidy/web-stories-wp#12987]
## Bug Description

When adding an element (an image, usually) to the web story canvas, if that element spans wider than the entire canvas it is automatically applied as the background layer. 

I can detach the element from the background manually, but if I reposition the element at all it will once again be set as the background. The editors I work with are reporting this as a significant impediment to their workflow.

## Expected Behaviour

There should be some kind of settings field where the behavior of automatically setting a full bleed element as the background can be toggled on or off.

## Steps to Reproduce

- In the web stories editor, drag an image from the library onto an empty canvas.
- Resize the added image so that it bleeds outside the workspace in all directions.
- The image will be automatically applied as the background layer for the current page.
- Click on the image / background layer and in the popup list click `Detach Image From Background`.
- Move the image on the canvas, making sure it still overflows the canvas in all directions.
- When you stop moving the image it will once again be set as the background layer.

## Additional Context

- Plugin Version: 1.27.0
- WordPress Version: 5.8.4
- Operating System: Mac OS Monterey
- Browser: Google Chrome version 109

**Comment by swissspidy** [comment]
Thanks for raising this.

Is there a specific type of story or page layout where this current behavior is deemed not useful? i.e. what result are you aiming for when this happens? A screenshot or story link might be helpful.

**Comment by RyanNeilson** [comment]
We have some web stories where editors build charts out of stacked layers, which are sometimes partly transparent and overflow the web story in all directions. A pretty typical example of one of these charts is on page 7 of this web story: https://www.barrons.com/visual-stories/lithium-electric-cars-tesla-stocks-01663596657

There isn't a specific story type where this is an issue, but the most common case where this behavior becomes a headache is with charts like these.

**Comment by swissspidy** [comment]
No plans at the moment to address this
