### ISSUE TITLE
Web Stories not clickable 

### ISSUE THREAD

**Issue by onlinetushar** [swissspidy/web-stories-wp#13000]
Web Stories are not clickable on my website. 

WordPress Version: 6.1.1
Plugin Version: 1.29.0

Error Log: <img width="1435" alt="Screenshot 2023-02-08 at 4 21 31 PM" src="https://user-images.githubusercontent.com/25270041/217510306-16691ddd-c05a-488e-afc4-a1a9f6abf546.png">

Site URL: https:// missionmpsc. com/web-stories/

**Comment by swissspidy** [comment]
Hi there

Please note that we only offer support via the [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/).

From what I can see, you are using both Web Stories for WordPress and MakeStories at the same time, which is not a configuration that is really supported. There might be other plugins playing a role as well, so I recommend you to try disabling all other plugins & switching your theme to see if that resolves the issue.

If this issue still occurs with no other plugins active and when using a default theme like Twenty Twenty, we can take another look at it.

**Comment by swissspidy** [comment]
Please [open a new support topic](https://wordpress.org/support/plugin/web-stories/) if this issue still occurs after disabling all other plugins (including MakeStories Helper) and changing themes.
