### ISSUE TITLE
WordPress Plugin 'Submit for Review' even for Admins

### ISSUE THREAD

**Issue by rishnarang** [swissspidy/web-stories-wp#13016]
## Bug Description

Web Stories created using the WordPress plugin are still pending even though they are being created by admins. Even the creation tool shows 'Submit for Review' instead of the Publish button. 

## Expected Behaviour

Expecting a 'Publish' button instead of 'Submit for Review'

## Steps to Reproduce

1. Stories > Dashboard > Create New Story 
2. 'Submit for Review' on top instead of 'Publish'

## Screenshots
<img width="958" alt="Screenshot 2023-02-13 at 9 01 26 AM" src="https://user-images.githubusercontent.com/82465478/218523320-1a84660c-c737-46cf-924b-8c6dc91dcd13.png">

## Additional Context

- Plugin Version:  1.23.1
- WordPress Version: 6.1.1
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
This was resolved by updating to the latest plugin version
