### ISSUE TITLE
Webstory: Unable to save a post with message "Failed to save the story.."

### ISSUE THREAD

**Issue by tallapallyn** [swissspidy/web-stories-wp#13137]
Unable to publish Post from Draft, message comes up “Failed to save the story. Should not happen”.

Steps to Reproduce:

1 User opened a draft web story created from Duplicate
2. Click on Publish
3. Story details window came up to confirm publish (correct)
4. Click on Publish again

Wordpress version: Version 6.1.1
Web stories : Version 1.28.1
<img width="449" alt="image-20230316-031757" src="https://user-images.githubusercontent.com/96516940/226217103-57650710-4120-4f66-b260-30fe40979812.png">

<img width="1344" alt="Screen Shot 2023-03-20 at 10 43 03 am" src="https://user-images.githubusercontent.com/96516940/226217241-139c7798-62e1-4d12-b815-028cafcd1ae4.png">

**Comment by LuckynaSan** [comment]
Hello @tallapallyn , thanks for your topic. Please note that support is provided at https://wordpress.org/support/plugin/web-stories so please create a topic there first. 

Also, it looks like you are using an older version of the plugin. Can you please update to 1.30.0 and check if the issue occurs there?
