### ISSUE TITLE
Ability to animate multiple selected elements

### ISSUE THREAD

**Issue by jortega-consultant** [swissspidy/web-stories-wp#13155]
## Feature Description

As many publishers use animations throughout their stories, we would like improvements made to support the ability to select multiple objects/layers and apply a uniform animation to the group.

The implementation of this feature should comply with the following cases:

- The user should be able to select multiple objects or layers in the Google Web Story editor.
- The user should be able to apply a uniform animation to the selected objects or layers as a group.
- The user should be able to preview the animation before applying it.
- The feature should be intuitive to use, and the user interface should clearly indicate when multiple objects or layers are selected.

## Alternatives Considered

Right now, users must animate each individual element, when selecting a group of objects/layers, the animation capabilities are not available.

**Comment by swissspidy** [comment]
Previously: #4105, #12830

**Comment by swissspidy** [comment]
As @ayushnirwal pointed out, on the surface it would be relatively simple to show the animations panel for multi-selection. However, the whole panel system is laid out for modifying elements themselves, whereas animations are actually a property on the page object. So making that work requires a bit more effort than originally anticipated.
