### ISSUE TITLE
Display the editor in a light theme

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#13161]
## Feature Description
The user would like an option for the Stories Editor to display in a light theme versus the current dark theme.

## Alternatives Considered

n/a

## Additional Context

related support topic: https://wordpress.org/support/topic/light-theme-2

**Comment by swissspidy** [comment]
While we originally developed the whole design system in both a light and dark theme, we decided to keep the dashboard in the former and the editor in the latter, without any way to switch themes.

As much as I would like to provide the ability to display the editor in a light theme as well, it would require a lot of design refinement first. Right now we don't have the capacity for that.

Closing as maybelater.
