### ISSUE TITLE
Story not loading in player after exiting the lightbox

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#13241]
## Bug Description

A user reported the story player is not loading or displaying as a black screen after viewing it and closing out of the lightbox. 

## Expected Behaviour

Story loads in player after closing out of lightbox or viewing it again.

## Steps to Reproduce

1. Go to site https://newsmaker.com.ar/
2. Click on story
3. Skip through each story
4. Close out of lightbox
5. View first story again
6. Notice black screen

## Screenshots

https://user-images.githubusercontent.com/66372350/234609877-2c60c1e9-c721-4ede-8390-70119ddb3593.mov

## Additional Context

Related support topic: https://wordpress.org/support/topic/more-than-2-stories-black-screen-second-time/

- Plugin Version: 1.31.0
- WordPress Version:
- Operating System:
- Browser:

**Comment by udaykanths** [comment]
Hi team,

Is there any option to revert to the earlier version? 
My site ( https://sareeing.com/web-stories/ ) is currently on "Version 1.33.0" , and facing the issue repeatedly. 

I have my other site which is working absolutely perfect. 
It is running on “Version 1.32.0” ( https://telugu.sareeing.com/web-stories/ )

It seems the issue is from quite a long time & it creating problem on my site ‘s performance.

Please give some solution.

**Comment by udaykanths** [comment]
Dear team, 
please let us know how many months it requires to fix the issue. Probably we will uninstall or disable web stories till then. 
The reason for the dissatisfaction is, this issue hugely impacted on our google "discover performance". Even though users can see our web stories, they get an error the moment they open the story. Hence it looks like the website itself has a problem.
Hope the team of internet's game changing application... "Google Web stories" will understand us & do the needful.
thank you.

**Comment by swissspidy** [comment]
I doubt that this is related to performance on Google Discover, but you might be pleased to hear that we're currently actively looking into this issue.

**Comment by udaykanths** [comment]
Hello @swissspidy , It is the reason for the performance on Google Discover. Especially for latest web story published,  unfortunately it won't work after some time, The link is opening a blank page. And again we need to go with 'Quick Edit' & save the web story, so that it will work for a while. Again after some time, the issue repeats. Again we need to go with 'Quick Edit'. This is the problem from past 2 months. 
P.S.: 
1. This is for a complete new visitor, not related to skipping.
2. In most scenarios, The latest web story is not working.
Refer the link:
[https://www.loom.com/share/1e579f405004404d892be57717fc8798](url)
Please do the needful on high priority.
Regards,
Udaykanth S

**Comment by swissspidy** [comment]
What you are describing is an entirely issue from what is being tracked here. Please open a new support topic on WordPress.org so that we can assist you with that.

**Comment by AnuragVasanwala** [comment]
## Previous Finding
@swissspidy Initially, after a lot of debugging I came to conclusion that `amp-story-player` had bug while setting up iframe src:
https://github.com/ampproject/amphtml/blob/4ce3cd79520dbeaf5ed5364cbff58d3d71dee40e/src/amp-story-player/amp-story-player-impl.js#L1268-L1270

Later on, after so many testing - I found AMP didn't have any bug related. I also crated a sample HTML page to demonstrate story with Lightbox. Working HTML page is attached here:
<details>
  <summary>📄 Expand: HTML WebStory with Lightbox</summary>

```

    <html>

    <head>
    <title>Lightbox Example</title>

    <script async src="https://cdn.ampproject.org/amp-story-player-v0.js"></script>
    <link href="https://cdn.ampproject.org/amp-story-player-v0.css" rel="stylesheet" type="text/css">

    <link href="https://fonts.googleapis.com/css2?family=Poppins&amp;display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <style>
        .entry-point-container {      
        margin-top: 40px;
        margin-bottom: 50px;
        margin-left: auto;
        margin-right: auto;
        }

        .entry-point-card-title {      
        margin-top: 10px;
        font-weight: 500;
        font-family: Poppins;
        font-size: 11px;
        line-height: 15px;
        text-align: center;
        display: block;
        color: #fff;
        width: 100px;
        margin-left: auto;
        margin-right: auto;
        }

        .lightbox {
        position: absolute;
        background-color: rgb(0, 0, 0, 0.7);
        z-index: -99999;
        top: 0;
        bottom: 0;
        right: 0;
        left: 0;
        opacity: 0;
        visibility: hidden;
        transition: visibility 0.2s linear, opacity 0.2s linear;
        }

        .lightbox.show {
        visibility: visible;
        z-index: 99999;
        opacity: 1;
        }

        amp-story-player.my-player {
        width: 100%;
        height: 100%;
        /*   margin: 70px auto; */
        }

        .entry-points {
        width: 100%;
        display: flex;
        left: -20px;
        padding: 0px 60px;
        padding-bottom: 10px;
        }

        .circular-entry-point {
        overflow-x: auto;
        overflow-y: hidden;
        }

        .circular-entry-point img {
        cursor: pointer;
        width: 100px;
        height: 100px;
        border-radius: 100%;
        background-clip: content-box;
        border: 2px solid;
        padding: 3px;
        }

        .entry-point-card-container {
        position: relative;
        padding-right: 25px;
        transition: transform 0.3s;
        }

        /* Extra stuff that makes sample aesthetic. */

        body h1 {
        font-weight: 600;
        font-size: 18px;
        line-height: 27px;
        color: white;
        font-family: Poppins;
        margin-bottom: 35px;
        margin-left: 20px;
        }

        .fake-content {
        width: 320px;
        height: 427px;
        top: -178px;
        margin: auto;

        background: #24242d;
        box-shadow: 0px 2px 8px rgba(0, 0, 0, 0.2);
        border-radius: 16px;
        }

        .viewport {
        /* position: absolute; */
        display: flex;
        flex-direction: column;
        border-radius: 10px;
        padding: 20px;
        margin: auto;
        /* width: 360px;
        height: 800px; */
        background-color: #202029;
        /* overflow: hidden; */
        }
    </style>
    </head>

    <body>
    <div class="viewport">
        <div class="fake-content"></div>
        <div class="entry-point-container">
        <h1> Web Stories </h1>
        <div class="circular-entry-point">
            <div class="entry-points">
            <div class="entry-point-card-container">
                <img src="https://assets.codepen.io/1780597/4.png" style="border-color:#FF6F32">
                <span class="entry-point-card-title">Q&A with ZOE Newman</span>
            </div>
            <div class="entry-point-card-container">
                <img src="https://assets.codepen.io/1780597/1.png" style="border-color:#E6AD1C">
                <span class="entry-point-card-title">24 Hours in New York City</span>
            </div>
            <div class="entry-point-card-container">
                <img src="https://assets.codepen.io/1780597/3.png" style="border-color:#466FFF">
                <span class="entry-point-card-title">The Next King of the Sea</span>
            </div>
            <div class="entry-point-card-container">
                <img src="https://assets.codepen.io/1780597/2.png" style="border-color:#4CA47C">
                <span class="entry-point-card-title">Spark a Passion for Reading</span>
            </div>
            </div>
        </div>
        </div>
        <div class="lightbox">
        <amp-story-player class="my-player">
            <script type="application/json">
            {
                "behavior": {
                "autoplay": false,
                "pageScroll": false
                },
                "controls": [{
                "name": "close",
                "position": "start"
                }]
            }
            </script>

            <a href="https://ampfest-story-player-demo.web.app/examples/amp-story/AMPFestPlayerDemo/s1"></a>
            <a href="https://ampfest-story-player-demo.web.app/examples/amp-story/AMPFestPlayerDemo/s2"></a>
            <a href="https://ampfest-story-player-demo.web.app/examples/amp-story/AMPFestPlayerDemo/s3"></a>
            <a href="https://ampfest-story-player-demo.web.app/examples/amp-story/AMPFestPlayerDemo/s4"></a>
        </amp-story-player>
        </div>
    </div>
    <script>
        const player = document.body.querySelector("amp-story-player");
        const lightboxEl = document.querySelector(".lightbox");

        if (player.isReady) {
        initializeCarousel();
        } else {
        player.addEventListener("ready", () => {
            initializeCarousel();
        });
        }

        function initializeCarousel() {
        const stories = player.getStories();

        const thumbnails = document.querySelectorAll(
            ".entry-point-card-container img"
        );

        thumbnails.forEach((img, idx) => {
            img.addEventListener("click", () => {
            player.show(stories[idx].href);
            player.play();
            lightboxEl.classList.toggle("show");
            });
        });
        }

        player.addEventListener("amp-story-player-close", () => {
        player.pause();
        lightboxEl.classList.toggle("show");
        });

    </script>
    </body>

    </html>
```
</details>

## Recent Finding
@swissspidy It seems like this LightBox issue started after fixing this issue https://github.com/GoogleForCreators/web-stories-wp/issues/12999.

Commenting out following browser history lines solves the issue:
https://github.com/GoogleForCreators/web-stories-wp/blob/a3c73c2942cf1966c5e0073f6478d7b89fed8134/packages/stories-lightbox/src/web-stories-lightbox.js#L61
https://github.com/GoogleForCreators/web-stories-wp/blob/a3c73c2942cf1966c5e0073f6478d7b89fed8134/packages/stories-lightbox/src/web-stories-lightbox.js#L131

Seems like pushing `storyObject.href` to history is having some conflict with AMP 🤔

**Comment by swissspidy** [comment]
Ah, interesting, we're onto something! 👀
