### ISSUE TITLE
How to add PUBLISH TO REVIEW button to Authors As well

### ISSUE THREAD

**Issue by nimish1995** [swissspidy/web-stories-wp#13243]
## Task Description

Please help me to remove access from the author to publish directly.

I want to add a "Publish to review" button for authors.

I am new to your plugin, I am using the "Publish to review" button on my post, just adding a few codes to my website [Techniblogic](https://techniblogic.com)

```
//Disable, Author, Publish Button Code Starts

   function take_away_publish_permissions() {
        $user = get_role('author');
        $user->add_cap('publish_posts',false);
	    $user->add_cap('delete_published_posts',false);
	 
	   
   }
   add_action('init', 'take_away_publish_permissions' );

function take_away_stories_publish_permissions() {
 $user->remove_cap('publish_posts');

}

//Disable, Author, Publish Button Code Ends
```
But this code does not work on your Web stories plugin.

Can you please help me out? 

Waiting for your response. Thanks in Advance

**Comment by swissspidy** [comment]
The web-story post type has its own capabilities:

edit_web-stories
edit_others_web-stories
delete_web-stories
publish_web-stories
read_private_web-stories
delete_private_web-stories
delete_published_web-stories
delete_others_web-stories
edit_private_web-stories
edit_published_web-stories

You can use a plugin like Members for troubleshooting.

**Comment by nimish1995** [comment]
Thank you for helping. I added your capabilities to my code, and it works.
