### ISSUE TITLE
Import Issue -  Post Content Filtered in databse 

### ISSUE THREAD

**Issue by mikezielonka** [swissspidy/web-stories-wp#13283]
## Bug Description

Followed a straightforward export/import process using WP All Export and Import to ensure the post content filtered column is migrated from staging to prod.  see details [here](https://github.com/GoogleForCreators/web-stories-wp/issues/4357) 

To ensure valid json, I manually moved the post content filtered contents from staging to prod's DB after search and replacing the URLs.

Content is valid json and present in production DB

![Screenshot by Dropbox Capture](https://github.com/GoogleForCreators/web-stories-wp/assets/1565502/1436439d-7a97-4d12-89ea-90391da84bac)

![Screenshot by Dropbox Capture](https://github.com/GoogleForCreators/web-stories-wp/assets/1565502/46d4bd18-b90e-4149-883b-878e99db3973)

## Expected Behaviour

Web Story should be editable in the WP web stories editor rather than showing a blank new story

## Steps to Reproduce

Import staging sql into production and replace the root URL to use the production root.  This method assumes some broken images but that can be resolved with my final export/import using the WP All Import/Export plugin

## Additional Context

Editor Preview (post import)
![Screenshot by Dropbox Capture](https://github.com/GoogleForCreators/web-stories-wp/assets/1565502/0c06c4a4-1384-4f6c-b9bf-43e8d685735e)

Web Story Preview  (post import)
![Screenshot by Dropbox Capture](https://github.com/GoogleForCreators/web-stories-wp/assets/1565502/794620b1-baab-4adf-b140-b21e0f4ed5be)

- Plugin Version: 1.32.0
- WordPress Version: 6.2
- Operating System: macOS latest
- Browser: chrome latest

[staging export.sql.zip](https://github.com/GoogleForCreators/web-stories-wp/files/11473322/staging.export.sql.zip)

[hamburger buns prod.sql.zip](https://github.com/GoogleForCreators/web-stories-wp/files/11473313/hamburger.buns.prod.sql.zip)

**Comment by mikezielonka** [comment]
We have web stories on staging that didn't get migrated when we did a theme refresh.  The team did the normal import/export from WP and then pinged me asking me to taking a deeper look.  Then it hit me... I know the issue. :) 

I'll set it up locally here and debug a bit more.

Any additional tooling tho would be excellent.

Perhaps a long term solution would be adding support to the core import/export to include the post_content_filtered column for stories?

**Comment by swissspidy** [comment]
> Perhaps a long term solution would be adding support to the core import/export to include the post_content_filtered column for stories?

Unfortunately WordPress core has no way of adding this extra column to neither the import or the export. 😞  Otherwise we would have added this a long time ago.

**Comment by mikezielonka** [comment]
> > Perhaps a long term solution would be adding support to the core import/export to include the post_content_filtered column for stories?
> 
> Unfortunately WordPress core has no way of adding this extra column to neither the import or the export. 😞 Otherwise we would have added this a long time ago.

This plugin, [Export media with selected content](https://wordpress.org/plugins/export-media-with-selected-content/), has a clever work around as an example to include media when you export via core's exporter.  Maybe some inspiration there.💡
