### ISSUE TITLE
GA4 on web-stories: I can't fill the field

### ISSUE THREAD

**Issue by isantolin** [swissspidy/web-stories-wp#13316]
## Bug Description

Web-Stories still can´t support GA4.

## Expected Behaviour

Ability to add a GA4 datastream on Web-Stories. (Because Site-Kit still cant support GA4 over AMP)

## Steps to Reproduce

1. Stories > Settings > Fill the "Google Analytics Tracking ID" field
2. The field will show an "Invalid ID format" validation error

## Screenshots

![image](https://github.com/GoogleForCreators/web-stories-wp/assets/264640/ff56e6af-3a8c-473d-9860-df8d50381a5d)

## Additional Context
- Plugin Version: 1.32.0
- WordPress Version: 6.2.2
- Operating System: Fedora 38
- Browser: 114.0.5735.45

**Comment by swissspidy** [comment]
GA4 does not currently support Web Stories, which is why you can‘t enter your GA4 ID there.

We will inform our users when there is an update regarding GA4.
