### ISSUE TITLE
Error: Can't resolve 'module' in 'node_modules/mediainfo.js/dist'

### ISSUE THREAD

**Issue by sanir** [swissspidy/web-stories-wp#13383]
I am using react 18

Using 
**Standalone Editor Tutorial**

https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/third-party-integration/story-editor/tutorial.md

geting error  Can't resolve 'module' in 'node_modules/mediainfo.js/dist'

**Comment by swissspidy** [comment]
We are not using React 18 yet and thus don't officially support it right now, could you try with React 17 instead?

**Comment by sanir** [comment]
let me check with React 17

**Comment by swissspidy** [comment]
You might need to update your webpack config like this:

https://github.com/GoogleForCreators/web-stories-wp/blob/1e66368e8715d082b1b6e58a8a704a960f88e49a/webpack.config.cjs#L66-L74

**Comment by sanir** [comment]
fallback: { 
   fs: false, 
   path: false, 
   url: false, 
   module: false, 
   assert: false, 
   perf_hooks: false, 
 }, 

Add in webpack.config.js, not working

**Comment by sanir** [comment]
<img width="1405" alt="Screenshot 2023-06-22 at 8 36 53 PM" src="https://github.com/GoogleForCreators/web-stories-wp/assets/11961089/66e3996b-980c-43a6-9198-d27dda28be9f">

Please check error

**Comment by swissspidy** [comment]
Then I don't know what's happening off the top of my head, sorry. I would need a public repository to reproduce the issue myself, but I don't currently have the bandwidth for looking into this too deeply. Alternatively I'd recommend asking on StackOverflow since it seems like a webpack configuration issue.

**Comment by sanir** [comment]
@swissspidy, sure thanks
