### ISSUE TITLE
Stories Archives Settings: Search field displaying HTML characters for pages

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#13404]
## Bug Description

In Stories Archives settings, the HTML characters are displaying in search results for page that has them.

## Expected Behaviour

For the page with symbols to pull up in search field without html characters. 

## Steps to Reproduce

1. Go to Settings > Stories Archives
2. Select Create Your Own
3. Type in a page containing symbols (e.g. Lucky's)
4. Notice HTML characters 

## Screenshots

<img width="966" alt="Screenshot 2023-06-28 at 10 04 45 AM" src="https://github.com/GoogleForCreators/web-stories-wp/assets/66372350/edb22ca1-41a4-4edd-9ea0-57da4887bd07">

## Additional Context

- Plugin Version: 1.33.0
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Possibly related: #9408

Probably caused by the fact that we use the `rendered` field (vs. the `raw` field) from the WP REST API responses which has these HTML entities in it. We might need to use `dangerouslySetInnerHTML` for this.

**Comment by AnuragVasanwala** [comment]
> Possibly related: #9408
> 
> Probably caused by the fact that we use the `rendered` field (vs. the `raw` field) from the WP REST API responses which has these HTML entities in it. We might need to use `dangerouslySetInnerHTML` for this.

@swissspidy I have fixed this issue (in PR #13410) by decoding HTML characters and returned updated string to the respective function instead of using `dangerouslySetInnerHTML`.
