### ISSUE TITLE
Image Alignment is off in the Carousel View

### ISSUE THREAD

**Issue by narangrishab** [swissspidy/web-stories-wp#13429]
## Bug Description

Image alignment is off due to 

```
.web-stories-list__story-poster img {
position: absolute;
}
```

while using web stories carousel view 

## Steps to Reproduce

1. Wordpress > Post > Text > Web Stories
2. Select layout > Box Carousel

## Screenshots
<img width="1236" alt="Screenshot 2023-07-21 at 12 15 14 PM" src="https://github.com/GoogleForCreators/web-stories-wp/assets/9140727/efa57092-5753-4181-b13c-4dc1cdc84272">
<img width="629" alt="Screenshot 2023-07-21 at 12 15 07 PM" src="https://github.com/GoogleForCreators/web-stories-wp/assets/9140727/ffc72eb9-ff98-453b-93a8-a1e7a5b986b9">

Expected

<img width="1294" alt="Screenshot 2023-07-21 at 12 15 19 PM" src="https://github.com/GoogleForCreators/web-stories-wp/assets/9140727/a4719748-e518-4fc3-b5d3-a9d60ce1abe0">

## Additional Context

- Plugin Version: 1.33.0
- WordPress Version: 6.2.2
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
Which theme is this with? Does it happen when using another theme?

**Comment by swissspidy** [comment]
Looks like this is from https://www.andreaabroad.com/, which uses a custom theme and some custom plugins, like a Pinterest button that might interfere, plus using WPBakery Page Builder.

---

Aside: we could consider adding `data-pin-nopin="true"` to the story posters to disable the Pinterest "Pin It" functionality for story posters in the carousel.

**Comment by swissspidy** [comment]
Not clear what caused the issue, but suggested fixing it with some custom CSS:

```css
.web-stories-list.is-view-type-carousel.is-style-default .web-stories-list__story-poster img {
display: block;
}
```
