### ISSUE TITLE
Custom Fonts availability depends on posts_per_page wordpress general setting

### ISSUE THREAD

**Issue by mpachas** [swissspidy/web-stories-wp#13441]
## Bug Description

You can only list and use as many fonts as that wordpress general setting value.

This is the REST API query, but it is not really limited (only) by the per_page args: /wp-json/web-stories/v1/fonts/?per_page=100&service=custom&_locale=user
## Expected Behaviour

Show all that fonts and be able to use them
## Steps to Reproduce
Add more than one custom font, then go to 
Wordpress Settings->Reading and change "blog pages show at most " and change it to 1.
You wont see more than 1 custom font listed in Web Stories settings and you wont be able to use more than that one in the stories editor.
## Additional Context
This is the clue I needed:
https://stackoverflow.com/questions/30325170/using-wp-query-in-functions-php-only-returning-one-result
WP_Query limits the number of results based on that setting. 

I guess you should use another value for this query to get web-stories-font posts from the db.

**Comment by swissspidy** [comment]
Thanks for your detailed report, it's much appreciated!

> I guess you should use another value for this query to get web-stories-font posts from the db.

Not quite :-) That's what `per_page=100` is for. The issue is that it was incorrectly ignored. We'll fix this in the next release.

Thanks again.

**Comment by mpachas** [comment]
Thanks a lot. I've found that 100 is the max value (limited by the rest api). More than 100 fonts may be added and never seen again. I'm not sure it there is a way to limit the number of fonts added or at least to show a little info message. 

We have 37 right now 🤕

**Comment by swissspidy** [comment]
> When called from the web stories editor there is no `per_page` args in the query and only 10 fonts are given. Do I have to create a new issue?

No need, we'll fix that in #13442 as well.

> Thanks a lot. I've found that 100 is the max value (limited by the rest api). More than 100 fonts may be added and never seen again. I'm not sure it there is a way to limit the number of fonts added or at least to show a little info message.

We'll consider adding some pagination in the future. 100+ fonts sounds like an edge case though, so probably not a high prio.
