### ISSUE TITLE
How to add custom functionality

### ISSUE THREAD

**Issue by El-Potato-Slayer** [swissspidy/web-stories-wp#13505]
## Summary

I'm trying to add custom functionalities, such as a before/after slide and modal components. However, I'm stumbling stuck at a roadblock. I don't understand how the project ties everything together.

## What I tried

I wanted to add a new list of button in addition to the default ones. So I added new elements to the `noElementSelectedActions` variable in the `useQuickActions` hook. To simplify it, I'll only show a default item and my custom item:
```
const noElementSelectedActions = useMemo(() => {
return [
      {
        Icon: Bucket,
        label: ACTIONS.CHANGE_BACKGROUND_COLOR.text,
        onClick: (evt) => {
          handleFocusPageBackground(backgroundElement?.id)(evt);

          trackEvent('quick_action', {
            name: ACTIONS.CHANGE_BACKGROUND_COLOR.trackingEventName,
            element: 'none',
          });
        },
        ...actionMenuProps,
      },
      {
        Icon: Shopping,
        label: 'Hotspot Modal',
        onClick: () => {
          setIsModalOpen(true)          
        },
        ...actionMenuProps,
      },
}
```

`setIsModalOpen` is a parameter I added to the `useQuickActions` hook so that the state can be passed from the parent:
```
const useQuickActions = (setIsModalOpen) => {
...
}
```

In `canvasLayout.js`, I'm creating the state and passing it to the hook as follows:
```
  const [isModalOpen, setIsModalOpen] = useState(false);
  const quickActions = useQuickActions(setIsModalOpen);
```

To test that it works, I added the Modal component in the `return` statement of the `canvasLayout` component:
```
return (
    <StyleSheetManager stylisPlugins={[]}>
      <EditLayerFocusManager>
        <Background ref={setBackgroundRef} style={layoutParamsCss}>
          <CanvasUploadDropTarget>
            <CanvasElementDropzone>
              <SelectionCanvas>
                {hasDimensions && !isInRecordingMode && <DisplayLayer />}
                {hasDimensions && !isInRecordingMode && <FramesLayer />}
                <NavLayer setShowSlider={setShowSlider} header={header} footer={footer} />
              </SelectionCanvas>
              <EditLayer />
              {!isInRecordingMode && (
                <>
                  <EyedropperLayer />
                  <EmptyStateLayer showSlider={showSlider} />
                  <FloatingMenuLayer />
                </>
              )}
              {isInRecordingMode && <MediaRecordingLayer />}
            </CanvasElementDropzone>
          </CanvasUploadDropTarget>
        </Background>
        <Modal isOpen={isModalOpen}>
          Test
        </Modal>
      </EditLayerFocusManager>
    </StyleSheetManager>
  );
```

## What do I expect to happen?

I expect the modal to open once I click on the `Hotspot Modal` button (created in the useQuickActions hook). However, the `setIsModalOpen` argument is undefined. I've verified that the state is `false` in the parent component (CanvasLayout). This leads to me believe that I'm not doing things the way its meant to be done in the projecct. I'd like an explanation or a very short guide as to what I need to do exactly in order to add custom features.

**Comment by swissspidy** [comment]
`useQuickActions` is not really meant to be used in other places like `canvasLayout.js`. It's used in exactly one place, `pageSideMenu.js`, to render that list of buttons. So when you call the hook in another place that will have simply no effect as it's a separate invocation with separate state. When you click on the button, what matters is what is passed to the hook in `pageSideMenu.js`.

What you are looking for is a way to set global state in one place (the quick actions component) and retrieve it in another (the edit layer component). For that, it's probably easiest to add your state to the `CanvasProvider` context provider.
Take a look how a similar thing is done for the `isEyedropperActive` state.
