### ISSUE TITLE
[Question] Generate video from stories 

### ISSUE THREAD

**Issue by santoshgistto** [swissspidy/web-stories-wp#13510]
## Question

Is there any way to create video from story editor ?
Pointers will helpful 
Thank you.

**Comment by swissspidy** [comment]
No, there isn't. This story editor doesn't support such a feature, though we explored that a few years ago in #7747. Right now we do not have any plans to revisit this.

If you want to build something yourself, look into tools like Remotion (which MakeStories uses, AFAIK) or screen capturing in a headless browser.

**Comment by santoshgistto** [comment]
Thank you

**Comment by santoshgistto** [comment]
With remotion it will easier looks like  need to export story as react component or html. 
Remotion doesn't understand AMP
