### ISSUE TITLE
Provide ability for users to move, group, and name templates

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#13517]
## Feature Description

As a user, I want the ability to move, group, and name templates in order to organize and categorize them based on their purpose or usage. This will make it easier for other users to understand the purpose of each template and locate the relevant one for their needs.

Acceptance Criteria

- User can move templates to different folders or groups based on their purpose or category.
- User can rename the templates so that other users can easily understand what they are for.
- The new folder/group names and template names are saved and visible to all users with access to the project.
- Moving, grouping or renaming templates does not affect the content or design of the templates.
- The feature is easy to use and understand, with clear instructions and user-friendly interface.
- The feature is stable and reliable, with no unexpected bugs or errors.
- The feature is integrated seamlessly with the existing template creation and editing functions.
- The feature is responsive and fast, with no noticeable lag or delay when moving, grouping or renaming templates.
- The feature is fully documented in the user manual or help center, with clear examples and use cases.
- The feature is tested thoroughly before release to ensure it meets the acceptance criteria and works as expected in various scenarios.

## Additional Context

This would reduce time to author via the creation of named, organized templates that can be leveraged as common starting points for authors.

**Comment by swissspidy** [comment]
How lovely to see you around @bmattb! 🤗  Thanks for filing this request!

Naming custom page templates is already possible nowadays:

<img width="578" alt="Screenshot 2023-11-29 at 22 30 19" src="https://github.com/GoogleForCreators/web-stories-wp/assets/841956/42c334d4-688a-45a2-a688-74c6b61961ec">

Tagging/Grouping/Categorizing templates is an interesting idea 👍  I'll need to think about how this could be best done.

**Comment by bmattb** [comment]
HI @swissspidy !!! Happy to be back! Thanks for letting me know about that feature, looks like we would need to update to the latest version of the plugin to get that activated.

Please do let me know if you feel that grouping/tagging/categorization is something that will be picked up

**Comment by swissspidy** [comment]
> Please do let me know if you feel that grouping/tagging/categorization is something that will be picked up

Off the top of my head I'd say it's unlikely or not in the next few months unless there's a big need for it. It would be quite some effort to implement, so I'd want to make sure that's warranted.

**Comment by swissspidy** [comment]
There isn't really a big ask for grouping/tagging at the moment, so closing this one for now.
