### ISSUE TITLE
Include an option to include separate measurement ID if SiteKit is installed. 

### ISSUE THREAD

**Issue by tajstar** [swissspidy/web-stories-wp#13524]
## Feature Description

Currently when a user has Sitekit installed, they will get a message that says " Site Kit by Google has already enabled Google Analytics for your Web Stories", but Sitekit doesn't allow setting a separate Measurement ID for web stories which users may want to use to track the data separately from the other pages on their site. 

![image](https://github.com/GoogleForCreators/web-stories-wp/assets/17879677/4bc31936-ad6c-4ab6-9773-2fe4219e7207)

It would be useful to have a toggle that would disable the Sitekit measurement ID and allow it to be set in the web stories plugin. 

## Alternatives Considered

Currently I use the following PHP snippet to disable the Site Kit's GA4 and add a custom one. But a toggle for less technical users would be better.

```php
function add_ga4_amp_script() {
    $ga4_amp_script = '
<amp-analytics type="googleanalytics" config="https://amp.analytics-debugger.com/ga4.json" data-credentials="include">
<script type="application/json">
{
  "vars": {
    "GA4_MEASUREMENT_ID": "G-xxxxxx",
    "GA4_ENDPOINT_HOSTNAME": "www.google-analytics.com",
    "GOOGLE_CONSENT_ENABLED": false,
    "WEBVITALS_TRACKING": false,
    "PERFORMANCE_TIMING_TRACKING": false,
    "DEFAULT_PAGEVIEW_ENABLED": true,
    "SEND_DOUBLECLICK_BEACON": false,
    "DISABLE_REGIONAL_DATA_COLLECTION": false,
    "ENHANCED_MEASUREMENT_SCROLL": false
  }
}
</script>
</amp-analytics>
';
    echo $ga4_amp_script;
}
add_action('web_stories_print_analytics', 'add_ga4_amp_script');

// Prevent Sitekit from loading UA
add_filter(
    'googlesitekit_analytics_tag_amp_blocked',
    static function ( $blocked ) {
       return $blocked ?: is_singular( 'web-story' );
    }
);


// Prevent Sitekit from loading ga4
add_filter(
    'googlesitekit_analytics-4_tag_amp_blocked',
    static function ( $blocked ) {
       return $blocked ?: is_singular( 'web-story' );
    }
);
```

**Comment by swissspidy** [comment]
Heya, thanks a lot for reaching out!

We're tracking this enhancement in #13506 right now and are actively looking into how to best provide this option on the settings page.

I'm aiming for adding this in the next release, so stay tuned!

Feel free to subscribe to #13506 for any updates in the meantime.
