### ISSUE TITLE
Cover image does not update in 1.35.0

### ISSUE THREAD

**Issue by altendorfme** [swissspidy/web-stories-wp#13539]
There is a conflict between the Webstories plugin in version 1.35.0 and the Advanced Custom Field Extended (https://wordpress.org/plugins/acf-extended/) plugin.

In the last update of Webstories (1.35.0), updating the cover image does not work. I went back 10 versions of the Advanced Custom Field Exteded plugin and the problem persists.

When returning to version 1.34.0 of Webstories the problem is solved.

**Comment by swissspidy** [comment]
Hiya, thanks for reaching out.

The changes in https://github.com/GoogleForCreators/web-stories-wp/releases/tag/v1.35.0 are relatively minor. I don't see anything in there that would cause any conflict with another plugin 🤔 

Also worth noting that Web Stories does not really support/use ACF, so not sure how that would even happen. Plus, ACF Extended requires ACF Pro and I do not have ACF Pro so I cannot test this issue at all.

If you can provide detailed reproduction steps, screenshots, error messages, or perhaps a testing environment, we might be able to look into it.

**Comment by altendorfme** [comment]
That's the problem, I don't see any kind of problem in the server log or in the browser console. It simply doesn't work. Creating Stories works, only the cover doesn't update.

First I turned off all the plugins, then turned them on one by one and tested, when I got to ACF Extended this bug happened.
I turned off ACF Extended and continued turning on all the other plugins.

The end result was that with ACF Extended enabled this problem appears.

The current version of ACF Extended is 1.8.9.5, I went back to version 1.8.9 and the problem continues.

I also sent a ticket to the Extended developer

**Comment by altendorfme** [comment]
Video:

https://github.com/GoogleForCreators/web-stories-wp/assets/1530032/0b655f9c-f320-4c86-ab11-651bef209dfd

**Comment by swissspidy** [comment]
Saving seems to work fine, so best to check the Network tab in dev tools when saving to see what's going on. You'll want to check which featured media ID gets sent to the server and which one is retrieved. Most probably another plugin is interfering there and not letting you save changes.

In the bottom right corner of the editor you have the "M" button. If you toggle it, it will show all your custom meta boxes. Which ones are there? Is there perhaps a custom meta box handling post thumbnails that could be interfering here?

**Comment by altendorfme** [comment]
Thank you, when I clicked on "M" it showed a field that was limited to not only appear in 3 other post types, but without explanation it was also appearing in Web stories.

From what I understand, it was an ACF configuration JSON synchronization error.

Thank you for your attention!
