### ISSUE TITLE
Third Party Integration: Having issue while adding PublishPanel component

### ISSUE THREAD

**Issue by sayamalvi** [swissspidy/web-stories-wp#13600]
I am integrating web stories in nextjs. While trying to add PublishPanel component, the editor is crashing. Commenting PublishPanel doesn't crashes the editor. Need help regarding this. 

![Screenshot 2024-03-02 145109](https://github.com/GoogleForCreators/web-stories-wp/assets/52599441/3fa436fd-1462-46e0-a59c-3b67f3006153)
![Screenshot 2024-03-02 145228](https://github.com/GoogleForCreators/web-stories-wp/assets/52599441/717bd6b2-8c16-424d-b136-c01230597465)
![Screenshot 2024-03-02 145454](https://github.com/GoogleForCreators/web-stories-wp/assets/52599441/ce712dac-cc60-4a8e-91e0-1304a356740c)

**Comment by swissspidy** [comment]
Unfortunately we don't really have the capacity to help with such integrations in much detail. Especially without any code repository to look at. Note that we haven't tested the packages with Next.js either.

I recommend using React dev tools and similar to debug this further based on the error message which seems to be very descriptive.
