### ISSUE TITLE
[working now] - Third Party Media Search Stopped Working

### ISSUE THREAD

**Issue by mindbugg** [swissspidy/web-stories-wp#13622]
## Bug Description

When attempting to use the third-party media search functionality in the plugin, the search unexpectedly stops. When I investigated and tried to hit it manually, it  prompts for a CAPTCHA verification, interrupting workflow and preventing media from being searched effectively. This issue began occurring without any changes to the plugin settings or WordPress configuration.

## Expected Behaviour

The expected behavior is that the third-party media search should function seamlessly without requiring intermittent CAPTCHA verifications, allowing for consistent and uninterrupted access to media resources.

## Steps to Reproduce

1. Go to the WordPress admin panel.
2. Navigate to the Web Stories plugin.
3. Click on 'Add New Story'.
4. Attempt to search for media using the third-party media search tool.
5. Observe that the search halts and a CAPTCHA prompt appears.

## Additional Context

- Plugin Version: 1.36.0
- WordPress Version: 6.5.2
- Operating System: Macos Version 124.0.6367.92
- Browser: Version 124.0.6367.92

**Comment by mindbugg** [comment]
<img width="1440" alt="media issue" src="https://github.com/GoogleForCreators/web-stories-wp/assets/18733918/faff80f4-039b-42a8-a3fd-9fa2396926b4">

**Comment by mindbugg** [comment]
<img width="1342" alt="too many requests" src="https://github.com/GoogleForCreators/web-stories-wp/assets/18733918/6016b586-a6b2-40df-bdb3-2f3c489a655f">

**Comment by mindbugg** [comment]
working now, it was down for a some time

**Comment by swissspidy** [comment]
Strange. We‘ll keep an eye on it
