### ISSUE TITLE
M.getExtension error on third party integration (React JS)

### ISSUE THREAD

**Issue by roshab007** [swissspidy/web-stories-wp#13630]
![Screenshot from 2024-05-14 21-43-36](https://github.com/GoogleForCreators/web-stories-wp/assets/126071843/10a701c0-0120-41d7-b78a-67b4fb7cd080)

**Comment by swissspidy** [comment]
Hi there, can you please share more information like a code repository to reproduce the issue? Otherwise we can‘t really assist much. Thanks!

**Comment by roshab007** [comment]
> Hi there, can you please share more information like a code repository to reproduce the issue? Otherwise we can‘t really assist much. Thanks!

Repo:https://github.com/roshab007/Web-Stories

**Comment by swissspidy** [comment]
Awesome, thank you!

Looks like it's because of 8e349ab044ffb21498a4f0c0e008feecfa4c91d9.

I just published new version of our packages so that said change is included. Once you update your project, the issue should go away.

**Comment by roshab007** [comment]
Thanks after updating to the latest version It is working now
