### ISSUE TITLE
RU translation is not showing properly on Web Stories

### ISSUE THREAD

**Issue by CJTS15** [swissspidy/web-stories-wp#13738]
## Bug Description

When uploading a content in RU language, when saving and viewing it on the frontend, it is not showing properly. I will attach a screenshot.

## Expected Behaviour

It should be displaying properly.

## Screenshots
![Screenshot 2024-07-01 at 2 48 04 PM](https://github.com/GoogleForCreators/web-stories-wp/assets/15966569/23649de8-ed59-4f68-896e-4f0b6e7e359b)

## Additional Context

- Plugin Version: 1.36.0
- WordPress Version: 6.5.5
- Operating System: Windows 11 Home
- Browser: Firefox, Chrome

**Comment by swissspidy** [comment]
Hi there, we don't provide support via GitHub. Since you have already opened a [support topic](https://wordpress.org/support/topic/translating-web-stories-to-ru/) in the right place, let's discuss it there.
