### ISSUE TITLE
Storybook preview not loading 

### ISSUE THREAD

**Issue by santoshgistto** [swissspidy/web-stories-wp#13733]
## Bug Description

When we click on preview button in editor, the preview page not loading the story  

## Expected Behaviour

Should load story preview 

## Screenshots
![Screenshot 2024-06-26 at 10 23 01 AM](https://github.com/GoogleForCreators/web-stories-wp/assets/12577046/9adc8139-1a67-4183-9647-7be6edf4292d)

## Additional Context

- Plugin Version: NA
- WordPress Version: NA
- Operating System: Mac
- Browser: Chrome

**Comment by swissspidy** [comment]
Thanks for letting us know.

The storybook isn't exactly a priority right now, so it's not something we're actively going to fix, but happy accept PRs for it.
