### ISSUE TITLE
importing "TaxonomiesPanel" in "DocumentPane" is not working as expected

### ISSUE THREAD

**Issue by AbhayPai** [swissspidy/web-stories-wp#13868]
## Bug Description
I am creating Standalone Editor following this [documentation](https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/third-party-integration/story-editor/tutorial.md). Where i got stuck/blocked when i am importing TaxonomiesPanel in DocumentPane.

<img width="351" alt="Image" src="https://github.com/user-attachments/assets/a37e29cd-d4e6-45a5-a969-5102efea806f" />

## Expected Behaviour
Once i import `TaxonomiesPanel` in DocumentPane and create dummy data for `getTaxonomies`; i should be able to see taxonomies dummy panel.

<img width="349" alt="Image" src="https://github.com/user-attachments/assets/71d66933-2ed4-4885-bae7-89abc67b2856" />

## Steps to Reproduce
```
const getTaxonomies = () => {
  const taxonomies = [
    {
      slug: 'tax1',
      hierarchical: true,
      restBase: 'tax1_Base',
      restPath: 'tax1/path',
      labels: {
        filterByItem: 'Filter by tax1',
        allItems: 'All Tax1',
        searchItems: 'Search Tax1',
        notFound: 'No tax1s found',
      },
    },
  ];
  return Promise.resolve(taxonomies);
};

export default getTaxonomies;
```
i am using this above dummy data to fulfill requirement of `getTaxonomies` in taxonomies.js file https://github.com/GoogleForCreators/web-stories-wp/blob/main/packages/story-editor/src/components/panels/document/taxonomies/taxonomies.js#L40

**Comment by swissspidy** [comment]
As you can see from the link you shared, the taxonomy terms are only shown if the user has the necessary capabilities to assign taxonomy terms:

https://github.com/GoogleForCreators/web-stories-wp/blob/f3f21fa92853188dd9fe306ea8b7239a42b6f186/packages/story-editor/src/components/panels/document/taxonomies/taxonomies.js#L40-L60

Similar for the media upload capabilities, you'll need to pass the current user's capabilities to the story editor via its config. It could look like this:

```
{
    publish: true,
    'assign-author': true,
    'assign-my-awesome-taxonomy': true,
    'create-my-awesome-taxonomy': true,
    'assign-another-taxonomy': true,
    'create-another-taxonomy': true,
  },
```

**Comment by swissspidy** [comment]
Ah, apologies, it's not part of the story editor config like `hasMediaUploadAction`, but it's part of the story object, like title and so on.

Here's an example from our tests:

https://github.com/GoogleForCreators/web-stories-wp/blob/f3f21fa92853188dd9fe306ea8b7239a42b6f186/packages/story-editor/src/karma/fixture/db/storyResponse.js#L74-L98

**Comment by AbhayPai** [comment]
Interesting... It works as expected for category, i am still debugging why tags are not searchable with dummy data for tags & configured capabilities for it.
<img width="343" alt="Image" src="https://github.com/user-attachments/assets/7c8a926d-d133-42b9-b364-48fd5ce2b724" />
<img width="399" alt="Image" src="https://github.com/user-attachments/assets/2024730f-96e6-41d1-be37-b6e584bebaf4" />
<img width="475" alt="Image" src="https://github.com/user-attachments/assets/71986087-aaed-4a8f-a22f-14e6edf2b49c" />
