### ISSUE TITLE
importing "BackgroundAudioPanel" in "DocumentPane" is not working as expected

### ISSUE THREAD

**Issue by AbhayPai** [swissspidy/web-stories-wp#13867]
## Bug Description
I am creating `Standalone Editor` following this [documentation](https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/third-party-integration/story-editor/tutorial.md). Where i got stuck/blocked when i am importing `BackgroundAudioPanel` in `DocumentPane`, i am not sure if this import requires some pre-requisites or i am missing some configuration. Other panels like `Visibility`, `Story Description`, etc are working as expected while importing & i am able to use it as require.

## Expected Behaviour
Once i import `BackgroundAudioPanel` in `DocumentPane`, i should be able to see Background audio panel in document pane & atleast i should be able to use `Link to audio file`

## Screenshots
![Not Working Image](https://github.com/user-attachments/assets/f531639a-a843-4feb-901b-2cccf0d1df3d)

![Expected Image](https://github.com/user-attachments/assets/aef98fdd-c95a-4ef6-bfbd-4e797e742263)

**Comment by swissspidy** [comment]
The panel doesn't render if you lack upload permissions, see https://github.com/GoogleForCreators/web-stories-wp/blob/f3f21fa92853188dd9fe306ea8b7239a42b6f186/packages/story-editor/src/components/panels/document/backgroundAudio/backgroundAudio.js#L64-L66

**Comment by swissspidy** [comment]
See https://github.com/GoogleForCreators/web-stories-wp/blob/f3f21fa92853188dd9fe306ea8b7239a42b6f186/docs/third-party-integration/story-editor/integration-layer.md#editor-config how to pass the capabilities config to the editor component.

**Comment by AbhayPai** [comment]
Appreciate your quick response here @swissspidy, We can close this support issue now :)
