### ISSUE TITLE
Taxonomy: Loading Errors 

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9033]
(Placeholder) 

If we cannot retrieve categories or tags to render in the editor, how should we display that error?

TODO: 
- demo how Gutenberg handles then and then discuss with Andrew

**Comment by maxyinger** [comment]
I'm struggling to produce an error state in Gutenberg. I turned the throttling to offline in the network tab and although requests were failing, there were no indicators in the UI itself.

something we should just send to UX? or ignore cus Gutenberg ignores as far as I can tell?

**Comment by BrittanyIRL** [comment]
> I'm struggling to produce an error state in Gutenberg. I turned the throttling to offline in the network tab and although requests were failing, there were no indicators in the UI itself.
> 
> something we should just send to UX? or ignore cus Gutenberg ignores as far as I can tell?

🤔  Yeah, let's send it to UX. It may very well be that we don't need to worry about it but I'd rather be sure. Feels a bit odd to not let a user know if something is going wrong.

**Comment by samwhale** [comment]
Guttenberg swallows the errors. We can mimic that in ours for now
 https://github.com/WordPress/gutenberg/blob/b78b615b59ded086d947140dcfb65806f610001c/packages/data/src/components/use-select/index.js#L144-L156
