### ISSUE TITLE
Taxonomy: Predictive suggestions for tags

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9034]
## Feature Description

When typing in new tags, if there are tags available already that fit what has currently been typed so far, offer the options that fit below the input. 

Using the keyboard arrows should allow you to navigate the list of matching strings but the input should stay active so you can choose to keep typing instead. 

![Kapture 2021-09-14 at 12 32 12](https://user-images.githubusercontent.com/10720454/133322088-10aed04a-e043-4067-affb-6d566d995bbb.gif)

**Comment by swissspidy** [comment]
This is super important for contributors who cannot create new tags but only assign existing ones. Without an autocomplete you have no idea if the tag assignment works or not.

**Comment by BrittanyIRL** [comment]
> This is super important for contributors who cannot create new tags but only assign existing ones. Without an autocomplete you have no idea if the tag assignment works or not.

Yup, realized that after finding out that tags were only blocked from create not also updating to use existing tags with the capabilities from the story. Part of reason for pushing back the release.
