### ISSUE TITLE
Taxonomy: Register new taxonomies

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9038]
## Feature Description

So far we've been developing the new taxonomy feature with this example plugin I put together: https://gist.github.com/swissspidy/62d54f3f48a81b88a0f2b07fd32f844e

But we actually want to have some built-in taxonomies in the Web Stories editor:

* `web-story-tag` (flat)
* `web-story-category` (hierarchical)

As for labels, they should just be called "Tags", and "Categories", respectively. So not "Story Tags" or anything.

**Note:** Initially, these taxonomies should not be exposed on the frontend, e.g. through archives 

Possible args:

* `labels`: same as defaults, but with our text domain
* `public`: `false`
or anything.
* `hierarchical`: `true` for `web-story-category`, `false` for `web-story-tag`
* `show_ui`: `true`
* `show_admin_column`: `true`
* `capabilities`: custom capabilities like for our post type?
* `rewrite`: `false`
* `show_in_rest`: `true`
* `rest_controller_class`: we might want a custom controller here

**Comment by spacedmonkey** [comment]
Name of this ticket is really unclear to me. Do we built in categories and tags to registered to our post type ( like the old editor did) or do we want new taxonomies named tags and categories ( prefixed ) to be added. 

If we are register core categories and tags to our CPT, then will need something like [this](https://github.com/spacedmonkey/built-in-taxos-cpt).

**Comment by swissspidy** [comment]
> new taxonomies named tags and categories ( prefixed ) to be added.

This. The new taxonomy slugs are `web-story-tag` and `web-story-category`.

**Comment by spacedmonkey** [comment]
> This. The new taxonomy slugs are web-story-tag and web-story-category.

The name of the ticket should be changed then. Maybe `Taxonomy: Register new taxonomies`

**Comment by spacedmonkey** [comment]
I think we should create a `taxonomies` namespace for this new taxonomies. I think we could add a new `taxonomy_base` class. This class would do the following. 

- Extend service base
- Has a method called register_taxonomy 
- Store tax slug in `TAXONOMY_SLUG` const
- Store tax args in `TAXONOMY_ARGS` const
- Implement `PluginDeactivationAware`, `SiteInitializationAware` to ensure that rewrite rules are flushed. [See](https://github.com/google/web-stories-wp/blob/c3dbff3bb3c3b2f7bb288c2a6c9c2c0b9406ef05/includes/Story_Post_Type.php#L164-L186).

The existing `Media_Source_Taxonomy` class, could easily be refactor to use this new base class. 

Register a new taxonomy could look like this.

```
/**
 * Class Media_Source_Taxonomy
 *
 * @package Google\Web_Stories\Media
 */
class Media_Source_Taxonomy extends Taxonomy_Base {
	/**
	 * Key for media post type.
	 *
	 * @var string
	 */
	const TAXONOMY_SLUG = 'web_story_media_source';
        
        /**
	 * Key for media post type.
	 *
	 * @var string
	 */
	const TAXONOMY_ARGS = [
				'label'        => __( 'Source', 'web-stories' ),
				'public'       => false,
				'rewrite'      => false,
				'hierarchical' => false,
				'show_in_rest' => true,
			];
}

```

**Comment by spacedmonkey** [comment]
Will these taxonomies ever be used in the dashboard?

**Comment by swissspidy** [comment]
Any thoughts on custom REST controllers and custom capabilities?

> Will these taxonomies ever be used in the dashboard?

Perhaps in the future, yes.

**Comment by spacedmonkey** [comment]
I am happy to create a custom capability.
