### ISSUE TITLE
Dashboard: display stories with "Pending Review" status

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9044]
## Feature Description

As mentioned at https://github.com/google/web-stories-wp/pull/8976#issuecomment-919935807, the Dashboard doesn't currently display stories with "Pending Review" status at all.

![Screen Shot 2021-09-14 at 9 38 59 AM](https://user-images.githubusercontent.com/10720454/133298639-727895a7-069b-460d-9c03-59b4ed639562.png)
![Screen Shot 2021-09-14 at 9 38 47 AM](https://user-images.githubusercontent.com/10720454/133298641-cba65a63-47e6-437b-b98c-a897d45515cc.png)

The `pending` status is actually missing from the list of retrieved statuses:

https://github.com/google/web-stories-wp/blob/c3dbff3bb3c3b2f7bb288c2a6c9c2c0b9406ef05/packages/dashboard/src/constants/stories.js#L104-L139

Adding support for this status would be as easy as amending that list and updating the counts on the server side as well:

https://github.com/google/web-stories-wp/blob/c3dbff3bb3c3b2f7bb288c2a6c9c2c0b9406ef05/includes/REST_API/Stories_Controller.php#L376-L392

This would need to be done after #8976 is merged.

**Comment by swissspidy** [comment]
FYI @BrittanyIRL

**Comment by csossi** [comment]
Set a story as "pending review":
![image](https://user-images.githubusercontent.com/16945664/135861460-1d660be6-a341-4067-a1fe-7927a24778c2.png)

Not seeing a "pending" stastus option in Dashboard:
![image](https://user-images.githubusercontent.com/16945664/135861722-95b582c6-3d7f-4c32-9c4a-181d84862f17.png)

**Comment by swissspidy** [comment]
@csossi please test #9235 again on the QA environment. I definitely **do** see pending stories there:

![Screenshot 2021-10-04 at 16 31 21](https://user-images.githubusercontent.com/841956/135870059-6357c7d2-ba9c-4d8b-9f33-e9ba9cacbd12.png)

**Comment by csossi** [comment]
Verified in QA
