### ISSUE TITLE
Add initial `<amp-story-auto-analytics>` migration implementation

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9045]
## Feature Description

While UX on #7739 is being finalized, we can already implement the actual migration under the hood.

### Implementation Brief

* Add new feature flag for `enableAutoAnalyticsMigration` (or something like that)
* Add a new database migration that sets a flag in the database for everyone with a non-empty tracking ID setting (`web_stories_ga_tracking_id`). We can call the flag `web_stories_using_legacy_analytics` or so. If no tracking ID is set, `web_stories_using_legacy_analytics` will be `false`.
* This new flag should be available via the RES API
* In the editor, in addition to all other settings, retrieve the value of `web_stories_using_legacy_analytics`
* If `web_stories_using_legacy_analytics` is `true`, display explanatory text (exact copy TBD, see #7739 for example) and a "Migrate" button below.
* Clicking on "Migrate" should set `web_stories_using_legacy_analytics` to `false` in the database and ideally show some success snackbar message
* In `Analytics.php`, check value of `web_stories_using_legacy_analytics` and either print a `amp-story-auto-analytics` tag or the regular on.  
  ```html
  <amp-story-auto-analytics gtag-id="UA-123456789-0"></amp-story-auto-analytics>
  ```

**Comment by swissspidy** [comment]
@spacedmonkey PTAL at the above brief when you get a chance and let me know if anything is unclear.

**Comment by csossi** [comment]
Verified in QA
