### ISSUE TITLE
Story Auto Analytics: Update Link

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9054]
## Feature Description

Once we have documentation, we need to update the link on the settings page accordingly.

**Comment by swissspidy** [comment]
The new link will be https://wp.stories.google/docs/seo/

**Comment by spacedmonkey** [comment]
Can I confirm, that url, it currently 404s. I am guessing part of that is the url should be https://wp.stories.google/docs/seo/

**Comment by swissspidy** [comment]
Whoops, yeah the URL is of course https://wp.stories.google/docs/seo/. The 404 is expected right now until #9215 is merged.
