### ISSUE TITLE
Fetch all hierarchical taxonomies, not just first 100

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#9056]
#9048 Adds the hierarchical input to the editor. Hierarchical taxonomies are loaded when the editor is mounted - but only the first 100 are loaded.

Gutenberg grabs all the pages, 100 items at time when there's more than 1 page. We actually have a little util for this from many moons ago:

https://github.com/google/web-stories-wp/blob/main/packages/dashboard/src/app/api/fetchAllFromPages.js

_Originally posted by @BrittanyIRL in https://github.com/google/web-stories-wp/pull/9048#discussion_r711174473_

**Comment by swissspidy** [comment]
🧐 I don‘t think you need this util.

Pass `-1` as the number to fetch all pages, one by one, like Gutenberg does.

This util could probably be deleted

**Comment by BrittanyIRL** [comment]
Well, today i learned! 

cool, this util isn't actually in use anywhere anymore, it was left over from something in the dashboard and kept it around incase we need it. 

let's keep this ticket to implement that (and gut the util) just to track it. dropping points though.

**Comment by BrookeGraham** [comment]
I was gonna remove the util, but it is used `useCategoriesApi` and `useTagsApi`

**Comment by BrittanyIRL** [comment]
> I was gonna remove the util, but it is used `useCategoriesApi` and `useTagsApi`

good note, we can clean that out separately, those are actually not in use and probably irrelevant now that these are separated so if we were to ever bring them back these would need updating anyways.

**Comment by swissspidy** [comment]
useTagsApi is not used anywhere. useCategoriesApi probably neither

**Comment by BrittanyIRL** [comment]
> useTagsApi is not used anywhere. useCategoriesApi probably neither

It's not. Here's the PR to clean it out: https://github.com/google/web-stories-wp/pull/9065 - I was planning on addressing it this coming week but had 30 minutes this AM so went ahead with it. The reason for the separation is that Brooke's PR is getting added to Samuel's for categories in the editor, which is already a big PR. It seemed unnecessary to add unrelated changes to that PR in addition. (Plus, Brooke's new on the project and still learning the codebase, I don't blame her for wanting to make sure it wasn't in play somewhere that's hard to find.) Anyways, that's just context. Happy to remove that now that it's not even a valuable reference material for anything else.

**Comment by swissspidy** [comment]
As mentioned on the other PR, use this to quickly generate lots of test data to tinker with:

```bash
wp term generate <taxonomyslug> --count=1000
```
