### ISSUE TITLE
Taxonomies: Add History Support

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#9073]
## Feature Description

A user should be able to undo/redo the addition and removal of taxonomy terms from a story. This will match the behavior of the Gutenberg editor.

After implementation: enable the `should not have new history changes when switching tabs without changes` test.

**Comment by BrittanyIRL** [comment]
@littlemilkstudio @samwhale thanks for making this ticket, can you add a point estimate to it?

**Comment by swissspidy** [comment]
According to https://github.com/google/web-stories-wp/pull/9048#discussion_r711614156, this ticket should fix the issue where opening the blank editor already creates a history entry. Is that correct? Because it's quite the annoying regression, so should be fixed swiftly.

**Comment by maxyinger** [comment]
@swissspidy ahh, I'll do a quick fix for that issue that you posted above, then work on proper history integration after (which might be pretty tough with the existing setup)

**Followup**
this PR should fix that regression while we figure out integrating history into taxonomies in the meantime
https://github.com/google/web-stories-wp/pull/9109
