### ISSUE TITLE
Static Page Templates

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9089]
## Context 

Some [discovery on the performance gains](https://github.com/google/web-stories-wp/issues/8826) of this update were done earlier, as well as loosely what to expect in this endeavor. 

There's a bit of work to do in the background first in order to swap out static images for the default page templates (and then from there, use the newly established structure from default page templates to look into custom page templates).

## General overview 
We have screenshots of each template page now, those can be used in the page templates section of the editor to cut down on previews rendered and reduce the editor's load time significantly. 

To get there we need to do a few things in the background first:

You can also filter default page templates by template page type. Right now this is based on the raw template json by page (`pages > pageTemplateType`) - One possible solution to this is mapping this when we export the templates from the templates package so we can reference page numbers to page types.

Once all of the background work on this is done, swapping out the page-templates-as-stories for page templates-as-screenshots should be done together.  This will include: removing the virtualized list, making sure page templates are memoized so we don't load excessively, and making sure that filtering still works - essentially, ensuring no regression. Right now the custom and default page templates share some components, it would probably make sense at this point to make a new page templates list component for static page templates, so that this work doesn't impact custom page templates at all but could be used for those as well once looking into that.  From here, we can explore using html-to-image to swap out custom page templates.

**Comment by swissspidy** [comment]
AFAIK we've ditched the "page layouts" terminology in favor of "page templates" throughout the code base & GitHub

**Comment by BrittanyIRL** [comment]
There's some of both, i'll update the rest of the epic where needed.
