### ISSUE TITLE
Update template screenshot script for grids (and generate screenshots)

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9090]
## Description 
~The script in templates package to get screenshots of each template page using the grid placeholder will need to be updated to also generate screenshots using the placeholder grid. The images are currently getting swapped out in the editor - there's a util in api called `replacePageImagesWithPlaceholders` - we'll need to store a `webp` and `png` version of each of these screenshots in the static branch in the same pattern as the other template screenshots. For all the templates that already have screenshots, just adding the placeholder version to the static branch is fine. The script itself should just grab both at once though so it's easier moving forward.~

### Updated 
Turns out we want to [ditch the placeholder grid version of the page layouts ](https://github.com/google/web-stories-wp/issues/9093#issuecomment-926197776)all together! 

Let's just use this ticket to update the screenshots to grab webp at the same time as png to avoid having to export them manually per Pascal's comment below. 
 

## Acceptance Criteria

1. template screenshot script updated to grab webp and png screenshots not just png.

**Comment by swissspidy** [comment]
Related to this:

Puppeteer v10.4.0 now supports saving screenshots directly as webp, so we can create the two versions in one go.
