### ISSUE TITLE
Default Page Templates: Swap for screenshots

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9093]
## Description

This will include: removing the virtualized list, making sure page templates are memoized so we don't load excessively, and making sure that filtering and toggling images are still working - essentially, ensuring no regression. Right now the custom and default page templates share some components, it would probably make sense at this point to make a new page templates list component for static page templates, so that this work doesn't impact custom page templates at all but could be used for those as well once looking into that. 

## To Do 
- Do we want to keep the placeholder grid around? (@choumx following up on this) 
- Do we want to swap the toggle so that images are there by default? (@choumx following up on this)

Reference: #8826

## Acceptance Criteria

- Using screenshots for default page templates instead of previewing stories for each page. 
- Filtering by page template type still works. 
- Toggling between templates with images and with the placeholder has been removed
- Performance metrics to see improvements. 
- Passing tests
- Added aXe integration test for accessibility -- will be done in #8736

**Comment by dreamofabear** [comment]
> Do we want to keep the placeholder grid around?

No.

> Do we want to swap the toggle so that images are there by default?

Let's remove the toggle and default to images on.

**Comment by BrittanyIRL** [comment]
@csossi if you could prioritize this one it would be really helpful! it's blocking other work. 

What to QA: 

- Make sure default and saved page templates work same as before.
- Default page templates should still keyboard navigable
- Default templates should now appear as images

**Comment by csossi** [comment]
Verified in QA
