### ISSUE TITLE
Dashboard: Remove incorrect warning dialog when removing publisher logos

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9096]
## Feature Description

When removing a publisher logo from the Settings screen in the dashboard, you are presented with the following warning:

![Dialog saying "The logo will be removed from any stories that currently use it as their publisher logo."](https://user-images.githubusercontent.com/841956/134181265-7ef3f3f5-f888-41ee-a68a-7add07c81b91.png)

This dialog is totally incorrect though.

Removing a publisher logo only removes it from the list of publisher logos, but does not remove the actual attachment in the media library. So it does not change any existing stories at all.

For this reason, I suggest completely removing this dialog.

**Comment by BrittanyIRL** [comment]
Has it always been wrong 🥴 ? I feel like when this first started it was an accurate warning. Regardless of my memory, yeah let's remove it.

**Comment by swissspidy** [comment]
I'm not 100% sure how things were originally, but I think the underlying attachment has never been deleted when removing the publisher logo.

And when creating a story we currently store the publisher logo (attachment) ID, so as long as that one is not deleted by the user in the media library, there is no issue.

The publisher logo section is basically just a selection of attachments, removing an item from the selection has no impact on existing stories or new ones, other than the selection being different.

**Comment by BrittanyIRL** [comment]
@BrookeGraham if you have time today or tomorrow after [9101](https://github.com/google/web-stories-wp/pull/9101) is merged can you knock this out?

**Comment by dreamofabear** [comment]
IMO we should keep the dialog and update the copy to inform the user that stories using deleted logos *won't* have those logos removed. I can see some users expecting "deletion propagation" to be the default behavior.

Aside: I'm curious if there's a use case to changing publisher logos across multiple stories. Probably niche but we can keep an eye out.

**Comment by BrittanyIRL** [comment]
> IMO we should keep the dialog and update the copy to inform the user that stories using deleted logos won't have those logos removed.

this feels like something that could just as easily get added to the copy so that users don't have to acknowledge that it won't remove the logo from stories every time they perform the action. 

![Screen Shot 2021-09-24 at 12 11 39 PM](https://user-images.githubusercontent.com/10720454/134728074-2c6656bf-94e1-49f7-bebc-588495662923.png)

**Comment by csossi** [comment]
Verified in QA

Note: the dialog is no longer appearing, but the new content mentioned above ("Removing a publisher logo..." isn't there. Since it's note in QA instructions for 9145, assuming it's not in scope)

**Comment by swissspidy** [comment]
> but the new content mentioned above ("Removing a publisher logo..." isn't there. Since it's note in QA instructions for 9145, assuming it's not in scope)

That is just a mockup saying what we could do in the future

**Comment by BrittanyIRL** [comment]
> > IMO we should keep the dialog and update the copy to inform the user that stories using deleted logos won't have those logos removed.
> 
> this feels like something that could just as easily get added to the copy so that users don't have to acknowledge that it won't remove the logo from stories every time they perform the action.
> 
> ![Screen Shot 2021-09-24 at 12 11 39 PM](https://user-images.githubusercontent.com/10720454/134728074-2c6656bf-94e1-49f7-bebc-588495662923.png)

@choumx is this something you want us to do? Since this issue is closed the comment's gonna get lost to the void here soon. I will make a ticket if this is copy update that you want.

**Comment by dreamofabear** [comment]
Sorry for the late response! Yes, please create a ticket to update this copy. 🙏
