### ISSUE TITLE
Archive: Redirect default archive page to custom one

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9100]
## Feature Description

When users choose a custom page as the Web Stories archive page, we probably want to add a redirect from `/web-stories/` to the custom archive page for UX reasons.
Probably also from `/web-stories/` to `/new/custom/path/feed/`

## Alternatives Considered

Just adding an FYI note to the settings screen that users should set up redirects themselves

**Comment by csossi** [comment]
Verified in QA
