### ISSUE TITLE
Display frames in the trim rail behind the handles

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#9104]
## Feature Description

Show actual frames from the video in the trim rail.

Things to consider:

* Video dimensions
* Mask dimensions
* Video length
* Number of frames to display

## Additional Context

Current frame-less design:
![Screen Shot 2021-09-22 at 10 21 05](https://user-images.githubusercontent.com/637548/134361729-4985270b-d1d1-4d6e-844a-67edc30f5dcd.png)

Goal design:
![Screen Shot 2021-09-22 at 10 22 02](https://user-images.githubusercontent.com/637548/134361756-de0348eb-9858-407b-854d-11ebb5c13421.png)

**Comment by csossi** [comment]
Verified in QA
