### ISSUE TITLE
Implement actual trim

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#9105]
## Feature Description

Implement the connection between the trim button in the trim mode UI implemented in #8890 with the underlying trim functionality created by Infra in #8891.

If necessary, show a loader or relevant placeholder icon while the transformation occurs.

**Comment by csossi** [comment]
Problem in PC/FFox. I moved handles to start and end points for the video and selected "Trim" while in edit mode. I was taken out of edit mode, and trimming didn't occur (no change in display to "Trimming" with spinner and quick menu "trim" remained active)

**Comment by miina** [comment]
@spacedmonkey Looks like the trimming is not working in FF, getting these errors in console and it never finishes:
<img width="1295" alt="Screenshot 2021-09-28 at 17 49 39" src="https://user-images.githubusercontent.com/3294597/135111264-c3d59f76-bbfb-4357-b03c-1b3031af8c9d.png">

Did you happen to try it out in FF as well when implementing the trimming part? Did it work then?

**Comment by barklund** [comment]
> @spacedmonkey Looks like the trimming is not working in FF, getting these errors in console and it never finishes:
> <img alt="Screenshot 2021-09-28 at 17 49 39" width="1295" src="https://user-images.githubusercontent.com/3294597/135111264-c3d59f76-bbfb-4357-b03c-1b3031af8c9d.png">
> 
> Did you happen to try it out in FF as well when implementing the trimming part? Did it work then?

I'll file as a new bug and we can merge this for bugbash (with the known caveat of Firefox not working).

**Comment by swissspidy** [comment]
@barklund @miina I think this only happens if you have dev tools open
