### ISSUE TITLE
Pause video while dragging trim handles

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#9108]
## Feature Description

Pause the video while dragging the trim handles at the current frame of the dragged handle, thus scrubbing it backward and forward as the user drags the offset. Once the user releases the handle, start looping the video again.

Do the same things for keyboard input, but with a slight delay before re-starting playing the video (so if the user makes multiple keypresses in a row, keep the video paused at that end, but updated the frame to the current state of the offset, and only once the user has stopped pressing keys for a while (200ms?), restart looping the video.

Of course, don't start the video again if it was paused from the start - but do still move the video play head to the offset that is being updated.

**Comment by csossi** [comment]
Verified in QA
