### ISSUE TITLE
Taxonomy: Tags should add on blur

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9134]
Right now in the tag input if you type in a new value and hit `tab` instead of `enter` or the spacebar it doesn't save the new tag. It should. The initial PRs for taxonomy were doing a lot at once, this just slipped through. Fixing ahead of release.

![Kapture 2021-09-22 at 12.26.14.gif](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/70477e0e-01f0-40df-ae41-47034db0066d)

**Comment by BrookeGraham** [comment]
Work for taxonomy history ticket [9073](https://github.com/google/web-stories-wp/issues/9073) will completely redo the taxonomy provider. Hold off on this ticket until that work is complete. The new work being done may also solve this issue.
