### ISSUE TITLE
Layers Panel: Add layer count badge to title area

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9136]
## Description

Sometimes not all layers are visible in the layers panel and it's not super obvious that there are more if you scroll. Add in a badge that displays the count of all the layers in the title area of the layers panel. 

Figma: https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=9954%3A422177 

Design as of Oct 4, 2021:
<img width="376" alt="Screen Shot 2021-10-04 at 10 50 38 AM" src="https://user-images.githubusercontent.com/10720454/135899702-c4fad837-7e5b-430a-b69b-34adddf9aa83.png">

## To Do
- [x] - Final UX from design team

## Acceptance Criteria 

- badge displays with layers count, badge stays current even when panel is collapsed. 
- updated tests

**Comment by csossi** [comment]
Verified in QA
