### ISSUE TITLE
Layers Panel: Duplicate layer from panel

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9137]
## Description

Add a button to each layer in the layers panel that allows the layer to be duplicated from the layers panel. Behavior should mimic duplicating a layer from the right click menu.

https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=9946%3A422172

Designs as of Oct 4, 2021 (middle button)
<img width="530" alt="Screen Shot 2021-10-04 at 11 24 50 AM" src="https://user-images.githubusercontent.com/10720454/135904175-f6ff77cd-4a1f-45a1-a120-960df3af2bdf.png">

## Acceptance Criteria 

- new button on each layer panel (besides background) that allows the layer to be duplicated, should also work with keyboard
- updated tests

**Comment by csossi** [comment]
Verified in QA
