### ISSUE TITLE
Layers panel: Delete layer from panel

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9138]
## Description

Add a button to each layer in the layers panel that allows the layer to be deleted from the layers panel. Behavior should mimic using the delete key on a layer.

https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=9946%3A422172
Designs as of Oct 4, 2021 (left button)
<img width="530" alt="Screen Shot 2021-10-04 at 11 24 50 AM" src="https://user-images.githubusercontent.com/10720454/135904548-aa0fbcb9-be29-4620-8118-b9f41a525106.png">

## To Do

- [x] Final UX from design team

## Acceptance Criteria 

- new button on each layer panel (besides background) that allows the layer to be deleted, should also work with keyboard
- updated tests

**Comment by csossi** [comment]
Verified in QA
