### ISSUE TITLE
Layers Panel: Context menus

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9139]
## Description

Harness the right click context menus that are available on the canvas by type and show them in the layers panel when a layer is right clicked on. 

Figma: https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=9954%3A422464
Designs as of Oct 4, 2021
<img width="290" alt="Screen Shot 2021-10-04 at 11 36 45 AM" src="https://user-images.githubusercontent.com/10720454/135905812-dc127690-64be-4b00-a784-cbb760028183.png">

## Acceptance Criteria 

- right clicking on layers in layer panel should show context menu for that layer type/layer 
- updated tests

**Comment by csossi** [comment]
Verified in QA
