### ISSUE TITLE
Layers Panel: Layer Action Scrim Container

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9140]
## Description

Create a container for the layer actions that appears on hover. This container should have a scrim to the left of it that overlays the title string when it's visible.

~Instead of an ellipsis on long layer titles, string should fade out (this will work better with the new delete, duplicate buttons that are getting introduced). The gradient would appear over text only in the hover state/when icons are on the panel—if the text is too long for the panel, it will still trail off with an ellipsis.~

Figma: https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=9954%3A422464
Designs as of Oct 4, 2021

<img width="614" alt="Screen Shot 2021-10-04 at 11 38 09 AM" src="https://user-images.githubusercontent.com/10720454/135906007-dd57f76f-55c1-438b-90bb-03f099be1e64.png">
<img width="439" alt="Screen Shot 2021-10-04 at 11 38 21 AM" src="https://user-images.githubusercontent.com/10720454/135906008-019964a7-0148-4d03-a0b9-fd4b88bbe91f.png">

## To Do
- [x] - Final UX from design team

## Acceptance Criteria 

- visual update as defined in figma

**Comment by maxyinger** [comment]
Renamed from `Layers Panel: Fade long strings` to `Layers Panel: Layer Action Scrim Container`
