### ISSUE TITLE
Media: Add initial `<amp-story-captions>` support

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9154]
## Feature Description

Add initial video captions rendering using `<amp-story-captions>`, behind a feature flag.

**Comment by csossi** [comment]
Captions not positioned properly for videos (cat video and wall-e video) on Preview (image is Mac/Chrome):
![image](https://user-images.githubusercontent.com/16945664/135864197-6b0650a3-d8bf-47db-9ad7-056b7b288e34.png)

**Comment by swissspidy** [comment]
@csossi Interesting scenario 👀  So you have 2 videos on the same page with the same captions?

What would be the proper placement in such a case in your eyes? We obviously can't position the two captions at the same position, otherwise you couldn't read them.

So positioning them on top of each other seems like working as intended.
