### ISSUE TITLE
Show tooltip while trimming / muting video

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#9159]
## Feature Description

While transcoding a video, if a user hovers over the element in the media library, they see a tooltip. See screenshot.

<img width="229" alt="Screenshot 2021-09-27 at 14 14 18" src="https://user-images.githubusercontent.com/237508/134921088-669bb663-e541-459e-894e-352a5afa0294.png">

A similar message should be shown, while a video is being trimmed or muted, as these operations can take some time.  

Related: https://github.com/google/web-stories-wp/issues/9158

**Comment by swissspidy** [comment]
For some historical context here for anyone chiming in:

Originally we added this tooltip because video optimization can take a long time. So this gives users some ideas about what's going on with their media item.

To be determined whether

a) this extra tooltip is still warranted
b) we should just remove this tooltip
c) we should add tooltips for other states as well

**Comment by gajasinski** [comment]
A few follow up questions for clarificaton:

- Can the user do anything to the video while it is optimizing?
- It looks like the tool tip is displayed below the video that is optimizing, correct?
- Does it matter if we use the same wording on the tool tip for trimming, muting, or transcoding?
@aaskedall cc

**Comment by swissspidy** [comment]
> * Can the user do anything to the video while it is optimizing?

Yeah

They just can't save/publish the story while uploads are in progress

> * It looks like the tool tip is displayed below the video that is optimizing, correct?

Yeah

> * Does it matter if we use the same wording on the tool tip for trimming, muting, or transcoding?

I'd change the wording to something more generic in this case, like "Video is being processed". Alternatively, a specific message per state.

**Comment by gajasinski** [comment]
Roger. Thanks for clarifying @swissspidy

**Comment by spacedmonkey** [comment]
It also worth noting, that when a video transcode starts, a snackbar message shows as well. 

![Screenshot 2021-09-27 at 15 51 05](https://user-images.githubusercontent.com/237508/134932651-0690e3c5-95bd-42ee-a955-5f2a9b356bf0.png)

I am wondering if the messaging should be changed here as well.

**Comment by spacedmonkey** [comment]
Was it decided, what the messaging should be. Did we decide that we wanted a generic message for all videos that are being processed?

**Comment by swissspidy** [comment]
Let's try a generic "Video is being processed" message.

Might be easier to get that state after #9577

**Comment by csossi** [comment]
Verified in QA
