### ISSUE TITLE
Add mute option to quick action menu

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#9160]
## Feature Description

When a video element is selected, show an option to mute video. There is already an option to trim the video, but not one to mute it. See screenshot. 

![Screenshot 2021-09-27 at 15 09 00](https://user-images.githubusercontent.com/237508/134925423-405ade3d-3d14-4682-a8ca-5faeb4448e50.png)

**Comment by swissspidy** [comment]
Not sure if muting videos is something that is needed frequently enough to warrant adding another option here.

Deferring to @gajasinski @aaskedall

**Comment by spacedmonkey** [comment]
> Not sure if muting videos is something that is needed frequently enough to warrant adding another option here.

Then the same argument can be made for captions and trimming then.

**Comment by swissspidy** [comment]
Sure.

I just think that muting videos is something one is less likely to do. But almost every video needs captions. And trimming also seems like something you'd need more often, perhaps even multiple times on the same video.

**Comment by agingoldseco** [comment]
I find having a video constantly talking while I'm trying to edit kind of annoying too. Right now, the quick action menu grays out when you trim a video—if we allow people to mute a video while working with it, that should be available during trimming too. Could we add a "mute while editing" (please suggest better wording) button to the quick action menu that becomes the entire (not grayed out) quick action menu when you click "Trim"? If that's unclear, I can mock it up.

One other issue—adding one more button to it would cover up the Right arrow on smaller screens. I'm working on some workspace changes that would fix that, but as it stands now it will be awkward.

<img width="274" alt="Screen Shot 2021-10-13 at 3 01 40 PM" src="https://user-images.githubusercontent.com/90645922/137197063-ab760e2f-20a9-48dd-bc67-8b26404685db.png">

**Comment by swissspidy** [comment]
@agingoldseco I think what you're describing is different from what this ticket is about.

This ticket proposes adding a quick action menu item for completely and _permanently_ removing any audio from the video (vs. going to the design panel to do that today), whereas you are talking about _temporarily_ muting the video while editing.

We actually un-muted the video during trimming recently in #9182.

We had this looong discussion about this on Slack before implementing that: https://xwp.slack.com/archives/C01ESBB8ZN1/p1632924765076100

I recommend reading that for context and then let's create a ticket for your proposal.
