### ISSUE TITLE
Safari page previews: some shapes display incorrectly

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9173]
## Bug Description
Some shapes in Safari seem to display incorrectly, for example Pentagon, Heart. 

## Steps to Reproduce
In Safari:
1. Add Pentagon to the Page
2. See the Page preview

## Screenshots
<img width="162" alt="Screenshot 2021-09-28 at 11 28 56" src="https://user-images.githubusercontent.com/3294597/135052485-b43989ae-0832-4049-8bb1-05442a5e4b17.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Closing as per discussion on #9933
