### ISSUE TITLE
Add Template Colors as section in color pickers

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9177]
_called out by @barklund and @merapi during bugbash 1.12_

This is a missed scope of adding template colors to 'saved colors' in the editor (#7449). 

![Screen Shot 2021-09-28 at 9.45.32 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/e9d286b2-de57-4e55-aad6-0566967a926d) 

^^ If there's template colors on editor load then there should be another section below 'Saved colors' for 'Template colors'. This should be the case in the color picker for all color pickers regardless of element type.

**Comment by samwhale** [comment]
Wondering if we should make a ticket to add the same section to the `Saved Colors` panel?
<img src="https://user-images.githubusercontent.com/22185279/136093724-5df69ef9-e36a-46b6-8351-5d5029270283.png" height="300px" />

**Comment by csossi** [comment]
Verified in QA
