### ISSUE TITLE
Video Trimming: Trim buttons should be always visible and cancel should exit trim mode

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9178]
## Bug Description
Originally reported by @aaskedall 

After using the trim tool and not trimming, hitting cancel does not exit the trim tool. 

## Expected Behaviour

Trim buttons should be always visible and cancel should exit trim mode. 
The trim is inactive until the handles are moved. But cancel should do both and be there from the start.  https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=9983%3A423093

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Entered trim mode and cancel isn't appearing:
![image](https://user-images.githubusercontent.com/16945664/135350312-6cb4e253-0a00-4354-9a06-2c41950dba31.png)


Note: Cancel WILL appear as soon as I move either handle, but clicking it does not exit trim mode - acts as a reset instead

**Comment by barklund** [comment]
> Entered trim mode and cancel isn't appearing:

Somehow the changes didn't appear on the QA site, but that should be fixed now. Please try again.

**Comment by csossi** [comment]
Verified in QA

Note: The "Trim" button in the design panel remains active and although it says "Trim", it actually behaves as a toggle and has the same effect as "cancel"
