### ISSUE TITLE
Video Trimming: Adjust trim mode background color

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9179]
## Bug Description

There is a vertical grey bar next to the trimming tools

![image6](https://user-images.githubusercontent.com/58738530/135143432-c7c83bae-ec1e-4e49-87ad-fc92b001eed5.png)

## Expected Behaviour

same background color as the rest of the editor background 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Verified in QA
