### ISSUE TITLE
Video Trimming: Add proper focus management in trim mode 

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9180]
## Bug Description

Dragging a handle (or moving it with the keyboard) and then hitting cancel will let the user focus the buttons underneath the slider

Also, Tabbing between the handles and the buttons seems to be reversed in RTL. The tabbing order goes from Cancel (on right) -> far left handle -> far right handle -> Trim (on left)

Also, While the trim bar is visible, I was able to tab to undo that is under the bar. I was not able to tab to the handles for the trim. 
![image16](https://user-images.githubusercontent.com/58738530/135161235-67377ee0-df07-485e-9013-4f47afcc4ff8.png)

## Expected Behaviour

Both initial focus to first handle as well as focus trapping within the trim mode

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Focus is on "Cancel" when user first enters trim mode, but it's not visible to user/highlighted properly:
https://share.getcloudapp.com/NQuYyY96

**Comment by barklund** [comment]
> Focus is on "Cancel" when user first enters trim mode, but it's not visible to user/highlighted properly

We only show focus outlines for users using a keyboard (as the last thing they did before this element received focus).

So if you select a video on stage, navigate to the trim button in the design panel using a keyboard and press the trim button there, you will see the focus rectangle display on the cancel button once in trim mode. But if you enter trim mode using the mouse, you will not see a focus rectangle.

So this is as designed.

**Comment by csossi** [comment]
understood - thanks for clarifying @barklund

**Comment by csossi** [comment]
Verified in QA
