### ISSUE TITLE
Video Trimming: Mask video to canvas when in trim mode

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9181]
## Bug Description
originally reported by @BrookeGraham 

if your video is large the trim functionality is hidden. Regardless of the media element size, the trim view should probably give the video consistent element sizing just while in trim. 

![image7](https://user-images.githubusercontent.com/58738530/135145728-9aec21d9-5f49-4a54-8066-c256c3ff8033.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Verified in QA
