### ISSUE TITLE
Video Trimming: Audio should not be muted while trimming

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9182]
## Bug Description

The audio should play back automatically during a trim action, as the audio can provide clues as to the user’s desired IN/OUTs.

There will not be an option to mute the audio while trimming, as this might lead the user to think that the video output is also muted.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by bmattb** [comment]
@aaskedall need an icon for the mute / unmute icon on this please

EDIT: And direction as to where to place it!

**Comment by swissspidy** [comment]
We already have `muted.svg` in the design system. The rest can be picked from Material Icons: https://fonts.google.com/icons?icon.query=volume

**Comment by csossi** [comment]
Verified in QA
