### ISSUE TITLE
Video Trimming: Remove panel highlight when trimming from quick actions

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9183]
## Bug Description
originally reported by @samwhale 
The `Video Settings` panel should not highlight when the quick action is clicked. The quick action could highlight the slider if we wanted any highlighting to happen?

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Verified in QA
