### ISSUE TITLE
Video Trimming: Update context menu copy to include video

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9185]
## Bug Description

Since we will be adding video trimming to the right click context menu (see https://github.com/google/web-stories-wp/issues/9184), we will need to update the verbiage of that menu to be inclusive of video assets (ie: change Image to <something else>) 

## Expected Behaviour

Right click context menu copy is updated to include video assets as well as image, as it currently only references "image(s)"

## Screenshots

![image9](https://user-images.githubusercontent.com/58738530/135149205-32369459-6258-4966-95fc-a2518b76bfb6.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrittanyIRL** [comment]
happy for pea pod to take this but those menus should be easy to update if someone with context of video trimming wants to take this.

**Comment by csossi** [comment]
Verified in QA
