### ISSUE TITLE
Color Tooltips get stuck on screen in Safari

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9188]
## Bug Description

On Safari, the color tooltips ("Gradients not allowed for text") sometimes get stuck on the screen. Seems to happen on mouse-out with high speed.

![image17](https://user-images.githubusercontent.com/58738530/135152882-c6aba1cb-0fad-4cd4-b5af-9307e84aa656.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrittanyIRL** [comment]
@miina objections to this getting tackled by peapod? Feel like colors are a prometheus thing mostly but Matt assigned this to me so I wanted to verify with you.

**Comment by miina** [comment]
@BrittanyIRL It's also related to tooltips so no objections (if that's ok with you).

**Comment by BrittanyIRL** [comment]
yeah i think i know what's up - there was a delay that morten added a while back, think this might be an unintentional side effect/ indicate that the solution should be elsewhere. Just wanted to make sure, feels like we've all been a little siloed lately. thanks!

**Comment by csossi** [comment]
Verified in QA
