### ISSUE TITLE
Video Trimming: Add duration to trim component

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9193]
## Feature Description
originally asked for by @aaskedall 
Feature request: time indicator of how long the trimmed segment is

Todo:
Add time to the trim bar (12px, primary color):
<img width="552" alt="Screen Shot 2021-10-13 at 1 02 01 PM" src="https://user-images.githubusercontent.com/90645922/137180414-dffbd576-82a3-4746-8af1-a0d245b801b1.png">

**Comment by swissspidy** [comment]
Related: #9393

**Comment by miina** [comment]
See @agingoldseco's suggestion for UX here: https://github.com/google/web-stories-wp/issues/9393#issuecomment-942534048

**Comment by csossi** [comment]
Verified in QA
