### ISSUE TITLE
Video Trimming: Show users that trimming is "in progress" better

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9195]
## Feature Description

Originally reported by @BrookeGraham , @aaskedall 
When the user trims the video, the trim icon seems to disappear from the UX. What's happening here is that the video is undergoing a trim & video optimization during this time period, and until this process is completed, the user is unable to perform another trim action.

This is indicated to the user via the progress bar that appears under the new trimmed video asset in the media panel, however, that can be a challenge to see (and interpret), especially if the user has moved to a different panel.

We should provide the user a better indicator that this process is underway, and that is why the trim icon/action is not currently available.

Here we see the video asset being trimmed, with the trim icon now "missing":

<img width="448" alt="image15" src="https://user-images.githubusercontent.com/58738530/135160425-4dbe6b2c-fa15-41a3-8d41-5144437c54de.png">

Additional information from @aaskedall in a duplicate issue (#9192):
Feature request: better indication of processing on the video itself or a busy indicator in the quick action menu.

**Comment by miina** [comment]
Looks like this needs additional UX input to understand how to show the progress for users better. This would probably be the same for muting and video optimization then, I assume?

cc @agingoldseco 

Also tagging @spacedmonkey here since I believe you brought a similar topic up at some point.

**Comment by swissspidy** [comment]
> This would probably be the same for muting and video optimization then, I assume?

Not necessarily. This ticket is about triggering video trimming via the Quick Actions menu. But we don't (yet) have quick actions for muting or optimization. So this flow doesn't exist there.

> since I believe you brought a similar topic up at some point.

#9159 probably

**Comment by miina** [comment]
> This ticket is about triggering video trimming via the Quick Actions menu. But we don't (yet) have quick actions for muting or optimization. So this flow doesn't exist there.

True about the quick action menu.

The feature request mentions "a better indicator that the process is underway" so depending on the UX, the indicator could potentially make sense for all processes though (unless it will be specific to the Quick Actions menu).

**Comment by miina** [comment]
This seems to be a potential duplication: https://github.com/google/web-stories-wp/issues/9192
Looks like #9192 is partially suggesting a solution for the issue:
> better indication of processing on the video itself or a busy indicator in the quick action menu.

I'll copy the information over to this issue and close #9192.

**Comment by spacedmonkey** [comment]
I think I have mentioned this somewhere else, but I had the idea to show the progress bar on the lay, in the layer panel. So if a resource is, muting, transcoding, trimming or uploading, you see a progress indicator of some kind. 

Adding a progress indicator to the element itself might be a little confusing.
