### ISSUE TITLE
Retriggering smart coloring

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9206]
## Feature Description

Quick action + design panel action for retriggering smart logic (e.g. after position change)

Todo:
- Add a new item to the quick action menu of a single text element and using the text magic icon from [Figma](https://www.figma.com/file/Ha6kk9yXDN1rB80NzcDf2J/_Editor---Design-System-%22Style-Guide%22?node-id=3441%3A80829).
- When clicking on the icon, the auto-styling logic is triggered on the single text element.
- Note that this feature will be applied to single text element only, multi-selection will not support it!
- Add a button to the design panel for triggering this auto-styling, [see Figma](https://www.figma.com/file/3t6ZYIDqzRpyBCRsZ1G7wJ/Adaptive-Text-Colors-Button?node-id=0%3A1), use the tooltip `Adaptive text colors` for it.
- Update the Color input to use icon for opacity ([Icon](https://www.figma.com/file/Ha6kk9yXDN1rB80NzcDf2J/_Editor---Design-System-%22Style-Guide%22?node-id=3441%3A80829) )
<img width="37" alt="Screenshot 2021-10-11 at 18 03 56" src="https://user-images.githubusercontent.com/3294597/136813073-4ce0927b-f7e6-4e81-a13f-15ae2e6c2d7f.png">

## Additional Context
Icon for the quick action menu:
<img width="116" alt="Screenshot 2021-10-06 at 11 42 32" src="https://user-images.githubusercontent.com/3294597/136169690-2668ac19-a12a-47ec-9fdb-61c313a0971b.png">

Design panel:

<img width="348" alt="Screenshot 2021-10-08 at 12 50 30" src="https://user-images.githubusercontent.com/3294597/136536097-ed939991-e2aa-439a-8738-a5b44f2e4d68.png">

**Comment by miina** [comment]
@aaskedall @gajasinski 
Should the re-triggering logic be enabled for multi-selection of text as well or just single text elements? 
E.g. if the user adds a text set and then later selects the same elements, can the smart styling be re-triggered on it again? If so, would it be re-triggered per element or handle the multi-selection as a text set (this would mean that any selection of multi-selected texts would be considered a text set when re-triggering the logic)?

Thoughts?

**Comment by gajasinski** [comment]
@miina are you suggesting this follow a pattern like this?
![test_with_bold](https://user-images.githubusercontent.com/90706605/135308857-39d06f64-a537-45d5-a879-4c0278b98ec7.gif)

**Comment by miina** [comment]
@gajasinski I'm mainly asking it this would be the pattern for re-triggering the auto-styling logic. Auto-styling is currently used in two separate ways:
- When adding a single text. If a single text is added with auto-styling on, then the single text is assigned either black/white text color + if needed either black/white highlight as well.
- Text Sets: When a text set is added with auto-styling on, then the *all the texts* are assigned either white/black text color and depending on the contrast, the whole area would get a semi-transparent white or black scrim behind it.

@aaskedall shared the icon for re-triggering the auto-styling in the quick action menu / from the design panel but we don't really have a product brief / specs about it.

- Do only single texts allow this?
- Does multi-selection support this as well? If multi-selection supports this, should it be applied assuming that every selected element is one single text? Or should a group selection be considered the same way as a text set?

Thoughts?

**Comment by gajasinski** [comment]
Going to have to defer to @aaskedall for best practices on this matter.

**Comment by csossi** [comment]
Verified in QA
