### ISSUE TITLE
Web Stories Carousel Widget Not Clickable on AMP Pages with Legacy Theme

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#9208]
## Bug Description

The Web Stories Carousel Widget is not clickable on an AMP page with the AMP legacy theme. The issue can be reproduced on AMP Legacy theme (with “Astra” theme activated). Console errors show `amp-bind` script is missing. Thanks to @milindmore22 for his findings that the `amp-lightbox` markup is not getting added on Legacy theme for some reason. His alternative considered is to add this code snippet `add_action( 'amp_post_template_footer', [ $this, 'render_stories_lightbox' ] ); `below [this line](https://github.com/google/web-stories-wp/blob/main/includes/Renderer/Stories/Renderer.php#L254)

## Expected Behaviour
For the Web Stories to open in a lightbox.

## Steps to Reproduce

1) Enable AMP plugin and its Reader Mode
2) Activate Astra Theme
3) Add Web Stories Carousel Widget
4) Visit site in AMP version
5) Click on Story
6) Note behavior and console errors

## Screenshots

https://user-images.githubusercontent.com/66372350/135308359-fe043df0-4d81-4082-a770-887b28db97e1.mov

<img width="1433" alt="Screen Shot 2021-09-29 at 11 59 44 AM" src="https://user-images.githubusercontent.com/66372350/135308174-b9629276-a1ff-43f3-8085-4c01d65bd8ad.png">

## Additional Context

Original report: https://wordpress.org/support/topic/web-stories-not-clickable-on-amp-pages/ 

Stories not clickable at https://www.thecurrentindia.com/govt/encumbrance-certificate-in-karnataka/?amp=1 , but clickable at https://www.thecurrentindia.com/govt/encumbrance-certificate-in-karnataka/ . 

- Plugin Version: 1.11.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
Yep, hooking into `amp_post_template_footer` would indeed be the correct solution here.

**Comment by csossi** [comment]
Verified in QA
