### ISSUE TITLE
Presets Duplicated - Caption and Label

### ISSUE THREAD

**Issue by csossi** [swissspidy/web-stories-wp#9210]
## Bug Description

Regression testing in Main branch and noted that selecting text presets "caption" and "label" create duplicate entries.

Note: this appears to sometimes be random - will click "caption and two entries are created - will click it again and only 1 created

## Expected Behaviour

1 click = 1 entry on canvas

## Steps to Reproduce

1. Open editor
2. Click "T" for text presets
3. Click "caption" and note duplicate entry
4. Click "label" and note duplicate entry

Note: may have to repeat 3 and 4 a few times to see the error

## Screenshots

Video:

https://share.getcloudapp.com/geuALvO4 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System: 
- Browser: Seeing this across diff browsers on both Mac and Win10

**Comment by swissspidy** [comment]
Can't reproduce this right now. 

Maybe a Moveable issue?

cc @miina

**Comment by miina** [comment]
Hm, yes, could be a Moveable issue and if it is, then probably from #9095 -- I'll take a look at it, probably next week.

**Comment by csossi** [comment]
Verified in QA
