### ISSUE TITLE
Video: Allow toggling audio muting

### ISSUE THREAD

**Issue by aaskedall** [swissspidy/web-stories-wp#9222]
## Feature Description

For improved usability, we should investigate allowing the user to toggle the audio of a video on an off without the need to remove it and manually find the clip with audio to undo.

**Comment by spacedmonkey** [comment]
Worth noting, on muted videos, we store the original video id. So, we could add an "unmuted" button, that just replaces the resource from the muted to the original, unmuted one. Similar to https://github.com/google/web-stories-wp/issues/8892

**Comment by swissspidy** [comment]
It would be better to have an actual checkbox that users can toggle instead of a second "Unmute" button.

Video with sound -> Toggle checkbox -> display spinner while in progress -> Untoggle checkbox -> maybe display spinner (theoretically no spinner needed because that's gonna be super fast)

**Comment by swissspidy** [comment]
^ @agingoldseco WDYT about the above suggestion to use a checkbox for muting and display a spinner next to the checkbox while muting is in progress?

**Comment by agingoldseco** [comment]
My concern with a checkbox is that it might not convey the on/off message quite the same way people are used to—what language would we use for it? I picture an on/off toggle convention for this, with a simple label like "Video audio". Or a button that switches from "Remove audio" to "Re-add audio". Could see a spinner being used in any of these scenarios though, to keep people from clicking again if change isn't instant.

**Comment by swissspidy** [comment]
I was thinking of a checkbox because we already have "Loop" checkbox, so I figured we could just add a "Mute" checkbox next to it:

![Screenshot 2022-01-19 at 23 15 38](https://user-images.githubusercontent.com/841956/150222954-6ac815b3-78be-46f9-9a77-0fbecce88741.png)

But just changing the button text should work fine too 👍 

As for an on/off toggle, I feel like using our existing switch/toggle UI component for that would take up too much space:

![Screenshot 2022-01-19 at 23 18 41](https://user-images.githubusercontent.com/841956/150223287-bb94e965-0ec4-4658-8320-675773ec4c63.png)

**Comment by agingoldseco** [comment]
Ah, didn't know about that toggle! I was thinking of this one that appears to be in the design system, but idk if it's used anywhere else in the UI. 
<img width="427" alt="Screen Shot 2022-01-19 at 3 53 09 PM" src="https://user-images.githubusercontent.com/90645922/151212414-b5c2effb-85db-4caf-aa4c-f797c5e1dc96.png">

I actually think the checkbox is fine, showed it to Andrew, but I've been told "mute" is an offensive word to some people—how about we just use "Include video audio" and have the checkbox checked by default?

**Comment by swissspidy** [comment]
> I was thinking of this one that appears to be in the design system, but idk if it's used anywhere else in the UI

Only aware of this instance off the top of my head:

<img width="360" alt="Screenshot 2022-02-15 at 15 14 27" src="https://user-images.githubusercontent.com/841956/154079368-b3d8cab7-97c8-456b-8c72-559cab17ab73.png">

> I actually think the checkbox is fine, showed it to Andrew, but I've been told "mute" is an offensive word to some people—how about we just use "Include video audio" and have the checkbox checked by default?

TIL! We can definitely use different wording. Not 100% sure though whether this should be "Include audio" and checked by default or "Exclude audio" and _not_ checked by default. Perhaps we can try & see what works best.

**Comment by spacedmonkey** [comment]
I just want to confirm the ask here. 

Videos uploaded without audio, should not show this toggle. 

Videos uploaded with audio, should show toggle. 
On pressing the toggle, the toggle should be disabled ( or hidden ). 
Once muting is completed, video element is updated and toggle is re-enabled. 
When toggle is now pressed, the muted / unmuted, the video element should be updated with correct version. 

Should there be some level of debouncing or a progress spinner while the switch from muted to unmuted version happens. The operations to make a rest api request to get the correct version, might take up to 5 seconds for the api response to return. What happens if the user button mashes the toggle?

**Comment by swissspidy** [comment]
> Videos uploaded without audio, should not show this toggle.
> 
> Videos uploaded with audio, should show toggle.
> On pressing the toggle, the toggle should be **disabled**.
> Once muting is completed, video element is updated and toggle is re-enabled.
>  When toggle is now pressed, the muted / unmuted, the video element should be updated with correct version.

Yes, if by toggle you mean checkbox. We'll be using a checkbox for this.

> Should there be some level of debouncing or a progress spinner while the switch from muted to unmuted version happens. The operations to make a rest api request to get the correct version, might take up to 5 seconds for the api response to return. What happens if the user button mashes the toggle?

No debouncing for now. Let's see how well it works without any of that.

There should be a spinner while muting (or unmuting) is in progress.

**Comment by spacedmonkey** [comment]
Okay, I have started work on this ticket and discovered something, there is no relationship from muted video to original video. When created a muted video, there is a piece of [post meta](https://github.com/GoogleForCreators/web-stories-wp/blob/176e2eb3415d70e3f8eeae0a77cdcf66b9eebad8/includes/Media/Video/Muting.php#L46) saved against original video, saving the attachment id. This means that if you are viewing unmuted video and there is muted version, you can do a simple request the rest api to the muted version. See this snippet. 

https://github.com/GoogleForCreators/web-stories-wp/blob/176e2eb3415d70e3f8eeae0a77cdcf66b9eebad8/packages/wp-story-editor/src/api/media.js#L88-L108

It is not possible to easily do this lookup the other way. So there are a couple of ways we could continue with this ticket.

1. We create a new piece of post meta / use parent field. For new muted videos, save the original attachment against the muted version. Making the reserve  lookup easy. 
  - For existing media, run a database migration to populate post meta / parent field.
  - Change the logic on muting to save this data for new videos that are muted. 
2. Extend the media rest api to be able to a meta query, to do the lookup. 

Option 1, could be a lot more work than the original scope of this ticket. 
Option 2, could return in slow meta queries. 

We may also need to have a new property to the resource object, like originalId / parentId / unmutedId, so we know to show the user the option unmuted the video. 

@swissspidy Can you advice on this one, I am blocked currently.

**Comment by swissspidy** [comment]
Hmm I see 😞 

Both options would definitely make this ticket too big and warrant its own.

At first glance option 1 is cleaner, but it's a whole lot of work for little benefit.

So this warrants some reconsideration.

I'll have to move this to the backlog again for now I'm afraid.

> We may also need to have a new property to the resource object, like originalId / parentId / unmutedId, so we know to show the user the option unmuted the video.

I don't see the need for this when we can just get the original ID from the REST API (using either option 1 or 2)
