### ISSUE TITLE
Flaky test: `should add categories and remove categories`

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9226]
## Bug Description
The following flaky test needs fixing: `Categories & Tags Panel Categories keyboard interactions > should add categories and remove categories`

PR that disabled the test: #9225 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrittanyIRL** [comment]
thanks, miina! @samwhale just fixed this here: #9223
