### ISSUE TITLE
Templates: Elements stripped by KSES

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9227]
## Bug Description

I was notified that some of the templates, for example the Summer Fashion one, are broken for users without `unfiltered_html` capabilities. KSES is stripping lots of content there.

## Expected Behaviour

The templates should be usable for authors.

## Steps to Reproduce

1. Log in as author
2. Create a new story from the Summer Fashion template
3. Preview story
4. See broken content

## Screenshots

<table>
<tr>
	<td>Actual
	<td>Expected
<tr>
	<td><img src="https://user-images.githubusercontent.com/841956/135598792-a56af6ad-382f-48dc-a76f-c56170d62185.png" alt="Actual result" />
	<td><img src="https://user-images.githubusercontent.com/841956/135598777-e9dd6eee-fc35-448e-9782-cd4a57a28356.png" alt="Expected appearance" />
</table>

## Additional Context

- Plugin Version: 1.11.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

**Comment by csossi** [comment]
Verified in QA
