### ISSUE TITLE
Checklist: Empty state not showing with contributor role

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#9232]
## Bug Description

The empty state of the checklist is not being shown to a user with the `contributor` role. When the checklist items are complete, the publish button tooltip still says the user should review the checklist.

## Expected Behaviour

Empty state of the checklist should be displayed when all checklist issues that the user can fix are fixed.

## Steps to Reproduce

1. Sign in as a contributor
2. Create a new story
3. Keep editing until all checklist items are completed
4. See that there is no empty state (checkmark icon with some nice text)

## Screenshots

![image](https://user-images.githubusercontent.com/22185279/135629100-48a82b51-4fa9-461b-bc83-6f4d9d11b18c.png)
![image](https://user-images.githubusercontent.com/22185279/135629830-cc34a176-1257-4fd3-9208-29328948c75c.png)

## Additional Context

- Plugin Version: 1.12.0
- WordPress Version: 5.8.1
- Operating System: MacOSX Big Sur
- Browser: Chrome

**Comment by BrittanyIRL** [comment]
Nice catch! Adding a test for this would be great.

**Comment by samwhale** [comment]
Tested this and seemed like it's working? ![image.png](https://images.zenhubusercontent.com/5b1032a1348b7966b43421a4/fb604a36-2b5d-4628-a075-60adad8c63ab)

Will add a test just in case
