### ISSUE TITLE
Taxonomy: Contributors have capability to create web story tags

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9236]
Came up in #9212 and am isolating here since that ticket has expanded. 

Right now, contributors are given the ability to create new web story tags: 
![Screen Shot 2021-10-01 at 2.22.37 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/ce1ac810-3309-4c57-83f2-f4115afa811b)

Is this something we want? If yes, we can update the e2e test and call it a day, otherwise this ticket should be to address that config discrepancy. 

In posts, contributors cannot create new tags, just assign existing ones.

**Comment by swissspidy** [comment]
cc @spacedmonkey

**Comment by swissspidy** [comment]
To create new ones, it looks like for hierarchical taxonomies users need `edit_terms_web-stories` caps, for tags they'd need `assign_terms_web-stories` caps.

**Comment by swissspidy** [comment]
> In posts, contributors cannot create new tags, just assign existing ones.

I **cannot** confirm this.

1. Log in as contributor
2. Create new post
3. Add some tags and save post
4. Log in as admin
5. Go manage tags
6. See the tags created by contributor

**Comment by spacedmonkey** [comment]
I am confused by this ticket, what is needed here? A change of behavior?

**Comment by swissspidy** [comment]
> I am confused by this ticket, what is needed here? A change of behavior?

It's a bug report for something that isn't actually a bug but WAI.

I'll wait for Brittany to reply & confirm.

**Comment by BrittanyIRL** [comment]
<img width="625" alt="Screen Shot 2021-10-04 at 9 24 50 AM" src="https://user-images.githubusercontent.com/10720454/135888536-d21a6471-9f26-4792-9954-5b068f5f9c4c.png">


So the above are the `capabilities` from the `story` as well as the `base` and `slug`. We're checking for the slug in the capabilities like so
```
 capabilities[`create-${taxonomy?.restBase}`] ||
            capabilities[`create-${taxonomy?.slug}`]
```
to figure out what users can do. 

The console on the right is from a contributor and the one on the left is admin.
The contributor, as far as I'm aware and what made me make this ticket, should not have `create-web_story_tag` as a capability. 

Does that make more sense?

**Comment by swissspidy** [comment]
> The contributor, as far as I'm aware and what made me make this ticket, should not have create-web_story_tag as a capability.

Not 100% correct. Check the post editor as a contributor. Contributors can create new tags.

**Comment by BrittanyIRL** [comment]
ok great then this isn't an issue. i was under the impression that tags should not be created since categories cannot be.

**Comment by swissspidy** [comment]
@BrittanyIRL could you unskip the e2e test that references this ticket?

**Comment by BrittanyIRL** [comment]
oh whooops, yup absolutely.
