### ISSUE TITLE
Nameable Layers 

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9248]
## Summary

Discussed and requested by design in conjunction with #8983 but isolated to make sure details are attended to accordingly.

Needs some discovery and syncing cross pods before this is dev ready. My understanding is this would be adding functionality that adds a new property getting saved to every story layer that would let them have a readable name separate from their id, etc. 

## References

https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=9935%3A421370
<img width="300" alt="Screen Shot 2021-10-04 at 1 10 00 PM" src="https://user-images.githubusercontent.com/10720454/135917741-4d8bdf9e-4af3-4f46-b71e-e93dfc27174f.png">

## Acceptance Criteria

- [ ] You can rename the layer by double-clicking on it in the Layers Panel, using Canvas RCM->Rename layer or Layers Panel context menu.
- [ ] In edit mode: Enter key and blur event will save changes, Escape key will cancel them.

## Other notes 

Naming layers is going to impact keyboard users because right now the layers panel is hidden for keyboards as all functionality is mirrored in keyboard shortcuts. The accessibility of the layers panel will need to be reconsidered ahead of this functionality getting added to the layers panel.

**Comment by felipebochehin87** [comment]
@barklund @mariana-k please, two questions:

1. On PR #11477, the summary reads: _"Editing of the layers names is disabled if the layer is a Background."_ However, I was able to change the background name (please see 1st video below). Has anything changed regarding this?

2. When I update the layer name and then I remove this new name and save with empty name, I see that the name is reset to the original name, not to the one that I updated. Is that expected? Please see 2nd video below.

https://images.zenhubusercontent.com/235435637/de389008-94ea-4992-8d95-79a3ab25b13e/2022_05_27_06_57_02.mp4

https://images.zenhubusercontent.com/235435637/038072a9-71fa-4388-8316-a1ac578f16c5/2022_05_27_07_03_56.mp4

**Comment by barklund** [comment]
@felipebochehin87,

> 1. On PR [Editor: Layer renaming #11477](https://github.com/GoogleForCreators/web-stories-wp/pull/11477), the summary reads: _"Editing of the layers names is disabled if the layer is a Background."_ However, I was able to change the background name (please see 1st video below). Has anything changed regarding this?

Yes, that has changed. Background layers are now renamable too. I will update the instructions.

> * When I update the layer name and then I remove this new name and save with empty name, I see that the name is reset to the original name, not to the one that I updated. Is that expected? Please see 2nd video below.

Good points, I will make sure to fix this so submitting an empty name (or even white-space-only name) is the same as aborting editing (so the name doesn't change at all).

**Comment by barklund** [comment]
@felipebochehin87, please re-verify this PR. I have changed the instructions re. your first comment and changed the implementation re. your second.

**Comment by felipebochehin87** [comment]
I was able to rename layers
Removed the name - previous name was set back to the layer
Double-click, right click, Enter, click outside the layer, commands working
