### ISSUE TITLE
Layers Panel Cosmetic Updates

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9254]
## Description 
Some tweaks to the layers panel styles found here: https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=9954%3A422171

- Vertical size of each panel reduced from 44px to 35px
- Image squares 21x21px 

## Acceptance criteria 
- Vertical size of each panel reduced from 44px to 35px
- Image squares 21x21px

**Comment by hamza-arshad** [comment]
Hi - is it available? Would love to work on this.

**Comment by swissspidy** [comment]
One of our team members is planned on picking it up soon, but you're more than welcome to contribute this change if you'd like to! 👍

**Comment by BrittanyIRL** [comment]
@csossi  if there's anyway you can run through this one this week it'd be helpful, Max is working on a lot of other layers panel updates and this contribution is needed to complete that.
