### ISSUE TITLE
Enable feature by default: Page carousel - Cache with image thumbnails

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9263]
## Feature Description
Now that issues with Safari have been fixed in #9168, we can enable the feature and set the feature flag to `true` by default.

**Comment by csossi** [comment]
still seeing some of the empty grey boxes, but note that these are pages that have 3rd party images/videos/animated gifs

if you confirm that's out-of-scope here (no mention of it in QA Instructions) I can verify this one
![image](https://user-images.githubusercontent.com/16945664/136040804-3a1c4cd4-548f-49e7-8f99-91481b500b28.png)

**Comment by miina** [comment]
@csossi Looks like uploading the correct files to QA failed. Re-running the build, will let you know once it succeeds.

**Comment by csossi** [comment]
Verified in QA
