### ISSUE TITLE
Remove Eyedropper Feature Flag Code

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9267]
## Task Description

The eyedropper feature has been enabled for a while. Time to remove the code completely.

**Comment by hamza-arshad** [comment]
@swissspidy is this open?

**Comment by swissspidy** [comment]
Yep 👍 

This ticket basically entails removing stuff like `useFeature('enableEyedropper');`, `fixture.setFlags({ enableEyedropper: true });` from the code base and removing the `enableEyedropper` entry in `Experiments.php`

See #8579 and #9025 for some inspiration.

**Comment by hamza-arshad** [comment]
Thanks. @swissspidy can you assign this to me?

**Comment by swissspidy** [comment]
Assignment doesn't really matter much, but sure.
