### ISSUE TITLE
Taxonomy: Weird Red Box-Shadow

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9276]
## Bug Description

Morten's seeing a weird red box shadow from colors.min css file from WordPress. Nobody else has been able to replicate this but let's mitigate it just to err on the side of caution and override the box-shadow on input type search:focus to overcome this because it's ugly. 

![Screen Shot 2021-10-05 at 11 03 24 AM](https://user-images.githubusercontent.com/10720454/136078133-cc2ff941-ddb3-4565-ba47-133ceb8c696d.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Verified in QA
