### ISSUE TITLE
Taxonomies: Improve dropdown when choosing a top level category

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9278]
## Feature Description

Originally reported by @barklund 
There is an Inconsistency in choosing a top-level category between editor and Gutenberg. In Gutenberg, adding a top level category requires you to select “None” as the parent, whereas in the editor, the entry is somewhat confusingly named “-- Parent category --”:"

for example, here is the presentation of top level in the editor:
![image9.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/3ec23f92-7912-4f21-b776-85693dc87abd)

and here it is in Gutenberg:
![image5.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/73c76a55-b447-46ef-a63d-cc28b74a1b98)

## Additional Context

The fix we discussed in bug bash is to update the default to "none" instead of parent category which is a separation from Gutenberg.

**Comment by swissspidy** [comment]
I assume with "inconsistency in choosing a top level category between the dashboard and the editor" you meant "between Gutenberg and editor"? 🤔

**Comment by barklund** [comment]
> I assume with "inconsistency in choosing a top level category between the dashboard and the editor" you meant "between Gutenberg and editor"? 🤔

It's actually on the _Web Stories_ > _Categories_ page (which I wrongly refer to as "dashboard" as that's my term for anything that doesn't happen inside the editor 😂 ).
