### ISSUE TITLE
Taxonomy: Duplicating Categories

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9279]
## Bug Description

Reported by @barklund 
>  I can’t add a duplicate category name somewhere else in the category tree. Is that WP standard? I want to add a category for the clothing type “Cardigan”, but nothing happens when I try to do so - I suspect it’s because we already have the corgi sub-category “Cardigan”, though that’s a completely different thing.

If you add categories in the categories list table (the thing that looks like a categories dashboard in the stories plugin, see screenshot below) you can add duplicative categories. This makes sense, given examples (as pointed out by @spacedmonkey ) like `Countries > Canada > Maple Syrup` or `Syrups > Maple Syrup` where both cases of maple syrup are independent and should be valid and separate. 

## Expected Behaviour

The editor should allow duplicative categories when their hierarchy is different.

Also, let's add a new e2e test case here.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
> If you add categories in the dashboard

Did you mean_in Gutenberg_?

**Comment by BrittanyIRL** [comment]
Just copying from the bug bash doc. This is what was meant
![Screen Shot 2021-10-05 at 12 10 23 PM](https://user-images.githubusercontent.com/10720454/136087556-cc46c4d9-7021-4552-bf07-8fc93cb40471.png)

**Comment by swissspidy** [comment]
Ah!

That would be the "categories list table".

Using "Dashboard" for this is very confusing because there's already the Web Stories dashboard and the WordPress admin dashboard.

**Comment by csossi** [comment]
Verified in QA
