### ISSUE TITLE
Taxonomies: Make it obvious to users what the top level Categories are

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9280]
## Feature Description
originally reported by @barklund 
As can be seen, the categories are not presented in a tree when choosing a parent category, so it’s not clear from the dropdown that “Corgis” is a child category of “Dogs”.
![image9](https://user-images.githubusercontent.com/58738530/136078819-e98f7a7e-27df-4cf4-a28b-3b4386ff4e70.png)

**Comment by BrittanyIRL** [comment]
@csossi now this menu should look like this
![Screen Shot 2021-10-08 at 2 14 55 PM](https://user-images.githubusercontent.com/10720454/136625494-5e6df42c-67b3-454c-af15-31142e40adf9.png)

**Comment by csossi** [comment]
Verified in QA
