### ISSUE TITLE
Taxonomy: Tag Input Height Resize

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9281]
## Bug Description

Found by @barklund in bugbash
> Slight difference in size for tag input height with and without tags in it (obvious when you undo/redo adding a single tag) 

## Expected Behaviour

Input should not resize until tags wrap

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Verified in QA
