### ISSUE TITLE
Taxonomies: Show/Confirm to user when a new Category was created

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9283]
## Feature Description
Originally reported by @samwhale 

Keyboard Accessibility Feature request. When submitting a new category with the keyboard it would be nice to show the user that the category is created. Maybe we could use a snackbar or somehow add it to the top of the stack?

**Comment by BrittanyIRL** [comment]
Do we want the same functionality with new tags?

**Comment by samwhale** [comment]
> Do we want the same functionality with new tags?

I think it's only necessary for categories since adding a new tag always adds it right next to the input. Right @littlemilkstudio?

**Comment by swissspidy** [comment]
How is adding a new category/tag announced to screen readers? Might be worth comparing with Gutenberg too.

**Comment by samwhale** [comment]
> How is adding a new category/tag announced to screen readers? Might be worth comparing with Gutenberg too.

Web stories: Currently there is no announcement that a new category was added
Gutenberg: Announces `"Category added"` and places the new category at the top of the container

**Comment by maxyinger** [comment]
> I think it's only necessary for categories since adding a new tag always adds it right next to the input. Right @littlemilkstudio?

Yea I don't see a need for extra highlighting of this around Tags.

Happy to Mirror Gutenberg exactly or do whatever with regard to Categories here

**Comment by BrittanyIRL** [comment]
let's mirror Gutenberg

**Comment by BrittanyIRL** [comment]
For QA: 
If a screen reader is in use and the user creates a new category they will hear "Category added." announced by the SR.
If a screen reader is in use and the user types in a value on the tag input that expands the autocomplete list they will hear the result count of options announced by the SR.

**Comment by csossi** [comment]
Verified in QA
