### ISSUE TITLE
Taxonomies: Change the header in the associated design panel

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9284]
## Feature Description

Originally reported by @samwhale 

> Think we should update the header since we can add custom taxonomies now 

Currently appears as:

![image10](https://user-images.githubusercontent.com/58738530/136080699-043ab854-5694-4354-9b8f-c389208fefc6.png)

Gutenberg splits it out like this:
![image7](https://user-images.githubusercontent.com/58738530/136080747-f2fe7b3e-b0f2-48f4-b1d9-2a587a294901.png)

**Comment by BrittanyIRL** [comment]
Did we agree on the update to `Taxonomies` ? @bmattb @choumx @agingoldseco

**Comment by dreamofabear** [comment]
"Taxonomies" sound good to me.

**Comment by agingoldseco** [comment]
I might be alone here, but I'm concerned a lot of people won't understand what "Taxonomies" means—it's not a word you see every day. While Categories and Tags seems simplistic with these new additions, people know exactly what it does.

**Comment by samwhale** [comment]
> I might be alone here, but I'm concerned a lot of people won't understand what "Taxonomies" means—it's not a word you see every day. While Categories and Tags seems simplistic with these new additions, people know exactly what it does.

Yeah I agree that it's a confusing term. However, when we start adding custom taxonomies then `Categories and Tags` won't apply, right?

I'm having trouble thinking of something more digestible. Maybe something like `Metadata` or `Grouping` 🤔

**Comment by BrittanyIRL** [comment]
Should we hold on renaming this for the time being?

**Comment by dreamofabear** [comment]
"Taxonomies" is a bit academic but is the standard WordPress terminology for the generalization of tags/categories. I don't think we should diverge: https://wordpress.org/support/article/taxonomies/

**Comment by BrittanyIRL** [comment]
Sounds good, we'll update to 'Taxonomies' from 'Categories & Tags'

**Comment by csossi** [comment]
Verified in QA
