### ISSUE TITLE
Unify Search Components

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9285]
## Feature Description
Originally reported by @agingoldseco 

> this doesn’t immediately register to me as a search bar I can type into as part of this larger scroll box. Would like to see the word “search” grayed out in there

<img width="301" alt="image3" src="https://user-images.githubusercontent.com/58738530/136082798-5e8496ca-b096-4557-8c51-6f753a72e98f.png">

Here is an example of "Author search" elsewhere in the editor:

![image15](https://user-images.githubusercontent.com/58738530/136082886-7aaa1710-28c1-4124-bf33-ccdd033491a2.png)

And here is an alternate presentation of the Category search 
![image2](https://user-images.githubusercontent.com/58738530/136083235-dde26a7b-885e-4fe7-8232-88db4e948b0c.png)

## Additional Context

This isn't isolated to the categories search, which was based off of what Gutenberg does for their categories search. But the comments Amy brought up in bug bash which Matt copied over here in this ticket do speak to the inconsistencies that we have in our search components which have been created for various needs. It might be a good time to look at unifying them.

**Comment by BrittanyIRL** [comment]
I think this should not be isolated to taxonomies, but rather be a discovery for design to unify the search dropdown components in the editor that have been implemented at various times. Off the top of my head there's the author search, font search, taxonomy now, dashboard has one too.

**Comment by swissspidy** [comment]
Would be nice to have some unification for sure, but that can potentially take a long time.

What can we do in the short term? IMHO at the very least we could add a placeholder text, e.g. "Category" (`taxonomy.labels.singular_name`)

**Comment by BrittanyIRL** [comment]
totally. I'll just make that it's own ticket to let this one serve as unification / update the name of this ticket to make more sense.

**Comment by agingoldseco** [comment]
It looks like every other search bar I've checked has that same magnifying glass and "Search" except this one—since it might take a little while to get to truly inventorying/unifying them all, would everyone be okay with adding those elements to the bar as a quick solution?

**Comment by BrittanyIRL** [comment]
Sure - added to the above issue #9300 since we split it up!

**Comment by BrittanyIRL** [comment]
This came up again here: https://github.com/google/web-stories-wp/pull/9539#pullrequestreview-790896185
