### ISSUE TITLE
Firefox: Publisher panel shows two scrollbars

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9286]
## Bug Description
originally noted by @spacedmonkey 

> (I see) two scrollbars on publisher document section

![image16](https://user-images.githubusercontent.com/58738530/136083730-427ade0e-b1ce-4097-9644-d1e3451526e2.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
@spacedmonkey Could you confirm if you can still see the issue, and also if there were any specific steps to reproduce it. Currently not seeing it, testing with Chrome on 13'' laptop.

**Comment by spacedmonkey** [comment]
@miina did you test it on Firefox?

**Comment by miina** [comment]
Sorry, completely missed the Firefox part there which was kind of the main point 🤦 

I can also see a second scrollbar for publishing in FF, even though it's below the main scrollbar, not next to it as in your case.
