### ISSUE TITLE
Media: Provide a filter for portrait / landscape orientation

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9287]
## Feature Description

Originally reported by @barklund :
Especially when searching for images that are to be used for Publisher logo, or the story thumbnail, it would be very helpful to have a filter to be able to quickly find images in the media library which are Portrait, or alternatively, Landscape oriented.

**Comment by swissspidy** [comment]
> Especially when searching for images that are to be used for Publisher logo, or the story thumbnail, it would be very helpful to have a filter to be able to quickly find images in the media library which are Portrait, or alternatively, Landscape oriented.

1. It's gonna be super complicated and not worth it IMHO to hook into the WordPress media modal to allow this.
2. There is an image cropping step when choosing an image, so the orientation does not matter at all

Putting this in the icebox for now
