### ISSUE TITLE
Dashboard Settings: Publisher Logo Copy Update

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9288]
## Feature Description

Per discussion here: https://github.com/google/web-stories-wp/issues/9096#issuecomment-928048933 updating the publisher logo copy to include a little blurb about removal. 

Suggested copy is: `Removing a logo from your settings won't remove it from any stories that use that logo.`

**Comment by swissspidy** [comment]
Lowercase "stories" would be nice :-)

**Comment by BrittanyIRL** [comment]
Went with `Removing a logo from your settings won't remove it from any stories using that logo` to deduplicate the `that` in the last fragment.

**Comment by csossi** [comment]
Verified in QA
