### ISSUE TITLE
Taxonomies: Reduce tag input size

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9291]
## Feature Description

The input field for entering tags is **enormous**

Any chance we could make that a bit smaller? Usual input fields in the editor are more like ~36px in size, but this one is a whopping 54px.

![Screenshot 2021-10-05 at 23 53 33](https://user-images.githubusercontent.com/841956/136108337-56053206-8da9-48f5-b754-9a9a02896892.png)

cc @aaskedall

**Comment by BrittanyIRL** [comment]
@aaskedall @agingoldseco - these are rather fat, care if it's decreased a bit for continuity with other sizes in the editor?

**Comment by agingoldseco** [comment]
@BrittanyIRL Not at all, please decrease the size as you see fit—what if we make the individual tags 32px high and the field 46px? It seems okay to keep it _kind of_ big since it has tags inside, but yeah 54px is huge
