### ISSUE TITLE
Choosing Saved Templates in the Page Templates panel crashes the editor

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9294]
## Expected Behaviour
Saved Templates should open instead of the editor crashing.

## Steps to Reproduce
1. Open the Page Templates tab
2. Choose "Saved Templates" from the dropdown
3. See the editor crashing

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
@swissspidy I did bisecting to detect what caused the issue and looks like it came from https://github.com/google/web-stories-wp/pull/8513

Errors in console:
<img width="1016" alt="Screenshot 2021-10-06 at 12 25 55" src="https://user-images.githubusercontent.com/3294597/136176683-c972681f-2e8c-48d5-a783-9b715c7be751.png">

I'll assign it to you for now since it seems to be a regression from infra work.

Usually, the "Save page as template" button appears in the Page templates panel but since merging the PR, it's not happening anymore and selecting "Saved templates" from the dropdown crashes the editor.

**Comment by swissspidy** [comment]
There are three bugs here:

1. Error response from  REST API, due to the story post type not yet being registered
2. Falsely doing a REST API request with `page=false` due to `nexTemplatesToFetch` being `false` (hence two failed requests in the console)
3. `TemplateList` crashing because `pages` is `null` when there are no page templates loaded yet

**Comment by spacedmonkey** [comment]
> Error response from REST API, due to the story post type not yet being registered

There seems be an order issue here. Story post type is registering after web story page story. We used `priority` of [11](https://github.com/google/web-stories-wp/blob/7b3652e23132e8236dfa8389220f482369b4aa3a/includes/Page_Template_Post_Type.php#L152), to ensure it loaded after the [10](https://github.com/google/web-stories-wp/blob/7b3652e23132e8236dfa8389220f482369b4aa3a/includes/Service_Base.php#L58) of stories. 

Not sure when this broke, but we need a E2E test to ensure it doesn't happen again.

**Comment by swissspidy** [comment]
@spacedmonkey Yes, I am working on it

**Comment by csossi** [comment]
Verified in QA
