### ISSUE TITLE
Page Attachment: Validation error due to empty `cta-image` attribute

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9307]
## Bug Description

We got a user report about page attachments causing AMP validation errors if `cta-image` is omitted/removed, because then we set its value to an empty string, and `cta-image=""` is invalid.

## Expected Behaviour

No AMP validation error

## Steps to Reproduce

1. Create new page
2. Add page attachment
3. Remove link icon (if set)
4. Preview story
5. Get AMP validation error related to `cta-image`

## Additional Context

- Plugin Version: 1.12.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

**Comment by csossi** [comment]
Verified in QA
