### ISSUE TITLE
Adding page attachment / link icons not working

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9309]
## Bug Description

We received a user report that changing the page attachment icon doesn't work.

Appears to be related to a change of data format received by the update callbacks since they should now all expect `Resource` objects.

## Expected Behaviour

Changing page attachment icons and link icons should work normally.

## Steps to Reproduce

1. Add a page attachment
2. Try to set the CTA image
3. See that nothing happens

## Additional Context

- Plugin Version: 1.12.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

**Comment by csossi** [comment]
Verified in QA
