### ISSUE TITLE
Use `DependencyInjectedTestCase` classes where possible

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#9317]
## Feature Description

Now, that we are using dependency injection more, example https://github.com/google/web-stories-wp/pull/9313. We should refactor more of tests to move from `TestCase` to `DependencyInjectedTestCase`. This will make class dependency management and refactors much easier.

**Comment by salmanansari14** [comment]
I like to contribute !

**Comment by swissspidy** [comment]
Thanks for sharing your interest!

Once #9313 is merged we'll have a better picture of what's left to be done here, so let's wait a little bit until that one's resolved.
