### ISSUE TITLE
PPC: No Publisher Logos Check

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9320]
@swissspidy pointed out that the issue that shows in the prepublish checklist when users have no publisher logos yet is incorrect - showing that they need to increase the size of the logo rather than just add a new one. 

Let's add a check for a publisher logo existing in a story before telling the user they need to make it larger. 
If there is no publisher logo let's display `Add a publisher logo to your story` that when clicked takes you to the publisher logo upload button. The helper text can stay the same as for increasing the size.

**Comment by csossi** [comment]
Verified in QA
