### ISSUE TITLE
`html-to-image` causing console errors for remote links

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9327]
This is a follow-up issue for #9264.
## Bug Description
After enabling the thumbnail caching for carousel, the e2e tests started failing and the following console errors appeared:
<img width="1091" alt="Screenshot 2021-10-07 at 11 46 42" src="https://user-images.githubusercontent.com/3294597/136528113-02464f8b-27e5-46cc-b939-c08efaf980d2.png">

Note that this can visibly be seen with Contributor role, or when turning off Video Optimization feature from Web Stories -> Settings menu.

Pascal already did some [investigation](https://github.com/google/web-stories-wp/pull/9264#issuecomment-938210070) into possible fixes for the issue.

## Expected Behaviour
- The errors mentioned above should not appear in console when the Video Optimization feature is turned off.

Please make sure to remove the relevant error messages from `ALLOWED_ERROR_MESSAGES` in the `bootstrap.js` file.

## Steps to Reproduce
1. Turn off the Video Optimization feature
2. Open the editor
3. See the errors in console.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
@swissspidy I was looking into this a bit more.
Just using empty string as the embed CSS will not embed the CSS and not display the font correctly. Even though in many cases in preview it wouldn't likely be noticeable, it will still be visible in many cases -- e.g. using larger font size with uncommon font. For example:

<img width="562" alt="Screenshot 2021-10-22 at 13 46 00" src="https://user-images.githubusercontent.com/3294597/138441416-2b84e48d-4118-4c14-a086-da338c0f20f4.png">

WDYT of the option of always assigning `crossorigin="anonymous"` in the backend to all the links/media as done when Video Optimization feature is on? I was thinking that since the feature is on by default and is assumed to be used most of the time and we're doing work assuming it'll be on (e.g. the proxy for Hotlinking), then maybe it makes sense to just always add crossorigin for consistency instead of having to consider less common cases where optimization is not turned on or can't be used (e.g contributors). Thoughts?

Edit: applying the content of `web-stories-fonts-css` of Google Sans only directly as `fontEmbedCSS` does get rid of the console errors but the fonts wouldn't get loaded properly.

**Comment by swissspidy** [comment]
Yeah I feared as much. Adding `crossorigin="anonymous"` by default for cases like this makes sense. But we should probably still only set the COOP / COEP headers needed for video optimization only when that is turned on.

I'll whip up a quick PR.
