### ISSUE TITLE
Video transcoding: Muting and trimming collisions

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#9332]
## Feature Description

Currently, we have some situations, where you can end up with a video "un-muting" even though you might not expect it to.

#### Scenario

* You have an original non-muted video of 60-second duration
* You trim the non-muted video to make a non-muted 30-second video
* You mute that video to make a muted 30-second video
* You then re-trim that muted 30-second video to a new 45-second video
* You might expect this new 45-second video to also be muted, but it's not, since it has been trimmed from the original non-muted video.

We should figure out which result should be the correct one and implement that.

This arose from a discussion in #9315.

## Alternatives Considered

The current approach might be the correct one (the mute flag of the original takes precedence).

**Comment by gajasinski** [comment]
IMO if the user has explicitly muted the video, we should carry that throughout the trim experience.
