### ISSUE TITLE
Video Muting: "Remove audio" button not disappearing

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9335]
## Bug Description

We got a user report about issues with resource updates when muting a video. The "Remove audio" button was simply not going away, yet the new file was uploading successfully.

I looked into it a bit and found some areas for improvement here.

## Expected Behaviour

When muting a video, the "Remove audio" button should be properly removed after the process finishes.

## Steps to Reproduce

1. Click "Remove audio" on video
2. Wait for new video to be uploaded
3. See that "Remove audio" button is still there

See also original bug report: https://wordpress.org/support/topic/remove-audio-not-working-anymore/#post-14951400

## Additional Context

- Plugin Version: 1.12.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

**Comment by csossi** [comment]
Verified in QA
