### ISSUE TITLE
Video Captions: Use similar captions appearance in editor

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9344]
## Feature Description

In #9043 we implemented initial support for using `<amp-story-captions>` to display video captions when viewing stories.

This allows showing captions always on top of all other elements so that they're never covered/obstructed by other elements.

Example:

![Screenshot 2021-09-29 at 14 29 32](https://user-images.githubusercontent.com/841956/135268531-ad945d04-ecb1-4745-8aee-7f0da263349f.png)

Demo Story: https://wp.stories.google/stories/three-tips-to-build-your-digital-community/

In the editor itself we also show captions, but not in this nice way.

Example:

![Screenshot 2021-10-08 at 19 57 50](https://user-images.githubusercontent.com/841956/136601783-dc83e880-b741-47ab-aaa2-bec7ebd95a3f.png)

Notice how the caption is covered by other elements on the page in the editor.

I do wonder whether we should aim for a similar captions appearance in the editor so that it more closely matches the end result.

## Alternatives Considered

* Keep status quo
* Don't display captions in the editor? Would be confusing though and not good for accessibility.

**Comment by gajasinski** [comment]
IMO - We should aim for a similar captions appearance in the editor so that it more closely matches the end result.

**Comment by swissspidy** [comment]
Agreed. It's quite confusing otherwise.

I'd say it's a not a blocker for shipping a V1 of this feature though.

**Comment by agingoldseco** [comment]
Apologies I'm a bit late to this, but I agree that captions should show above any other object on the editor canvas / look like the end result when a video is being watched or edited.
