### ISSUE TITLE
CORS Proxy: Perform preflight request

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9367]
## Feature Description

Ideally in the editor we perform a (CORS preflight?) request first before trying to pass media requests through our proxy. So that we only proxy requests if needed due to performance considerations.

Something along these lines perhaps (untested):

```js
let shouldProxy = false;
try {
	  await fetch(
	      resourceUrl,
	      {
	          method: 'OPTIONS',
	          headers: {
	              'Accept': '*/*',
	              'Access-Control-Request-Method': 'GET',
	              'Access-Control-Request-Headers': {
	                  'Accept': '*/*',
	              }
	          },
	      }
	  )
} catch {
	shouldProxy = true
}
```

(untested)

## Acceptance Criteria

* There is a preflight request done when encountering an external resource the first time when loading the editor
* The response should be cached: ideally we only perform this check once per resource

**Comment by spacedmonkey** [comment]
> The response should be cached: ideally we only perform this check once per resource

By this, do you mean adding a new field to the resource object stored in the element?

**Comment by swissspidy** [comment]
No, nothing stored on the resource itself. Otherwise we would never know when proxying is no longer needed. This can be determined at runtime, when loading the editor.

Something simple to memoize the information:

```js
// in useCORSProxy()
const cache = useRef(new Map()); // useState() might make more sense here, needs testing.

const shouldProxyResource = useCallback(async (resource) => {
if (!resource?.isExternal || resource?.id || !resource?.src) {
  return false;
}

if (cache.current.has(resource.src)) {
  return cache.current.get(resource.src);
}

const result = await doThePreflighRequestHere();

cache.current.set(result);

return result;
}, []);
```

`shouldProxyResource()` could be called in two places:

1. In `packages/story-editor/src/components/library/panes/media/local/hotlink/useInsert.js` when inserting a hotlinked media item for the first time.
2. Once when loading the editor. Perhaps as an effect in StoryProvider or an alternate location

Of course the question is: what do we do while the preflight request is still in progress? Do we just proxy or not? I think it should be OK to proxy in that case, e.g.

```js
const getProxiedUrl = useCallback(
  (resource, src) => {
    if (cache.current.has(resource.src)) {
      return cache.current.get(resource.src);
    }

    const { isExternal, id } = resource;

    if (enableCORSProxy && !id && isExternal) {
      return getProxyUrl(src);
    }
    return src;
  },
  [getProxyUrl, enableCORSProxy]
);
```

(again, untested)


Please let me know what you think

Also cc @choumx for input

**Comment by dreamofabear** [comment]
Sending CORS preflight before proxying sounds reasonable.

**Comment by swissspidy** [comment]
@choumx The question is more _how_ we're going to do it. But I'll try out some options.

**Comment by dreamofabear** [comment]
Ah. I think client-side caching might be overkill. I think we should punt it until we see that (a) creators are hotlinking many pieces of media from the same origin and (b) the preflight roundtrip latency is adding noticeable friction.

> what do we do while the preflight request is still in progress? Do we just proxy or not?

I thought that the proposed benefit of doing a preflight was that we might reduce unnnecessary proxying. If we proxy while the preflight is in progress, doesn't that defeat the purpose?

**Comment by swissspidy** [comment]
> I thought that the proposed benefit of doing a preflight was that we might reduce unnecessary proxying.

True, but if we don't proxy, we can't display the image during that time, so we'd need to display some placeholder.

>  If we proxy while the preflight is in progress, doesn't that defeat the purpose?

Only for a couple of seconds until the preflight request is done and we have determined that proxying is not actually necessary.

**Comment by dreamofabear** [comment]
Ah, or it may be simpler if we just wait/block on the preflight request before inserting the element (perhaps display a loading indicator).

**Comment by swissspidy** [comment]
> Ah, or it may be simpler if we just wait/block on the preflight request before inserting the element (perhaps display a loading indicator).

What if you edit an existing story with some hotlinked media in it?

I don't think we should store/cache the "proxying state" (i.e. whether proxying is needed) on the media resource itself.

Also regarding client-side caching: resources are displayed in multiple places and can be used multiple times in a story. But there should ideally only be 1 preflight request

**Comment by dreamofabear** [comment]
> What if you edit an existing story with some hotlinked media in it? 
> I don't think we should store/cache the "proxying state" (i.e. whether proxying is needed) on the media resource itself.

Hmm, I thought it might be simpler if we do store a `supportsCORS` bit on hotlinked resources at the time of insertion. I imagine that bit would rarely changing for a given resource over time.

> Also regarding client-side caching: resources are displayed in multiple places and can be used multiple times in a story.

I think browser caching should cover this case.

**Comment by csossi** [comment]
Verified in QA
