### ISSUE TITLE
Video Muting: Reuse existing resource if exists

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9385]
### Scenario

* You have an original non-muted video and place it on the canvas
* You mute it
* You create a new story and place the original non-muted video on the canvas
* You mute it
* This will result in another muted version being created instead of just using the original

### How to possibly solve this

1. When optimizing an existing video, fetch `/web-stories/v1/media/<resource_id>` and check for `meta.web_stories_muted_id`.
2. If `meta.web_stories_muted_id` is set, grab `/web-stories/v1/media/<mutedd_id>` and replace the existing resource with the muted one

**Comment by csossi** [comment]
Additional muted video was created:
![image](https://user-images.githubusercontent.com/16945664/138339140-9a42b075-434a-44b5-be95-11f369714a9b.png)

**Comment by spacedmonkey** [comment]
@csossi Any chance of a video showing this behavior? I am not seeing this locally.

**Comment by swissspidy** [comment]
@csossi @spacedmonkey looks like the PR build wasn‘t properly uploaded for QA. I‘ll need to fix that on Monday.
