### ISSUE TITLE
Video: Show video duration in workspace

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9393]
## Feature Description

In the media library, we show the video duration.

But as soon as you insert a video onto the canvas, you don't know how long the video is.

It would be nice if we could show the duration somewhere, either directly on canvas or in the design panel.

**Comment by swissspidy** [comment]
cc @agingoldseco for thoughts

**Comment by agingoldseco** [comment]
Just curious—was this a specific user ask? 

I see a few options for this, currently—might come up with more, but I'd love to hear if any sound appealing:  

- We overlay it on the video itself when it’s selected, in a bottom corner of the bounding box (where it still overlaps the canvas, if the video is half off the canvas or in an odd-shaped mask)
- We put it under the play button and, similarly, show it only on hover
- We make a little section in the video setting box with that info 
- We put it really small under the trim bar when that’s active and have it count down w/ trim (should probably do this anyway)

**Comment by swissspidy** [comment]
I just ran into this myself as I was trying to trim a video and I had no clue how long the current video was and how long the trimmed version was going to end up.

**Comment by agingoldseco** [comment]
Gotcha, that's helpful context! Perhaps we should first focus on that last option first then—I'll mock up a version today

**Comment by agingoldseco** [comment]
I could see it just being something like this, 12px font 

<img width="552" alt="Screen Shot 2021-10-13 at 1 02 01 PM" src="https://user-images.githubusercontent.com/90645922/137180414-dffbd576-82a3-4746-8af1-a0d245b801b1.png">

**Comment by swissspidy** [comment]
cc @barklund

**Comment by swissspidy** [comment]
Oh apparently we have #9193 specifically for adding the time in trim mode.

So we can handle that part there.

Still would be nice to generally display duration somewhere, not just when in trim mode.
