### ISSUE TITLE
Increase link icon dimensions

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9396]
## Feature Description

Right now we crop link icons and page attachment icons to 32x32px:

https://github.com/google/web-stories-wp/blob/7c1bec55dd799096afdefd79f0f47ab5052d72aa/packages/story-editor/src/components/form/linkIcon.js#L65-L68

But in the editor we display them at 54x54px, causing them to appear pixelated in the design panel:

<img width="277" alt="Screen Shot 2021-10-12 at 4 23 50 PM" src="https://user-images.githubusercontent.com/841956/137036044-29a6e853-966a-4bfd-b34c-2c70c394d445.png">

We could safely crop them to something larger like 96x96 to make them more crisp and future proof in case the icons ever need to be displayed in larger size.

**Comment by hamza-arshad** [comment]
@swissspidy can I give this a try? Starting pointers would be helpful as always. Thanks.

**Comment by miina** [comment]
Potential approaches for the issue (from discussion with Pascal):
- Adjusting the design to display the correct size in the panel as well
- Increasing the crop size but force-cropping to 32x32px for frontend output

The first option seems simpler and might be good as well for displaying the accurate view for the user but needs confirming with UX probably to verify if it looks ok.

@swissspidy Let me know if you had other thoughts here. Moving the issue away from the Review column meanwhile.

**Comment by swissspidy** [comment]
Thanks for following up on that! Totally forgot about it.

Let's sync with Amy to decide on path forward.

**Comment by agingoldseco** [comment]
I don't think the icon needs to _look_ bigger in the display, but I'm all for it looking crisper—can be okay with whatever it takes to do that. I'm a little unclear on what's needed from me though, are you asking for it to be bigger in the display?

**Comment by swissspidy** [comment]
We could either make it crisper _or_ smaller—to be more aligned with actual appearance in the story

**Comment by agingoldseco** [comment]
Crisper is my vote :)
