### ISSUE TITLE
Pre-Publish Checklist: Improve video resolution check description

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9400]
## Feature Description

Both the title and the description say basically the same thing, which doesn't really make the description useful.

![Screenshot 2021-10-11 at 10 58 38](https://user-images.githubusercontent.com/841956/137125218-32d927ef-9b5b-4e50-b5be-25325d6dd074.png)

Suggesting the following wording:

**Title:** `Increase video resolution`
**Description:** `Ensure your video has a minimum resolution of 480p (852×480px).`

If there are multiple offending videos (n > 1), use `Ensure your videos have a minimum resolution of 480p (852×480px).`

## Additional Context

* This came from user feedback through support.

**Comment by BrittanyIRL** [comment]
@choumx or @gajasinski  can you verify that you're ok with the above language Pascal is suggesting?

**Comment by gajasinski** [comment]
LGTM

**Comment by dreamofabear** [comment]
Nit: Consider using `480x852px` to represent portrait videos.

**Comment by BrittanyIRL** [comment]
![Screen Shot 2021-10-18 at 4 16 42 PM](https://user-images.githubusercontent.com/10720454/137818988-cbc729c0-42fc-44e0-b079-2b22872a8f06.png)

Combined Pascal and Will's copy into this - which i think works regardless of video count.

**Comment by BrittanyIRL** [comment]
use #9440 to test this copy change
