### ISSUE TITLE
Page Templates: Remove confirmation dialogue code

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9414]
## Bug Description

Edit: The behaviour described below is actually expected behaviour, however, we still have the leftover code for the confirmation dialogue that should be removed.

Originally reported bug (but expected behaviour):
`useTemplateActions` is supposed to ask for user confirmation when applying a page template on the current page if it's not empty.

The code for that is there.

However, no such confirmation step is happening.

## Expected Behaviour

~Confirmation dialog should appear.~~

Confirmation dialogue should not be in code since it's not used.
## Steps to Reproduce

1. Add some element to the current page.
2. Select a page template to apply
3. Don't get any confirmation dialog

## Additional Context

- Plugin Version: 1.13.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

**Comment by miina** [comment]
This is intended behaviour, see https://github.com/google/web-stories-wp/issues/9415#issuecomment-944170038 for more details.

**Comment by swissspidy** [comment]
Then we should remove all the code that deals with confirmation, e.g.:

https://github.com/google/web-stories-wp/blob/e7fc7071543bc4a768d15e653c9baf50a8c814a2/packages/story-editor/src/components/library/panes/pageTemplates/useTemplateActions.js#L38-L43

**Comment by miina** [comment]
Yep, we should def remove the leftover code.

**Comment by miina** [comment]
@BrittanyIRL Assigning this to Pea pod as well as it's related to Page Templates.
