### ISSUE TITLE
Page Templates: Clean up replacing current page code

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9415]
## Bug Description

Edit:
The bug originally reported is expected behaviour, however, there seem to be leftovers of the previous logic and/or confusing naming in the code that should be adjusted to the expected logic of adding a new page instead of replacing. See comments below for details.

Original reported bug:
`useTemplateActions` is supposed to apply the page template on the current page.

Instead, the code is always adding a new page.

## Expected Behaviour

~The current page should be replaced (with confirmation if necessary, see #9414) with the page template~

The naming in code should reflect what it actually does.

## Steps to Reproduce

1. Apply page template
2. See new page being added

## Additional Context

- Plugin Version: 1.13.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

**Comment by miina** [comment]
@swissspidy This behaviour is as intended. Initially, with the first iteration, it replaced the page, however, it was changed to not ask a confirmation and instead add a new page using the template instead.

[See Frame 11 in Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7082%3A531898).

Q: Where did the information come that it should replace the current page? (To avoid confusion in the future, this has been brought up as an issue once before as well)

**Comment by swissspidy** [comment]
@miina Even if my current page is completely empty, it always generates a new page? 🤔 

Then why does this code use the `replaceCurrentPage` action?

https://github.com/google/web-stories-wp/blob/e7fc7071543bc4a768d15e653c9baf50a8c814a2/packages/story-editor/src/components/library/panes/pageTemplates/useTemplateActions.js#L31-L56

**Comment by miina** [comment]
> Even if my current page is completely empty, it always generates a new page? 

Yep, that was a UX decision and is specifically the case brought out in Figma. Probably the empty page case was for consistency. 

I'm not sure really what's going on with the code without looking into it in more detail, perhaps `replaceCurrentPage` actually adds a new page as the current page and doesn't replace the existing one? (Not that it would make sense from naming perspective).

But anyway we should have a cleanup issue to remove the existing confirmation-related code and look into this part as well to make the code/naming less confusing.

**Comment by swissspidy** [comment]
Feel free to use #9414 for cleaning up the confirmation dialog and this one for cleaning up the replacement code.

Making this code more self-explanatory would help a lot to avoid confusion like this.

**Comment by BrittanyIRL** [comment]
@miina  - happy to take this too, we're doing this epic right now: https://github.com/google/web-stories-wp/issues/9089 and these tickets for page template bugs/code refactor would play nicely after we finish up the perf gains / adjust the grids. are you ok with me taking all of these?

**Comment by miina** [comment]
@BrittanyIRL Of course, thanks for flagging this.
