### ISSUE TITLE
Improve page preview thumbnails

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9420]
## Feature Description

Now that we generate preview thumbnails with `html-to-image`, is there any way we can fix the **horrible** appearance of these previews when text elements are involved?

The browser can’t display text with such a low text size.

Perhaps we could fix this by supplying `width`/`height` or `canvasWidth`/`canvasHeight` to `htmlToImage` or something to create a larger image and then downscale it?

![Screenshot 2021-10-14 at 12 53 26](https://user-images.githubusercontent.com/841956/137716808-7a7b933c-9221-4df3-9692-e4b9bef5ad92.png)

![Screenshot 2021-10-14 at 12 52 29](https://user-images.githubusercontent.com/841956/137716810-ee2350f4-1f78-4c1d-94a3-c8a6ab97738a.png)

https://github.com/google/web-stories-wp/blob/d6c955e7d669b576b08346fb18742eedf0cdf0f7/packages/story-editor/src/components/carousel/pagepreview/index.js#L124-L131

**Comment by miina** [comment]
@swissspidy Is this happening in any browser? Are there specific steps to reproduce this? I added some pages using templates with lists and currently seeing the previews as expected:
<img width="239" alt="Screenshot 2021-10-19 at 11 32 35" src="https://user-images.githubusercontent.com/3294597/137873395-b394bc67-76ce-4cc2-91dc-4054fa78a4d8.png">

**Comment by swissspidy** [comment]
I've only tested it in Chrome so far.

It happens when I edit some existing stories on our wp.stories.google WP instance, where we currently have v1.13.0 installed.

Examples:

![Screenshot 2021-10-19 at 11 08 23](https://user-images.githubusercontent.com/841956/137879327-5551c34e-5cd3-48f8-85f4-fba4ad5225b7.png)
![Screenshot 2021-10-19 at 11 06 42](https://user-images.githubusercontent.com/841956/137879329-3a566b46-3bee-4ac8-81b1-317ac1660e42.png)

It also happens when creating a story from a template:

![Screenshot 2021-10-19 at 11 09 38](https://user-images.githubusercontent.com/841956/137879566-bcb69e6b-f1c2-4550-9735-04d7d76376c6.png)

**Comment by miina** [comment]
@swissspidy Is this something you can reproduce in the QA environment as well? E.g. I tested with the same template + Chrome in the QA environment and the preview seems to show OK. Or does it happen in the wp.stories.google instance only?
<img width="292" alt="Screenshot 2021-10-19 at 13 07 00" src="https://user-images.githubusercontent.com/3294597/137889235-f8a51fa1-319b-43cb-af8f-964996ea7f9c.png">

**Comment by swissspidy** [comment]
Yes, I also see it there.

**Comment by barklund** [comment]
@swissspidy Is this still an issue?

**Comment by swissspidy** [comment]
Thanks for the ping!

From what I can see now, things look much better than last year 🎉  See how the text in the thumbnails is not giant anymore:

![Screenshot 2022-08-24 at 15 45 10](https://user-images.githubusercontent.com/841956/186434449-9af7992f-b6d9-40f3-a2d1-0c14c90db33a.png)

Aside: multi-page canvas is super nice when working with a template like that.

I suppose we can close this 🎉
