### ISSUE TITLE
Right Click Menu: Right Click from Element to Element Discovery

### ISSUE THREAD

**Issue by maxyinger** [swissspidy/web-stories-wp#9426]
Currently the right click context menu opens up based on the selected element. This ticket is to:
1. Explore passing in an element to the callback handler to generate the menu items vs generating them based on the selected element
2. Explore alternatives to the fullscreen clickable background element approach to dismiss the context menu. The new approach should be geared towards allowing for right clicking between elements, but not cause any regressions from the previous approach.

Task 1 should be pretty straight forward to implement, however, task 2 could be a rabbit hole. Mainly setting this up as a 3 point Discovery ticket in case there's no fruitful approaches for task 2 (which is very much a possible outcome).

Please try to time box this. It's okay if nothing gets discovered. This is just a possible UX enhancement, so it's not worth spending a week on if initial discovery seems like there's no possible paths

**Comment by csossi** [comment]
Verified in QA
