### ISSUE TITLE
UI Simplifications: Border Panel

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9461]
## Feature Description
See [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=10250%3A436799).

- [ ] Update the design based on Figma for locked and unlocked status
- [ ] Add Eyedropper next to the color input
- [ ] Update the opacity icon (it was adjusted a bit since initially adding it)

<img width="248" alt="Screenshot 2021-10-20 at 12 17 42" src="https://user-images.githubusercontent.com/3294597/138065445-c13543a8-319a-499b-a6ab-985cec2aebab.png">

**Comment by csossi** [comment]
Verified in QA
