### ISSUE TITLE
UI Simplifications: Text Panel

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9462]
## Feature Description
See [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=10250%3A435667)

- [ ] Remove Text Box as separate panel and move all fields under the Text panel
- [ ] Create a subheading for the Text box sub-panel.
- [ ] Update style for pills per Figma
- [ ] Add eyedropper next to the color input (might make sense to add it to the color input directly since it will be like this everywhere.
- [ ] Move Text Magic button to the Text panel heading (hide when collapsed)

Note: Saved Styles will be worked on in a separate issue.

**Comment by csossi** [comment]
Verified in QA
