### ISSUE TITLE
UI Simplifications: Saved Styles

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9463]
## Feature Description
See [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=10250%3A435820)

- [ ] Move Saved styles to the Text Panel using a subheading.
- [ ] Create a popup for displaying Saved Styles (behaves the same way as the Color Picker)
- [ ] Only display one row of styles in the panel, and use the popup for the rest of the styles when clicking on "More styles"
- [ ] Adjust the style when there are no Saved Styles
- [ ] Ensure the Edit mode (now only inside the popup) and Adding style work as previously.

<img width="343" alt="Screenshot 2021-10-20 at 12 28 01" src="https://user-images.githubusercontent.com/3294597/138067168-3b9afcf6-32c2-4402-8f4d-db0790404155.png">

**Comment by csossi** [comment]
Verified in QA
