### ISSUE TITLE
UI Simplifications: Colors

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9464]
## Feature Description
See [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=10250%3A437034)

- [ ] Change "Style" panel to "Color" for Shape element
- [ ] Remove Saved colors panel from Design Panel
- [ ] Change "Story colors" to "Current story" and reorder the sections
- [ ] Allow saving colors directly from the "Basic" view of the Color Picker by clicking the `+` icon.
- [ ] Add Edit mode to the Color Picker for Current/Saved Colors. When clicking on a Default color in edit mode, it should work as usually + exit the edit mode.
- [ ] Change "Add" in the Custom view to "Add to Saved Colors"
- [ ] Add Eyedropper to the Basic view.

**Comment by csossi** [comment]
Verified in QA
