### ISSUE TITLE
UI Simplifications: Media panels

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9465]
## Feature Description
See [Figma for background media](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=10250%3A436589) and for [accessibility panel](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=10250%3A436662)

 ~Update the style for Removing Background media button~ That was an accidental difference, it can stay the same! - Amy
- [ ] Filter Panel: Add eyedropper next to the Color input (not seen in Figma but it was confirmed by UX that it should be like this everywhere. Makes sense to add it to the Color input directly if not done elsewhere.
- [ ] Accessibility panel: Add description above the textarea for both Video and Image (instead of the current placeholder).

**Comment by delowardev** [comment]
@miina Filters panel already has an opacity controller (eyedropper) but the Page Background panels don't.
- [screenshot filter panel](https://i.imgur.com/VV2gV2r.png) 
- [screenshot page bg](https://i.imgur.com/l34T4Dt.png)

**Comment by miina** [comment]
@delowardev

Page background panel is not supposed to have opacity.
Eyedropper is a tool for picking a color from the page and is not related to opacity.

Also, please note that any issue for UI Simplifications might still change as of current moment, these are being prepared to be worked on for the next Sprint starting on Monday.

**Comment by delowardev** [comment]
@miina There are some places that could break UI by adding EyeDropper ( see screenshot), so I'm thinking of adding a boolean prop `eyeDropper` to the color input with the default value of `false`, so it can be enabled wherever needed.

![Screenshot](https://i.imgur.com/LDiDeCY.png)

**Comment by miina** [comment]
@delowardev Thanks for checking about it. This icon will be moved within #9462, eventually, all color inputs will have eyedropper as part of it.
Feel free to add `false` for `hasEyedropper` now as you suggested, we can remove it and make it default when working on #9462.

About the TextArea component: it looks like currently we are not using the Label anywhere at all, and the Hint either. Since now we'll have two fields having description above the TextArea, it might generally make sense to modify the TextArea component to allow placing the description (or Hint) above the field and adjusting its style (instead of modifying the label) and continuing using `aria-label` for the label. I'm still confirming the details with UX about it.

We are currently using the TextArea component in one more place: Story Description in the Document panel. In case of the story description, we're just using a separate `Text` to display the description, if you prefer, feel free to do the same until we confirm the details with UX.

Note that if you change the TextArea component, [the Storybook](https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-components-textarea--default) would also need an update to reflect all the changes.

**Comment by csossi** [comment]
Not seeing the dropper re: tint
![image](https://user-images.githubusercontent.com/16945664/139468699-cc527c83-bc9b-4e4e-ae67-2178d1434323.png)

**Comment by miina** [comment]
> Not seeing the dropper re: tint

Merging this regardless since I can definitely see the eyedropper for Tint and it's a bit hard to QA this PR currently. I'll follow up with a separate issue if for some reason the eyedropper should not appear in QA after merging.
