### ISSUE TITLE
Enable Media Hotlinking by default

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9466]
## Feature Description
Once the Proxy related issues have been completed, we can enable the feature by default.

- [ ] Enable the feature (both Hotlinking and CORS Proxy)
- [x] Add Karma tests if/where needed

Note: more issues might need to be resolved before enabling the feature once it gets tested.

**Comment by swissspidy** [comment]
@miina So the CORS proxy needs to be finalized before the feature can be enabled by default. But Karma tests can already be added now. There's no reason not to. So that's best done in a separate ticket though.

**Comment by miina** [comment]
@swissspidy Thanks for the update!

I guess https://github.com/google/web-stories-wp/issues/9369 includes unit tests (both PHP and JS) but not Karma, right? Will create a separate issue for Karma tests for Prometheus then.

**Comment by swissspidy** [comment]
Yes, #9369 only includes unit tests, and mostly for the CORS proxy itself, not for hotlinking in general.

**Comment by csossi** [comment]
Verified in QA
