### ISSUE TITLE
Use native eyedropper API if available

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9478]
## Feature Description

The EyeDropper API enables developers to use a browser-supplied eyedropper in the construction of custom color pickers.

Chrome has started shipping this new API in v95. See https://www.chromestatus.com/feature/6304275594477568

It would be nice if we could use that one if available, so we don't have to use html-to-image for it.

Demo:

https://twitter.com/tomayac/status/1432969851811794944
https://codepen.io/matanbobi/pen/GREoZvo

**Comment by timarney** [comment]
Any idea why the EyeDropper doesn't exist on window ?

Web stories browser window - doesn't exist
![Screen Shot 2022-06-17 at 2 53 11 PM](https://user-images.githubusercontent.com/62242/174385760-051e7b8c-93ee-48e8-95a1-fdf95ecdeaa8.png)

New Browser window
![Screen Shot 2022-06-17 at 2 52 17 PM](https://user-images.githubusercontent.com/62242/174385674-effff59d-0b50-46e0-b499-9cc2ffd66fbc.png)

Testing here outside of  web stories and it works:
https://codesandbox.io/s/restless-wildflower-g6z22m?file=/src/useEyeDropper.js

**Comment by felipebochehin87** [comment]
![eyedropper chrome.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/18f8438f-376a-4f3f-8544-0e9e2e4ad368)

**Comment by felipebochehin87** [comment]
Thanks @swissspidy . In this case, the changes look good. Thanks!
