### ISSUE TITLE
Use CORS Proxy for Link Icons

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9492]
## Feature Description

For page attachments and links we automatically fetch the site's favicon to display it.

That works fine on the frontend, but in the editor, when video optimization is enabled (and thus cross-origin isolation), it often doesn't work because of lacking CORS headers:

![Screenshot 2021-10-21 at 16 49 47](https://user-images.githubusercontent.com/841956/138302804-901675ac-5ce4-46a1-915c-510b9e801c18.png)
![Screenshot 2021-10-21 at 16 49 33](https://user-images.githubusercontent.com/841956/138302808-484275da-0552-4b3b-9c36-46e5084af668.png)
![Screenshot 2021-10-21 at 16 49 28](https://user-images.githubusercontent.com/841956/138302809-57680dd9-9f01-465c-8f16-493f57e48631.png)

By using our new CORS proxy for that we could easily fix this.

Only needed when video optimization is enabled though. Otherwise it works fine.

**Comment by csossi** [comment]
Verified in QA
