### ISSUE TITLE
Page Attachments getting `rel="noreferrer"` attributes

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9494]
## Task Description

Background:

In #4732 we ensured that links opened in a new tab, adding `target="_blank"` and `rel="noreferrer"`.

We also added some PHP code to always add `rel="noreferrer"` to any `<a>` tags if missing.

Recently we migrated page attachments from `<amp-story-page-attachment>` to `<amp-story-page-outlink>`, which meant that actual `<a>` tags would get added to the page.

So somewhat accidentally, that causes page attachment links to now also get `rel="noreferrer"`.

This is confusing for some users who now now don't know how much traffic their blog posts get from their stories. (Example report: https://wordpress.org/support/topic/utm-code-question/)

* Should we keep this behavior as-is?
* Should we perhaps remove `rel=noreferrer` if the link target is on the same origin as the story?
* Should we just give users an option to add this themselves if desired? (see #4440)

**Comment by swissspidy** [comment]
@choumx Would love to hear your thoughts on this

**Comment by dreamofabear** [comment]
Avoiding `rel=noreferrer` on same-origin links SGTM. Context: https://web.dev/external-anchors-use-rel-noopener/

Separately, supporting `rel=sponsored` and `nofollow` sounds reasonable (e.g. new checkboxes in the Link panel). I can't think of a good use case for `ugc`.
