### ISSUE TITLE
Template Search

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9508]
## Feature Description

Let's give the explore templates view a search input (just like my stories). Searching should be based on template tag metadata. Additional tickets will be created to update tags to include color families and titles.

## Alternatives Considered

Considered a search component that allows multiple search terms - like the `tags` in the editor's taxonomy section, decided it would be overkill for a first round. 

## Additional Context

Figma: https://www.figma.com/file/Ha6kk9yXDN1rB80NzcDf2J/_Editor---Design-System-%22Style-Guide%22?node-id=467%3A13745 
![Screen Shot 2021-10-22 at 11 46 54 AM](https://user-images.githubusercontent.com/10720454/138507438-ae0883cb-bf66-42b5-86ab-8dcb966ae432.png)

## Acceptance Criteria 
- Ability to search templates by metadata tags
- New karma tests
- telemetry added to track what users are searching

**Comment by swissspidy** [comment]
Why don't we allow searching the title or description? 🤔

**Comment by BrittanyIRL** [comment]
> Why don't we allow searching the title or description? 🤔

this is the first step in figuring out what all should be searchable out of a template. I think in most cases the title comes up in some capacity in the tags. This started out as 4 different "filters" that we realized actually have no design done and also have not been really asked for? So Amy is going to do some user research about what's useful and we'll go from there. For now, just doing a generic search. So, we can add title and description to it for sure, it's just something that people (eng, design, product) are kinda assembling the tracks for as the train is in flight. Not ideal, and I'll admit the oversight on my part thinking the mocks were done and that we could make do - but really the original filters aren't really applicable to our template library as is. 

Anyways, that's a bit of background. Quick answer is: because we met with design last week and agreed to start with tags and colors. We're meeting again today though and will probably discuss next steps.
