### ISSUE TITLE
Dashboard: Template Preview Focus Resets

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9537]
When you're using a keyboard to navigate the single template views in the dashboard the focus resets in a less than ideal way. Morten outlined it as such: 
`When using the keyboard to navigate between templates on the single template view (the right-most or left-most arrow buttons), focus is reset to the close button. Focus should remain on the same button. Focus should only move to the close button the first time the single template page is loaded, not every time the single page template changes to a different template` 

which is pretty on spot. We can improve this.

**Comment by csossi** [comment]
Verified in QA
