### ISSUE TITLE
Layer Panel: Pointer should only be cursor when title is hovered

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#9543]
## Bug Description

In the layer panel: the mouse cursor should only change to a hand when the collapsed state icon is highlighted — that is, when the title label is hovered over.

## Steps to Reproduce

Hover the panel's header.

## Screenshots

![pointer](https://user-images.githubusercontent.com/22185279/138968726-442d164d-0639-4771-9dff-b7ecb3c9e876.gif)

## Additional Context

Originally brought up by @choumx in bug bash. Mentioned tangentially: 
> Corollary: we should increase the drag-to-resize activation area to the rest of the header (remaining parts that don't trigger collapse/expand)
> In other words: when the mouse is hovering over any part of the layers panel header, there's always an action that can be taken (either collapse/expand OR resize)

This needs more discussion with Amy and Will before it's actionable so we're all clear on what's going on.

- Plugin Version: 1.14.0-alpha
- WordPress Version: 5.8.1
- Operating System: Mac OSX Sierra
- Browser: Chrome

**Comment by swissspidy** [comment]
So we don't allow clicking anywhere anymore to collapse it?

**Comment by samwhale** [comment]
> So we don't allow clicking anywhere anymore to collapse it?

Not sure - let me check with @agingoldseco

**Comment by agingoldseco** [comment]
Was clicking anywhere to close/open available for layers and panel sections before? If so, I do think it should still do that—if not, I think it should now.

**Comment by swissspidy** [comment]
Hmm I might have misremembered.

Only clicking on the title itself currently collapses the panels. But the pointer cursor is shown even beneath the text. So that's confusing.

If clicking anywhere there should collapse the panel, then the cursor should still be a pointer (hand) there.

Also: this applies to **all panels**, not just the layers panel.

**Comment by dreamofabear** [comment]
I think it'd be nice if we made the rest of the header (outside of the title) an activation area for drag-to-resize.

It would reduce the amount of mouse precision required to resize the Layers panel today.

**Comment by swissspidy** [comment]
Screencast of how clicking next to "Page Attachment" does nothing, despite the pointer cursor:

https://user-images.githubusercontent.com/841956/139158182-1612a79f-13f3-4b9e-8c11-45e809f01158.mov

**Comment by csossi** [comment]
Verified in QA
