### ISSUE TITLE
Layer Panel: Hover state of icons when a layer is selected

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#9544]
## Bug Description

Layer Panel: The hover color of the icons when a layer is selected is too dark. @agingoldseco would like us to lighten it up a little.

- [x] Color TBD

## Expected Behaviour

Change the hover color of the icons when the layer is selected

## Steps to Reproduce

1. click a layer in the layer panel
2. Hover an icon like `delete` or `copy` on that layer

## Screenshots

![image](https://user-images.githubusercontent.com/22185279/138967649-d507990c-ac4a-4537-bdc2-28d074267393.png)

## Additional Context

- Plugin Version: 1.14.0-alpha
- WordPress Version: 5.8.1
- Operating System: Mac OSX Sierra
- Browser: Chrome

**Comment by BrookeGraham** [comment]
@agingoldseco would like gray 70 to be used for this. ie. #393D3F

**Comment by csossi** [comment]
Verified in QA
