### ISSUE TITLE
Smart Text Color re-triggering includes the element itself to the reference image

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9546]
## Bug Description
When generating an image for contrast calculation, the text element itself is also included into the image, that causes unexpected and inaccurate results.

## Expected Behaviour
The element itself should not be included into the generated image.

## Steps to Reproduce
1. Add a text element on a white background
2. Click on the "Magic wand" button for auto-styling.
3. The text should stay black as it is but it gets a highlight instead.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Verified in QA
