### ISSUE TITLE
Two videos with captions compete for the screen

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9553]
## Bug Description
Originally reported by @LuckynaSan & @BrookeGraham 
When two videos are on a page and both have captions, the captions display over each other. 

It was further noted that in Safari, the two sets of captions stack on top of each other
![image7](https://user-images.githubusercontent.com/58738530/139122089-ffad9cda-1548-4268-b4d5-1e1de83f2fc2.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
What is the exact bug here / what behavior did you all expect? 🤔

**Comment by LuckynaSan** [comment]
How should captions appear when there are multiple videos on the page with captions?  I am not sure how common of a use case it is to have multiple videos on the same page, but if those multiple videos each have captions, how do we know which captions apply to what video?

**Comment by swissspidy** [comment]
> how do we know which captions apply to what video?

We don't. And it's not a use case we aim to cover.

In such a case, if you'd turn on sound you would not understand a single thing either because of overlapping sound.
