### ISSUE TITLE
Page Templates: Focus disappears between filters and page buttons

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9554]
## Bug Description
originally reported by @BrittanyIRL 

When tabbing from the filters for default templates to individual template pages there’s 1 tab where nothing shows as focused, this is the whole grid being focused. It should probably show the whole grid focused here so that it doesn’t appear lost. (found in firefox but probably not browser specific) 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrookeGraham** [comment]
Just FYI. This is only happening in Firefox. Tabbing is working as expected in Chrome and Safari.

**Comment by BrookeGraham** [comment]
It is also present on Firefox in the saved templates.

**Comment by csossi** [comment]
Verified in QA
