### ISSUE TITLE
Layer Panel attached to side panel has a scroll bar that interferes with the UX

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9555]
## Bug Description
Originally reported by @agingoldseco 
When layer panel is dragged to fit entire side panel, a scrollbar appears to the right and overlaps it

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Duplicate of #9542?

**Comment by bmattb** [comment]
confirmed, closing
