### ISSUE TITLE
Adaptive Text Colours : 2nd click doesn't undo the first clicks action

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9556]
## Bug Description
Originally reported by @BrittanyIRL 
After selecting the Adaptive Text Colour magic wand button, if the user doesn't like the result, re-clicking that button doesn't revert the change.
![image4](https://user-images.githubusercontent.com/58738530/139126536-0bd864e8-ceb9-42b0-810f-9cbb17d3f25f.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by bmattb** [comment]
this may be a dupe of https://github.com/google/web-stories-wp/issues/9546

**Comment by miina** [comment]
@bmattb The second click is not supposed to undo anything, this is not an issue.
