### ISSUE TITLE
Enable Delete & Duplicate action on a multi-layer selection

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9558]
## Feature Description
Originally reported by @LuckynaSan 

When applying an action (delete/duplicate) on a bulk selection of layers, the action only applies to one layer instead of all the layers selected. For example, select several layers from the panel and click delete. Notice only one layer element deleted. Note: delete key on keyboard works for bulk selection.

**Comment by BrittanyIRL** [comment]
Dupe of #9562
