### ISSUE TITLE
Layer Panel: Circle shape not looking circular

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#9559]
## Bug Description

Circle shape preview in layer panel gets cut off.

## Expected Behaviour

Circle shape preview in layer panel should look circular.

## Steps to Reproduce

1. Add circle shape to story
2. Look at layer panel

## Screenshots

![image](https://user-images.githubusercontent.com/22185279/139132280-602e5504-399a-4a80-9511-6c997f0d626d.png)

## Additional Context

- Plugin Version: 1.14.0-alpha
- WordPress Version: 5.8.1
- Operating System: Mac OSX BigSur
- Browser: Chrome

**Comment by csossi** [comment]
Verified in QA
