### ISSUE TITLE
Layers Panel Focus Drag 

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9561]
## Bug Description
Originally reported by @Trapsta and @agingoldseco  in bug bash.

When you drag the layers panel to expand it or shrink it and you are done dragging it, the blue focus outline sticks around, when you're not dragging anymore that blue outline should go away. 

## Expected Behaviour

I recognize that it's still in _focus_ which is why that blue outline is appearing, but this one situation is unique I'd say since it's really just for people using a mouse (layers panel is not navigable by keyboard). So perhaps we don't need that blue outline at all? 

## Steps to Reproduce

Drag the layers panel open a bit then stop dragging, see outline.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Verified in QA
