### ISSUE TITLE
Bulk Delete/Duplicate Layers

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9562]
## Feature Description

Originally brought up by @LuckynaSan  in bug bash:
> When applying an action (delete/duplicate) on a bulk selection of layers, the action only applies to one layer instead of all the layers selected. For example, select several layers from the panel and click delete. Notice only one layer element deleted. Note: delete key on keyboard works for bulk selection

The key detail here being that you can bulk delete with the keyboard but not anywhere within the editor as a button. Do we want this to be the case?

**Comment by BrittanyIRL** [comment]
we just implemented a new right click menu for multiple elements selected to duplicate a group and clear a group's (allowed/consistent) styles. We _could_ add in 'delete' as a third option in this menu. @choumx @gajasinski @agingoldseco  - I'll leave this in your court!

**Comment by agingoldseco** [comment]
I wouldn't mind adding Delete, but it's so similar to Copy and Paste that were gotten rid of cause they seemed redundant with keyboard shortcuts. BUT this might also help avoid the issue Will brought up a while ago of people thinking the trash can by the canvas is for elements and not the canvas.

**Comment by BrittanyIRL** [comment]
Coming back to this. Thoughts on adding `delete`?  @agingoldseco @aaskedall 

it could _just_ be on bulk or it could be consistent through all menus. 

<img width="389" alt="Screen Shot 2022-01-11 at 10 44 00 AM" src="https://user-images.githubusercontent.com/10720454/148994334-0f173e64-035a-4733-9c54-3da15d63cfe0.png">
