### ISSUE TITLE
Save Custom Page Templates as Images

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9574]
## Description 

When a page is saved as a custom page template, we should use the same `html-to-img` pattern as in the carousel to get an image of that page and save that image to media. 

This is going to need some back and forth between back and front end to make sure that the new data is getting saved properly. Probably we can use the media optimization flow as a starting place for how to store custom page template images without making them part of the main media gallery. Ideally,  the custom page template now has a media id for that img of the page and if that media is available it'll render the img instead of loading a preview of the page. 

If a custom page template loads in the panel and doesn't have an image yet then we should take a snapshot of that preview once it's loaded and save it to media as well. 

## Acceptance Criteria 
- images getting saved in media of custom page templates 
- if existing custom page templates have no image yet, when those load, images are added to media

**Comment by swissspidy** [comment]
The main obstacle right now seems to be how we always get an image with the right size. The canvas size changes depending on your browser size after all, and can be zoomed in as well.

**Comment by kkalarickal** [comment]
Tested via [stories-qa](https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=15778&action=edit#page=%252269e5c7d1-69fd-4c7b-a84d-22f5f6cc73e2%2522) running #9584

Status: Passed 

Notes:
- verified that custom page template is saved as an image for a page containing video/image/gif/shapes/text
- confirmed that the image can be opened/downloaded as a jfif file format
- checked the use of saved template to create new page
- checked with multiple saved templates
- saved template with different zoom levels to ensure same sized image was saved

![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/d483438f-9ebd-433f-a2d5-0162a764668f)

Callout: 
1. When a page that was added as a template is deleted, I was expecting the media library to be cleaned up as well. However, when i open the media-library, I see all the images that were captured of the page, which had subsequently been deleted from the template list, are still present in wordpress.

![image](https://user-images.githubusercontent.com/3719412/148724367-36440e59-9860-4284-88ab-69a0ef1ba266.png)

2. On some templates, it took a long time to right-click and open the saved image.

Cc: @swissspidy

**Comment by swissspidy** [comment]
> When a page that was added as a template is deleted, I was expecting the media library to be cleaned up as well. However, when i open the media-library, I see all the images that were captured of the page, which had subsequently been deleted from the template list, are still present in wordpress.

Good callout :-) 

That's actually a bug, which I'll fix real quick.

> On some templates, it took a long time to right-click and open the saved image.

Interesting. Perhaps the image wasn't yet generated when you clicked on it.

Not really a common user action to save the image there, so I don't think we have to worry about that :-)

**Comment by kkalarickal** [comment]
> That's actually a bug, which I'll fix real quick.

Will it be part of this PR ? I can test it if you let me know when its ready.

> Not really a common user action to save the image there, so I don't think we have to worry about that :-)

Totally .... i guess its "we report, you decide" with some of these call outs ;)

**Comment by swissspidy** [comment]
@kkalarickal Yes, part of this PR. I just fixed it, so please try again now 👍  It works well here
