### ISSUE TITLE
Media: Do not store transient data on resource objects

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9577]
## Feature Description

We currently store some transient flags on media resources when performing some tasks on them, e.g. `isTranscoding`, `isTrimming`, `isMuting`, and even `local`. That's really not the best way to handle this, especially when a resource is used in multiple places.

Storing this transient data on the resources themselves might also cause issues with the edit history, see https://github.com/google/web-stories-wp/issues/9550#issuecomment-953828865. Another good reason to change this.

**Idea**

Export some helper function(s) in `useMediaUploadQueue` to get a specific resource's state, and re-export that in the local media provider for use by the rest of the editor.

Perhaps something like this:

```js
// in packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js

isResourceUploading: (resourceId) =>
  state.queue.some(
    (item) =>
      !['UPLOADED', 'CANCELLED', 'PENDING'].includes(item.state) &&
      item.resource.id === resourceId
  ),
isResourceTranscoding: (resourceId) =>
  state.queue.some(
    (item) =>
      item.state === 'TRANSCODING' && item.resource.id === resourceId
  ),
isResourceMuting: (resourceId) =>
  state.queue.some(
    (item) => item.state === 'MUTING' && item.resource.id === resourceId
  ),
isResourceTrimming: (resourceId) =>
  state.queue.some(
    (item) =>
      item.state === 'TRIMMING' && item.resource.id === resourceId
  ),
```

So we don't have to check for `resource.isTranscoding` and the like anymore.

Then, update all the reducers in there which currently set `isTranscoding` et al on the resources. We don't need that anymore.

**Note:** need to update `createResource` and the `Resource` JSDoc accordingly.

**Related:** We should probably generate a resource ID with `uuid` in `getResourceFromLocalFile` and `getResourceFromUrl` so that all resources have an ID. Just to make our lives easier in the future.

**Comment by spacedmonkey** [comment]
Reposting this https://github.com/google/web-stories-wp/pull/9758#discussion_r754113046 as I think it is related. 

I think we should remove the `local` property from resources. We can replace it with a new property called `source`. When a media element is uploaded, instead of changing local from `true` / `false`, you could just change source from `local` to `library`. This makes gets rid of a property that is not useful outside the upload process and adds a useful field for the future. This would of course require a migrate but is possible. 

Thoughts @swissspidy

**Comment by swissspidy** [comment]
Could you open a separate ticket for this suggestion? Thanks!

**Comment by spacedmonkey** [comment]
Here are some important places that need to updated. 

https://github.com/google/web-stories-wp/blob/25d43b402e39f46de36ec4636a1893f8749b932e/packages/story-editor/src/components/library/panes/media/common/mediaElement.js#L221

https://github.com/google/web-stories-wp/blob/dae19afa13198b2c121f438176497f80b6a45ea4/packages/story-editor/src/components/panels/design/videoOptions/videoOptions.js#L105-L115

https://github.com/google/web-stories-wp/blob/25d43b402e39f46de36ec4636a1893f8749b932e/packages/story-editor/src/app/media/utils/useProcessMedia.js#L114-L121

https://github.com/google/web-stories-wp/blob/25d43b402e39f46de36ec4636a1893f8749b932e/packages/story-editor/src/app/media/utils/useProcessMedia.js#L195-L202

https://github.com/google/web-stories-wp/blob/25d43b402e39f46de36ec4636a1893f8749b932e/packages/story-editor/src/app/media/utils/useProcessMedia.js#L273-L284

https://github.com/google/web-stories-wp/blob/f923a0b5fe257641718d07fc25fd68686215e8e5/packages/story-editor/src/components/checklist/checks/videoOptimization.js#L57-L65

https://github.com/google/web-stories-wp/blob/833cc68bd99067cc2288f7026a32f2f0060ff9b8/packages/story-editor/src/components/library/panes/media/common/mediaElement.js#L261-L263

https://github.com/google/web-stories-wp/blob/721a329f2a1f44e18c11721035244a17e94c0571/packages/media/src/canTranscodeResource.js#L23-L28

**Comment by spacedmonkey** [comment]
> Could you open a separate ticket for this suggestion? Thanks!

This ticket, would block that one. I will create it now.

**Comment by swissspidy** [comment]
Why would this be blocking? 🤔

**Comment by spacedmonkey** [comment]
>Why would this be blocking? 🤔 

Because if we add a new property of source, we get rid of local property and we will not need to look in the media queue to see if a resource is local, we can use the source property. That would change what happens in this PR.

**Comment by swissspidy** [comment]
First and foremost this ticket is about getting rid of `isTranscoding`, `isTrimming` and `isMuting`.

If we'd implement something like `source`, that would not necessarily be _blocking_ this ticket, but merely be an enhancement on top of it.

What we need to do is:

1. Create a ticket for that proposal
2. Elaborate in detail the use, pros and cons of said proposal

**Comment by felipebochehin87** [comment]
Hi @swissspidy @kkalarickal 

I tested the following scenarios against **https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/edit.php?post_type=web-story&page=stories-dashboard, using PR #9875**, and they look good to me:

1. Uploaded images, videos and gifs ✔️
2. Muting off videos ✔️
3. Trimming videos ✔️
4. Trimming a trimmed video ✔️
5. Trimming a trimmed video again ✔️
6. Transcoding videos ✔️
7. Uploading via WP media dialog ✔️
8. Dragging into canvas ✔️
9. Pasting images into canvas ✔️
10. Dragging gif onto canvas and converting to mp4 ✔️
11. Videos contain timestamp, is_muted icon and poster image ✔️

Evidences can be found in the following document: https://docs.google.com/document/d/1YxaAUGP3ba8a6SEKhLAi2z0FYyO8bLjVhxtYQHb37SQ/edit#

**Comment by swissspidy** [comment]
Thanks a lot for your thorough testing!
