### ISSUE TITLE
Performance: reduce re-rendering in Media panel

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9580]
## Feature Description
Currently, when doing anything on canvas, there is excess re-rendering happening in the Media Library panel, at least the `LibraryMoveable` and `InnerElement` components re-render hundreds of times while dragging for example.

Try either by logging out something in the `InnerElement` or checking the "Highlight updates when components render." checkbox in the React dev tools, and then dragging an element on canvas.

There is no reason these should re-render while doing something unrelated on canvas.

We should detect what's causing it and avoid unnecessary rendering.

See also discussion in https://github.com/google/web-stories-wp/issues/9549#issuecomment-953732053 for context.

**Comment by swissspidy** [comment]
Sharing this finding by rtCamp related to this:

> If you do anything in the editor, the element every `LibraryMoveable` component in the media library will re-render.
>
> Root cause: `InnerElement` has two dependencies (`draggingResource`, `handleDrag`) that change every time someone starts dragging an element on the canvas

https://github.com/google/web-stories-wp/blob/145c41f2359caeec235536c6d4a2d2d4be98db38/packages/story-editor/src/components/library/panes/media/common/innerElement.js#L110-L113

A few additional observations from my side in that regard:

1. `useDropTargets()` is never used with a selector function, this can be improved
2. `DropTargetsProvider` could wrap its return value in `useMemo()`
3. `InnerElement` uses `draggingResource`, but it doesn't need the resource itself, just a boolean flag whether something is being dragged. Thus, `DropTargetsProvider` could return such a boolean `isDraggingResource` flag.
4. `handleDrag` and `handleDrop` from `DropTargetsProvider` change whenever the drop target changes, causing the library elements to needlessly re-render.
5. `InnerElement` could potentially be wrapped in `memo()`
