### ISSUE TITLE
Dashboard: Update and align aspect ratio for displaying stories and templates

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9583]
Right now the poster images are getting displayed in 3:4 ratio, let's update it to be 4:6 to be inline with how stories are presented in search -  cropping (in css) the images a bit to get to this is expected.

**Comment by swissspidy** [comment]
As per Slack, currently getting confirmation for the desired aspect ratio.

Also, need to keep in mind that the page templates in the editor would need to be displayed at the same aspect ratio, for consistency.

**Comment by swissspidy** [comment]
So in a nutshell, the recommendation was to use whatever works best for us, but definitely not 3:4 as the stories are displayed way too small that way.

So ❌ to 3:4

Search is using 10:16 aspect ratio apparently. Can we do a quick mockup to see what that looks like?

Otherwise 4:6 should be OK

**Comment by BrittanyIRL** [comment]
> Search is using 10:16 aspect ratio apparently. Can we do a quick mockup to see what that looks like?
> 
> Otherwise 4:6 should be OK

yeah! i'll mock both up early next week and post here for comparison/decision

**Comment by BrittanyIRL** [comment]
Alrighty, here's 4:6 vs 10:16
| 4:6 | 10:16 | 
| --- | --- | 
| <img width="1010" alt="Screen Shot 2021-10-29 at 4 24 08 PM" src="https://user-images.githubusercontent.com/10720454/139511024-886b26e5-37a8-4e8a-abf3-051be994abcb.png"> |  <img width="1006" alt="Screen Shot 2021-10-29 at 4 25 38 PM" src="https://user-images.githubusercontent.com/10720454/139511085-ad69dd06-ec7b-40f2-98d4-b17ff119ff80.png"> |

**Comment by swissspidy** [comment]
4:6 does look better IMO 👍

**Comment by BrittanyIRL** [comment]
> 4:6 does look better IMO 👍

i agree :) i'll get Amy to weigh in and then push the code up.

**Comment by agingoldseco** [comment]
I'm good with 4:6 as well!

**Comment by csossi** [comment]
Verified in QA
