### ISSUE TITLE
Video trimmer ignores flipped videos

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#9589]
## Bug Description

The video trimmer should display videos with the flipping settings, it has in the element on the canvas. And the video frame strip should do the same.

## Expected Behaviour

Element flip should be preserved.

## Steps to Reproduce

1. Add a video to the canvas
2. Flip it using the flip tools
3. Enter video trim mode
4. Observe that the video is no longer flipped

**Comment by csossi** [comment]
Verified in QA
