### ISSUE TITLE
Utilize shortcodes inside stories

### ISSUE THREAD

**Issue by brianpetro** [swissspidy/web-stories-wp#9595]
Shortcodes are unusable since `the_content()` isn't called when rendering web stories.

How can we call `do_shortcode` on the web story output?

Thanks

**Comment by swissspidy** [comment]
This is not currently supported as shortcodes could output arbitrary content, often breaking stories and causing AMP invalidation.

What would be your use case for using shortcodes within story content?

**Comment by brianpetro** [comment]
I read through the support forums and realize that this isn't something that can be "supported" because of the potential validation issues.

However, I'm just looking for a developer workaround.

The use case is that this plug-in omits features like `amp-story-interactive`, `amp-story-page-attachment`, `amp-form` (https://github.com/ampproject/amphtml/issues/35569).

A shortcode would make it easy to indicate where to render these via a filter.

**Comment by swissspidy** [comment]
Note that we're planning on adding support for these features in the future. We're just not there yet.

If you want to manually add components like these already today, shortcodes wouldn't work for that as they'd output content at the wrong level in the document tree.

I recommend writing a custom AMP content sanitizer and filtering `web_stories_amp_sanitizers` to inject it. Check out `Story_Sanitizer` in the plugin to see how such a sanitizer can modify the DOM of the resulting story.

**Comment by brianpetro** [comment]
Thanks @swissspidy, I'll give it a look.
