### ISSUE TITLE
Tooltips: Watch position while open

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9598]
A while back @BrookeGraham fixed an issue that was newly exposed with dropdowns where they should switch positions while expanded because their position on the page changed and obscured the menu. That was here: #9060

We should do the same for tooltips. @miina pointed out here: https://github.com/google/web-stories-wp/issues/9460#issuecomment-956072696 that there's a few tooltips that are encountering the same problem.

Acceptance criteria: 
- If a tooltip, while open, changes position and is obscured by the end of the browser window or app space it should automatically move positions so that it is not obscured. Places this happens: `toggle consistent corner radius`

**Comment by swissspidy** [comment]
Related: #8945

**Comment by csossi** [comment]
When I click on the tooltip for the radius lock, the tooltip remains onscreen until user clicks somewhere. Can this be set to disappear after a few seconds?:
![image](https://user-images.githubusercontent.com/16945664/142005674-709aff0d-0975-4d07-93b4-3e07563147bc.png)

**Comment by BrookeGraham** [comment]
> When I click on the tooltip for the radius lock, the tooltip remains onscreen until user clicks somewhere. Can this be set to disappear after a few seconds?

Hey @csossi  I am a little confused here. The tooltip should be disappearing after toggling the radius lock icon. If you aren't seeing this, can I get some more details? 

https://user-images.githubusercontent.com/1820266/142008477-ca6b5618-ef14-4bef-b2b0-93d6f682101c.mov

**Comment by BrookeGraham** [comment]
@csossi the tooltip should no longer appear after you click the lock icon. 👍 Let me know if I missed anything. I can hop on a call too if that helps.

**Comment by csossi** [comment]
Verified in QA
