### ISSUE TITLE
Context: Fix sneaky bug in the hooks across the application

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#9600]
## Bug Description

This app uses the [`useContextSelector` hook](https://github.com/dai-shi/use-context-selector). The current pattern looks like:

```js
export function useHelpCenter(selector) {
  const context = useContextSelector(Context, selector ?? identity);

  if (!context) {
    throw new Error('Must use `useHelpCenter` within <helpCenter.Provider />');
  }

  return context;
}

```

But this could fail if the selector is selection for just one value that ends up being 'falsey', like

```js
const isHelpCenterOpen = useHelpCenter((stuff) => stuff.isHelpCenterOpen);
```

This would throw an error whenever the help center is closed.

## Expected Behaviour

Using the hook should only throw an error if the hook is used outside of the related provider.

**Comment by swissspidy** [comment]
Could we just remove that safeguard and not throw errors?

**Comment by samwhale** [comment]
Yeah for sure - that would work 👍
