### ISSUE TITLE
Page background audio continuously plays and overlaps into the next video

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#9621]
## Bug Description

There are a few issues with stories that have a page background audio.
1. The audio from the previous story carries into the next story
2. The audio continues to play after exiting the story
3. The audio overlaps one another

Note: 
- Issue occurs when using the Circle Carousel widget or the Web Stories block. 
- Visit this site and navigate through the stories to see an example of the issue https://testsite.cmsdevrel.com/about
- Each story has audio on each page

## Steps to Reproduce
1. Let [Story 1](https://testsite.cmsdevrel.com/web-stories/ztest-3/) play through on the widget/block, and note audio carries through Story 2. [Story 2](https://testsite.cmsdevrel.com/web-stories/test-audio-2/) has its own audio on each page.
2. Skip through each story, unmute, and note the audio overlaps. 
3. Exit player notice story audio continues to play

## Screenshots

https://user-images.githubusercontent.com/66372350/139908468-1b7f140a-7f22-4dac-8b60-ddabf05f5987.mov

## Additional Context

- Plugin Version: 1.13.0
- WordPress Version: 5.8.1
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
Closing in favor of https://github.com/ampproject/amphtml/issues/36710
