### ISSUE TITLE
Add primary/secondary color families to template tags

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9624]
## Feature Description

Right now template colors are really specific (burnt sienna i'm lookin' at you) which is great for the detailed template view but really unhelpful for the new template search (#9508 ) - let's add in the primary color families as tags (and make 'em translatable).

## Alternatives Considered

- should this be it's own `color-tag` section in template metadata or just strings in the array of tags? If the latter, updating the template search component to also consider color-tags on search matching. 

## Acceptance Criteria 
- Update template package unit tests to make sure color groups aren't skipped on new template additions.

**Comment by swissspidy** [comment]
Just so I understand correctly, the template search is nothing but a freeform text input that allows searching by typing some text?

And if I type "red" I should also find templates with the color "burnt sienna" (which is reddish-brown)?

If so, perhaps we could just extend the `colors` array and add an `alias` key to each color? And then search just looks for that `alias`?

```js
colors: [
  {
    label: _x('Winter Blue', 'color', 'web-stories'),
    color: '#a4deff',
    alias: _x('Blue', 'color', 'web-stories'),
  },
  {
    label: _x('Blackcurrant Blue', 'color', 'web-stories'),
    color: '#160236',
    alias: _x('Blue', 'color', 'web-stories'),
  },
  {
    label: _x('Sunset Yellow', 'color', 'web-stories'),
    color: '#ffc700',
    alias: _x('Yellow', 'color', 'web-stories'),
  },
  // Does not need an alias.
  { label: _x('White', 'color', 'web-stories'), color: '#fff' },
],
```

**Comment by BrittanyIRL** [comment]
I like the alias idea a lot, it keeps the colors organized moving forward. I think the other idea that was tossed around was adding a subset of tags or just tags for the primary colors. 

@littlemilkstudio - you've been in the weeds on this feature, thoughts on approach?

**Comment by maxyinger** [comment]
yea no opinions other than gotta hardcode the meta data in there to map colors to other colors.

Happy to add something like `alias` or `primitive` to map `burnt sienna` to show up when you search `red`, the only drawback to this approach is that there's no notion of predominant colors in a template.

You can see the behavior I'm talking about if you checkout this branch and search `green`:
https://github.com/google/web-stories-wp/pull/9648

this template shows up cus it has green in its specified colors, but doesn't use it on it's cover image:
<img width="1093" alt="Screen Shot 2021-11-05 at 2 55 18 PM" src="https://user-images.githubusercontent.com/35983235/140570886-80915440-0d73-46ac-9c14-63a7da598551.png">

I guess the approach we use just depends if we want this behavior or not? I could see it being beneficial either way, so I'm open to whatever

**Comment by maxyinger** [comment]
A third option is to just ignore colors entirely and just add the primary primary color or two to the `tags` and just search based on that. I guess a lot of them already have a single color specified in the tags? I wonder if they all do:

<img width="573" alt="Screen Shot 2021-11-05 at 3 06 09 PM" src="https://user-images.githubusercontent.com/35983235/140572051-3755b6d9-3f5e-496f-bb91-e6aa2762f7e2.png">

**Comment by BrittanyIRL** [comment]
After design sync with @agingoldseco we've agreed to add in high level colors only (so show 'blue' not also 'blue oyster') so this means updating the metadata so that there's a color family for each color. then we'll search that color family instead of the specific color names.

**Comment by swissspidy** [comment]
So... basically the `alias` approach?

**Comment by BrittanyIRL** [comment]
> So... basically the `alias` approach?

yup! just needed design to look at this so we could get on the same page. alias, family - same concept.

**Comment by csossi** [comment]
Verified in QA
