### ISSUE TITLE
Update Get Started Story

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9627]
## Task Description

When activating the Web Stories plugin users are greeted with the following banner:

<img width="1239" alt="Screenshot 2021-11-03 at 11 02 18" src="https://user-images.githubusercontent.com/841956/140042041-7b7eba4d-44d0-4d62-af79-136fd49fc769.png">

Clicking on the link to the Get Started story opens the story editor pre-filled [with this existing demo story](https://wp.stories.google/stories/tips-web-stories-editor/):

<img width="1680" alt="Screenshot 2021-11-03 at 11 02 35" src="https://user-images.githubusercontent.com/841956/140042180-39b268f7-a592-4126-ac3d-65dccb970bd7.png">

Since the initial launch of the plugin, this demo story has not changed. That means it's quite outdated by now, since we've had over a dozen new releases since then.

Even though it's somewhat cool to read a story about how to use the editor directly within the editor, it's really just a gimmick.

Also, this demo story can only be accessed after plugin activation, but it still means we need to maintain the code for it. 
Especially in the context of the ongoing decoupling work it means we have to move/refactor this code. Now would be a good time to consider removing it.

Thus, I am asking whether we still want to keep this demo story or not.

Some possible options:

1. Completely remove demo story from the plugin activation banner and the editor
2. Remove demo story from editor, and have plugin activation banner link to https://wp.stories.google/stories/tips-web-stories-editor/ instead.  
3. Keep everything as-is

Also:

1. Refresh external story at https://wp.stories.google/stories/tips-web-stories-editor/ with updated content
2. Do not refresh that story

**Comment by swissspidy** [comment]
Asking @gajasinski @choumx @agingoldseco for input & decision

**Comment by gajasinski** [comment]
Do we have any signal around whether creators actually click on this or find it useful. If not (or if they don't), we could remove. @choumx @agingoldseco ??

**Comment by swissspidy** [comment]
We don‘t have any data, because at this point users haven‘t opted into telemetry yet

**Comment by dreamofabear** [comment]
Some unorganized thoughts:

- We do have a tutorial section now
- I think it's kind of nice to have a warm welcome story vs. an empty library
- "Get started" doesn't look like a link though so I'd guess that only a fraction of users would actually click it
- I don't really mind either way :)

**Comment by gajasinski** [comment]
+1 to the warm welcome - nobody likes an empty chat room. 

@swissspidy what is the effort to include the activation banner? Would adding the banner but removing the demo story make your future work easier or more difficult?

**Comment by swissspidy** [comment]
@gajasinski We already have that banner. We also already have the demo story. It's just outdated.

If someone volunteers to bring the demo story up to date, we can work with it. It should not affect our future work too much.

**Comment by gajasinski** [comment]
@aaskedall @agingoldseco do you think this might be something small you'd be willing to take on? Updating the demo story?
