### ISSUE TITLE
Decoupling: Move demo story logic from `story-editor`

### ISSUE THREAD

**Issue by mohdsayed** [swissspidy/web-stories-wp#9628]
## Feature Description

As discussed here https://github.com/google/web-stories-wp/pull/9569#discussion_r739076535.
Since `getDemoStoryById` is WordPress specific, it should not be part of the core story editor. 

> That probably means reverting most of #5507.

> I've always felt that using `get_default_post_to_edit()` or having something that works more akin to how Gutenberg loads the post would be cleaner than the current `useLoadStory` logic.

> It's essentially this story: https://wp.stories.google/stories/tips-web-stories-editor/

> Admittedly, it's a very hidden gimmick that probably has very low usage. So this is not a priority at all.

> In fact, I might even suggest to the team that we remove this feature entirely.

## Additional Context

Related https://github.com/google/web-stories-wp/issues/2918

**Comment by swissspidy** [comment]
Thanks for opening this!

In #9627 I proposed updating or potentially removing this logic. Let's wait for the outcome on that ticket.
