### ISSUE TITLE
Introducing and removing animated elements at different time settings

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#9635]
## Feature Description

A user has requested a feature to introduce and remove text elements at a set time on a story page. For example, text set 1 would appear first on the page, then text set 2 would appear a few seconds later on the same page.

## Alternatives Considered

Animating a text element allows you to introduce the element at a set time, but doesn't remove it at a different time. 

## Additional Context

Related support topic: https://wordpress.org/support/topic/text-duration-limits-on-video

**Comment by swissspidy** [comment]
Related: #3414

**Comment by swissspidy** [comment]
I don't think we'll have an animation timeline anytime soon that would enable this.
