### ISSUE TITLE
E2E tests run failure: Test suite failed to run

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9636]
## Bug Description
E2E tests seem to fail consistently on various PR-s even after re-running multiple times.

An example run: https://github.com/google/web-stories-wp/runs/4104763628?check_suite_focus=true#step:11:23

<img width="877" alt="Screenshot 2021-11-04 at 19 16 48" src="https://user-images.githubusercontent.com/3294597/140387563-5660846a-3242-4fcf-83be-da1eb2a559f0.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Looks like the culprit is in the `packages/e2e-tests/src/specs/wordpress/archive.js` test: https://github.com/google/web-stories-wp/runs/4179192112?check_suite_focus=true

**Comment by swissspidy** [comment]
Disabling `packages/e2e-tests/src/specs/wordpress/archive.js` for now as this takes more time to debug than I thought.

The error might be coming from Puppeteer or elsewhere, and if the this part is correct, it might not even be from within a test:

https://github.com/facebook/jest/blob/7bb400c373a6f90ba956dd25fe24ee4d4788f41e/packages/jest-message-util/src/index.ts#L122-L135

> ExecError is an error thrown outside of the test suite (not inside an `it` or`before/after each` hooks). If it's thrown, none of the tests in the file are executed.

I verified this by skipping all the tests in that file. The error was still occasionally occurring.
