### ISSUE TITLE
Default view for page templates panel

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#9637]
## Feature Description

A user would like to have the ability to change the default view for page templates to their saved page templates instead of the default templates. 

<img width="428" alt="Screen Shot 2021-11-04 at 1 33 20 PM" src="https://user-images.githubusercontent.com/66372350/140390123-e3402e21-44d3-4521-87b5-7a07d7263264.png">

## Additional Context

https://wordpress.org/support/topic/few-enhancement-requests/

**Comment by BrittanyIRL** [comment]
🤔  Would be curious about setting the default to be custom page templates if user has 1 or more custom page templates saved and otherwise the default view is the default page templates. Def a design question but this is my unsolicited 2 cents.

**Comment by swissspidy** [comment]
Alternatively, we could just save the view type in localStorage, so whenever you change it, the change persists.

**Comment by BrittanyIRL** [comment]
@agingoldseco @gajasinski  - what are your thoughts on this?

**Comment by gajasinski** [comment]
I like @swissspidy 's recommendation. If you've already built a library of saved templates, it could be annoying to have to constantly switch these. Saving the state of the view type and allowing the user to bounce back and forth would be a nice touch.

**Comment by maxyinger** [comment]
> Alternatively, we could just save the view type in localStorage, so whenever you change it, the change persists.

This sounds good to me too. Real straight forward

**Comment by gajasinski** [comment]
Added this to the backlog

**Comment by csossi** [comment]
Verified in QA
