### ISSUE TITLE
Workspace UX changes: Page Menu

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9640]
## Feature Description
See the section in [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=10548%3A453241)

- [ ] Move the placement of the Page menu: Add new page, duplicate page, delete page go to the bottom right side of the page
- [ ] Redo / undo go to next to the preview button
- [ ] When in Zoom mode, move the Page menu to the right side of the Workspace, together with the quick-actions menu of the selected element, always visible.

Note: increasing page size to use the new room will be done separately

## Additional Context

In Zoom mode:
<img width="651" alt="Screenshot 2021-11-05 at 13 18 25" src="https://user-images.githubusercontent.com/3294597/140502813-937211ee-8bb8-4060-8f38-c3d7aca32830.png">

Default mode:
<img width="657" alt="Screenshot 2021-11-05 at 13 18 14" src="https://user-images.githubusercontent.com/3294597/140502823-662d8454-5030-4534-a980-3c7dec39545e.png">

**Comment by csossi** [comment]
Verified in QA
