### ISSUE TITLE
Workspace UX changes: Allow collapsing page carousel

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9641]
## Feature Description
See [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=10638%3A453154)

- [ ] Add button for collapsing page carousel that shows the total number of pages + the selected page number
- [ ] Allow collapsing page carousel, add animation for sliding up/down
- [ ] The carousel will display as many pages as fit (as it currently does)
- [ ] Keep in mind the thumbnails generation when implementing to ensure it still works as expected.

Notes: 
- the default state of the page carousel is expanded, no need to store the state.
- increasing page size to use the new room will be done separately

## Additional Context

Expanded vs collapsed states:
<img width="520" alt="Screenshot 2021-11-05 at 13 22 58" src="https://user-images.githubusercontent.com/3294597/140503294-2d5f9736-8beb-485d-9b0f-b1a3fb2b172d.png">

**Comment by csossi** [comment]
Verified in QA

**Comment by csossi** [comment]
Verified in QA

**Comment by csossi** [comment]
Verified in QA (re: canvas sizing)
