### ISSUE TITLE
Code quality: Refactor media reducer to reduce complexity

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#9646]
## Feature Description

The  media reducer currently [has a complexity of 30](https://github.com/google/web-stories-wp/blob/ed06c490cd86bb2d46f69ccecbdfe4006deb084b/packages/story-editor/src/app/media/local/reducer.js#L17). This is very high, we should refactor this logic to reduce this complexity.

**Comment by swissspidy** [comment]
Should be trivial to move every reducer into its own file, like we do in the media upload queue for example.
