### ISSUE TITLE
Media: Use base color while loading in assets

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#9647]
## Feature Description

In https://github.com/google/web-stories-wp/issues/9550, we now store the base color of the image / video with the resource.  Currently when resources are loading a grey box is rendered. See screenshot. 

<img width="348" alt="Screenshot 2021-11-05 at 15 52 27" src="https://user-images.githubusercontent.com/237508/140539813-dec62f78-b833-4464-b138-834728086a92.png">

But now we have the base color, we use this color as the background color. This is what other sites like unsplash do. See this example. 

<img width="1371" alt="Screenshot 2021-11-05 at 15 49 47" src="https://user-images.githubusercontent.com/237508/140540038-4590da7b-5091-43ba-8b04-63bc57d01aae.png">

We could do the same in the editor.

**Comment by swissspidy** [comment]
Good idea. Makes sense to use the avg color in more places where possible.

Though worth noting that Unsplash uses [BlurHash](https://blurha.sh/), not just a solid color placeholders.

Reminds me that I actually once [proposed](https://xwp.slack.com/archives/CCCAUAH6F/p1588667580251200) using BlurHash.

Perhaps something worth revisiting?

cc @choumx @gajasinski @agingoldseco WDYT about using blurred placeholders?

**Comment by gajasinski** [comment]
+1 a more polished experience compared to grey boxes

**Comment by dreamofabear** [comment]
Love it.

**Comment by spacedmonkey** [comment]
<img width="1904" alt="Screenshot 2021-11-08 at 11 18 44" src="https://user-images.githubusercontent.com/237508/140733234-f3786c87-46af-4a77-9560-4f4896e80028.png">

Google images also does this.

**Comment by swissspidy** [comment]
Summary:

1. Using base color in media library is a no-brainer. We'll add this.
2. Blurhash is a nice enhancement on top of that, will create a new ticket for that.

**Comment by spacedmonkey** [comment]
Related: #1194

**Comment by csossi** [comment]
Verified in QA
