### ISSUE TITLE
Design panel: Don't show collapse button hover styles on headers if not collapsible

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#9670]
## Bug Description

`Saved Styles` section header shows the hover bubble that is supposed to be behind the chevron when there is no content to show.

## Expected Behaviour

The hover style should not be visible unless the panel is collapsible.

## Steps to Reproduce

1. Create a story
2. Add text to the page
3. Select the text
4. Go to the `Saved Styles` panel
5. Delete all saved styles (if any)
6. Hover the `Saved Styles` header. Should see the bubble hover styles.

## Screenshots

![hover-thing-not-needed](https://user-images.githubusercontent.com/22185279/140977490-ec2e6df9-ab25-4889-ae10-e140efa6306b.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrittanyIRL** [comment]
@miina - we've got space, care if we fix this?

**Comment by miina** [comment]
@BrittanyIRL Thanks for reaching out -- actually, this issue is not valid anymore since the Saved Styles is now a subpanel under the Text panel and can't be expanded/collapsed at all.
