### ISSUE TITLE
Deduplicate Tooltip

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9684]
## Feature Description

The story-editor has it's own implementation of the Tooltip that is imported from the design system. With work done here #9668 - that implementation should be obsolete and able to be removed. 

Let's branch off of 9688 and remove that redundant tooltip (story-editor/src/components/tooltip) and use the one in the design system. I suggest branching so that we can verify that the bugfix there is actually a solution here. 

After review it can be merged into 9668 and QA'd all together.

**Comment by BrookeGraham** [comment]
The `Story-Editor` and the `Dashboard` wrap the `Tooltip` from `Design-System` and check the config for `RTL` before re-exporting.  If the user is in `RTL` then we swap out the `placement` prop and map it to the `RTL_PLACEMENT` . 

The story-editor version of Tooltip, as well as the dashboard version are working as expected.
