### ISSUE TITLE
Media: Generate and backfill BlurHash for media items

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9685]
## Feature Description

As a follow-up to #9550 and #9647, we want to adopt [BlurHash](https://blurha.sh/) as progressive enhancement on top of `baseColor` to get even nicer previews when media is loading.

* [ ] Register post meta to store blurhash strings on attachments
* [ ] Use [`blurhash`](https://github.com/woltapp/blurhash/tree/master/TypeScript) to create blurhash during upload and backfill blurhash for existing media items in the library
* [ ] Display blurhash while loading media items in the media library, perhaps using [`react-blurhash`](https://github.com/woltapp/react-blurhash), which seems pretty lightweight
* [ ] Update `Resource` JSDoc to add blurhash string
* [ ] Get `blurHash` from media3p (currently Unsplash-only) as well

**Comment by kkalarickal** [comment]
Tested on: https://stories-qa-wordpress-amp.pantheonsite.io/ using #9953 

Status: LGTM 👍 

Steps; Confirmed BlurHash front end behaviorby following these steps:

1. Create a new story.
2. Upload a video or image.
3. Wait until upload is complete.
4. Wait for 20 seconds.
5. Reload the editor.
6. See blurhash for newly uploaded asset.
7. Scroll down within the images panel and observe the blurhash as the more images are loaded

Screencast: https://share.getcloudapp.com/z8ukDNAq

**Comment by kkalarickal** [comment]
Also confirmed Blurhash front end behavior for the 3rd party media panel, To see this:

1. Open a web story 
2. Click on 3rd party media
3. for a brief moment, the images that are loaded in 3rd party media panel will show blurhash
4. Next scroll down within the Trending panel
5. Observe the blurhash effect as newer images are loaded

**Comment by swissspidy** [comment]
@kkalarickal Thanks for the detailed report! ❤️
