### ISSUE TITLE
Media: Avoid repeated backfilling logic

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9686]
## Feature Description

In the local media provider we currently have lots of code duplication related to logic for backfilling media metadata (poster image, video's audio information, base color, and soon blurhash).

There's an opportunity to make this more DRY, in a way TBD.

**Comment by spacedmonkey** [comment]
I believe this was handled by https://github.com/google/web-stories-wp/pull/9638

**Comment by swissspidy** [comment]
I thought we were originally talking about this:

https://github.com/google/web-stories-wp/blob/c4b6efa369aa450bbdb9191c68be2a9c1d9f8086/packages/story-editor/src/app/media/local/useContextValueProvider.js#L156-L209

Which is still very repetitive

**Comment by spacedmonkey** [comment]
Originally I was talked about this repeated code. 

https://github.com/google/web-stories-wp/blob/3a3ab6805a6907f7f6b129ae32cbab3bb239922a/packages/story-editor/src/app/media/utils/useProcessMedia.js#L128-L141

Which is now removed. 

It is very repetitive, but each check is different. I can't see a nice way to refactor this.

**Comment by swissspidy** [comment]
Let's close this for now then
