### ISSUE TITLE
3P Media: Get correct `baseColor` from API response

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9691]
## Feature Description

The media3p API will soon provide `color` and `blurHash` fields.

That means we need to change the following instances of `m.baseColor` to `m.color`:

https://github.com/google/web-stories-wp/blob/86609e0ea2642f378f6a29fb72501a3d906fa16e/packages/story-editor/src/app/media/utils/getResourceFromMedia3p.js#L266

https://github.com/google/web-stories-wp/blob/86609e0ea2642f378f6a29fb72501a3d906fa16e/packages/story-editor/src/app/media/utils/getResourceFromMedia3p.js#L287

https://github.com/google/web-stories-wp/blob/86609e0ea2642f378f6a29fb72501a3d906fa16e/packages/story-editor/src/app/media/utils/getResourceFromMedia3p.js#L313

The user-facing change—after #9647 is merged— will be colored placeholders when loading Unsplash images in the media3p tab.

**Comment by spacedmonkey** [comment]
Resharing from Slack. 

Seems like Tenor also has a color field. See this [example](https://g.tenor.com/v1/gifs?ids=5589342&key=LIVDSRZULELA). The field is called `bg_color`

**Comment by swissspidy** [comment]
@spacedmonkey FYI, `color` and `blurHash` are now available for Unsplash images (if provided). Working on Tenor next.
