### ISSUE TITLE
Hotlinking: False positive for invalid link 

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#9696]
## Bug Description

Valid urls are being flagged as invalid url, when they are not. 

## Steps to Reproduce

1. Create a new story. 
2. Click in media from url. 
3. Input this URL: https://spacedmonkey.ams3.cdn.digitaloceanspaces.com/uploads/2021/10/sample_5184×3456-1-scaled.jpeg
4. See error.

## Screenshots

<img width="604" alt="Screenshot 2021-11-12 at 12 40 37" src="https://user-images.githubusercontent.com/237508/141468779-26ee0632-1cce-44b1-8954-0a796d31ec78.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Copying from Slack:

The issue is that the “x” in that URL is not actually the ASCII character “x”, so it needs to be encoded.
`https://spacedmonkey.ams3.cdn.digitaloceanspaces.com/uploads/2021/10/sample_640%C3%97426.jpeg `works

**Comment by csossi** [comment]
Verified in QA
