### ISSUE TITLE
Color Picker: fix navigation with arrow keys

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9701]
## Bug Description
Since adding a `Tooltip` wrapper around the `StyledSwatch` component, navigation with arrow keys doesn't work anymore.

## Expected Behaviour
The user should be able to navigate between the color swatches using arrow keys.

## Steps to Reproduce
- Open the color picker after ensuring it has a few saved colors
- Try to navigate between the colors using arrow keys.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Verified in QA
