### ISSUE TITLE
Checklist: Large Elements with Link Copy Update

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9712]
Following #9654 - copy update per @choumx :

https://github.com/google/web-stories-wp/pull/9654#discussion_r748635732

> Elements with links must not cover most of the page. Decrease the size of elements with links.

Instead of 

> Links cannot cover a large majority of the page. Use smaller elements for links.

**Comment by csossi** [comment]
Verified in QA
