### ISSUE TITLE
Media: Add `decoding=async` to all images

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#9740]
## Feature Description

Background [Trac #53232](https://core.trac.wordpress.org/ticket/53232). 

In WordPress core, there is a plans to add `decoding=async` to all images. This improves page render performance. We should consider doing the same for images found in the media library.

**Comment by swissspidy** [comment]
We can do some testing to measure benefit of this. We could perhaps add this _everywhere_, not just the media library.

**Comment by spacedmonkey** [comment]
I put together a PR https://github.com/google/web-stories-wp/pull/9743 for this. We only render images in a couple of places, so didn't take that long. Performance is better, but I am not sure how to measure it.

**Comment by spacedmonkey** [comment]
Worth noting we are already using this property in a couple of places. 

https://github.com/google/web-stories-wp/blob/833465cc85541f9650612a3471092ff2c8398860/packages/story-editor/src/elements/media/imageDisplay.js#L114

https://github.com/google/web-stories-wp/blob/96ceba3f6bfd5de50269734b63398283a7849a5f/packages/media/src/preloadImage.js#L29

**Comment by swissspidy** [comment]
The `decoding="sync"` part there is interesting. It was just recently added in #9168 on purpose to fix an issue with Safari.

This is why it's important to do testing and measurement to see the impact of this. DevTools offer powerful solutions for that.

cc @choumx @miina for input before we dig deeper into this

**Comment by dreamofabear** [comment]
Looks like `decoding=sync` fixes missing images in canvas-to-image transformations, which makes sense. 

I think it should be safe to add to media library images (which we never try to screen capture), though the performance benefit (media library images don't block render of subsequent DOM children) might be hard to detect w/o strong CPU throttling.

**Comment by miina** [comment]
> The decoding="sync" part there is interesting. It was just recently added in #9168 on purpose to fix an issue with Safari.

Yep, let's not undo that fix :) Image generation is currently used for canvas and also for page previews, so using `async` for the media element display should be skipped everywhere for now.

> This is why it's important to do testing and measurement to see the impact of this.

💯

**Comment by spacedmonkey** [comment]
I am not an expect on performance measurements like this, does anyone have any recommendations on how to collect data to much so that we can get this merged.

**Comment by dreamofabear** [comment]
I'd just turn on CPU throttling in devtools and sample LCP a number of times before and after the fix. It might be not detectable within measurement noise but at least we can make sure it's not negatively impacting performance.
