### ISSUE TITLE
Explore Templates Search: Turn Experiment On

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9746]
This ticket is to turn the experiment on for the explore template search. The bulk of the work was done here: https://github.com/google/web-stories-wp/pull/9648

Now you can search through templates in the dashboard's explore templates view. Fields that are searched are template tags, vertical, and color families. This feature started out as adding a bunch of filters to the explore templates view and has been scaled back to this so that more user research and feedback can be gathered about how to best make it more robust.

To test this feature out: 

- Go to explore templates view in dashboard
- Try searching, see templates matching your search show up.

**Comment by csossi** [comment]
Verified in QA
