### ISSUE TITLE
Design System: Refactor context menu

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#9750]
## Feature Description

The context menu in the design system generates a menu from a list of objects. At first this was thought to be easier since we could create a context menu without needing to build out too much JSX.

However, with the introduction of the `MediaPicker` it has become apparent that it would become easier to define whatever UI we'd like in the context menus.

## Alternatives Considered

n/a

## Additional Context

Ex: The context menu in the [radix-ui](https://www.radix-ui.com/docs/primitives/components/context-menu#anatomy) builds a context menu out of smaller pieces every time it's used. This seems to be a better approach in the event that we'd want to wrap individual items with something (such as a media picker)

```tsx
import * as ContextMenu from '@radix-ui/react-context-menu';
export default () => (

  <ContextMenu.Root>

    <ContextMenu.Trigger />
    <ContextMenu.Content>

      <ContextMenu.Label />

      <ContextMenu.Item />
      <ContextMenu.Group>

        <ContextMenu.Item />

      </ContextMenu.Group>
      <ContextMenu.CheckboxItem>

        <ContextMenu.ItemIndicator />

      </ContextMenu.CheckboxItem>
      <ContextMenu.RadioGroup>

        <ContextMenu.RadioItem>

          <ContextMenu.ItemIndicator />

        </ContextMenu.RadioItem>

      </ContextMenu.RadioGroup>
      <ContextMenu.Root>

        <ContextMenu.TriggerItem />

        <ContextMenu.Content />

      </ContextMenu.Root>
      <ContextMenu.Separator />

    </ContextMenu.Content>

  </ContextMenu.Root>

);
```

**Comment by BrittanyIRL** [comment]
@samwhale will you also point this?

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #9960.

1. Retested publisher logo menu
2. Retested story page - list view and grid view
3. Verified that contest menus are displayed when clicking on ellipsis
4. Retested right click menu in the editor when right clicking an element
5. Retested quick action menu next to the canvas
