### ISSUE TITLE
Templates: Use JPEG images instead of PNG where appropriate

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9782]
## Feature Description

I noticed quite a few templates use PNG files for photos, where JPEG would make much more sense and bring down file size.

Affected templates noticed so far:

* `summer-adventure-guide`
* `summer-fashion-collection`
* `sustainability-tips`
* `technology-advice`
* `tips-for-throwing-an-outdoor-luau`
* `tv-show-recap`
* `ultimate-comparison`
* `ways-to-eat-avocado`

Potentially more!

We should:

1. Convert all the applicable PNG files to JPEG in the https://github.com/GoogleForCreators/wp.stories.google repo
2. Submit a PR there to update the files. Make sure the files are tracked with LFS.
2. Update the template files in a PR in this repo here to change the file extension accordingly

## Alternatives Considered

**Note:** WebP would be best but we don't use that just yet due to browser support.

**Comment by spacedmonkey** [comment]
From the looks of it there are around 588 png references in the templates. That is a a lot files to change. Should this be automated. What settings should be used? Quality / color profile etc. 

I am also unable to see where these image files are stored.

**Comment by swissspidy** [comment]
They are stored in the https://github.com/GoogleForCreators/wp.stories.google repo mentioned above.

There's also detailed documentation on (templates) image storage:

https://github.com/google/web-stories-wp/blob/main/docs/cdn.md
https://github.com/google/web-stories-wp/blob/main/docs/external-template-creation.md

We need to be careful. Not _all_ PNG files need to be changed per se. If the resulting JPEG is bigger than the PNG file or has worse quality it obviously doesn't make sense.

And yes, this can definitely be automated to some degree, e.g. by using [ImageMagick](https://imagemagick.org/). Quality level 90 should be reasonable.

Suggestion:

1. Go through all the templates in this folder: https://github.com/GoogleForCreators/wp.stories.google/tree/main/public/static/main/images/templates
2. Convert all PNG images in a folder to JPEG using `magick mogrify -format jpg -quality 90 *.png`
3. If the JPEG files are smaller than the PNG files with same quality, keep them and delete the PNG files. Otherwise delete the JPEG files again.
4. Submit a PR on the GoogleForCreators/wp.stories.google repo to update the image files. Make sure the files are tracked with Git LFS (see documentation above).
5. Update the image URLs in the template files in a PR in this repo here to change the file extension accordingly

If you have any questions or concerns or would want me to do that instead, just let me know.

**Comment by spacedmonkey** [comment]
I just tried to push from `wp.stories.google`, but either from my own fork. it doesn't work. I was unable to setup lfs. I think someone with access to the repo will need to push this change. :( 

I can push change to our repo through.

**Comment by spacedmonkey** [comment]
Here is the script I ran locally. 

```
for dir in /Users/jonny/workspace/wp.stories.google/public/static/main/images/templates/*
do
  magick mogrify -format jpg -quality 90  ${dir}/*.png;
done
```

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10104.

Opened the templates below, inspecting elements, and images are saved as .JPEG.

Used https://github.com/google/web-stories-wp/pull/10104/files to identify images that should be updated.

- summer-adventure-guide
- summer-fashion-collection
- sustainability-tips
- technology-advice
- tips-for-throwing-an-outdoor-luau
- tv-show-recap
- ultimate-comparison
- ways-to-eat-avocado
