### ISSUE TITLE
Templates: Ensure all resources have `baseColor` property

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9783]
## Feature Description

Not all templates' resources have a `baseColor` set.

Let's add it everywhere for consistency.

We should also add a test to cover that.

Here's a WIP branch: https://github.com/google/web-stories-wp/tree/add/templates-baseColor

**Comment by spacedmonkey** [comment]
Should we add blurhash here as well?

**Comment by swissspidy** [comment]
BlurHash is mostly useful for the media library, not the canvas or output. So not really relevant for templates.

Let's focus on base color for now. We could always add BlurHash later in a separate ticket if we have more use cases for it.

**Comment by spacedmonkey** [comment]
How did you add these base colors, manually?

**Comment by swissspidy** [comment]
Yeah I did those ones manually using some online tool, since in some templates there was just 1 missing blurhash so it was quick.

A quick search suggests that something like `convert imagename.jpg -scale 1x1\! -format '%f\n%c\n' -colors 5 -define histogram:unique-colors=true histogram:info:` or `magick imagename.jpg -colors 1 -unique-colors txt:` might work to get the dominant color via CLI.

**Comment by spacedmonkey** [comment]
Could we add a migration?

**Comment by swissspidy** [comment]
This is a one time thing.

A migration for adding basecolor would also run when opening an old story in the editor, making it unusable until the migration has finished. Not great.
