### ISSUE TITLE
Video trim mode broken after introduction of collapsing carousel

### ISSUE THREAD

**Issue by barklund** [swissspidy/web-stories-wp#9788]
## Bug Description

The trimmer for video trim mode now attaches completely weirdly and pushes the trimmed video element to a weird place.

## Expected Behaviour

Trim should work correctly.

## Steps to Reproduce

1. Enter video trim mode

## Screenshots
![Screen Shot 2021-11-23 at 14 16 35](https://user-images.githubusercontent.com/637548/143091768-6d0466c6-de2a-4fec-af53-a95084d0bd36.png)

**Comment by csossi** [comment]
Verified in QA
