### ISSUE TITLE
Hotlinking: Improve messaging for large files

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9797]
## Feature Description

The UX when trying to hotlink large media files (e.g. a 2 minute HD video) isn't ideal.

**Suggestion 1**

We could add a message to the dialog with some recommendations:

![Screenshot 2021-11-24 at 13 36 20](https://user-images.githubusercontent.com/841956/143239564-ad8c4105-805b-430e-b4c9-f35dcd7c65ec.png)

For example:

```
For a better user experience, files smaller than %s MB and videos short than %d seconds are recommended.
```

With reasonable values like 30 MB and 60 seconds (matching what we say in the checklist)

**Suggestion 2**

The catch-all error message for hotlinking is currently this:

```
Media failed to load. Please ensure the link is valid and the site allows linking from external sites.
```

The latter part is not super accurate anymore because of the CORS proxy.

We could change to something like that:

```
Media failed to load. Ensure the site allows linking from other sites or try a different file.
```

**Suggestion 3**

Second, we _might_ have information about file size from the server-side validation (`hotlinkInfo.file_size`) here:

https://github.com/google/web-stories-wp/blob/90cb2d2c05eafcd4a5e63e7ade1ddf694437c771/packages/story-editor/src/components/library/panes/media/local/hotlink/useInsert.js#L194

So as soon we receive that information, we could check the file size and warn the user if the size exceeds the recommended threshold.

```
Warning: large file detected. Insertion might be slower.
```

**Comment by spacedmonkey** [comment]
I think the hotlink validation endpoint should check the size of the file and errors at the point instead of failing on proxying. This means that it the hotlinking will fail fast.
