### ISSUE TITLE
Publishing: Support publishing pending stories

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9798]
## Feature Description

When opening a pending story as an admin, it's not currently possible to publish it, continue saving it as pending, or switching to a draft.

Compare this with Gutenberg:

![Screenshot 2021-11-24 at 14 39 31](https://user-images.githubusercontent.com/841956/143251392-03ae3c87-b4cc-4508-832c-f5f89076b504.png)

To fix this, we need to update the buttons in the header like this for pending stories:

![Screenshot 2021-11-24 at 14 54 11](https://user-images.githubusercontent.com/841956/143251542-0935dda8-5c28-4a13-8808-2c14bda03c90.png)

Bonus points for an e2e test.

**Comment by swissspidy** [comment]
Had quick stab at this while I was filing the ticket: https://github.com/google/web-stories-wp/tree/fix/9798-pending

Seems pretty straightforward.

**Comment by csossi** [comment]
Verified in QA
