### ISSUE TITLE
Editor: Improve UX when validating links

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9799]
## Feature Description

Noticed in bug bash but not a regression or anything.

> While the browser is trying to figure out if the link is valid it shows the hidden UI for a moment. If the link isn’t supported, then it hides it again. This was very confusing to me.

> Maybe we don’t show the UI until the link is valid?
> Maybe we show the UI no matter what but disable the UI and add a message saying why it is disabled?

![uh](https://user-images.githubusercontent.com/841956/143256895-27814202-e853-4b7a-92d9-072ad5f1bbe3.gif)

> Similarly jarring when typing a link and the panel jumps up and down due to link validation. Maybe validation could be debounced?

![jarring](https://user-images.githubusercontent.com/841956/143256944-4dbd29e0-888c-4213-a2a8-dc07cedff922.gif)

**Worth noting** that the experiencesimilarly jarring for page attachments and media hotlinking. It would be great to apply the same treatment there as well. Demo:

https://user-images.githubusercontent.com/841956/143257138-8ee3b78d-58f3-4c27-8353-11f33e8a58d3.mov

https://user-images.githubusercontent.com/841956/143257114-cdba30bd-bb8e-45a9-bcff-92461d159688.mov

**Comment by miina** [comment]
@gajasinski / @agingoldseco Would be great to get your thoughts on this.

Basically currently we're hiding some of the link fields while the link is being verified. The idea is that if the link is not set or is invalid, we shouldn't display additional fields.

When the link is verified as valid, but is then changed, the fields are hidden again until the modified link is verified.

This, however, causes confusing jumpiness for the users.

Thoughts on improvements?

**Comment by gajasinski** [comment]
Would the experience be negatively impacted if we didn't hide/unhide the fields? If we just locked them/greyed them out as we were validating? @agingoldseco thoughts?

**Comment by agingoldseco** [comment]
I agree with George—like the idea of only showing the new fields only when a new link is valid, disabling the fields if they're changing the link until it's revalidated, and if the link isn't replaced with another or a valid one the fields can disappear when the user clicks away from the panel. Would that last part be feasible?

**Comment by miina** [comment]
> if the link isn't replaced with another or a valid one the fields can disappear when the user clicks away from the panel. Would that last part be feasible?

Hm, by clicking away from the panel, do you mean that if the URL input is not focused, the other inputs would disappear? This might still cause jumpiness/confusion, e.g. if the user clicks away while waiting for the link to load? Thoughts?
It is possible to do that though.
