### ISSUE TITLE
Panel Condensing - UX issue with the expanded corners box

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9802]
## Bug Description

Originally reported by @agingoldseco 

> Slight misalignment of expanded corners box with edges of other text boxes
![image6.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/79f31d06-a40b-4314-a448-50e23a3b7efc)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Verified in QA
