### ISSUE TITLE
Panel condensing - The selection panel fields are much closer to the bottom of the box than in other panels 

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9805]
## Bug Description

originally reported by @agingoldseco 

> The selection panel fields are much closer to the bottom of the box than in other panels 

<img width="319" alt="image18" src="https://user-images.githubusercontent.com/58738530/143277158-e91c5d8f-414a-4cd7-8cad-64c7b755baf9.png">
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Verified in QA
