### ISSUE TITLE
Zoom + RTL: Horizontal scroll not working with 200%

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9807]
## Bug Description
Originally reported by @BrittanyIRL 

Horizontal scrolling is not working in RTL mode when zoomed in 200% (see [Brittany's comment](https://github.com/google/web-stories-wp/issues/9807#issuecomment-981812506) below).

<img width="863" alt="image3" src="https://user-images.githubusercontent.com/58738530/143288259-bc25e16f-b83f-4d02-ab13-771b1aeb5212.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by bmattb** [comment]
@BrittanyIRL can you please confirm that this is what you meant?

**Comment by miina** [comment]
@BrittanyIRL Could you also confirm how to reproduce it -- is this something that happens only in RTL or did you always see it?

**Comment by BrittanyIRL** [comment]
yeah, that's vague. thanks for following up. So pretty much it's just that horizontal scroll doesn't work in RTL + 200% zoom but it does in LTR. 


https://user-images.githubusercontent.com/10720454/143907919-deb22d80-f0e3-43b8-a6c3-9c8de2e5d732.mp4

**Comment by miina** [comment]
Thanks, @BrittanyIRL, that makes things more clear. Was this happening in Firefox specifically or just a general bug?

**Comment by BrittanyIRL** [comment]
Just firefox.

**Comment by miina** [comment]
Looks like it's not working in Chrome either, just tested.

**Comment by felipebochehin87** [comment]
Tested against, using PR #10128.

1. Zoomed in to 200%
2. Checked behavior of scroll bars (both horizontal and vertical) in Firefox
3. Checked behavior of scroll bars (both horizontal and vertical) in Chrome
4. Checked behavior of scroll bars (both horizontal and vertical) in Safari
