### ISSUE TITLE
On small screen sizes Page side menu buttons are overlapping

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9808]
## Bug Description

Originally reported by @spacedmonkey 

Note below the quick actions menu is on top of the page navigation button

<img width="325" alt="image9" src="https://user-images.githubusercontent.com/58738530/143288750-22ee3781-cf27-4578-92ef-c42e2823279e.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
Hey @agingoldseco, if I understand correctly, your suggestion is to move the menus to the right edge of the workspace not only in case of zoom but also if the page is very small.

Could you confirm which would be the moment where this should happen? E.g. maybe if the longest possible menus are longer than the page itself? Let me know what you had in mind.

**Comment by miina** [comment]
Additional context from @spacedmonkey, see the original comment: https://github.com/google/web-stories-wp/issues/9809#issuecomment-979215075

<img width="1792" alt="Screenshot 2021-11-25 at 13 23 14" src="https://user-images.githubusercontent.com/237508/143449275-b760009d-1051-449e-803e-d7e771257ff1.png">
<img width="1792" alt="Screenshot 2021-11-25 at 13 22 49" src="https://user-images.githubusercontent.com/237508/143449284-e5c0cdd2-72f4-44df-b02b-122c9cd7aba5.png">

> This are exact screenshots. It is worth noting that the height of my browser window is pretty low. Either way I think it should fail a little more graceful than this. 

> Worth noting, this is not RTL. 

@agingoldseco Looks like in case of very low window height, the page buttons on the right edge of the workspace also start colliding with other buttons (Grid button).

Perhaps we should assign minimum height to the editor use scrolling if it gets too small. Currently, the editor can be resized so small that the page becomes basically invisible and various buttons start overlapping. Thoughts?

**Comment by miina** [comment]
Note: we should also take the scrollbar into consideration when adjusting the UX.

**Comment by agingoldseco** [comment]
Yes to moving menus when someone zooms way out—I think that should be when the canvas is zoomed to ~55% of the 100% view or smaller whether that's through changing browser size or using normal zoom. Thoughts on that?

Re: people being able to zoom the canvas out to oblivion, I have no issue with setting a minimum for that—don't think it's a massive priority cause it seems unlikely people will try to work on a page that tiny, but we can set the minimum page height to maybe 550px tall where at least the buttons won't all collide and the whole bottom of the editor just starts cutting off instead. Or less than that, like 475px, and we set a minimum canvas size so you have to scroll in the workspace to see the whole canvas behind the bottom bar. Am I understanding that correctly?

**Comment by miina** [comment]
> Yes to moving menus when someone zooms way out—I think that should be when the canvas is zoomed to ~55% of the 100% view or smaller whether that's through changing browser size or using normal zoom. Thoughts on that?

Sure, we could try with that and see how it feels like.

> Re: people being able to zoom the canvas out to oblivion, I have no issue with setting a minimum for that—don't think it's a massive priority cause it seems unlikely people will try to work on a page that tiny, but we can set the minimum page height to maybe 550px tall where at least the buttons won't all collide and the whole bottom of the editor just starts cutting off instead. Or less than that, like 475px, and we set a minimum canvas size so you have to scroll in the workspace to see the whole canvas behind the bottom bar. Am I understanding that correctly?

Yep, all correct :) I'm not thinking that people purposefully try to get the canvas very small but just that on small screens, when not using the full screen, it can get very small without wanting it.

@barklund for thoughts here since you implemented the Fit size of the canvas -- do you think that would mess up and need refactoring the whole Zoom system? If we'd have a minimum limit to Fit / zoom values?

**Comment by miina** [comment]
Note: Floating menu might help with it since some buttons will be removed: #10112

**Comment by miina** [comment]
Marking it blocked by #10111  since that will change the layout generally -- probably best to address this issue once the change has been done.
