### ISSUE TITLE
Update the title of the Text Box & Saved Styles box to bold

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9810]
## Feature Description

Originally reported by @agingoldseco 

> we should bold “Text Box” and “Saved Styles” so they stand out better?

**Comment by miina** [comment]
@agingoldseco Since the note in the bug bash document was with a question mark, wanted to confirm if we should proceed with it.

**Comment by agingoldseco** [comment]
@miina Yes—question mark was cause I hadn't actually gotten to try it out yet, but I think it looks good and helps differentiate the small headers from the none / fill / highlight buttons. Do you agree?

<img width="362" alt="Screen Shot 2021-11-29 at 1 14 57 PM" src="https://user-images.githubusercontent.com/90645922/143921281-6a5c1e2b-0201-495c-ac27-3d03285ecbeb.png">

**Comment by miina** [comment]
Thanks, @agingoldseco, sounds good to me!

**Comment by csossi** [comment]
Verified in QA
