### ISSUE TITLE
Provide a quick link in the carousel to the first & last pages of a story

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9811]
## Feature Description

Originally reported by @BrittanyIRL 

> it would be nice to get a “first page” and “last page” button on the carousel to skip to the beginning or end.

**Comment by miina** [comment]
@agingoldseco / @gajasinski Tagging you as this seems to be a UX / Product decision.

**Comment by agingoldseco** [comment]
I like this idea, but def want to get all the spacing / button placement changes fully worked out first. At this moment, especially at the bottom of a small screen where I've had issues with arrows overlapping the buttons, I'm wary of adding any new options

**Comment by gajasinski** [comment]
Realistically, the story would have to have a good number of pages and/or your screen size is smaller where the current arrow implementation wouldn't allow you to scroll to the first or last page with one tap, yes?

**Comment by swissspidy** [comment]
Doesn't seem too bad having to tap on the arrow twice to get to the end of the carousel if on a small screen 🤷

**Comment by gajasinski** [comment]
I'm not keen to prioritize this ATM.
