### ISSUE TITLE
Video captions layer covering links

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9819]
## Bug Description

Miina just reported that the video captions layer makes all links on the page untappable because it covers most of the page (see screenshot below). Unfortunately we can't use `pointer-events: none` here because of the following CSS in AMP:

https://github.com/ampproject/amphtml/blob/b78e8781ff3976b3bff1ba881cf66dd2609b5c07/extensions/amp-story/1.0/amp-story.css#L351-L353

## Expected Behaviour

Links should still be tappable, as much as possible.

## Steps to Reproduce

1. Add video with captions
2. Add link to an element on the same page

## Screenshots

![Screenshot 2021-11-25 at 16 59 02](https://user-images.githubusercontent.com/841956/143475579-073f8948-8d90-4c17-b359-3629cf557139.png)

## Additional Context

- Plugin Version: 1.14.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

**Comment by csossi** [comment]
Verified in QA
