### ISSUE TITLE
Disable/Ignore Samsung & Opera mobile browsers font size settings for Web Stories

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#9821]
## Feature Description

A user on the support forum has identified an issue with Web Stories on Samsung & Opera mobile browsers when browser font size settings have been changed from the default.

This [article](https://www.samsung.com/za/support/mobile-devices/how-do-i-make-the-text-bigger-or-smaller-in-the-internet-app-on-my-samsung-galaxy-s5/) explains how these settings are changed in the Samsung browser.

**How it should look:** https://drive.google.com/drive/folders/15sPQGVTNA4IceetFYXNN7j0FR4xZw6L2
**How it looks with custom font settings:** https://drive.google.com/drive/folders/15sPQGVTNA4IceetFYXNN7j0FR4xZw6L2

Could we disable or ignore this feature for Web Stories when running in these browsers. This is only for the mobile version of these browsers and there is no impact on the desktop versions.

## Additional Context

**Related Support topic:** https://wordpress.org/support/topic/my-mobile-result-is-way-off-what-i-created-in-the-editor/

**Comment by swissspidy** [comment]
Context for the team:

Some help articles say that `text-size-adjust: none;` might help. In my testing it didn't have an effect.

AMP itself sets `text-size-adjust: 100%;` by default:

https://github.com/ampproject/amphtml/blob/56b609e6df76a513afdeb45a0de29171e50c2c62/css/ampdoc.css#L39-L44

It would be good to sync with the stories wg team to find out whether they have any experience with that.

cc @choumx
