### ISSUE TITLE
Error in portuguese translation in upload button.

### ISSUE THREAD

**Issue by rodrigofglima** [swissspidy/web-stories-wp#9852]
Hi! In 1.15 version, the Brazilian Portuguese have and error in button translate caption. 

https://imgur.com/a/kfl3VLy

The correct world its "**Inserir**". 

I don't know its is better place to report this, or its and error in Wordpress in general. 

Thanks in Advanced.

**Comment by swissspidy** [comment]
Hi there, thanks for your report.

I just fixed this particular translation.

In the future, if you find any oddities with the translations, you can [suggest improvements directly on WordPress.org](https://translate.wordpress.org/projects/wp-plugins/web-stories/dev/pt-br/default/). All you need is an account there.

**Comment by swissspidy** [comment]
Oh, and to get the updated translation, just go to Painel -> Atualizações in WordPress and update the translations there.

It might take a while until the updated translation is available there.
