### ISSUE TITLE
Media: tax query affects WP media library performance

### ISSUE THREAD

**Issue by dreamofabear** [swissspidy/web-stories-wp#9853]
## Bug Description

> The Web Stories plugin is causing a performance issue with the WordPress Media Library.  The issue is a tax query that's being added in the function `get_exclude_tax_query` in file `plugins/web-stories/includes/Media/Media_Source_Taxonomy.php`
> 
> This tax query is causing the underlying SQL query to be too slow and causing long delays with working in the media library.  This is most noticeable in the preprod environment due to lower database resources, but is slowing down the media library in production as well. 
> 
> We would like to have the plugin add a filter that would allow us to disable the addition of this tax query.  We tested changing the plugin directly to remove this tax query and that appears to resolve the issue.  There are three functions where we had to make code changes for this: `filter_ajax_query_attachments_args`, `filter_generated_media_attachments` and `filter_rest_generated_media_attachments`
> 
> We would need this filter to apply to all of these contexts.  

## Expected Behaviour

Media library performance is good.

## Steps to Reproduce

See above.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by dreamofabear** [comment]
Curious what the raw generated SQL is and if it could be tuned. 

Failing that, perhaps some opt-out option and alternative UX e.g. identifying items in the media library as an auto-generated poster etc.

**Comment by swissspidy** [comment]
This current way tax query is already the optimal and recommended way for implementing this kinda filtering in `WP_Query` that works on all WP sites.

The proposed filter is essentially an opt-out option and the most reasonable solution for larger sites like the one here.
