### ISSUE TITLE
Limit the number of revisions for stories

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9857]
## Feature Description

By default, an infinite number of revisions are kept in WordPress.

Since we store lots of data in `post_content` and `post_content_filtered`, that can quickly fill up the database.

We want to filter that number for now to something more reasonable, like `10`.

## Additional Context

* Add new method to `Story_Post_Type_Class`
* Filter `wp_{$post_type}_revisions_to_keep`
* If `$num` is already `0` or below `10`, return current `$num` unchanged. The number is already OK.
* Else, return `10` to limit number of revisions to keep.
* Potentially add a new database migration to delete excess revisions, like `wp_save_post_revision()` does.

**Comment by spacedmonkey** [comment]
> Potentially add a new database migration to delete excess revisions, like wp_save_post_revision() does.

Is this really needed? If you had say 100 stories, each of which had 20 revisions, with post meta, could mean 4k deletes on admin_init. It is really worth it? Not to mention, cache cleaning and any hooks on delete revisions.

**Comment by swissspidy** [comment]
We can do it without a migration for now. It's not critical.
