### ISSUE TITLE
AMP Sanitization: `MinifyHtml` Transformer causing issues

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9861]
## Bug Description

The new `MinifyHtml` transformer in the AMP PHP Toolbox causes issues with linewraps (https://github.com/ampproject/amp-toolbox-php/issues/427) and some special chars encoding (https://github.com/ampproject/amp-toolbox-php/issues/420)

## Expected Behaviour

No issues present

## Steps to Reproduce

See the two referenced issues above for some details.

## Screenshots

See https://github.com/ampproject/amp-toolbox-php/issues/427

## Additional Context

- Plugin Version: 1.15.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

**Comment by csossi** [comment]
Verified in QA
