### ISSUE TITLE
Highlight & Fill text editor option issues

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#9872]
## Bug Description

A user has pointed out in the support forums that there are issues with Highlight & Fill text editor options since updating to version 1.15.0. 

**Highlight option:**
This now renders differently since the update. See the screenshots of before 1.15.0 update and after the update from the user.
**Before:** https://onedrive.live.com/?authkey=%21AGJXeukq7slyiN0&cid=F3781633E408D2AC&id=F3781633E408D2AC%21155802&parId=F3781633E408D2AC%21155587&o=OneUp
**After:** https://onedrive.live.com/?authkey=%21AJv0NnjXVKZW%2DTk&cid=F3781633E408D2AC&id=F3781633E408D2AC%21155803&parId=F3781633E408D2AC%21155587&o=OneUp

I have been able to recreate this using both versions also. See results of both here: 
![image](https://user-images.githubusercontent.com/91896826/144410655-4deb5277-dcc4-477b-872a-f0bf2a3fb253.png)

The editor panel in the middle is larger since the update so not sure if this is related to that but it's clear that these are not consistent. Note that this issue only shows in the editor and once published looks as expected. 

**Fill option:**
When using the fill option for text, if you select a padding of 10px it used to put 10px of padding all around the text, now the editor sticks the text to the top of the box, as if padding-top was set to 0. This again is only while in the editor and is as expected once published.

It looks like any Fill textbox actually loses any bottom and top padding when double-clicking to edit.
So every time you edit a textbox with padding, you have to go and change the padding in the editor to revert.

## Expected Behaviour

Highlight should show as shown in the previous version screenshots and the fill option should apply the padding when selected.

## Steps to Reproduce

**Highlight option:**
- Add some text to your story. It helps to add a few rows like a list.
- From the design panel select the highlight option.

**Fill option:**
– Create a text box with Fill mode
– Add a padding of 10px
– Add some text
– Double Click the textbox to edit the text
=> All vertical padding is gone (but it still shows 10 in the settings)
– Change to 9px and then to 10px
=> It goes back to “normal” (even though the text has a weird top align instead of being centred)

## Screenshots

Provided above.

## Additional Context

**Related Support topic:**
https://wordpress.org/support/topic/highlight-text-box-style-issue-in-1-15/

- Plugin Version: 1.15.0

**Comment by miina** [comment]
@swissspidy I was doing some bisecting and looks like https://github.com/google/web-stories-wp/pull/9801 caused the issue.

I'm guessing perhaps the change [in this file](https://github.com/google/web-stories-wp/pull/9801/files#diff-16448c215bce2b2a56c688f2ccddc37bda9e5eb76b4ea493650c761aab9cfa57) might have caused it?

Let me know if you prefer I take a look at it myself.

**Comment by swissspidy** [comment]
Which file? The link doesn't work for me. Could you provide a file path or a link like `https://github.com/google/web-stories-wp/blob/afb924a118682df112ae048d689cdbe810d6656e/path/to/file`?

If you have time to take a look yourself, that would be great.

**Comment by miina** [comment]
Whoops, sorry, this file: https://github.com/google/web-stories-wp/blob/6f9f4c75bab405064bd8cba4a2cfa35e5f36b61b/packages/story-editor/src/elements/text/util.js

**Comment by csossi** [comment]
Verified in QA
