### ISSUE TITLE
Embeds: Add navigation controls for embedded stories (amp-story-player)

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9874]
## Feature Description

This originally came out of #3561 and was requested as a feature in `amp-story-player` itself in https://github.com/ampproject/amphtml/issues/29799.

The suggestion is to add forward/backward arrows next to the story player for users to navigate through the story (vs. having to tap on the story itself).

While this might not end up being implemented upstream, we could look into adding custom buttons ourselves using the provided JS API in `amp-story-player`.

It raises some questions about arrow styling and positioning though.

Also, it's not clear whether this is a common feature request or not, and whether it makes sense to implement.

## Alternatives Considered

* Recommend users to not embed stories using `amp-story-player` directly, but instead use singleton previews that open in a lightbox (#6894)

**Comment by swissspidy** [comment]
cc @choumx @gajasinski as this is one of the feature requests from NYP.

**Comment by gajasinski** [comment]
So i'm understanding correctly, the user is opening the web story on desktop and the current UX forces the user to use the curser to scroll to the sides and click to advance, correct?

**Comment by swissspidy** [comment]
No, this is when [_embedding_ a story in a blog post](https://blog.google/web-creators/embedding-web-stories-across-your-site/) using amp-story-player. Like this:

![Screenshot 2021-12-04 at 12 59 14](https://user-images.githubusercontent.com/841956/144708604-6b8d4aa1-769b-4f9b-8636-2592da16aee0.png)

The suggestion is to add some arrows there instead of having to tap to advance.

**Comment by gajasinski** [comment]
@swissspidy thanks for clarifying!

@aaskedall @agingoldseco - thoughts? This makes sense to me.

**Comment by swissspidy** [comment]
Also, in case it was missed in the ticket description: there is an open feature request for this [on the format side](https://github.com/ampproject/amphtml/issues/29799), in case we want to push for implementing that there instead.

**Comment by gajasinski** [comment]
+1 @swissspidy makes more sense for this to be universal

**Comment by agingoldseco** [comment]
Question—is there any part of the process of adding the story to a site that a user might be able to choose whether they want arrows or tap-to-advance? Stationary arrows on or next to a story would potentially get in the way of story graphics or not vibe next to other graphics/info on the site, maybe we could do a hover state? But I'm asking cause I could see us providing a few different styling options and allowing a user to choose for whatever interface they're applying it to.

**Comment by swissspidy** [comment]
It's not possible to turn off tap-to-advance. So adding arrows would be _in addition_ to that.

Since this is about embedded stories, we could position the arrows _outside_ of the player. In the same styling as when viewing a fullscreen story:

![Screenshot 2021-12-10 at 09 55 48](https://user-images.githubusercontent.com/841956/145546061-74de0384-3222-41e2-98a4-82fa150f6a85.png)

Then a site owner could always position them on top of the story if they are comfortable with that, or style them differently.

IIRC this feature request was made because they feel like it's not super clear to users that they have to tap on the embedded story to advance it.

It's not a problem of course when viewing the actual fullscreen story, because that one has buttons on desktop (and on mobile it's super obvious you have to tap, too).

But embedded stories in a blog post or so are often viewed on a desktop, where there are no arrows.

**Comment by andrew-askedall** [comment]
I think that could work, I also wonder if on mouseover we could show them on top of the story so the embeds width can be taken up solely by the content. Will ping our player team to see if they have considered this use case already.

**Comment by andrew-askedall** [comment]
Hey @swissspidy , I pinged @hongcatlover since she handles the UX of the player and wasn't sure how the eng alignment / storytime acceptance criteria interplay.

**Comment by swissspidy** [comment]
Similar feature request: https://wordpress.org/support/topic/replay-2/

The user wants to have forward/backward controls for the story player, as well as a replay button.
