### ISSUE TITLE
Video: Re-trimming a video for the second time not working

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9878]
## Bug Description
Trimming a video works well and re-trimming it once seemingly works as well but re-trimming the re-trimmed video for the second time doesn't seem to work as expected. The trimmer handles show incorrect value.

## Steps to Reproduce

1. Add a non-trimmed video.
2. Trim the video (e.g. from 15 seconds to 6 seconds) - works
3. Wait until trimming finishes and open the trimmer again - works
4. Now re-trim the video again (e.g. from 6 seconds to 2 seconds) - visibly seems to work
5. Open the trimmer again. The trimmer still shows 6 seconds as the length instead of 2 seconds. - incorrect value

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Just let us know if it's an issue with the media upload logic rather than the video trimming UI.

**Comment by miina** [comment]
> Just let us know if it's an issue with the media upload logic rather than the video trimming UI.

At this point, it looks like with trimming. Will let you know if that changes.
