### ISSUE TITLE
Custom Fonts: Allow inserting custom fonts via URL

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9880]
Note: The UX of this issue is still in progress and the feature might change a little bit
## Feature Description
Figma link to be added once ready
- [ ] Add the necessary input(s) to the Dashboard Settings for inserting custom font via URL
- [ ] Extract the font metrics and save the URL and relevant data about the URL (needs to be checked which library to use, see https://github.com/google/web-stories-wp/issues/4717#issuecomment-981943916)
- [ ] Display the custom fonts in a separate section in the Font Picker
- [ ] Allow removing fonts
- [ ] Consider invalid URLs

Note: This issue does NOT include any API work and assumes that all that part is already in place.

**Comment by miina** [comment]
Although this issue can't be completed before the API is ready, we could already do the following using dummy data before to make things quicker once the API is done:
- Implement the UX
- Implement extracting the font metrics utils (find the suitable library)
- Add a new section to the Font Picker using dummy URLs

**Comment by swissspidy** [comment]
Yes, a lot of this is not blocked by the API work at all.

**Comment by kkalarickal** [comment]
Tested this on https://stories-qa-wordpress-amp.pantheonsite.io/ running PR #9966 

Status: LGTM 👍 

Scenarios:
1. Confirmed experimental feature flag (on/off) ✔️ 
2. Confirmed success case for adding custom font via URL ✔️ 
3. Confirmed negative case of trying to add woff2 font or using a font URL that is behind CORS ✔️ 
4. Confirmed ability to use the said custom font inside the editor ✔️ 
5. Confirmed deleting font removes it from the available font list in editor ✔️

**Comment by kkalarickal** [comment]
@miina ... some things to note that might need future polish:

1. when I use the custom font in the editor, there is some weird flickering. I saw it when i changed color of the custom font.... like there is a temp font style applied and then the custom one. this is not consistently reproducible, but it only happened for the custom font.
2. when a custom font is applied to some text in the story, and then the custom font is deleted, the original text continues to show the deleted custom font even though the drop down no longer has it.

**Comment by swissspidy** [comment]
> when a custom font is applied to some text in the story, and then the custom font is deleted, the original text continues to show the deleted custom font even though the drop down no longer has it.

That is expected until we have some mechanism in place to notify users about deleted fonts. See #10014
