### ISSUE TITLE
Saved Template Wrong Keyboard Shortcut

### ISSUE THREAD

**Issue by delowardev** [swissspidy/web-stories-wp#9884]
## Bug Description

When a saved template is in focus, pressing on `Space` key does multiple jobs, it opens the delete modal and fires scroll event at the same time. It should do one job at a time (either it should scroll or handle the delete modal).

IMO pressing on `Delete/Backspace` makes more sense to open the delete modal since the entire template gets focused and pressing on `Space` should handle the scroll.

## Expected Behaviour

Pressing on `Space` button shouldn't fire multiple events at a time.

## Steps to Reproduce

1. Go to Saved templates
2. Create 10+ templates
3. Focus on a template using the keyboard.
4. Press on `Space` key

## Screenshots

https://user-images.githubusercontent.com/17360543/144630866-132a9292-0d19-4eaa-bf29-595a8cbfd04d.mov

## Additional Context

- Plugin Version: 1.16.0-alpha.0
- WordPress Version: 5.8.2
- Operating System: macOS Monterey (M1)
- Browser: Chrome

**Comment by BrittanyIRL** [comment]
Moving back to backlog since no active work has occurred on it since early dec.
