### ISSUE TITLE
Editor crashing due to `baseColor` usage in `SkeletonPage`

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9888]
## Bug Description

We received [an error report via the forums](https://wordpress.org/support/topic/the-editor-has-crashed-please-try-reloading-the-page-and-report-the-error/#post-15132130) with the following stack trace:

```
Error: An error occurred. See https://github.com/styled-components/polished/blob/main/src/internalHelpers/errors.md#7 for more information.
at SkeletonPage (https://MY-WEBSITE.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=1d1f606301213e85c081ee9e74f22ba4:175:455)
at div
at j (https://MY-WEBSITE.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=1d1f606301213e85c081ee9e74f22ba4:1:33997)
at https://MY-WEBSITE.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=1d1f606301213e85c081ee9e74f22ba4:234:3019258
at Reorderable (https://MY-WEBSITE.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=1d1f606301213e85c081ee9e74f22ba4:133:3602)
...
```

https://github.com/styled-components/polished/blob/main/src/internalHelpers/errors.md#7 says:

> Passed invalid arguments to rgba, please pass multiple numbers e.g. rgb(255, 205, 100, 0.75) or an object e.g. rgb({ red: 255, green: 205, blue: 100, alpha: 0.75 }).

`rgba()` is called in `generatePatternStyles()` here:

https://github.com/google/web-stories-wp/blob/b76635df44d0532f20de573675abf6b4549e96a2/packages/story-editor/src/components/footer/carousel/skeletonPage.js#L61-L77

So I suspect it's either a broken `baseColor` on the background element's resource causing this, or an incorrect background color on the background element itself.

## Expected Behaviour

No crash

## Steps to Reproduce

Unclear

## Additional Context

- Plugin Version: 1.15.0
- WordPress Version: 5.8
- Operating System: ?
- Browser: ?

**Comment by swissspidy** [comment]
More reports here: https://wordpress.org/support/topic/editor-crashed-and-cant-load/

**Comment by swissspidy** [comment]
```
TypeError: C.resource.baseColor.replace is not a function
    at SkeletonPage (https://example.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js:145:511)
    at div
```

**Comment by swissspidy** [comment]
cc @spacedmonkey

**Comment by spacedmonkey** [comment]
At a guess, I would say the migration from array / object to string failed / didn't happen for some reason. It might be related to the issue I saw in testing, where the check for is object was failing.

**Comment by swissspidy** [comment]
All the users so far reported that this crash happened randomly in the middle of story generation, for example after video optimization. That doesn't necessarily support that theory. But if it is really a reproducible issue, we might need to look into running that migration again.

One creator mentioned working on custom page templates, so maybe #9898 caused the issue; not sure.
