### ISSUE TITLE
Cannot change text color of text element

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9890]
## Bug Description

Whenever I want to change the text color of a text element, it won't let me. The color is immediately reset to black / the original color.

## Expected Behaviour

I should be able to change the text color

## Steps to Reproduce

1. Insert text element
2. Try to change color

## Screenshots

https://user-images.githubusercontent.com/841956/144714614-d7da5495-d73f-449c-b1b7-2183a5919d63.mov

## Additional Context

- Plugin Version: 1.16.0-alpha
- WordPress Version: 5.9 Beta 1
- Operating System: macOS
- Browser: Chrome

**Comment by miina** [comment]
Hm, not able to reproduce this in local nor in QA on `main` --  could you try again just in case on the current `main` to see if you can still reproduce it?

**Comment by swissspidy** [comment]
Weird, now I can't reproduce it anymore either 🤔 

Sorry for the false alarm!
