### ISSUE TITLE
Validation Issues in 1.15.0 version

### ISSUE THREAD

**Issue by panchammsinghh** [swissspidy/web-stories-wp#9896]
## Bug Description

Two days ago, I updated the web stories plugin to v1.15.0 now, i am seeing validation errors in amp tests.

1st error is - HTML Event attributes, aka 'on*', are not allowed in AMP. Instead use 'amp-bind'.
2nd error - Custom Javascript is not allowed

I downgrade to **v1.14.0**, and tested again, all errors are gone, everything was fine, but from yesterday, Editor is showing crash error, help me what to do now.

I am using WP Rocket as my cache plugin.

## Screenshots

![amp stories validation](https://user-images.githubusercontent.com/61957280/144827242-054d767a-aa1e-46cb-8cfc-fdac00ed97c1.png)

## Additional Context

- Plugin Version: 1.15.0
- WordPress Version:  5.8.2
- Operating System:
- Browser: Chrome

**Comment by swissspidy** [comment]
Hi there

Please not that we handle support question like yours via the [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/), not GitHub.

It looks like the Google Fonts optimization in WP Rocket is adding inline JavaScript to Web Stories, causing this invalidation.

I recommend disabling this optimization in WP Rocket and/or exempting any `web-stories/` URLs from it. You might also want to reach out to WP Rocket support to let them know about this incompatibility so they can fix this on their end.
