### ISSUE TITLE
Code Quality: use service container in `uninstall.php`

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#9901]
## Feature Description

Use injector / Service:get_service in uninstall.php, in the following lines. 

https://github.com/google/web-stories-wp/blob/99422064c5a6d7a8b81e220de1ee0e3805191c22/includes/uninstall.php#L186-L191

**Comment by swissspidy** [comment]
Some of these services might not be available in certain contexts, e.g. when uninstalling via WP-CLI. Would need some testing.
