### ISSUE TITLE
Flaky Karma test: `should navigate templates via keyboard`

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9912]
## Bug Description
The following Karma test is flaky:
`CUJ: Page Templates: Creator can Apply a Default Page Template Keyboard Navigation should navigate templates via keyboard`

[Example run](https://github.com/google/web-stories-wp/runs/4433714640?check_suite_focus=true#step:6:8235)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
@BrittanyIRL I assigned it to Prometheus automatically but started thinking that perhaps that would be for Pea pod instead?

LMK, either is fine by me!

**Comment by BrittanyIRL** [comment]
think we last worked on this, taking it from you!
