### ISSUE TITLE
Media Library: Reset state when losing focus

### ISSUE THREAD

**Issue by delowardev** [swissspidy/web-stories-wp#9913]
## Bug Description

If we open the media element dropdown menu from keyboard and then close it by pressing `Esc` key, the focus moves to the canvas but the media dropdown (3 dots) button keeps visible. ( See attached video )

Addition: pressing `Esc` doesn't reset the element `tabindex`, so when someone tries to refocus the media element, it doesn't start with the first element. ( See 2nd video )

## Expected Behaviour
Pressing on`Esc` key either should refocus the media element, or it shouldn't show the menu button when the focus gets moved to the canvas; plus it should reset the `tabindex`.

## Steps to Reproduce

1. Focus any media element
2. Press `Space` key
3. Press `Esc` key

## Screenshots

https://user-images.githubusercontent.com/17360543/144904883-59c130f3-0a40-4b66-9cd4-ca0768a5145e.mov

https://user-images.githubusercontent.com/17360543/144904924-c9190aa2-9e3e-444f-9fec-57841ab6c490.mov

## Additional Context

- Plugin Version: 1.16.0-alpha.0
- WordPress Version: 5.8.2
- Operating System: macOS Monterey (M1)
- Browser: Chrome

**Comment by swissspidy** [comment]
Nice find!

Sounds like we'd want to use `useFocusOut()` in `MediaElement` to reset the tabindex to -1 and call `setIsMenuOpen()`

**Comment by swissspidy** [comment]
@amovar18 since #10162 was refactored to only fix the crash, would you be up for creating a new PR for the focus fix?

**Comment by amovar18** [comment]
@swissspidy sure I would love to create a PR for this.

**Comment by miina** [comment]
The first part of it got fixed within #10607, I believe the second part (not resetting the tabIndex) is actually intentional currently. The user can navigate using the arrow keys to get back to the first item.

We could create a separate issue for it if the best practices are different, lmk and let's create one -- this would need to be changed everywhere in the code then since currently keeping the latest state of tabIndexes is intentional.

**Comment by swissspidy** [comment]
So it's intentional that when going somewhere else in the editor and coming back to the media library the tabindex is still on like the 7th element and not the first one again?

**Comment by miina** [comment]
At least that's what I thought!
I believe that's how the roving tab index util and also custom navigation handlers are implemented currently.
But perhaps it was always a bug, I just didn't know.

I can create a general issue for it if it's a bug -- we're using the same logic everywhere currently, in all library panes, in color picker, calendar, etc.

E.g. when I tab out of the library (or a group of colors in the color picker) and then click `Shift + Tab` to get back, I'd expect to jump back to where I was. If we'd reset the tab indexes when losing focus, I'd end up on the first element instead.

Thoughts?

**Comment by swissspidy** [comment]
Hmm I suppose that makes sense 🤔 

We can consult with a11y folks if this comes up again.
