### ISSUE TITLE
Allowing to add properties for integration with other CMS

### ISSUE THREAD

**Issue by amovar18** [swissspidy/web-stories-wp#9927]
## Feature Description
While trying to integrate core `story-editor` with other CMS I found that it is not necessary that every CMS will provide a `MediaModal` like WordPress does, there may be instances where we might need to pass down some props via `CMS-story-editor` which will allow invoking `MediaModal` of that CMS.
Some places that might need this:
https://github.com/google/web-stories-wp/blob/91d7271af6a7f17b42e0be4bbaef5332fecd7170/packages/story-editor/src/app/highlights/quickActions/useQuickActions.js#L187-L198
https://github.com/google/web-stories-wp/blob/76f20d3303a44ef5a4092dde4971acf55b2b7f77/packages/story-editor/src/components/form/media.js#L101-L127
https://github.com/google/web-stories-wp/blob/25d43b402e39f46de36ec4636a1893f8749b932e/packages/story-editor/src/components/library/panes/media/local/mediaPane.js#L297-L310
https://github.com/google/web-stories-wp/blob/25d43b402e39f46de36ec4636a1893f8749b932e/packages/story-editor/src/components/library/panes/media/local/mediaPane.js#L312-L324
https://github.com/google/web-stories-wp/blob/76f20d3303a44ef5a4092dde4971acf55b2b7f77/packages/story-editor/src/components/panels/design/captions/captions.js#L153-L172
https://github.com/google/web-stories-wp/blob/c210a3c9307a224ed800551c04df93e3b066a0ac/packages/story-editor/src/components/panels/shared/backgroundAudioPanelContent.js#L82-L94

**Comment by swissspidy** [comment]
Could you perhaps elaborate a little bit on how passing a custom `MediaUpload` component via the config doesn't help here and whit kind of props you would want to pass down?

In the `wp-story-editor` we have a custom `MediaUpload` component using `useMediaPicker` that opens the WP media modal, but I imagine that on another CMS this could invoke that system's media picker in any way possible.

**Comment by amovar18** [comment]
Yes but in my experience while working with other CMS (joomla) does not provide system's media picker (AFAIK). Searched other plugins for joomla too. Didnt find any that used a showed the use of system's media modal. So it would be nice to provide an support for that.
Props might be data-attributes like `data-bs-toggle` or `data-bs-target` that are targeted for Bootstrap modals. The `MediaUpload` component just uses the functions that are passed, incase of joomla the action of invoking a modal happens on the click of a button via these 2 attributes  `data-bs-toggle` and `data-bs-target` now these buttons are placed inside the core `story-editor`.

**Comment by swissspidy** [comment]
Bootstrap supports opening modals via JavaScript: https://getbootstrap.com/docs/5.0/components/modal/#via-javascript

Would that work?

**Comment by amovar18** [comment]
@swissspidy Yes that would work but only concern would be bootstrap needs to be installed as a library out of the box we dont get `bootstrap.Modal` the integrator would have to include the whole bootstrap library along with their version of the plugin.

**Comment by swissspidy** [comment]
I'm still not sure how good of an idea it is to allow injecting random attributes to support this use case 🤔 But seems like it's the most viable option. 

@sayedtaqui @choumx any thoughts on this?

**Comment by amovar18** [comment]
@swissspidy Due to some issue, `bootstrap.Modal` wasn't showing before when I checked, but now I see that it's globally available to use. So I was able to open the modal using `bootstrap.Modal`. So extra attributes aren't required.
