### ISSUE TITLE
Flaky Karma tests related to Media Fetching

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#9928]
## Bug Description
The following Karma tests are flaky:
`Media3pPane fetching Gallery navigation should handle pressing left when focused` ([Example run](https://github.com/google/web-stories-wp/runs/4441826329?check_suite_focus=true#step:6:14303))
`Media3pPane fetching Gallery navigation should handle pressing up`
`Media3pPane fetching Gallery navigation should handle pressing Home` [Example run](https://github.com/google/web-stories-wp/runs/4437212276?check_suite_focus=true#step:6:386)
`should handle pressing right when at the end of a row`

Looks like the Media is not always loaded by the time the tests start running.

Also seeing occasional failures with `should render the second media provider`:
`Error: Not ready: 40 != 20`

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
@BrittanyIRL Is this also something for Pea pod? I think you recently worked on the Media Fetching issues (https://github.com/google/web-stories-wp/pull/9780, not sure if it's related at all though). Thoughts?

I'm disabling the rest of the tests but not the `should render the second media provider` one since that seems to be failing less often and mostly passes one of the additional tries that's automatically being done.

**Comment by BrittanyIRL** [comment]
these are different but we'll take it!
