### ISSUE TITLE
Web Stories + AdSense support question

### ISSUE THREAD

**Issue by 0xSatwik** [swissspidy/web-stories-wp#9929]
It's not yet resolved. I tried troubleshooting, adsense forum but no proper answer

@airdropking1810 We already replied to you [on the WordPress.org support forums](https://wordpress.org/support/topic/adsense-ads-are-not-showing-3/) with all possible information. Let's keep the conversation there; we don't provide support on GitHub.

To recap:

* Your AdSense configuration looks correct
* It can take some time for ads to appear, be patient
* Try creating longer stories with more than 7 pages
* Try [AdSense troubleshooting](https://support.google.com/adsense/workflow/10383839?hl=en)
* If you still have issues with AdSense, reach out to [AdSense support](https://support.google.com/adsense/#topic=3373519)

_Originally posted by @swissspidy in https://github.com/google/web-stories-wp/issues/3448#issuecomment-987792469_

**Comment by swissspidy** [comment]
Hi there

**Please** continue the discussion on the WordPress.org support forums where you have already asked this question.

https://wordpress.org/support/topic/adsense-ads-are-not-showing-3/

We will continue to help you there.

We don't provide support here.
