### ISSUE TITLE
Text not adhering to line-height from version 1.15 onwards

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#9940]
## Bug Description

Text is not adhering to the set line-height from Web Stories version 1.15.0 onwards. This has been pointed out by a user of the plugin and confirmed with testing of my own. 

In the screenshots section you will see an image of versions 1.14 and 1.15.1 both using a 'Title 1' text box with a line-height value of 4 set.

## Expected Behaviour

Line height should display as seen in 1.14 screenshot. 

## Steps to Reproduce

1. While editing a story add a new text box to a page.
2. From the text options set a line-height value of 4.

## Screenshots

![WS-line-height](https://user-images.githubusercontent.com/91896826/145201980-efe191ff-e178-453d-83a3-258daca0fcca.png)

## Additional Context

This is the behaviour as of version 1.15.0.

**Comment by swissspidy** [comment]
@miina Perhaps also caused by #9801 and not missed by #9873?

**Comment by miina** [comment]
> Perhaps also caused by #9801 and not missed by #9873?

@swissspidy Actually in my testing it looks like #9873 introduced it 😞 Can't see it earlier -- I'll take a look.

**Comment by kkalarickal** [comment]
Confirmed on https://stories-qa-wordpress-amp.pantheonsite.io/ via PR #9942 that the text adheres to line height 

![image](https://user-images.githubusercontent.com/3719412/146451901-2e7bb9d1-0d0d-4aea-942a-6eef3778dad3.png)
