### ISSUE TITLE
Add integration to disable conditional featured images plugin

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9962]
## Feature Description

Some of our creators are reporting issues with the ["Conditionally display featured image on singular posts and pages"](https://wordpress.org/plugins/conditionally-display-featured-image-on-singular-pages/) plugin, which causes the featured image to be hidden / not saved properly.

To prevent this kind of confusion, we want to add an integration to disable it for the web-story post type using the `cybocfi_post_type` filter.

## Additional Context

See also https://github.com/cyrillbolliger/conditional-featured-image/issues/24

**Comment by cyrillbolliger** [comment]
Please use the `cybocfi_enabled_for_post_type` (available since 2.10.0) instead of `cybocfi_post_type` as the latter was deprecated.

See https://github.com/cyrillbolliger/conditional-featured-image/commit/63627a8b1b93675255819cc5bb348cf8b27d4662

**Comment by swissspidy** [comment]
@cyrillbolliger Merci! :)

**Comment by spacedmonkey** [comment]
@swissspidy What is being asked here? 

```
function cybocfi_limit_to_posts( $enabled, $post_type ) {
    if ( 'web-stories' === $post_type ) {
        return false;
    }

    return $enabled;
}
add_filter( 'cybocfi_enabled_for_post_type', 'cybocfi_limit_to_posts', 10, 2 );
```

**Comment by swissspidy** [comment]
Yes, this.
