### ISSUE TITLE
Floral Sticker causing AMP validation errors

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#9969]
## Bug Description

There is a particular image built into the Indoor Garden Oasis DIY Web Story template that is causing stories to fail AMP validation. The image can be seen highlighted in the screenshot attached below. When a story is published with this image then the following AMP validation errors are flagged:

- Invalid or missing doctype declaration. Should be '!doctype html'.
- The attribute 'public' may not appear in tag 'html !doctype'.
- The attribute 'system' may not appear in tag 'html !doctype'.

I have created 2 stories to test this where 'test-floral2' is published with no changes to the template and 'test-floral3' has been published after the image has been removed from all pages in the story. AMP validation results can be found below: 

**test-floral2:** https://search.google.com/test/amp/result?id=TOKQnjAsB4FD2Ssu7b9u4g
**test-floral3:** https://search.google.com/test/amp/result?id=iaLeMDp2OfTrqAEPqZqGjQ

**Related Support topic:** https://wordpress.org/support/topic/failing-amp-testing/

## Expected Behaviour

The story should pass AMP validation when using the default template.

## Steps to Reproduce

1. Create new story using the Indoor Garden Oasis DIY template.
2. Don't make any changes to the template and publish the story.

## Screenshots

![WS-IndoorGarden-Template](https://user-images.githubusercontent.com/91896826/145809575-9a29ea14-a3c2-44fb-8500-c49499e946d4.png)

**Comment by swissspidy** [comment]
Found the possible culprit in the upstream AMP PHP toolbox: https://github.com/ampproject/amp-toolbox-php/issues/441
