### ISSUE TITLE
Animations not working on the first page

### ISSUE THREAD

**Issue by freibergerb** [swissspidy/web-stories-wp#9987]
## Bug Description

It looks like animations aren't working on the first page of the stories. We've tried background animations and normal image animations.

Sorry if maybe this is something obvious but we couldn't yet found an answer.

## Expected Behaviour

Animations to work as they do on other pages.

## Steps to Reproduce

1. Add a new Web Story
2. On the first slide add an image as background
3. Go into design, animation, add pan right or pan left
4. Publish and view the story
5. Animation doesn't work either on the Preview or Web Story permalink

## Screenshots
![Web Stories 1st page animation issue 1 11](https://user-images.githubusercontent.com/59546527/145936865-7366bf5e-4c4a-4657-a026-5a3400efe8b3.png)
![Web Stories 1st page animation issue 1 15 1](https://user-images.githubusercontent.com/59546527/145936870-67b095d6-3856-456b-bd5b-f82e0094ab89.png)

These two examples are "raw" installations of WP and Web Stories. On our production environments we do have a lot of customisation on top so that's how we were checking if any of it was affecting first page animations.

## Additional Context

Dev env:
- Plugin Version: 1.14.0
- WordPress Version: 5.8
- Operating System: MacOS
- Browser: Chrome and FF

We've also tested WP 5.8 with Web Stories 1.11, 1.14 and 1.15.1. Dev environment built with [VIP Local Dev Environment](https://docs.wpvip.com/how-tos/local-development/use-the-vip-local-development-environment/)

Prod env:
- Plugin Version: 1.14.0
- WordPress Version: 5.8.2
- Operating System: MacOS
- Browser: Chrome and FF

Example of Web Story which has an animation on the first page but doesn't work:
https://www.news.com.au/web-stories/free/news-com-au/new-zealands-radical-plan-to-end-smoking

**Comment by swissspidy** [comment]
Thanks for your detailed report!

It looks like the Web Stories format has recently made a change to disable animations on the first page of a story for performance and UX reasons: https://github.com/ampproject/amphtml/pull/37135

We might need to disable the functionality to animate elements on the first page accordingly, or find a solution with the format team to re-enable this functionality somehow.

cc @choumx @gmajoulet

**Comment by dreamofabear** [comment]
Looks like this is just a stories format experiment for now:

> ...we have temporarily turned on the experiment that disables animations on the first page for now in order to check the performance improvements on all stories with animations as we test other improvements in parallel (...) until the beginning of January (if all goes well, no promises) but we might eventually think of a smarter / more long term approach with better UX.

**Comment by gmajoulet** [comment]
+1, we are testing various performance optimizations. No animations on cover page will likely become the default for transformed (optimized) documents, with the right set of opt-ins. If and when it launches, it'd be documented.

**Comment by freibergerb** [comment]
Thank you for the quick response! I see, makes sense from a performance point of view. We did hear from editors right away though. If it becomes a permanent change it would be good if it could be driven by a data attribute or something similar so on wp web stories we could introduce a filter to have control over it, potentially even something on the Settings menu.

**Comment by bmattb** [comment]
@gmajoulet Is there any update/ETA on these animations being re-enabled?

**Comment by mxbclang** [comment]
+1 @bmattb – We have some forum users asking about this. Thanks!

**Comment by gmajoulet** [comment]
I just noticed that WordPress generated Stories are "transformed" (ran through the optimizer). This combined with our implementation, even turning off our _no-animations-on-first-page-experiment_ would not re-enable animations for you.

We'll need to keep testing two alternative implementations to improve performance before we can re-enable animation for these specific documents.

**Comment by bmattb** [comment]
@swissspidy if we aren't going to allow first page animations, shouldn't we tell the user

**Comment by swissspidy** [comment]
Yes, see https://github.com/GoogleForCreators/web-stories-wp/issues/9987#issuecomment-993386722

**Comment by BrittanyIRL** [comment]
We could add a design issue to the checklist if a user adds animation to the first page to just let them know that animation on the first page won't work. 

This would alleviate confusion. WDYT @swissspidy @aaskedall ??

**Comment by BrittanyIRL** [comment]
Could also disable the animation input if it's the first page - allows for persisting if page order updates.

**Comment by BrittanyIRL** [comment]
Per discussion today in our design sync with @agingoldseco I whipped this up: 
<img width="367" alt="Screen Shot 2022-04-19 at 2 23 56 PM" src="https://user-images.githubusercontent.com/10720454/164104938-90f4cec3-eb29-4dfb-8227-4bbb559895f7.png">
<img width="365" alt="Screen Shot 2022-04-19 at 2 23 52 PM" src="https://user-images.githubusercontent.com/10720454/164104945-b559da87-0b8b-4fe4-8ddf-0f1c722d17f9.png">

So if you're on the first page, animation dropdown is disabled. If this wasn't historically the first page and you added an animation to it, then that animation is preserved but disabled. There's a note (I made the copy up it's not final) to clue the user into why it is disabled. 

Additionally, the play button next to the canvas for page 1 would be disabled. 

I think this does a good job of cluing the user in on why their animations aren't working as they might think they should be. 


The text box is borrowed from the color contrast warning and can easily be reused. Otherwise, it's just checking what page number is active in the canvas. 

Acceptance criteria should include new karma test. 

@swissspidy WDYT?

**Comment by swissspidy** [comment]
@BrittanyIRL This would be in addition to a checklist issue, correct?

Adding a checklist item + such a warning sounds good to me!

Happy to provide wording etc. as well.

I don't expect any animation change on the AMP side anytime soon, so implementing this now makes sense. It's been unaddressed for too long.

**Comment by gmajoulet** [comment]
I believe telling users why animations won't play on first page over an "AMP restriction" (do users even know what AMP is?) would be more useful.
Disabling the animations make the content show/load faster, and positively impacts all engagement metrics (bounce rate, time spent on story, progress within the story, less abandonment during Story load, ...), and [Core Web Vitals](https://web.dev/vitals/#overview) which improves SEO.

**Comment by swissspidy** [comment]
Yes, totally agree. The exact wording is still TBD and we'll definitely frame it around these types of metrics and PX.
